### ISSUE TITLE
Sync Button On after reboot

### ISSUE THREAD

**Issue by computerfreek274** [Aircoookie/WLED#100]
Is there a way to make the Sync button off after reboot or for it to remember the last state ? Sorry if this was already asked.

**Comment by Aircoookie** [comment]
Yes, you can go to the Sync settings and in "WLED Broadcast" you can change the options as you like. To completely disable the sync feature, just uncheck everything. I recommend leaving the receiving on, and turning "Send notification on direct change" off. After a reboot, those will be your default settings!

Thanks for your support by the way :)
