### ISSUE TITLE
Light sensor module

### ISSUE THREAD

**Issue by costads** [Aircoookie/WLED#1005]
Hi guys,

I read on another forum about a guy suggesting to use a light sensor module with digital output ( https://www.aliexpress.com/item/32571120284.html ) to make my LED strip turn on at night, and off during the day.

I have connected the module to D3, setup the macro T=2, and as such is working, however, the light sensor has to reach off/on (turn light off / turn light on)  before it will turn off the light, and again off/on to turn it on again.

Is it not possible to make it work like I want to somehow?

**Comment by Aircoookie** [comment]
Hi!
Please do not post the same both to issues and the forum. I replied to you there :)

**Comment by costads** [comment]
Sorry, didn't see you had the forum untill today :)
