### ISSUE TITLE
Okay to sell products that use wled to drive the leds?

### ISSUE THREAD

**Issue by ikrowni** [Aircoookie/WLED#1006]
Hello i wanted to start selling some products online that i make using the 3d printer with wled running the leds. Is this ok? Just wanted to confirm before stepping on any toes

**Comment by Aircoookie** [comment]
Hi, as per the MIT license of WLED, of course that is permitted :) It would be nice if you could mention WLED in the description, package, or manual though. Thank you!

**Comment by ikrowni** [comment]
Well thank you very much I will surely mention wled in the description.
