### ISSUE TITLE
WLED Alexa Device, RGBWW SK6812, white channel problem

### ISSUE THREAD

**Issue by TechnoHoschi** [Aircoookie/WLED#1012]
Hello,

I control my SK6812 RGBWW using the Alexa device. red, green, pink, everything works perfectly. however, if I switch to white once via Alexa, the following colors are shown with too high white channel. Only after I manually set the white channel in the web interface to 0, the colors fits again. However, only until the next time Alexa is switched to white.

I use version 0.10.1 on an ESP32, tests on an 8266 were identical. Version 0.9.1 and earlier work correctly.

regards

michael

**Comment by Aircoookie** [comment]
Hi,

thank you for the report!
Indeed this is the case, the white channel is not reset to 0 when selecting non-white. Will fix!

**Comment by TechnoHoschi** [comment]
Great,

thank you.

**Comment by Aircoookie** [comment]
Done!
