### ISSUE TITLE
a number shown next to the slider for effects like bpm

### ISSUE THREAD

**Issue by Th0mie** [Aircoookie/WLED#1015]
When I use the BPM effect it is hard to sync it to music because all you have is a slider that isn't showing a value.

Would it be possible to show a value next to the slider so you can more accurate controll the speed?
The best solution for BPM would be a field to insert the speed.

![screenshot](https://user-images.githubusercontent.com/67544159/85946788-31f24900-b947-11ea-8fac-8b664398282e.jpg)

**Comment by Aircoookie** [comment]
This would be helpful for a handful of effects! Will add it soon!

**Comment by Aircoookie** [comment]
Added in 0.14, available as release soon :)
