### ISSUE TITLE
Ucs 1903 Unterstützung 

### ISSUE THREAD

**Issue by Speeder001** [Aircoookie/WLED#1029]
Gib es die Möglichkeit LEDs mit ucs1903  Chip zu benutzen?
Wenn ja welche?

**Comment by Aircoookie** [comment]
Hi, soweit ich weiß ist der UCS1903 protokollkompatibel zu den WS2812b, es sollte also jedes LED Produkt, das auf diesem Chip basiert WLED-kompatibel sein.
