### ISSUE TITLE
mdns service type

### ISSUE THREAD

**Issue by raymiec** [Aircoookie/WLED#103]
Can you change  MDNS.addService("http", "tcp", 80);   to MDNS.addService("wled", "tcp", 80); 

Didn't realise this was actually in it already, couldn't discover with android NDP,

Don't think there would be any issues changing?

Changing would make it easier to discover from android and other devices if we are specifically looking for it, http as a service type will return all services on the network with service type http.

I can't think of any other way to just return wled devices when discovering on the network.

Thanks. 

Parsing the name is unreliable.

**Comment by Aircoookie** [comment]
Good suggestion!
Today I will finally release 0.8.3. mDNS will then advertise _http._tcp as well as _wled._tcp.
I ran into the same issue when writing the app, my workaround was to send an API call and see if the response is valid, but I too realized it would be way easier to have a separate service type for WLED!

**Comment by raymiec** [comment]
Excellent, i can fire an android app on the play store to will let you list and switch between devices.?

**Comment by Aircoookie** [comment]
Sure! :) (Although my app https://play.google.com/store/apps/details?id=com.aircoookie.WLED pretty much does the same thing)

**Comment by raymiec** [comment]
Haha it does so I never even knew you released one!   I have a few things that could be added to yours. I also have accounts / roles / permissions etc, i.e kids account can only control bedroom. You could also use it for premium features etc. That side of things does require an active internet connection / or host server on pi etc.
