### ISSUE TITLE
WLED on Wemos D1 Mini losing WiFi

### ISSUE THREAD

**Issue by iansime** [Aircoookie/WLED#1036]
I have loaded the latest WLED binary onto a Wemos D1 Mini and connected it to my home WiFi. I am able to connect to the board from my Android phone (WiFi) or Desktop PC (wired) but soon after the WiFi drops out for a while then eventually comes back.

I put a port scanner on my network and I can see Port 80 regularly not responding, even though th PING to the board never drops.

I tried loading the previous binary (using ESPHome-Flasher-1.2.0-windows-x64.exe) and upgrading to the newest version from there but no change in behaviour.

As a last step I uploaded a sample sketch to the board (simple web server) and that never drops the WiFi connection.

Any tips or troubleshooting steps I can follow?

**Comment by JohCo-hassio** [comment]
I also have version 0.10.0 for some time now
And he indeed loses his connection after some time with, for example, Home assistant. 
This is simply accessible via the Wled app,

**Comment by iansime** [comment]
I have just installed "Sound Reactive WLED Version 0.10.1" as a comparison and so far that seems rock solid.
Not a single connection loss so far after an hour or so of solid use.

**Comment by gastonMM** [comment]
where do you download version 0.10.1?

**Comment by iansime** [comment]
https://github.com/atuline/WLED/releases/tag/0.10.1

**Comment by pbolduc** [comment]
Is this a duplicate of #1025 ?
