### ISSUE TITLE
Wled won’t work with xlights

### ISSUE THREAD

**Issue by wvpt** [Aircoookie/WLED#1040]
I am using xlights to create a show. I have 2 espixnodes working properly through xlights. I can ping wled, I can log into wled through browser and control it. When I am running my show through FPP wled shows message that it is getting sign through E1.31. I recently just upgraded wled to newest release. Can anyone guide me to trouble shooting?

Problem: pixels connected to wled don’t light while FPP is playing show

**Comment by huggy-d1** [comment]
When you updated the firmware, I suspect you might need to toggle the E1.31 setting (off->on, or ON->OFF->ON) to activate E1.31 properly.
Also, if you have unused protocols enabled, go ahead and disable them.  Is it possible you can install firmware 0.10.1 for your devices?  Is that the "newest" release you mentioned?  If not, try that.
If 0.10.1 is installed and it is not working, try saving the current configuration (settings, presets, and so on), then use an esp firmware tool to completely erase the firmware on the esp.  Then install WLED from scratch and restore the saved settings (which you may have done by screenshots of WLED configuration settings).
