### ISSUE TITLE
WLED BULID

### ISSUE THREAD

**Issue by kevinhuihui** [Aircoookie/WLED#1042]
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)
**### Hi Aircoookie!
when i was found this wonderful and amazing source, i was shocked!
what a great WLED!   it's lighted my life!**

_i really really put my myself into this project! find and dig...._

also after i modified my personal effects wants add to WLED,(LATER im gonna to post...) i met a problem stoppped me while buliding(im using vscode and Platform IO(PIO EXTENSION) files..... lots of warnings... could you pls give me some suggestions?

also i tried bulid in arduino IDE, many times , it works but...u know...speed took very long(here also a problem met in Arduino IDE while buliding...wants to bulid sucess except delete “arduino” folder from (WLED-0.10.0\WLED-0.10.0\wled00\src\dependencies\**arduino**）im not sure whether u know or not?

any suggetsions about my question i appreciate it!

thanks! great day!

> Such as following(from vs code):

Compiling .pio\build\nodemcuv2\src\alexa.cpp.o
Compiling .pio\build\nodemcuv2\src\blynk.cpp.o
Compiling .pio\build\nodemcuv2\src\button.cpp.o
Compiling .pio\build\nodemcuv2\src\colors.cpp.o
In file included from src\fcn_declare.h:79:0,
                 from src\wled.h:84,
                 from src\alexa.cpp:1:
src\FX.h:41:0: warning: "MIN" redefined [enabled by default]
 #define MIN(a,b) ((a)<(b)?(a):(b))
 ^
In file included from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/fastled_esp8266.h:5:0,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms.h:34,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/FastLED.h:52,
                 from src\FX.h:34,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\alexa.cpp:1:
C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_block_esp8266.h:8:0: note: this is the location of the previous definition
 #define MIN(X,Y) (((X)<(Y)) ? (X):(Y))
 ^
In file included from src\fcn_declare.h:79:0,
                 from src\wled.h:84,
                 from src\blynk.cpp:1:
src\FX.h:41:0: warning: "MIN" redefined [enabled by default]
 #define MIN(a,b) ((a)<(b)?(a):(b))
 ^
In file included from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/fastled_esp8266.h:5:0,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms.h:34,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/FastLED.h:52,
                 from src\FX.h:34,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\blynk.cpp:1:
C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_block_esp8266.h:8:0: note: this is the location of the previous definition
 #define MIN(X,Y) (((X)<(Y)) ? (X):(Y))
 ^
In file included from src\fcn_declare.h:79:0,
                 from src\wled.h:84,
                 from src\button.cpp:1:
src\FX.h:41:0: warning: "MIN" redefined [enabled by default]
 #define MIN(a,b) ((a)<(b)?(a):(b))
 ^
In file included from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/fastled_esp8266.h:5:0,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms.h:34,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/FastLED.h:52,
                 from src\FX.h:34,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\button.cpp:1:
C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_block_esp8266.h:8:0: note: this is the location of the previous definition
 #define MIN(X,Y) (((X)<(Y)) ? (X):(Y))
 ^
In file included from src\fcn_declare.h:79:0,
                 from src\wled.h:84,
                 from src\colors.cpp:1:
src\FX.h:41:0: warning: "MIN" redefined [enabled by default]
 #define MIN(a,b) ((a)<(b)?(a):(b))
 ^
In file included from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/fastled_esp8266.h:5:0,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/platforms.h:34,
                 from C:\Users\user\Documents\Arduino\libraries\FastLED/FastLED.h:52,
                 from src\FX.h:34,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\colors.cpp:1:
C:\Users\user\Documents\Arduino\libraries\FastLED/platforms/esp/8266/clockless_block_esp8266.h:8:0: note: this is the location of the previous definition
 #define MIN(X,Y) (((X)<(Y)) ? (X):(Y))
 ^
In file included from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/LEAmDNS.h:108:0,
                 from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/ESP8266mDNS.h:46,
                 from src\wled.h:43,
                 from src\blynk.cpp:1:
C:\Users\user\Documents\Arduino\libraries\Adafruit_CC3000_Library\utility/debug.h:28:22: error: section 
attribute not allowed for 'prog_char'
 typedef char PROGMEM prog_char;
                      ^
In file included from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/LEAmDNS.h:108:0,
                 from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/ESP8266mDNS.h:46,
                 from src\wled.h:43,
                 from src\alexa.cpp:1:
C:\Users\user\Documents\Arduino\libraries\Adafruit_CC3000_Library\utility/debug.h:28:22: error: section 
attribute not allowed for 'prog_char'
 typedef char PROGMEM prog_char;
                      ^
In file included from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/LEAmDNS.h:108:0,
                 from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/ESP8266mDNS.h:46,
                 from src\wled.h:43,
                 from src\button.cpp:1:
C:\Users\user\Documents\Arduino\libraries\Adafruit_CC3000_Library\utility/debug.h:28:22: error: section 
attribute not allowed for 'prog_char'
 typedef char PROGMEM prog_char;
                      ^
In file included from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/LEAmDNS.h:108:0,
                 from C:\Users\user\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266mDNS\src/ESP8266mDNS.h:46,
                 from src\wled.h:43,
                 from src\colors.cpp:1:
C:\Users\user\Documents\Arduino\libraries\Adafruit_CC3000_Library\utility/debug.h:28:22: error: section 
attribute not allowed for 'prog_char'
 typedef char PROGMEM prog_char;
                      ^
In file included from src\src/dependencies/espalexa/Espalexa.h:60:0,
                 from src\wled.h:73,
                 from src\blynk.cpp:1:
src\src/dependencies/espalexa/EspalexaDevice.h:7:15: warning: 'typedef' was ignored in this declaration 
[enabled by default]
 typedef class EspalexaDevice;
               ^
In file included from src\wled.h:73:0,
                 from src\blynk.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::typeString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:102:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::modelidString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:114:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
In file included from src\src/dependencies/espalexa/Espalexa.h:60:0,
                 from src\wled.h:73,
                 from src\alexa.cpp:1:
src\src/dependencies/espalexa/EspalexaDevice.h:7:15: warning: 'typedef' was ignored in this declaration 
[enabled by default]
 typedef class EspalexaDevice;
               ^
In file included from src\wled.h:73:0,
                 from src\blynk.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In destructor 'Espalexa::~Espalexa()':
src\src/dependencies/espalexa/Espalexa.h:585:22: warning: deleting array '((Espalexa*)this)->Espalexa::devices' [enabled by default]
   ~Espalexa(){delete devices;} //note: Espalexa is NOT meant to be destructed
                      ^
In file included from src\wled.h:73:0,
                 from src\alexa.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::typeString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:102:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
In file included from src\src/dependencies/espalexa/Espalexa.h:60:0,
                 from src\wled.h:73,
                 from src\button.cpp:1:
src\src/dependencies/espalexa/EspalexaDevice.h:7:15: warning: 'typedef' was ignored in this declaration 
[enabled by default]
 typedef class EspalexaDevice;
               ^
In file included from src\src/dependencies/espalexa/Espalexa.h:60:0,
                 from src\wled.h:73,
                 from src\colors.cpp:1:
src\src/dependencies/espalexa/EspalexaDevice.h:7:15: warning: 'typedef' was ignored in this declaration 
[enabled by default]
 typedef class EspalexaDevice;
               ^
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::modelidString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:114:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
In file included from src\wled.h:81:0,
                 from src\blynk.cpp:1:
src\src/dependencies/json/AsyncJson-v6.h: In member function 'virtual void AsyncCallbackJsonWebHandler::handleBody(AsyncWebServerRequest*, uint8_t*, size_t, size_t, size_t)':
src\src/dependencies/json/AsyncJson-v6.h:143:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (total > 0 && request->_tempObject == NULL && total < _maxContentLength) {
                                                                ^
In file included from src\wled.h:73:0,
                 from src\colors.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::typeString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:102:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::modelidString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:114:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
In file included from src\wled.h:73:0,
                 from src\button.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::typeString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:102:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
src\src/dependencies/espalexa/Espalexa.h: In member function 'String Espalexa::modelidString(EspalexaDeviceType)':
src\src/dependencies/espalexa/Espalexa.h:114:12: warning: enumeration value 'onoff' not handled in switch [-Wswitch]
     switch (t)
            ^
In file included from src\wled.h:73:0,
                 from src\alexa.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In destructor 'Espalexa::~Espalexa()':
src\src/dependencies/espalexa/Espalexa.h:585:22: warning: deleting array '((Espalexa*)this)->Espalexa::devices' [enabled by default]
   ~Espalexa(){delete devices;} //note: Espalexa is NOT meant to be destructed
                      ^
In file included from src\wled.h:73:0,
                 from src\button.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In destructor 'Espalexa::~Espalexa()':
src\src/dependencies/espalexa/Espalexa.h:585:22: warning: deleting array '((Espalexa*)this)->Espalexa::devices' [enabled by default]
   ~Espalexa(){delete devices;} //note: Espalexa is NOT meant to be destructed
                      ^
In file included from src\wled.h:73:0,
                 from src\colors.cpp:1:
src\src/dependencies/espalexa/Espalexa.h: In destructor 'Espalexa::~Espalexa()':
src\src/dependencies/espalexa/Espalexa.h:585:22: warning: deleting array '((Espalexa*)this)->Espalexa::devices' [enabled by default]
   ~Espalexa(){delete devices;} //note: Espalexa is NOT meant to be destructed
                      ^
In file included from src\FX.h:30:0,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\blynk.cpp:1:
src\NpbWrapper.h: In constructor 'NeoPixelWrapper::NeoPixelWrapper()':
src\NpbWrapper.h:322:53: warning: 'NeoPixelWrapper::_pGrbw' will be initialized after [-Wreorder]       
   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;
                                                     ^
src\NpbWrapper.h:318:16: warning:   'NeoPixelType NeoPixelWrapper::_type' [-Wreorder]
   NeoPixelType _type;
                ^
src\NpbWrapper.h:153:3: warning:   when initialized here [-Wreorder]
   NeoPixelWrapper() :
   ^
In file included from src\wled.h:81:0,
                 from src\alexa.cpp:1:
src\src/dependencies/json/AsyncJson-v6.h: In member function 'virtual void AsyncCallbackJsonWebHandler::handleBody(AsyncWebServerRequest*, uint8_t*, size_t, size_t, size_t)':
src\src/dependencies/json/AsyncJson-v6.h:143:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (total > 0 && request->_tempObject == NULL && total < _maxContentLength) {
                                                                ^
In file included from src\wled.h:81:0,
                 from src\colors.cpp:1:
src\src/dependencies/json/AsyncJson-v6.h: In member function 'virtual void AsyncCallbackJsonWebHandler::handleBody(AsyncWebServerRequest*, uint8_t*, size_t, size_t, size_t)':
src\src/dependencies/json/AsyncJson-v6.h:143:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (total > 0 && request->_tempObject == NULL && total < _maxContentLength) {
                                                                ^
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':    
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'uint8_t* NeoPixelWrapper::GetPixels()':
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::cleanup()':
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
In file included from src\wled.h:81:0,
                 from src\button.cpp:1:
src\src/dependencies/json/AsyncJson-v6.h: In member function 'virtual void AsyncCallbackJsonWebHandler::handleBody(AsyncWebServerRequest*, uint8_t*, size_t, size_t, size_t)':
src\src/dependencies/json/AsyncJson-v6.h:143:64: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (total > 0 && request->_tempObject == NULL && total < _maxContentLength) {
                                                                ^
In file included from src\FX.h:30:0,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\alexa.cpp:1:
src\NpbWrapper.h: In constructor 'NeoPixelWrapper::NeoPixelWrapper()':
src\NpbWrapper.h:322:53: warning: 'NeoPixelWrapper::_pGrbw' will be initialized after [-Wreorder]       
   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;
                                                     ^
src\NpbWrapper.h:318:16: warning:   'NeoPixelType NeoPixelWrapper::_type' [-Wreorder]
   NeoPixelType _type;
                ^
src\NpbWrapper.h:153:3: warning:   when initialized here [-Wreorder]
   NeoPixelWrapper() :
   ^
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'uint8_t* NeoPixelWrapper::GetPixels()':
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::cleanup()':
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
In file included from src\FX.h:30:0,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\colors.cpp:1:
src\NpbWrapper.h: In constructor 'NeoPixelWrapper::NeoPixelWrapper()':
src\NpbWrapper.h:322:53: warning: 'NeoPixelWrapper::_pGrbw' will be initialized after [-Wreorder]       
   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;
                                                     ^
src\NpbWrapper.h:318:16: warning:   'NeoPixelType NeoPixelWrapper::_type' [-Wreorder]
   NeoPixelType _type;
                ^
src\NpbWrapper.h:153:3: warning:   when initialized here [-Wreorder]
   NeoPixelWrapper() :
   ^
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
In file included from src\FX.h:30:0,
                 from src\fcn_declare.h:79,
                 from src\wled.h:84,
                 from src\button.cpp:1:
src\NpbWrapper.h: In constructor 'NeoPixelWrapper::NeoPixelWrapper()':
src\NpbWrapper.h:322:53: warning: 'NeoPixelWrapper::_pGrbw' will be initialized after [-Wreorder]       
   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;
                                                     ^
src\NpbWrapper.h:318:16: warning:   'NeoPixelType NeoPixelWrapper::_type' [-Wreorder]
   NeoPixelType _type;
                ^
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h:153:3: warning:   when initialized here [-Wreorder]
   NeoPixelWrapper() :
   ^
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':        
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
*** [.pio\build\nodemcuv2\src\blynk.cpp.o] Error 1
src\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':    
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'uint8_t* NeoPixelWrapper::GetPixels()':
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::cleanup()':
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:172:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type)
            ^
src\NpbWrapper.h:262:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:271:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:290:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':    
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
*** [.pio\build\nodemcuv2\src\alexa.cpp.o] Error 1
src\NpbWrapper.h:300:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'uint8_t* NeoPixelWrapper::GetPixels()':
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:309:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch] 
src\NpbWrapper.h: In member function 'void NeoPixelWrapper::cleanup()':
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_None' not handled in switch [-Wswitch]
     switch (_type) {
            ^
src\NpbWrapper.h:326:12: warning: enumeration value 'NeoPixelType_End' not handled in switch [-Wswitch]
*** [.pio\build\nodemcuv2\src\colors.cpp.o] Error 1
*** [.pio\build\nodemcuv2\src\button.cpp.o] Error 1
===================================== [FAILED] Took 14.15 seconds =====================================

**Comment by Aircoookie** [comment]
Hi,
I am very happy that you like WLED!
In Arduino IDE, for me a full build typically takes 90 seconds while re-building with only a few bits changed takes about 12 seconds. This might vary depending on your system of course.
About the error in PIO, it seems to bbe referencing the Adafruit CC3000 library, but that is not actually a dependency of WLED as far as I know. What are the modifications you made and did the unmodified version compile?

**Comment by huggy-d1** [comment]
Were you ever able to compile WLED?  Then you made changes and suddenly you cannot?   Uncomment (or use git to go back in time) chunks of added code to identify what new library is causing so much conflict.

**Comment by kevinhuihui** [comment]
> Hi,
> I am very happy that you like WLED!
> In Arduino IDE, for me a full build typically takes 90 seconds while re-building with only a few bits changed takes about 12 seconds. This might vary depending on your system of course.
> About the error in PIO, it seems to bbe referencing the Adafruit CC3000 library, but that is not actually a dependency of WLED as far as I know. What are the modifications you made and did the unmodified version compile?

> Very thanks for ur response! 

i've found conflict which is ur methioned....i installed that library long long time ago.. when i was compiling i selected use arduino library as reference in PIO, so casued this problem.... but now! see below... hhah... life is starting...

Creating BIN file ".pio\build\nodemcuv2\firmware.bin" using ".pio\build\nodemcuv2\firmware.elf"
=================================== [SUCCESS] Took 176.46 seconds ===================================

Environment            Status    Duration
---------------------  --------  ------------
nodemcuv2              SUCCESS   00:02:56.460
esp01                  IGNORED
esp01_1m_ota           IGNORED
esp01_1m_full          IGNORED
esp07                  IGNORED
d1_mini                IGNORED
heltec_wifi_kit_8      IGNORED
h803wf                 IGNORED
esp32dev               IGNORED
esp8285_4CH_MagicHome  IGNORED
esp8285_4CH_H801       IGNORED
esp8285_5CH_H801       IGNORED
d1_mini_5CH_Shojo_PCB  IGNORED
d1_mini_debug          IGNORED
d1_mini_ota            IGNORED
custom_LEDPIN_4        IGNORED
custom_LEDPIN_16       IGNORED
custom_APA102          IGNORED
custom_WS2801          IGNORED
custom32_LEDPIN_16     IGNORED
wemos_shield_esp32     IGNORED
m5atom                 IGNORED
travis_esp8266         IGNORED
travis_esp32           IGNORED
==================================== 1 succeeded in 00:02:56.460 ====================================

**Comment by kevinhuihui** [comment]
> Were you ever able to compile WLED? Then you made changes and suddenly you cannot? Uncomment (or use git to go back in time) chunks of added code to identify what new library is causing so much conflict.

Thanks a lot! have a great day!

**Comment by toto79** [comment]
you can give https://gitpod.io#https://github.com/Aircoookie/WLED/tree/master an try

run 1st: pip3 install -U platformio
run 2nd: platformio run -e <env:type> , e.g. platformio run -e d1_mini or platformio run -e esp01_1m_full (as defined in platformio.ini)

find your firmware.bin file in folder .pio/build/<env:type>, save as... and flash to your esp
good summary you'll find also at https://tasmota.github.io/docs/Gitpod/
