### ISSUE TITLE
request for pin change and text display .

### ISSUE THREAD

**Issue by loverboyritesh** [Aircoookie/WLED#1045]
First of all many thanks Aircoookie for this awesome Project ....its ultimate and All in one project .
Although OTA programming and web updates are possible this project has eliminated my task or re-uploading different codes for different tasks like some times you need to use simple   effects  other times you need to connect to Artnet/E131 etc . this is just one answer to all . Very great project ....

Here i wish for small additions ... i request for 
1: custom Data pin  
to be able to change data out pin in the settings page just like the way we could change the number of leds ....
this is not a big issue but some times have no physical access to the ESP, and you want to try other codes .. yes its possible to change it in the source and recompile the binary ... but just wishing if this can be added in the future updates ...

2:Text for matrix 
this is not a new request already many like DrMarlin have asked about it //
but still it would be nice if we could control a matrix to display a desired text //
i know its possible through Artnet thru Jinx! and other ...
but wonder if  added this and controlled thru the android/ iphone WLED app or in the web interface / to display a customized text ..
text customization like colour plain or multi with effects like rainbow or plasma and background change and if possible Fonts // and as esp could connect to NTP servers a way to display time / date etc 

and a few ways to decide the matrix type like horizontal/rows vertical columns snake type or progressive , matrix dimensions and the first led position TL , TR ,BL, BR etc
here i am talking about simple matrix made of neopixel strips like ws2811/2812 single continuous strip made in to matrix .. working with matrix of matrices will yet be a different story means like tile matrix of 8x8 small matrices /////

well it would  be great and i would be very thankful if you could add these features in the coming updates ...... Thanks one again for your great work ....

**Comment by Aircoookie** [comment]
Hi! I'm very happy that you like WLED!
The custom data pin as well as multiple LED output pins is the most requested feature by far, so it will get implemented at some point soon.
I also hope to support matrices soon (in fact I have already started building my own one!), so stay tuned for that!
For now I am going to close this issue since the features you'd like have already been requested. But feel free to reply if you have more ideas! I am very grateful for your kind words :)
