### ISSUE TITLE
Very good with presets after the esp reboot

### ISSUE THREAD

**Issue by karen8000** [Aircoookie/WLED#1047]
Good afternoon friend 🙃😉I ask for a sling for my English 

Very does not swell the mode of saved preset, namely all saved time and wicket of presets but after the reboot esp8266 01s with a memory of 4mb all have to a new tune. Even if the presets active button 🔳 gpi0 does not work 😔 until you turn off the presets. 
I would like to see the function of blinking to the rhythm of the song if it is possible to realize the 🙃

WLED is a great substitute for Chinese controllers who are forced to use applications and here everything with the web server is very coo.

**Comment by Aircoookie** [comment]
Hi, awesome that you like WLED!

I do not understand the issue clearly, sorry. Are your saved presets gone
after a reboot? ESP8266 01s usually only have 1MB of memory, you might have
more luck using a binary with `1m` in the name
For sound reactivity, check out
https://github.com/atuline/WLED

**Comment by karen8000** [comment]
Friend, I mean, auto scrolling presets and immeno settings after the reboot with
A esp 01s I have with 4mb memory firmware stands for 4mb full. 


- [ 

> Привет, классно, что тебе нравится WLED! Я не понимаю вопроса ясно, извините. Ваши сохраненные пресеты исчезли после перезагрузки? ESP8266 01s обычно имеют только 1 Мбайт памяти, вы можете иметь больше удачи , используя двоичный файл с `1m` во имя Для звука реактивностью, проверьте https://github.com/atuline/WLED

Friend, I mean, auto scrolling presets and immeno settings after the reboot with
A esp 01s I have with 4mb memory firmware stands for 4mb full. 


- [ 
![Screenshot_20200804_150339](https://user-images.githubusercontent.com/40894373/89292105-75d21f80-d664-11ea-8c9b-1fca81282a34.jpg)
