### ISSUE TITLE
Can you make custom presets on a NodeMCU?

### ISSUE THREAD

**Issue by ForbiddenMonkey** [Aircoookie/WLED#1051]
Hey all :)

I really would love an effect thats got ~5 led moving along in a rainbow type pattern.
I love the way "pride 2015" looks at the beginning of the effect when its ~5 leds moving along but after a few minutes the whole effect changes to different patterns longer patterns.

I could only find [this](https://github.com/Aircoookie/WLED/wiki/Add-own-functionality) on making a custom effect but it say "Programming is done in the Arduino IDE" which i dont have.

I dont have any programming knowledge and couldnt find a tutorial on make an effect but i waned to give it a go but wasnt sure if its possible on  a NodeMCU?

Huge thank you in advance :)

**Comment by Aircoookie** [comment]
Hey! :)
Try playing with the Palette and intensity of the `Running` effect, it will yield a very similar effect :)
Pacifica and Lake also look great. There are thousands of possible combinations!
Making your own effect in WLED requires some C++ programming and compiling a new binary, but if you have a great idea and your effect is noticably different from all existing ones, maybe me or another contributer will implement it :D
