### ISSUE TITLE
How to add an effect

### ISSUE THREAD

**Issue by Nikolay16700011** [Aircoookie/WLED#1055]
Good afternoon. Tell me how you can add your effect to the list. To display them in the WLED app. And how to summon it. I want to add two additional points: 1. I want to add an analog clock effect with arrows. 2. Make the output ESP =1. The number of effects will increase to 113.

**Comment by fishbone-git** [comment]
try this:
https://github.com/Aircoookie/WLED/wiki/Add-own-functionality

I iwll assume that you have already downloaded the code and successfully built code from the unmodified source.

**Comment by Nikolay16700011** [comment]
> попробуйте это:
> https://github.com/Aircoookie/WLED/wiki/Add-own-functionality
> 
> Я предполагаю, что вы уже загрузили репозиторий и успешно создали бинарный файл из неизмененного источника.

**Comment by Nikolay16700011** [comment]
> попробуйте это:
> https://github.com/Aircoookie/WLED/wiki/Add-own-functionality
> 
> Я предполагаю, что вы уже загрузили репозиторий и успешно создали бинарный файл из неизмененного источника.
