### ISSUE TITLE
Different colours with macros

### ISSUE THREAD

**Issue by BezziHD** [Aircoookie/WLED#1065]
Hi there,
I have like two hands full of wLED Lights in my room. Sometimes it looks great, when there are different colours like red and blue. It would be great to change this with one touch on a macro button or something like this.

My idea was to set  "macro 1" for every wLED Controller with different colours, so if I klick on "macro 1" every single wLED Controller will do his own "marco 1" and not "macro 1" from the choosen Controller.

Is this possible?

Thanks for you help!

Jannik 👍 
(Deutsch/English)

**Comment by camcs1** [comment]
Checkout the UDP Sync feature: 

https://github.com/Aircoookie/WLED/wiki/Sync-WLED-devices-(UDP-Notifier)
