### ISSUE TITLE
WS2801 Working but gives wled error2

### ISSUE THREAD

**Issue by insproad** [Aircoookie/WLED#1066]
Hi, thats awesome project but when I  use WLED_0.10.0_ESP8266_ws2801.bin app always gives wled error 2 and when I power off wifi forgettting from esp8266. I need to write wifi information every reset time.

**Comment by raoulteeuwen** [comment]
Does https://github.com/Aircoookie/WLED/issues/1014 help?

**Comment by insproad** [comment]
I also use ESP Home Flasher and I cant use different bin for WS2801. Other bin files dont work with ws2801.

**Comment by Aircoookie** [comment]
What is your board? The WS2801 binary is compiled for 4M boards like wemos d1 mini and the NodeMCU

**Comment by insproad** [comment]
My esp model is esp-01 black.

**Comment by insproad** [comment]
Have you any suggestion?

**Comment by Aircoookie** [comment]
Hi, esp-01 only has 1mb of flash memory, so the default binary won't work.
I compiled a custom one for you:
https://drive.google.com/file/d/1_AzpjjOzXPZyEXoQzxX8QkZF-hsnWDMB/view?usp=sharing
Hope it works well :)

**Comment by insproad** [comment]
> Hi, esp-01 only has 1mb of flash memory, so the default binary won't work.
> I compiled a custom one for you:
> https://drive.google.com/file/d/1_AzpjjOzXPZyEXoQzxX8QkZF-hsnWDMB/view?usp=sharing
> Hope it works well :)

You are awesome my friend I friend and now doesnt have error2 and forget wireless. Working perfect:))))
Can you help me for google home connection too??

**Comment by WoodyLetsCode** [comment]
Hey,
join the WLED Discord server. There is a guide for google home. 😄

**Comment by RajeeRah** [comment]
Hi Guys, where can i find the wiring to WS2801 ? i tried using this link which doesnt work: https://alexbloggt.com/wp-content/uploads/2015/10/nodemcu_pinout_700.png

I did connected power via USB
LED GND -> GND
LED clock -> SCLK
LED Data -> MOSI

**Comment by RajeeRah** [comment]
> Hi Guys, where can i find the wiring to WS2801 ? i tried using this link which doesnt work: https://alexbloggt.com/wp-content/uploads/2015/10/nodemcu_pinout_700.png
> 
> I did connected power via USB
> LED GND -> GND
> LED clock -> SCLK
> LED Data -> MOSI
> 
> tried also:
> LED clock -> D3
> LED DATA -> D4

Finally works - i had to switch clock and DATA + powered the nodemcu also via 5V from LED strip. Thanks for the amazing project. :)

**Comment by newwolf** [comment]
Experienced the same issue with my Wemos D1 mini and WS2801.
Flashing "WLED_0.10.2_ESP8266_ws2801.bin" with Tasmotizer gave me Error 2 and loosing Wifi Info.
But flashing "WLED_0.10.2_ESP8266_ws2801.bin" with "ESP8266Flasher" on 0x00000 works perfect and without errors.
