### ISSUE TITLE
Effect: Round-LED-Clock (feature request)

### ISSUE THREAD

**Issue by kolbenhans** [Aircoookie/WLED#1072]
**Is your feature request related to a problem? Please describe.**
No, not ab problem. Only a possible nice effect to configure

**Describe the solution you'd like**
a round LED clock lightning based on actual ntp time.

**Describe alternatives you've considered**
see the following project: https://github.com/leonvandenbeukel/Round-LED-Clock

**Comment by Aircoookie** [comment]
Hi!
This feature is already part of WLED - just select Analog Clock in the drop down menu in Time Settings! Don't forget to also turn on NTP :)

**Comment by sansillusion** [comment]
Yes I made one for a friend was great ! Used 60 leds.

Just posted it to youtube :
https://youtu.be/It_TK4mL4nk

Le mar. 28 juill. 2020 7 h 55 a.m., Aircoookie <notifications@github.com> a
écrit :

**Comment by TGM3D** [comment]
or look in this graetful project whit a clock and the WLED Software !
