### ISSUE TITLE
Stairways ESP32 + SK6812 RGBW starts flashing half way 480 leds

### ISSUE THREAD

**Issue by MvZeeland** [Aircoookie/WLED#1074]
Dear,

Just finished my stairwells project with an ESP 32 with 480 SK6812 RGBW (60leds/meter) and an 30 Amp/5v power supply.

However, it seems that arround half way through the leds, it starts to blink/flash. Could this be the result of not using any levelshifters/translators? i've already tried to play with the Automatic Brightness Limiter but have no good result. Also the blinking/flashing effect occurs mainly when using an solid color, especially when using an white color.

Please see this video; 
https://youtu.be/dc8RYA9O6sU

My schematics are as following;
![2020-08-01_11-37-01](https://user-images.githubusercontent.com/45131481/89099511-2b486d00-d3f0-11ea-9fd1-3e9f090238dc.jpg)

Thanks in advance!

**Comment by raoulteeuwen** [comment]
Afaik, the data signal should be repeated and 'rejuveniled' by each led. Are you sure the data line is connected correctly around the position where the flicker starts?

**Comment by MvZeeland** [comment]
Hi Raoul,

Thanks for your reply.

I've measured every data to data connection with an multimeter and all diode values are roughly the same, which should indicate that there is not an loose cable.

However, i've flipped the cables from data in and data out so the first led is at the bottom. This gave me roughly the same results.

I've been using these connectors in every stairs for connecting the wires.
![2020-08-01_14-55-53](https://user-images.githubusercontent.com/45131481/89102219-2a6f0580-d407-11ea-9096-32615911db40.jpg)

I've checked every strip from top to down, everyone seems to have an solid connection. However it's very brittle.. should i need to hardly solder the connections? That'll take some time and effort..

Thanks in advance for any help!

**Comment by sansillusion** [comment]
From your picture, I think you may need power injection at both ends if the string is too long.

**Comment by KensonN** [comment]
Maybe try connecting the ground of the led strips straight to the ESP ground. Was having similar issues

**Comment by MvZeeland** [comment]
> Maybe try connecting the ground of the led strips straight to the ESP ground. Was having similar issues

Thanks for your reply, ESP and led strip share the same ground. Could you explain it in some more detail? Thanks!

**Comment by KensonN** [comment]
Yeah, try adding an additional ground wire from the LED strip straight to the ESP

**Comment by MvZeeland** [comment]
That did the trick! However when i connected only an ground wire, it did some flashing during the color/effect changing. When i added the positive wire also, it was fixed!

Thanks KensonN, sansillusion & raoulteeuwen for your support!

**Comment by KensonN** [comment]
Glad that worked!
