### ISSUE TITLE
Return version string 

### ISSUE THREAD

**Issue by raymiec** [Aircoookie/WLED#108]
is there a way to get the version string via api or something ? i could probably parse from the security page but a bit ott.

Cheers

**Comment by Aircoookie** [comment]
Yes! `/version` subpage returns the version ID (for example 1902122 for 0.8.3).
The version string can be found in the `/build` page. Still requires some parsing, but not as ridiculous as the security page. I plan to json-ify /build soon.

**Comment by raymiec** [comment]
Perfect!,   Yeah json would be good, i'm literally grabbing the xml and converting to a json object.
