### ISSUE TITLE
Black out ranges of pixels

### ISSUE THREAD

**Issue by murki25** [Aircoookie/WLED#1103]
Sometimes strips are partly covered by furniture. If it was possible to always set these to black it will save otherwise unneccesary wasted power. Cutting strips and replace with wires isn't a very flexible solution and leads to some visual "hopping" of effects.

I know, that it may be archived by the new segment feature, but that has some downsides here: scenes can only (and have to, to survive reboot) be saved in slot 16 and effects are local to segment and not spanning the whole strip.

So an config option on LED settings in the favour of Black out: "60-123, 420-533"

**Comment by Aircoookie** [comment]
Hi!
I agree that this is a good idea, blacking out non-visible LEDs indeed decreases power consumption without interfering with the visual result! However I do believe segments are a good fit to achieve this functionality (at least once more presets are able to save segment configs, which I'm working on right now!)

**Comment by blazoncek** [comment]
This can be achieved using ledmap and properly sized segments. Both available since 0.11
