### ISSUE TITLE
Connecting to WIFI but no response

### ISSUE THREAD

**Issue by SpyGuyIan** [Aircoookie/WLED#1105]
I have been running `WLED_0.10.0_ESP8266_1M_full.bin` on an ESP-01 in AP mode successfully for a little while now, and recently wanted to connect it to my home wifi. I input my SSID and password and can see the device connect as IP: `192.168.1.23` on my router. I cannot get the webpage to show nor do I get a response when I ping it, however. 

Interestingly, this problem does not manifest in `WLED_0.10.0_ESP8266_1M_ota.bin` when I follow the same steps.

WLED Version: 0.10.0, ESP-01
Uploaded via ESP Home Flasher

**Comment by Aircoookie** [comment]
Hi, thank you for the report!
For some users, the Alexa device emulation causes a crash when connecting to the home wifi. If you disable Alexa in Sync settings before entering the home network credentials.

**Comment by SpyGuyIan** [comment]
Cool, thanks for the response! I've switched to an ESP8266 with more flash and the `esp8266.bin` is working fine. If I go back to the esp-01 I'll keep that in mind.
