### ISSUE TITLE
Minor issue: Default effect not allowed past effect #57

### ISSUE THREAD

**Issue by N1nja98** [Aircoookie/WLED#111]
Minor issue: Default effects can not be set after effect number 57. 
80 total effects 

The following line comes from "settings_leds.htm": 
Default effect ID: input name="FX" type="number" min="0" max="57" required<br>

**Comment by Aircoookie** [comment]
Thanks for finding that one! Will be fixed in the next commit!

**Comment by Aircoookie** [comment]
Fixed now, thank you! Also, next version will feature drop down lists for default effect and palette settings, so the user doesn't have to know the FX number!
