### ISSUE TITLE
ESP 8266 connects to phone through app but does not change lights whenever I press the buttons

### ISSUE THREAD

**Issue by FortLightning** [Aircoookie/WLED#1111]
**Describe the bug**
A clear and concise description of what the bug is. Please quickly search existing issues first!

**To Reproduce**
Steps to reproduce the behavior, if consistently possible

**Expected behavior**

**WLED version**
 - Board: [e.g. Wemos D1, ESP32 dev]
 - Version [e.g. 0.10.0, dev200603]
 - Format [e.g. Binary, self-compiled]

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by FortLightning** [comment]
I have all the wiring and programming done correctly. The lights come on but when I try to change the colors through the app or the computer nothing happens. It says that it is connected but nothing changes.

**Comment by Aircoookie** [comment]
Hi!
What color do your lights illuminate in? Do all of them turn on? Does the master brightness slider or the on/off button work?
This might give us a hint at what is wrong.
In LED settings, make sure you have chosen the correct LED count and set the max. current to the rating of your power supply.

**Comment by FortLightning** [comment]
Hey! The lights are green, blue, red, yellow, white, pink. They do not all turn on either. And the slider does not work aswell. I have adjusted the led light count but never the other other thing.

**Comment by raoulteeuwen** [comment]
Sounds like something might be wrong with the data connection.

What LED strip exactly do you have?
What are the specs of your PSU?
Can you share a picture of your wiring?

**Comment by FortLightning** [comment]
![image](https://user-images.githubusercontent.com/70172752/91623142-d6046a80-e95f-11ea-927a-81b167cf75c9.jpeg)

![image](https://user-images.githubusercontent.com/70172752/91623148-dbfa4b80-e95f-11ea-9934-a37de2564804.jpeg)
![image](https://user-images.githubusercontent.com/70172752/91623151-df8dd280-e95f-11ea-8426-50758590c021.jpeg)

**Comment by raoulteeuwen** [comment]
Looks good to me. What controller is that exactly? Data wire is on D4? What bin exactly did you flash to the controller?

**Comment by FortLightning** [comment]
![image](https://user-images.githubusercontent.com/70172752/91639536-e870b980-e9dc-11ea-98cf-27b5fa6e5aa1.jpeg)
![image](https://user-images.githubusercontent.com/70172752/91639538-eb6baa00-e9dc-11ea-9ed0-f0988c4cda7f.jpeg)

The 8266 bin


And yes the wire is on d4

**Comment by Aircoookie** [comment]
Wait, is that 12v power supply attached directly to the LEDs?
In that case your LEDs are likely toast now :( The listing says they are 5 volt (most WS2812b are).
The NodeMCU typically also breaks at more than 6.5v input voltage, you are lucky if it survived.

**Comment by FortLightning** [comment]
So what you are saying is that the issue is my power supply?

**Comment by FortLightning** [comment]
Yes it is attached directly

**Comment by FortLightning** [comment]
Could you send me what power supply i should get then for 150 leds please. And a strip I should get

**Comment by FortLightning** [comment]
Also, the light still comes on on the nodemcu but could it still be broken you think?

**Comment by Aircoookie** [comment]
Yes, this power supply has the wrong voltage for these LEDs.
You can either use LEDs made for 12v (WS2815) with this power supply (but you'd need a step down voltage converter for the nodemcu!) or what I recommend is to get the LEDs you have again (yours are 99% broken because of the overvoltage) and get a 5 volt power supply with at least 3 amps.

The nodemcu is not broken yet but disconnect it from the circuit immediately as it could blow at any point.

**Comment by FortLightning** [comment]
Okay! Thank you! So is it fine if I get a 4amp or 5 amp power supply?

**Comment by FortLightning** [comment]
I can't find any 3 amps

**Comment by Aircoookie** [comment]
That is good, 3 amp is the minimum. More will give you more headway. Just make sure it is 5 volts :D

**Comment by FortLightning** [comment]
Thank you! I will try everything you said and get back to you!

**Comment by FortLightning** [comment]
![image](https://user-images.githubusercontent.com/70172752/91644467-de14e680-ea01-11ea-98f6-1a87f49ea01b.jpeg)
![image](https://user-images.githubusercontent.com/70172752/91644481-f5ec6a80-ea01-11ea-9d6b-47867672442e.jpeg)


I ordered these two. Will that work?

**Comment by Aircoookie** [comment]
Yep, that should work!

**Comment by FortLightning** [comment]
Okay, I'll let you know tomorrow!

**Comment by FortLightning** [comment]
It worked! Thank you!
