### ISSUE TITLE
Multiple led strip control from single NodeMcu 

### ISSUE THREAD

**Issue by Yusef1985** [Aircoookie/WLED#1117]
Hi guys, 

I'm trying and failing to control two led strips in parallel, using the D4 pix and I made a Y cable going from the pin D4 two LED strips.
the issue is one of the strips working fine but the other is blinking.any ideas?

**Comment by huggy-d1** [comment]
Use a level shifter between pin D4 and your Y cable.  That should fix the problem

**Comment by sansillusion** [comment]
Or you could use a single pixel close to the board as a sacrificial led.

Le mer. 26 août 2020 5 h 56 p.m., huggy-d1 <notifications@github.com> a
écrit :

**Comment by Yusef1985** [comment]
thank you guys, I think i will get QuinLED Dig Uno it has a level shifter on board
