### ISSUE TITLE
Transition between LED Color only for LED segment 0

### ISSUE THREAD

**Issue by somebuddy87** [Aircoookie/WLED#1118]
I tried to use my led stripe with different segments. It seems that the "transition between colors for color changing" only works for segment 0. All further segments changing their color imediatly. Is this really or bug or am i doing something wrong?

**Comment by easp** [comment]
It looks like the expected behavior, [according to the documentation](https://github.com/Aircoookie/WLED/wiki/Segments):

"Color transitions only work on the main segment"

**Comment by Aircoookie** [comment]
Yep, this is expected behavior for now. See #826 for the enhancement request :)
