### ISSUE TITLE
Display scrolling text?

### ISSUE THREAD

**Issue by Bihel29** [Aircoookie/WLED#1122]
Hello, I have a question: 
Is there a way to display scrolling text? 

I made a 3D lamp with 200 pixels and use WLED on it.

I would like to display the text like with Glediator / Jinx but using WLED is this possible? 

My lamp: https://i.imgur.com/4S8z2bH.jpg
I would like : https://i.imgur.com/drexllE.jpg

Thanks

**Comment by Aircoookie** [comment]
Hi!
Yes, using WLED with Jinx is supported! I would recommend the TPM2.net protocol supported in WLED master (not yet in the latest release 0.10.0, but there is a new release 0.10.2 coming tomorrow if you are using the binary) as it is somehow difficult to get more than 170 LEDs to work via E1.31 in Jinx.

**Comment by Bihel29** [comment]
Hi , thanks for your answer.

I directly use the source to upload WLED on my Wemos so I am in 0.10.2?

In Jinx, I configured my Matrix Options, then in output Devices I configured the IP address of my Wemos with the TPM2.NET protocol.

I run a test with Jinx and nothing happens, what should I do?

I'ts the first time with jinx so i am a bit confused.

Sorry for my bad english

Thanks

**Comment by Aircoookie** [comment]
If you are using the latest source, support is in, awesome!
One important thing I forgot to mention is that you need to set the WLED broadcast port in sync settings to 65506 and reboot once! Hope that solves it :)

**Comment by Bihel29** [comment]
It works, thank you :)

**Comment by pattyland** [comment]
Hi, I want to do the same but I can't get jinx to change any of me leds. Controlling via the web interface is working great.
I set the port to 665506 and rebooted, I added the IP of my wled esp with tpm2.net driver and configured the output page. 
When I click on "start output" nothing happens :(￼￼￼

**Comment by micw** [comment]
Hello,

I found this ticket by searching if it is possible to show text with WLED. Would it be possible without an external software, directly with WLED?

**Comment by blazoncek** [comment]
Yes, change segment name.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
