### ISSUE TITLE
RGBW color errors with Home Assistant

### ISSUE THREAD

**Issue by NegativFourteen** [Aircoookie/WLED#1134]
Running into an issue with the control of RGBW lights from within Home Assistant.

I am using the Merkury MI-BW210-999W bulbs running a custom esp8266 ota build. Using the color wheel within HA allows me to select any non-white color and updates the RGB values in WLED correctly. However, when selecting white on the color wheel (255,255,255) it sets the values within WLED to (0,0,0) and the white channel stays off.

I have WLED configured to RGBW with Accurate mode selected. When setting the RGB channels to 255,255,255 manually the white channel works as expected.

**Comment by nicr4wks** [comment]
I have different PWM bulbs running ESPHome but the same issue. When using the color wheel HA sends RGB commands, when adjusting the white level it sends white channel commands. The brightness command always seems to work as expected.

I created an automation so if RGB = 255,255,255 then set RGB 0,0,0 and set WHITE to 255.
Just a note if you use google home when you ask it to set the lights to white it uses RGB 255,221,172 so had to add automation for that one too.
