### ISSUE TITLE
With ArduinoOTA disabled ESP8266 reboots

### ISSUE THREAD

**Issue by SpicerSolutions** [Aircoookie/WLED#1148]
After compiling the source and uploading wled to the esp8266 the board reset itself ( rst cause: 2, boot:(3,7) ).

I've disabled a number of features and set the LEDPIN to 5

build_flags = ${common.build_flags_esp8266} -D LEDPIN=5

#define WLED_DISABLE_OTA         // saves 14kb

/ You need to choose some of these features to disable:
//#define WLED_DISABLE_ALEXA       // saves 11kb
#define WLED_DISABLE_BLYNK       // saves 6kb
#define WLED_DISABLE_CRONIXIE    // saves 3kb
#define WLED_DISABLE_HUESYNC     // saves 4kb
#define WLED_DISABLE_INFRARED    // there is no pin left for this on ESP8266-01, saves 12kb
#ifndef WLED_DISABLE_MQTT
  #define WLED_ENABLE_MQTT         // saves 12kb
#endif
#define WLED_ENABLE_ADALIGHT       // saves 500b only

Compile the source with the above settings

**WLED version**
 - Board: ESP8266 (nodemcuv2)
 - Version 0.10.2
 - self-compiled

It is a great project and really useful.

Any advice would be great thanks in advance.

Johnny

**Comment by Aircoookie** [comment]
Hi,
first of all, I'm very sorry for the extremely late response, got a bit overwhelmed recently :)

I believe this could be an issue I've fixed immediately after the 0.10.2 release.
If you are still looking for a solution, you can either give the latest master source a try or compile 0.10.2 with `#define WLED_DISABLE_OTA` commented out.
Hope it will resolve the bootloops!
