### ISSUE TITLE
Nightlight & preset revisited

### ISSUE THREAD

**Issue by abyssdj** [Aircoookie/WLED#1154]
Morning! I noticed the nightlight now works correctly with the preset playlist, ie it doesn't turn itself back on when the light switches off. However, I'd like to once again suggest a slight alteration. As it is now, (I think) as soon as you turn on the nightlight setting, the preset playlist pauses. Can this be changed so that the presets continue to change until the timer is up and the light is actually off? Do correct me if I'm wrong on this one, I've only checked it quickly.

**Comment by blazoncek** [comment]
Not intended to work that way ATM.
