### ISSUE TITLE
Server Descriptions Always Displayed

### ISSUE THREAD

**Issue by Araforn** [Aircoookie/WLED#1157]
Hello.

I understand this might be specific to me but I have added a number of WLED servers that are receiving streams from hyperion.
Due to the nature of the setup, Hyperion always streams and therefore  i am consistently just seeing the streaming info on the app where the server description should be.

See image below.

![WLED Server Description](https://user-images.githubusercontent.com/16431270/92389530-2d999780-f111-11ea-8f14-a6bb874a0403.jpg)

I would like to see all my server names and perhaps an asterisk only to show that this server is receiving a stream. When i click in to that server I could then see the streaming source.

I know the recommendation is to stop the streaming service but I am happy with automations set up in home assistant that sends the JSON Api command to disable the stream.

Ignore if you feel this is totally unnecessary but I could modify the code for my own if you could point me in the right direction?.

Thanks a lot.

Best Regards,

**Comment by Aircoookie** [comment]
Hi and welcome!
After a similar request it occured to me as well that the dynamic description causes this issue in the app if streams are running, so the behavior was changed recently :)
Make sure you update to WLED 0.10.2 and it will display the description as normal with just a ` (live)` appended if a stream is currently running.

**Comment by Araforn** [comment]
Great. Thanks so much for the response. I'll update all my installations. Really great work with WLED.
