### ISSUE TITLE
Initital Setup-Tutorial??

### ISSUE THREAD

**Issue by lightrunner86** [Aircoookie/WLED#116]
Hello, big wled newbee question:
 I already tried 3 versions of arduino (1.8.8. last) and only getting anoying messages that this&that header file is missing (after finaly gathering all seperate files from different locations?)
now I'm only getting this:

In file included from C:\Users\user1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0-beta2\cores\esp8266/Arduino.h:38:0,

                 from C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master\src/NeoPixelBus.h:28,

                 from C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master\src/NeoPixelBrightnessBus.h:29,.............................................

and so on...

would anyone please be so kind and wrap All additional needed files in one *Zip /*.Rar & Share here. Thx :-)
What really help allot. Is there a list of possible Boards? esp8266Mod d1 Mini Supported?
thank you very much in advance :-)

**Comment by lightrunner86** [comment]
What really help allot. Is there a list of possible Boards? esp8266Mod d1 Mini Supported? 
thank you very much in advance :-)

**Comment by lightrunner86** [comment]
I also tried the *.bin Update Variant via WiFi First. After Uploading it restarts at Firmware Upload Page?

**Comment by Aircoookie** [comment]
Hi @lightrunner86 ,
you can try to install version 2.3.5 of NeoPixelBus! It is really easy via the Arduino Library manager.
The bin update should work in any case, if you still end up at the upload page after reboot, try deleting the `/update` part from the URL and you should see the welcome page or control UI!

**Comment by lightrunner86** [comment]
Hello, thx for your quick response, i "downgraded to v.2.3.5:



Build-Optionen wurden verändert, alles wird neu kompiliert
In file included from sketch\WS2812FX.h:30:0,

                 from sketch\WS2812FX_fcn.cpp:27:

NpbWrapper.h:159:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                       ^

NpbWrapper.h:159:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                                  ^

NpbWrapper.h:160:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                       ^

NpbWrapper.h:160:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                                  ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':

NpbWrapper.h:67:57: error: 'PIXELMETHOD' was not declared in this scope

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:67:68: error: template argument 2 is invalid

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                                    ^

NpbWrapper.h:68:16: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

         _pGrb->Begin();

                ^

NpbWrapper.h:72:58: error: the value of 'PIXELMETHOD' is not usable in a constant expression

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                          ^

sketch\NpbWrapper.h:67:57: note: 'PIXELMETHOD' was not declared 'constexpr'

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:72:69: error: type/value mismatch at argument 2 in template parameter list for 'template<class T_COLOR_FEATURE, class T_METHOD> class NeoPixelBrightnessBus'

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                                     ^

NpbWrapper.h:72:69: error: expected a type, got 'PIXELMETHOD'

NpbWrapper.h:73:17: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

         _pGrbw->Begin();

                 ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':

NpbWrapper.h:82:38: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->Show();   break;

                                      ^

NpbWrapper.h:83:39: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->Show();  break;

                                       ^

sketch\NpbWrapper.h: In member function 'bool NeoPixelWrapper::CanShow() const':

NpbWrapper.h:90:38: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->CanShow();  break;

                                      ^

NpbWrapper.h:91:39: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->CanShow(); break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbColor)':

NpbWrapper.h:98:37: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetPixelColor(indexPixel, color);   break;

                                     ^

NpbWrapper.h:99:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetPixelColor(indexPixel, color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':

NpbWrapper.h:106:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->SetPixelColor(indexPixel, RgbColor(color.R,color.G,color.B));   break;

                                      ^

NpbWrapper.h:107:39: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->SetPixelColor(indexPixel, color);   break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':

NpbWrapper.h:114:37: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetBrightness(b);   break;

                                     ^

NpbWrapper.h:115:38: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetBrightness(b);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'RgbColor NeoPixelWrapper::GetPixelColor(uint16_t) const':

NpbWrapper.h:122:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);     break;

                                             ^

sketch\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':

NpbWrapper.h:133:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);  break;

                                             ^

NpbWrapper.h:134:46: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: return _pGrbw->GetPixelColor(indexPixel); break;

                                              ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbColor)':

NpbWrapper.h:142:37: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->ClearTo(color);   break;

                                     ^

NpbWrapper.h:143:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbwColor)':

NpbWrapper.h:151:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

In file included from sketch\WS2812FX.h:30:0,

                 from sketch\WS2812FX.cpp:27:

NpbWrapper.h:159:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                       ^

NpbWrapper.h:159:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                                  ^

NpbWrapper.h:160:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                       ^

NpbWrapper.h:160:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                                  ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':

NpbWrapper.h:67:57: error: 'PIXELMETHOD' was not declared in this scope

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:67:68: error: template argument 2 is invalid

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                                    ^

NpbWrapper.h:68:16: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

         _pGrb->Begin();

                ^

NpbWrapper.h:72:58: error: the value of 'PIXELMETHOD' is not usable in a constant expression

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                          ^

sketch\NpbWrapper.h:67:57: note: 'PIXELMETHOD' was not declared 'constexpr'

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:72:69: error: type/value mismatch at argument 2 in template parameter list for 'template<class T_COLOR_FEATURE, class T_METHOD> class NeoPixelBrightnessBus'

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                                     ^

NpbWrapper.h:72:69: error: expected a type, got 'PIXELMETHOD'

NpbWrapper.h:73:17: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

         _pGrbw->Begin();

                 ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':

NpbWrapper.h:82:38: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->Show();   break;

                                      ^

NpbWrapper.h:83:39: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->Show();  break;

                                       ^

sketch\NpbWrapper.h: In member function 'bool NeoPixelWrapper::CanShow() const':

NpbWrapper.h:90:38: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->CanShow();  break;

                                      ^

NpbWrapper.h:91:39: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->CanShow(); break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbColor)':

NpbWrapper.h:98:37: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetPixelColor(indexPixel, color);   break;

                                     ^

NpbWrapper.h:99:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetPixelColor(indexPixel, color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':

NpbWrapper.h:106:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->SetPixelColor(indexPixel, RgbColor(color.R,color.G,color.B));   break;

                                      ^

NpbWrapper.h:107:39: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->SetPixelColor(indexPixel, color);   break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':

NpbWrapper.h:114:37: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetBrightness(b);   break;

                                     ^

NpbWrapper.h:115:38: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetBrightness(b);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'RgbColor NeoPixelWrapper::GetPixelColor(uint16_t) const':

NpbWrapper.h:122:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);     break;

                                             ^

sketch\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':

NpbWrapper.h:133:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);  break;

                                             ^

NpbWrapper.h:134:46: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: return _pGrbw->GetPixelColor(indexPixel); break;

                                              ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbColor)':

NpbWrapper.h:142:37: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->ClearTo(color);   break;

                                     ^

NpbWrapper.h:143:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbwColor)':

NpbWrapper.h:151:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

Mehrere Bibliotheken wurden für "NeoPixelBrightnessBus.h" gefunden
 Benutzt: C:\Users\user1\Documents\Arduino\libraries\NeoPixelBus_by_Makuna
 Nicht benutzt: C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master
 Nicht benutzt: C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master
 Nicht benutzt: C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master
 Nicht benutzt: C:\Users\user1\Desktop\arduino-1.8.8\libraries\NeoPixelBus-master
exit status 1
In file included from sketch\WS2812FX.h:30:0,

                 from C:\Users\user1\Documents\Arduino\WLED-master\wled00\wled00.ino:70:

NpbWrapper.h:159:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                       ^

NpbWrapper.h:159:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;

                                                  ^

NpbWrapper.h:160:39: error: 'PIXELMETHOD' was not declared in this scope

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                       ^

NpbWrapper.h:160:50: error: template argument 2 is invalid

   NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

                                                  ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Begin(NeoPixelType, uint16_t)':

NpbWrapper.h:67:57: error: 'PIXELMETHOD' was not declared in this scope

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:67:68: error: template argument 2 is invalid

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                                    ^

NpbWrapper.h:68:16: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

         _pGrb->Begin();

                ^

NpbWrapper.h:72:58: error: the value of 'PIXELMETHOD' is not usable in a constant expression

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                          ^

sketch\NpbWrapper.h:67:57: note: 'PIXELMETHOD' was not declared 'constexpr'

         _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);

                                                         ^

NpbWrapper.h:72:69: error: type/value mismatch at argument 2 in template parameter list for 'template<class T_COLOR_FEATURE, class T_METHOD> class NeoPixelBrightnessBus'

         _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);

                                                                     ^

NpbWrapper.h:72:69: error: expected a type, got 'PIXELMETHOD'

NpbWrapper.h:73:17: error: request for member 'Begin' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

         _pGrbw->Begin();

                 ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::Show()':

NpbWrapper.h:82:38: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->Show();   break;

                                      ^

NpbWrapper.h:83:39: error: request for member 'Show' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->Show();  break;

                                       ^

sketch\NpbWrapper.h: In member function 'bool NeoPixelWrapper::CanShow() const':

NpbWrapper.h:90:38: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->CanShow();  break;

                                      ^

NpbWrapper.h:91:39: error: request for member 'CanShow' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->CanShow(); break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbColor)':

NpbWrapper.h:98:37: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetPixelColor(indexPixel, color);   break;

                                     ^

NpbWrapper.h:99:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetPixelColor(indexPixel, color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetPixelColor(uint16_t, RgbwColor)':

NpbWrapper.h:106:38: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  _pGrb->SetPixelColor(indexPixel, RgbColor(color.R,color.G,color.B));   break;

                                      ^

NpbWrapper.h:107:39: error: request for member 'SetPixelColor' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: _pGrbw->SetPixelColor(indexPixel, color);   break;

                                       ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::SetBrightness(byte)':

NpbWrapper.h:114:37: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->SetBrightness(b);   break;

                                     ^

NpbWrapper.h:115:38: error: request for member 'SetBrightness' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->SetBrightness(b);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'RgbColor NeoPixelWrapper::GetPixelColor(uint16_t) const':

NpbWrapper.h:122:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);     break;

                                             ^

sketch\NpbWrapper.h: In member function 'RgbwColor NeoPixelWrapper::GetPixelColorRgbw(uint16_t) const':

NpbWrapper.h:133:45: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);  break;

                                             ^

NpbWrapper.h:134:46: error: request for member 'GetPixelColor' in '*(int*)((const NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw: return _pGrbw->GetPixelColor(indexPixel); break;

                                              ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbColor)':

NpbWrapper.h:142:37: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrb', which is of non-class type 'int'

       case NeoPixelType_Grb: _pGrb->ClearTo(color);   break;

                                     ^

NpbWrapper.h:143:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

sketch\NpbWrapper.h: In member function 'void NeoPixelWrapper::ClearTo(RgbwColor)':

NpbWrapper.h:151:38: error: request for member 'ClearTo' in '*((NeoPixelWrapper*)this)->NeoPixelWrapper::_pGrbw', which is of non-class type 'int'

       case NeoPixelType_Grbw:_pGrbw->ClearTo(color);  break;

                                      ^

'PIXELMETHOD' was not declared in this scope


...with this effect?

**Comment by Aircoookie** [comment]
Thanks for sending the error message! Did you change anything in the file NpbWrapper.h?
Also, are you trying to compile 0.8.3 or the current master?
Lastly, what is your installed ESP8266 arduino core version?

Don't worry, if we can't get compiling to work, you can still install the binary :)

**Comment by lightrunner86** [comment]
..... Sorry so sooo much :-/ ... I'm new on github, and somehow mixed up 2 versions... *shame* 
i finally got it running :-) 
A great Idea !! hope i'm skilled enough soon to also help here :-)

**Comment by Aircoookie** [comment]
No worries :) Have fun with the software!

**Comment by lightrunner86** [comment]
The issue for my search findung this projekt was that i built a ws2812b Led
matrix in a 3*27 glassbrick wall. ^^ , -but stand-alone....
making value changes from analog input visiblile in the matrix/ ws2812b ist
no big deal.
I'd like for example getting descrete notifications in light (Effekt/color)
change if oil level runs low, mail in the mailbox, motion on PIR, Hooked
via esp8266, but thats just a thought ;-)
Aircoookie <notifications@github.com> schrieb am Fr., 1. März 2019, 00:32:
