### ISSUE TITLE
Esp32s will not flash keep getting “ A fatal error has occurred:failed to connect to esp32: timed out waiting for pocket header”

### ISSUE THREAD

**Issue by superbond05** [Aircoookie/WLED#1160]
**Describe the bug**
A clear and concise description of what the bug is. Please quickly search existing issues first!

**To Reproduce**
Steps to reproduce the behavior, if consistently possible

**Expected behavior**

**WLED version**
 - Board: [e.g. Wemos D1, ESP32 dev]
 - Version [e.g. 0.10.0, dev200603]
 - Format [e.g. Binary, self-compiled]

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by huggy-d1** [comment]
Are you able to write stock esp32 firmware to device?

It would help if you were to edit your post and transfer most of the title into the post, and then edit the default text with the details related to your specific situation.

**Comment by huggy-d1** [comment]
This tutorial may help: [https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/](url)

**Comment by superbond05** [comment]
I tried to rewrite to stock. Doesn’t matter what I do it always come up “fatal error waiting for pocket header” I’m sorry but I’m green as green can be when it comes to this kind of thing. I’m only here because I promised my wife new Xmas lights on the house. Don’t take this the wrong way. But I would like to learn how to do this. I just need to do baby steps at first. Hope you can help. If your too buy I understand


Sent from my iPhone

On Sep 8, 2020, at 7:23 PM, huggy-d1 <notifications@github.com> wrote:

﻿

This tutorial may help: https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/<url>

**Comment by superbond05** [comment]
Thanks for trying but that didn’t work still get the same message 😩

Sent from my iPhone

On Sep 8, 2020, at 8:40 PM, Super <superbond05@hotmail.com> wrote:

﻿ I tried to rewrite to stock. Doesn’t matter what I do it always come up “fatal error waiting for pocket header” I’m sorry but I’m green as green can be when it comes to this kind of thing. I’m only here because I promised my wife new Xmas lights on the house. Don’t take this the wrong way. But I would like to learn how to do this. I just need to do baby steps at first. Hope you can help. If your too buy I understand


Sent from my iPhone

On Sep 8, 2020, at 7:23 PM, huggy-d1 <notifications@github.com> wrote:

﻿

This tutorial may help: https://randomnerdtutorials.com/solved-failed-to-connect-to-esp32-timed-out-waiting-for-packet-header/<url>

**Comment by superbond05** [comment]
Here is what I did and no change still error




















Sent from my iPhone

**Comment by huggy-d1** [comment]
Did you find a way to press Boot/Flash button at power up so you could enter flash mode like the link I posted?  Or, did you install a 10µF capacitor between EN and GND pins on the ESP32?

**Comment by superbond05** [comment]
I soldered a wire from EN to the top left of the wifi chip as in the instructions. Tested it with a multimeter. Tried to flash it with the latest wled update 10.2. Still got that error message

Sent from my iPhone

On Sep 9, 2020, at 12:27 PM, huggy-d1 <notifications@github.com> wrote:

﻿

Did you find a way to press Boot/Flash button at power up so you could enter flash mode like the link I posted? Or, did you install a 10µF capacitor between EN and GND pins on the ESP32?

**Comment by Aircoookie** [comment]
Do you have a different ESP32 on hand? If keeping the boot button pressed during flashing does not work it might be a defective unit.

**Comment by superbond05** [comment]
That’s my thinking also.
No. I should be getting some in the next day or two.
 Sounds like I’ll be needing five maybe more. Nice to know how to fix them just in case it happens again.
 Did you get the pics of what I did? To see if I did it correct


Sent from my iPhone

On Sep 9, 2020, at 2:06 PM, Aircoookie <notifications@github.com> wrote:

﻿

Do you have a different ESP32 on hand? If keeping the boot button pressed during flashing does not work it might be a defective unit.

**Comment by huggy-d1** [comment]
Your uploaded images are not getting displayed on github (at least not in Chrome/Windoze10).

**Comment by superbond05** [comment]
![Uploading 92663678...]

**Comment by superbond05** [comment]
![image](https://user-images.githubusercontent.com/69334355/92663701-f9b8a080-f2cf-11ea-8f78-2b8141ce26a1.jpeg)

**Comment by superbond05** [comment]
![image](https://user-images.githubusercontent.com/69334355/92663732-0f2dca80-f2d0-11ea-8732-ae58c9dc5f3d.jpeg)

**Comment by superbond05** [comment]
So that one I gave up on. Bought 5 more and flashed them. Only one worked. With the help of wingscastona we figure it out. Thought I had no data coming from the esp32s but it turned out that I set the leds to 1000 in the wled configurations. Changed it to 450 and all is good

**Comment by Aircoookie** [comment]
@superbond05 if the LEDs stay black when set to 1000 it is because of the current limiter. You  can uncheck `Enable automatic brightness limiter` in LED settings to get full brightness if your power supply is adequate :)
