### ISSUE TITLE
Parallel output using direct port access 

### ISSUE THREAD

**Issue by Kamal-Sonani** [Aircoookie/WLED#1179]
Instead of using one single line of output ,  is their any chance  to take 4 parallel output (using direct port access)?

it Will take same time as single pin output.

On each port 500 led (512 ideally) x 4 port = 2048 led

By doing that, frame rate will be increased instead of driving  >600 led on single line.

**Comment by Aircoookie** [comment]
Hi! Yes this is being worked on, check #104 for progress and even a working community mod for ESP32 :)
