### ISSUE TITLE
How to call reverse direction from API or from MQTT

### ISSUE THREAD

**Issue by kjkearney** [Aircoookie/WLED#1189]
Currently I see it is possible to reverse the direction from within the webpage of the WLED device however I cannot seem to find anything stating this can be called from MQTT or via API.

Is this possible and if is not could this be added to the next release?  Seems like it should be a pretty easy addition since it is already a feature of the software.

**Comment by Aircoookie** [comment]
Hi, this is of course possible from both APIs :)
Use `RV=1` in the HTTP/MQTT API and `{"seg":{"rev":true}}` in the JSON API!
