### ISSUE TITLE
Button for marco’s don’t work

### ISSUE THREAD

**Issue by antonlamers** [Aircoookie/WLED#1191]
Hi

Since the new version the button for choose a Marco doesn’t work anymore

**Comment by Aircoookie** [comment]
Hi!
What button is not working? Do you mean the button Short press/Long press/Double press macros or something else?

**Comment by antonlamers** [comment]
Yes

**Comment by antonlamers** [comment]
yes, that's i mean. I connect it to D3 and ground what Dr Zzs said in a video. In version 10.0 it worked. https://www.youtube.com/watch?v=6eCE2BpLaUQ&t=1117s
