### ISSUE TITLE
Can't save Presets Cycle settings

### ISSUE THREAD

**Issue by Moskus** [Aircoookie/WLED#1192]
**Describe the bug**
I've set 16 presets, but no matter what I select I can't set the any settings under "Preset Cycle". On/Off works, but nothing else. All settings reverts back to:
First preset: 1
Last preset: 5
Time per preset: 1.2
Transition: 0.7

**To Reproduce**
Adjust the settings on the Favorites page.

**Expected behavior**
As there is no save button, I excpected that WLED saved them automatically.

**WLED version**
 - Board: NodeMCU/ESP8266
 - Version: 0.10.2
 - Format: Binary

**Comment by Aircoookie** [comment]
Hi!
They are saved by activating the preset cycle. Just turn it off, set them the way you'd like and turn the cycle on again :)

**Comment by Moskus** [comment]
Thanks! 😊
Now I just feel really stupid... That was apparently the only thing I didn't try.

**Comment by Aircoookie** [comment]
No worries, this is an error on my side :) There really is no reason why these inputs should reset if any different control command is given.

**Comment by Morphy99** [comment]
@Aircoookie changing transition time from the favourite tab doesn't seem to save for me. I have to change it in LED Preferences.

**Comment by Aircoookie** [comment]
@Morphy99 That setting is only temporary. After changing it, use the power button to apply it and that will be the transition time until the next reboot. To change the settng permanently, use LED preferences :)
