### ISSUE TITLE
RGBW with warm white support

### ISSUE THREAD

**Issue by notherealmarco** [Aircoookie/WLED#1223]
**Is your feature request related to a problem? Please describe.**
Hi, it would be really nice to make the software know if the white channel is either cold or warm. Now it always assumes it's cold.

On Home Assistant (while channel mode is on "accurate"), when I set the color temperature slider to cold, it turns on my warm white channel, instead of generating a nice cold white by using RGB channels. As I move the slider to warm, it turns on red and green channels to warm up the white channel.
It's a really nice feature, but it can only be used with RGB + cold White. I hope RGB + Warm white will soon be supported!

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
CCT support has been added in November 2021 in #2285
