### ISSUE TITLE
Zones or Segments

### ISSUE THREAD

**Issue by HughSparks** [Aircoookie/WLED#1231]
I am not well versed in the LED community and methods of applying LEDs to a project. I want to renovate a room where I light the edge of the room and multiple objects. As of now it seems that every strip requires a separate controller. This is fine when doing on large stip with simple effects. I would like to do one controller to do say a dresser with a strip on the back, the top lip, and each drawer. Possible wiring all the strips to one controller but be able to address the first 20 LEDs as the back ones and so forth for each zone. That way on one controller it may be possible to set a solid color for the back and a strobe for the others. Something along those lines.

I guess the TL;DR is i want zoning for a single controller so that sections of or sets of strips can be controlled without a new controller for every 10-30 LEDs.

**Comment by jezmck** [comment]
The segments feature exists for this purpose.
