### ISSUE TITLE
Gradient setting

### ISSUE THREAD

**Issue by svanton** [Aircoookie/WLED#1232]
Hi and thank you for a great work with the WLED project!

I have an idea of a neat way to create gradients over the strip, similar to set up a gradient i photoshop

See picture
https://community.adobe.com/t5/image/serverpage/image-id/21767i75A3B1094079F3A7/image-size/original?v=1.0&px=-1

As for now colors does not mix great if the are not next to each other in the color wheel, this would not solve the backend of that code but at least provide a nice UI to create the gradient. 

Thanks again for the great work 👍

**Comment by blazoncek** [comment]
For nice/pleasing gradients on the strip you can use custom palettes (available since 0.14-b2) and Palette effect.
It does require from you create a custom palette but the end result is there.
Closing.
