### ISSUE TITLE
Macro Toggle Not Working

### ISSUE THREAD

**Issue by z4nd3rz** [Aircoookie/WLED#1234]
Hello,

First off, WLED is so awesome! I can't wait to get all of my holiday lights going. I've got the lights up and connected to controllers, and I've even had success sequencing them with XLights. Now I'm trying to set up a couple of macros to turn on and off the lights each evening.

**Goal:** 
Run the preset cycle (I've got 3 presets that it cycles through - although that's irrelevant) at a specified time (T1) each evening, and turn it off at a specified time each evening (T2).

**Manual Method:**
This is how I've been able to achieve my goal manually:
1. While LEDs are off, go to main controller (the one with sync enabled) and toggle the check box (on) for preset cycle. This starts all of my controllers on the preset cycle.
2. To turn off the LEDs, I go back to the main controller again and toggle the check box (off) for preset cycle. This stops the preset cycle, but leaves the LEDs on.
3. Turn off the main controller via the power button, which shuts off all of the lights.

**Macro Method Attempts:**
To do the above using macros, I have tried a couple of variants. I've tried to set the macros up so that at T1 the preset cycle is toggled on. This has worked for me with either the "CY=2" or "CY=1" commands. I have been able to successfully start the preset display from a "powered-off" state.

The issue I'm having is that I am unable to turn off the preset display. I've attempted this with both "CY=0" and "CY=2" with no luck, it won't turn off the cycle. I've also tried to use "T=0" to turn off the controller, but it hasn't worked for me. What I'd like to do is have a second macro that will turn off the preset display at T2 and then power off ("T=0") the main controller, but I have not been able to get that to work for me.

Any tips here? Let me know if any clarification is needed.

Thanks!
-Z

**Comment by Aircoookie** [comment]
Hi, thank you for the detailed report! I'm very happy that you like WLED!

What version are you running? For me in latest master, `T=0&CY=0` appears to turn off both the cycle and power correctly.

**Comment by z4nd3rz** [comment]
Thanks for the quick response! I'm using 0.10.0.

**Comment by Aircoookie** [comment]
Try updating to 0.10.2 :) I believe it was changed for that version that `T` and `CY` work together.

**Comment by z4nd3rz** [comment]
Updating to 0.10.2 seemed to do the trick for the main controller! (insert high five emoji) But now I'm experiencing a different issue that was not present with the previous firmware...

At time T1, I run the macro `T=1&CY=1`, which turns on the lights for the main controller, but not the other controllers that should be synced to it (I have the "sync" button enabled on the main controller). The first preset is displayed for 30 seconds, after which it switches to the second preset. When it switches, all of the other controllers turn on and start to sync up with the main controller and continue to do so as it cycles through the other presets.

At time T2 I run the macro `T=0&CY=0`, turning off the main controller; however, the rest of the controllers continue to display the last shown preset when the main controller shut off.

Any thoughts? Am I missing something here with the sync functionality? If you'd like me to create a separate "issue" for this I'd be more than happy.

Again, thanks so much for taking time to help me out!

-Z
