### ISSUE TITLE
Feature: Disable BTNPIN

### ISSUE THREAD

**Issue by tablatronix** [Aircoookie/WLED#1237]
There is no `-1` value to disable BTNPIN, like other pins.

**Comment by Aircoookie** [comment]
Hi!
You can disable the BTNPIN by commenting it out/undefing.
Of course it makes sense to streamline this though, so I believe setting it to `-1` to disable as with the other pins would make the most sense. Will change :)

**Comment by tablatronix** [comment]
Right you can remove the ifndef from npbwrapper , but you cannot disable via build environment build flags etc.
