### ISSUE TITLE
Headless mode library for sync only.

### ISSUE THREAD

**Issue by jimb-cc** [Aircoookie/WLED#1240]
It would be great to have a version of WLED that could be included in another project, where it is only going to be used as a sync to a master node somewhere else on the network.  I have some ESP32s already around the house doing things like environmental logging, and I would like to use spare cycles on these devices to run WLED synced to a different node.  I would prefer it if there was minimal integration needed in the existing scripts I have built for these nodes, such as include the library, construct, and then call in loop().  It wouldn't need any of the web GUI, or WiFi initialization as it would piggyback on the network connection these nodes have open already.

**Comment by blazoncek** [comment]
WLED is a product/application and not a library. As such it cannot be integrated into other products/applications.
It would be infeasible to make such version. Closing.
