### ISSUE TITLE
How do I delete segments using the JSON API?

### ISSUE THREAD

**Issue by DivanX10** [Aircoookie/WLED#1244]
How can I delete segments using the json api? I can create several segments, but I can't remove them. What command should I use in json to remove all segments by zone?

**Comment by huggy-d1** [comment]
From the wiki, JSON API, this is the text that when searched for delete:

`stop | 0 to info.leds.count | LED the segment stops at, not included in range. If stop is set to a lower or equal value than start (setting to 0 is recommended), the segment is invalidated and deleted.`

So, update the _stop_ value to 0 or -1 (via JSON API).

**Comment by DivanX10** [comment]
Thanks. Turn out. Everything works. Just in case, I will post a link, I have described everything in detail there and attached files that can be copied and used for their intended purpose.

https://mjdm.ru/forum/viewtopic.php?f=30&t=7249&p=123641#p123641
