### ISSUE TITLE
Sync send turns off after a while

### ISSUE THREAD

**Issue by LeoLTM** [Aircoookie/WLED#1253]
**Describe the bug**
First I controlled my WLED nodes with the WLED android app, but I recently integrated them into my home assistant network. In home assistant, there are two entities for every node: sync send and sync recieve. I turn on "sync recieve" on the nodes I want to be able to sync to another one and "sync send" on the one I want the others to sync to, After a random period of time, the strip turns dark and turns on again in the default boot up color, a mushy yellow (I know that the color is configurable). After they turned off and on again, only the "sync recieve" entity remains active. 
So, to summarize everything:
My WLEDs turn off randomly and after they light up again, the sync send option is disabled. 

**To Reproduce**
Set up two WS2812b WLED nodes on ESP8266s with 5V 10A power supplies, connect them to the local wifi network, pair the app, add them to home assistant, set a color of your choice, turn on "sync recieve" on one node and "sync send" on the other one, wait until one of them turns off and then on again and check the switches for synchronisation.

**WLED version**
 - Board: Wemos D1 mini
 - Version 0.10.2
 

**Additional context**
All that happened the same with only the WLED app connected.
This bug is really annoying... 

Thank you for your help!

**Comment by huggy-d1** [comment]
When you have your WLED nodes working the way you want, grab a JSON backup of the strip.  When HA notices the WLED node has just come online, have it trigger an action to send a curl json packet (the backup you got) with the settings it had before it turned off.

This will help protect you from yourself (as the saying goes).

Now, if you have not saved your settings in the proper preset (#16 I believe), at WLED restart, the settings will return to default.

Another option that I hate to even suggest but depends on how much this problem lowers WAF.  Custom compile each WLED nodes firmware with all the settings already configured for sync and default boot colors / effect / segments and so on.  This is a horrible option, but is guaranteed to work as long as you don't need to update to a newer WLED version later.

Mainly though, it is important to save those settings into preset 16.  That may involve some macros.  There are number YT videos on how to save settings.  The WLED wiki is very helpful in describing the details. It is getting better at addressing these types of things.
