### ISSUE TITLE
Segmented DMX Channels

### ISSUE THREAD

**Issue by windows10luke** [Aircoookie/WLED#1254]
I have a DMX controlled light that can accept up to 14 channels, which I have configured and it works fine with WLED. However, I can only address the entire fixture as one segment despite having more than one color channel. Ideally, I would like the ability to split up the DMX fixture into multiple separate segments so that each portion of the DMX fixture can have a different color or effect. I am not sure if this can be done in the current build or not, but I would appreciate any help with this issue. Thank you!

**Comment by JvPeek** [comment]
Do you have a channel map at hand for that particular device?
