### ISSUE TITLE
WS2812b don't work anymore

### ISSUE THREAD

**Issue by LAR92** [Aircoookie/WLED#1260]
Hello I use ws2812b 2m 200 led strip, I flashed wled on the esp8266, d4 on data, gnd on gnd and connected the power for the strip to a 5v 15a external power supply, wled set up everything works fine but suddenly it stopped working, after I set up everything again today it still doesn't work, I reflashed the esp8266 then soldered the jumper wires to the esp to the connector, but it still doesn't work, but the app says that the esp8266 is connected, if i change something in the app nothing happens, do you know what the problem is?
![IMG_20201016_150231 1](https://user-images.githubusercontent.com/72699565/96261639-fe543100-0fc0-11eb-9b26-46db08f8f9b0.jpg)
![IMG_20201016_150158 1](https://user-images.githubusercontent.com/72699565/96261671-08762f80-0fc1-11eb-9ffc-e80eab309ad1.jpg)

**Comment by huggy-d1** [comment]
The - lead on the DC supply needs to have a jumper to the GND lead on the ESP8266.
However, be VERY careful because that may put the USB GND lead on the - lead of the power supply.  If it does, it can burn up the USB power source.

I _strongly_ recommend powering the esp8266 with the same 5V supply used on the LED strip and never connect both USB and 5V supply at the same time.

**Comment by LAR92** [comment]
Ok, the esp is already connected to the gnd of the power supply and is powered by usb, but i will try it out tomorrow. So positive to VIN and negative to GND? Can the esp 5v and 15a withstand?

**Comment by huggy-d1** [comment]
On the NodeMCU in the posted images, you can read printed right on the white background, Vin +5V recommended.

**Comment by LAR92** [comment]
Yes, so do I have to connect positive to VIN and negative to GND?  And the ESP8266 can withstand 15A?  I'm sorry for asking so much, I'm just an insecure beginner ...

**Comment by Aircoookie** [comment]
The ESP8266 will only pull as many amps as it needs. As long as it's 5V, you're all set!  
That's correct, VIN to 5v and GND to GND. That should work well!  
Keep in mind that if you need to connect the USB port of the ESP (for firmware flashing, etc.) you need to disconnect the 5v wire between ESP and power supply as it could otherwise destroy the ESP.

Hope you can get it to work :)

**Comment by LAR92** [comment]
Thanks, I'll give it a try, I'll tell you how it went.

**Comment by LAR92** [comment]
So, I connected the esp via VIN and GND to the power supply, when I plugged the power supply into the socket, nothing happened, so the blue led on the esp does not light up and the led strip also does not, so the esp apparently has No power, but if you connect the esp without the cable to the usb then it lights up, then I checked the lines with a multimeter, the positive and negative connections should actually reach the esp and the strip, and the data line reaches the strip apparently not. Did I wire or do something wrong or what do you think is the problem?
![IMG_20201017_142541 1](https://user-images.githubusercontent.com/72699565/96337446-8f8ddb00-1087-11eb-8637-251abe212db2.jpg)
![IMG_20201017_142535 1](https://user-images.githubusercontent.com/72699565/96337456-987eac80-1087-11eb-87f5-3f488ac4155e.jpg)
![IMG_20201017_142506 1](https://user-images.githubusercontent.com/72699565/96337460-a5030500-1087-11eb-9d51-3c18439d93c7.jpg)

**Comment by sansillusion** [comment]
You may want to try using the ground pin on the opposite side of VIN. With
my board if I try to power using these two pins I get a bootloop. But when
I used the ground pin on the other side of the board it worked.

**Comment by LAR92** [comment]
So I connected ground to the other side, still nothing happened, I wasn't sure what the problem was, so I soldered GND and VIN to a USB cable using a cable, plugged it into a power bank and the esp worked, but why it then? Is the power supply broken? Can I test the strip without a power supply unit by limiting the number of LEDs? Or what ideas do you have?
![IMG_20201017_195931 1](https://user-images.githubusercontent.com/72699565/96350143-8109e880-10b4-11eb-884d-d01b0b8e43c3.jpg)

**Comment by LAR92** [comment]
Can someone help me please?

**Comment by LAR92** [comment]
So I once connected the esp and the led strip to another 5v source and lo and behold everything works, before switching on I of course limited the number of leds so as not to destroy my charging station, so it was really my power supply which no longer worked, i will contact the seller and request a replacement, thanks for the help and if i have any further questions i will get in touch.
![IMG_20201018_201714 1](https://user-images.githubusercontent.com/72699565/96376619-538a7100-1180-11eb-856c-87329817805e.jpg)
