### ISSUE TITLE
WLED zusätzlich über Schalter an/aus schalten?

### ISSUE THREAD

**Issue by eldoman** [Aircoookie/WLED#1265]
Hallo zusammen, 
ist es möglich über einen Schalter der direkt an dem Board (z.B. D1mini) angeschlossen ist die LEDs an oder aus zu schalten, ohne dies über die WLAN Verbindung machen zu müssen?

Also nur Licht ein und aus.

Vielen Dank und Gruß.

**Comment by Aircoookie** [comment]
Hi,
ja, das ist über einen Taster (Schließer) zwischen GPIO0 und GND ohne Weiteres möglich. An der Unterstützung von Kippschaltern wird noch gearbeitet 👍 
Viele Grüße!

**Comment by NeariX67** [comment]
Wenn du einen ESP32 hast, geht das auch mit einem Touch pin. Habe dafür ein Usermod geschrieben, das du in /usermods/ESP32_TouchBrightnessControl findest. In der Readme steht auch wie du es in WLED einbindest (Selbst kompilieren notwendig!)
Ich empfehle ein Stück Alufolie oder irgendwas anderes elektrisch Leitendes an den Pin bzw dann das Kabel anzuschließen, damit man nicht ein winziges Kabel antippen muss.

**Comment by Camel2k** [comment]
welchen PIN am ESP benutzt du für den Taster?
Den GPIO 0 gibt es auf meinem Board nicht.

**Comment by NeariX67** [comment]
Der Pin ist hier defeniert: https://github.com/Aircoookie/WLED/blob/master/wled00/NpbWrapper.h (Zeile 21)

**Comment by Camel2k** [comment]
Hallo, mein Esp32 dev board hat keinen GPIO 0 Anschluß. Oder meinst Du ich sollte den Soucecode anpassen?

**Comment by NeariX67** [comment]
Ich denke es wäre besser den Pin anzupassen. Wie im Kommentar steht, sollte es ein Pull-Up GPIO Anschluss sein. Rufe dazu ambesten die Dokumentation deines ESP32 auf, um herauszufinden, welche GPIOs einen Pull-Up Widerstand haben.
