### ISSUE TITLE
Hyperion and WLED

### ISSUE THREAD

**Issue by ikrowni** [Aircoookie/WLED#1280]
Hello I just learned about hyperion and installed it as an add-on onto my home assistant server. After doing that I ran some LEDs on my living room TV, flashed WLED into a wemos d1 mini and got the living room TV working great. 

Now I want to add another strip of lights to my bedroom tv as well and also my computer monitor. Will I need a new hyperion server running for each WLED device to communicate with or can I use multiple WLED instances with 1 hyperion instance?

Main goal is the matched colors to the screens.

**Comment by huggy-d1** [comment]
Since there is no real "issue" with WLED, this question should probably go here: https://wled.discourse.group/c/integrations/9
