### ISSUE TITLE
Device names in WLED app

### ISSUE THREAD

**Issue by superbond05** [Aircoookie/WLED#1282]
How do you get the wled app to have the name you named your lights to come up? All I get is the last ip digit

[Template content removed by Aircoookie]

**Comment by Aircoookie** [comment]
Hi!
Enter the name you'd like to "Server Description" in the UI settings. Then, the app will display the device name instead of just `WLED` for every device!

**Comment by superbond05** [comment]
Thank you👍

Sent from my iPhone

On Oct 24, 2020, at 9:48 PM, Aircoookie <notifications@github.com> wrote:

﻿

Hi!
Enter the name you'd like to "Server Description" in the UI settings. Then, the app will display the device name instead of just WLED for every device!
