### ISSUE TITLE
Trying to connect to Amazon Echo Dot.

### ISSUE THREAD

**Issue by suhassamarth** [Aircoookie/WLED#1283]
Hello @Aircoookie , i'm having a nodeMCU and Analog LED's connected and all is working fine except alexa cannot find the device under philips hue nor other devices. NodeMCU hasn't connected to any UpNP 
![image](https://user-images.githubusercontent.com/20596733/97108294-9903ec80-16f2-11eb-960c-47085bce2743.png)

Please help me out.

**Comment by Aircoookie** [comment]
Hi, did you manage to find out what the issue was?

**Comment by suhassamarth** [comment]
Yes, @Aircoookie , mine is a 3rd Gen Echo Dot. On an unusual occasion without any uPnP client being subscribed I had to restart(Router, Node MCU & Echo Dot 2 time) and change the name of Alexa Invocation name. Then it found the device.

Anyway thanks for the response @Aircoookie . Love the work 👍
