### ISSUE TITLE
1 Pixel dead when using xLights

### ISSUE THREAD

**Issue by PKCubed** [Aircoookie/WLED#1284]
I just installed WLED on my esp8266 and I have a similar, if not exactly the same problem. I’m using XLights to control my LEDs. They all work except for the 1st LED on the 2nd universe. (It could also be the last LED on the first universe)

I also just reinstalled xLights, and that doesn't seem to make a difference.

**Comment by Aircoookie** [comment]
#1187 :) It is already fixed in source, so the error will disappear if you compile from source or once I release v0.11.0

**Comment by PKCubed** [comment]
Has v0.11.0 been released yet? If not, when will it be?

Btw, thanks for making this. I'm making a Christmas light show for the first time and everything other than this has been working really well.

**Comment by Aircoookie** [comment]
No it has not been released yet, but will be for sure this week!

**Comment by PKCubed** [comment]
Great, thanks!
