### ISSUE TITLE
MQTT Settings don't save

### ISSUE THREAD

**Issue by dcbo** [Aircoookie/WLED#1311]
I am using WLED (0.84)  on three lamps.
Now I updated to the current 0.10.2 Version.
As the Lamps are at the Ceiling, I flashed three new ESP-01 (4MBIT) Modules 
and changed them with the previous installed ones.
Everything went fine, except one thing:

**Bug**
The MQTT-Settings will not be saved.

**To Reproduce**
- Goto WLED User Interface http://[IP]/settings/sync?
- enter the MQTT Settings e.g:
![wledmqtt](https://user-images.githubusercontent.com/8166737/97975242-1a314280-1dc9-11eb-989c-a83fe427ede6.png)
- Click Save
- Optionaly:
  - Click _Back_
  - Click _Info_
  - Click _Reboot WLED_
  - Click _Confirm Reboot_

**Expected behavior**
The MQTT Settings will be saved

**Observed behavior**
All MQTT Settings-Fields are empty and MQTT ist disabled.

**WLED version**
 - Board: ESP-01 4MBIT
 - Version: 0.10.2  [2008310]
 - Format: Binary

**Comment by Aircoookie** [comment]
Hi! Unfortunately MQTT is disabled on the 512K binary due to space constraints.
You'll have to stick to the old version or upgrade to an ESP with at least 1MB (recommended 4MB for OTA updates), sorry about that.
