### ISSUE TITLE
Sync persistence and inconstancies

### ISSUE THREAD

**Issue by tablatronix** [Aircoookie/WLED#1313]
I am not sure if this is expected but it makes no sense to me, and the docs for this are outdated and confusing.

https://github.com/Aircoookie/WLED/wiki/Sync-WLED-devices-(UDP-Notifier)
* classic ui is deprecated
* there is no way to toggle (easily) send and receive modes, a trisate would be nice to have. send/receive
  * Sync button toggles option... is on some other page, and unclear what exactly it does, no hint. Does this mean sync toggle button, enables and disables both send and listening? Otherwise if off, it only toggles sending ? This can be simplified to a single concept. Once I understand it I can rework the docs and add better settings page notes.

The following settings are not well described, and confusing as to what they do.
* send on button press ? what button? , i have been power off and on to force syncs, I have no idea how you are supposed to use this
* Send on direct change ? what direct change? sliders, color picker?
* what about api, alexa etc ?

* Sync last state is not restored on reboot unless 'button press is enabled'

* what about sync on boot if sync enabled ? No idea what the behavior is here.

**Comment by Aircoookie** [comment]
Hi and thank you for pointing out that that wiki page was indeed quite outdated :)

I've added some new info, let me know if that makes it clearer or if some questions remain!
