### ISSUE TITLE
MQTT command to reboot WLED

### ISSUE THREAD

**Issue by psbest** [Aircoookie/WLED#1324]
I have noticed that the HTTP interface is not always available on bad wifi signals (long distance garden), but the MQTT interface always works.  After a reboot (manual reset button) the HTTP mostly works again. 
Is it possible to reset the WLED with a API/MQTT command, so i dont have to go into the garden :-) I have looked at the examples and wiki but was not listed.

**Comment by Aircoookie** [comment]
Hi!
Yes, sending `RB` to the API topic should reboot your device (sorry for the connectivity issues in the first place, I suspect it is a problem ESPAsyncTCP might have with intermittent wifi connections)

Added that to the docs!

**Comment by psbest** [comment]
YES it work, thank you, this is really great. Many thanks for the wled software, having a lot of fun with it!
