### ISSUE TITLE
Support for Open Pixel Control

### ISSUE THREAD

**Issue by token47** [Aircoookie/WLED#1331]
Does WLED support the protocol "Open Pixel Control"? Has it been considered? Seems like it's a better alternative to the E1.31 / DMX one. I'm looking into a project that can control devices over OPC.

The reason I marked this as a feature request is because it seems it's not supported and this can be a request for support.

http://openpixelcontrol.org/

Thanks!

**Comment by Aircoookie** [comment]
Not yet, but there are plans to support it at some point :) (see #1241)
In the meantime, the DDP and TPM2.net protocols are a more lightweight alternative to Art-Net and E1.31 that is now supported in the latest WLED source!

**Comment by token47** [comment]
Nice, thank you, I'll take a look at those.

And thanks for the good work.
