### ISSUE TITLE
APA102 support on ESP32

### ISSUE THREAD

**Issue by Grimwig** [Aircoookie/WLED#1334]
Request for 10.2 binary for ESP32 with APA102 support.

I'm running 10.1 using an ESP32_APA102 binary you complied following a specific request. Just wondered if you could expand your list of ESP32 binary variants to routinely include APA102 in future, as you do for ESP8266. Appreciate this is more work for you-love WLED!

**Comment by pemontto** [comment]
This is all configurable in the UI now with the release of 0.12.0 - https://github.com/Aircoookie/WLED/releases
