### ISSUE TITLE
Pixels on Universe Boundaries Stay Off When Controlled by E1.31

### ISSUE THREAD

**Issue by pierslawson** [Aircoookie/WLED#1337]
**Describe the bug**
I have a single ESP8266 controlling 709 GRB pixels in a stip. When using the built in effects, all pixels work great. When I control the lights using xLights over E1.31 three pixels never turn on (pixels 170, 341 and 510).

When I use version 0.9.0-b1 all pixels work fine when controlled by E1.31.

**To Reproduce**
Control more than 1 universe of LEDs using E1.31.

**Expected behavior**
I expected all LEDs to be controlled OK using E1.31.

**WLED version**
 - Board: ESP8266 NodeMCU
 - Version: 0.10.2 Build 2008310
 - Format: Binary

**Additional context**
The problem pixels are on the boundaries of universes. Is this a division issue?

**Comment by sansillusion** [comment]
If I remember correctly there was a bug on dmx miscalculated pixes. I think
it is fixed in the xurrent master 0.10.2

Le ven. 13 nov. 2020 1 h 31 p.m., Piers Lawson <notifications@github.com> a
écrit :

**Comment by pierslawson** [comment]
I have 0.10.2 installed at the moment. Do you mean in the master branch but not yet released?

I found this commit https://github.com/Aircoookie/WLED/commit/10c22efbb5decd8bf1f2dd324f7070af46e4608a that I guess you are referring to.

**Comment by k7bbr** [comment]
Yes. The master branch has the fix for this bug, but the 0.10.2 release doesn’t have the fix. You’ll have to download and compile yourself.

**Comment by Aircoookie** [comment]
#1187 :)
