### ISSUE TITLE
Unable to change stop led

### ISSUE THREAD

**Issue by inbound-dev** [Aircoookie/WLED#1343]
Hey so I am having an issue where I cannot change the stop led in the segments tab, I want to change it to the number of leds my stip has(300) but by default it’s 30 and I can’t change it to more than that, I can’t do 31 etc but I can to like 29 or 6 etc

**Comment by Aircoookie** [comment]
Hi!
Please change the LED count in LED preferences to 300 first.
Also in LED preferences, set the maximum Current to the rating of your LED power supply to get the maximum safe brightness :)
