### ISSUE TITLE
fatal error: Network.h: No such file or directory

### ISSUE THREAD

**Issue by sansillusion** [Aircoookie/WLED#1349]
I can't compile master with Arduino ide anymore.
I get the error:
sketch\src/dependencies/espalexa/Espalexa.h:50:21: fatal error: Network.h: No such file or directory

I tried deleting and cloning again but get the same error.

**Comment by Aircoookie** [comment]
Thank you!
Should now be fixed in latest master :)
Interesting that PlatformIO IDE even managed to include that file, as it was in a totally different folder level.

**Comment by sansillusion** [comment]
Thanks a lot, I will try again tonight when I get home.

Le mar. 17 nov. 2020 2 h 59 a.m., Aircoookie <notifications@github.com> a
écrit :
