### ISSUE TITLE
Minor bug v0.11_beta

### ISSUE THREAD

**Issue by srg74** [Aircoookie/WLED#1350]
**Describe the bug**
wled00/cfg.cpp: In function 'void serializeConfig()':
wled00/cfg.cpp:426:24: error: 'BTNPIN' was not declared in this scope
   hw_btn_ins_0_pin.add(BTNPIN);
                        ^
*** [.pio/build/custom_APA102/src/cfg.cpp.o] Error 1

**To Reproduce**
Compile with env:custom_APA102

**Expected behavior**
Compilation stop with error

**WLED version**
 - Board: [d1_mini]
 - Version 0.11_beta, build 2011154]
 - Format [self-compiled]

**Additional context**
Fixed with -D BTNPIN=3

Thank you for your help!

**Comment by Aircoookie** [comment]
Thank you very much :) Fixed!
