### ISSUE TITLE
UI saturation bar not work

### ISSUE THREAD

**Issue by lucaf86** [Aircoookie/WLED#1360]
**Describe the bug**
I built the latest master (commit 7875a961378b1bfb582da8c611e1dfc14918a5c1) for a wemos D1 mini and I noticed that the saturation bar in the UI it's changed. Instead of one bar now there are two bars, one to change from black to full color and another one for full color to white.
The first bar doesn't work, it's only possible to change the saturation to white using the second bar.

**To Reproduce**
Open the UI and select a color.
Try to change the saturation of the color using the bar

**Expected behavior**
It should be possible to change from black to full color using the bar

**WLED version**
 - Board: Wemos D1
 - Version: WLED 0.11.0p (build 2011200)

Thank you for your help!

**Comment by Aircoookie** [comment]
Fixed, thank you :)
