### ISSUE TITLE
Preset Errors: "preset does not exist" and "enter your API command"

### ISSUE THREAD

**Issue by twlare** [Aircoookie/WLED#1361]
**Describe the bug**
Errors "The requested preset does not exist" and "Please enter your API command first" when trying to modify a saved preset.

**To Reproduce**
Create a preset and save it. Create a second preset and save it. Open the first preset and try to modify it.

**Expected behavior**
Since the preset was created and saved, I didn't expect "preset does not exist" or "enter your API command" errors.

**WLED version**
 - Board: Wemos D1
 - Version 0.11.0p (build 2011200)
 - Format Self-compiled, changed only platformio.ini - "default_envs = d1_mini"

![Screenshot (130)](https://user-images.githubusercontent.com/38672507/99891253-b5754500-2c1c-11eb-9557-32f307e5beef.png)

**Comment by twlare** [comment]
Related to the above, the Presets are not saved in the presets.json file when accessed via the /edit interface.

![Screenshot (131)](https://user-images.githubusercontent.com/38672507/99891353-f02bad00-2c1d-11eb-8917-a827a4b7123a.png)

**Comment by twlare** [comment]
That definitely helped. I haven't been able to reproduce the problem after merging the changes you made today. I will keep testing...

**Comment by dan-buckley** [comment]
The presets .cfg has saved a file, but it doesn't look like it 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/37830504/100581284-5d40f000-334c-11eb-84a8-38700b42a65a.png">

If you then press enter after the bracket the json comes into view 
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/37830504/100581458-a133f500-334c-11eb-88cd-d63a78982561.png">
