### ISSUE TITLE
TPM2 color pattern lasts just for 2 sec

### ISSUE THREAD

**Issue by SebaStKai** [Aircoookie/WLED#1365]
I send a TPM2 message for ~200 LEDs to a Wled on a esp8266. It is received and displayed correctly. But after 2 seconds the "native pattern", that was set on the web interface before, is displayed again.
How can I fixate the pattern send via TPM?

**Comment by Aircoookie** [comment]
Hi!
TPM2 is designed in a live streaming way - if no new packet is received, it will revert to the standard WLED effect. If you want to send just one packet and have WLED keep that state, set the `Realtime timeout` in Sync settings to 65000 :)
