### ISSUE TITLE
Green Flash @ end of transition

### ISSUE THREAD

**Issue by otisrhw** [Aircoookie/WLED#1368]
Hello and thanks in advance! I'm wondering why I get a green flash (strobe) on certain effects, am I doing something wrong? 12v string, 30amp power supply nodemcu on 5v step down.

**Comment by sansillusion** [comment]
Are you using a level shifter on you data line ? It could be that the signal is too weak for stable data decoding by the LEDs.

**Comment by otisrhw** [comment]
No, I'm not currently, I only have 12" jumpers from node the first pixel but I'll give it a shot. Thanks for taking the time to reply, I really appreciate it!!!
