### ISSUE TITLE
D1 MINI PRO problem

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1372]
Wifi cant detect board

**To Reproduce**
All the time

**Expected behavior**
To see SSD under wifi

**WLED version**
 - Board: Wemos D1 Pro
 - Version 0.10.2 pin16
 - Format [e.g. Binary

**Additional context**
I flashed over the ESP32 Bootloader which flashed successful, then flashed the latest release pin16, no joy, tried multiple boards.

Thank you for your help!

**Comment by StefanRu1** [comment]
D1 mini Pro is no ESP32.
I have a D1 mini pro working fine flashed with ESP8266 version.

Best regards,
Stefan

**Comment by Doyle4** [comment]
Thank you, will give that a try.

Problem is, I do have a NodeMCU esp32 and thats not working either.

**Comment by Doyle4** [comment]
D1 PRO solved
