### ISSUE TITLE
default MQTT password with homeassistant has 64 characters

### ISSUE THREAD

**Issue by Matoran** [Aircoookie/WLED#1373]
Hi,

I've configured WLED with MQTT yesterday to connect to homeassistant MQTT broker (mosquitto).

It wasn't working until I notice the default password of mosquitto in homeassistant is too long for WLED.

The max length is 40:
https://github.com/Aircoookie/WLED/blob/b25e22bca486d7a7cae687700a6694f94d37b6f4/wled00/wled.h#L277

Should we up the limit or warn the user if he tries to write/paste a too long password?

**Comment by Aircoookie** [comment]
Hi!
I will redo the settings page soon and i believe it would be a great idea to warn the user if they attempt to input a password/other string which is over the character limit.
For the MQTT pass in particular, I'll consider upping the max. length to 64 for consistency, which is also the max. for the wifi passwords!
