### ISSUE TITLE
Ready to use hardware here

### ISSUE THREAD

**Issue by robi772** [Aircoookie/WLED#1374]
I was created a ready to use hardware which working with this firmware, if anybody want to use this lib but the hardware is not working, can buy it from my shop:
https://iot4.eu/product/iot4wled/
Price is 14.9 Euro + shipping

**Comment by Aircoookie** [comment]
That's nice, thanks!
Added your board to the hardware list: https://github.com/Aircoookie/WLED/wiki/Compatible-hardware#useful-boards-and-addons :)
