### ISSUE TITLE
Last preset number not saved in UI

### ISSUE THREAD

**Issue by lucaf86** [Aircoookie/WLED#1376]
**Describe the bug**
When preset cycles is enabled in UI the last preset number is not saved. Refreshing the UI or rebooting cause the last preset number to be reset to 5.

**To Reproduce**
- Open a browser and go to Favorites page
- check Preset cycle to activate the feature
- change "last preset" with a numbere other than 5 (ex. 2)
- refresh the page (F5 in a browser)
- last preset number is not saved,  return back to defauld value 5

**Expected behavior**
last preset number should be saved

**WLED version**
 - Board:  Wemos D1
 - Version: 0.11.0 "Mirai"  build 2011230
 - Format: self-compiled

**Additional context**
changing the last preset value using http request api works as excpected, with 192.168.4.1/win&PL=6 the value is changed and saved even after refreshing the page or rebooting the wemos

Thank you for your help!

**Comment by emdeex** [comment]
I'm still getting this bug on build 2011290
