### ISSUE TITLE
segment lost after restart

### ISSUE THREAD

**Issue by velidhu** [Aircoookie/WLED#1379]
I use 10.0.0 on nodemcu. i loaded the bin with tasmotizer or other software. the problem is that I only have 35 LEDs which I divide into 2 segments. everything seems to work, but at each restart it loses the division into 2 segments and starts with only 1 segment of 35 LEDs

**Comment by Aircoookie** [comment]
https://github.com/Aircoookie/WLED/wiki/FAQ#my-segments-are-gone-after-a-reboot :)
