### ISSUE TITLE
Adafruit HUZZAH32 Pin 21

### ISSUE THREAD

**Issue by boskoe** [Aircoookie/WLED#1386]
I read in #1243 that the default data pin in the binaries isn't broken out on the Adafruit HUZZAH32 and that a binary may have been compiled using the HUZZAH32's Pin 21. If a binary was made I can't seem to find it?

Thanks

**Comment by srg74** [comment]
> I read in #1243 that the default data pin in the binaries isn't broken out on the Adafruit HUZZAH32 and that a binary may have been compiled using the HUZZAH32's Pin 21. If a binary was made I can't seem to find it?
> 
> Thanks

Please come over to WLED discord and someone will help you with custom binary.

**Comment by boskoe** [comment]
@srg74 Thanks but I managed to borrow an Adafruit Huzzah 8266 which does have the supported pin broken out. I flashed it and it's working very well and I'll use it to learn the WLED enviorment. I have ordered a [Dig-UNO](https://quinled.info/2020/02/11/quinled-dig-uno-pre-assembled-available/) but they are back ordered.

Again thanks for your help.
