### ISSUE TITLE
No available sensors on Home Assistant

### ISSUE THREAD

**Issue by pepsonEL** [Aircoookie/WLED#1392]
Hi
I have installed WLED on my ESP32. Then i added it to Home Assistant integration but i see that:

sensor.wled_uptime

sensor.wled_free_memory

sensor.wled_wi_fi_bssid

sensor.wled_wi_fi_channel

sensor.wled_wi_fi_rssi

sensor.wled_wi_fi_signal

is no available in home assistant and not show state for it. Why ?

**Comment by sansillusion** [comment]
You just need to enable them in home assistant. They are disabled by
default.

Le sam. 28 nov. 2020 5 h 20 p.m., pepsonEL <notifications@github.com> a
écrit :

**Comment by pepsonEL** [comment]
Can you tell me how ?

**Comment by pepsonEL** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/71824185/100555951-34165600-329f-11eb-915b-1500f257a30e.jpg)

**Comment by sansillusion** [comment]
Go in configuration->devices click your wled device, show disabled devices,
click on then and flip the enable switch.

Le dim. 29 nov. 2020 6 h 01 p.m., pepsonEL <notifications@github.com> a
écrit :
