### ISSUE TITLE
Lights wont turn on automatically, and ramdomly turns off when it does

### ISSUE THREAD

**Issue by seanymack** [Aircoookie/WLED#1397]
I have 2 ESP8266 WLED controllers running christmas lights and i set a simple time macro to turn on at 17:00 (T=1) and turn off at midnight (T=0) but its not working reliably. Sometime they work, and sometimes they dont. Also, when i turn on the lights manully, after an hour or so they turn themselves off. Could it be some simple setting i am missing? Timer was not active 

First 5v 20a power supply running 90 led WS2812
Second 5v 20a power suppy running 300 led WS2812

Both controllers are in sync and preset cycle is checked

Thanks for your help

**Comment by fribse** [comment]
Not sure about the failing to turn off, sounds like a wifi problem, but the second one with them turning off after an hour, that sounds like this
![billede](https://user-images.githubusercontent.com/13660621/100575979-765e8800-32dd-11eb-8132-3d89e40f6636.png)
under LED preferences?

**Comment by seanymack** [comment]
i checked and timed option was not turned on. Does the controller need to have a strong wifi for it to turn on/off? i didnt think so

Last night i removed the time macros, to my surprise the lights stayed on all night and into the morning, which suggests its some setting in the time and macro's section that's causing the lights to turn off after an hour or so

This is what my settings look like

![macros1](https://user-images.githubusercontent.com/43820018/100700394-507fc480-336b-11eb-9bb4-d30aacf420f3.PNG)
![macro](https://user-images.githubusercontent.com/43820018/100700400-55447880-336b-11eb-8a9b-c871a448b144.PNG)

**Comment by Aircoookie** [comment]
Those settings seem alright. I don't know what it is which is turning them off unexpectedly 🤔
