### ISSUE TITLE
[Bug] HTTP-API &CL parameter works for H or h, but not #

### ISSUE THREAD

**Issue by arnedebeer** [Aircoookie/WLED#1422]

**Comment by Aircoookie** [comment]
Thank you for reporting! I removed it from the documentation.
`#` is supported in code, however it is treated as a special control character in an URL and the browser removes everything from the URL after `CL=`, therefore to use the HEX color input over HTTP you need to use the H or h prefix, over MQTT or in a preset, `#` works as well.
