### ISSUE TITLE
Device UI unreachable but power button still works in android app

### ISSUE THREAD

**Issue by auggy** [Aircoookie/WLED#1424]
I'm noticing with 0.11.0 that I can't connect to the UI on a semi regular basis. It just says loadjng and it's unreachable in a browser. However the power button on the front page of the android app always seems to work when this is happening.   I'm using a D1 mini and a string of 50 lights.  30% - 40% signal.  0.10.0 didn't seem to do this. Any ideas why? If you need more info please let me know.

**Comment by Doyle4** [comment]
Try enabling 'Disable wifi sleep' or a long them lines, I had a similar issue a while back and this helped.

**Comment by auggy** [comment]
Closing for now. I rebooted,, reconnected, moved the box my d1 was in and it seems fine now.
