### ISSUE TITLE
Group capability within mobile app

### ISSUE THREAD

**Issue by jonfranz24** [Aircoookie/WLED#1427]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Having the ability to group devices within the mobile app.  I have a significant number of devices that serve several functions and being able to group them into collapsible groups would be a huge improvement over just having alphabetical list.

**Describe alternatives you've considered**
I am not sure if the mobile app source is available for modification, if it is then would look at improving as a fork of current design. 

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by Aircoookie** [comment]
Hi! I agree this would be a really cool enhancement, though I wan't to focus on WLED itself right now and it will likely be a few months until I might do anything with the app again.

If you want to make some changes yourself, the app is of course open source and available in a separate repo at https://github.com/Aircoookie/WLED-App/ :)
