### ISSUE TITLE
Xmas 2020

### ISSUE THREAD

**Issue by Legsmaniac** [Aircoookie/WLED#1439]
Well here it is - Xmas 2020!

6 NodeMCUs running latest WLED 11 and one Matrix Board NodeMCU (own programming) on the front of our bungalow.
All running perfectly without a hitch.

YouTube video - https://youtu.be/FQqmD60AnJ0

Controlled via Automations and Scripts on Home Assistant which automatically turns on at dusk and off at midnight.
![HomeAssistantXmas](https://user-images.githubusercontent.com/50076851/101260526-969ca580-3728-11eb-81df-7dec6a9907c9.jpg)

Musical Bells is my musical tree, also running a modified WLED on a NodeMCU triggered by an Arduino Mega which plays Xmas tunes on the bells.
![2020-05-07 11 10 42](https://user-images.githubusercontent.com/50076851/101260530-9ef4e080-3728-11eb-82c9-ac5be5f4583d.jpg)

Santa Express is my modified Xmas train controlled by a simple Sonoff.

Generally running "Merry Christmas" effect but on the hour, every hour a set routine of different effects plays out lasting about 28 minutes, controlled by a script in Home Assistant.

Grateful thanks to Christian Schwinne (Aircookie) and the team for a fantastic nifty program.

Just thought I'd share to spread some much-needed cheer this crazy 2020.

**Comment by pbolduc** [comment]
Glad to see positive feedback. Perhaps this cheerful message is better shared on [discord](https://discord.gg/29VmKNGP) and closed. Lots of issues on the list already.
