### ISSUE TITLE
Wled not connecting to my Nodemcu

### ISSUE THREAD

**Issue by Gled8** [Aircoookie/WLED#1440]
When i power down my nodemcu down and bring it back it does not connect to my WLED. 
WLED says off line. Is that becuase my nodemcu is loosing the ip address of it? how do i make the node mcu ip address a static?

**Comment by Justdigit** [comment]
> When i power down my nodemcu down and bring it back it does not connect to my WLED.
> WLED says off line. Is that becuase my nodemcu is loosing the ip address of it? how do i make the node mcu ip address a static?

You can set a static ip address in wifi settings. 

https://github.com/Aircoookie/WLED/wiki/Settings
