### ISSUE TITLE
preset setting problem

### ISSUE THREAD

**Issue by mascolo74** [Aircoookie/WLED#1444]
**Describe the bug**
impostazione preset tempo si azzera dopo riavvio
spunta su configurazione set preset ciclo si annulla

**To Reproduce**
allego foto di seguito

**Expected behavior**

**WLED versionaggiornamento da 0.10 a 0.11
 - Board:  Wemos D1, ESP32 wrom,esp8266 v3]
 
 - Format  Binary, WLED_0.11.0_ESP32.bin
                             WLED_0.11.0_ESP8266.bin

Thank you for your help!

**Comment by mascolo74** [comment]
Board:  Wemos D1, ESP32 wrom]
version 0.11 installed
the problem I set the preset time to 3.5 s the preset starts to work, but if I reset, turn off, or restart, the cycle stops I saw that the time is set to 0
the check set to reboot the preset disappears

**Comment by mascolo74** [comment]
I attach photos
![Immagine 2020-12-06 191125](https://user-images.githubusercontent.com/46155903/101288565-8c95a800-37f7-11eb-9f5e-ad4755f8824f.png)
![Immagine 2020-12-06 191147](https://user-images.githubusercontent.com/46155903/101288571-96b7a680-37f7-11eb-8e27-10f86aa27adc.png)
![Immagine 2020-12-06 191255](https://user-images.githubusercontent.com/46155903/101288583-a3d49580-37f7-11eb-9f89-635c07185cb0.png)
![Immagine 2020-12-06 191441](https://user-images.githubusercontent.com/46155903/101288594-ae8f2a80-37f7-11eb-858d-a969a339937c.png)

**Comment by Crosstuga** [comment]
Hi, I experience the same issue does not hold after reboot and but also something wrong in the segments in the preset cycle. Might be related on boot does not read the settings properly.

I have 2 segments defines and for both all settings for what I can see will get saved in the json file (http://<IP>/edit). If I click the preset "button" will do as set in both segments but if after reboot will treat it both segments as only one with total LED's - like segment 2 will not exist. The Segment 1 settings will play in 2 as well. If I force and click the button of the preset (or via API PL=~ for example) will play fine- It is like on reboot does not recognize the 2 segments. Sometimes need to refresh the browser to appear - Firefox last version on windows 10.

Thanks for any help. Outstanding piece of software btw!

**Comment by Aircoookie** [comment]
@mascolo74 thank you for the report! It is intended that the cycle turns off when toggling the power or rebooting, however it should not set the time per preset to `0`. I will need to investigate that!

**Comment by Aircoookie** [comment]
@Crosstuga I suspect your issue is a bit different - after boot there is only a single segment, this is correct. Have you set one of the presets with both segments set up correctly as Boot preset in LED settings? Then WLED should restore the segments for you on reboot.

**Comment by mascolo74** [comment]
> @ mascolo74 grazie per la segnalazione! È inteso che il ciclo si spenga quando si accende o si riavvia, tuttavia non dovrebbe impostare il tempo per preset su `0`. Avrò bisogno di indagare su questo!

grazie a te per quello che hai fatto e fai, rimango in attesa di novità, ma purtroppo nel frattempo dovrò tornare alla versione 10
thanks to you for what you did and do, I am waiting for news, but unfortunately in the meantime I will have to go back to version 10

**Comment by Crosstuga** [comment]
> @Crosstuga I suspect your issue is a bit different - after boot there is only a single segment, this is correct. Have you set one of the presets with both segments set up correctly as Boot preset in LED settings? Then WLED should restore the segments for you on reboot.

@Aircoookie You are right on the behavior on the boot but is not linked to reboot just mislead me. Is not the same issue as reported here.
It is the preset cycle when run the cycle segment 2 does not work. If i press button work fine. I just saw the issue https://github.com/Aircoookie/WLED/issues/1447 that describes what I have better and it is confirmed. All good I will wait for fix.
thanks again for your help!

**Comment by exeljb** [comment]
I too am having the issue that @mascolo74 is having.  I'm using wled 0.11 to animate some blinking/winking led light bulbs which work great...until they lose power or reboot. then they run through the presets at lightning speeds when the time per preset goes to zero

**Comment by brownbloodspider** [comment]
> @mascolo74 thank you for the report! It is intended that the cycle turns off when toggling the power or rebooting, however it should not set the time per preset to `0`. I will need to investigate that!

I have the exact same issue. The time per preset value resets to 0 after a boot. I have only 1 segment and only 2 effects in favorite. Any quick help as this is important for my christmas lights
