### ISSUE TITLE
Power Issues

### ISSUE THREAD

**Issue by rkeating30** [Aircoookie/WLED#1446]
So I used the most recent version of the program and with the power source I am using it, it fryed or shorted the circuit. Is there any WLED versions compatible with a 12V 2A power source? thank you. I also bought that one and the exact same stuff that was recommended in the video provided yet it fryed or shorted on me.

**Comment by Aircoookie** [comment]
Hi. No, sorry that you fried your board :(
ESPs are always 5V only, if you have a 12V supply, you need a step-down buck converter to get 5V.
Such a converter is also part of the pre-assembled QuinLED Dig boards, if you want to go that route.
