### ISSUE TITLE
Analog clock settings not stored

### ISSUE THREAD

**Issue by gegu** [Aircoookie/WLED#1449]
**Describe the bug**
With the settings for the analog clock some values are not stored in cfg.json

- First LED
- Last LED
- 12h LED
- Show 5min marks
- Seconds (as trail)

The others I have not tested.

part of cfg.json:
```json
{
"ol":{
  "clock":1,
  "cntdwn":false
}
```

**To Reproduce**
Change values in web UI **Time & Macros** and reboot

**Expected behavior**

The values should be stored.

**WLED version**
 - Board: Wemos D1, mini
 - Version 0.11.0
 - Format self-compiled

**Comment by Aircoookie** [comment]
Thank you for the report and fix. Merged :)
