### ISSUE TITLE
No Web UI when connected as client

### ISSUE THREAD

**Issue by yloose** [Aircoookie/WLED#145]
So I already have ESP with the WLED firmware working perfectly fine, so I tried to flash another ESP. The new one also opens the AP and I can connect and control the strip, but when I connect it to my WiFi network it doesnt have a web server running.

This one is working:
![workingF](https://user-images.githubusercontent.com/47208829/55341151-6b1edd80-54a6-11e9-8e3a-d837bf85fb26.jpg)
This one is not
![notworkingF](https://user-images.githubusercontent.com/47208829/55341177-75d97280-54a6-11e9-97e1-76a69f915159.jpg)

**Comment by Aircoookie** [comment]
Hi! You probably have compiled the project from source using the latest 2.5.0 arduino core. Most likely you are experiencing https://github.com/esp8266/Arduino/issues/5784 . Installing Arduino core 2.4.2 or one of my binaries should solve the issue!

**Comment by yloose** [comment]
Yeah, that was it. It works now, thanks!
