### ISSUE TITLE
RGBW auto calculation of white channel option returns to Dual after power loss or restart

### ISSUE THREAD

**Issue by srdjanv** [Aircoookie/WLED#1457]
RGBW auto calculation of white channel option returns to Dual after power loss or restart

**If you go to config > Led Preferences and check 4-channel type (RGBW) option and put it to Accurate like in picture below, save the settings.**

![image](https://user-images.githubusercontent.com/46896450/101538902-049dd280-399e-11eb-9f8a-f6c87127a6f9.png)

**now if you reboot or restart device that Accurate option is returning to Dual** 

![image](https://user-images.githubusercontent.com/46896450/101539685-33687880-399f-11eb-88c9-4a77a03063d5.png)

**Expected behavior**
On older version this was not a problem 
This is probably connected with new color temperature option.
I use RGBW Cold White strip

**WLED version**
 - Board: Wemos D1 mini
 - Version: v0.11.0
 - Format tried Binary and self-compiled (same issue)

Thank you!

**Comment by southseaboy** [comment]
I am also seeing the same issue with 0.11 on ESP32 - Wemos D1 style (compiled with my own Usermod for touch controls).

**Comment by Aircoookie** [comment]
Thank you very much - fixed :)

**Comment by southseaboy** [comment]
Thankyou - marvellous firmware and excellent support.  Still watching the Home Assistant conference ... interesting new capabilities...

**Comment by srdjanv** [comment]
@Aircoookie , Thank you soo much for fixing this! :)
