### ISSUE TITLE
Custom ESP32 Build red led constant blink.

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1469]
I have managed to compile a D1 Mini firmware all good, and works on the NODEMCU

I changed environment to custom32_LEDPIN_16, Compiled and flashed, the red power indicator LED blinks constantly, I erased its memory, flashed the 32 bootloader and reflashed firmware, LED back to blinking, What am I missing?

I read the VSC link, but to be honest its not a very clear tutorial for someone new like my self sorry. I feel you need to already know what you are doing to follow it, a good breakdown tutorial would be amazing, id also be happy to do one once I have figured it out as I did for others with Marlin firmware for the 3D Printing community.

Not moaning, please don't take this the wrong way.

**Comment by Doyle4** [comment]
![Screenshot 2020-12-10 at 9 38 07 am](https://user-images.githubusercontent.com/65953502/101754388-9820f180-3acb-11eb-8462-a0fc469c963f.jpg)
![Screenshot 2020-12-10 at 9 38 39 am](https://user-images.githubusercontent.com/65953502/101754396-9a834b80-3acb-11eb-8778-fb2c4d18e491.jpg)

**Comment by Aircoookie** [comment]
Maybe the LED blinking is actually fine. Is your WLED-AP reachable? If not you can click the little power plug symbol in the bottom blue bar of VS code to open the serial terminal and see if the board is bootlooping.

**Comment by Doyle4** [comment]
Its like the board is bricked, no WLED SSD shows up in wifi settings on my mac..

**Comment by Doyle4** [comment]
I have tried flashing back over 0.11.0 that I had previously downloaded (not compiled by me) and thats not fixed it,

**Comment by Doyle4** [comment]
serial is showing nothing connected

**Comment by Doyle4** [comment]
@Aircoookie Dude... Im so sorry! I was using as ESP8266 flasher, so sorry! using an updated version of the same software fixed the issue using your compiled version, will test mine now.

Again, im sorry.

**Comment by Doyle4** [comment]
UPDATE:
Working: Own compiled version for D1 Mini and ESP32! Thanks for the slider fix and putting up with me.
