### ISSUE TITLE
Update LED / Sync Settings via JSON API

### ISSUE THREAD

**Issue by jfrux** [Aircoookie/WLED#1474]
I may end up just doing a PR myself but figured I'd post this here first if there is any concerns with doing this type of thing before I attempt it.

I've been managing / calculating my universes, brightness mAh limiter, etc. using airtable and would like to be able to quickly do an HTTP POST to quickly update the power settings and universes as my setup / configuration changes.

I did attempt to do a POST to `/json/info` but it seems to be read only for now.

The things I think I'd like to update or make writable would be the name, led count, and power limit.
Power limit would be nice since I'm dividing the load across my modules connected to a shared power supply.

**Comment by huggy-d1** [comment]
POST to /json per json api wiki

**Comment by blazoncek** [comment]
Configuration changes can be POSTed to `/json/cfg`.
