### ISSUE TITLE
Absent info about third color in MQTT

### ISSUE THREAD

**Issue by mrloggyst** [Aircoookie/WLED#1486]
**Describe the bug**
When changing the third color, no information about it is sent to mqtt.

**To Reproduce**
Enable and setup MQTT connection. Try to change third color.

**Expected behavior**
The color information will be updated and sent to the mqtt topic.

**WLED version**
 - Board: Nodemcu v3 ESP8266
 - Version: v0.11.0 "Mirai"
 - Format: binary

**Additional context**
none

**Comment by nodiaque** [comment]
There's also no trigger at all and the mqtt api result (/v) doesn't contain any info about third color, nor even get triggered.

**Comment by mrloggyst** [comment]
The problem still exists

чт, 3 июн. 2021 г. в 05:54, stale[bot] ***@***.***>:
