### ISSUE TITLE
Multiple boards question

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1489]
Hello,

Does anyone know if its possible for multiple boards to communicate with each other? say I have 4 boards setup in my room, each doing there own thing, instead of connecting to a different board, can one board be master and control other devices connected to the same Wifi router?

Thanks :)

**Comment by Aircoookie** [comment]
Yes :)
https://github.com/Aircoookie/WLED/wiki/Sync-WLED-devices-(UDP-Notifier)

**Comment by Doyle4** [comment]
Thank you!!
