### ISSUE TITLE
Problems with IR control and Sync

### ISSUE THREAD

**Issue by poblabs** [Aircoookie/WLED#1490]
**Describe the bug**
When IR is enabled AND sync is enabled, the IR COLOR controls only affect the WLED with the IR. 

Presets sync correctly, but color changes do not. 

**To Reproduce**
Turn on sync
Press any color on an IR remote
It does not sync across

**Expected behavior**
Presets and color to sync

**WLED version**
 - Board: Wemos D1
 - Version 0.11.0
 - Format: Binary

**Comment by Aircoookie** [comment]
Hi! Please enable "Send notifications on button press" in Sync setting. I should clarify in settings that this checkbox also applies to IR, thanks for the tip :)

**Comment by poblabs** [comment]
That worked! Thanks! 😄
