### ISSUE TITLE
How to access WLED once wifi settings added?

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1493]
Not sure whats going on, I have used my own build and a pre compiled.

I enter my SSD and password, change WLED-XXXX.local and save.

Nothing shows up in my wifi like usual, but nothing is gaining access to my board, 4.3.2.1 and .local

Any ideas?

ESP32 and D1 Mini/NodeMCU

**Comment by nodiaque** [comment]
is your wifi 5g by any change? Only 2.4ghz work with these. Sounds a lot like it's not connected to your wifi. You can use tasmotizer to get the ip (if it return none, it's not connecting)
