### ISSUE TITLE
WLED on ESp32 or esp8266  MATRIX 900 LED - Can WLED drive multi Universes?

### ISSUE THREAD

**Issue by flixmyswitch** [Aircoookie/WLED#1494]
Very new to this but having fun

I have a matrix with 864 LED.  data in from the bottom left and all leds connected in series. 5V ws2811 leds power injection every 50 leds.

I have it running through xlights and the matrix works, but the top 288 leds  , panel flickers strange colours.

Even when just running through WLED i have the same flashing problem

I can still see the whole image on the matrix 32 x 27 only this flickering and colour issue.  I have a logic level shifter installed

i am sure i have not the this up correct but have not been able to find any guidance.

How should i set up WLED to control 864 pixels.

Checked power supply steady 5v. And changed power supply as i had a spare same result

I have doubled checked all my wiring especially the data lines.

If i drive one  panel at a time they all work perfectly. If i join two together perfect, its only when i have all three connected that the issue starts.  If i move the data line connections i can make the error, flashing wrong colour move panels.  So that would lead me to believe my wiring and power injection is ok. 

I have used other esp32 and esp8266 flashed with the correct bin files and each controller makes the same random flashing light error 

In xlights i have i only have 1 universe set up with 6 universe counts at 510 channels per universe.  And i think this may be my problem.

Is anybody able to give me some pointers.  So i think i need how to set up multiple universes with WLED, for xlights i can always ask in their ZOOM room

Other than that. Thanks WLED for getting me started

Thanks

Andy

**Comment by bgutman** [comment]
Do you have any power injection between each panels?  Sounds more like voltage drop issues with adding each panel
I would use the esp32 for this.

WLED can handle the large number of pixels and in xlghts your device will span multiple universes.

**Comment by flixmyswitch** [comment]
Thank for the reply

ITS ALL SORTED.  USER ERROR AS NORMAL.

the way i had constructed my matrix in 3 sections.

Each section had its own power and power injection every 50 pixel back to a common power supply which also powers the ESP.

So what i did (WRONGLY) when going the three panels of 288 pixels together was ONLY like the DATA line between the 3 panel.  Yes this worked but gave me strange colours in the top panel.  Having fault tested for two days, cutting out pixel which i thought were bad.  I then found my error.

I should of also linked the negative between the panel, once i did this the real magic started and displays well.

So thanks for your help.

**Comment by adamcoulombe** [comment]
I am curious, How do you configure your matrix in xlights to use multiple universes? I am trying to figure this out right now

**Comment by flixmyswitch** [comment]
strings 1
nodes/strings 864 (the number of pixels you have
strands/strings 27   (my matrix is 32x 27 rows = 864 and the rows zig zag left to rigth
I have one esp8266 with wled being pass data from xlights
