### ISSUE TITLE
Can't sign into WLED AP WIFI

### ISSUE THREAD

**Issue by Michi1860** [Aircoookie/WLED#1502]
After connecting successfully to the WLED AP with wled1234 there is no prompt to sign in. 
After typing http://4.3.2.1 into the webbrowser and waiting for a bit there is a network-timeout error.
Using a ESP8266MOD 12-f.
Smartphone: XIAOMI NOTE 10 PRO
After switching to a ESP 12-f it's working just fine. Same Flash settings though. 
What am i doing wrong?

**Comment by huggy-d1** [comment]
You should wait a bit longer at the wifi connection page where you tell your note10pro to connect to the WLED-AP.  It will "capture" your phone and present the WLED interface where you can enter your local wifi credentials.  For 4.3.2.1, you cannot use a web browser.

**Comment by sansillusion** [comment]
You may need to disable cell data to get your phone to connect to the IP,
some phone try to connect on the internet instead when connected to both an
wifi AP and cell data at the same time.

**Comment by mike2nl** [comment]
XIAOMI NOTE 10 PRO has issues with that what @sansillusion posted before me.

**Comment by Michi1860** [comment]
Don't really know what changed but it's working now... 
Thanks and close :)
