### ISSUE TITLE
How are you guys changing the wifi on a numbe of these?

### ISSUE THREAD

**Issue by l0c0luke** [Aircoookie/WLED#1503]
I have 5 of these at my house. Love 'em. But I want to take them to my friends house and set up a scene. I won't know his wifi until I get over there. How is everybody mass updating wifi settings? If at all.

Or will I have to turn one on at a time, wait for it to go into AP mode, and redo each one individually?

**Comment by Legsmaniac** [comment]
> Or will I have to turn one on at a time, wait for it to go into AP mode, and redo each one individually?

Yep. Unless you set up the WiFi in the code, recompile and flash each one.

**Comment by huggy-d1** [comment]
You can do one, upload the firmware, then download the firmware to another.  I would try this at home to verify it uploads / saves the wifi settings during the firmware upload process.  I am not at all sure with the 0.11.x version and the little file system where the settings are stored.
