### ISSUE TITLE
Infrared remote setting lost

### ISSUE THREAD

**Issue by Sigi-cz** [Aircoookie/WLED#1518]
**Describe the bug**
Infrared remote setting is lost upon reset

**To Reproduce**
set an Infrared remote to 44 key remote, reset the board, the setting is lost

**Expected behavior**
the setting isn't lost

**WLED version**
nodemcu v3
WLED_0.11.0_ESP8266.bin

Thank you for your help!

**Comment by Aircoookie** [comment]
Hi, thank you for the report 👍 
It has already been fixed, see https://github.com/Aircoookie/WLED/pull/1395
Release 0.11.1 with the fix coming out tomorrow :)

**Comment by Sigi-cz** [comment]
ok. thanks! 
the [search ](https://github.com/Aircoookie/WLED/issues?q=is%3Aissue+is%3Aopen+Infrared+remote)gave no results
