### ISSUE TITLE
AP WiFi SSID not hiding

### ISSUE THREAD

**Issue by Legsmaniac** [Aircoookie/WLED#1520]
**Describe the bug**
I have just noticed that all my WLEDs AP SSIDs are showing in my WiFi list despite checking the box "Hide AP name".

**To Reproduce**
Check the box "Hide AP name" in WiFi Setup and save settings, the SSID doesn't disappear when "AP opens: Always" is selected. 
(It is of course not a problem if "No connection after boot" is selected")
Also, after a power cycle, if you now look in WiFi Setup, the "Hide AP name" box is unchecked once again regardless of which setting "AP opens" is set to.

**Expected behavior**
When selecting "Ap opens: Always" AND after checking the box "Hide AP name" I would expect : -
1)  The AP SSID to be hidden and
2) The AP SSID to remain hidden even after a power cycle.  (ie. the box setting remains checked.)

**WLED version**
 - Board: I'm using both Wemos D1 Minis and NodeMCU 12fs
 - Version v0.11.0 "Mirai" build 2012010
 - Format - both binary and self-compiled with PlatformIO.

Thank you for your help!

**Comment by Aircoookie** [comment]
Thank you very much, will fix shortly :)
