### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by superbond05** [Aircoookie/WLED#1521]
I noticed that my lights are not syncing anymore. First I could not find one of my controller on the computer or iphone app. searched for it for two days it would not come back on line. Was scared to reset as I might loose all me presets. I pressed the reset button on the controller and all is good. I did not loose my presets but I used this controller to control all my effects for the rest of the house. 
 I tried to unsync and resync a dozen times with no success. How do I get them to Sync with this controller again?

**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by WoodyLetsCode** [comment]
Did you also restart all your other controllers?
And btw: You can also restart them in the wled web page. Just click on info.

**Comment by superbond05** [comment]
no But I will

**Comment by superbond05** [comment]
Refresh or reboot?

**Comment by WoodyLetsCode** [comment]
Reboot

**Comment by superbond05** [comment]
K

**Comment by superbond05** [comment]
Nice 
Seems to be working! Thank you
