### ISSUE TITLE
Automatically open when I turn on the electricity

### ISSUE THREAD

**Issue by IcyFeather233** [Aircoookie/WLED#1524]
I turn off the electricity every night, and when I come the next day, I will turn on the electricity, and the light comes on automatically. How can I not let it come on automatically?

**Comment by Legsmaniac** [comment]
Setting >  LED Preferences.......

![Screenshot 2020-12-19 122425](https://user-images.githubusercontent.com/50076851/102689355-48da6f80-41f5-11eb-8710-bde4666f8ee3.jpg)

**Comment by IcyFeather233** [comment]
> 
> 
> Settings > LED Preferences.......
> 
> ![Screenshot 2020-12-19 122425](https://user-images.githubusercontent.com/50076851/102689355-48da6f80-41f5-11eb-8710-bde4666f8ee3.jpg)

Thanks！
