### ISSUE TITLE
IR Remote disabled after Reboot (Firmware 0.11.0)

### ISSUE THREAD

**Issue by Aynrandless** [Aircoookie/WLED#1526]
**Describe the bug**
I use a 24 RGB IR Remote with a IR Receiver (TSOP38238) together with my Wemos. I chose 24 RGB in the Sync settings menu and everything works as expected. After rebooting the WLED (via menu or when the power is dis- and then reconnected) the IR setting is disabled again as in the default settings.

**Expected behavior**
I expect that once the settings is saved the IR remote keeps beeing activated...

**WLED version 0.11.0**
 - Board: Wemos D1 Mini
 - Version 0.11.0
 - Format: Binary

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by Aircoookie** [comment]
Thank you for the report, it is already fixed in the release I just made :)
https://github.com/Aircoookie/WLED/releases/tag/v0.11.1
