### ISSUE TITLE
Turn Off in "Time-controlled presets"

### ISSUE THREAD

**Issue by Stefan231278** [Aircoookie/WLED#1531]
Hi

I have searched, how to do it, but i didn`t find the answer. 

I can turn on the WLEDs in the Time&Macro setup. Therfore I go to the "time-controlled presets" and input the time and the present, i want. Works good.

But I can`t turn off the lights with a timer. How can i make, that the lights turn of at xxx o`clock or after xx minutes?

I get sick an search al lot. Please dhelp me.

thx a lot

Stefan

**Comment by Aircoookie** [comment]
Hi, please turn your light off, then create a preset. You can use that to turn it off.
Alternatively uncheck "Use current state" when creating the preset and enter `T=0` into the API command field.
I hope it helps you :)
