### ISSUE TITLE
MQTT : missing channel for color 2 and 3

### ISSUE THREAD

**Issue by nodiaque** [Aircoookie/WLED#1533]
Hello,

in the mqtt topic, we have /c. This work great, but only for the main channel. Would be great to have cs and ct also to send / received the current color of these channel.

**Comment by mrloggyst** [comment]
The second color in the "v" topic is coded under "cs". But the third color is really nowhere to be found. As well as the white channel for the third color.

**Comment by blazoncek** [comment]
Use topic `wled/device/api` and submit JSON API in message body.
