### ISSUE TITLE
Favorites don't save or load

### ISSUE THREAD

**Issue by luminxa** [Aircoookie/WLED#1534]
I recently noticed on the favorite pages and  hadn't tested it yet, it won't save or load the presets, well I can't say that it doesn't save the presetspiece that because it does advance to the next ID when I press save but it won't load the presets... Any ideas?

**Comment by Aircoookie** [comment]
Hi! Does it happen with the latest 0.11.1 release?
Please send me the output of `http://[WLED-IP]/presets.json`, that may allow us to figure out what's going wrong :)
