### ISSUE TITLE
TM1803

### ISSUE THREAD

**Issue by Menno000** [Aircoookie/WLED#1545]
I saw that the TM1814 is possible
i have treid the TM1803 but no luck for me
Has somebody als tride this?

**Comment by jonathanrobichaud4** [comment]
Could this issue possibly be reopened? I'm not to sure how to implement new led strips but I would assume the drivers are similar since both strips are compatible with fastLED which is used in this project, Correct?

**Comment by jonathanrobichaud4** [comment]
Oh ok. I must've assumed because ESPHome uses fastLED. Does that mean that currently it's not possible with WLED?

**Comment by blazoncek** [comment]
Check what NeoPixelBus supports. If it supports it the it may be added to WLED.
