### ISSUE TITLE
Error 10: Could not mount Filesystem

### ISSUE THREAD

**Issue by Michi1860** [Aircoookie/WLED#1549]
After finally finding the lamp in wled I get more issues as you can see in the pictures below. The second message comes immediately after clicking on the lamp and the first one comes after klicking on anything in the app. 

I looked the issues up but there seems to be no answer. 

Controller: ESP8266 ESP-12F
Binary: WLED_0.11.1_ESP8266

![Screenshot_2020-12-21-17-45-20-265_com aircoookie WLED](https://user-images.githubusercontent.com/22622858/102800666-7883a600-43b4-11eb-8495-7703549537aa.jpg)
![Screenshot_2020-12-21-17-45-13-630_com aircoookie WLED](https://user-images.githubusercontent.com/22622858/102800672-7a4d6980-43b4-11eb-9d16-22e4a0f6e934.jpg)

**Comment by WoodyLetsCode** [comment]
What Microcontroller do you use? What binary file do you use?

**Comment by Michi1860** [comment]
Controller: ESP8266 ESP-12F
Binary: WLED_0.11.1_ESP8266
Phone: XIAOMI NOTE 10 PRO

**Comment by Aircoookie** [comment]
Hmm, it should work with your mcu, but just in case, try the `WLED_0.11.1_ESP8266_1M` binary

**Comment by Michi1860** [comment]
I no longer recieve an error when using the ..._1M binary. Thank you very much sir.

**Comment by Michi1860** [comment]
Though it doesn't seem to be working. I can press buttons in the app all I want but the lights are not changing. Yes, I solderd the right gpio2 which is D4 in this case. 
![IMG_20201222_124140](https://user-images.githubusercontent.com/22622858/102885213-4b3a0500-4453-11eb-9365-b2ac3401f67c.jpg)

**Comment by janbernhardt** [comment]
I had the same issue when uploading the source with Arduino. Finally I discovered that the FlashSize in my Arduino settings was set to `FS:none`. After changing it to FS:2MB it was working fine.
![image](https://user-images.githubusercontent.com/1104935/102886851-2c893d80-4456-11eb-92e9-c5868adf9ddb.png)

**Comment by Michi1860** [comment]
This is my current FlashSize. I will try with different sizes now. 

![grafik](https://user-images.githubusercontent.com/22622858/102887855-f056dc80-4457-11eb-9aee-5370a73f1646.png)

**Comment by WoodyLetsCode** [comment]
Use this: https://github.com/Aircoookie/WLED/wiki/Installation-using-the-official-GUI-tool-(ESP8266)

**Comment by Michi1860** [comment]
Im beginning to think that the LED Strip is the issue. I orderd another one (same brand and type) and this time there is not a single LED emitting light when connecting the Strip to the designated 5V and GND. Even without any 'Data In' they should emit light, right?

**Comment by Aircoookie** [comment]
@Michi1860 I would maybe check the data connection. Those jumper wires have almost no metal in them and I found them very hard to use reliably. Typically, addressable LEDs will NOT light up without a data input.

**Comment by Michi1860** [comment]
In conclusion i ordered 5 different LED Strips. 2 of them apparently never worked. 1 Strip always showed the same (few) lights so it was broken too. The last 2 i ordered arrived at christmas and worked just perfectly fine. They even lighted up without any data connection. There is also to mention that i connected every single LED strip to the same setup. Therefore i can be sure that there is no error in the cata connection since the last 2 Strips worked just fine. 

What can we learn from this? 
Do not trust cheap sellers. 
Always double check your connections. 

Thanks for the support!
