### ISSUE TITLE
Bringing back skip number of LED's feature

### ISSUE THREAD

**Issue by jandrzejczak** [Aircoookie/WLED#1555]
Hi,
from few updates WLED is missing in skip number of LED's feature. Is there any chance of bringing it back? I use some ws2812b strips behind my monitor, unfortunately there are too many lights on one strip, and latency of bandwith is killing me. Thanks for any response or consideration. 
Best regards, keep up with amazing work!

**Comment by sansillusion** [comment]
You could just chage the start position in the segment.
