### ISSUE TITLE
LEDs do not light up

### ISSUE THREAD

**Issue by 3DFans** [Aircoookie/WLED#1558]
Hey
I've connected and connected everything so far. The web interface is also available, but I can do what I want, but no LEDs light up. I put the datapin on D4, but without success. The LEDs stay off. Does anyone else have a tip?

**Comment by Aircoookie** [comment]
Hi! How many LEDs do you have and how are they wired up? What LED count and brightness limiter setting do you have in LED settings? You can send pictures of your setup, that often helps with figuring out what the issue is :)

**Comment by 3DFans** [comment]
Hey, I've attached a few photos. The whole thing is supplied by a power bank with 5V, 2.4A.
![IMG_20201222_172610](https://user-images.githubusercontent.com/59125879/102910623-26598800-447b-11eb-89d5-5b20f908dd2b.jpg)
![IMG_20201222_172620](https://user-images.githubusercontent.com/59125879/102910627-28bbe200-447b-11eb-89aa-398b14ec2a3f.jpg)
![IMG_20201222_172704](https://user-images.githubusercontent.com/59125879/102910630-2a85a580-447b-11eb-86f1-8e6b974619b9.jpg)

**Comment by sansillusion** [comment]
Mabe you have the wrong pin ? I did a lamp yesterday and I soldered the
data wire to D4 on my board, the lights would not turn on, so I decided to
try pin D2 (chinese esp32 devboard) and tada ! Lights turned on ! Mabe just
a different labeling sheme.

**Comment by 3DFans** [comment]
> Mabe you have the wrong pin ? I did a lamp yesterday and I soldered the data wire to D4 on my board, the lights would not turn on, so I decided to try pin D2 (chinese esp32 devboard) and tada ! Lights turned on ! Mabe just a different labeling sheme.

That's what I thought and tested the pins, but none of them bring success. : /

**Comment by huggy-d1** [comment]
Swap out the Dupont jumper(s) after finding which one is not crimped properly.

What is the voltage from GND to +5V on the LED strip?

Wiggle the dupont jumpers while measuring.  Any change?
