### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by pontos-dev** [Aircoookie/WLED#1559]
Hey Aircoookie

Recently I updated to the new wled 0.11.1, and now I can't login to the gui, I have tried with many different devices, and it says the password is wrong (wled1234)

What to do ?

**Comment by pontos-dev** [comment]
Sorry, it was bad wifi connection apparently

**Comment by huggy-d1** [comment]
Perhaps you can remove the bug label, and at least close out the issue?

**Comment by Hardwarekiller** [comment]
Please close the thread or delete it if the error is not a bug but your fault!

Otherwise, users click on the thread and want to help but are annoyed because it wasn't a bug and they didn't delete the thread because of their operating error.

Hardwarekiller
