### ISSUE TITLE
Feature Request: FX: Black/Two Tone Lightning

### ISSUE THREAD

**Issue by ShiHotKeyMushroom** [Aircoookie/WLED#1563]
Picture the Lightning FX...but you control the color of the flash, or just make the "flash" the pixels going dark instead of white? I know strobe is simulate to this, but it makes the entire strip go a different color. Whereas I'm suggesting random sized segments at randomized times like lightning.

Context:
I'm building a custom wallpiece made of lightsabers and I'm controlling the lights with wled. I want a variety of lightning effects so I can give the blade different effects.

**Comment by Aircoookie** [comment]
Hi! You can do this currently! Just change the Palette to `* Color 1`, and the first color will be the color of the flashes and the second the color of the background :)
