### ISSUE TITLE
How do I disable UI Background Image?

### ISSUE THREAD

**Issue by RaSTuS26** [Aircoookie/WLED#1575]
I'd like to disable the background image in the UI.

I've tried various options in the 'BG HEX color' field (#333333, 333333, #333, 333) but none seem to have any effect, was hoping this would override the BG Image, I don't want an image.

Thanks in advance.

**Comment by Aircoookie** [comment]
Hi! Just put a space or any invalid URL in the BG image field :)

**Comment by RaSTuS26** [comment]
> Hi! Just put a space or any invalid URL in the BG image field :)

Beautiful, thanks a lot, now #nnnnnn works in the 'BG HEX color' field too, just what I was looking for.
