### ISSUE TITLE
bugs with commands to mqtt/api

### ISSUE THREAD

**Issue by daddvok** [Aircoookie/WLED#1582]
I catch very strange bugs when sending to a topic /api, for example FX=0 switches to "Solid", and &FX = 0 switches to Effect number 6. And vice versa. that is, somewhere & FX teams work, and somewhere FX. And the same watch in other api commands, whether &A, &IX, &SX. wled versioin v0.11.1, esp8266
**Example 1**
![1](https://user-images.githubusercontent.com/47695947/103164061-818ed000-4817-11eb-863b-2dfe8f89357c.jpg)
**Example 2**
![2](https://user-images.githubusercontent.com/47695947/103164062-82276680-4817-11eb-83a6-ea21536beda7.jpg)

**Comment by Aircoookie** [comment]
Hi! Stock WLED does not return such JSON to the `.../v` topic. Furthermore there isn't even an effect 144. Are you using a fork or usermod?

**Comment by daddvok** [comment]
> Hi! Stock WLED does not return such JSON to the `.../v` topic. Furthermore there isn't even an effect 144. Are you using a fork or usermod?

Hi, I just reformatted the title of the topic for better understanding. The value is not formatted in any way

**Comment by daddvok** [comment]
@Aircoookie I connected and flashed another esp, I send both the same commands, everything works fine on the new one, on the old one - no, what could be the problem?

**Comment by daddvok** [comment]
The reason was a bad power supply for the LED strip, it apparently gave false pulses, after replacement everything works fine
