### ISSUE TITLE
Color do not match LED light colors

### ISSUE THREAD

**Issue by Tinkertron1972** [Aircoookie/WLED#1591]
**Describe the bug**
Beginner - but when I download file and flash the control board and start using the WLED software to control the LED light by selecting color via color wheel, the just don't match up

**To Reproduce**
Steps to reproduce the behavior, if consistently possible

**Expected behavior**

**WLED version**
 - Board: KeeYees Development Board WiFi WLAN Wireless Module for ESP8266 for NodeMCU for ESP-12E for Arduino
 - Version: WLED version 0.11.1
 - Format Binary (Windows 64bit)

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by sansillusion** [comment]
Go in settings->led settings, and change rgb to grb or vice versa.
