### ISSUE TITLE
Why is there this restriction? ESPALEXA_MAXDEVICES 

### ISSUE THREAD

**Issue by gsieben** [Aircoookie/WLED#1595]
Hi all,
I have a small question. I have almost finished my usermod for a relay control. The relays can be configured via the web interface or a JSON call. At the moment I restrict the number of possible relays already at compile time. But I do this only because I didn't want to set the number ESPALEXA_MAXDEVICES too high. I don't know why the number is limited. Does anyone know? What does it mean if I increase the number. 

With my Wemod D1 I have set 4 and everything works. Anyway, I do not have more PINs free. But with other devices it makes sense to have more available. 

Cheers Gabriel

**Comment by Aircoookie** [comment]
Hi! 
Sorry for responding half a year later :)
The limit has memory reasons. Espalexa needs to chain the states of all the controlled devices into one JSON response, and at some point, that requires too much memory, especially on an ESP8266. The upper safe limit for `ESPALEXA_MAXDEVICES` (in WLED, standalone about 12) i would estimate to be about 8.
