### ISSUE TITLE
Make Cycle modifiers work stand-alone

### ISSUE THREAD

**Issue by StormPie** [Aircoookie/WLED#16]
Hey!

It seems &PA &PC &PX don't work when sent as standalone API requests. Have you been able to get these new features to work? If so, what API request are you using? 😀 

Thanks heaps.

p.s I've sent some emails, the new UI is working really well!

**Comment by Aircoookie** [comment]
Hi!

At the moment they don't work standalone, but only as a modifier together with "&CY=1".  However, don't worry, you can just call "&CY=1" again while the cycle is active and it will not do anything (except applying the modifiers you use).

You've got a new mail! 😊

**Comment by Aircoookie** [comment]
0.7.0 is out! This will be closed once I updated the documentation!
