### ISSUE TITLE
Usermod custom UI elements broken

### ISSUE THREAD

**Issue by gegu** [Aircoookie/WLED#1608]
**Describe the bug**
After version 0.11.1, it no longer works to display custom UI elements on the INFO page.
Also does not work with usermod_v2_example.

**To Reproduce**
Uncomment MyExampleUsermod::addToJsonInfo() and compile using the usermod.

**Comment by Aircoookie** [comment]
Thank you, should be fixed just now in master :)

**Comment by gegu** [comment]
Sorry, but I don't think so. I tried a few minutes ago using the current master.

**Comment by Aircoookie** [comment]
Oh noes I need a break haha. Good that you double checked!
Forgot to run the npm script to actually apply the fix to the version saved by the ESP.
Now it should work :)

**Comment by gegu** [comment]
👍 now it works
