### ISSUE TITLE
Error compiling for board Generic ESP8266 Module

### ISSUE THREAD

**Issue by sumondigi** [Aircoookie/WLED#161]
hello there
many many thanks for sharing such a great great great work...
i want to use ESP-01 (blue) ( 512K(64K SPIFFS))
 i m having problem 'Error compiling for board Generic ESP8266 Module' with this massage.
i m using :    board: Generic ESP8266    /  arduino IDE 1.8.7    /  ESP8266 Arduino Core v2.3.0
 All libraries that u have mentioned in the WIKI page.
i have also tried to update this folder : AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\tools\sdk
(pasting the arduino esp cores manually but causes some library related error massages)

but if i select NODEmcu-12e from board anager, there is no compilation error.
_____________________________________________________________________________________________
i have trited the OTA using WLED_0.8.4_ESP01_512k.bin file
but it progresses only 19% and crashed

please consider my problems.....

**Comment by Aircoookie** [comment]
Hi! Thanks for your interest in WLED! I recommend you try installing the binary using [esptool](https://github.com/espressif/esptool). OTA only works on boards with 1Mb+ flash.

I use arduino core v2.4.2, but you have to change a few flags in the top of wled00.ino for it to compile with low enough flash usage.
