### ISSUE TITLE
Add URL to start the iOS app from other app

### ISSUE THREAD

**Issue by tijlvuyk** [Aircoookie/WLED#1620]
I would like to be able to start WLED iOS app from other app 

syntax would be like this "wled://"

This can be achieved by adding URL to plist.info of the iOS app, I think..

**Comment by mountainash** [comment]
This (https://github.com/Aircoookie/WLED-App) project might be a better place for this request.

**Comment by softhack007** [comment]
Closing, as its "wrong project". Please make a request in https://github.com/Aircoookie/WLED-App
