### ISSUE TITLE
using WLED App and ArtLight/E1.31 at the "same" time?

### ISSUE THREAD

**Issue by hmrickhoff** [Aircoookie/WLED#1625]
is it possible to controle the WLED LEDs via the APP when the ArtLight Mode is enabled?
at night i want to control my LEDs via xlights/madrix etc but at daylight i want to control the lights via hue/app for simple lighting.

**Comment by Aircoookie** [comment]
Yes, WLED will automatically revert to standard mode after the transmission from E1.31 stops. Even while a transmission is active, you can access the WLED UI and override (ignore) the transmission to use built-in controls, though I don't recommend it.
