### ISSUE TITLE
v0.13.0 send settings data to locIp

### ISSUE THREAD

**Issue by WoodyLetsCode** [Aircoookie/WLED#1630]
Hey,
I saw that a revamp of settings page is planned for v0.13.0, so here is a suggestion for it.
Currently when you change something in settings the data will be loaded into the same browsing context as the current one. The post request is sent to `http://[current-ip]/settings/leds`.
I would like it, if you handle this like you do in index.htm. If the local storage locIp is set, than use this ip as target. So if locIp is set the post request will be sent to `http://[locIp]/settings/leds`.
This would make it much easier to implement new features and to have better access to settings.

Thank you! 😄

**Comment by Aircoookie** [comment]
Hi, that is a great idea, thanks! :)

**Comment by blazoncek** [comment]
Done in 0.14-b3.
