### ISSUE TITLE
Flashing ESP32 with W25q128 flash onboard , how to do ? 

### ISSUE THREAD

**Issue by athlon1900** [Aircoookie/WLED#1648]
Hello !

I like to flash a ESP32 with W25q128 , but it fail.
Bootloader at 0x00000 and Image at 0x10000
On a W25q32 flash-chip the bootloader and image working great with these settings.

Do i need another adress for W25q128 ?
If yes , which adress for bootloader and image should be set ?

Thanks , athlon1900

**Comment by Aircoookie** [comment]
Hi, you have accidentally opened a duplicate issue. Closing this and I will reply to you in #1647 later :)

**Comment by athlon1900** [comment]
Thanks aircoookie !
Was my mistake , there was a failure in my browser , so i didn't noticed that.
