### ISSUE TITLE
[Request] Distinct boot preset when no connection found

### ISSUE THREAD

**Issue by drinfernoo** [Aircoookie/WLED#1649]
This is a request for being able to have a separate preset (single or cycle) when there is no WiFi connection.

I feel this would bring a similar feel to most commercial smart devices, in which they typically boot into a "pairing mode", accompanied by some type of visual indicator (blinking lights, from most of my experience), and after being "paired", settle into their standard behavior.

A typical use case would look like:

1. User boots WLED device
2. "No WiFi" preset gets shown at boot to prompt pairing
3. User pairs WiFi
4. WLED reboots with and displays the "paired" preset (possibly showing the "no WiFi" preset until a connection is established)

Would this be possible in the future?

**Comment by SpaceCadetLights** [comment]
You could do this easily in a usermod, it shows how to check if wifi is connected in the example usermod v2, and you could write a few lines of code that checked if it was connected, and if not then it would select a preset or a specific effect. Then when it did connect it would just select preset0 like a normal boot. Great idea :)
