### ISSUE TITLE
Feature request: AnalogClock custom colors (and brightness) for hrs/min/sec and 5min dots

### ISSUE THREAD

**Issue by DDNRN** [Aircoookie/WLED#1652]
I use analogclock overlay at some devices and have a design problem with fixed colors for the clock dots.
Using another affect in the background is possible but the colors don't meet the clock and even not to the "housing" this clock is set in.
Must be not to hard to implement a settings value for this 4 color codes?

Another wish on top is to combine the colors if one dot overlays another from the clock dots. Always searching for the mins or hours if one erases the other one at same minute LED. Easyest way is to add color codes together to have mixed colors.   

. . and thanks to all that work about WLED, its a fantastic project!

**Comment by blazoncek** [comment]
Done in recent updates and new usermods as well.

**Comment by jasmohan-narula** [comment]
I also need this feature request. Can anyone explain the how to set custom colors for clock? I'm unable to find the settings.
