### ISSUE TITLE
Wiki Effects/Pallette list triggers GitHub content abuse block

### ISSUE THREAD

**Issue by smartroad** [Aircoookie/WLED#1661]
Hi All,

Sorry if this is not the right place but I was looking at the Wiki and trying to look at the Effects. I noticed it would only load a certain number before giving up. At first I thought it was my computer/connection but when I went to another part of GitHub it said I had triggered some anti abuse system, stopping  GitHub from loading at all for a short while. The upshot is that I can never seem to load all the patterns and palettes.

Just wanted to mention it, again, sorry if this is the wrong place to report

**Comment by Aircoookie** [comment]
Hi!
Thank you for sharing this, that page contains a lot of embedded gifs that make upwards of 100 requests simultaneously, which I would say makes sense for Github to block, although it doesn't seem to happen for me at this point.
If this happens more, we might need to remove some effect/palette visualizations from that page and use a different approach :)
