### ISSUE TITLE
colortwinkle problem

### ISSUE THREAD

**Issue by tonyn0** [Aircoookie/WLED#1679]
Confirmed for someone that brightness levels below 7 cause this effect to freeze.

**Comment by toto79** [comment]
for me the effects stops with brightness <=20 if speed is set to 15. it seems that fcn fadeup works (so all lights are on) but fadedown works not. if i set speed to >200 i can set brightness to 4 ... in my conclusion there is a correlation between these propertiers

hope this helps.
