### ISSUE TITLE
Auto return to Solid effect when color pic. (not work when effects running)

### ISSUE THREAD

**Issue by marcoboutch** [Aircoookie/WLED#1690]
Hi,

When i pic color or call color from Home Assistant, WLED not change the color because effect already run. I know probably some effect can use this color but i think is a good idea have checkbox like

-Comeback to Solid effect when color change.

For now, i watch color from HomeAssistant and if color change, i force WLED to change for FX=0

Concret exemple: In my hot tub, WLED run effect and i say "Ok google, hot tub in blue"

Sorry im bad to speak english. Thank you ;)

**Comment by Aircoookie** [comment]
Hi! Sorry, this is not planned. Many effects utilize color and it would be very inconvenient if it switched back to Solid every time.
