### ISSUE TITLE
WLED is compatible with HD107S led ?

### ISSUE THREAD

**Issue by vincentbattez** [Aircoookie/WLED#1707]
Hello :) WLED is compatible with HD107S led ? I don't see it on [compatible led stripe](https://github.com/Aircoookie/WLED#-compatible-led-strips)

If they not, can we add incompatible section on the readme ?
If yes, can we add add the 'HD107S' word to be more clear ?

**Comment by legorreta** [comment]
Hi Vincent,

HD107S are just like APA102. So it will be compatible. I am using it in my project, I replaced the APA102 with it.
