### ISSUE TITLE
White does not show up on PEEK

### ISSUE THREAD

**Issue by Skiidlive** [Aircoookie/WLED#1716]
White does not show up on PEEK viewer when using RGBW and "accurate" is selected.  All effects and colors work correct on the led's but anything white no longer shows in the PEEK viewer.  If I change the white setting to say "both" it works.  Using SK6812 strips.

**Comment by Aircoookie** [comment]
Thank you for the report!
This is an issue with conversion from RGBW back to RGB for display in the Peek bar. I have made a patch in the dev branch so that at least the RGB component of the color is correctly displayed. It will be merged to master soon and be part of the next release :)

**Comment by Skiidlive** [comment]
Awesome. Thank you.  Amazing work you are doing.

**Comment by ChuckMash** [comment]
Seems like this is still happening, I'm not seeing white channel data in peek / websockets live view data.
