### ISSUE TITLE
SP501e wled running - no leds come on

### ISSUE THREAD

**Issue by mauritsje** [Aircoookie/WLED#1725]
Hi there,

ive got several ESP32 boards running just fine, and had a a spare SP501e so I flashed that to WLED 0.11.1 esp8266 1M.bin

Now Wled is running just fine (can also access the http) but the LEDS are not coming on, should I have used a other .bin version  or should the Data wire be resoldered to a other point.

Thanks Maurits

**Comment by mauritsje** [comment]
Solved it by compiling a custom WLED with other pinout.

**Comment by jaredgisin** [comment]
Looks like this issue can be closed now.
