### ISSUE TITLE
Only first 3 LEDs light up, no control

### ISSUE THREAD

**Issue by senex44** [Aircoookie/WLED#1728]
Hi! 
I have an ESP8266 (exactly [this ](https://www.az-delivery.de/products/copy-of-nodemcu-lua-amica-v2-modul-mit-esp8266-12e?variant=36247507474) here) [[PINs](https://cdn.shopify.com/s/files/1/1509/1638/files/NodeMCU_Lua_Lolin_V3_Pinout_Diagram.pdf?16469362585003288970)] & a BTF-LIGHTING WS2812B ([amzn](https://www.amazon.de/gp/product/B088BRY2SH/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1)). 
I've flashed WLED_0.11.1_ESP8266_ledpin4.bin to the ESP and can see the WLED-AP. I've included it in my network and can access the WLED web page. 
**Nevertheless, only the first 3 LEDs light up, first one blue, second green, third red. There is no control possible,** they just light up when they get power from the ESP. With and without Data cable connected.
Data cable doesn't change this (plugged in/plugged off). +5V cable is connected to `VU`
The ESP'S blue light lights up, when the data cable is connected to D4, not when it is connected to D2. 
I've tested the data cable at both ends of the light strip, but for normal I am working in flow direction of the small arrows on the strip.
_Does someone know what's wrong here?_
![IMG_20210206_172718 - Kopie](https://user-images.githubusercontent.com/63457786/107124039-96906180-68a1-11eb-9359-5a2361bfa28b.jpg)

**Comment by asb2106** [comment]
GPIO pin 4 is actually pin D2 on the nodemcu you got there :) Move your green data wire there from D4 to D2 and you should light up.  you wont have a lot of power for the lights going through the usb like that, ive never tried.  get some power injected and you are good to go

**Comment by senex44** [comment]
Unfortunately, this does not make any difference with a separate power unit. But I found a LED ring, and it's directly working smoothly. So I guess the LED stripe is somewhat broken or so. Sorry for that and thanks for the advice!
