### ISSUE TITLE
2 x WLED kommen sich in die Quere. 

### ISSUE THREAD

**Issue by SeriousOri** [Aircoookie/WLED#173]
Hallo Aircoookie
Ich habe auf 2 Wemos D1 Mini je ein Wled drauf. Einmal eine Kugel und einmal ein LED Streifen unter einem Schreibtisch. Habe beide Wemo' s in der FritzBox Feste Ip's vergeben. Beide Wemo's habe ich anders benannt. Wenn ich Alexa schalte Kugel sage, schalten sich beide ein. Wenn ich Farbwechsle das selbe. Was kann ich machen, das ich die unterschiedlich bedienen kann? 
Wie ist das überhaupt möglich das ich sie gleichzeitig bedienen kann? Trotz Unterschiedliche IP und Name.

**Comment by Aircoookie** [comment]
Hi,
das ist das WLED Sync Feature, mit dem sich mehrere Lampen gruppieren lassen.
Einfach in die Sync Einstellungen gehen und den Haken bei "Send notifications on direct change" wegmachen. Dann rebooten und es sollte klappen :)

**Comment by SeriousOri** [comment]
Danke dir werde es mal so einstellen.
