### ISSUE TITLE
Web UI not reachable Ver. 0.11.1

### ISSUE THREAD

**Issue by br41n79** [Aircoookie/WLED#1735]
Hi, 

i cant reach the Webfrontend also. Neither with mobile (iPhone 12), Browser (Firefox/ Safari/ IE).
After turning on it works for 2-3minutes and later on only sometimes for a short time period. 

Some Info:
"ver":"0.11.1","vid":2012180,"leds":{"count":300,"rgbw":false,"wv":false,"pin":[2],"pwr":400,"maxpwr":7000,"maxseg":12,"seglock":false},"str":false,"name":"WLED","udpport":21324,"live":false,"lm":"","lip":"","ws":0,"fxcount":116,"palcount":55,"wifi":{"bssid":"F0:B0:14:7F:67:75","rssi":-75,"signal":50,"channel":6},"fs":{"u":40,"t":1024,"pmt":1612631519},"arch":"esp8266","core":"2_7_4_7","lwip":1,"freeheap":22080,"uptime":626250,"opt":127,"brand":"WLED","product":"FOSS","mac":"483fda78113f"}

Changing the WiFi-Channel/ reinstall did not work. 

Since yesterday the commands send vir ioBroker also "get lost". 
Tried several solutions e.g. put Wemos D1 mini direct net to accesspoint, restart everything etc. 

Best
Michael

**Comment by Plisken78** [comment]
My device is also lost after updating.
