### ISSUE TITLE
Request* Automotive use

### ISSUE THREAD

**Issue by craigrobbo** [Aircoookie/WLED#1737]
Would it be possible to impliment automotive use so that we can have several inputs to control certain functions such as, brakes, reverse, indicators running lights?

**Comment by sansillusion** [comment]
I think that would be better suited for a usermod.
One could create segments and have input pins contol each segment
individually.
ESP32 would be best suited.for this I guess given it usually has more input
pins.

>

**Comment by tonyn0** [comment]
There have already been several requests for supporting more than one button. Would be a great addition to 0.12 if it could be snuck in!
