### ISSUE TITLE
Hardware support for ESP32 D1 MINI

### ISSUE THREAD

**Issue by mgcrea** [Aircoookie/WLED#1739]
I recently bought a pack of 3 [ESP32 D1 MINI](https://www.az-delivery.de/en/products/esp32-d1-mini) that I intended to use with WLED.

Unfortunately it does not work out of the box, tried both `default` and `gpio16` builds.

Did build and flash locally trying many supposedly available pins with no luck.

Tried with and without a logic level shifter.

Uncommented `#define USE_WS2801` (not sure if required but I'm driving ne-pixels).

Any ideas of things I could try?

**Comment by k7bbr** [comment]
I've used the ESP32 minis. Try compiling with the `[env:wemos_shield_esp32]` build.

**Comment by mgcrea** [comment]
Just realised that I forgot to toggle the RGBW setting -_-, it's working now, thanks for the help anyway!
