### ISSUE TITLE
Sonoff L1 support

### ISSUE THREAD

**Issue by ShonP40** [Aircoookie/WLED#1747]
Hello, I have a Sonoff L1 LED strip with its ESP8285 based "Spider Z" controller.
I am currently running Tasmota on it and was wondering if WLED supports it or not.

The ESP8285 in the controller connects to a Nuvoton chip which then connects to the non-addressable 5050 LEDs.

**Comment by srg74** [comment]
If you running Tasmota than most likely you can use it with WLED too. Only one thing you need a custom firmware with proper pins as outputs.

**Comment by ShonP40** [comment]
Yea, figured that.
Well, I’ll see what I can do with it.
Thanks
