### ISSUE TITLE
not possible to enter more than 500 Led count

### ISSUE THREAD

**Issue by Daniel-Hasibar** [Aircoookie/WLED#1748]
I am new to this topic, I recently installed 4 W Leds with Nodemcu 8266 board. 

the first 2 boards were installed with 0.9x wled software. the second 2 boards with 0.11. 

In the App it says that all boards are 0.11.1 ( dont know why )

I also didnt get a Com on gpio4 / D2 as on 0.9x 

on 0.11.1 COM is  on Gpio3 / RX 

Long story short, on the new Wleds i cannot exceed the number of 500 Leds in the preferences

old 2 Wleds running fine with 600+

You got any advice? tried to raise the current with no succes

thanks Daniel

**Comment by toto79** [comment]
see FAQ: [Wled-Wiki](https://github.com/Aircoookie/WLED/wiki/FAQ#why-can-i-only-use-500-leds-on-the-esp8266-gpio-pin-3), you defined Pin3 or used a binary with Pin3 for Led-Control or edited Uart0/1 / DMA Method. Change Code in NpbWrapper (Line 7 or Line 144-147) or use another binary.
