### ISSUE TITLE
WS2811S 12V

### ISSUE THREAD

**Issue by yogi1325** [Aircoookie/WLED#1751]
Any ideas how to run the WS2811S 12V strip, as the diode trick work only on 5v strips?

Thank you in advance

**Comment by toto79** [comment]
My idea: Data-Line with 5V works on most 12V Strips, like ws2815. See [picture](https://github.com/toblum/McLighting/issues/351) for wiring.

**Comment by dmxlaser** [comment]
As i found  on my own setup, do not use logic transistor level shifters with ws2811, they cause flickering some times.
If its needed use the 74hct125 or the 74ahct125.
Level shifters with PNP transistors or PNP FETS are a very bad choise.

**Comment by koenslootmans** [comment]
Hello dmxlaser,

I am experiencing the problem that you reference too I belive, I have a 5m 12v led strip with in total 150 leds hooked up.
There is levelshifter on the dataline (DVAR-SPK11978 from sparkfun) , the strip is powered with a 5amp power supply (and the same supply is powering the wemos d1 mini that drives the led via a voltage reducer. all grounds are connected)

The strip works ok untill a certain point when I increase the brightness then the strips starts flickering. (depending on the choosen animation the brightness level at which flickering appears is different, it seems the more leds are lit at a given time the lower the brightness must be kept to not have the flickering effect.

My questions are the following:
- Is this indeed the behaviour when the level shifter is not ok ?
- the level shifters you are refering too are not on boards, how can I solder them ? (I am a newbie so this is probably a dumb question)
-

Thanks for any help much appreciated.
Cheers

**Comment by ghpk** [comment]
> Hello dmxlaser,
> 
> I am experiencing the problem that you reference too I belive, I have a 5m 12v led strip with in total 150 leds hooked up.
> There is levelshifter on the dataline (DVAR-SPK11978 from sparkfun) , the strip is powered with a 5amp power supply (and the same supply is powering the wemos d1 mini that drives the led via a voltage reducer. all grounds are connected)
> 
> The strip works ok untill a certain point when I increase the brightness then the strips starts flickering. (depending on the choosen animation the brightness level at which flickering appears is different, it seems the more leds are lit at a given time the lower the brightness must be kept to not have the flickering effect.
> 
> My questions are the following:
> 
> * Is this indeed the behaviour when the level shifter is not ok ?
> * the level shifters you are refering too are not on boards, how can I solder them ? (I am a newbie so this is probably a dumb question)
> 
> Thanks for any help much appreciated.
> Cheers

Looks like a clear case of Low Power to the LED's

Try powering the strip from both ends and it should be fine.

**Comment by dmxlaser** [comment]
> Hello dmxlaser,
> 
> I am experiencing the problem that you reference too I belive, I have a 5m 12v led strip with in total 150 leds hooked up.
> There is levelshifter on the dataline (DVAR-SPK11978 from sparkfun) , the strip is powered with a 5amp power supply (and the same supply is powering the wemos d1 mini that drives the led via a voltage reducer. all grounds are connected)
> 
> The strip works ok untill a certain point when I increase the brightness then the strips starts flickering. (depending on the choosen animation the brightness level at which flickering appears is different, it seems the more leds are lit at a given time the lower the brightness must be kept to not have the flickering effect.
> 
> My questions are the following:
> - Is this indeed the behaviour when the level shifter is not ok ?
> - the level shifters you are refering too are not on boards, how can I solder them ? (I am a newbie so this is probably a dumb question)
> -
> 
> Thanks for any help much appreciated.
> Cheers

Hi there.
The DVAR-SPK11978 from sparkfun was my first choise and also was the problem.
You can try to find a schematic with the sn74hct125n and solder it by yourself or 
try the TXS0102  breakout board if you don't 
want something like the DVAR-SPK11978 from sparkfun.

**Comment by koenslootmans** [comment]
Hello, Thanks for the comment

I just managed to fix the problem yesterday, I soldered all unused ports on
the board to the ground and the problem is now gone,
The lights are now 100% stable

Cheers,
Koen
