### ISSUE TITLE
ESP32 DevKit not connect to wifi

### ISSUE THREAD

**Issue by arigia62** [Aircoookie/WLED#1753]
I have completed the flashing of two ESP32 Dev KITs using ESPHome-flasher and after the reboot while seeing the WLED AP network on my mobile I cannot connect.
After entering the password, the network disappears from the list and reappears after a few seconds.

The router is located about 1 meter from the board and the fixed red LED and the flashing blue LED are on on the card.

The problem is present whether the board is powered via USB or applying 5V to the VIN and GND pins (5V - 2A power supply)

For completeness, I report the ESPHome-flasher screen shot at the end of the flashing
![esphomeflasher](https://user-images.githubusercontent.com/79118101/108049623-d0532c00-7048-11eb-9e57-b3a825880917.jpg)

**Comment by Doyle4** [comment]
Unplug the module, I get this error sometimes but still works after.

**Comment by arigia62** [comment]
Hi Doyle4, I followed your advice but the problem remains (I also tried with an RSP8266 -F12 Dev Kit). In the list of available wifi networks, WLED AP appears but as soon as I enter the pw (wled1234) it makes me the message "it is not possible to connect to this network" and the network disappears from the list

**Comment by Doyle4** [comment]
Try using this flasher.
https://github.com/nodemcu/nodemcu-flasher

Baud set to 460800
Flash 40mhz
SPI DIO

**Comment by Model-Man** [comment]
ESP home flasher does not format and partition a ESP32 correct and can cause issues. As advised try a different flasher then check your available memory. It should be around 1500Kb.
