### ISSUE TITLE
HUZZAH 32 /feather IO2 

### ISSUE THREAD

**Issue by Yyov** [Aircoookie/WLED#1757]
Hello, 

i am using a Feather Huzzah 32. 

The requested port is not brought out of the board. i read that it is possible to change these settings but i lack the knowledge to recompile the .bin fille. 

can i get some help with this? 

Kind Regards! Yov

**Comment by srg74** [comment]
You can use Discord #bot to compile custom firmware for your board. If you not able to do yourself ask someone and you will receive help.

**Comment by Yyov** [comment]
> 
> 
> You can use Discord #bot to compile custom firmware for your board. If you not able to do yourself ask someone and you will receive help.

Thx, as i said, i lack the knowledge to do this so help would be welcome :) as i can see in the other questions it seems like a easy job for someone who knows what he is doing!
