### ISSUE TITLE
Color selection wheel blacked out

### ISSUE THREAD

**Issue by mentaluproar** [Aircoookie/WLED#176]
Me and my roommates iPhones (an X, 7, and xr) cannot see the color wheel. It’s solid black. I can still select colors with it, but it’s all black so we can’t really see what we are aiming for.

**Comment by StormPie** [comment]
Hey! Are you just using Safari? Does it work using a laptop/computer or an Android device?

**Comment by mentaluproar** [comment]
Yes, it’s otherwise fine. I just tried it on Firefox for iOS and it’s fine.

**Comment by mentaluproar** [comment]
Any news on a fix?

**Comment by Aircoookie** [comment]
Sorry for not replying earlier, I currently lack an iOS device for testing this.
Does it also happen on this page? https://iro.js.org/ If it works fine, we might be able to fix by updating the colorpicker library.

**Comment by mentaluproar** [comment]
Yes. That one works fine. I can’t really do much resting on an updated version though because of another issue. My 8266 won’t respond when Bluetooth coexistence is enabled on my router. I turn that off and literally all Bluetooth in the house goes haywire.

**Comment by mentaluproar** [comment]
Looks like you were right.  V4 is listed as fixing this very issue in the migration guide.
https://iro.js.org/migrating.html

**Comment by Aircoookie** [comment]
0.9.0 UI is now using V4 :)
