### ISSUE TITLE
Segment config lost between restarts 

### ISSUE THREAD

**Issue by reynos** [Aircoookie/WLED#1770]
Anyone had this issue? 
After a power cycle the segment info resets to the default (only Segment 0 remains)
I have had this happen on my current QLED hw and also on a generic ESP8266 setup.

**Comment by blazoncek** [comment]
Save a preset.

**Comment by pa1okz** [comment]
Yup, segments are only remembered by storing them in presets.

**Comment by kmalinich** [comment]
Literally this

https://github.com/Aircoookie/WLED/wiki/FAQ#my-segments-are-gone-after-a-reboot

I had the same issue happen when I started using segments, but I was able to find that wiki page on this repo via a Google search

**Comment by Aircoookie** [comment]
#1926 opened as a feature request for auto saving on change.
