### ISSUE TITLE
More ESP8266 with Wled with Alexa

### ISSUE THREAD

**Issue by mphiruhr** [Aircoookie/WLED#1772]
Is it possible to connect more than one ESP8266 chip with WLED to my Echo?

Or is this not possible, if so I would be grateful for a howto.

Sorry I am from Germany and my English is not so good.

**Comment by mphiruhr** [comment]
Update: I have both chips connected to my Alexa, but I can only add one particular chip in a group, when I want to add the other it always adds the other lamp.

**Comment by Aircoookie** [comment]
Hi! Alexa groups not working correctly is currently a bug that will be resolved for the 0.12 release coming in March :)

**Comment by mphiruhr** [comment]
Hi, thx for the infos
