### ISSUE TITLE
Power On does not work if WS2812B connected

### ISSUE THREAD

**Issue by DSRocker** [Aircoookie/WLED#1777]
Everything is connected correctly. If the LED strip is connected to the ESP GPIO2 and I power on the esp, then it does not work. Only the first LED is on. If the strip is disconnected and I power on the esp and then connect the strip, then it works fine.

**Comment by tonyn0** [comment]
This likely means you need a pull-up resistor (~10k) between the gpio and 3.3v pins.

**Comment by DSRocker** [comment]
Which GPIO?

**Comment by DSRocker** [comment]
I tried it with GPIO 0 and GPIO 2. It does not work

**Comment by pa1okz** [comment]
R U sure you use the same GND for the LED strip and the ESP? Make sure that no excessive current from the LED strip is drained from the ESP PCB. Here is how connections shall be done: https://github.com/Aircoookie/WLED/wiki

**Comment by bl33ding-edge** [comment]
I had the same problem, the pull up resistor on gpio 2 did the trick!
3V3---10K---D2---WS2812B.DIN

**Comment by ashinckley** [comment]
I've tried a pull up resistor of 10k as suggested in this thread, a 3.3k and a 4.2k as suggested in the [FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ#once-i-attach-leds-i-cant-connect-to-the-esp-anymore).  Each time I power on with the D2-DIN connection, resistor or not, I cannot see the ESP WiFi AP.

**Comment by DSRocker** [comment]
You have to use another GPIO! I think there is no other way.
-------- Ursprüngliche Nachricht --------Von: ashinckley ***@***.***> Datum: 16.03.21  14:49  (GMT+01:00) An: Aircoookie/WLED ***@***.***> Cc: DSRocker ***@***.***>, Author ***@***.***> Betreff: Re: [Aircoookie/WLED] Power On does not work if WS2812B connected
  (#1777) 
I've tried a pull up resistor of 10k as suggested in this thread, a 3.3k and a 4.2k as suggested in the FAQ.  Each time I power on with the D2-DIN connection, resistor or not, I cannot see the ESP WiFi AP.

**Comment by ashinckley** [comment]
> You have to use another GPIO! I think there is no other way. -------- Ursprüngliche Nachricht --------Von: ashinckley ***@***.***> Datum: 16.03.21 14:49 (GMT+01:00) An: Aircoookie/WLED ***@***.***> Cc: DSRocker ***@***.***>, Author ***@***.***> Betreff: Re: [Aircoookie/WLED] Power On does not work if WS2812B connected (#1777) I've tried a pull up resistor of 10k as suggested in this thread, a 3.3k and a 4.2k as suggested in the FAQ. Each time I power on with the D2-DIN connection, resistor or not, I cannot see the ESP WiFi AP. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Which GPIO? Were you able to get it to work?  Did you have to recompile with a different GPIO value?

**Comment by DSRocker** [comment]
Yes... it works with gpio 14... you have to recompile with other gpio
-------- Ursprüngliche Nachricht --------Von: ashinckley ***@***.***> Datum: 16.03.21  15:50  (GMT+01:00) An: Aircoookie/WLED ***@***.***> Cc: DSRocker ***@***.***>, Author ***@***.***> Betreff: Re: [Aircoookie/WLED] Power On does not work if WS2812B connected (#1777) 



You have to use another GPIO! I think there is no other way. -------- Ursprüngliche Nachricht --------Von: ashinckley @.> Datum: 16.03.21 14:49 (GMT+01:00) An: Aircoookie/WLED @.> Cc: DSRocker @.>, Author @.> Betreff: Re: [Aircoookie/WLED] Power On does not work if WS2812B connected (#1777) I've tried a pull up resistor of 10k as suggested in this thread, a 3.3k and a 4.2k as suggested in the FAQ. Each time I power on with the D2-DIN connection, resistor or not, I cannot see the ESP WiFi AP. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



Which GPIO? Were you able to get it to work?  Did you have to recompile with a different GPIO value?
