### ISSUE TITLE
ws2801

### ISSUE THREAD

**Issue by ricardo-brenner** [Aircoookie/WLED#178]
Can you make it compatible with ws2801 strips?

**Comment by Aircoookie** [comment]
The WS2801 are not supported by NeoPixelBus (the LED driver library WLED uses), so this isn't easily possible.
If one was to rewite the `NpbWrapper.h` file to interface with the Adafruit WS2801 library, it could work.
Definitely something to keep in mind!

**Comment by Sirup55** [comment]
That would be suuuper awesome! :)

**Comment by kolossboss** [comment]
I'm also interested!

**Comment by pixeye33** [comment]
Maybe this : https://github.com/r41d/WS2801FX could help/inspire ?

**Comment by webben-de** [comment]
like to have this feature, too

**Comment by ricardo-brenner** [comment]
Those are great news, I'll rescue my old strips back to life. Tks
