### ISSUE TITLE
Unable to connect to WLAN

### ISSUE THREAD

**Issue by kanawati975** [Aircoookie/WLED#1792]
Greetings everyone, and thanks to everyone helped in this great Project.

I have an issue and I was hoping that someone could tell me what am I doing wrong.

So... Using Platformio I have uploaded the code to a D1 mini, which was without any Problems... Accessed WLED-AP and assigned wifi data, and saved. But it won't connect to the wireless network. (I'm also checking my Router for any connection).

Tried fiddling around with the code, and uploaded it again, to no avail.

Tried another D1 mini Chip... disabled unneeded functions... also didn't help.
Tried accessing the D1 mini via 4.3.2.1 and re-flashed using the .bin file... also didn't help
Tried deleting the code, and uploading on a trusted (verified) NodemcuV2 but also didn't work.
The wifi Network is 2.4GHz and the chip's MAC address is identified and saved in the router.

What am I missing? Why can't it connect to wifi?

Any help would be appreciated.

**Comment by gobo-ws** [comment]
Now I do not know if it is due to this but do you use any special characters in your WPA2 key?
If so, they need to be escaped.
https://github.com/xoseperez/espurna/issues/1439

**Comment by kanawati975** [comment]
@gobo-ws Actually there is one. But not sure if that's somehow relevant
