### ISSUE TITLE
Unable to connect to WIFI

### ISSUE THREAD

**Issue by LeducH** [Aircoookie/WLED#1793]
**Describe the bug**
I am unable to connect to my home wifi 

**To Reproduce**
connect to the via the wifi setup 
enter SSID and password 
it shows client ip : not connected 

**Expected behavior**
connects to my home wifi 

**WLED version**
 - Board: ESP8266 node mcu
 - Version 0.11.1
 - Format `WLED_0.11.1_ESP8266.bin`

**Additional context**

I am able to connect to the wifi `WLED-AP` and set up the wifi. My home network SSID and password only have letters and numbers. 
I use a fritzbox with 2.4 and 5GHz connection

**Comment by Aircoookie** [comment]
Hi, sorry about that! Is your WiFi 2.4GHz? What router/access point do you use?

**Comment by LeducH** [comment]
I use a fritzbox with 2.4 and 5GHz connection. But it is connected via 2.4Ghz

**Comment by sigsegv0** [comment]
How about the case you're using for SSID? I want to say it's case sensitive and needs to  match the router's definition of SSID.

**Comment by rjworks** [comment]
did you fix it
