### ISSUE TITLE
disconnecting/connction issue 

### ISSUE THREAD

**Issue by LeducH** [Aircoookie/WLED#1794]
**Describe the bug**
the board keep trying to reconnect/connect the wifi 

**To Reproduce**
set up the board 

**Expected behavior**
stays in wifi network 

**WLED version**
 - Board: ESP8266 node mcu
 - Version 0.11.1
 - Format `WLED_0.11.1_ESP8266.bin`

**Additional context**
I can see in my router that the board keeps reconnecting

**Comment by imroue** [comment]
I have the same issue as @LeducH . It doesn't stay in the wifi network very long.
    
My power supply is 5v to the board and 12v to the leds.

**Comment by giddyhup** [comment]
Same issue. Perhaps it's the wifi/AP used. In my case it's a Unifi AP.

**Comment by Legsmaniac** [comment]
I have UniFi, no issues.

Is it possible that the DNS which is fixed to 8.8.8.8 (Google) in the code could have anything to do with it for some users who have WiFi connectivity issues? 
I once helped someone who was having WiFi connection problems (not WLED) who was using Google DNS servers. It was only after scratching my head long and hard after trying everything I could think of that I decided to try changing 8.8.8.8 to his routers own DNS which was his Gateway address (as it is in most cases) and his connection woes disappeared.  I'm sure I read somewhere that in some countries, Google DNS is blocked.
Unfortunately, the DNS cannot be changed in WLED WiFi settings, it would need to be changed in the code and recompiled but it may be worth a try for some of you with connection issues. Perhaps @Aircoookie will consider adding the option to set our own DNS in future versions? 🙂

**Comment by giddyhup** [comment]
> I have UniFi, no issues.
> 
> Is it possible that the DNS which is fixed to 8.8.8.8 (Google) in the code could have anything to do with it for some users who have WiFi connectivity issues? 
> 
> (...) Perhaps @Aircoookie will consider adding the option to set our own DNS in future versions? 🙂

This would definitely be a good thing. Devices that ignore the DHCP-assigned DNS may be considered evil in some networks.  

I have to look into this since my network actually blocks queries not going to the assigned DNS.

**Comment by Legsmaniac** [comment]
> I have to look into this since my network actually blocks queries not going to the assigned DNS.

Precisely.
The file to to make changes is `wled.cpp`
For Ethernet users look for `ETH.config(staticIP, staticGateway, staticSubnet, IPAddress(8, 8, 8, 8));` and either change the 8,  8,  8, 8 to a DNS of your own choosing or use `ETH.config(staticIP, staticGateway, staticSubnet, staticGateway);` to that of your router's Gateway, which is the most common. 
For WiFi users look for `WiFi.config(staticIP, staticGateway, staticSubnet, IPAddress(8, 8, 8, 8));` and change to `WiFi.config(staticIP, staticGateway, staticSubnet, staticGateway);` or your own DNS numbers as suggested above. 
Save, recompile and upload/flash to your Arduino.
Hopefully this could solve many users connection issues.
