### ISSUE TITLE
How flash ESP32 by firmware with bootloader ( beta)

### ISSUE THREAD

**Issue by pepsonEL** [Aircoookie/WLED#1797]
Hi. How i can flash WLED firmware with Bootloader as i see new version BETA ?

**Comment by Ramblurr** [comment]
I'm also wondering this. The instructions in both wikis refer to the separate bootloader file.

**Comment by Aircoookie** [comment]
I don't currently offer a combined binary. Is there a reason why flashing the bootloader file first is a problem? For the most easy installation i recommend install.wled.me :)
