### ISSUE TITLE
Esp32 Multi Strip /io

### ISSUE THREAD

**Issue by 9ghost9** [Aircoookie/WLED#1799]
Having disabled Crossfade in WLED only seems to affect the native Gpio and not the added Strips/Gpio .

Any help suggestions would be greatly appreciated .

Also , thanks so much for adding this mod .

**Comment by blazoncek** [comment]
If you are willing try the beta version (0.12).
You can get support on WLED Discord.

**Comment by gabyleon** [comment]
excuseme , where is the beta version?

**Comment by blazoncek** [comment]
> excuseme , where is the beta version?

You can compile it yourself from dev branch or use a precompiled version available at @srg74 WLED_wemos_shield repo.
https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/WLED_wemos_shield

Please join WLED Discord for further support.

**Comment by gabyleon** [comment]
@blazoncek, thank you, sir :-)

**Comment by 9ghost9** [comment]
> If you are willing try the beta version (0.12).
> You can get support on WLED Discord.

You are awesome my friend !!! thank you very much for this works like a charm.
