### ISSUE TITLE
question about wifi

### ISSUE THREAD

**Issue by richyxi** [Aircoookie/WLED#180]
hi, is it possible to have some kind of wifi manager, to add the credentials of the network to the ESP8622  through that via?

thks in advance

**Comment by Aircoookie** [comment]
Hi!
WLED works really similar to WiFi manager. Just flash the software as-if, connect to the WLED-AP and enter your home network in WiFi settings ([full tutorial](https://github.com/Aircoookie/WLED/wiki#quick-start-guide)).
I might add Captive portal soon to simplify this process even further.
