### ISSUE TITLE
Wemos D1 mini Pro - problem with SK6812 , Ws2812B

### ISSUE THREAD

**Issue by Rafal-PL** [Aircoookie/WLED#1802]
Hello , Wemos D1 mini Pro does  not work with mini led SK6812 WS2812B , but to works perfectly with WS2811 - where is the problem?

**Comment by srg74** [comment]
Please visit Discord WLED channel for further issue investigation

**Comment by Sangoku** [comment]
I am using an esp32 D1 mini custom compiled and WS2812B  works without problems. Could you try to add the data pin after some length? 
It could be your 1st led is broken.

**Comment by Rafal-PL** [comment]
Hello everyone, I have a wemos d1 mini pro and a led string
![DC5V-USB-SK6812-dekoracyjne-wiat-o-LED-String-do-sypialni-WS2812B-wiat-a-LED-RGB-Bluetooth jpg_q50](https://user-images.githubusercontent.com/80586914/111234359-aa408d80-85ee-11eb-8911-8467ea972ecb.jpg)

I connect: Pin D4  - Data, power pin 5V and GND and it does not work. I connected the power supply to the 3.3V pin once and it worked for a while and stopped for a while. I connect the same LEDs to ESP32 and everything works. Somewhere read that you may need to apply a resistor on pin D4?

**Comment by LocalNic** [comment]
Looks like the same or similar problem that I have faced and documented my findings here #2342

**Comment by blazoncek** [comment]
These may not be SK6812 but are WS2812 instead.

**Comment by darkmattercoder** [comment]
I experience the same, with the same product. They seem to have a white led, so they cannot be ws2812 afaik. I also have very weird behaviour. Data line looks like being not in the middle but on the outside. However, what weird is, even if I connect the outside line to data from the wrong end, controlling kinda works (when set to sk6812, used a lot more leds than there physically are) however colors are messed up completely. If I use the middle wire for data, no matter which end i connect it, no controlling works at all. Neither with ws281x nor sk6812 settings. 

Atm I am lost. A friend of mine apparently could control the strip with an sp110e controller. I still need to confirm that myself.

**Comment by blazoncek** [comment]
Those may have addresses _burned in_ so they will still work even if one fails (bus topology as opposed to daisy chain topology).

**Comment by darkmattercoder** [comment]
after further investigation in #2342 i can confirm what you are saying. References can be found in #1312. So it is no sk6812 at all. The white LED I did mentioned before does not exist in those. Thus is more like ws281x protocol-wise.
