### ISSUE TITLE
Show sliderbubble even when FX list scrolled

### ISSUE THREAD

**Issue by jdtsmith** [Aircoookie/WLED#1810]
**Is your feature request related to a problem? Please describe.**
I _love_ the new sliderbubble showing speed and intensity value as you slide.  But when you scroll the list of effects, it is not displayed.  So you must scroll all the way up, set the slider, then remember which effect you had set and scroll back down. 

**Describe the solution you'd like**
By placing the bubble on _top_ the bar (higher z-index), and moving it from the left to right side as the slider passes the mid-way point, you could easily have it displayed even when the effects list is scrolled down.  As currently, it would remain hidden when not actively sliding. 

**Describe alternatives you've considered**
Alternatively, a small background-free number could be placed below the icon at left of the slider bar, but this may be difficult for mobile users to read.

**Additional context**
Here's a "while-sliding" mock-up with the bubble to the left side (since the slider is right of center):

![image](https://user-images.githubusercontent.com/93749/111786850-a2a21280-8894-11eb-8e25-b52ab114b8e6.png)

**Comment by blazoncek** [comment]
This is fixed in @andyshinn PR #1685 .
