### ISSUE TITLE
palette preview and search 0.12beta

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1813]
How do I enable this? Flashed the 0.12beta to my D1 Mini and the palette preview and search isn't showing, looked in UI setting and couldn't see anything to change, Thanks.

**Comment by sansillusion** [comment]
I had to refresh my browser to see it.

**Comment by Doyle4** [comment]
> I had to refresh my browser to see it.

Hard refresh did the trick! Thanks!
