### ISSUE TITLE
NodeMCU ESP8266 hw-628 v1.1

### ISSUE THREAD

**Issue by stream74** [Aircoookie/WLED#1814]
Hello

sorry for bad english, i'm french :)

I've got some problem with code

i try many thing but nothing work
it work perfectly with esp32 but not with esp8266 version hw-628 v1.1

i think i know what the problem but too many thing to change for me

when i change the   WiFi.begin(clientSSID, clientPass);
who are 
WLED_GLOBAL char char clientSSID[33] _INIT(CLIENT_SSID);
WLED_GLOBAL char char clientPass[65] _INIT(CLIENT_PASS);

by

const char *clientSSID= CLIENT_SSID;
const char *clientPass = CLIENT_PASS;

  WiFi.begin(clientSSID, clientPass );

it connect to my router
if i don't do these it doen't see my router

the same thing i think with the appass
i'cant connect to wled password doesn't work

i think there is a problem with recognize string

**Comment by ghpk** [comment]
Are you compiling from available source,
If Yes, Why not use pre-compiled bin file Aircookie has shared already.

**Comment by stream74** [comment]
hello
i try many thing
compil whith arduino
and pre-compiled fin
same thing happen

**Comment by sansillusion** [comment]
I guess you have some special characters in your SSID or passkey. You may need to escape those characters. But standars don't recommend using special characters on an AP/router

**Comment by stream74** [comment]
thank you for your answer
i know i don't speak very well english

he don't see my router
but the same thing happen when i wan't to connect to it with acces point
when i enter the _**AP_PASS     "wled1234"**_ 
he don't recognize it and disconnect

but i don't have this problem whith the example code esp8266 wifiacces point

wled code don't recognize any string

no problem with my esp32

only problem with the ESP8266 hw-628 v1.1

but when i change code like esp8266 example:
**const char *ssid**

it recognize everything

**Comment by stream74** [comment]
hum i don't know why it don't work with my esp8266 version hw-628 v1.1
i test with esp 01S and no problem
