### ISSUE TITLE
0.12.0b2

### ISSUE THREAD

**Issue by balucanb** [Aircoookie/WLED#1827]
Just got into using WLED love it. Thanks for all the hard work. I am asking this as a question because I do not have enough info to know if this is a issue or not. My money is the problem is me doing something wrong...
I am using a Dig-Quad with a ESP32, 2812b lights- 528 total broke down into 2 sets, using 2 data connections.
ESP flashes fine, (WLED_0_12.0_b2_ESP21.bin) UI comes up in Chrome (windows box) everything seems fine. The issue is when I put the ESP back onto the quad I get nothing, no lights and the UI seems to be locked up. I have flashed it a few times, same every time. I know the "hardware" is good because it works fine with 0.11 and with the 4 channel version (QuinLED). Can you help me out. TIA.

**Comment by jaredgisin** [comment]
The fastest way to get an answer to a question like this is either on the [WLED](https://discord.gg/KuqP7NE) or [QuinLED](https://discord.gg/WdbAauG) Discord servers.
