### ISSUE TITLE
0.12.0b2 Issue with E1.31

### ISSUE THREAD

**Issue by mre150** [Aircoookie/WLED#1828]
When sending data over e131 from xlights to a 512 pixel matrix of ws2812b the nodemcu reboots itself every few seconds. 
This can been seen by the matrix going off then all pixels going orange and then back to the data being sent before looping. 

I have no issues with my tests on strings upto 277 pixels. Just with the 512 pixel model. 

This is using esp8266mod and 5v ws2812b flex matrix panels. 

I went back to 11.1 and the problem disappeared and all worked as normal.

**Comment by mase76** [comment]
I suggest to use DDP instead of E1.31. It is somewhat faster and more powerful.
