### ISSUE TITLE
connecting analog rgb tape

### ISSUE THREAD

**Issue by mrgray777** [Aircoookie/WLED#1831]
Hello everyone! tell me where can I find information on connecting analog rgb tapes? I cannot find such information, only incomprehensible pieces and general information. interested directly three-channel tape: red green blue

**Comment by WoodyLetsCode** [comment]
Hello,
if you know the width of your led strip you can search for connectors.
Maybe you are looking for something like this: https://de.aliexpress.com/item/32242559186.html

**Comment by mrgray777** [comment]
> Hello,
> if you know the width of your led strip you can search for connectors.
> Maybe you are looking for something like this: https://de.aliexpress.com/item/32242559186.html

you have a good sense of humor)) however, I'm interested in how to connect a three-color or monochrome tape to a WLED controller instead of an address tape. the wiki does not describe this method, although it is stipulated that it is possible. that's what I would like to know)

**Comment by sansillusion** [comment]
You need MOSFET's to drive the current needed for analog LEDs, there
isnplenty of tutorial online for that. In wlet setup/led setup you can
chooses the type of LEDs and then the pins you wish to use. (0.12.x)

Le mar. 30 mars 2021 10 h 29 a.m., mrgray777 ***@***.***> a
écrit :

**Comment by ericksvasc** [comment]
did you manage to do that?
