### ISSUE TITLE
Possibility to control several relays

### ISSUE THREAD

**Issue by autonomobil** [Aircoookie/WLED#184]
Is there a possibility to control a 4-channel relay module, for example with pin D5-D8?
![IMG_20190703_184207](https://user-images.githubusercontent.com/31781343/60609586-4d715500-9dc2-11e9-8238-7008036c7c57.jpg)

If yes where should I start to implement it?

**Comment by bogeuh** [comment]
pick a method of control
control the relay with chosen method
then you will know what to add where
work bottom up instead of top down

**Comment by sjude68** [comment]
I have used 4 relays with Alexa control.  Add the code as per the example in espalexa.

**Comment by Bobinox** [comment]
@sjude68 can you share your code whit us? to take it as example 
thanks in advance

**Comment by sjude68** [comment]
@Bobinox 
[wled00.zip](https://github.com/Aircoookie/WLED/files/3829701/wled00.zip)

I added 4 relays and a temp/humidity sensor.  You can check the modified code in attached file.

**Comment by szurr** [comment]
Anyone try this with mqtt?

**Comment by sjude68** [comment]
> Anyone try this with mqtt?

Yes. I setup MQTT on Raspberry Pi and it works

**Comment by szurr** [comment]
Thank you I'll try this

**Comment by Bobinox** [comment]
thanks @sjude68 , whit your example i can make it work!
modified some of the code and voilà now i can control my relays whit alexa

**Comment by sjude68** [comment]
> thanks @sjude68 , whit your example i can make it work!
> modified some of the code and voilà now i can control my relays whit alexa

Even I modified for Alexa & mqtt control. It was modified within other scripts. I want to move the lines in usermod so when there is a version update, it will be easy to just copy the usermod.ino
