### ISSUE TITLE
Preset cycle transition time

### ISSUE THREAD

**Issue by AngieSoft** [Aircoookie/WLED#1843]
**Describe the bug**
transition time on preset cycle isn't working. 

Die Transiton time bei "preset cycle" wird nicht beachtet und auch nicht gespeichert.

**Comment by Aircoookie** [comment]
Hi, the transition time is not specific to preset cycle, it applies to all color and brightness changes.
This field is only applied if you use another control afterwards (I use the power button) and does not persist a reboot.
To set a transition time permanently, you can use the field in LED settings.

Hi, das Transition Time Feld gilt nicht nur für den Preset Cycle, sondern global für alle Farb-und Helligkeitsänderungen.
Um es zu speichern, einfach kurz den Power-Knopf oben links drücken.
Um eine Transition Time als Standard beim Boot zu setzen, gibt es eine Einstellung in den LED settings.
