### ISSUE TITLE
Alexa discover problem on NodeMCU 

### ISSUE THREAD

**Issue by Cosmicbase** [Aircoookie/WLED#1848]
Hello everybody,

 I use WLED on 3 different NodeMCU.
 Always the latest release.  After I have deleted the device (s) from Alexa, they are no longer found.  Tried everything from restart to reinstallation.  I am sure that the Alexa emulation worked. What's wrong?

Maybe there is a way to integrate belkin wemo emulation..It also works perfect with Alexa and Alexa Discover. 

 Please help
![Screenshot_20210402_002017_com android chrome](https://user-images.githubusercontent.com/31271212/113360014-3f5eb880-9349-11eb-862d-5eec41e8a997.jpg)
![Screenshot_20210402_002127_com android chrome](https://user-images.githubusercontent.com/31271212/113360095-66b58580-9349-11eb-90cf-e139b72868db.jpg)

**Comment by Cosmicbase** [comment]
I have now reinstalled everything, but on a Wemos D1 Mini. And here we go, the Alexa emulation works. I think that the Nodemcu is only suitable for this to a limited extent.

**Comment by VoidElle** [comment]
I have the same problem with a NodeMcuV3,
I have the alexa option active but alexa doesn't detect it!

I also tried to fix:
Restarting alexa
Restarting the nodemcu
Checking if the network is 2.4Ghz in both the devices

**Comment by etlon** [comment]
I have the same problem. NodeMCU ESP8266 with WLED but no working alexa emulation.

**Comment by etlon** [comment]
@Cosmicbase are you using the d1 mini esp8266 or the d1 mini esp32?

**Comment by Cosmicbase** [comment]
I use Wemos D1 Mini with Esp8266 chipset.

**Comment by VoidElle** [comment]
> I have the same problem with a NodeMcuV3 ESP8266,
> I have the alexa option active but alexa doesn't detect it!
> 
> I also tried to fix:
> Restarting alexa
> Restarting the nodemcu
> Checking if the network is 2.4Ghz in both the devices

The stable version 0.12 fixed this problem for me.

**Comment by Cosmicbase** [comment]
The stable version 0.12 fixed this problem for me too.
