### ISSUE TITLE
Feature request and clarification, fade to dark with schedule

### ISSUE THREAD

**Issue by erkme73** [Aircoookie/WLED#1855]
I am using my wled to control lighting for brooding chickens.  I currently have it scheduled to turn on and off around sunrise and sunset.  However, the transition is very abrupt and unnatural.   

Is there any existing way to have a present ramp up over x minutes when it first comes on, and ramp down when it turns off (like pressing the timer button)?

Also is there any way to tie the timer to actual sunset/sunrise give a specific geolocation?

The idea is to simulate dusk and dawn so the chicks have time to settle down.

**Comment by blazoncek** [comment]
You can create playlist with a very long transition from solid black to solid white (or whatever) and have it scheduled as normal. See wiki.
Actual sunrise/sunset trigger is planned for next release meanwhile you can use my fork, dev branch.
