### ISSUE TITLE
Infrared does not work in v0.12.0?

### ISSUE THREAD

**Issue by blogaster** [Aircoookie/WLED#1858]
**WLED version**
 - Board: ESP-12
 - Version 0.12.0
 - Format bin

Infrared don't work. I'm downgraded to 0.11.1 and IR working OK

Thank you for your help!

**Comment by Aircoookie** [comment]
Hi!
Have you verified that the Infrared pin in LED settings is set to 4 (the default in 0.11) and that an IR type is selected in Sync settings?

**Comment by blogaster** [comment]
Yes, it is enabled in the settings. I did not compile the bin, but downloaded the ready-made one from the release section

**Comment by blogaster** [comment]
I tried to compile from source files and all works!
