### ISSUE TITLE
Lights are not saved after they are discovered

### ISSUE THREAD

**Issue by myrulezzz** [Aircoookie/WLED#1861]
**Describe the bug**
After installing app on iphone my lights are discoverable and working.However after i close the app and open it again lights are not saved in my list and i have to rediscover them

**To Reproduce**
Deleted lights from iphone app. Then hit add lights.I have tried both discovery and manuall add.Lights are added successfully but after quit the mobile app and open it again there no lights saved.Is an empty list
**Expected behavior**
When opening the app to find my discovered lights

**WLED version**
 - Board: Nodemcu8266
 - Version 0.11.1
 - Format Bonary

**Additional context**
Did not have the issue a few weeks back

Thank you for your help!

**Comment by myrulezzz** [comment]
Hi after restarting my device the issue is reolved.
Thanks

**Comment by Aircoookie** [comment]
Strange, normally the device should save the list once you exit the app. Glad that it's working now though!
