### ISSUE TITLE
Top nav bar is flashing on reload in File Mode (since v0.12.0)

### ISSUE THREAD

**Issue by WoodyLetsCode** [Aircoookie/WLED#1868]
Hello,
since the v0.12.0 update the top nav bar is flashing every time I reload the page.
This only happens in Chrome and in File Mode.

**To Reproduce**
1. Open Chrome
2. Load index.htm locally

**Expected behavior**
No flashing like in previous versions

**WLED version**
 - v0.12.0, Build 2104020

Here you can clearly see the flashing effect:
![nm1RRLOfdU](https://user-images.githubusercontent.com/27882680/113765217-40626200-971c-11eb-9e9c-9b1194b7926b.gif)

While you can see the popup you can see the top bar permanently in white:
![grafik](https://user-images.githubusercontent.com/27882680/113764850-cf22af00-971b-11eb-8e1d-2f9e016d74ee.png)

It's only a small bug, but this flashing didn't happen in v0.11.1, so that is why I made this report. 😄 
Thank you for this cool project! 😎

**Comment by Aircoookie** [comment]
Noticed that too. I will take a look next time I work on the UI 😄

**Comment by softhack007** [comment]
Not observed any more in 0.14.
