### ISSUE TITLE
Send IR commands

### ISSUE THREAD

**Issue by ricardo-brenner** [Aircoookie/WLED#187]
Now I have one nodemcu to control the lights (WLED - hyperion) and another just to act like a IR remote control to turn on TV with Alexa, anyone already changed/adapted the code to work as a IR sender? 
How can I add another instance of alexa? a single ON/OFF can help me, with that i'll add the code to send the IR on/off

**Comment by ricardo-brenner** [comment]
I've merged wled with sinric code, worked perfectly

**Comment by ulhas10** [comment]
Hi.. i am new to programming..  can u share the code? please.. it would help newbies like myself a lot
