### ISSUE TITLE
Import name of realtimeMode to display the mode on LCD or TFT

### ISSUE THREAD

**Issue by AB-DMX** [Aircoookie/WLED#1880]
Hi !! I need to know how import name of realtimeMode .... I want to display on LCD...... I make usermod and it work but just need this for finalize the project. The only thing it print is the number of realtimeMode.

Thank you !!! When is finish I upload my usermod :)

**Comment by Aircoookie** [comment]
Hi! You could copy the switch block from [here](https://github.com/Aircoookie/WLED/blob/0e99c948d68948ec3ea43482c4b40a497c3ee552/wled00/json.cpp#L441) and just change `root["lm"]` to the string you want to set :)

**Comment by AB-DMX** [comment]
Thank you Aircoookie !!!
I try this tonight :)
