### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by michelnet** [Aircoookie/WLED#1883]
As Serverdescrption i add wled-01. But the client made a self registration in DNS with wled-wled-01. 

WLED-0.12.0 ESP32 Binary

Thank you for your help!

**Comment by nob0dy80** [comment]
thats not a bug, thats the usual behavior. it always uses the prefix wled- !
If you want to name it wled-01 just but 01 in the hostname.

**Comment by mrJelleBeat** [comment]
This is still an issue.
The prefix "wled-" does not follow my naming convention and makes an absolute mess of my DHCP list.
Yes, OCD much, but when I set a name (in UI settings or mDNS), I expect it to show up a such and not force a prefix.

Taking a peek at Tasmota, which has a dedicated hostname field under WiFi Settings.
That seems like a proper implementation, no?

**Comment by blazoncek** [comment]
@mrJelleBeat see and upvote/test #4893

**Comment by softhack007** [comment]
The double name ("DNS with wled-wled-01") problem will be solved with
* #5424
