### ISSUE TITLE
Brightness when controlling via DDP

### ISSUE THREAD

**Issue by mase76** [Aircoookie/WLED#1884]
Hi!
When I control the device via DDP with xLights, the brightness-slider in WLED should not have any effect. The general brightness control should only be taken by the controlling protocol, and WLED should be at full brightness. Only the brightness limiter should be active.
The current behaviour: I select a solid light with the lowest brightness as a power-on-indicator. When xLights takes control, the brightness settings of WLED and xLights are somehow merged together. This results in dark or even off leds.

**Comment by Aircoookie** [comment]
Hi!
This is intended behavior.
If you would like to control the brightness exclusively from xLights, you can enable `Force max brightness` in the Realtime section of Sync Settings.

**Comment by mase76** [comment]
I see. Is the limiter still active then, to prevent from too high current?

**Comment by Aircoookie** [comment]
Yes! The target brightness is set to maximum, but actual output still limited if required.

**Comment by mase76** [comment]
Great! Thx!
