### ISSUE TITLE
problemas ESP8266 NodeMcu v3 aliexpress

### ISSUE THREAD

**Issue by josejuano** [Aircoookie/WLED#1887]
compré ESP8266 CP2102 y lo utilizo sin problemas, flah con ESPHome-Flasher-1.3.0-Windows-x64, instalo WLED_0.11.1_ESP8266.bin y sin problemas, pero con la placa ESP8266 V3 CH340G hago lo mismo y no conecta com la aplicacion. alguna idea? no tengo idea de programar ni nada de eso, hasta ahora ha sido muy facil con las primeras

**Comment by Aircoookie** [comment]
Hola, deberá instalar los controladores para CH340G en su computadora antes de poder flashearlo

**Comment by josejuano** [comment]
gracias aircoookie por contestar. ahora ya lo tengo instalado en mi computadora. Ahora lo flasheo como siempre?

**Comment by Aircoookie** [comment]
Puedes flashear con https://install.wled.me ahora
