### ISSUE TITLE
BTNPIN = -1 as default after 0.12.0 can mislead first-time users

### ISSUE THREAD

**Issue by jpcurti** [Aircoookie/WLED#1891]
Release 0.12.0 added the possibility to define BTNPIN as -1 so that the button can be set as null. However this is now the default value and even when the user selects the option "enable on/off button" on the gui the function will not work, as the button is set as none.  I am unsure if this is the expected behaviour, as it can mislead new users when the trigger by button press doesn't work as expected.

A simple reminder below the option "enable on/off button", stating that the user also need to set a pin for the button, would be already ok. Maybe the correct approach is to leave the default value for the BTNPIN as before (e.g FLASH PIN/GPIO0 on ESP8266) and keep the value -1 as an option.

 - Board: [nodemcuv2]
 - Version [0.12.0,]
 - Format [Binary/ self-compiled]

Maybe this does not qualify as a bug therefore I wrote it as a question.

**Comment by Aircoookie** [comment]
Thank you, this is a great point!
It was not intended that no pin is set as default, not only for the button, but also for IR and the relay pin. I will set the defaults to their respective 0.11 values of 0, 4, and 12 again.
