### ISSUE TITLE
How to use WS2815

### ISSUE THREAD

**Issue by LukasVFL99** [Aircoookie/WLED#1892]
Hey how do I need to Setup the LED Preferences if I use a WS2815 I cant get the WW working.
Its a RGBWW Led Stripe. Any help would be appreciate.
Thanks. :)

**Comment by blazoncek** [comment]
AFAIK WS2815 is a RGB (GRB order) strip and not RGBW(W).
SK6812 is RGBW.

**Comment by LukasVFL99** [comment]
@blazoncek I ordered it from AliExpress and there they said it's rgbww

**Comment by blazoncek** [comment]
So, if I say "throw it away", will you? I guess not. ;) Don't belive everything that is said.

If it is WS2815 it will be 12V and will have DI/BI and DO/BO signal lines.
![ws2815](https://user-images.githubusercontent.com/7722392/114823448-d99c1300-9dc3-11eb-89a4-0d28a391250f.jpg)

If it is RGBW it will have a separate LED for white.
![sk6812-vs-ws2812b-vs-sk6812-rgbw](https://user-images.githubusercontent.com/7722392/114823559-fa646880-9dc3-11eb-9abf-cb8226e7f168.jpg)

**Comment by LukasVFL99** [comment]
Ah damn it. Yeah I guess I will deal with it but thanks :)
