### ISSUE TITLE
5050 led strip support

### ISSUE THREAD

**Issue by ericksvasc** [Aircoookie/WLED#1895]
sorry for my English, but how do I use the Wled with RGB 5050 led strip

**Comment by ericksvasc** [comment]
> sorry for my English, but how do I use the Wled with RGB 5050 led strip

**Comment by sansillusion** [comment]
In settings/leds you can choose the led type and pins(s).
If your question is about how to connect your leds to your board I recommend doing a search with your board type/model + 5050 in your language. That should give you good results that you can apply and then configure wled to use the pins chosen.

**Comment by srg74** [comment]
Answered in #1897

**Comment by ericksvasc** [comment]
> In settings/leds you can choose the led type and pin(s).
> If your question is about how to connect your leds to your board I recommend doing a search with your board type/model + 5050 in your language. That should give you good results that you can apply and then configure wled to use the pins chosen.

already researched in my language and did not find it. do you know of any tutorials in English?

**Comment by srg74** [comment]
https://www.instructables.com/Driving-RGB-LED-strips-off-an-Arduino/
