### ISSUE TITLE
Hyperion ambilight suport?

### ISSUE THREAD

**Issue by Osmii** [Aircoookie/WLED#19]
Did anybody managed to connect WLED to [Hyperion server](https://hyperion-project.org/), like you can do with this [client](https://github.com/penfold42/stuff/blob/master/ESP-udp-neo-OTA-webconfig.ino)?
Is it even possible?

**Comment by pete111** [comment]
Hi @Osmii Osmii, yes, I tested it and works nice. I am pretty sure @Aircoookie release modified version with Hyperion feature soon.

**Comment by Aircoookie** [comment]
I should really set up a separate development branch so you can test the latest progress at any time before the next 0.7.0 version is released. For now, here is the version with Hyperion support: https://drive.google.com/open?id=1kRZ2qAQnvFlpmPizvJxPNBo7nEXMPDFr (you can now either use Adalight protocol via USB, that was already possible with 0.6.3, but in this version you can also do it via UDP protocol 0 on port 19446). Thanks for your interest in the project!

**Comment by Aircoookie** [comment]
Version 0.7.0 is released now! Please check for any issues! (like #25) If Hyperion works correctly, this will be closed.

**Comment by lightrunner86** [comment]
Hi got everything running fine, ist the Bridge really nessasary? If i search for hue, the esp8266Wled flickers 1* (meaning to me its untersanding what im trying to do??).
The last thing i'd like to do is buying any further parts from Phillips. ;-)
Thanks for advice.
