### ISSUE TITLE
Color correction for UDP signals

### ISSUE THREAD

**Issue by ahmed-shehata** [Aircoookie/WLED#1901]
**Is your feature request related to a problem? Please describe.**
Hyperion sends color data to WLED instance over UDP. LED strips are not all created alike, they differ in quality and color calibration. It would be very useful if there was a way to calibrate and configure [Saturation/Brightness](https://en.wikipedia.org/wiki/HSL_and_HSV) of the incoming color signal.

**Describe the solution you'd like**
The proposed solution would be a modifier option in settings to modify the factor of saturation/brightness to increase/decrease (1x,1.5x, etc..) 

**Describe alternatives you've considered**
I have built a solution as a proxy UDP server (Hyperion -> UDP Proxy server (modifies color) -> WLED) and it works fine, I would like to implement it in WLED for better latency and easier configuration.

**Additional context**
Philips has a setting in their Ambilight TVs for enhancing the color reproduction on the LEDs (Standard/Vivid/Natural):

![image](https://user-images.githubusercontent.com/4982099/115028580-efd9ca00-9ebc-11eb-8e9c-8d6748531854.png)

**Proposed change in WLED sync settings:**
![A5EA3091-1BD1-437F-8EB6-AC0AF604B217](https://user-images.githubusercontent.com/4982099/115806403-9ef73380-a3de-11eb-9d54-d1d8df53154e.jpeg)

### Demonstation:
![Screenshot 2021-04-16 at 1 55 42 pm](https://user-images.githubusercontent.com/4982099/115027639-dd12c580-9ebb-11eb-943a-99b38b978d52.jpg)

Before: (very dim)
![C5115D7B-973B-44BF-BD5F-4BB2D074C9E6](https://user-images.githubusercontent.com/4982099/115806023-f648d400-a3dd-11eb-82ca-3dfcaef0f3d8.jpeg)

After: (vivid)
![E19CED91-5C35-4B9E-8CAD-E2D1BED45A9D](https://user-images.githubusercontent.com/4982099/115806013-f34de380-a3dd-11eb-8f41-5696f5a3c001.jpeg)

I am happy to implement this myself, would such feature be of interest?

I'm preparing a Pull request soon.

**Comment by ahmed-shehata** [comment]
Pull request here: https://github.com/Aircoookie/WLED/pull/1902

Happy to hear your thoughts, @Aircoookie.

**Comment by moustafa-nagaty** [comment]
Thats a great idea, will definitely be useful!

**Comment by ReviloEgros** [comment]
Would love to see this implemented!
