### ISSUE TITLE
WLED über GPIO Ansteuern.

### ISSUE THREAD

**Issue by ahaberes** [Aircoookie/WLED#1907]
Hallo zusammen,

Ich bin relativ neu was das Thema WLED angeht. Aber habe es schon auf einem ESP8266 am laufen und funktioniert über das Webinterface auch alles.
Ich habe vor kurzem gesehen wie jemand mit WLED und Loxone eine sehr sehenswerte Garagentorbeleuchtung realisiert hat.

Da ich leider kein Loxone nutzer bin habe ich nicht die Möglichkeit dies so umzusetzten.
Nun zu meiner Frage:

Kann man einzelne Sequenzen auch über das ESP8266 board direkt über Digitaleingänge "abspielen"?

Gruß Alex

**Comment by timae146** [comment]
Ja man kann eigene Presets durch einen Digitaleingang triggern.

https://github.com/Aircoookie/WLED/wiki/Macros
