### ISSUE TITLE
JSON Sample Configuration for Home Assitant

### ISSUE THREAD

**Issue by stockklauser** [Aircoookie/WLED#191]
Hay Guys, 

can anyone share and document in the wiki a Sample Configuration for Home Assistant using the JSON Interface with Status Update functionality? 

Thx!

**Comment by Aircoookie** [comment]
Hi,
if someone has a good config, I will happily add it to this [wiki page](https://github.com/Aircoookie/WLED/wiki/Home-Automation-systems)!
