### ISSUE TITLE
Funktioniert nicht mit WS2801

### ISSUE THREAD

**Issue by vocaris9** [Aircoookie/WLED#1914]
Hallo,
ich bin neu auf dem WLED Gebiet und möchte das ggf. bekannte Garagenprojekt umsetzen.
Was habe ich:
Einen ioB mit MQTT, einen WEMOS D1 Mini und zum Test einen kurzen LED Streifen WS2801. Auf dem WEMOS ist die WLED_0.12.0_ESP8266.bin. In den LED Eigenschaften habe ich dies eingetragen:
![image](https://user-images.githubusercontent.com/43674377/115862111-fe336300-a433-11eb-83be-133d3d0a00c3.png)
Somit ist dann der DATA an D4 und der CLOCK an D3.
Nach dem Speichern reagieren die LEDs nicht, wenn ich die Farben wechsele.
Im neue Edge Browser erscheint bei jedem Klick im Web Interface folgende Meldung:
![image](https://user-images.githubusercontent.com/43674377/115862317-4bafd000-a434-11eb-95ec-3315f1c10784.png)

**Comment by ToTXR4Y** [comment]
https://github.com/Aircoookie/WLED/issues/1852
