### ISSUE TITLE
WS2811 12v LED STRIP(3 group of led)  not working with ESP8266

### ISSUE THREAD

**Issue by sbali620** [Aircoookie/WLED#1917]
![WhatsApp Image 2021-04-25 at 10 15 10 AM](https://user-images.githubusercontent.com/80770625/115982147-68741100-a5b6-11eb-885b-d4b1067f66bf.jpeg)

I am using this ws2811 strip with 3 led group.  It run on 12v. now i am using Nodemcu ESP8266 to run this. I am not able to drive it. Now i am not using level shifter. Can it drive without level shifter? I have connected output in D4. So please tell me the solution. how I can use the STRIP? when i connect the power directly to Strip, Its running the effect automatically which is preinstalled.

**Comment by Aircoookie** [comment]
Hi!
Can you show us the connections between strip and the ESP8266? WS2811 usually does not have a pre-installed effect, maybe this is a different type of LED chip...

**Comment by sbali620** [comment]
Sir, There are 3 pin in led strip. 1-vin 12v, 2- signal ,3-ground. I am using Esp8266 pin D4 connected to signal of Strip. And pin ground is connected to 12v ground and my Ln7805 ground pin. I am using 7805 to powerig esp8266. And I am using it in  Home assistant.

**Comment by sbali620** [comment]
> Hi!
> Can you show us the connections between strip and the ESP8266? WS2811 usually does not have a pre-installed effect, maybe this is a different type of LED chip...

![WhatsApp Image 2021-04-29 at 3 30 25 PM](https://user-images.githubusercontent.com/80770625/116575056-eecc8200-a92b-11eb-921a-65954831d7b6.jpeg)
![WhatsApp Image 2021-04-29 at 5 29 49 PM (1)](https://user-images.githubusercontent.com/80770625/116575069-f0964580-a92b-11eb-86fb-99541743842a.jpeg)
![WhatsApp Image 2021-04-29 at 5 29 49 PM (2)](https://user-images.githubusercontent.com/80770625/116575073-f0964580-a92b-11eb-8778-a0cdc8bce1b0.jpeg)
![WhatsApp Image 2021-04-29 at 5 29 49 PM](https://user-images.githubusercontent.com/80770625/116575074-f12edc00-a92b-11eb-8bf0-f35d7314151c.jpeg)

**Comment by sbali620** [comment]
i am using even logic shifter
