### ISSUE TITLE
ios effects

### ISSUE THREAD

**Issue by covasna5252** [Aircoookie/WLED#1925]
Hi Aircoookie/WLED
Congratulations, and thanks for your great job.
I use WLED (on PC and iPhone) for about 2 days. Everything great,  less, from my iPhone6, I can not change the effects. All other features are working fine.
I flashed the firmware several times, WLED App for ios reinstall many times ...the same result.
Thank You!

**Comment by Aircoookie** [comment]
Hi!
This is a known problem with devices running iOS 12: https://github.com/Aircoookie/WLED/issues/1853
If you do not need multiple outputs from one device, you could give WLED 0.11.1 a try, it might work with that version.
Sorry for the inconvenience, I hope I can get it fixed soon!

**Comment by covasna5252** [comment]
Indeed it's working with WLED 0.11.1Thanks a lot!
    Pe marți, 27 aprilie 2021, 17:47:58 CEST, Aircoookie ***@***.***> a scris:  
 
 


Closed #1925.

**Comment by xfactory9025** [comment]
I also installed the 0.11 version to fix the problem, but this version does not have led pin settings. Esp-01 also does not work if I do not connect leds to 0 pin. Connect to pin number 2, esp does not start.

**Comment by sansillusion** [comment]
It looks like ios is not respecting web standards. It's not assigning
proper z-depth to different elements of the webpage (effects buttons in
this case).
