### ISSUE TITLE
PIR_sensor_switch

### ISSUE THREAD

**Issue by ItsMrJP** [Aircoookie/WLED#1928]
I am trying to reduce the user mod for the PIR sensor switch so that the light only turns on for 15-30 seconds. There is a limit in the range. Currently the lowest possible value is 60 seconds. Any help would be much appreciated!

**Comment by blazoncek** [comment]
I am currently working on a fully configurable PIR sensor switch usermod.
It is already available in my WLED repo, dev branch.
It may take a while to get included into WLED master though.

**Comment by 1igeza** [comment]
Will it be possible to use more then one PIR sensor and send also status to mqtt?

**Comment by blazoncek** [comment]
More than one, no.
MQTT, yes.

**Comment by ItsMrJP** [comment]
> I am currently working on a fully configurable PIR sensor switch usermod.
> It is already available in my WLED repo, dev branch.
> It may take a while to get included into WLED master though.

Awesome! Thank you! Will check out your fork

**Comment by blazoncek** [comment]
This has been now submitted as a PR for master.
