### ISSUE TITLE
MAC address in WiFi Settings listed

### ISSUE THREAD

**Issue by Cinux90** [Aircoookie/WLED#1938]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
MAC Address information listed in the "WiFi Settings".

**Describe alternatives you've considered**
None

**Additional context**
I started to combine the WLED with Hyperion-NG. For now I face the issue that I need to configure an IP Addresse in Hyperion instead of a hostname. As the IP address can be changed after DHCP lease time is over it would be nice to set an static IP in the Router before the first connection with the Wifi is established. Therefore the MAC address is needed.

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
MAC address is available in Info page.
If you want to use host name, just enable/install mDNS on your network. WLED has mDNS built in.
