### ISSUE TITLE
ESP-01S not connect

### ISSUE THREAD

**Issue by xfactory9025** [Aircoookie/WLED#1942]
I uploaded the file WLED_0.12.0_ESP8266_1M to module esp-01s. I adjusted the wifi settings, it was working fine. The connection was lost after 5 minutes and never connected again. I restarted it over and over but failed. 
Also, effects do not work in the mobile application ios.

**Comment by Aircoookie** [comment]
Hi!
Please use the `WLED_0.12.0_ESP8266_1M.bin` binary, which does allow saving on ESP01 :)

**Comment by xfactory9025** [comment]
The save problem has been fixed, but it often disconnects and takes a long time to reconnect. The effects do not work in the mobile browser and the mobile application, only color adjustment can be made. On the computer, all functions are running.

**Comment by xfactory9025** [comment]
Effects work on ios 13 but not on ios 11.

**Comment by sansillusion** [comment]
It seems ios is having issues with proper management of different z-depth
elements on web pages. Seems like an ios issue to me. They don't respect
web standards.

Le mar. 4 mai 2021 6 h 10 a.m., xfactory9025 ***@***.***> a
écrit :

**Comment by xfactory9025** [comment]
The connection drops after a certain period of time. Esp8266 going into sleep mode?
