### ISSUE TITLE
Purpose of the 65ohm resister and 1000 capacitor 

### ISSUE THREAD

**Issue by tinseltunes** [Aircoookie/WLED#1943]
I've just noticed these on the wiring diagram over on the Wiki.
What is the purpose of these? I've been running my 5v ws2812 without these.
The runs I have are short, these than 100 pixels. (I'm using these on my drum kit). Should I install the components?

Thanks

**Comment by Aircoookie** [comment]
Hi!
These are best practices to protect against voltage spikes on the voltage and data lines: https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices

If you have a running setup, leave it. I never incorporated these into my lights, and they've been running well so far.
They are also not required with e.g. QuinLED boards as they got the cap + resistor on board.
