### ISSUE TITLE
LED Grouping for Hyperion (Live) Ambilight

### ISSUE THREAD

**Issue by dimitrij2k** [Aircoookie/WLED#1947]
Ambilight with Hyperion and WLED is limited to 490 LEDs (in reason of the UDP Protocol). But with the possibility to Group LEDs it would be possible to use 144LEDS/m with bigger TVs. So we could use 2 or 3 LEDs as one LED. 

LED Grouping actually don’t work with the „(Live)“ feautre.

**Comment by blazoncek** [comment]
May be resolved when #2601 is merged.

**Comment by dimitrij2k** [comment]
Sounds great ❤️
