### ISSUE TITLE
State value to set for "wled.0.483fda49c0fd._info.mac" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by OlfrygtACAB** [Aircoookie/WLED#1948]
<html>
<body>

wled.0 | 2021-05-06 20:35:27.254 | info | (1832) State value to set for "wled.0.ecfabcc232d5.seg.0.col.2" has to be one of type "string", "number", "boolean" but received type "object"
-- | -- | -- | --
wled.0 | 2021-05-06 20:35:27.242 | info | (1832) State value to set for "wled.0.ecfabcc232d5.seg.0.col.1" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-06 20:35:27.234 | info | (1832) State value to set for "wled.0.ecfabcc232d5.seg.0.col.0" has to be one of type "string", "number", "boolean" but received type "object"
wled.0 | 2021-05-06 20:35:27.127 | info | (1832) State value to set for "wled.0.ecfabcc232d5._info.mac" has to be type "number" but received type "string"
wled.0 | 2021-05-06 20:35:27.051 | info | (1832) State value to set for "wled.0.ecfabcc232d5._info.leds.pin" has to be one of type "string", "number", "boolean" but received type "object"

</body>
</html>

**Comment by huggy-d1** [comment]
If you have recently installed WLED, I recommend fully erasing the ESP, then loading the firmware again.

**Comment by Aircoookie** [comment]
Hi! The received types of "object" (rather, an array in most cases) and "string" for the MAC address are the correct ones as per my API documentation. What software are you using for interacting with the JSON API that created these logs?
