### ISSUE TITLE
Not able to turn ON lights with IR after multiple IR OFF commands

### ISSUE THREAD

**Issue by JensMKofoed** [Aircoookie/WLED#1950]
**Describe the bug**
After multiple off commands from an IR controller you can't turn on the light again with the on button.

**To Reproduce**
Configure a WLED with IR, turn on the light. Press the off button and then the light is turn off press the off button again. Try to turn on the light with the on button. The lights stays off

**Expected behavior**
The on button should turn on the light.

**WLED version**
 - Board: ESP32
 - Version 0.12.0
 - Format Binary

**Additional context**
In the ir.cpp file the code is like this:
case IR44_OFF         : briLast = bri; bri = 0;  break;
case IR44_ON          : bri = briLast;              break;

So multiple off commands will save 0 as briLast.
If adding an IF-statement something like this: 
case IR44_OFF         : if  ( bri != 0) {briLast = bri;} bri = 0;  break;

The briLast will only be updated with the value where the lights was actually on.

Thank you for your help!

**Comment by Aircoookie** [comment]
Thank you for finding, reporting and analyzing this issue! I've applied your fix and it should be resolved in latest master now :)
