### ISSUE TITLE
toggle on state via JSON-API

### ISSUE THREAD

**Issue by CWempe** [Aircoookie/WLED#1952]
**Is your feature request related to a problem? Please describe.**
I want to control my WLED from another ESP8266 via JSON-API.
Currently I can only send `{"on":true}` and `{"on":false}` to control the state.

**Describe the solution you'd like**
I would like to have the option to toggle the `on` state of WLED via JSON-API.
Because `on` is boolean we cannot add a third option.
So I would propose something like `{"toggle":true}`.

**Describe alternatives you've considered**
I do not want to read the state first in order to send the opposit command.
This would add unnecessary overhead and delay, I think. 

Anyway, keep up the great work! 👍

**Comment by Aircoookie** [comment]
Just added `{"on":"t"}` to support this!
I chose to stick with the `on` property and accept a string as the value rather than adding a new property, as that goes well with my plans here: https://github.com/Aircoookie/WLED/issues/1933#issuecomment-830698817
