### ISSUE TITLE
Brightness Preview for Segments is scaling to much

### ISSUE THREAD

**Issue by timae146** [Aircoookie/WLED#1953]
**Describe the bug**
The Brightness Preview for Segments scales to much. If you set the seg. brigness value to low you cant see sth. in the WebGui Preview.

**To Reproduce**
See the gif

**Expected behavior**
Would be nice if the scaling could be modified same like the Preview of the Main brightness 

edit:
is it even necessary to have two brightness controllers? why can't the brightness controller of the segment override the brightness of the main controller for that segment ? 

**WLED version**
 - Board: Wemos D1
 - Version 0.12.0
 - Format Binary

![Animation](https://user-images.githubusercontent.com/42387818/117546480-eca0ac80-b02a-11eb-8dbd-91a86f1cd7df.gif)

**Comment by Aircoookie** [comment]
Hi!
Both sliders scale the output equally - if you set both to 50%, the resulting output will be 25%. This also means that if you put one slider on minimum, the scaling will cause the LEDs to appear off if the other slider is not at maximum. When changing the brightness of an individual segment, I would recommend leaving the master brightness slider on maximum.

There is indeed no use case for two sliders when running a single segment, but it is useful with multiple segments to set different brightness values for different parts of the installation :)

**Comment by timae146** [comment]
hey. :) 

that's what I thought too. main slider to max and adjust the individual segments, but the disadvantage by this is that you cant the a preview if the brightness is to low.

![986226e8-be7e-44b8-b2d3-110939a23fc9](https://user-images.githubusercontent.com/42387818/117641003-f5f25c00-b185-11eb-8c4a-fc709336a7ec.jpg)
main slider max (peek activated) you can´t see a preview with the segment slider value ~<20

this problem doesnt exist if you only adjust the main slider:
![3622185c-1054-4c1f-8e18-066792e36de5](https://user-images.githubusercontent.com/42387818/117643060-4a96d680-b188-11eb-8e34-7e6189ca7a7a.jpg)
