### ISSUE TITLE
Drip langsamer machen

### ISSUE THREAD

**Issue by AchimFelsdrache** [Aircoookie/WLED#1957]
was muss ich machen um Drip erheblich zuverlangsamen.

Und gibt es einen Weg alle Effects in einem Schlag zu verlangsamen
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by Aircoookie** [comment]
Hi, soll die Fallgeschwindigkeit geringer sein oder die Anzahl/der Abstand zwischen den Tropfen?
Geschwindigkeit lässt sich mit dem Speed-Slider einstellen, die Tropfenanzahl mit Intensity. Beides auf 0 sieht schon sehr gut aus.
Ich werde den Wertebereich der Geschwindigkeit etwas anpassen, so dass ein noch langsamerer Fall möglich wird :)

**Comment by Aircoookie** [comment]
Habe es angepasst, die Fallgeschwindigkeit ist nun bei geringster Geschwindigkeitseinstellungs nur noch halb so hoch.
Wenn du eigene Anpassungen machen möchtest, such einfach nach `SEGMENT.speed` in der jeweiligen Effektfunktion in `FX.cpp`. Der Wertebereich davon ist 0-255 und wird von der Effektfunktion individuell skaliert, sodass du mit einer Anpassung des Faktors viele Effekte relativ einfach langsamer bekommst :)

**Comment by AchimFelsdrache** [comment]
Danke dir. Ich schaue mal ob ich hinbekomme. 

Gruss Achim

Am 13. Mai 2021 23:36:05 MESZ schrieb Aircoookie ***@***.***>:
>Habe es angepasst, die Fallgeschwindigkeit ist nun bei geringster
>Geschwindigkeitseinstellungs nur noch halb so hoch.>
>Wenn du eigene Anpassungen machen möchtest, such einfach nach
>`SEGMENT.speed` in der jeweiligen Effektfunktion in `FX.cpp`. Der
>Wertebereich davon ist 0-255 und wird von der Effektfunktion
>individuell skaliert, sodass du mit einer Anpassung des Faktors viele
>Effekte relativ einfach langsamer bekommst :)>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Aircoookie/WLED/issues/1957#issuecomment-840849149

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by AchimFelsdrache** [comment]
Hi . 
Sei mir nicht böse aber um colortwinkels langsamer zu bekommen bin ich zu doof. 
Kannst du mir noch einen Tip geben bitte.

Gruss Achim

Am 13. Mai 2021 23:36:05 MESZ schrieb Aircoookie ***@***.***>:
>Habe es angepasst, die Fallgeschwindigkeit ist nun bei geringster
>Geschwindigkeitseinstellungs nur noch halb so hoch.>
>Wenn du eigene Anpassungen machen möchtest, such einfach nach
>`SEGMENT.speed` in der jeweiligen Effektfunktion in `FX.cpp`. Der
>Wertebereich davon ist 0-255 und wird von der Effektfunktion
>individuell skaliert, sodass du mit einer Anpassung des Faktors viele
>Effekte relativ einfach langsamer bekommst :)>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Aircoookie/WLED/issues/1957#issuecomment-840849149

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Aircoookie** [comment]
Bei Colortwinkles ist es in der Tat etwas komplizierter 😄 
Das Problem ist, dass die Pixel in jedem Animationsschritt (etwa 40 pro Sek.) ein wenig dimmen müssen, da sie sonst auf einer Farbe "stecken bleiben" können.
Als Workaround würde ich evtl. empfehlen, `return FRAMETIME` am Ende des Colortwinkle-Effekts durch `return FRAMETIME*3` zu ersetzen. Dies sollte die Geschwindigkeit auf ein Drittel reduzieren :)

**Comment by AchimFelsdrache** [comment]
Werde ich versuchen Danke

Am 17. Mai 2021 10:46:36 MESZ schrieb Aircoookie ***@***.***>:
>Bei Colortwinkles ist es in der Tat etwas komplizierter 😄 >
>Das Problem ist, dass die Pixel in jedem Animationsschritt (etwa 40 pro
>Sek.) ein wenig dimmen müssen, da sie sonst auf einer Farbe "stecken
>bleiben" können.>
>Als Workaround würde ich evtl. empfehlen, `return FRAMETIME` am Ende
>des Colortwinkle-Effekts durch `return FRAMETIME*3` zu ersetzen. Dies
>sollte die Geschwindigkeit auf ein Drittel reduzieren :)>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Aircoookie/WLED/issues/1957#issuecomment-842142207

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
