### ISSUE TITLE
presets in home assitant

### ISSUE THREAD

**Issue by KingMark66** [Aircoookie/WLED#1959]
When I want to create a scene in home assistant, is it then possible to set a preset that i made in wled?
So for example, I set a preset in wled with 5 segments, al different colors, solid.
Can i call that preset using a scene in home assitent?

**Comment by Legsmaniac** [comment]
I believe you need to be asking this on the Home Assistant forum as that is a separate entity created for Home Assistant to work with WLED.

**Comment by sansillusion** [comment]
If you use a rest_command in HA it should work.

Le jeu. 13 mai 2021 9 h 14 a.m., Legsmaniac ***@***.***> a
écrit :

**Comment by 1igeza** [comment]
You can use:
service: wled.preset
    data:
      preset: 1
