### ISSUE TITLE
astroclock issue

### ISSUE THREAD

**Issue by b3-4r** [Aircoookie/WLED#1991]
I've been running WLED 0.12.1-b1 on several separate devices, making use of the new astroclock feature (sunrise/sunset). So far all have been working great until today when all instances came on way too early in the afternoon, then off midway through the night. One has rebooted shortly after turning off but that may be unrelated, this board has spontaneously rebooted before.

All devices show the correct current time, and the sunrise/ sunset times displayed correspond to the times at which the macros fired.

I'll post a reply should this happen again. The displayed sunrise and sunset times are still way off.

Is anybody else seeing this? I wonder if this could be related to my timezone and/ or geographical location but I'm wary of divulging that.

**Comment by Aircoookie** [comment]
Hi!
Yes, this is a bug that emerged because a math approximation had an input that was out of its range.
Fixed in master :) You can compile it yourself or wait for a 0.12.1-b2 binary, I will hopefully release that in the next few days!
