### ISSUE TITLE
Disconnected from chip

### ISSUE THREAD

**Issue by kalo16** [Aircoookie/WLED#1995]
Hi! It looks like my strip was disconnected from its chip and I’m not sure if it’s fixable! It seems to have some sort of like hot glue at the end of it but I do not want to mess with it until I hear from you! Is there anyway I can fix it myself? Thank you! :)

**Comment by Aircoookie** [comment]
Hi,
sorry I do not know what you mean. Is your WLED no longer reachable, or did something come apart with the wiring? You can also send photos.

**Comment by smartroad** [comment]
Really going to need some pictures to help with this
