### ISSUE TITLE
Sync Room lighting with in-game lighting

### ISSUE THREAD

**Issue by SnappierSoap318** [Aircoookie/WLED#2002]
I saw some videos on instagram and reddit about a person's setup where the LED's behind his TV were lighting up  according to the lighting in the game.

This feature is done in Philips Hue, [video](https://www.youtube.com/watch?v=7RQtJ1GM7uY), i think its possible with a display capture software and then calling WLED using api requests.

**Comment by sansillusion** [comment]
Search for hyperion-ng already supported in wled

Le lun. 31 mai 2021 12 h 12 p.m., Adwaith s ***@***.***> a
écrit :
