### ISSUE TITLE
Wifi settings

### ISSUE THREAD

**Issue by demianquin** [Aircoookie/WLED#2010]
Hi!
I have bought my WLed lights and I have tried to connect them to my wifi, in question is that I connect a light and configure it with the IP of my wifi (before that I could use it freely and change the colors), now that I want to connect from Back to my light does not appear on the network or in controls that I download to use it. What should I do?

**Comment by blazoncek** [comment]
Join WLED Discord and ask there.

**Comment by demianquin** [comment]
Thanks bro!

**Comment by demianquin** [comment]
Thanks bro! have you link of the discord?

**Comment by blazoncek** [comment]
It is on the main page. Just scroll a bit.
