### ISSUE TITLE
[Feature request] Digital clock overlay

### ISSUE THREAD

**Issue by lodesmets** [Aircoookie/WLED#2018]
I made a new overlay to create a digital clock with WLED. (7 segment style)

I already made a pull request, can someone take a look at it? #1916 

I'm currently 3D printing the last parts. Once this is done I will write more documentation on how it works.

**Comment by Aircoookie** [comment]
Hi!
That is awesome, I need to review and merge your PR (and also #1873, which is very similar), soon :)
