### ISSUE TITLE
Updates to non-main segment do not trigger a WebSocket (or MQTT) push

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#2026]
**Describe the bug**
Only updates to the main segment (usually the first selected segment) trigger a WebSocket push. Additionally, segment on/off and brightness updates never trigger it.

**Expected behavior**
Every state change triggers updates.

**WLED version**
0.12, master

**Additional context**
Reported by @Frenck (Discord)

Thank you for your help!

**Comment by blazoncek** [comment]
Yes, indeed.

**Comment by Aircoookie** [comment]
Fixed in https://github.com/Aircoookie/WLED/commit/dc01c907f1d014d84a4e887dc167ba9324cb5153 :)
