### ISSUE TITLE
i need help connect esp 8266 nodemcu esp-12 ch340 with ws2812b 

### ISSUE THREAD

**Issue by tctmaster** [Aircoookie/WLED#2029]
I connect VIN and GND to a common 5v6a power line and connect to leds without using a 4.7kohm divider between 3.3v and D4 since 4.7kohm is not available because of order and  wait shipping
Case 1: board is powered up and running online, but set LED SETUP pin = 2 (D4) or 4 (D2), nothing happens to LED, onboard LED stays blue 
Case 2: Same as above but the board does not start and flashes, Led board flashes green once and then turns off (if using usb power, it will power on but still can't led light up)

in my case is there any way to solve the problem from D2 and D4 pin and the circuit diagram from the shop I bought it says D4 pin is GPIO2 pin11
**WLED version**
 - Board: [default_envs = d1_mini because i don't know which one to choose for my esp 8266 nodemcu v3 esp-12e ch340 board]
 - Version [0.12.0]
 - Format [self-compiled]
> ![f65907b82000ba5f01212a1c1f39d261](https://user-images.githubusercontent.com/85792521/122071140-b243df80-ce20-11eb-8797-ca4aa60af8d1.jpg)
> ![2614c53a3548c1169859](https://user-images.githubusercontent.com/85792521/122071125-aeb05880-ce20-11eb-88ab-768b337891ad.jpg)
Additional context
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by tctmaster** [comment]
Can I ask is it a direct solder connection of 4.7k ohm from the 3.3v pin to the D4 pin?
![error-esp-12e-1](https://user-images.githubusercontent.com/85792521/122102797-06aa8780-ce40-11eb-9443-c51b7a6c98f8.jpg)

**Comment by huggy-d1** [comment]
Just connect up the LED strip data line directly to the D4 pin.  It will either work, or if the lead from the pin to the strip is too long, it won't.
If you have a level shifter to boost the 3.3V output from D4 to 5V for the LED strip, you insert that between the D4 output and the LED strip data connection.

**Comment by tctmaster** [comment]
> Just connect up the LED strip data line directly to the D4 pin. It will either work, or if the lead from the pin to the strip is too long, it won't.
> If you have a level shifter to boost the 3.3V output from D4 to 5V for the LED strip, you insert that between the D4 output and the LED strip data connection.

level shifter to increase 3.3V output from D4 to 5V for LED I don't use. I use 4.7k ohm connect D4 <> Led.can it work without 3.3v > 5v level booster?

**Comment by huggy-d1** [comment]
Very often, the 3.3V output LED data pin provides enough voltage to drive the LED strip.  If the wire is small or long or both between the controller and LED strip, you should consider a level shifter to increase reliability.

**Comment by tctmaster** [comment]
> Very often, the 3.3V output LED data pin provides enough voltage to drive the LED strip. If the wire is small or long or both between the controller and LED strip, you should consider a level shifter to increase reliability.
I'll take a look after the 4.7k ohm I ordered is delivered to try.
let me ask is my board esp 8266(esp-12e) nodemcu v3 ch340, which item should I choose default_envs as the most optimal item because I still don't know which one is the most suitable other than d1_mini

**Comment by tctmaster** [comment]
can anyone tell me which entry should default_env be for esp-12e nodemcu 8266 v3

**Comment by tctmaster** [comment]
> Very often, the 3.3V output LED data pin provides enough voltage to drive the LED strip. If the wire is small or long or both between the controller and LED strip, you should consider a level shifter to increase reliability.

i have used sn74hc125n and it is stable thanks, can i ask if i am going to have esp wroom 32d, do i need to flash bootloader first and then flash wled
