### ISSUE TITLE
WS2811 working fine except incorrect colors

### ISSUE THREAD

**Issue by stagea09** [Aircoookie/WLED#203]
uploaded, running perfect with 12v WS2811 strip. but when selecting blue - its actually green, and red is actually blue, and green is actually red.
i see the RGBW setting for adjusting the config but these are like the WS2812b just 12v, and obviously in a different configuration.
is there a way to change the way the controller sends the colors on my strip?

**Comment by Aircoookie** [comment]
Hi and welcome to WLED!
Below the RGBW setting there is a "Color order" dropdown field. Try selecting "RBG" and you should be getting the correct colors!

**Comment by stagea09** [comment]
Thanks, i was under the impression that the setting was for when you're using RGBW strips. i'll give it a go when i get home and see how i go

**Comment by stagea09** [comment]
Yep.. I feel Abit retarded right now.... Thanks ;)
