### ISSUE TITLE
Possible to customize home page

### ISSUE THREAD

**Issue by Kepler-11** [Aircoookie/WLED#2030]
is it possible to change the home pages html and css? (permanently)

**Comment by huggy-d1** [comment]
With a usermod, or simply customizing WLED and compiling / build WLED yourself, you can do whatever you like.  It is a somewhat involved process that I do not claim to understand.  However, the wled wiki has some information about it.

**Comment by blazoncek** [comment]
It may be possible to _skin_ WLED in one of the next releases.
I have already implemented skinning (using CSS) in my experimental fork.
You can upload custom skin.css to the file system and it will override built-in CSS.

If you are inclined to completely override index.html, you can try to upload index.htm (or .html) to the file system. Don't forget your custom .js and .css.

**Comment by tctmaster** [comment]
sorry to ask what impedance welding is the correct principle.
Case 1: solder 1 4.7k ohm pin from the 3.3v pin on the board and the other 1 pin to the D4 position pin.
Case 2: solder one 4.7k ohm pin to D4 and the other back to the DataInput wire of the led
which one is correct?

**Comment by blazoncek** [comment]
> sorry to ask what impedance welding is the correct principle.
> Case 1: solder 1 4.7k ohm pin from the 3.3v pin on the board and the other 1 pin to the D4 position pin.
> Case 2: solder one 4.7k ohm pin to D4 and the other back to the DataInput wire of the led
> which one is correct?

Look at the Wiki page.

**Comment by sanjulanipun** [comment]
> It may be possible to _skin_ WLED in one of the next releases.
> I have already implemented skinning (using CSS) in my experimental fork.
> You can upload custom skin.css to the file system and it will override built-in CSS.
> 
> If you are inclined to completely override index.html, you can try to upload index.htm (or .html) to the file system. Don't forget your custom .js and .css.

@blazoncek  **Can you Tell me you know how to covert index.html code as binary ?**

![image](https://user-images.githubusercontent.com/32708235/132016586-46507dac-6980-4b9d-9f29-8a920acb0feb.png)

**Comment by blazoncek** [comment]
https://kno.wled.ge/advanced/custom-features/

**Comment by sanjulanipun** [comment]
> https://kno.wled.ge/advanced/custom-features/

@blazoncek  
**ok, my problem is ok. but please i need to know how i can covert html code like this binary? this question for my knowlage. please tell me any tool or something how i can covert html code like this binary code. plz.**

**Comment by spblat** [comment]
Is it feasible to present a custom page when the user connects to AP, such that a link in the custom page takes the user to the standard UI?
