### ISSUE TITLE
Timed light

### ISSUE THREAD

**Issue by Zazou27** [Aircoookie/WLED#2033]
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by Zazou27** [comment]
Hi everybody, i'm trying to use "Timed light" but it does not work if i do not toggle "Timer" in the main screen.
Is it normal and how to save this preset to make it word alone ? ( sorry for my bad english from france .... )

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
