### ISSUE TITLE
Segment Effect Offset

### ISSUE THREAD

**Issue by Sturm2002** [Aircoookie/WLED#2041]
For each segment a offset from which the effects start (not the segment itself), could help to sync the leds even more

**Describe the solution you'd like**
Maybe another input field for each segment, to input a number (offset)

**Additional context**
Imagine having Leds arranged in a circle, the segment starts Top-Left (NW) (Picture 1), if you now give it an effect-offset (let's say 10 Leds), it would look like the segment would start from North (Picture 2)

Picture 1 :
![fig1](https://user-images.githubusercontent.com/50213395/123527221-e0a5a280-d6dd-11eb-8538-12a89d2a566f.png)

Picture 2 :
![fig2](https://user-images.githubusercontent.com/50213395/123527223-e3a09300-d6dd-11eb-8bad-02a396d91ae9.png)

**Comment by blazoncek** [comment]
This can be done using LED map.
Create a ledmap.json file and upload it to the file system on /edit.
Look into #1738 and Wiki.

**Comment by Sturm2002** [comment]
oh, whoops i kinda missed that :D
thank you
