### ISSUE TITLE
Apply preset at boot ignores Turn LEDs on after power up/reset

### ISSUE THREAD

**Issue by ReviloEgros** [Aircoookie/WLED#2052]
**Describe the bug**
If you disable Turn LEDs on after power up and you want to apply a preset at boot, the LEDs will turn on. 

**To Reproduce**
Uncheck Turn LEDs on after power up, save a preset and apply it at boot.

**Expected behavior**
Keep LEDs turned off.

**WLED version**
 - Board: Wemos D1 mini
 - Version: V0.13.0-b0
 - Format: self-compiled

**Additional context**
Problem exists with V0.13.0-b0, V0.12.1-b1 is fine

**Comment by blazoncek** [comment]
Save a preset with "Include brightness" unchecked.
