### ISSUE TITLE
Still now chance to change mqtt Port?

### ISSUE THREAD

**Issue by Beliar-666** [Aircoookie/WLED#206]
Hey Cookie, 
there is still no chance to change the mqtt Port myself?`

**Comment by timothybrown** [comment]
Yes, that feature is in the current development branch:

![D6926F47-EE5F-45BC-9237-3AF4F798A100](https://user-images.githubusercontent.com/4151634/63499992-fbca7a00-c496-11e9-9773-3e33277177e7.jpeg)

You’ll need to download the repository and compile yourself, or wait for 0.8.5 to be released.
