### ISSUE TITLE
Same Preset after Reset

### ISSUE THREAD

**Issue by Sturm2002** [Aircoookie/WLED#2062]
**Is your feature request related to a problem? Please describe.**
Currently the active preset will be replaced with the default preset after a reset

**Describe the solution you'd like**
Somthing like saving the active preset as soon as it's selected (also if it's time controlled) so it will also be selected after a reset

**Additional context**
I noticed this "problem" since i use the time related presets, which won't be used after a reset

Thank you all so much for maintaining this wonderful projekt, i love it

**Comment by blazoncek** [comment]
There is a usermod called Auto Save that implements this feature.
Be mindful that too many writes will wear down flash on your ESP.
