### ISSUE TITLE
Bus manager classes can accidentally free pins it didn't successfully allocate

### ISSUE THREAD

**Issue by henrygab** [Aircoookie/WLED#2063]
**Describe the bug**

Bugs in bus manager classes cause de-allocation of pins already allocated to other resources.

**To Reproduce**

Compile with some pins in use.  For example:
`-D IR_PIN=0  -D BTNPIN=1 -D RLYPIN=2`

Edit exported JSON to add LEDs, such that the `BusConfig` structure matches the following array of three busses:

```C++
BusConfig bc[] {
    // type, count, start, colorOrder, reversed, skip, pins[5]
    { 41, 5, 0, 0, false, 0, {  3,  4,  5,  6,  7 } }, // 5-channel analog
    { 50, 5, 0, 0, false, 0, {  8,  9, -1, -1, -1 } }, // WS2801
    { 51, 5, 0, 0, false, 0, { 10, 9, -1, -1, -1 } }, // APA102
    { 45, 5, 0, 0, false, 0, {  3,  4,  5,  6, -1 } }, // 4-channel analog
};
```

**Expected behavior**

* 5-channel analog succeeds, allocates pins 3..7.
* WS2801 succeeds, allocates pins 8 & 5.
* IR, button, relay, WS2801, and 5-channel analog retain their allocated channels.
* APA102 fails, because at least pin 9 already allocated to WS2801.
* 4-channel analog fails, because at least pin 3 already allocated to 5-channel analog.

**Actual behavior**

* For APA102, `BusDigital` constructor [fails to allocate pin 9 at line 114](https://github.com/Aircoookie/WLED/blob/8c44147a4596112a7f5d5720ae809949399e9d44/wled00/bus_manager.h#L113-L115).  Therefore, `cleanup()` is called, which [de-allocates pin 9 at line 198](https://github.com/Aircoookie/WLED/blob/8c44147a4596112a7f5d5720ae809949399e9d44/wled00/bus_manager.h#L198) ... **_even though pin 9 was already allocated to WS2801_**.

* For 5-channel analog, `BusPwm` constructor [fails to allocate pin 3 at line 233](https://github.com/Aircoookie/WLED/blob/8c44147a4596112a7f5d5720ae809949399e9d44/wled00/bus_manager.h#L232-L233).  It therefore calls `deallocatePins()`, which  [frees pin 3 at line 324](https://github.com/Aircoookie/WLED/blob/8c44147a4596112a7f5d5720ae809949399e9d44/wled00/bus_manager.h#L324) ... **_even though pin 3 was already allocated to 5-channel analog_**.

**WLED version**

 - Board: D1 Mini clone, any board
 - Version: All versions since commit 9518c5f2e4440f93384c5d706c28e99e7f12eb84
 - Format: code review

**Additional context**

I expect to have a fix soon, will submit PR then.

Thank you for your help!

**Comment by blazoncek** [comment]
Good catch. Already fixed in my fork.
