### ISSUE TITLE
Get all presets / playlists via json API

### ISSUE THREAD

**Issue by vento66** [Aircoookie/WLED#2070]
Is it possible in further  versions to read the presets / paylists via the json API?
It would also be nice to be able to start the playlists directly. Now I can only select the playlists, and must switch on separately.
like:
{"playlist": {"ps": [2,1,3,5,8], "dur": [10,30,30,200,10],"transition": 0,"repeat":1,"end":3},"on":true}

**Comment by blazoncek** [comment]
[WLED_IP]/presets.json
[WLED_IP]/win&PL=<playlist_preset_id>
