### ISSUE TITLE
Relay support ESP32

### ISSUE THREAD

**Issue by Tofty85** [Aircoookie/WLED#2074]
Hi, i am trying to get a relay to work in the same way is does on esp8266 to control my power supply.

I'm using ESP32 based NodeMCU with  4 strips ws2812b

i cant locate any pin which goes high/low with WLED power

if anyone can help me with this i would very much appreciate it

thanks

**Comment by 3ative** [comment]
By default WLED uses GPIO12 for the relay.

**Comment by 3ative** [comment]
Or if you have the latest version, you can set it yourself
![relay](https://user-images.githubusercontent.com/51385971/128638655-5c1fa57b-37a3-43cd-ad05-7d25485d7336.jpg)
