### ISSUE TITLE
Use cold-white channel of RGBWC PWM led-strip

### ISSUE THREAD

**Issue by Lars-Thestorf** [Aircoookie/WLED#2078]
Hello,

i have build myself a second WLED Device, an LedPanel containing a PWM RGBWC (RGB + warmwhite + coldwhite) strip.

After Setup the cold-white channel wasn't working. After some debugging i figured out that the channel is simply completely unused in software:
https://github.com/Aircoookie/WLED/blob/123bd0bb92ebe76eba5a95b8521ff8094a39f05c/wled00/bus_manager.h#L275

Since I want to be able to use all LEDs of my panel for full brightness i have an suggestion.
As a simple first solution i would like the cold-white channel to also use the white value by changing _data[4] = 0; to _data[4] = w;

Thank you for your help and very awesome wled software.

**Comment by Aircoookie** [comment]
Supported natively since 0.13.0-b6 :)
