### ISSUE TITLE
Siri can’t find blue

### ISSUE THREAD

**Issue by Phatsyd** [Aircoookie/WLED#2081]
**Describe the bug**

When calling Siri to turn LEDs blue via homebridge/HomeKit the latest version cannot display blue other versions are fine.  Just 0.13.0-b2. 
Works fine with 0.11.0

**To Reproduce**
Steps to reproduce the behavior, if consistently possible

**Expected behavior**
Turn LEDs Blue RGB is set correctly

**WLED version**
 - Board Wemos D1 esp8266
 - Version 3.0.0
 - Format Binary

**Additional context**

Thank you for your help!

**Comment by maiiikell1995** [comment]
Which plugin do you use for homebridge? I couldn't find one that is well maintained
