### ISSUE TITLE
Preset cycles when start controller 

### ISSUE THREAD

**Issue by kolobok24rus** [Aircoookie/WLED#21]
Hi @Aircoookie
What to change in the code so that when the controller start, a сycle presets is started?
presetCyclingEnabled = true; not work

**Comment by kolobok24rus** [comment]
Great news, I'll follow the development of the project
Thank you!

**Comment by Aircoookie** [comment]
This is now supported in 0.7.0! Set your favorite preset cycle, then go to LED settings, check the "Save current preset cycle configuration as boot default" setting and save!
