### ISSUE TITLE
New binaries with latest updstes

### ISSUE THREAD

**Issue by chitrangad** [Aircoookie/WLED#210]
Hi would it be possible to release new binaries with all the latest updates (mqtt, cooling etc)? 
Thanks for the great work and awesome software!

**Comment by Aircoookie** [comment]
You are correct, this is long overdue. Releasing 0.8.5 tomorrow!
You're welcome! :)

**Comment by chitrangad** [comment]
Thank you!

**Comment by Aircoookie** [comment]
Takes a bit longer due to a short-term issue! Sorry :)

**Comment by alanlawton** [comment]
Has this been released somewhere?

**Comment by Aircoookie** [comment]
Here is a binary of current master!
Still need to do some bug testing before releasing 0.8.5, coming this week!
https://cdn.discordapp.com/attachments/473448917543944193/620321838169325598/wled_1908303_master_ESP8266.bin
https://cdn.discordapp.com/attachments/473448917543944193/620329347601006632/wled_1908303_master_ESP32.bin

**Comment by alanlawton** [comment]
Thanks
