### ISSUE TITLE
Sync infrastructure / Instance sync disable

### ISSUE THREAD

**Issue by Sturm2002** [Aircoookie/WLED#2102]
**Describe the solution you'd like**
having the possibility to select which instances to sync to which one, for example instance 0 is the "master" and 1 and 2 should sync to that one, but in your other room you have another instance 3 which is also a "master" and 4 and 5 should sync to instance 3

**Describe alternatives you've considered**
another sync option (the button on the top left) wether exactly this instance should sync at all, so you could sync for example 2 out of 3 instances and the third is a "standalone" instance.

**Additional context**
![Screenshot 2021-07-29 102820](https://user-images.githubusercontent.com/50213395/127459149-b8f0340d-d3cb-4916-b20e-a6e873ac486f.png)

Thank you for maintaining this wonderful project <3

**Comment by huggy-d1** [comment]
In instance 0, 1, 2, leave the UDP sync port # at the default value.
In instance 3, 4, 5, change all UPD sync port #'s, say to one port # higher.
Then they are independent of each other.
It's all about the sync port # as to which devices talk to one another.

**Comment by Sturm2002** [comment]
Oh, i didn't know that. thank you very much ^^
