### ISSUE TITLE
Control Strips on a Pin Basis

### ISSUE THREAD

**Issue by dremerb** [Aircoookie/WLED#2104]
The support for multiple strips is amazing! Allows for more lights per ESP.
While we have segments to virtually split strip, the output to all pins currently is the same. How about enabling dedicated controls for every connected strips? Would allow to e. g. have one ESP per room, but with different lighting zones.

**Comment by huggy-d1** [comment]
I believe that is working in someone's development fork right now.  You may be able to search the topics on the WLED discourse site and find it, download / install and try it out.

**Comment by blazoncek** [comment]
This is indeed in works, very early stages though.

**Comment by blazoncek** [comment]
DDP out (which will solve this issue) will be available shortly with next 0.13 beta release.
Closing.
