### ISSUE TITLE
effects work on PC Via bowser but via phone browser or app cant change 

### ISSUE THREAD

**Issue by FigJam23** [Aircoookie/WLED#2115]
**Describe the bug**
Unable to change effects via phone browser or 
WLED app but works via browser on PC Fine

**To Reproduce**
Use using phone either android or apple dosent work via PC changes fine

**Expected behavior**
Should change effects via phone browser or app but only works on PC

**WLED version**
 -  ESP32 dev kit v1]
 -
 - WLED_0.12.0_ESP32.bin

Thank you for your help!

**Comment by huggy-d1** [comment]
Have you tried the latest firmware which probably addressed the bug you are experiencing?  v0.13.x

**Comment by Aircoookie** [comment]
What is your phone model, OS version and browser? :)

**Comment by FigJam23** [comment]
> Have you tried the latest firmware which probably addressed the bug you are experiencing? v0.13.x

Yeah was running latest version of bats downgraded to latest stable with same issue. Strangely after a few reboots it now seems to work as it should

**Comment by FigJam23** [comment]
> What is your phone model, OS version and browser? :)

Seems to be working now but just in case it helps devices that issues was not working on was a Google pixel 2xl and a iphone 8 running latest os
