### ISSUE TITLE
Additional Time Zone: AKST (Alaska Standard Time)

### ISSUE THREAD

**Issue by lefesj** [Aircoookie/WLED#2121]
**Is your feature request related to a problem? Please describe.**
Problem - AKST does not exist in the time zone settings for NTP config.

**Describe the solution you'd like**
I would like the AKST (UTC -9) added to the list of time zones.

**Describe alternatives you've considered**
Only alternative is manual entry of mins to sec conversion 

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by Aircoookie** [comment]
Hi!
Sure, that can be added.
Just to clarify, you are looking for AKST/AKDT with daylight saving time (which would make your time zone UTC-8 currently until Nov. 7 at 2am), correct?

**Comment by lefesj** [comment]
Yes, exactly!  Thank you!
