### ISSUE TITLE
Doku : missing definition for JSON api values

### ISSUE THREAD

**Issue by DutchmanNL** [Aircoookie/WLED#2131]
Hey @Aircoookie,

I update all source of our ioBroker adapter to be in line with WLED 0.13

I found some new values the docu is not mentioning their purpose/description can you please clarify ? :)

ndc
of
fx
f1x
f2x
f3x
spc
grp

**Comment by Aircoookie** [comment]
Hey!
Thanks, I've added the description to https://kno.wled.ge/interfaces/json-api/ for ndc, grp, spc and of.
fx is the effect within the segment, but this is an old property.
I don't recognize f1x, f2x  and f3x, these are not part of my JSON API. Perhaps you have a sound-reactive binary, I am quite sure it uses these for additional effect sliders on some effects.

By the way (this is somewhat related to #2122 ), usermods may add custom values to the API response, or I  may add some that are only useful internally in the UI. I would recommend that your integration ignores all values in the JSON it is not written to explicitely utilize, which would likely be the easiest way. If that has undesirable side effects or is not possible within the ioBroker framework, you can fully ignore the `state.u` and `info.u` objects, which are meant for custom usermod values. These two objects may or may not exist and may or may not contain their own child objects :)

**Comment by DutchmanNL** [comment]
> I would recommend that your integration ignores all values in the JSON it is not written to explicitely utilize, which would likely be the easiest way. If that has undesirable side effects or is not possible within the ioBroker framework, you can fully ignore the `state.u` and `info.u` objects, which are meant for custom usermod values. These two objects may or may not exist and may or may not contain their own child objects :)

great that was al I needed to have proper filtering implemented.
I basically do not work with a "Whitelist" of states but will do the "blacklist" for everything in state.u and info.u

As ioBroker itself is an data interaction platform, I leave it to the consumer which states/API information they would like to use instead of altering all out except I think they need. But in this case, as these are custom attributes for guidance purposes, it makes no sense to get them

Will update that in next release of ioBroker.wled adapter
