### ISSUE TITLE
JSON IR remote not working with codes greater than 0xFFFFFF

### ISSUE THREAD

**Issue by valerachuk** [Aircoookie/WLED#2135]
**Describe the bug**
My IR remote produces codes such as "0xB5909768", "0xB590D52A".
So, my ir.json doesn't work
```
{
  "desc": "Custom",
  "0xB5909768": {
    "label": "Toggle",
    "pos": "1x1",
    "cmd": "T=2"
  },
  "0xB590D52A": {
    "label": "Brightness up",
    "pos": "1x2",
    "cmd": "A=~25"
  },
  "0xB5903DC2": {
    "label": "Brightness down",
    "pos": "1x3",
    "cmd": "A=~-25"
  }
}
```

**WLED version**
 - Board: nodemcu v2
 - Version: 0.13.0-b2
 - Format: self-compiled

**Additional context**
I've commented out the line ```  if      (code > 0xFFFFFF) return; //invalid code```  in ```void decodeIR(uint32_t code)``` in ir.cpp and my codes started working fine. 

I think, the method ```void decodeIRJson(uint32_t code)``` can be called without such restriction

**Comment by Aircoookie** [comment]
Thank you, I've applied your feedback :)
