### ISSUE TITLE
WLED not responding to MQTT

### ISSUE THREAD

**Issue by Thotho131097** [Aircoookie/WLED#2142]
Hi all,

I am a newbie to WLED and MQTT. I've tried to setup my MQTT towards WLED, yet I am unable to get response.
I've used the same settings for my SONOFF MINI + RF BRIDGE (except for different topics etc) and this is working fine.

Can anyone see a mistake I am making? 
WLED settings:
![image](https://user-images.githubusercontent.com/89147367/129918526-f1895c6f-b2e9-4c38-bda5-0e18a6944bf2.png)

Home assistant / NODE red settings:
![image](https://user-images.githubusercontent.com/89147367/129918613-8f21c4f6-9eb3-4eb3-bc2d-b35048aa3b85.png)

Message. payload settings:
![image](https://user-images.githubusercontent.com/89147367/129918657-2bc4b4db-5086-466f-bc02-de9f7c9e18ce.png)

Testsetup is basicly a inject node, message gets transformed to "Toggle" and sent over MQTT towards WLED:
![image](https://user-images.githubusercontent.com/89147367/129918740-afcca55e-b129-4350-8b34-386b90dc1636.png)
Yet WLED does not seem to receive the message :( 
What am I missing here?
 (I cant seem to find a console type of thing to troubleshoot either (like in tasmota), is this available on WLED?

**Comment by victorclaessen** [comment]
Can you test with another tool (like MQTT Explorer, or mosquitto_sub) to see if the messages you expect WLED to receive are really being published on the broker?

**Comment by blazoncek** [comment]
do not use same topic for device and group.

**Comment by Aircoookie** [comment]
Dumb question, but have you rebooted WLED after adding your MQTT configuration?
