### ISSUE TITLE
my /edit page is not accessible

### ISSUE THREAD

**Issue by neckyaan** [Aircoookie/WLED#2145]
Version 13.0-b2 http://[controller-ip]/edit page is not accessible，my Lock wireless (OTA) software update is open。 [controller-ip] is 192.168.*.*
Google Chrome
Google Chrome is already the latest version
Version 92.0.4515.159 (official version) (64-bit)

**Comment by Aircoookie** [comment]
Hi!
Sorry about that. What error does the browser give, a timeout or 404?
It is also possible that it does not load if you don't have internet access on your device (e.g. when connected to WLED-AP), as it needs to load the `ace` library: https://github.com/Aircoookie/WLED/issues/1592

**Comment by neckyaan** [comment]
![2021-08-19 162738](https://user-images.githubusercontent.com/42715960/130035130-27bb31cc-bc74-4538-bb29-31b51c6f40b0.png)
![2021-08-19 162621](https://user-images.githubusercontent.com/42715960/130035156-26d2509a-85d3-476e-b691-d9feb744c542.png)

**Comment by neckyaan** [comment]
the browser give me nothing pormpt

**Comment by Aircoookie** [comment]
Seems like it is indeed having problems loading the ace library. We will need to modify the `/edit` page to fallback to a simple textarea if ace cannot be loaded. I believe @embedded-creations recently had a look at a fork of ESPAsyncWebserver which improves the `/edit` page.

**Comment by blazoncek** [comment]
please show your Network tab after reloading /edit page

**Comment by embedded-creations** [comment]
> I believe @embedded-creations recently had a look at a fork of ESPAsyncWebserver which improves the `/edit` page.

This issue is still present

**Comment by neckyaan** [comment]
Sorry for the late response
I found the problem. There are network restrictions in my area, which prevents me from accessing https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js

**Comment by Aircoookie** [comment]
Alright :) I'll close this as it is just another manifestation of #1592 , but that doesn't change the fact that we should add a fallback if the library can't be fetched.
