### ISSUE TITLE
MQTT: XML data missing power state information

### ISSUE THREAD

**Issue by 0rsa** [Aircoookie/WLED#2146]
Hi,
Please add an attribute to know if WLED is ON or OFF in XML data
A single attribute containing brightness value is not enough, you can have a WLED OFF with brightness set to a value > 0, we miss one information with a sinle attribute for toggle/brightness.
Thank you

Refering to: https://github.com/Aircoookie/WLED/wiki/HTTP-request-API section XML response

**Comment by blazoncek** [comment]
It is not possible to have bri(ghtness)>0 and have WLED turned off or the other way around (having bri==0 and WLED on).

If global brightness equals 0 it means WLED state is OFF. If it is not equal to 0 then WLED state is ON.

**Comment by 0rsa** [comment]
@blazoncek I have this JSON history in my database logs

`{"state":{"on":false,"bri":29`

Master Off/On/Toggle is "OFF" (false)
Master brightness is 29

If brightness and toggle are the same, how retrieve your previous brightness when you toggle on your WLED?

**Comment by blazoncek** [comment]
It is internally stored and retrieved when needed.

What you are seeing in JSON is stored value.
```
root["on"] = (bri > 0);
root["bri"] = briLast;
```

**Comment by 0rsa** [comment]
Ok, thank you.
Why not to share this internal value in XML data?
Why XML works in a different approach of JSON?

**Comment by blazoncek** [comment]
It doesn't. JSON just gives you additional information.
Some things are difficult to implement in JSON some in XML/HTML. You can freely mix the two in your API calls.

**Comment by 0rsa** [comment]
Sure but I'm currently switching to MQTT due to HTTP JSON issues :)
https://github.com/Aircoookie/WLED/issues/2141
Mixing requests it not an option for my case.

**Comment by blazoncek** [comment]
Check if you are flooding WLED with too many requests at once.

**Comment by 0rsa** [comment]
Moving to WebSockets to use JSON instead of MQTT / XML.
Thank you
