### ISSUE TITLE
Unable to connect to a Wifi network when WPA password contains exclamation mark "!"

### ISSUE THREAD

**Issue by GendronAC** [Aircoookie/WLED#2148]
**Describe the bug**
I am unable to connect the WLED to my network. Password is in the form <8 letters><1 digit><1 special char> (e.g. AlloAllo3!)

**To Reproduce**
1. Factory boot on a ESP8266 2M running version 1.12.0
2. Setup wifi to my home network with said password (e.g. AlloAllo3!)

**Expected behavior**
Able to connect to the network and rock the neighborhood !

**WLED version**
 - Board: Kuman NodeMCU LUA WiFi Internet ESP8266 KY69
 - Version 0.12.0
 - Format : official release binary

**Additional context**
Created a secondary SSID on my network with a password without a "!" and was able to connect, so I don't think any other element is related.

Congratulation on this awesome project !

**Comment by jdanbru** [comment]
I have an “!” In my WiFi password.

what’s your network setup?

**Comment by GendronAC** [comment]
Ubiquity (multiple devices)

Le sam. 21 août 2021 00 h 03, realJustinBruce ***@***.***> a
écrit :

**Comment by blazoncek** [comment]
Try updating firmware on your Ubiquiti APs.

**Comment by GendronAC** [comment]
Using the latest. Close it if you are unable to reproduce it.

Le sam. 21 août 2021 09 h 52, Blaž Kristan ***@***.***> a
écrit :

**Comment by Aircoookie** [comment]
I've had multiple reports of SSIDs with special characters not working in a past.
Since "change your password" would be bad advice and a considerable effort, we need to find out what causes this and what characters are affected.

I will ask on discord if others have SSIDs with an `!` that can connect successfully.

**Comment by GendronAC** [comment]
The ssid is using plain character (MaisonOiseau)

"LedDriver" is working
"MaisonOiseau" isn't

**Comment by GendronAC** [comment]
![MaisonOiseauConfig](https://user-images.githubusercontent.com/45271725/130374783-8de911c4-b883-479d-900b-87f69d48c1c3.jpg)
![LedDriverConfig](https://user-images.githubusercontent.com/45271725/130374785-0ed4bcd4-ef87-435b-b2e2-fc9d3d8db7fe.jpg)

**Comment by Eddiiie** [comment]
I have Ubiquity, my wifi password has !  at beginning and end.   Not problems.
