### ISSUE TITLE
The name of the wifi network does't change after saving

### ISSUE THREAD

**Issue by Baroo4** [Aircoookie/WLED#2152]
Hi,
I recently purchased a WS2815 LED strip and ESP2866. I installed the software from the WLED website and when I want to change the WIFI settings (network name and password) after clicking save&connect, my settings are not saved because the network is still WLED-AP. Does anyone know how to solve it? Thank you in advance!

**Comment by blazoncek** [comment]
That means WLED cannot connect to your network.
That may be due to it being 5GHz, has incompatible SSID name or password with characters ESP libraries cannot handle.
