### ISSUE TITLE
[JSON] add IP address

### ISSUE THREAD

**Issue by CWempe** [Aircoookie/WLED#2154]
I just realized the ip address is not listed in the JSON output.

There might be cases where a user accesses the device via hostname and does not know the ip address.

This is just a nice-to-have feature request. 😄 
I do not need this (at the moment).

But I think this would make the json output more complete.

**Comment by Aircoookie** [comment]
This has been added in #1912 and will be availabe in 0.13.0!
I realized though that it isn't documented yet, so added that to [kno.wled.ge](https://kno.wled.ge/interfaces/json-api/)  😃
