### ISSUE TITLE
Defaults Turn LEDs on after power up/reset Check box is invalid

### ISSUE THREAD

**Issue by neckyaan** [Aircoookie/WLED#2155]
**Describe the bug**
WLED 0.13.0-b0 (build 2106302)  Defaults Turn LEDs on after power up/reset Check box is invalid

**Comment by neckyaan** [comment]
> **Describe the bug**
> WLED 0.13.0-b0 (build 2106302) Defaults Turn LEDs on after power up/reset Check box is invalid

thank you for all your hard work and devotion you have put into this Aircookie.

**Comment by Aircoookie** [comment]
Hi and thank you for the report!
What do you mean with the checkbox being invalid?
Does the browser display an issue or is the option not doing what you expect?

**Comment by neckyaan** [comment]
Yes, a preset is selected. But WLED 0.12, WLED 0.13.0-b2 have no such problem, the same setting.

**Comment by blazoncek** [comment]
Boot options slightly changed in recent beta.
Closing.
