### ISSUE TITLE
macOS Menu Bar App

### ISSUE THREAD

**Issue by satrik** [Aircoookie/WLED#2159]
Hi, 
I've written a small Menu Bar Application to control power/brightness of a WLED device.
I thought I link it here because it might be interesting for other users.
Maybe you can also add it to the _Compatible Software_ section in the wiki :) 

https://github.com/satrik/wledQuickControl

Greetings
satrik

**Comment by satrik** [comment]
@blazoncek sorry for the late response. I've tested it and to get all `_wled._tcp.` devices works very well, but I need to find some time to implement it into the app. I hope I will get it done over the weekend 🙂

**Comment by satrik** [comment]
btw. I had the same issue as #2009 and found a fix/workaround

**Comment by satrik** [comment]
@blazoncek I've created a dev branch with the "new" version of the app. would be nice if you (and of course all others who are reading this) can test it and give me feedback in the repo 🙂 https://github.com/satrik/wledQuickControl/tree/dev

**Comment by blazoncek** [comment]
Sorry for lack of updates, am quite busy lately.
I hope to have some time this weekend.

**Comment by blazoncek** [comment]
Unfortunately I do not have any mac with macOS 11. ☹️ 
Can you make app compatible with older macs? High Sierra & later.

**Comment by satrik** [comment]
I'm not sure if the system glyphs will work with earlier versions. Can you try to run the xcode project and see if there are any error?

**Comment by blazoncek** [comment]
I have a fairly old Xcode which I never really used (since I don't do any mac programming).

**Comment by satrik** [comment]
@blazoncek I've added a "wledQuickControlTest.zip" file to the dev branch. It's comlied for macOS 10.13 and above. Could you please test it?

**Comment by blazoncek** [comment]
Will do. Just give me some time. 😃

**Comment by blazoncek** [comment]
Sorry for the delay. Unfortunately it still says macOS 11 required.
![ScreenShot 2021-09-18 at 21 25 21](https://user-images.githubusercontent.com/7722392/133906376-f162bc1a-3c21-4c80-9187-b2fee8b4e1a1.png)

**Comment by satrik** [comment]
I think that's because of the system icons I use for the buttons... I will make a version with "ugly buttons" and without icons - just to see if it will work then.

**Comment by satrik** [comment]
And here wo go again :D 
I've uploaded another [version](https://github.com/satrik/wledQuickControl/blob/dev/wledQuickControlOldIcons.app.zip) 
I've just replaced the icons _quick and dirty_ with TouchBar icons (which should work).

Would be nice if you could test it again :)

**Comment by blazoncek** [comment]
Will do.

**Comment by blazoncek** [comment]
Ok, feedback time!
- refresh devices only found 1 device (the one updated with your mDNS fix)
- left-clicking on the icon does nothing
- clicking on the bullet (left of brightness slider) does nothing
- I would prefer to have all WLED devices shown in a list with on/off and brightness slider next to the name
- re-opening app icon selects 1st WLED instance instead of last used even though brightness shows the last one
- I would use separate config dialog for adding devices and configuring

**Comment by satrik** [comment]
Ok, I can't reproduce the issues you have... Could be that there are still some newer function which are not available in macOS < 11 or maybe something else is now broken after I've deployed the code for older versions. 

My initial goal was to have a small app to control exactly 1 WLED instance and I don't even have any use case for controlling more. So I think I don't will spent more time in the project and will focus again on the initial app.

**Comment by blazoncek** [comment]
Understand. Wish you luck. 👍

**Comment by Aircoookie** [comment]
Added to https://kno.wled.ge/basics/compatible-software/ :)
