### ISSUE TITLE
stairway_wipe_basic usermod not working

### ISSUE THREAD

**Issue by LoschLED** [Aircoookie/WLED#2161]
Hey,

i recently tried to implement the usermod stairway_wipe_basic to my wled on esp32. For compiling I used VS code and platformio, which perfectly worked. But after successfully updating the esp32 with the new version of wled, the usermod doesnt appear in the config at usermods. I did everything as described to implement the usermod and I even tested other usermods which showed up correctly at usermods. Is there anyting I missed?
![Unbenannt](https://user-images.githubusercontent.com/89608816/131029132-25ab56ad-a22d-46d2-915b-eacf6b78a503.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/89608816/131029154-ff097d84-5f72-42d7-98ea-cdb111e293a7.JPG)

**Comment by blazoncek** [comment]
Yes, only _Animated Staricase_ usermod has been updated to be runtime configurable.
The usermod you are specifying still needs modifications to be runtime configurable but since _Animated Staircase_ is superior it may never get that attention.

**Comment by LoschLED** [comment]
Alright, so theres most likely no way I can use this usermod?

**Comment by blazoncek** [comment]
If you are willing to invest time into figuring the inner workings you can.
But I would recommend Animated Staircase usermod instead.
