### ISSUE TITLE
Certain Effects not behaving correctly

### ISSUE THREAD

**Issue by kas21** [Aircoookie/WLED#2166]
**Describe the bug**
Certain effects are not working as they should.  For example, Tri Chase does not show the three color pattern uniformly across the segment.  The first and and last third of the segment show colors 1 and 3.  The center third shows colors 1,2, and 3.  I've noticed some other effects impacted in similar ways where there is a bias toward the center of the segment.

**To Reproduce**
Select Tri Chase, set three colors, select Colors Only

**Expected behavior**
All three colors repeated uniformly across the segment.

**WLED version**
 - Board: ESP32 on a Dig Quad
 - Version 0.12.0
 - Format Binary
 - 
![image](https://user-images.githubusercontent.com/367045/131735044-a4fd2b3a-6083-4ff5-a894-9a02d5ffe782.png)

**Comment by blazoncek** [comment]
You should have all segments checked prior to applying colors and effects.

**Comment by kas21** [comment]
Did more testing and this may not be a bug.  If you select "* Colors Only" you get the odd behavior that I described in the report.  If you select "Default" it works as intended and all 3 colors are repeated throughout the entire segment.  I would have expected the Colors Only and Default to work the same way.

**Comment by blazoncek** [comment]
"Default" palette just means whatever an effect considers most natural to it. i.e. Fire 2012 uses a palette that is the same as "Fire" palette.
"* Colors Only" means use only col1, col2 and col3 as a palette (equally spread across 256 values)
You can see a preview of a palette on a palette selection button.
