### ISSUE TITLE
How i Convert index.html as binary ? 

### ISSUE THREAD

**Issue by sanjulanipun** [Aircoookie/WLED#2173]
**i need to know ho i can covert index page as binary?**
**like this ? i need to customize index page and after covert binary and after i need to upload normally code. anyone know how to convert html page like this ?**

![image](https://user-images.githubusercontent.com/32708235/132013304-1958e218-d7dd-4026-b980-08fc9d87aa96.png)

**Comment by blazoncek** [comment]
https://kno.wled.ge/advanced/custom-features/

**Comment by sanjulanipun** [comment]
> https://kno.wled.ge/advanced/custom-features/

**ok, my problem is ok. but please i need to know how i can covert html code like this binary? this question for my knowlage. please tell me any tool or something how i can covert html code like this binary code. plz.**

**Comment by blazoncek** [comment]
Read the article. It details exactly what to do.
