### ISSUE TITLE
save/filesystem not working on an esp32 s2

### ISSUE THREAD

**Issue by vautieri** [Aircoookie/WLED#2174]
**Describe the bug**
first noticed that homeassistant wouldn't configure when auto detected.  Found out if I remove power to the chip, it also comes up with default parms.  Going to the "control" one sees an error pop up about configurations.

**To Reproduce**
install on an esp32-s2 chip.  I have the cucumber which is an ESP32-S2-WROVER

**Expected behavior**
use the filesystem

**WLED version**
 - Board: ESP32-S2-WROVER
 - Version latest
 - Format selfcompiled (used your only esp32-s2 config, I don't see why it wouldn't work (not a guru yet with partitions)

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by blazoncek** [comment]
S2 is not yet fully supported.
And as you have discovered, it is a FS causing troubles.
