### ISSUE TITLE
Effect flicker when applied to segment

### ISSUE THREAD

**Issue by gmcaesar** [Aircoookie/WLED#2178]
**Describe the bug**
Strips flicker between each change when using effect on a single segment, but not when applied to entire strip

**Expected behavior**
Smooth fades etc when running effects right now it almost looks like strobe and any other effect combined, but only when applied to segments that are not the entire strup

**WLED version**
 - Board: dig uno board
 - Version 13.0-b2 build 2107100

**Comment by blazoncek** [comment]
Known issue with 0.13-b2.
