### ISSUE TITLE
wled json api on pyhton/micropyhton

### ISSUE THREAD

**Issue by nickpesman** [Aircoookie/WLED#2181]
I am working on a little project which requires me to use the json api from wled. I am using a esp32 running micropython. And i have been stuck on this for a while now. When i send a get command to the api i get nothing in return. Or it just bugs and errors and i can't seem to figure out why. when i do get request to a json test website it is fine but i doesn't work on wledip/json for some reason. does someone have any idea how i van fix this? Or have something else i could try?

A simplified version of my code:
![wledjsonrequest](https://user-images.githubusercontent.com/50640258/132727178-a95631de-8282-411b-89d6-48f1bd5ca418.JPG)

**Comment by ChuckMash** [comment]
Can you show some less simplified code, or the error?

**Comment by nickpesman** [comment]
Yea sure
![image](https://user-images.githubusercontent.com/50640258/132919017-28d75733-f390-402f-a003-1538e964e1f0.png)

Here is my code. This is what i get when i try to call the wled-ip/json url. It gives mee a 200 response code en then just stops

![image](https://user-images.githubusercontent.com/50640258/132919203-89edbd90-a047-48a9-bc77-e8cc41774044.png)

Here is te same code but here i call a json test website httpbin.org and it works just fine so i don't know what i am doing wrong here.

**Comment by ChuckMash** [comment]
Does networkcred.ipaddresswled translate to something like http://4.3.2.1/json ?

Not sure about how micropython urequests lib differs from regular pythons requests lib.
In any case, not sure if this is related to WLED.

**Comment by blazoncek** [comment]
Include `"v": true` in your JSON requests to get verbose response.

Normally GET-ting /json endpoint will return state and info objects, as well as palettes and effects.

**Comment by nickpesman** [comment]
Do you mean something like this?
![image](https://user-images.githubusercontent.com/50640258/132987257-28af4a32-edd8-49f7-aa34-228fdd192b03.png)

because this doesn't work for me....

**Comment by blazoncek** [comment]
I said JSON. I have no clue how to create JSON object in Python. I do not know anything about Python for that matter.
And this may entirely be your particular Python problem, not WLED problem.

In any case use `curl` to test your setup and IPs used.

`$ curl http://wled.local/json` where _wled.local_ would be your WLED device IP address or mDNS name.

The response should look something like:
`{"state":{"on":true,"bri":128,"transition":10,...},"info":{"ver":"0.13.0-b2","vid":2109101,"leds":...}`
