### ISSUE TITLE
Using the WLED/usermods/bridgeway_wipe_basic/  how ?

### ISSUE THREAD

**Issue by hudako417** [Aircoookie/WLED#2185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Can't you provide any description?

**Comment by hudako417** [comment]
Please guide, compile and export the bin file

**Comment by blazoncek** [comment]
[https://kno.wled.ge/advanced/compile-wled/](https://kno.wled.ge/advanced/compile-wled/)

**Comment by softhack007** [comment]
Loses due to inactivity, and lack of information to reproduce the problem.
