### ISSUE TITLE
Connected strip to DOut by mistake 

### ISSUE THREAD

**Issue by sanjayjuded** [Aircoookie/WLED#2189]
I hope someone can help me.

I am using wled for my Alter lights. Used 2 individual leds (1st seg) for candles. Then used 7 leds in strip (2nd seg). This was working fine.

The problem came when I extended the strip for 15 more leds. By mistake I connected the 2nd segment at the DOut pin to DOut of the 1st segment. The last led of 2nd strip was lighting up. I then increased the led count in wled but the 2nd segment was not lighting up. When this happen I noticed the mistake. It seems the complete segment blew up.

How do I check the strip. I am asking here because I know I will get an answer.

In the meantime I got another piece of the strip and made the correct connection for the 2nd segment which is working fine. So the 1st segment of candles is not blown up.

**Comment by blazoncek** [comment]
Please use Discord for support.
