### ISSUE TITLE
Segments return after deleting

### ISSUE THREAD

**Issue by darranwil** [Aircoookie/WLED#2200]
**Describe the bug**
Segments return after being deleted.

**To Reproduce**
Add 2 segment. Set Options. Save. Reboot device.  Delete second segment. Save. Reboot. Second segment has returned.

**Expected behavior**
Be gone!

**WLED 0.13.0-b2**
 - Board: Wemos D1 mini
 - Version [e.g. 0.10.0, dev200603]
 - Format Binary

**Additional context**
Anything else you'd like to say about the problem?

Thank you for your help!

**Comment by blazoncek** [comment]
Cannot reproduce.
Please update to b3 (or newer build from @srg74) and reproduce.
If you can reproduce with newer version, please write down exact values and steps needed.
