### ISSUE TITLE
How can I set wled to run a LED mode every 30 mins then revert back to normal?

### ISSUE THREAD

**Issue by nftarts** [Aircoookie/WLED#2207]
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by blazoncek** [comment]
For support questions please use WLED Discord or provide a detailed description.
