### ISSUE TITLE
Cold white LED never turns on in RGBWC

### ISSUE THREAD

**Issue by hamed-ta** [Aircoookie/WLED#2208]
When I set up Wled with my own custom esp8266 hardware which has 5 PWM channels for RGBWC, the cold white channel never turns on when I chose the cold white color.

WLED version 0.12.0

you can see in the pictures 

![image](https://user-images.githubusercontent.com/9883945/133919002-0eab9224-21f8-4e38-ab18-d4994ed408fc.png)
![image](https://user-images.githubusercontent.com/9883945/133919159-227d2e3e-accd-458b-b2cf-d4e3718ae179.png)
![WhatsApp Image 2021-09-19 at 11 57 52](https://user-images.githubusercontent.com/9883945/133919195-6d34a6f9-22ad-4ad5-b7d1-9087723c3479.jpeg)

**Comment by blazoncek** [comment]
Control of WW/CW is only supported via Alexa control.
We are working on full support.

**Comment by KoffeinKaio** [comment]
I just hacked my chia RGBWC light from an WSB3L to an ESP8266 and ESP32 after that
With both current stable and current beta theres no way to control the C channel of RGBWC - cant seem to control it with alexa either.

Any way to get this to work? Or anyone knows a FW that supports this at the moment?
I dont need fancy effects, I just need an alexa controllable RGBWC light.

**Comment by blazoncek** [comment]
> Any way to get this to work? Or anyone knows a FW that supports this at the moment? I dont need fancy effects, I just need an alexa controllable RGBWC light.

You can compile _cct-support_ branch or use pre-compiled binaries from @srg74 from my fork (experimetal).
But AFAIK Alexa should be able to control your RGBWW strip with current binaries.

**Comment by blazoncek** [comment]
Fixed with CCT implementation.
