### ISSUE TITLE
Separate Color and White mode control

### ISSUE THREAD

**Issue by hamed-ta** [Aircoookie/WLED#2209]
Hello and thank you for your great project.

I think that would be very useful to have separate modes in the user interface to be able to switch in white color which users only can select a warm or cold white color and in this way if separate warm and cold white PWM channels are available only those channels are influenced, and a color mode which controls RGB channels. it is also available in Yeelight smart lamp app as you can see in the picture.
![WhatsApp Image 2021-09-19 at 12 05 29](https://user-images.githubusercontent.com/9883945/133919372-4667235b-85e8-4711-854f-ee08569b3ebb.jpeg)

**Comment by blazoncek** [comment]
A duplicate of #2208. Closing.
