### ISSUE TITLE
Pin for APA102 Led?

### ISSUE THREAD

**Issue by phamre** [Aircoookie/WLED#221]
What pin shold i use for apa102 on esp8266 and esp32 ?

**Comment by ssirkakriss** [comment]
Not tried the apa102 support yet.
This file has what you need to know.
https://github.com/Aircoookie/WLED/blob/master/wled00/NpbWrapper.h

**Comment by craigsincl** [comment]
If I remember correctly it pins D5 and D7 for apa102 clock and data lines

**Comment by HimbeersaftLP** [comment]
According to [these lines](https://github.com/Aircoookie/WLED/blob/40aaac58686dda009ebef3a9c82cddcbe25ea7a8/wled00/NpbWrapper.h#L15-L17) GPIO0 (D3 on NodeMCU) is used for CLK and GPIO2 (D4 on NodeMCU) for DATA.

**Comment by phamre** [comment]
Thanks. I will try when i get time
