### ISSUE TITLE
Adding support of digital or analog temp sensores

### ISSUE THREAD

**Issue by hamed-ta** [Aircoookie/WLED#2211]
Hello,

in order to add a protection facility to the device, having the support of different types of temprator sensors would add a great facility to the device to monitor and control the temperature of the device.

Thanks.

**Comment by blazoncek** [comment]
Currently DHT type sensors and Dallas DS18B20 are supported by usermods.

**Comment by blazoncek** [comment]
Closing due to feature being implemented as a usermod.
