### ISSUE TITLE
Animated_Staircase with 14 steps

### ISSUE THREAD

**Issue by Chillkroete1206** [Aircoookie/WLED#2216]
Hi there,

I am intended to light my stairs with wled and found the [Animated_Staircase ](https://github.com/Aircoookie/WLED/tree/master/usermods/Animated_Staircase) usermod.
As I understood I need to segment each step. As far as I know segments are limited to 10 for an ESP32 and even less for an ESP8266.
However I have 14 steps, so is there a way to use this in my case?

Thanks and regards,

**Comment by blazoncek** [comment]
Next beta will include 16 for 8266 and 32 for ESP32.

**Comment by huggy-d1** [comment]
Have you considered this less capable but functional usermod: https://github.com/Aircoookie/WLED/tree/master/usermods/stairway_wipe_basic

**Comment by blazoncek** [comment]
New beta with 16 segments for 8266 is out. Closing.
