### ISSUE TITLE
WLED as a octoprint plugin

### ISSUE THREAD

**Issue by codycato** [Aircoookie/WLED#222]
feature request: octoprint plugin with status led etc

**Comment by Mariu86** [comment]
I am interested in this :D . I have a 3d printer with octoprint and wled will be a very good addition .

**Comment by codycato** [comment]
:) I would also like to use the other gpio pins, ex. wled along with multisensor

**Comment by Aircoookie** [comment]
Thanks for the suggestion :) However I can't implement this at the time because it is very specific and i lack an Octoprint setup for testing. However, I believe this should definitely be possible using the WLED API!

**Comment by nibblerrick** [comment]
I think @cp2004 has done this with this plugin now: [OctoPrint-WLED](https://github.com/cp2004/OctoPrint-WLED)
