### ISSUE TITLE
DP "lor" in MQTT XML API response

### ISSUE THREAD

**Issue by Matten-Matten** [Aircoookie/WLED#2222]
_EN:_ Hello, I would like to have the data point "lor" in the "XML API"
so that the data point can also be set via MQTT

_DE:_ Hallo ich hätte gerne den Datenpunkt "lor" in der "XML API"
um den Datenpunkt auch via MQTT setzen zu können

BSP:
Advanced
<html>
<body>

Parameter | Value Range | Description
-- | -- | --
&LOR= | 0/1 | is receiving live data

</body>
</html>

bzw in XML Data:
`<lor>0</lor>`

@Aircoookie can you please integrate that?

Kind regards
Matten Matten

**Comment by Aircoookie** [comment]
Hi, adding LOR to the legacy HTTP API is unfortunately not planned.
However, you can send JSON requests like `{"lor":1}` via MQTT easily, just the other way around is not yet supported :)
