### ISSUE TITLE
Custom mapping problems

### ISSUE THREAD

**Issue by mase76** [Aircoookie/WLED#2223]
Hi!
I have a matrix 32x32 build with 4 matrices 32x8. I did a custom mapping in xLights, that worked fine.
To be more flexible, I wanted to use the custom mapping in WLED. I copied the mapping from xLights, and decremented every number, because, xLights starts with 1.
But some lines are horizontally displaced one LED.
Here is my ledmap.json renamed to txt. Maybe you can tell me, what's wrong.
[ledmap.txt](https://github.com/Aircoookie/WLED/files/7213775/ledmap.txt)

**Comment by mase76** [comment]
Now I use the alignment feature provided with the latest beta. But there is the same displacement effect.
For example the 32x32 Skull from xLights:
![IMG_20211002_144348](https://user-images.githubusercontent.com/2173853/135717168-d7b59a11-c48f-45fc-998a-58d3bbe8a73c.jpg)

**Comment by blazoncek** [comment]
Why not correcting those lines in ledmap.json?
Nobody said that xlights and wled have compatible ledmaps. 😉

**Comment by mase76** [comment]
Because it would be wrong with WLED effects, when I change the mapping that way.
