### ISSUE TITLE
Show Hardware Model on Manual OTA Page

### ISSUE THREAD

**Issue by MrPaulAR** [Aircoookie/WLED#2224]
**Describe the solution you'd like**
Display the hardware info (esp8266, esp32, etc) on the manual OTA page.  I'm lazy and simply forget to look at the info page.

**Comment by huggy-d1** [comment]
I think that is a fantastic idea.  Would help idiots like me keep from trying to load the wrong firmware.

**Comment by bphermansson** [comment]
Something like this? (But better looking of course :) )

![Screenshot from 2021-10-13 15-59-30](https://user-images.githubusercontent.com/3775861/137149045-b6ba5b7c-a98d-44b0-bbdf-b6a980633f28.png)

**Comment by MrPaulAR** [comment]
Works for me.

**Comment by MrPaulAR** [comment]
I believe this has gotten way off topic.  If the feature is useless then so be it, lets just close it out.

I would do this myself and submit a pull request but my front-end (and C++) skills are not up to par so I gave up.  

My goal wasn't to get under anyone's skin here.

**Comment by softhack007** [comment]
Implemented in 0.14.0-b1
