### ISSUE TITLE
Bad sunset/sunrise 

### ISSUE THREAD

**Issue by AndrejSayadov** [Aircoookie/WLED#2230]
Hello, I'm use WLED v0.13.0-b3. I from Novosibirsk, UTC+7, Latitude 55,02, Longitude 82,94.
![image](https://user-images.githubusercontent.com/89129698/134812017-5c8ff6a1-c572-49d0-8141-3251366b7a83.png)
![image](https://user-images.githubusercontent.com/89129698/134812028-ab4affc8-f1c4-458d-b2f7-c2088e97cbc1.png)

**Comment by AndrejSayadov** [comment]
Expect sunset=19:17

**Comment by blazoncek** [comment]
Fixed in [a94269c](https://github.com/Aircoookie/WLED/commit/a94269ceb9548a274dfd0d8b1b3fc17e9376c6ac)

**Comment by blazoncek** [comment]
WORKAROUND: if you compile with PIO and add *build_flag*`-D WLED_USE_REAL_MATH` then WLED will use standard *libc* functions instead
