### ISSUE TITLE
Pin configuration for serial communication

### ISSUE THREAD

**Issue by salbader** [Aircoookie/WLED#2234]
**Is your feature request related to a problem? Please describe.**
The Lolin32 lite board for ESP32 has not populated the pins GPIO1 and GPIO3

**Describe the solution you'd like**
Provide a configuration for the pins used for serial communication.

Thx, really appreciate your project, Holger

**Comment by blazoncek** [comment]
GPIO1 & GPIO3 are connected to USB interface. Use USB for serial.
If you cannot use USB you will need to reconfigure UART pins by modifying WLED code and compile yourself ATM.
There are currently no plans for this in our roadmap.
