### ISSUE TITLE
dead nodemcu board

### ISSUE THREAD

**Issue by sayeed205** [Aircoookie/WLED#2241]
Greetings ,
This is my 1st time working with wled and esp8266.
I flashed WLED_0.12.0_ESP8266.bin(687kb) via esphome flashed on nodemcu v2 .
It was working fine for some time then suddenly all led stopped its effect so i resupplied power then nodemcu stopped working and now it's heating like hell.
I didn't find any thread about this.
Also this happened to my two nodemcu
The blue light of nodemcu board is not working.

**Comment by blazoncek** [comment]
You can throw it away. The ESP.
Most likely short-circuited somewhere but also possible manufacturing flaw.
Had a few of those.

**Comment by sayeed205** [comment]
Same happened with two nodemcus
Sad :''''''(
My bad luck

**Comment by sayeed205** [comment]
After flashing wled 
Vin should be as 5v
D4 should be as data in
And gnd and gnd 
And i was using 5v 2amp 10w power supply 
Is it okay ?

Or this could make short circuit ?

**Comment by blazoncek** [comment]
I do not know. Never used NodeMCU.
Look at the technical data.
For support questions please use Discord.
Closing.
