### ISSUE TITLE
Insufficient LAT LONG Entry Fields

### ISSUE THREAD

**Issue by yodajones** [Aircoookie/WLED#2243]
**Describe the bug**
WLED is not calculating the correct Sunrise / Sunset from the Latitude and Longitude fields.  The Latitude and Longitude fields seem to be shortening the data entered, although I am not sure if this is why the results are incorrect.

**To Reproduce**
Config | Time & Macros | Latitude (N): {field} Longitude (E): {field}
It appears that the fields only accept two decimal points.  Example Lat = 42.43 Long = -123.35
This shortened lat long is indicating: Sunrise: 12:43 Sunset: 00:28 when it should be Sunrise: 07:10 Sunset: 18:55
Actual Lat and Long according to Google Maps = 42.458130502430514, -123.31770746479044

**Expected behavior**
Expected the Sunrise and Sunset to be correctly calculated.

**WLED version**
 - Board: ESP32
 - Version 0.12.0 - WLED 0.12.0 (build 2104150)
 - Format Pre-Installed on Dig Uno with ESP32
 
![wletime-settings](https://user-images.githubusercontent.com/3802894/135552525-3876796e-3128-4e87-bbd0-b9aa73a508e4.png)

**Comment by blazoncek** [comment]
This is a known bug, alrerady fixed in master.
Wait for new beta release or compile from master.
