### ISSUE TITLE
Generic data pins for ESP32 and ESP32 eth

### ISSUE THREAD

**Issue by harueg** [Aircoookie/WLED#2248]
Hi
What are the recommended data out pins. xlights did set one output pin on gpio12, which of course doesn't work.
I tried hard to find this info on the usual sites.

What ESP32 ethernet is referred to in the binary with esp32_eth ?
How many and which pins are left for LED data out ?

Thanks
Harald

**Comment by blazoncek** [comment]
Any GPIO in ranges 0-5, 12-33 should normally work.
Ethernet does reserve quite a few GPIOs. Please refer to Discord pinned messages in #dev-general topic.

**Comment by harueg** [comment]
I always had problems when connecting anything on gpio12, esp wouldn't boot.
But found a schematic of esp32_eth
<img width="753" alt="Screen_Shot_2021-03-29_at_10 13 17_AM" src="https://user-images.githubusercontent.com/60239890/135754257-4cb062d0-6204-4ff7-ba56-a5572a7550af.png">


Is the SN74AHCT a good choice or is the ADUM1400 better. Mr. Radig is using the ADUM1400 on his LED controllers, although a lot more expensive.

**Comment by blazoncek** [comment]
GPIO12 is safe to use in any combination, pulled low or pulled high or left floating.
WT32-ETH01 may be buggy though, there were complaints...
I've ever only used 74HCT or 74AHCT or even 74LS for that matter. 😃

**Comment by harueg** [comment]
Buggy on the hardwareside, or library ? Any other recommendation ?
For the pins I always used this : https://randomnerdtutorials.com/esp32-pinout-reference-gpios/
Is there a single chip solution from 3.3V data to 5V RS485 ? For long distance transmission.
I've used 3.3V RS485 over 12m and worked perfectly, but just to be on the safe side.
I think the ADUM1400 produces less spikes, due to the coil design.

Thanks  Harald

**Comment by harueg** [comment]
There are various olimex boards : https://www.olimex.com/Products/IoT/ESP32/
some even have SD card slots, for playing fseq files.

**Comment by blazoncek** [comment]
I use [this](https://www.tindie.com/products/twilightlord/twilightlord-esp32-ethernet-shield/) one.
And [this](https://quinled.info/quinled-esp32-ethernet/) one is also good.

**Comment by harueg** [comment]
Thanks for the hint !
Also found this, but only has 4 outputs
https://www.tindie.com/products/k7bbr/wled-wt32-ethernet-controller-and-level-shifter/

**Comment by blazoncek** [comment]
If your question is answered, please close the issue.

**Comment by BlackBird77** [comment]
I use pins GPIO 32 and 33 for APA102 Leds in Olimex Board..
