### ISSUE TITLE
Sunrise/set Times Wrong (13.0b3)

### ISSUE THREAD

**Issue by smartroad** [Aircoookie/WLED#2249]
**Describe the bug**
Sunrise/set times wrong, showing as sunrise @12:31 and set at 00:01 when it should be about 7:08am and 6:35pm

**To Reproduce**
Set time from server, time zone to GMT/BST, no utc offset (local time shows correct) Lat 51.35 Long -1.06 (not my actual location but somewhat nearby)

**Expected behaviour**
Calculate to the correct(ish) time of 7am and 6:30pm

**WLED version**
 - ESP8266 Generic, D1 clone
 - 13.0b3
 - Binary

Thank you for your help!

**Comment by blazoncek** [comment]
Fixed already. Will be available in 0.13-b4, or you can build from master.

**Comment by smartroad** [comment]
THanks, sorry to bother you :)
