### ISSUE TITLE
ESP8266 nodemcu v3 with two LED outputs

### ISSUE THREAD

**Issue by Cuacco** [Aircoookie/WLED#2253]
**Describe the bug**
esp8266 v3 looks as it reboots each 1 o 2 minutes, or power-off automatically or change first color assigned automatically.

**To Reproduce**
update esp8266 nodemcu v3 with latest version (WLED beta version 0.13.0-b3)
create 2 LED outputs 
assign Pin 1 for output 1 (master segment ), TX pin esp8266 nodemcu (as WLED wiki recommends)
assign Pin 2 for piutput 2 (second segment), D4 pin esp8266 nodemcu  (as WLED wiki recommends)
select 1 color for first color
select fade effect
select default palette
wait 1 or 2 minutes

**Expected behavior**
avoid reboots

**WLED version**
 - Board: esp8266 nodemcu v3 dev kit
 - Version: WLED beta version 0.13.0-b3
 - Format: WLED beta version 0.13.0-b3

**Additional context**
If I remove the second LED output (Pin 2 for piutput 2 (second segment), D4 pin esp8266 nodemcu ) the issue dissapears and WLED works correctly without issues.

Thank you for your help!

**Comment by bphermansson** [comment]
I can't reproduce this with v0.13.0-b4, have you tried that version?
