### ISSUE TITLE
Custom Pixel Mapping not working with Segments

### ISSUE THREAD

**Issue by Funland-James** [Aircoookie/WLED#2260]
Custom Pixel Mapping in "ledmap.json" is not recognized by segments. Instead of segments using the ledmap to set the order, segments tries to use the physical order of the pixels.

To reproduce this, convert a series of rows into columns by remapping them in "ledmap.json". This works as expected. Now try to divide up the columns under segments. The interface works as expected, but the LEDs are not grouped together in the segment as expected.

The expected behavior is that the mapped pixels can be broken up into segments (columns) that can each run their own effect.

 - Board: ESP8266/ESP32
 - Version: 0.12, build 2104020
 - Format: Binary

Fixing this bug will save me hours to days on each of my projects. It will simplify my projects greatly and others could benefit.

Thank you for your help!

**Comment by blazoncek** [comment]
Known issue in 0.12. Please update to 0.12.1 or latest beta build.
