### ISSUE TITLE
Automatic Brightness Limiter

### ISSUE THREAD

**Issue by f3rr311** [Aircoookie/WLED#2265]
Attify TrueElec ESP8266 Dev Board Using this board 

Stock image WLED version 0.12.0 ESP8266 Bin
I have 50 5v 2811 pixels connected

When I first plugin after taking off power for awhile with the auto brightness limiter on I have to use the 8266's reset button to get the 8266 to power up and boot WLED, when turned this off I can disconnect from power wait a while and plug back in with no issues 

I am willing to give as much data as I can if this is a bug or if its intended.

**Comment by f3rr311** [comment]
Update it was not the Auto brightness limiter and the issue is still there

**Comment by blazoncek** [comment]
Have you tried 0.13-b6?
