### ISSUE TITLE
DDP option missing in 0.13.0-b4

### ISSUE THREAD

**Issue by docmattman** [Aircoookie/WLED#2267]
**Describe the bug**
There used to be a `DDP` option in the Network DMX input type selector before this version.  Now it seems to be gone.

**To Reproduce**
Upgrade to version `0.13.0-b4` and it's gone from the options list

**Expected behavior**
Expect `DDP` option in the dropdown list

**WLED version**
 - Board: esp8266
 - Version build: 2110110
 - Format Binary

**Comment by blazoncek** [comment]
This is intentional.
DDP is always enabled in 0.13-b4 and up.

**Comment by docmattman** [comment]
@blazoncek , good to know.  Thanks for the info!
