### ISSUE TITLE
ESP32 goofy pin numbers

### ISSUE THREAD

**Issue by qeggs** [Aircoookie/WLED#2269]
Hello, I have my ESP32 wired up with 4 outputs. I figured out working pin numbers to enter into WLED configuration by guess & check, but the results are unexpected. This is using a freshly installed version of WLED 0.12.0 shown as "esp32 v3.3.5-1-g85c43024c" on the device.

| silkscreen marking  | ESP32 chip pin number | WLED pin number | Note |
| ------------- | ------------- | ------------- |------------- |
| TX2 | 27 GPIO 17 | 17 | this is expected
| RX2 | 25 GPIO 16 | **_2_** |  <-- this is odd
| D15 | 21 GPIO 15 | **_12 or 13_** |  <-- this is very odd
| D2 | 22 GPIO 2 | **_15_** |   <-- this is odd

This isn't a major issue since I was able to determine the correct pin numbers to enter into WLED configuration, but it may be a source of confusion for folks trying to set up multiple outputs with an ESP32.

**Comment by blazoncek** [comment]
Use manufacturers technical specifications regarding silkscreen markings and actual GPIO numbers.
Chinese manufacturers are known to misplace the markings and this has nothing to do with WLED.

WLED uses only GPIO numbers (this is also one of the changes in WLED UI in 0.13).
