### ISSUE TITLE
Adjusting white balance of individual segments.

### ISSUE THREAD

**Issue by AnthonyJQQ** [Aircoookie/WLED#2270]
![image](https://user-images.githubusercontent.com/15061501/137261049-babc7e53-10fd-4399-9d3c-f47fbdc247ec.jpeg)
I have built a backlit countertop with wled and about 7420 sk6812 warm white LEDs. 

I should have known better but I ordered all of the sk6812s from BTF lighting on Amazon. Being that I was in a hurry to get the project underway, Half of my order was for the ip-30 warm white LEDs and the other half was for the ip65 warm white version.

The LEDs were advertised as the same model with only a transparent coating on one of them being the difference. 

It turns out that the two versions are different LEDs upon closer inspection. 
![image](https://user-images.githubusercontent.com/15061501/137260915-16d925d9-b7f3-4ded-bdf6-8adc7ddfebc0.jpeg)

The problem is that I am facing is that the pure white of the ip65 LEDs is slightly cooler than the ip30 version. The variation in white balance was indistinguishable before the countertop was installed.
![image](https://user-images.githubusercontent.com/15061501/137262669-2bbf5487-c361-4aac-ac53-d43572b84265.jpeg)
I can't rebuild the led matrixes because the LEDs are under the countertop and the counter is now installed. 

I can however, add a little bit of yellow to the ip65 LEDs to make them match the ip30s on pure white. 

The solution that I think will get me out of this mess would be to have the ability to be able to set the pure white on the segments that are ip65 LEDs to an off white color such as  #ffdbb. So ideally those cooler segments would get just a bit more yellow mixed in to compensate for their cooler pure white color. 

Without going into too much detail of the build, I think that if this white balance feature could be applied to segments, it would allow me to solve the problem. It's also important to note that the white configuration on the led page is set to accurate. 

I've considered removing the countertop and replacing the off color segments but my stone installer won't do it for fear of damage.  I've also considered removing the segments from underneath the cabinets, but the amount of work that this would be is too much after all the work I took to get to this point. 

I've also considered just living with the issue but this project has been 90% successful and 100% incredible thanks to wled and it's really a travesty to have these color variations after all this work. 

I know that we can fix this via software.   For instance, I have 2 adjacent matrixes on 2 separate controllers. If I set one to pure white and the other to #ffdbbb they match up. 

Here is a photo of both set to pure white. 
![image](https://user-images.githubusercontent.com/15061501/137266187-90874eca-b1c1-491c-974b-edcbb1e2e8ad.jpeg)

And here is a photo with one set to pure white and the other set to #ffe63d. 

![image](https://user-images.githubusercontent.com/15061501/137266409-fd7349a9-ee2c-43fd-92e8-ff7deeebbf47.jpeg)

As you can see, it's possible to correct this by adjusting the cooler LEDs to match. 

Some of these miscolored LEDs are in the middle of a matrix. So segment level control is the only way that this will fix my specific issue. I think that adding this white correction adjustability in segments will also help other people who have similar white balance discrepancy issues. 

I'm excited to do a full, in-depth post on the build, but I want to get this white mismatch solved first. 

I'd like to ask people interested in full build details to hold their comments. I will post a full build post once I'm 100% finished and happy with the results. 

Thank you so much devs for this amazing project. I'm hopeful that we can get this feature implemented!

**Comment by AnthonyJQQ** [comment]
@blazoncek I have had some success with your white balance fork.  I thought you would like to have some feedback.  I was able to balance the white in the off color segments by turning off the pure white LED and using a full red white balance setting using only the RGB LEDs on those segments.  This has allowed me to have a good match of color between the segments when I want pure white light.- THANK YOU!

A few problems that I have encountered:
1.  Most effect colors appear very different between the white balanced and non-white balanced segments. The white balance correction appears to add correction to more colors than just the calculated white color. 
2. The white balance setting appears to be sent to the other synced lights when the main segment is white balanced.   

I created a white balance preset that I use when I want to make the lights white.    If I want to use effects or different colors, I have to load a different preset with no white balancing in order to make the effects match across the segments, however, when I do this, it makes the pure white not match which was my original problem.  

Let me know your thoughts!  I can send you a video if you would like to see a demonstration.

Thanks!
Anthony

**Comment by blazoncek** [comment]
White balance is applied to any selected segment (i.e. the ones with checkmark). If you want to apply white balance only to some segments unselect the others, change white balance, re-select all segments and then save preset.
Do not modify white balance after this procedure.

**Comment by blazoncek** [comment]
One more thing.
Yes, white balance WILL affect all colors (as it is supposed to).

I am starting to get the impression that _white balance_ (as in photographic terms) is not what you need but instead an channel independent gain (per segment). This unfortunately is not easy to achieve and will most likely never be implemented.

**Comment by AnthonyJQQ** [comment]
Having channel independent gain would be the fix.  I currently I have to load a preset when I want even, white light.

Here are the 2 segments both set to white #ffffff with no adjustment. 
![image](https://user-images.githubusercontent.com/15061501/140675041-9d0998e9-f9c8-4157-ae56-c0ba199f2179.png)
you can see that the warm white LEDs are on the left and the cool white are on the right.


Here is the adjustment that I make on the cool white led segments to match the warm white:
![image](https://user-images.githubusercontent.com/15061501/140674801-5976b9e2-ea7c-4248-a48c-e731fc1a0c6d.png)

The result:
![IMG_5792](https://user-images.githubusercontent.com/15061501/140675475-66e5abaf-f879-47f7-a197-1ae3bcddf56d.jpeg)

So as you can see, I can get it really close by just pulling back blue and green on the cooler white LEDs.   

My solution right now is to custom tune the cool white segments to the color of the warm white segments for each color that we like and then save that color to a preset.

For most situations, we only use the white lighting.   The difference in color temperature of the LEDs is not very noticeable when running effects anyway, so for my situation, saving presets for color matching is working.

**Comment by blazoncek** [comment]
This has been merged to master in #2285
