### ISSUE TITLE
TM1814 RGBW -> In "solid" mode, color randomly goes red for a sec

### ISSUE THREAD

**Issue by cmpGI** [Aircoookie/WLED#2271]
My build:
Wemos D1 Mini Esp8266 with LevelShifter TXS0102
To connect everything: 3way cable 0,75mm each line

Behavior:
TM1814 led strip randomly goes red for a sec, no matter what solid color I use. Multimetr show voltage around 11.30 at the end of the strip for 12v and ground, for data around 5.40V (not solid, jumping from 5.4x to 5.5x)
I tried different wled version from 0.12.0 to 0.13.0. I built 3 different boards, used different TM1814 strips which weren't longer than 5m - still the same issue.

For wled version 0.12.0 I wasn't even able to control the strip - it doesn't react for anything - is it normal behavior?

**WLED version**
 - Board: Wemos D1 Mini ESP8266
 - Version: 0.12.0 -> 0.13.0-b4
 - Format: Binary
- Led Strip: TM1814 12V

**Comment by AgentHawk** [comment]
did you solve your problem?

**Comment by cmpGI** [comment]
> did you solve your problem?

Barely but yes... had to re-soldered everything with thicker cables (between wemos - level shifter - led strip) afer that it goes stable.

**Comment by blazoncek** [comment]
TXS0102 may be too slow in some instances.
Try using 74AHCT125 or similar.

**Comment by AgentHawk** [comment]
same problem with a QuinLED DigUno V3

**Comment by cmpGI** [comment]
> TXS0102 may be too slow in some instances. Try using 74AHCT125 or similar.

I will order few of them and give a try - thanks

**Comment by blazoncek** [comment]
GPIO pins used?

**Comment by cmpGI** [comment]
>

**Comment by cmpGI** [comment]
> GPIO pins used?

GPIO 2 as data output which is connected to the level shifter
