### ISSUE TITLE
WLED_0.13.0-b4: Failed to save

### ISSUE THREAD

**Issue by dedblank** [Aircoookie/WLED#2273]
saved five presets, save five presets to playlist, 'Failed to save: not enough space', save again, playlist saved, select playlist, peek stops responding, refresh page, Sorry there was an issue loading your presets (all saved item are gone), Playlist still running in background.
ESP32 v3.2.3-14
build 2110110
signal strength -76dBm
uptime 6hr, 21min (since update)
free heap 177.2 kB
Est current 1.1A
Frames/Sec 32
Filesystem 61/61 kB

**Comment by dedblank** [comment]
Update: I have flashed two different ESP32 and both are returning 61k.  Using ESPHome-flasher recognizes the 4mb and erases it before flashing.  The info in WLED still show 61k with 13.0-b4 and even when flashing 0.12

**Comment by blazoncek** [comment]
There must be something wrong with binary, flasher, esp or any combination. FS total size shoud be 980+kB or more.
Try redownloading binary or try one of @srg74 builds.

**Comment by dedblank** [comment]
Just resolved it. There is known issue with ESPHome-Flasher where it mis-reads the block size.  Filip in Intermit.tech discord reminded me about the install.wled.me and the cleared the flash up.
