### ISSUE TITLE
How to at compile time Disable automatic brightness limiter？

### ISSUE THREAD

**Issue by zx804262156** [Aircoookie/WLED#2274]
How to at compile time Disable automatic brightness limiter？

**Comment by Aircoookie** [comment]
Add this build flag to your environment: `-D ABL_MILLIAMPS_DEFAULT=65000`

**Comment by SpeakingOfBrad** [comment]
> Add this build flag to your environment: `-D ABL_MILLIAMPS_DEFAULT=65000`

This doesn't actually uncheck the "Enable automatic brightness limiter" checkbox, right? Just sets it so high that it won't go into effect?

**Comment by Aircoookie** [comment]
True. I should add that `-D ABL_MILLIAMPS_DEFAULT=0` turns it off entirely.

**Comment by ryansabin** [comment]
Setting this flag `-D ABL_MILLIAMPS_DEFAULT=0` fails to compile.

From wled_eeprom.cpp line 271 setting milliampsPerLed to 0 disables ABL. How would I set this to 0 at compile.
strip.milliampsPerLed = 0; //disable ABL

**Comment by blazoncek** [comment]
> Setting this flag `-D ABL_MILLIAMPS_DEFAULT=0` fails to compile.
> 
> From wled_eeprom.cpp line 271 setting milliampsPerLed to 0 disables ABL. How would I set this to 0 at compile. strip.milliampsPerLed = 0; //disable ABL

It does for me.

**Comment by processor83** [comment]
it compile but when you go to led config page and press save it give error because 0 is not a correct value and the checkmark stay there. I really need top disable ABL ar compile time any solution?
