### ISSUE TITLE
Increase number of stripes from 3 to 6 for ESP8266

### ISSUE THREAD

**Issue by strama-cs** [Aircoookie/WLED#2276]
I had to light my stairs with 6 standalone strips due to relocation. Is it possible to increase the maximum number of strips from 3 to 6. There are 60 per stripe. I don't see the total number as a problem.

Thanks in advance

**Comment by blazoncek** [comment]
Use ESP32 or arrange your strip in a S (continuous) arrangement and use segments.
If you insist on more than 3 outputs for ESP8266 you can override default 3 during compile.

**Comment by blazoncek** [comment]
If using VSC + PIO add this to your platformio.ini.
`-D WLED_MAX_BUSSES=4`
Otherwise use #define.
