### ISSUE TITLE
Change AP SSID and Password

### ISSUE THREAD

**Issue by F10rian** [Aircoookie/WLED#2277]
I wannt to know if it's possible to change the access point's SSID and password in the WLED Code and if it's possible how to do it (at the moment I'm working on the version 0.12.0).

**Comment by specs32** [comment]
Hey.
I had the same question... 
In 0.13.0-b2 you can change the default AP-SSID in the file wled.cpp at line 410 .
`    strcpy_P(apSSID, PSTR("YourdesiredAPname"));
`
