### ISSUE TITLE
color shift

### ISSUE THREAD

**Issue by SirJaburaScorpio** [Aircoookie/WLED#2281]
hi there  i have a problem with wled an philips hue wenn ein change the color to blue  in the hue app  then the wled goes blue and than to turquoise  by red the same its goes pink but by green evrything ist ok were ist the problem

**WLED version**
 - Board: ESP32
 - Version 0.12.0

**Comment by xal3xhx** [comment]
Commenting here as im having this same issue on the latest version, 

board: ESP8266
Strip: ws2812b
build: 2310130

heres what i have observed

all 3 base colors (red, green, blue) will shift to a different color when being set by the hue sync
red and blue are the most obvious as green only shifts a little bit

this seams to only affect hue sync and i have not seen this with any other syncing

not sure if this will help but this is the color that was set and the color that it changed to

Red: fe0000 -> fe27fc
blue: 0000fe -> 38fdfe
green: 00fe00 -> 00fe41
