### ISSUE TITLE
ESP not reachable even when connected to wifi

### ISSUE THREAD

**Issue by embediver** [Aircoookie/WLED#2282]
**Describe the bug**
I am facing a strange problem were the ESP Stays connected to the Wifi (atleast my router is reporting that) but networking seems to be completely defunct.

The ESP-07 runs the 1Mb binary of the current release and is configured with a static IP address in my network (yes that IP isn't used by something else). WLED keeps running when the Bug occurs (the defined presets can be switched with the configured button).

At first WLED seamed to work flawless on my ESP-07, but now I face the problem that it won't be reachable with any protocol. Even a simple ping won't work.
To get it back up I have to restart the ESP. As I experienced often multiple resets are needed.

To further investigate this i did a capture of ARP packets with Wireshark:
- When the ESP powers up it connects to the Wifi
- The ESP announces its IP to the Network
- The ESP asks for some IPs (Gateway and MQTT broker)
- After that no ARP packets from the ESP are seen
- "Who has" requests asking for the ESP aren't beeing answered

**To Reproduce**
Not consistently reproducable, but resetting the ESP doesn't seem to help most of the times. 
After several resets WLED is correctly reachable again.
After a successful reset it seems to work for hours as far as I've seen.

**WLED version**
 - Board: Custom ESP-07 based board
 - Version: 0.12.0 (ESP8266_1M.bin)
 - Format: Binary

**Additional context**
Maybe this is related to #1629.

I could do some serial logging, if that would help.
What's the default Baud WLED is using and is it necessary to enable some debugging flags? 

Thank you for your help!

**Comment by blazoncek** [comment]
Build with -D WLED_DEBUG, attach serial cable and monitor output.
You will see network related data output on regular intervals.

**Comment by MG-96** [comment]
I did a build with `common.debug_flags` enabled and will comment again if the problem occurs again.

Interestingly I can't set a IR Pin in the web configuration anymore (stays at -1 all the time).
I checked out 0.12.0 from the repo and compiled the `esp01_1m_full` environment with the said debug_flags added.
Any sense why that might be?

**Comment by blazoncek** [comment]
If you want help, use latest available source. We are unable to fix old releases.
BTW I did not suggest `common.debug_flags` even though it includes WLED_DEBUG.
