### ISSUE TITLE
Binaries for APA102

### ISSUE THREAD

**Issue by pashis** [Aircoookie/WLED#229]
Would someone be nice enough to share a compiled version for APA102 leds?

Thank you

**Comment by HimbeersaftLP** [comment]
https://github.com/Aircoookie/WLED/releases

**Comment by pashis** [comment]
My APA102s just emit bright white light.  Can't seem to control anything via the app. Any hints?

**Comment by Aircoookie** [comment]
@pashis I'll send you a compiled binary once I get home. You use ESP8266, right? I don't personally use APA102, so I don't know why it could fail.

@HimbeersaftLP thank you, but the release binaries are for WS2812B only. APA102 need a recompile.

**Comment by pashis** [comment]
Great.  Yes using a nodemcu.

**Comment by Aircoookie** [comment]
@pashis Here you go: https://drive.google.com/open?id=15MDKROaJDyBirhBiLaFxUQD0hwwBJ7LL
If it works for you, I'll add it to release binaries!

**Comment by pashis** [comment]
Thanks aircookie.  I'll give it a go

**Comment by pashis** [comment]
In terms of 'LED Preferences' or any other settings, is there something I should note?

**Comment by Aircoookie** [comment]
No, just set your LED count normally and the milliamps limit to the rating of your power supply!
