### ISSUE TITLE
Support Raspberry Pi Model B, Zero, etc.

### ISSUE THREAD

**Issue by raintonr** [Aircoookie/WLED#2297]
Say one already has a Raspberry Pi Model B, Zero (or similar?) running at a location where they would like to install a LED strip...

Sure, they could install WLED on one of the supported micro-controllers and add this additional hardware at that same location, but when a Raspberry Pi Model B/Zero is capable running a web-server and driving LED strips, why not use it?

I have looked in the issues here but cannot find any reference of anyone wanting to do this & can't figure out why. C libraries to drive strips from these Raspberry Pi models exist (eg. https://github.com/jgarff/rpi_ws281x) so why not?

**Comment by Aircoookie** [comment]
There is no good reason for "why not" other that no one has made it yet, a Raspberry Pi would be more than capable to run WLED.

Many network libraries used in WLED are exclusively for ESPs, so a bottom-up approach where you would first get the core parts of WLED (I'd say FX.cpp/FX.h/FX_fcn.cpp with does all the rendering, and json.cpp to interface with the UI) ported on the Pi would likely make the most sense.
As far as I can see, Pi support would also likely mean support for most Linux environments that offer GPIO, so it would certainly be cool to have.

**Comment by raintonr** [comment]
> ... you would first get the core parts of WLED (I'd say FX.cpp/FX.h/FX_fcn.cpp with does all the rendering, and json.cpp to interface with the UI) ported on the Pi would likely make the most sense.

Funnily enough my first instinct was to mashup a command line utility using that code and the @jgarff library mentioned above ;)

But yeah, glad you are open to this support, knowing that will maybe have a go if time permits (could be a while - many projects on the go here - sorry!).

**Comment by bsmith76s** [comment]
Any updates on this?

**Comment by raintonr** [comment]
Not from me. Sorry, this isn't a high priority right now.

**Comment by champagj** [comment]
One use-case would be for magicmirror / smartmirror installation. There is a large community supporting the project www.magicmirror.builders which is based on Raspberry Pi.
Many example of mirror includes leds as a backlit which could benefit from the rich WLED development. 
I dont have the software skills to do it so for my design I will  use a Pi for the display and a 8266 for the leds and a bit of hardware interfacing.

**Comment by softhack007** [comment]
Right now this will be hard to achieve, as we have a lot of esp specific code that will not run on a PI with linux. Porting to a different architecture is not easy, see  https://github.com/Aircoookie/WLED/issues/1706 for some details. 

Do you know if an esp32 emulator is available? If yes, than maybe try to run the WLED firmware in an emulator (aka virtual machine)?

I think that the WS2812FX project is largely architecture independent, maybe you could make it run on the Rasberry Pie, instead of waiting for WLED.
https://github.com/kitesurfer1404/WS2812FX

**Comment by softhack007** [comment]
Not planned, aw it would imply a complete rewrite of espressif specific code, and a full set set of 100% compatible libraries.
