### ISSUE TITLE
我遇到的问题

### ISSUE THREAD

**Issue by mengyuxiangsui** [Aircoookie/WLED#2298]
Machine translation
I am from China, I want to translate it into Chinese, so far it has been half translated, the compilation can also run, but the console interface compilation failed, I want to know how I should compile, NPM install and NPM run build are compiled. Platformio IED compiled out of the file, run to ESP8266 01S, console interface is still not translated

**Comment by blazoncek** [comment]
The translation APIs are in the process of being developed. Unfortunately in very early stages.
