### ISSUE TITLE
"Failed updating firmware!" 0.10.2 to 0.12

### ISSUE THREAD

**Issue by dcbo** [Aircoookie/WLED#2302]
**Describe the bug**
Some times ago I flashed WLED_0.10.2_ESP8266.bin to four NodeMCU Boards.
Today I started to update to: WLED_0.12.0_ESP8266.bin
But in the OTA Update I get the following error:
"Failed updating firmware! Please check your file and retry!"
What can I do?
It's nearly impossible for me to disassamble all Lamps to reflash the NodeMCU Boards over Serial-Connection. 

**To Reproduce**
Flash WLED_0.10.2_ESP8266.bin to NodeMCU.
Goto Manual OTA Update http://[WLED-IP]/update
Select: WLED_0.12.0_ESP8266.bin
Press "Update"

**Expected behavior**
Sucessfully flashing WLED 0.12.0

**WLED version**
 - Board: NodeMCU 
 - Version 0.10.2 [2008310]
 - Format Binary, from Releases

**Comment by Aircoookie** [comment]
Hi!
This is most likely a problem with the partition layout. Do you remember which program you used to initially flash 0.10.2 via Serial?
You can try flashing 0.11.0 or 0.13.0-b4 instead, perhaps that makes a difference.
