### ISSUE TITLE
Issues changing content of Index.htm

### ISSUE THREAD

**Issue by makeroutlet** [Aircoookie/WLED#2305]
Followed this howto https://github.com/Aircoookie/WLED/wiki/Add-own-functionality

When i run npm install and npm build all changes work except for changes to index.htm. Is this something im doing wrong or does this process not update the contents of index.html anymore?

**Comment by Aircoookie** [comment]
Hey!
The index.htm is cached by default to improve performance. Before updating your changes to the ESP, make sure to increment the version code in line 11 of `wled.h` by one (or use Ctrl+F5 to hard-refresh in browser).
I hope that solves the problem :)

**Comment by makeroutlet** [comment]
so increment this number? #define VERSION 2109220

**Comment by makeroutlet** [comment]
does the increment change allow the index.htm to update through the npm install and npm build commands?

**Comment by Aircoookie** [comment]
Yes!

No, the npm build will most likely update the index.htm correctly even without it, but your browser will still have the earlier version cached. Changing `VERSION` will tell your browser that it will need to refresh the index.htm
