### ISSUE TITLE
Lost DDP in 0.13.0-b4

### ISSUE THREAD

**Issue by bcarriveau** [Aircoookie/WLED#2306]
![2021-11-01 22_36_25-Sync Settings](https://user-images.githubusercontent.com/60801063/139783013-c5aa6a18-c2a3-4036-a160-bee9fca634d0.jpg)

**Comment by blazoncek** [comment]
DDP is permanently enabled in 0.13-b4 and up.

**Comment by bcarriveau** [comment]
Right on!
