### ISSUE TITLE
Highpower LED Chip 10W 350mA

### ISSUE THREAD

**Issue by DarthWeber** [Aircoookie/WLED#2309]
Hi, is there any way to drive those high power LEDs which needs 350mA constant current with WLED ? 

**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

**Comment by Aircoookie** [comment]
Can you send a link to the LED you want to use?
Most likely you can drive it with WLED, but will need extra circuitry.

**Comment by blazoncek** [comment]
That is what I use.
You need MOSFET as IRLZ044N.

**Comment by DarthWeber** [comment]
@aircookie for example https://www.ebay.de/itm/161057358276?mkevt=1&mkcid=1&mkrid=707-53477-19255-0&campid=5338364437&customid=161057358276_12576&toolid=11000

@blazoncek Is there any circuit diagram ? Or pics ? Not sure which board i should use and how to connect the MOSFET

**Comment by DarthWeber** [comment]
@blazoncek Thanks, but i am not experienced enough to get this connected to my board - above that i expect this will be driven by PWM and since i have at least two LEDs, i do not know which board is suitable.

In the meanwhile i found [https://www.led-genial.de/Power-Dot-10W-WS2811-kompatibel](url) which seems to be pretty easy to use with the Wemos mini board.

**Comment by blazoncek** [comment]
Look for @srg74 [ESP-01](https://www.tindie.com/stores/serg74/) board on Tindie or @intermittech [QuilnLED-Quad](https://quinled.info/analog-led-dimming/#AnalogBoards) controller. They offer PWM circuitry.

**Comment by blazoncek** [comment]
![4E654553-76C4-4EF4-9115-E38DCC60A0C4](https://user-images.githubusercontent.com/7722392/142718879-1882e800-1096-4b2d-ac01-09d7891af5d1.jpeg)

**Comment by pyr0ball** [comment]
try one of these! 
https://www.aliexpress.com/item/32798198341.html

If you need something like the above, but a different form-factor, you'll need someone to design you a custom carrier.

**Comment by blazoncek** [comment]
> try one of these! https://www.aliexpress.com/item/32798198341.html
> 
> If you need something like the above, but a different form-factor, you'll need someone to design you a custom carrier.

These are digital. Mine is analog.
I guess OP wanted analog LEDs.
