### ISSUE TITLE
mqttDeviceTopic ON or OFF

### ISSUE THREAD

**Issue by martyartmann** [Aircoookie/WLED#231]
Would it be possible to set the mqttDeviceTopic ON or OFF from the app and web interface? This would make operation via home automation, app and web interface possible. And all get the respective switching state.

**Comment by Aircoookie** [comment]
Hi, when values are changed in the web interface, `[mqttDeviceTopic]/g` gets updated. `[mqttDeviceTopic]` is only for setting, the ESP doesn't publish to it by itself. 
That said, MQTT is currently being overhauled, which should get closer to what you need: https://github.com/Aircoookie/WLED/issues/207
