### ISSUE TITLE
Full Reset

### ISSUE THREAD

**Issue by Imperattor** [Aircoookie/WLED#2314]
How to do a full reset, if I changed and forgot the password in the settings and now haven't access to the control interface ?
Help, please!

**Comment by blazoncek** [comment]
Attach ESP to computer using USB cable and erase flash then re-flash WLED.

**Comment by Imperattor** [comment]
> Attach ESP to computer using USB cable and erase flash then re-flash WLED.

i know. impossible now. 
and other methode?

**Comment by blazoncek** [comment]
remember password

**Comment by poelzi** [comment]
Pressing user button 6 seconds opens AP with default password wled1234 or something like that.

**Comment by Imperattor** [comment]
> Pressing user button 6 seconds opens AP with default password wled1234 or something like that.

what the button ??

**Comment by poelzi** [comment]
There are 2 buttons on most esp boards, one reset one USR1 button. Press the USR1 button 6 seconds and look for the wled wlan. if not, your firmware was to old for that feature.

**Comment by Imperattor** [comment]
> There are 2 buttons on most esp boards, one reset one USR1 button. Press the USR1 button 6 seconds and look for the wled wlan. if not, your firmware was to old for that feature.

ESP-01 have a any button?

**Comment by blazoncek** [comment]
> ESP-01 have a any button?

I feel your pain but actually they do, if you invested in them.
You will not find a better project: [ESP01 shield](https://www.tindie.com/products/serg74/esp-01-wled-shield/)

**Comment by Imperattor** [comment]
> > ESP-01 have a any button?
> 
> I feel your pain but actually they do, if you invested in them. You will not find a better project: [ESP01 shield](https://www.tindie.com/products/serg74/esp-01-wled-shield/)

of course, but i can't physical connect to the board (((

**Comment by blazoncek** [comment]
I bet you can. Not without hassle as I can see. 😉
