### ISSUE TITLE
mDNS address changes not reflected (until true powercycle?)

### ISSUE THREAD

**Issue by jlsjonas** [Aircoookie/WLED#2319]
### What happened?

I (during initial set-up; i.e. along with connecting the device to my WIFI) set the mDNS address to `wled-1`

### To Reproduce Bug

1. download & install last release to the ESP32 (tested on a EspressIF esp32-WROOM-32d)
2. connect to WLED-AP & enter wifi credentials
3. change the mDNS address to `wled-1` (was `wled-304674`)
4. Save & Connect
5. wait for esp32 to connect to your wifi
6. try to connect to `http://wled-1.local` => NXDomain
7. try to connect to `http://wled-304674.local` (original address) => success
8. go to wifi setup, confirm that mDNS address is wled-1 (despite being served from wled-304674)

### Actual Behavior

responded on mDNS wled-304674

update: after a "true" powercycle, mDNS is now correctly using wled-1
It did _restart_ itself before though; switching from AP mode to joiining an actual network; mDNS change was done before it ever joined that network.

### Expected Behavior

Custom mDNS address to be used instead of the default-generated one

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.12.0 (build 2104020)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OlJohnny** [comment]
Working fine for me:
- WT32-ETH01
- 0.13.0-b4
- after clicking "Save & Connect" I can directly connect to the entered mDNS address (e.g http://asd123.local)
