### ISSUE TITLE
Data pin on Adafruit Feather HUZZAH ESP8266

### ISSUE THREAD

**Issue by matterdark11** [Aircoookie/WLED#2322]
Hi,

Hope you are well?

I have a noob question. I am trying to set up WLED with Adafruit Feather HUZZAH ESP8266 (https://learn.adafruit.com/assets/46249) but I am not able to figure out which pin should I use for data. Would be very much appreciated if someone could point me on the right direction.

![adafruit_products_Huzzah_ESP8266_Pinout_v1 2-1](https://user-images.githubusercontent.com/93915311/140728890-80eb2362-2445-4098-b860-0e8613d49023.png)

Thanks a lot!

**Comment by Aircoookie** [comment]
Hi,
it is best if you use pin IO2 (3rd from the bottom on the right side)

**Comment by matterdark11** [comment]
Hi,

Thank you, very much appreciate your help!
