### ISSUE TITLE
Can I use FastLED code in WLED?

### ISSUE THREAD

**Issue by matterdark11** [Aircoookie/WLED#2327]
Hi,

I have another noob question: is there a way to use amination written for FastLED with WLED? 

Thanks a million for any help.

**Comment by blazoncek** [comment]
You can. How? Not easy. 🤷‍♂️ 
WLED is based on NeoPixelBus which has a different approach than FastLED.

**Comment by matterdark11** [comment]
thank you blazoncek. Basically to me it means it is not possible :)

**Comment by blazoncek** [comment]
I think there was a work from @embedded-creations or someone else that made porting FastLED code easier.

**Comment by embedded-creations** [comment]
I have this on my out of date WLED branch:

https://github.com/embedded-creations/WLED/tree/FastLED_2D/usermods/FastLED_Compatibility

I need to merge the latest changes to WLED back into my branch, and will hopefully do that sometime after 13.0 is released
