### ISSUE TITLE
"What Binary" doesn't line up with the latest BIN file releases

### ISSUE THREAD

**Issue by chunkysteveo** [Aircoookie/WLED#2330]
Howdy AirCookie!

Great work as always. Just a note/correction that the documents for https://kno.wled.ge/basics/install-binary/#what-binary-should-i-use don't match the available binaries of the latest release - more specifically for users of 1Mb ESP8266 devices, there's new ones for 1Mb, 2Mb etc, but the documents still talk about ESP01 bin file.

Steve

**Comment by blazoncek** [comment]
Thanks for the information.
Still, you should open an issue on [WLED-docs](https://github.com/Aircoookie/WLED-docs) Github, not here.

**Comment by chunkysteveo** [comment]
Ahh is that separate? Ok - will do!
