### ISSUE TITLE
Discord link invalid

### ISSUE THREAD

**Issue by dekiesel** [Aircoookie/WLED#2331]
When trying to join the discord I am greeted with

![image](https://user-images.githubusercontent.com/17333827/141190102-54414e12-cf90-4c7c-bee2-24d5c221b058.png)

**Comment by Aircoookie** [comment]
Sorry about that!
https://discord.com/invite/KuqP7NE is still valid as checked in server settings.
You could also try https://discord.com/invite/tMGCqBE

Perhaps someone who has/had the same IP address as you has been banned. In that case, please try the link via cellular/a different networks.

**Comment by dekiesel** [comment]
That works, thank you!
