### ISSUE TITLE
Restore state on power on by polling from MQTT or Home Assistant

### ISSUE THREAD

**Issue by Hartsord** [Aircoookie/WLED#2333]
Hi! Would it be possible to have a third option for the state on power on to check MQTT and / or Home Assistant for the last state and restore that? At least you won't be flashing anything onto onboard memory, and still get "consistent" behavior.

I suggest this because I'm finding that I'm getting restarts on my D1 mini christmas lights automation where I come down to find it's stopped prematurely for some reason. I'm using 0.13.0-b4

**Comment by blazoncek** [comment]
You can always push last known configuration from home automation software since it is/should be the one controlling WLED.
You can do that after receiving WLED announce message.
If you are fiddling with WLED settings after HA configured it then it may not reflect those settings on restart.
