### ISSUE TITLE
Unable to add deleted wled node into HA integration

### ISSUE THREAD

**Issue by stefancvetkovic** [Aircoookie/WLED#2335]
### What happened?

I deleted successfull integration from HomeAssistant, and then I tried to re-add again, and then it says that device already added which is not true.

### To Reproduce Bug

1. Add host via integration tab
2. Delete particual wled node integration from HA
3. Try to add again same node to wled integration

### Expected Behavior

Should add again same node that I deleted from HA integration

### Install Method

Binary from WLED.me

### What version of WLED?

WLED beta version 0.13.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
.
```

### Anything else?

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Isn't this an issue for HA? Not WLED.
