### ISSUE TITLE
Color palette not working v0.13.0-b4

### ISSUE THREAD

**Issue by wgoldfish78** [Aircoookie/WLED#2337]
### What happened?

When I select a palette nothing's happening.  Like for example f I select C9 it just stays the same color nothing happening. 

### To Reproduce Bug

select the palette c9 effect solid 

### Expected Behavior

from what I remember I would make a pixel of each color

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_v.0.13.0-b4 ''Toki''

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not all effects use palettes.
Select an effect that uses palette.

Instead of Solid select Palette effect to display palette.

**Comment by wgoldfish78** [comment]
> Not all effects use palettes. Select an effect that uses palette.
> 
> Instead of Solid select Palette effect to display palette.

Thanks I guess that's how I did it last year
