### ISSUE TITLE
Segments Issue

### ISSUE THREAD

**Issue by KB706** [Aircoookie/WLED#2344]
Segments Issue

1st, Let me start with I LOVE this program/App. It is awesome. My neighbors love it. As do it. 

So, I am trying to test out the "Segments" portion of these program. I am using WS2811 Bullet LEDs. I have a 107 In a row that I am testing. hit "+ Add Segment". Segment #1 I have setup as LEDs 0-50. Segment #2 I have as 50-107. All works fine when the effect is "Solid" as soon as I select any other effect they begin to Flash and Bright white, while running whatever segment I have chosen. Almost as if it is a Data issue. I am running a Dig-Uno Booster Board, so in theory, it shouldn't be Data. My hope is to eventually use the segments on some LED strips in some arches I have made, but I wanted to tinker with setting them up 1st. So, I tried it on my LED's in my Screen room. Please Help. This feature would be great for what I need, but can't get it to stop doing what it's doing. At 1st, I thought it was because I was running an older version of WLED. I updated to 0.13.0-b5... Still doing the Exact same thing. No better or worse. I took a 5 second video to better display what it is doing, but the file is too large to share on here. 

### To Reproduce Bug

setup the segments and then pick ANY effect. Bam... Issue right away. 

### Expected Behavior

multiple displays(arches), smooth operation of multiple effects 

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Show your LED and segment set-up.
