### ISSUE TITLE
WS2801 builds for new versions?

### ISSUE THREAD

**Issue by OliPassey** [Aircoookie/WLED#2347]
Version 11 has a release that can support WS2801 - is it possible to get this config added to the regular build list so it appears in future releases?

I have some older boards / strings running only at christmas, xLights now supports WLED directly, but requires 12.1 or above. 
Would be great to keep these running if at all possible.

Cheers

**Comment by blazoncek** [comment]
WS2801 is still supported.
Just select it from the drop-down list.
