### ISSUE TITLE
Can you upload firmware? I can't compile

### ISSUE THREAD

**Issue by Awe7** [Aircoookie/WLED#2353]
I'm going to conclude this for the time being.

Support for the ESP32-SOLO-1 / WiZ Analog LED Strip is possible, but until this ESP32 variant is better supported in core, one must make some modifications to get it working.

![wizled](https://user-images.githubusercontent.com/86080247/132926335-98205bd7-9c0e-438a-afdd-9294d4ed4464.jpeg)

![esp32-solo-1-front-back](https://user-images.githubusercontent.com/86080247/132926010-794cd2cc-d304-4da7-8d0f-6000d6af2358.jpg)

In conclusion, the following steps are required to get WLED running on this hardware.

1.  Swap some libraries out: https://github.com/lbernstone/arduino-esp32-solo to support the single core ESP-SOLO-1
2. Add in a `delay(1)` at the end of the main loop: https://github.com/Aircoookie/WLED/blob/1d4487b6cd7c9a69bbce45c14ae1fb1c622e1d0e/wled00/wled.cpp#L121
Otherwise the ESP won't be able to multitask.
3. Attach to the ESP32-SOLO-1 RX/TX/GND pins for serial communication and Flashing.
4. Bridge IO0 to GND before booting to to being flashing process
5. Compile for ESP32 (with the aforementioned library swap)
6. Cross your fingers and Flash
7. Remove IO0 from Ground and power cycle
8. WLED should boot if successful.
9. Set LED output type to `PWM RGBWC` with pins 25, 26, 27, 4, 2
10. Set Button 0 pin to 16
11. Enjoy!

_Originally posted by @ChuckMash in https://github.com/Aircoookie/WLED/issues/2171#issuecomment-917262843_

**Comment by Aircoookie** [comment]
I don' think you meant to make this a new issue :) Your comment in #2171 will be kept.

**Comment by Awe7** [comment]
No, I can't


---Original---
From: "Christian ***@***.***&gt;
Date: Tue, Nov 23, 2021 23:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Aircoookie/WLED] Can you upload firmware? I can't compile (Issue#2353)




 
I don' think you meant to make this a new issue :) Your comment in #2171 will be kept.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
