### ISSUE TITLE
13-0-b5 can not update number of LEDs

### ISSUE THREAD

**Issue by balucanb** [Aircoookie/WLED#2354]
Understand there is a more than 50% chance this user error-Title says it all once I updated it will not let me update the # of leds. I have 511 on a Quad but it say 811? I did try to go back to a previous version and it worked as expected, then I updated again and same issue.

**Comment by Aircoookie** [comment]
The total amount of LEDs is now calculated from the busses set up below. Make sure these are set correctly, but they shouldn't have changed as you updated. If you have some overlapping busses, `511 (811 physical)` would be normal to see for the total field.

**Comment by balucanb** [comment]
Thanks. I will try again and see it this is the case.
