### ISSUE TITLE
ruban LED WS2811 + WLED + SONOFF

### ISSUE THREAD

**Issue by arnaud-aub** [Aircoookie/WLED#2355]
Bonjour, je reviens vers vous après un grand nombre de test et je ne comprends pas, WLED sur SONOFF fonctionne avec des pixels WS2811 mais pas avec un ruban led WS2811, sur le ruban, les led ne fonctionnent pas correctement pourquoi ? Merci

PS: j’ai déjà modifié tous les paramètres et rien ne change.

**Comment by arnaud-aub** [comment]
Bonjour, j'ai essayé une énième fois mais rien ne change, quelqu'un peut m'aider ?

**Comment by sansillusion** [comment]
Comment allimente-tu ton ruban. Il faut que le "ground" soit connecté entre les LED et le sonoff pas juste le signal. Le sonoff n'as pas assez de pouvoir pour allimentez le ruban, il faut donc un power supply.

**Comment by arnaud-aub** [comment]
Oui je connecte bien tout ce qu'il faut, ainsi qu'une alimentation à part, tout fonctionne avec des ws2811 en pixel mais pas en ws2811 en ruban sans changement, je ne comprends donc pas d'où vient le problème.

**Comment by arnaud-aub** [comment]
Bonjour, n'avez-vous pas d'aide à me donner ?

**Comment by sansillusion** [comment]
Peut être que le ruban est défectueux ? Vous utilisez biens le data in (le bon bout du ruban) ?
Peut être que la première del est défectueuse, j'ai déjà endommagé une bande et après avoir retiré les deux premiers DEL le reste fonctionnais bien.

**Comment by arnaud-aub** [comment]
Non, le problème ne vient pas du ruban avec un programme déjà tout fais sur Arduino tout fonctionne à la perfection, tout est correctement branché, je ne sais pas d'où vient le problème mais en tout cas ni du ruban ni de l'alimentation ni du branchement, mais merci quand même

**Comment by jzeeman01** [comment]
Arnaud
Not sure this is the same...
If you have an external power supply - I connected the wire I soldered to the GRD pin to the earth on the power supply and also only got flashing lights....try connecting the wire to the V- on the power supply and not GRD - this worked for me
