### ISSUE TITLE
Esp8266 and ws2801 any binary doesnt work for my card

### ISSUE THREAD

**Issue by insproad** [Aircoookie/WLED#2359]
I use two esp01 without any problem but when I try with my new card. Any binary doesnt show Wlep-Ap, have you any fix bin file for me, I want to use WS2801 leds
![Wemos-için-d1-nodemcu-lua-v3-ch340-ch340g-esp8266-kablosuz-internet-geliştirme-devre-kartı-modülü-32-m-flash-için-arduino-ide-i2c-spi-9815_6](https://user-images.githubusercontent.com/67734770/143501802-93b6ff22-e3af-4afa-a0d0-7a9341098376.jpg)
.

**Comment by blazoncek** [comment]
Use 4k7 pull-up on data pins. Use GPIO2 & GPIO1 for data & clock.

**Comment by insproad** [comment]
but problem not about the connection. wled ap isn' t working

**Comment by blazoncek** [comment]
Do you want help or not? Listen to what I say.

**Comment by insproad** [comment]
> Do you want help or not? Listen to what I say.

I will try that, but I want to learn. When we dont connect the leds, can we see wled ap? If we can see, that isnt make sense.

**Comment by austwhite** [comment]
Try the pull-ups as requested.  Some boards need certain pins at a the correct state to start the board.  If it doesn't work, you might have a faulty board or one that has weird compatibility issues.   
Also, try to remember none of us are paid to do this.  We try to help best we can based on what information we have, we are not able to hold hands for every scenario that comes up

**Comment by mouzg** [comment]
I have the same board and the same problems, soldered the pull-ups on tx rx as suggested but made no difference. On the other hand WLED 8.5 is working flawlessly so I'm guessing it must be something similar to [this](https://github.com/Aircoookie/WLED/issues/946)

**Comment by blazoncek** [comment]
GPIO2 and GPIO1 and GPIO0 need pull-up resistors, not GPIO3
I have found out that some ESP01S (perhaps also ESP01) boards have a very strong on-board LED resistor making it difficult to use GPIO1 for anything but button.
Try GPIO2 and GPIO3 for WS2801 LED output.

**Comment by makeroutlet** [comment]
i wouldnt say you need pull resistors.. im running ws2801 on esp8266 directly no mods and works fine
