### ISSUE TITLE
Webpage shortcuts (for, Effects, Presets) and way to hide Config button

### ISSUE THREAD

**Issue by JPElectron** [Aircoookie/WLED#2362]
When loading the IP of the module, it always starts at the "colors" page

Need URL shortcuts to go directly to Effects and Presets page for "older" or "kid" users who are "impatient"

Propose using URL "sub-folders" or "query-string" to go direct to those other pages...

http://[IP_Address]/Effects
http://[IP_Address/Presets
or
http://[IP_Address]/?load=effects
http://[IP_Address]/?load=presets

...this is useful for href links on Home Automation systems, "pin to desktop" shortcuts on Windows, "add to home screen" icons made on mobile devices - all taking you right to the effects or presets page!

Also need way to hide the config button, useful when kids are involved...

http://[IP_Address]/no-config
http://[IP_Address]/Effects/no-config
or
http://[IP_Address]/?config=false
http://[IP_Address]/?load=effects&config=false

...this could simply set a session state of config=false, so no matter which pages are hit afterwards the config menu button stays not visible for the duration of that browser session

**Comment by blazoncek** [comment]
For that purpose I have developed a _simplified_ UI available in my fork as an experimental feature.
I would be grateful if you can test it.

**Comment by softhack007** [comment]
@blazoncek simplified UI is part of official WLED now, should we close this request as implemented?

**Comment by blazoncek** [comment]
I do not think we should close it as opening particular tab is not implemented (useful on mobile).

**Comment by blazoncek** [comment]
@w00000dy could you look into this issue if you can conjour something up? 😉
