### ISSUE TITLE
Cannot Adjust Number Of LEDs on 0.13.0-b5

### ISSUE THREAD

**Issue by MonsterMuffin** [Aircoookie/WLED#2368]
I have a number of WLED instances running on Wemos D1 Minis. These were all running WLED_0.12.1-b1 and I recently went to add some more, so I updated my previous installs.

I have noticed I am no longer to change the number of LEDs in the settings page as can be seen here:

![vpn4g](https://user-images.githubusercontent.com/9695227/143864805-e4bac99e-57d6-4c16-aae5-ccfa58dd53ab.png)

I am having to flash WLED_0.12.1-b1, change this setting, then update to WLED_0.13.0-b5. When doing this, the settings so persist but it is once again locked:

![Capture](https://user-images.githubusercontent.com/9695227/143865044-04661be4-b725-4f4b-940b-226a8b04991e.PNG)

Is this expected behaviour? 

Thanks.

**Comment by fishbone-git** [comment]
it is intended.  see #2354

**Comment by MonsterMuffin** [comment]
> it is intended. see #2354

My apologies, I see this now. I was being stupid.

Thank you very much!

**Comment by Bohan-Song** [comment]
> > it is intended. see #2354
> 
> My apologies, I see this now. I was being stupid.
> 
> Thank you very much!

Sorry my English is not very good, I have the same problem led numbers can only be set to 30, why? Will the number be calculated automatically here without manual setting?

**Comment by blazoncek** [comment]
You set number of LEDs on each GPIO separately.

**Comment by Bohan-Song** [comment]
> You set number of LEDs on each GPIO separately.

What's mean, I can't understand...

**Comment by blazoncek** [comment]
Scroll down...
