### ISSUE TITLE
xlights port

### ISSUE THREAD

**Issue by cocolino83** [Aircoookie/WLED#2370]
Hello. i have a question regarding the number of doors on xlights. i installed the latest version of wled on esp 32 and i wanted to create a project with xlight i would need to use all 10 wled ports on xlights but it only detects 8, there is a reason i need to do something? thank you very much for helping
![photo_2021-11-30_10-59-59](https://user-images.githubusercontent.com/88486650/144026091-42226c73-650a-44b6-91c6-4a25407500e5.jpg)
![photo_2021-11-30_10-59-45](https://user-images.githubusercontent.com/88486650/144026120-3f108ca3-67ec-4173-8daa-d4a5bd291587.jpg)

**Comment by harueg** [comment]
Hi
Just tried, it shows 10 ports, but 2 not valid
![image](https://user-images.githubusercontent.com/60239890/145883364-b6713766-f065-4b97-9344-a537f6c5a4bb.png)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
