### ISSUE TITLE
IR recv return random values

### ISSUE THREAD

**Issue by dDaYb** [Aircoookie/WLED#2376]
### What happened?

Same IR remote button press echos different code on the serial monitor. There is no such problem in 0.12.0 vesion

### To Reproduce Bug

tsop 4838 connected to pin d2 on nodemcu v3, then press on IR remote same button with patience.

### Expected Behavior

receive same code

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
Hi, thanks for the report. Are you using any LED pin other than GPIO2/D4?

**Comment by dDaYb** [comment]
Yes, I use D6 and D4 for 2 ws2812 strips. And D0 and D3 for 2 momentary buttons.

**Comment by Aircoookie** [comment]
Ok, D6 (GPIO12) is a problem, it uses software driving, which will interfere with IR receiving. If you change that strip to use pin TX (GPIO1), IR should work :)

**Comment by dDaYb** [comment]
ok, but now I get garbage in console instead of a IR codes? And why its ok with 0.12 version, but not 0.13.0-b5?

**Comment by blazoncek** [comment]
GPIO1 is Serial output from ESP.

**Comment by dDaYb** [comment]
I guessed)) which pin should I use instead?

**Comment by blazoncek** [comment]
For LED output or IR?
LED: 1, 2, 3
IR: 12,13,14

**Comment by sn0wst0rm** [comment]
Hello, I have the same issue. I have a WS2811 strip connected to GPIO5, and IR receiver to GPIO12. Every time I press the same button I get a random code. The only right code I get is when I long press a button, getting 0xFFFFFFFF.

How can I solve this problem?
Thanks

**Comment by dDaYb** [comment]
Every time I press the same button I get a random code even if I connect
only ir diode without any leds.

вт, 7 дек. 2021 г., 21:02 Blaž Kristan ***@***.***>:
