### ISSUE TITLE
My love for Circus effect was removed

### ISSUE THREAD

**Issue by Tinkertron1972** [Aircoookie/WLED#2379]
What happen to the circus effect in the wLED app? That was my favorite effect, and now it's gone.

**Comment by Aircoookie** [comment]
The Circus effect was a duplicate and thus replaced. You can still achieve it using the effect `Tri Chase`  with Red, White and Black selected as colors :) `Tri Chase` will be called `Chase 3` in v0.13.0.

**Comment by Tinkertron1972** [comment]
Nope none of those match the Circus effect that I was uses too, and I am using the Toki version.
