### ISSUE TITLE
wifi DMX converter wf310

### ISSUE THREAD

**Issue by Imperattor** [Aircoookie/WLED#2387]
How to run DMX control via Art-Net wifi dmx converter ? e.g. WF310
please help!

**Comment by Aircoookie** [comment]
The WF310 is a wifi->DMX converter. WLED can do the same job with DMX output compiled in and a MAX485 attached to GPIO2, but it makes no practical sense to _combine_ a WF310 with a WLED instance.

**Comment by Imperattor** [comment]
> The WF310 is a wifi->DMX converter. WLED can do the same job with DMX output compiled in and a MAX485 attached to GPIO2, but it makes no practical sense to _combine_ a WF310 with a WLED instance.

Thank you. But I'm looking for some way to install and run the DMX control and don't understand how to do it ( 
Can you tell me step by step?
board ESP-01

**Comment by Imperattor** [comment]
What software do I need to do this? 
e.g. how to control the wled via resolume ?

**Comment by Imperattor** [comment]
ledfx controls wled via wifi
How can I do the same from another light control program?

**Comment by Imperattor** [comment]
I need this!
https://www.youtube.com/watch?v=Vrg2UhUGqcc&ab_channel=dBLumsolutionaudiovisuelle

**Comment by Aircoookie** [comment]
WLED can receive standard Art-Net or E1.31 data. Just select it in sync settings and enter the WLED device IP address in resolume.

**Comment by Imperattor** [comment]
> WLED can receive standard Art-Net or E1.31 data. Just select it in sync settings and enter the WLED device IP address in resolume.

Thank you! I'll be sure to try it and report back.

**Comment by Imperattor** [comment]
Can't find anything like that. 
Where i need put the IP address in resolume?
there is no such item in the in DMX tab

**Comment by Aircoookie** [comment]
No clue, sorry. All that I can help you with is that WLED can receive Art-Net data, not how to configure a sending software to output it.

**Comment by Imperattor** [comment]
> No clue, sorry. All that I can help you with is that WLED can receive Art-Net data, not how to configure a sending software to output it.

OK, I'll try to find a solution
