### ISSUE TITLE
Segments are not saved

### ISSUE THREAD

**Issue by viktor6** [Aircoookie/WLED#2389]
### What happened?

Segments are not saved

### To Reproduce Bug

I break the tape into segments
1 segment 0-75
2 segment 75-95
save and reboot

### Expected Behavior

To keep segments after restart

### Install Method

Binary from WLED.me

### What version of WLED?

Server message: WLED 0.13.0-b5 (build 2111170)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

![image](https://user-images.githubusercontent.com/10570918/144757927-b4ca9008-e2bb-4fa1-9bc5-64abdfb018c6.png)
![image](https://user-images.githubusercontent.com/10570918/144757946-7e7405d2-bf07-491b-80c5-e40cd6e62b98.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
You need to save a preset.
Not a bug.

**Comment by shampeon** [comment]
This is still a bug, actually. I originally set up my ESP32 with 50 LEDs, and then added more. The Segments only show 50. When I update the segment to 250, click Apply, and reboot, it goes back to a single segment of 50.

**Comment by shampeon** [comment]
Before:
<img width="412" alt="Screen Shot 2021-12-05 at 1 54 07 PM" src="https://user-images.githubusercontent.com/5759834/144765415-75a7de0c-d7a1-43f6-897f-0540775dc526.png">
<img width="607" alt="Screen Shot 2021-12-05 at 1 54 24 PM" src="https://user-images.githubusercontent.com/5759834/144765423-0f5f5aad-f3fb-434e-afce-d2648265b8e1.png">

After reboot:
<img width="411" alt="Screen Shot 2021-12-05 at 1 54 42 PM" src="https://user-images.githubusercontent.com/5759834/144765430-49ef7dbf-a227-4bb8-9682-6eac8323ea44.png">

**Comment by blazoncek** [comment]
Segments are saved in **PRESET** not by themselves.

**Comment by Aircoookie** [comment]
@shampeon still a feature 🙂 If you only have a single segment and plan to add more LEDs and want the preset to adjust dynamically, uncheck "Save segment bounds"

**Comment by shampeon** [comment]
Ok. Then I'd suggest moving the segment dialog under the presets to make it clear that segments are per preset in the UI. It looks like they're distinct things.

**Comment by Aircoookie** [comment]
It's already arranged that way, just left to right: Colors and palettes are part of effects which are part of segments which are part of presets. Putting everything underneath would make the UI very impractical to use.
