### ISSUE TITLE
Pixel count for RGB

### ISSUE THREAD

**Issue by 9ghost9** [Aircoookie/WLED#2394]
Copied from Led preferences 
Total LEDs: 1

RGB selection set 3 gpio and all work on Channel 1 only . I believe we need 3 leds minimum or 1 pixel .
I tested 3 outputs with  3 mosfets and all are controlled by channel #1 in WLED.

Channel #1 select red  first set  gpio lights up
Channel #1 select green second set gpio lights up
Channel #1 select blue third set gpio lights up
Channels #2 and #3 have no effect.

Esp32 and most recent WLED release .

**Comment by blazoncek** [comment]
You can assign PWM White and have each of the channels controlled individually (by any color or white slider). This set up will also let you have each of the channels act as segment.

This is as far as I understood your cryptic description. 😉

**Comment by 9ghost9** [comment]
I hope not cryptic , just a bit perplexed as to why there is 3 circles on the colors page  labeled 1 ,2 and 3 , but only 1 is assigned to 3 gpio .



As far as I can tell by testing , it is impossible to get 3 discrete channels . 
I will conclude that WLED does not provide discrete channel level control to each gpio .

**Comment by blazoncek** [comment]
Ohhh! Those are not channels but color placeholders (as paint buckets).
Some effects will use just color 1, most will use color 1 for foreground and color 2 for background, a few will use all three colors.

**Comment by 9ghost9** [comment]
All this time I have wasted trying to understand why these 3 channels are not working . Oh my gosh .

**Comment by 9ghost9** [comment]
So how does one drive the gpio independently ?

**Comment by blazoncek** [comment]
Assign each as a separate PWM White bus.

**Comment by 9ghost9** [comment]
Ok , now that I know how rgb is handled . I chose rgb x 3 which gives 9 gpio  and position the channels accordingly to the color order and all works correctly with the color wheel  . 

Thank you .

**Comment by 9ghost9** [comment]
A final note on this , using WLED as designed for rgb selection of 3 gpio works perfectly with DMX/E1.31 as discrete control . 

I should have tried this first not last .

Thanks again .
