### ISSUE TITLE
super slow effects?

### ISSUE THREAD

**Issue by jaygrovr** [Aircoookie/WLED#240]
Does anyone know how to slow down the effects to very very slow?  I have a display in my house and i want the colors to fade over minutes, is this possible?

Thanks
Jason
PS.  excellent work on this, its amazing.  I will contribute once I figure out this issue.

**Comment by Aircoookie** [comment]
Hi!

The effect aren't really supposed to run slow enough for your use case. I recommend Palette or Colorfox with a low speed though - looks amazing!

**Comment by Aircoookie** [comment]
Ah sorry, i was meaning Twinklefox! Look for them in the list of effects, pretty far down. Twinklefox is the last one.

**Comment by jaygrovr** [comment]
I still don’t see it, which effect number is it, and how would I set it for 5-10 minute color fades?
ThanksJason


Sent from Yahoo Mail for iPhone


On Wednesday, October 2, 2019, 10:56 AM, Aircoookie <notifications@github.com> wrote:


Ah sorry, i was meaning Twinklefox! Look for them in the list of effects, pretty far down. Twinklefox is the last one.

**Comment by jaygrovr** [comment]
If i dontated to your software can i get a new effect made.. super slow color fade?  Timing from 1 minute to 10 minutes transition time?
ThanksJason


Sent from Yahoo Mail for iPhone


On Thursday, October 3, 2019, 1:56 AM, Aircoookie <notifications@github.com> wrote:


Ah sorry, i was meaning Twinklefox! Look for them in the list of effects, pretty far down. Twinklefox is the last one.

**Comment by Aircoookie** [comment]
I've just made changes to the random color effect (FX=5) in latest master source :)  Set the intensity to 255 to get smooth fading between colors, 128 to fade half of the time and stay on the color the other half. Use the palette list to set the colors you'd like. Just replace line 207 in WS2812FX.cpp:
```cpp
//uint32_t cycleTime = 200 + (255 - SEGMENT.speed)*50;
uint32_t cycleTime = 60000 + (255 - SEGMENT.speed)*2352;
```
it will set the fade time selectable between 1 and 10 minutes using the speed slider!
Let me know if you need a binary!

**Comment by jaygrovr** [comment]
Thank you sir, what is the best way to contribute to your software, monetarily?
Jason


Sent from Yahoo Mail for iPhone


On Monday, October 7, 2019, 2:54 AM, Aircoookie <notifications@github.com> wrote:


I've just made changes to the random color effect (FX=5) in latest master source :) Set the intensity to 255 to get smooth fading between colors, 128 to fade half of the time and stay on the color the other half. Use the palette list to set the colors you'd like. Just replace line 207 in WS2812FX.cpp:
//uint32_t cycleTime = 200 + (255 - SEGMENT.speed)*50;
uint32_t cycleTime = 60000 + (255 - SEGMENT.speed)*2352;
it will set the fade time selectable between 1 and 10 minutes using the speed slider!
Let me know if you need a binary!

**Comment by Aircoookie** [comment]
Hi Jason,
feature requests, bug reports and pull requests are also all great ways to contribute!
If you'd like to buy me a coffee: https://paypal.me/Aircoookie

I wish you a lot of fun WLED!

**Comment by jaygrovr** [comment]
Hey there aircookie, thanks for making that change to your code for me (the super slow effect).
Wanted to know if you can maybe make another change for me.
I wanted to build some icicles and each icicle would have a certain number of pixels in them (all being the same).. Can you make an effect of dripping, and the modifier is the number of pixels per icicle (from 1-30)?
Thanks
jason
    On Sunday, October 6, 2019, 01:05:17 PM PDT, Aircoookie <notifications@github.com> wrote:  
 
 
Hi Jason,
feature requests, bug reports and pull requests are also all great ways to contribute!
If you'd like to buy me a coffee: https://paypal.me/Aircoookie

I wish you a lot of fun WLED!

**Comment by jaygrovr** [comment]
yea it worked out fine.. thank you sir
