### ISSUE TITLE
Can I use existing hardware setup?

### ISSUE THREAD

**Issue by VeniceNerd** [Aircoookie/WLED#2403]
I've been using Toblum's McLighting project in the past and would like to switch over to this project. I'm wondering it it would be possible to keep my current hardware setup and just flash the new software:

https://github.com/toblum/McLighting/wiki/Hardware

I used his setup WITH the level shifter. Here is a photo of my actual setup:
![IMG_8806](https://user-images.githubusercontent.com/25128243/145470616-72966d2e-1314-41aa-b32e-63c208f8f791.jpg)

Could I just flash a new ESP8266 and then replace the old one with the new one? I have set this up many many years ago and would love not having to go through the headache of figuring out the hardware side of it all again. ;)

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord (link on front page) for help and support questions.
Closing.
