### ISSUE TITLE
Is there a way to "export the effect"

### ISSUE THREAD

**Issue by nardev** [Aircoookie/WLED#2404]
I couldn't find a question which would help.

I se many of the effects in the WLED but i don't want to extend or use it in my code. I have other functionalities to inplement.

So, is there a way to "export" the effect in some kind of array/matrix/header file, which i can call/pass to a function and get the effect on the stip/display, what ever?

thnx, the project is amazing.

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord (link on front page) for help and support questions.
Closing.
