### ISSUE TITLE
Manual OTA Update Page Display Environment information

### ISSUE THREAD

**Issue by jgvary** [Aircoookie/WLED#2405]
When updating multiple ESP8266 and ESP32 OTA, knowing the device type on the Info page (/?) Environment on the WLED Software Update Page (/update).  This would make it much easier to update the devices with the correct version.

Example

WLED Software Update
Installed version: 0.13.0-b6 
Environment: esp82662_7_4_7(1)
Download the latest binary: 
No file chosen

Or

WLED Software Update
Installed version: 0.13.0-b5
Environment: esp32 v3.2.3-14-gd3e562907 (0)
Download the latest binary: 
No file chosen

Thank you in advance

**Comment by softhack007** [comment]
Availeable in WLED 0.14.0-b1
