### ISSUE TITLE
Going out of sync after a while

### ISSUE THREAD

**Issue by fribse** [Aircoookie/WLED#2411]
### What happened?

I have three WLED controlled lights.
All running 0.12, using udp port for sync
1) esp8266 send and receive sync (star)
2) esp32    send and receive sync (facade)
3) esp8266 receive sync (candles)

I'm running a standard colorloop effect.
If I manipulate 1) or 2) they sync up, but after a while they are a tiny bit out of sync, and this worsens over time.
They are all timesynced to a local timesource (Home Assistant, chrony addon).

### To Reproduce Bug

Set up colorloop and sync between several instances, and over time they drift.

### Expected Behavior

They shouldn't drift, but keep synced

### Install Method

Binary from WLED.me

### What version of WLED?

0.12

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Anything else?

![image](https://user-images.githubusercontent.com/13660621/145691740-76c5a363-2149-4021-bcee-36cb60298e80.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use 0.13-b4 or newer and use virtual buses (network DDP). Even regular sync is handled better in 0.13
The problem of time drift (and hence effects) is due to lack of RTC on ESP chips.

**Comment by fribse** [comment]
Hi @blazoncek 
You have to enlighten me on this one, I have no idea what you are talking about 🤣 
I've updated to 0.13-b4, and I can find the word DDP in the docs, but it is only mentioned, not explained.
This morning the esp32 was out of whack with the esp8266's.
My current settings after the update is this:
![image](https://user-images.githubusercontent.com/13660621/145704777-de948be3-489f-4ef9-859b-46e40955f169.png)

**Comment by blazoncek** [comment]
Use LED settings and select network type.
Please use [WLED docs](https://wled.discourse.group) or Discord for help and support questions.
