### ISSUE TITLE
I dont know wath the Problem is 

### ISSUE THREAD

**Issue by MagdicsAron** [Aircoookie/WLED#2412]
I have a esp8266 with irfz44n Transistors becose i want to use a 12v led strip, i wired up correctly and it is still not working coud you help me? 
![1639297817195312534586650200598](https://user-images.githubusercontent.com/95531532/145705707-42897679-ff72-489a-8481-085ba0b382f9.jpg)
![1639297867342329729271188690042](https://user-images.githubusercontent.com/95531532/145705717-aafbddb2-5e61-4d1f-bc3a-c2eaa924b42f.jpg)

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
