### ISSUE TITLE
TM1814 red flashing

### ISSUE THREAD

**Issue by AgentHawk** [Aircoookie/WLED#2418]
Hey

im using the new beta version of WLED. And the stripes run with it - but every few seconds i got a red flash.

Running in Solid mode - with the quinLED Uno. 

Greetings

(TM1814 DC24V RGBW)

--------------------------------------
Edit:

Always after 1:30 minutes after the last command, the stripe briefly flashes red

Edit2:

tiny Workaround - Effect Colorloop with Color1 (static) fixed the issue. So I think its a problem with the sync rate in Solid and off mode?

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
See #658
Closing.
