### ISSUE TITLE
Longitude entry problem

### ISSUE THREAD

**Issue by n1iic** [Aircoookie/WLED#2424]
Greetings everyone. When trying to enter my longitude, I was unable to select a negative value for the West. The android entry screen of only numbers did not have a minus symbol available, and the only optionon on the time page was for an Eastern location.
I wish I could contribute to the coding for this, since it's such a great project, but I will only be able to offer these little details for the problem that I found.

Thanks

Jason

**Comment by n1iic** [comment]
Greetings everyone. When trying to enter my longitude, I was unable to select a negative value for the West. The android entry screen  of only number did not have a minus symbol available, and the only option was for an Eastern location available on the time page.
I wish I could contribute to the coding for this, since it's such a great project, but I will only be able to offer these little details for the problem that I found.

Thanks 

Jason

**Comment by n1iic** [comment]
One idea is to compute the +/- setting from the user selected time zone

**Comment by blazoncek** [comment]
This is a shortcoming of the Android device (web view implementation).
Try updating your Android to a newer version or use computer to enter LAT/LON.

**Comment by blazoncek** [comment]
> One idea is to compute the +/- setting from the user selected time zone

How to do that for southern hemisphere? They have the same problem with LAT.

Nevertheless I will think of something, though it is low on priority list.

**Comment by Aircoookie** [comment]
Could instead of negative entry do radio buttons for N/S and W/E.

As a workaround, use Gboard or another 3rd party keyboard. The person at Samsung who made that keyboard unable to enter negative numbers was about as smart as the one who made the specification for log4j.

**Comment by blazoncek** [comment]
> Could instead of negative entry do radio buttons for N/S and W/E.

Was my thought as well.

**Comment by n1iic** [comment]
I copied the dash from a text field using the full keyboard.

Samsung is the problem. Software on mainstream devices can be a pain, that's for sure. It worked fine on my Blackvue phone.

**Comment by blazoncek** [comment]
check commit https://github.com/Aircoookie/WLED/commit/2c1418105154457c658d1f01fa9c329561567cee
![Screenshot 2021-12-23 at 20 17 33](https://user-images.githubusercontent.com/7722392/147284829-82a829bc-783e-4883-86a5-4c6ab8a50aaa.png)

**Comment by n1iic** [comment]
That is great! Nice work, and thank you again.
