### ISSUE TITLE
Audio Client

### ISSUE THREAD

**Issue by FreshImmuc** [Aircoookie/WLED#2436]
Add audio reactive modes. I know there are already some github forks with audio reactive stuff but they either don't work or just work with a microphone wich is dumb.

Add a feature to "record" or "share the screen/window" with the web-interface chrome-tab on pc and make the music you shared appear as effects on the LED strip.

Something like tap on an effect that is audio reactive, it prompts you to share your spotify window or youtube window and then takes the audio from that shared window and sends it to the chip.

You can also make an Audio Client for windows. Something like a exe file that promts you to put in the ip and then just sends all desktop audio to the chip. But the website soltuion would be way easier at my opinion

I also saw that you already made a Repository named "[Audio Reactive LED Strip](https://github.com/Aircoookie/audio-reactive-led-strip)" but this has to be installed as a new firmware so its not useable with WLED and Desktop Audio. Maybe take some stuff from that and paste it in this Project and make it compatible.

**Comment by Stektax** [comment]
This would be AMAZING to have omg

**Comment by FreshImmuc** [comment]
Ok so I just found LedFx. THIS IS SO AMAZING. THIS COMBINATION IS SO GREAT

Thank you for making this, this is so great
