### ISSUE TITLE
ColorTwinkles always fade to red

### ISSUE THREAD

**Issue by Vacant0mens** [Aircoookie/WLED#2437]
I know this is kind of a picky request, but I noticed when running the Color Twinkle effect, when each led fades out, it almost always ends up red just before it turns off.

Functionally, it seems like it's using static values when it decreases the brightness of each R, G, or B. Would it be possible to dim them by a percentage instead? My theory is that the color would then remain consistent as it dims out.

Looks like the effect itself is a pretty short piece of code, but I don't know enough about C++ to feel confident making any changes. For someone who does, (correct me if I'm wrong) this seems like a pretty easy request to fill. Also, if I'm wrong about the percentage being the fix for this, please let me know.

**Comment by Aircoookie** [comment]
All color channels are scaled equally, at low brightness values the color will converge towards the closest primary color (Orange for example with channel values 255,160,0 will fade down to 2,1,0, then 1,0,0).
Personally I like the current effect as it mimics the behavior of incandescent bulbs, which also redden at a lower brightness.
