### ISSUE TITLE
Thermaltake ARGB fan w/ ESP3266: Bug? Request?

### ISSUE THREAD

**Issue by ja518** [Aircoookie/WLED#2439]
Hello all,

First of all: THANK YOU for the fantastic job!

Now to the point: I'm trying to use WLED with the boards I have at hand (Nodemcu Amiga and Wemos D1 Mini, both of them ESP8266-based clones) to control one of my son's PC fans, that happens to be a Thermaltake ARGB 120mm fan. The led strip on the fan has 15 WS-8215 addressable LEDs, and an onboard controller to generate a basic sequence when there's no signal on the data pin.

I'm currently debugging this thing using a bench power supply for the 12V, and powering the board(s) through the USB port. The fan has an onboard step-down converter to provide power to the LED strip, so the USB port is taking very little power. 

I tried both ESP8266 boards using the WLED_0.13.0-b6_ESP8266 binary, and with both I had the same issues when using D4/GPIO2:
- the board wouldn't boot when the fan's data pin was connected - even after adding a 4.7K pull-up resistor to 3.3V as described on other threads. If I connected the data pin after the board had booted, everything would be Ok (or almost Ok).
- the "solid" pattern doesn't work. All I get is some seemingly random blinking.

After spending some time and doing some tests, I found using a different pin solves the 1st issue. I'm currently using pin D5/GPIO14, with a pull-up to the 3.3V, and the board is booting correctly when powered up or reset using the onboard button.

I still have the 2nd issue, though: I can't get the "Solid" pattern to work.
From previous testing using an Arduino, I know the built-in controller acts up/misbehaves if it doesn't receive a signal on the data pin for more than ~250ms, but I have not been able to find out what's the update frequency for WLED running on these ESP8266, so this may or may not be the issue. If that IS the issue, though, I need some help modifying the code to increase the refresh rate.

I can get the LED to hold a solid color at full intensity by selecting patterns that transition the LEDs between two colors, and using the same color for the two (or 3) "target" colors. I assume this is because WLED is updating multiple times to go from color "A" to color "B" (where color B happens to be exactly the same as A), so I *think* it should be possible to get the data signal to refresh more often.

The question is: how do I do so?

Thanks!
[Edit] On the video below, WLED was set to a "solid" red pattern :D

https://user-images.githubusercontent.com/77372614/147044516-ed29a845-51eb-4f29-a0a8-ec4924caaeb9.mp4

**Comment by blazoncek** [comment]
WS2815 is a 12V LED chip and my require level shifter (data signal boost) from MCU to LED.
D4 (GPIO2) may on some occasions need pull-up resistor (10k but you can try as low as 4k7).
And please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
