### ISSUE TITLE
Fixed number of leds on ESP-01

### ISSUE THREAD

**Issue by Natal-CWB** [Aircoookie/WLED#2441]
### What happened?

I can't change the number of LEDs. On this new version the quantity of Leds are fixed at 30.
Before I was using version 0.12 and it was possible to select the amount of leds.
![WLED](https://user-images.githubusercontent.com/58017591/147299367-ee4929cb-0551-4dd1-a6e3-7b7091f00c80.JPG)

### To Reproduce Bug

Install WLED_0.13.0-b6_ESP01.bin on any ESP-01 and look at LED Preferences

### Expected Behavior

enter the number of leds

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.13.0-b6_ESP01

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Natal-CWB** [comment]
I also tried it with 0.13b5 and 0.13b4 and both didn't work, only 0.13b3 worked.

**Comment by blazoncek** [comment]
You should have read release notes.
The field is no longer required. You change number of LED in the bus/strip data.
