### ISSUE TITLE
Transition with Colour not working from Home Assistant

### ISSUE THREAD

**Issue by Morphy99** [Aircoookie/WLED#2442]
### What happened?

When sending light.turn_on with a different rgb_color and a longer transition time than the WLED default, and the colour has been changed in WLED GUI, the first command uses the WLED specified transition time and not the one sent from the HA integration. Subsequent commands with transition to other colours seem to work correctly with the specified HA transition time.

Tested with transition off in WLED settings. Interestingly, adding brightness to it does seem to correctly transition that over the specified amount of time but colour still changes at the WLED default.

Using WLED v0.12 and HA 2021.10.7

EDIT: After trying this in a script, it does seem to work after the first light.turn_on is issued. The first one still does not transition though.

EDIT2: Edited first paragraph to explain a bit more precisely the behaviour.

### To Reproduce Bug
Set WLED instance to a random rgb_color from the GUI that's not [255,255,255]

Send this in HA dev tools:
```
service: light.turn_on
target:
  device_id: 1801e557652a4728b36641238515a00b
data:
  transition: 60
  rgb_color:
    - 255
    - 255
    - 255
```
The result uses the set transition time in WLED not the specified.

### Expected Behavior

Colour would transition over the specified time, first time around.

### Install Method

Binary from WLED.me

### What version of WLED?

v0.13b6

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use 0.13-b6 and report back. We are unable to fix older releases.

**Comment by Morphy99** [comment]
Thanks but still the same with 0.13-b6

I've updated the post with a better explanation (I hope!) and the version tested.

**Comment by blazoncek** [comment]
use "tt" instead of "transition" in JSON

**Comment by Morphy99** [comment]
> use "tt" instead of "transition" in JSON

Thanks. I'm not sure how to implement your suggestion though as I'm not very experienced in using json. Can I send this from HA? I've had a look in the wiki to send via curl which I can try if that's what you want me to do?

I've got as far as this but I'm not sure what I'm doing with the segment part?

`curl -X POST "http://xxx.xxx.xxx.xxx/json/state" -d '{"on":"t","v":true,"transition":"20"}' ""seg":[{"single":{"0": [255,0,0],"20":[255,0,0]}}]" -H "Content-Type: application/json"`

I'm guessing there may be an issue with my formatting as I'm getting:

```
curl: (3) bad range specification in URL position 6:
seg:[{single:{0: [255,0,0],20:[255,0,0]}}]
```

I have 20 LED's in this case and changing to Red over 20s.

**Comment by blazoncek** [comment]
Use `curl -X POST "http://xxx.xxx.xxx.xxx/json/state" -d '{"on":"t","tt":"20"}'  -H "Content-Type: application/json"`

Include "v" only if you need complete state as a result.

**Comment by Aircoookie** [comment]
Hmm to really gauge if this is an HA or WLED issue, we would need to know the exact JSON command(s) sent to WLED by the integration using your dev tools command above.

Before sending the HA command, was the light on or off? If off before, there should be no color transition at all, only the brightness transition.

The difference between `transition` and `tt` is just that `tt` applies only to the current request. `transition` should also always work, so there likely is an edge-case bug with color transitions somewhere.

**Comment by wildman199** [comment]
I’m also having this problem with Hoobs and Homekit.

**Comment by blazoncek** [comment]
Transitions have been completely reworked in 0.14.
