### ISSUE TITLE
3d effects

### ISSUE THREAD

**Issue by emmexx** [Aircoookie/WLED#2449]
I was curious if it would be possible to create easily 3d effects with WLED.
I watched Matt Parker videos on Youtube ([My 500-LED xmas tree got into Harvard](https://www.youtube.com/watch?v=WuMRJf6B5Q4)) and wondered if it would be easy to add a 3d configuration to WLED and some effects that use the position in space of the leds.

Thank you 
  maxx

**Comment by blazoncek** [comment]
Not yet. Not even 2D.

**Comment by emmexx** [comment]
I made the request the wrong way.
I wasn't asking

**Comment by blazoncek** [comment]
https://github.com/Aircoookie/WLED/issues/2420
