### ISSUE TITLE
Documentation should elaborate on the button's purpose

### ISSUE THREAD

**Issue by hmeine** [Aircoookie/WLED#2451]
### What happened?

I was reading the getting started documentation at https://kno.wled.ge/basics/getting-started/ and read "Optionally connect a normally open pushbutton to GPIO0 (NodeMCU/Wemos pin D3, on ESP32 use IO17) and ground.", but could not find any more information on the button's purpose.

### To Reproduce Bug

Just look at the documentation; this bug report is not about WLED itself.

### Expected Behavior

The documentation should give enough information to make an educated decision on whether to mount this optional button or not. (I asked in Discord and heard that it can be used to control effects etc., so that sounds quite useful.) Ideally, there should be a link to an according section in the user manual.

### Install Method

Binary from WLED.me

### What version of WLED?

n/a

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Whatever purpose you want. 😄  Default is on/off but you can assign any preset to it.

Second, [WLED-docs](https://github.com/Aircoookie/WLED-Docs) is a separate repo and you are welcome to fill the void...
