### ISSUE TITLE
Newbee..how to custom program ?

### ISSUE THREAD

**Issue by bnilesh21** [Aircoookie/WLED#2453]
I am willing to custom program for my project but overwhelmed seeing advanced kind of programming. 

I am having 60 LED's in a strip. Can anybody help me to know which instructions can I use to for following 
1. ON/OFF a LED in strip  ?
2. Change color of a LED to custom color?
3. Change & set brightness of a LED ?
4. I will like to basic test in V1 usermod.cpp first. how this mode I can see in WLED app?

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
