### ISSUE TITLE
Use with 5050 non-adressable rgb led strip, with voice sensor

### ISSUE THREAD

**Issue by insproad** [Aircoookie/WLED#2455]
Hi again, I want to use wled with 5050 rgb led strip. Can you help me for that, and I just wanna add one voice sensor. For, when I make clap led will be white. Can we do that?

**Comment by insproad** [comment]
Hi again, I want to use wled with 5050 rgb led strip. Can you help me for that, and I just wanna add one voice sensor. For, when I make clap led will be white. Can we do that?

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
