### ISSUE TITLE
WLED-AP password

### ISSUE THREAD

**Issue by DOUGAL6666** [Aircoookie/WLED#2459]
This is going to sound really stupid but I've flashed a ESP8266. It's powered, LEDs are lit and the WLED-AP is available but  I can't for the life of me find the network security key to finish config and connecting to my AP.

I am sure I am missing something really obvious but please help :)

**Comment by LightMaster001** [comment]
There is a wiki linked, and on the Getting-Started-Page you can find the password.
https://kno.wled.ge/basics/getting-started/
default password: wled1234
Have a nice day!

**Comment by DOUGAL6666** [comment]
thank you so much. Like I said, STUPID question!!
