### ISSUE TITLE
Could use some help

### ISSUE THREAD

**Issue by wou5er** [Aircoookie/WLED#2461]
After flashing HyperSerialEsp8266.ino.d1_mini_WS8201_rbg_FIRSTLED_ENABLED.bin, connected to RPI4 made the changes in Hardware setup. 
But my leds only have static white.
Using a Wemos D1 mini
with WS2801 LEDS

What i'm doing wrong or i over see?

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
