### ISSUE TITLE
Manage color ordering by LED offset, rather than GPIO.

### ISSUE THREAD

**Issue by justfalter** [Aircoookie/WLED#2462]
**Is your feature request related to a problem? Please describe.**
Yes. 
I have 1200 LEDs spread over 5 GPIOs. On two of the GPIOs, I have a mix of LED strings with RGB and BRG color ordering.  In both cases, I want them to apply color and effects to them as a single segment, but the colors are always wrong on one of the strings because the color order config is tied to the GPIO. 

**Describe the solution you'd like**
I want to be able to set LED color order based on LED offset, rather than by GPIO, and I want to do this multiple times throughout my 1200 LEDs. This is similar to what can be done in xLights, where you can specify color ordering on a per-model (string) basis. 

- Remove the `Color Order` option from `LED outputs`
- Add a new section to `LED Settings` for specifying color ordering. 
  - Drop-down for choosing the default color order (ex: RGB)
  - Similar to segment management, allow addition of color order overrides for LED ranges (start, length, color order). 

**Describe alternatives you've considered**
* Moving one of the strings to a separate GPIO is not always possible. In my case, there is 30 feet between the esp32 and the first string. If I moved the second string to a separate GPIO, it'd mean I'd have to run a 40 foot cable, which would be pushing it for range, as well as wasteful.

* Per-segment color ordering (#1428) is not viable as I want the two strings on a GPIO with different color ordering to operate as a single segment, not separately.
* Additional reasons why per-segment color ordering is no good:
  * It feels like the wrong place. Segments are for effects/presets, not for lower-level color order mapping. Some presets might have 10 segments, while others will have just one.
  * Managing segments across multiple presets can be tedious.  

* Using the [`COLOR_ORDER_OVERRIDE`](https://github.com/Aircoookie/WLED/blob/17d2fb80f2c053ff923187d4ab57898068511ade/wled00/bus_wrapper.h#L386-L389) define is not viable, as I want to override the color order in multiple places.
  * Color order can only be overridden for a single range (between `COO_MIN` and `COO_MAX`).

**Additional context**

Current approach I'm using (and unhappy with) requires me to define separate segments, and manually remapping the color palette from RGB to BRG for the strings of LEDs that have the different color ordering. This is very frustrating as any changes to the palette requires me to remap colors on the individual segments, which is very tedious. 

I went so far as to implement per-segment color ordering, but quickly found that it was not in the right direction. Segment configurations do not survive power cycles, unless they've been saved to a preset. And, again, managing segments across many presets is tedious.

**Comment by blazoncek** [comment]
Custom compile with:
-DCOLOR_ORDER_OVERRIDE
-D COO_MIN=<start_pixel>
-D COO_MAX=<end_pixel>
-D COO_ORDER=<color_order>

**Comment by justfalter** [comment]
> Custom compile with:
> -DCOLOR_ORDER_OVERRIDE
> -D COO_MIN=<start_pixel>
> -D COO_MAX=<end_pixel>
> -D COO_ORDER=<color_order>

I should have provided a bit more detail, but I actually need to override the color order for _multiple_ ranges of LEDs, not just one. I'll update my original message.

**Comment by blazoncek** [comment]
For your requirements (a very unusual) you'll need to modify bus_wrapper.h and ajust COO in such a way to be compatible with your strips.
Use COLOR_ORDER_OVERRIDE aas a guide.

**Comment by Aircoookie** [comment]
@embedded-creations perhaps this should become part of `Mapping`, though I'm not sure how much additional overhead it would incur.

**Comment by embedded-creations** [comment]
@Aircoookie this seems like a hardware issue,  and an ideal software fix would be to allow each bus to alternate between different LED color orders (or even different types of LEDs, e.g. RGB and RGBW).  That seems like a lot of work for a very rare case and I don't think it should be a high priority.

I don't think Mapping is the right place to fix it, but it would be possible to hack in a fix with a custom Mapping class without modifying the core of WLED, but it would still require custom compiling WLED to add the class in a Usermod.  I don't think swapping colors should be a standard feature of Mapping.

**Comment by justfalter** [comment]
FWIW, I'm currently working on a set of changes that attempts to address this issue in the manner that I proposed. I'm in the middle of something at the moment, but I'll push a branch up before I get too deep into the weeds on the configuration/html/js side of things so that folks can take a look.

Thus far, the modifications sit within the core of WLED, the changes sitting in/behind `BusManager`.

**Comment by justfalter** [comment]
As mentioned, here's my WIP branch for the color order modifications I've got, so far: https://github.com/Aircoookie/WLED/pull/2463
