### ISSUE TITLE
[QUESTION] Parallel LED order settings

### ISSUE THREAD

**Issue by sauer-m** [Aircoookie/WLED#2464]
Hi,

didt find a real answer in the threads.

Is it possible to set up parallel stripes with one data line to act like one linear segment like in the pictures below?
(So, for better understanding - a running light from 1 to 80 in target image would start and run simultaneously on LEDs 30/31, 29/32, 28/33, ...).

Also I thought I could address a part of a stripe (e.g. LEDs 80-100) as separate segment (so I could light them up individually).

![led_panel_actual](https://user-images.githubusercontent.com/16384794/147852825-aa6fa332-ea2b-40d0-bc78-d9ff2c5f4220.png)
![led_panel_target](https://user-images.githubusercontent.com/16384794/147852876-99c24d79-9490-4701-adc3-47a430e9ceaf.png)

As for using a plain ESP8266, I would prefer to not split the 3.3V Signal for parallel addressing and/or using a level-converter (due to circuit size) 😬

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.

**Comment by sauer-m** [comment]
> As for using a plain ESP8266, I would prefer to not split the 3.3V Signal for parallel addressing and/or using a level-converter (due to circuit size) 😬

Oh, sorry 😌 
I created a [thread](https://wled.discourse.group/t/settings-for-parallel-u-shaped-led-stripe/4573) in the forum, thanks :)
