### ISSUE TITLE
the sp32 can run up to 10output on the esp 32 if im not wrong or atleast more than five but why when i add more output up to 5 it limits only 5 and says pin"6 7,8,9,10,11" cant be used

### ISSUE THREAD

**Issue by Capboyxd** [Aircoookie/WLED#2466]
![Screenshot_20220103-182740.jpg](https://user-images.githubusercontent.com/77866889/147925666-18b44f13-f94d-4efe-85e8-a6bc781fa1e4.jpg)

**Comment by blazoncek** [comment]
Have you read any specifications on ESP32?
If not, you should.

GPIOs 6-11 are reserved GPIO pins, used for flash memory.

**Comment by Capboyxd** [comment]
oh but then is it possible for me to add more than 5outputs then

**Comment by Aircoookie** [comment]
Use GPIO pins 12 and above.
