### ISSUE TITLE
Magic Home LED SPI Controller 

### ISSUE THREAD

**Issue by salopette** [Aircoookie/WLED#2468]
Hallo, ich habe ein SPI Controller, kann man hier die WLED FW installieren?

https://deu.grandado.com/products/dc-5v-12v-24v-led-spi-controller-ws2811-ws2812b-address-pixel-mini-wifi-controller-magie-hause-app-telefon-control-dimmer-5050?variant=UHJvZHVjdFZhcmlhbnQ6NjU2NDY0NQ&gclid=Cj0KCQiA2sqOBhCGARIsAPuPK0jt9mvKbRmVtpv4B2cIrbY3myekVow-bP6KRLEXnPIbMNxfbP0GmNAaAonPEALw_wcB

https://githubmate.com/repo/atuline/WLED/issues/74

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
