### ISSUE TITLE
all LED turning green after various time

### ISSUE THREAD

**Issue by smarthomenewbee81** [Aircoookie/WLED#2470]
### What happened?

An effect is running for e.g. 40 minutes (time is very various) and then all LED turn green

### To Reproduce Bug

Turn on WLED, choose any effect und brightness and wait

### Expected Behavior

The choosen effect should be stable at work

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.0-b6 (build 2112080) and also WLED 0.13.0-b5 (build 2111170)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Most likely a HW issue (noise on data line or bad connection/pixel).
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support issues.
Closing.
