### ISSUE TITLE
Misplaced QR codes

### ISSUE THREAD

**Issue by NathanielCob** [Aircoookie/WLED#2471]
Hello. A few months back, I purchased two strips of Comet LEDs. I recently finished remodeling my office and hung up the lights only to discover that I no longer had the papers with the QR codes on them. Is there any way that I can still connect the LED lights to the WLED app? Or are the lights deemed useless now? Thank you!

**Comment by Aircoookie** [comment]
Hi! Please use Discord or the forum for support questions next time :)
If the product you purchased has an USB port, I would recommend re-installing WLED, the new web installer at https://install.wled.me/v2.htm will allow you to connect it to your network without any QR code. Afterwards, you can simply discover them using the app.
