### ISSUE TITLE
analog potneiometer changes Segment 0 brightness instead of Global brightness

### ISSUE THREAD

**Issue by jkatton** [Aircoookie/WLED#2479]
### What happened?

when a potentiometer is hooked up to A0 to control brightness, the value for Segment 0 brightness is modified, instead of global brightness.  

![image](https://user-images.githubusercontent.com/7003534/148707925-732dd60c-15b1-4212-91c6-a0be0c4f0f61.png)

### To Reproduce Bug

 hook analog potentiometer to wled, go nuts on the slider, wheeeee!

### Expected Behavior

I would expect the analog input should control global brightness, so that it functions if segments are being used.  Currently if any segments are being used, the analog input is ignored.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.0-b6 (build 2112080)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

Thanks for all your hard work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
https://kno.wled.ge/features/macros/#analog-button

**Comment by jkatton** [comment]
Thank you very much for your quick reply, that solves my issue completely,
in a really comprehensive way.  Sorry that I didn't see that option earlier.

Thanks again for all your hard work, I really appreciate it.

-  Jesse.
