### ISSUE TITLE
Stability: What's the safest way to set up WLED with Esp ?

### ISSUE THREAD

**Issue by NessLange** [Aircoookie/WLED#2482]
### What I have done so far: 

- Flashing WLED to an Esp8266/ Esp32
- connecting to my home Wifi 
- setting up a naive circuit in order to control a strip (mainly for Ambilight)

Here is the circuit: 
![frstSetupWLED1 2](https://user-images.githubusercontent.com/96953655/148940837-a7a2ddae-a790-4763-b87a-068f55c0ac32.png)

### What I have been ending up with:

- smooth system that can control LED'S wirelessly via Web interface for the first couple of times
- after some power cycles not corresponding controller, even not connecting to my Mac anymore 

So that's the main point I want to fix: **how to build a reliable controller, that runs after power cut?** 

### What kind of problems I (a novice) consider:

- micro-USB-cable sends corrupted data albeit flashing worked nicely
- power-supply has voltage drops leaving any wrinkles on the microchip 
- while assembling,  pins were wrongly connected (e.g. 3.3 V-pin to 5 V!)
- physical damage was applied by pushing to hard into a board
- not any protections were implemented (capacitor, resistors)
- Data pin was not "pulled high" while powere leaving the Esp unresponsive 
- logic level shifting was ignored -  although it shouldn't damage the Esp

### What I am planing to do now:

- in order to spare many more Esp-modules I want to construct a safe circuit, working reliably 

Here is what I'm having in mind:  
![2ndSetupWLED2](https://user-images.githubusercontent.com/96953655/148965600-0a1ea447-50f9-43fe-aabe-28c5425ae6ab.png)

### What my primary improvements are (in theory): 

- connecting GPIO0 (D3) to 3.3 V output of the Esp: this should "pull" the pin "high", enabling booting 
- choosing another pin for Data output (D5) and putting a resistor in between (just to be safe)
- Level shifter and capacitor: just optional, I don't think they are related to the booting of the Esp

### What are your thoughts and setups for wiring an Esp?

- assuming cables and power supply are alright, do you think my diagram holds, compared to yours? 
- do you believe it's feasible at all or do you suggest a premade controller (If possible shipped to Germany)?

I'd be glad if you were to answer some of my numerous question, thanking you for your support

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
