### ISSUE TITLE
Why are my leds going mad?

### ISSUE THREAD

**Issue by Lucid010** [Aircoookie/WLED#2487]
I recently bought some cheap wled controller and I just set it up and now it is doing this 

https://user-images.githubusercontent.com/92048044/149549672-2db342b8-0926-428e-82f8-6a0b8ca87a03.mp4

Is there a way to fix this?

**Comment by Aircoookie** [comment]
Check that both the ground and data of the LED strip and controller are connected properly. Also, if your controller doesn't have a built-in level shifter (all controllers that come pre-installed with WLED should), that could result in that behavior too.

Please use Discord or the forum for support the next time :)
