### ISSUE TITLE
Saving Overlays with Presets

### ISSUE THREAD

**Issue by CptSplard** [Aircoookie/WLED#2488]
I have a build of WLED with an overlay for a 7 segment clock, which works great. I'd like to be able to use the clock as a generic display at times, and be able to switch back and forth. Unfortunately when I select a preset it only changes the effect etc. and doesn't turn on/off the overlay 

I'd love to be able to use a preset or similar method of switching the  clock overlay on and off, especially via Home Assistant or other tool

I've been unable to find an alternative method to achieve this

https://github.com/hwtronics/clock-7seg-fw-WLED is the fork I'm using. I'd love to see his overlay become official too.

Thanks for all your hard work.

**Comment by blazoncek** [comment]
Usermod data can be saved in preset if usermod supports it (utilizes readFromJsonState()).
Ask usermod creator to add such support.
Closing.
