### ISSUE TITLE
change the Brightness on Segments with Hyperion

### ISSUE THREAD

**Issue by SirRob008** [Aircoookie/WLED#2490]
When i user wled with hyperion and have different Brightness on segments.
on connect from hyperion to wled, Wled change the Brightness of segments to master Brightness of wled and the segment Brightness are disabled.

**Comment by blazoncek** [comment]
Segments have their own API for setting brightnes/opacity: `"seg":{"bri":128}}` or `{"seg":[{"id":0,"bri":128},...]}`
