### ISSUE TITLE
Wifi connection 

### ISSUE THREAD

**Issue by Jurcsikk** [Aircoookie/WLED#2491]
### What happened?

So I am using esp8266 with the latest version of WLED self compiled/binary 1m of ws2812b 74leds and 6 amp power supply. After reboot it hardly connects to my wifi and if it connect I enter in the UI it says that is offline/unreachable tested 3 board's the same issue. 

### To Reproduce Bug

I don't know I have it from beginning 

### Expected Behavior

Pin 4 pull low 

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.0-b6

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use [WLED forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
