### ISSUE TITLE
SK9822 support

### ISSUE THREAD

**Issue by ricardogfp** [Aircoookie/WLED#250]
Would it be possible to add SK9822 support?

**Comment by Aircoookie** [comment]
Hi, SK9822 might be supported already due to similarities with the APA102 protocol. Try flashing the APA102 binary or enabling `#define USE_APA102` in NpbWrapper.h. Pins are also changeable there.

**Comment by Jaf1** [comment]
Is APA102 only supported by ESP8266? Or will the standard ESP32 binary also support APA102?

**Comment by Aircoookie** [comment]
@Jaf1 also supported on ESP32!
