### ISSUE TITLE
DMX output not working

### ISSUE THREAD

**Issue by johanneswilkens** [Aircoookie/WLED#2501]
### What happened?

I compiled wled via pio in vscode, I uncommented the dmx support line, changed led pin to 15, and no dmx option in wled web UI, changed dmx pin to 12, still no dmx option. Even tried emptying the whole flash by flashing esphome bin and then flashed new wled, still no dmx. The blue led on the esp12 keeps staying on, it doesn't matter if the dmx is on 2 or 12.

### To Reproduce Bug

Just flash a wled bin where you enable dmx, and no setting to configure appears.

### Expected Behavior

According to the site there should be an option to configure dmx somewhere in settings

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.0-b6 (build 2112080)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
Thank you for the report :) This should now be fixed in master!
