### ISSUE TITLE
Enable more LED outputs for DD RGB (network) on weaker devices

### ISSUE THREAD

**Issue by dgrekov** [Aircoookie/WLED#2505]
It looks like the number of LED outputs is limited by the number of available GIPO pins. Which makes sense if there are only local stops, but now that there is a capacity to add networked devices, it should be possible to add additional output strings over the network as long as all other criteria are covered (total LED count, etc).

**Comment by softhack007** [comment]
Number of DDP connections was increased with commit https://github.com/Aircoookie/WLED/commit/95869eeb7029ba41b7e092adde9c0af5ffd449e2.

Please open a new feature request if the problem you describe still persists in the latest development version.
