### ISSUE TITLE
Custom segment LED order/patterns

### ISSUE THREAD

**Issue by Keyes** [Aircoookie/WLED#2512]
**Is your feature request related to a problem? Please describe.**
I'm using "NeoPixel" rings for a project, and right now they're filling up circular when using an effect. While this is fine for many effects, it would be great to have the option to configure a custom order of LEDs, so that the ring fills up from the bottom to the top for example

**Describe the solution you'd like**
For the first iteration something like the segment UI would be enough: Create a pattern, add as many steps as you like, and define one or more LEDs to be affected by this step.

**Describe alternatives you've considered**
- use an external tool + E1.31/Art-Net/UDP

**Additional context**
---

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
use a ledmap.json file.
https://kno.wled.ge/advanced/mapping/
