### ISSUE TITLE
Playlists no longer working

### ISSUE THREAD

**Issue by SK360** [Aircoookie/WLED#2513]
### What happened?

Playlists will open the first preset and stop.

### To Reproduce Bug

Click playlist

### Expected Behavior

Playlist continues

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.0-b6 2201260

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output
Preset.json

`{"0":{},"1":{"n":"Uplighting","on":true,"bri":16,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":212,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[255,255,255,0],[0,0,0,0],[0,0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":true,"rev":false,"mi":false},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]},"2":{"n":"Rainbow","on":true,"bri":118,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":212,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[255,255,255,0],[0,0,0,0],[0,0,0,0]],"fx":9,"sx":128,"ix":128,"pal":0,"sel":true,"rev":false,"mi":false},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]}                                                                                                   ,"3":{"playlist":{"ps":[1,2],"dur":[100,100],"transition":[7,7],"repeat":0,"r":false,"end":0},"on":true,"n":"Test"}} `

State from the API, pl never changes from -1
`{"state":{"on":true,"bri":16,"transition":7,"ps":1,"pl":-1,"nl": `

### Anything else?

Works if I flash back to WLED 0.13.0-b6 2112080

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
you should provide playlist JSON API

**Comment by SK360** [comment]
> you should provide playlist JSON API

Added above

**Comment by blazoncek** [comment]
Fixed in https://github.com/Aircoookie/WLED/commit/3170fa220874524c8807f0f36a3a36f9e86cc20b

**Comment by SK360** [comment]
Rebuilt and playlists work! Thanks for the quick resolution!
