### ISSUE TITLE
Soundreactive wled noise issue

### ISSUE THREAD

**Issue by ArduinoNerdBheeshma** [Aircoookie/WLED#2515]
Hello I'm making a diy nanoleaf with about 565 neopixels, a 5v 20a power supply, esp32 dev and a max 4466 electret mic. The esp boot cycles on power up but sometimes turns on fine. But when I turn on a music effect the leds bounce around in complete silence. Decreasing the gain on the max4466 does solve this issue but it becomes too un sensitive. Pls help

**Comment by blazoncek** [comment]
Please file an issue with soundereactive [fork](https://github.com/atuline/WLED).
