### ISSUE TITLE
Feature request: IO-Pin for power supply on/off

### ISSUE THREAD

**Issue by mike811** [Aircoookie/WLED#252]
Hi,
thank you very much for this great project!

It would be nice to have an io pin and automatically switch the main power supply off when the LEDs are compleatly off. The ESP could be powered by USB and a second PS.
Background: Did some measurements and have about 16W light off power consumption with 600 LEDs and a Meanwell PS.

**Comment by Aircoookie** [comment]
Hi,

that feature is already implemented! By default, GPIO 12 goes LOW when the LEDs are fully off. You can change both pin and high low with the `#define RLYPIN` and `#define RLYMD` in NpbWrapper.h.

**Comment by fribse** [comment]
And it works perfectly!

**Comment by mike811** [comment]
Great, thanks.
