### ISSUE TITLE
ESP32 / WEMOS D1 Erroneous functions with 5V Stripes

### ISSUE THREAD

**Issue by Bebick** [Aircoookie/WLED#2525]
Hello all,

I got the following LED strips:
1) https://de.aliexpress.com/item/1005003068770194.html?gatewayAdapt=glo2deu&spm=a2g0o.9042311.0.0.6e7c4c4dE5Fc0d
2) https://de.aliexpress.com/item/1005003532294866.html?gatewayAdapt=glo2deu&spm=a2g0o.store_pc_groupList.0.0.67f945fdU1cPOy&pdp_ext_f=%7B%22sku_id%22:%2212000026198959070%22,%22ship_from%22:%22%22%7D&gps-id=pcStoreJustForYou&scm=1007.23125.137358.0&scm_id=1007.23125.137358.0&scm-url=1007.23125.137358.0&pvid=0fdecf17-c0fb-4298-90e9-71cc2f03db82

First I tested both LED strips on an ESP32. Unfortunately without satisfying result. The following errors occurred: 
For Stripe 1):
On the first LED there is a permanent fault (flashing in all colors).
At Stripe 2):
There is a permanent malfunction of the stripes (colors can be changed only conditionally - some LED points change their color others do not change them. Effects are also played only conditionally.
At first I suspected a defect of the stripes.
Afterwards I tested the same strips with a WEMOS D1 mini pro (ESP8266 with external antenna) and found out that they both work without problems.

Both tests were tested with the current 0.13.0-b6.

Do you have for this possibly an explanation of how this comes about?

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
