### ISSUE TITLE
Individually controlled LED brightness comes from previous Segment brightness

### ISSUE THREAD

**Issue by tmjd** [Aircoookie/WLED#2549]
### What happened?

I've been trying to control a single LED using the JSON API and have found that the brightness of the LED in a segment is dependent on the brightness and on state of the "previous" segment.

### To Reproduce Bug

Set up 4 segments (I don't know if 4 are necessary, that is how many I have).
1. Turn off the 3rd segment with `"{'bri':255, 'seg':[{'id': 2, 'on':false, 'bri':255}]}"`
2. Try to turn on the 1st LED on the 4th segment `{"seg":[{"id": 3, "i":[[0,0,255]]}]}`
3. The 1st LED on the 4th segment does not turn on.
4. Turn on the 3rd segment with `"{'bri':255, 'seg':[{'id': 2, 'on':true, 'bri':255}]}"`
5. Turn on the 1st LED on the 4th segment `{"seg":[{"id": 3, "i":[[0,0,255]]}]}`
6. The 1st LED on the 4th segment does turn on.

### Expected Behavior

I expect to not need to turn on the 3rd segment to Individually turn on an LED on the 4th segment.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.0-b6 (build 2112080)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

I have attempted to set the brightness and `on` state in my 4th segment individual LED command but that did not seem to make a difference.
I also created https://wled.discourse.group/t/json-api-individual-leds-are-dim/4914 because I thought maybe I was using the API was wrong.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tmjd** [comment]
I was doing a bit more testing and found that if a segment is "Reverse direction" and I turn on an individual LED on the segment, I must have the following segment on and the brightness set. 
Here is an example:
With Segments:
  0: don't care
  1: don't care
  2: Reverse direction. This is the segment where I turn on an individual LED
  3: This segment drives the individual LED brightness

Also a general note on this that I haven't really mentioned is that the individual LED is not directly controlled because if I have the Individual LED lit up and turn off the "controlling" segment the individual LED does not turn off, but if I send the command for the individual LED again then the Individual LED turns off.

**Comment by Aircoookie** [comment]
Hi! I've tried your reproduction steps and step 2 correctly turns the LED blue for me even after turning of the previous segment.
Your observation of reversing segments changing the direction leads me to believe you might have overlapping segments that cause this issue.
WLED will not stop you from creating overlapping segments, but they are not really intended at this time and may lead to unexpected behavior.
Please send your output of `/json/state` and I will retry again to reproduce the bug :)

**Comment by Aircoookie** [comment]
Note that your observation in the forum thread, albeit suboptimal, is true: Any changes to brightness will alter/fade the colors set by individual LED control as there is no double buffering. Turning off the LEDs completely will auto-revert from individual control to effect mode as individual mode would just display black.
I would recommend to always set the individual LEDs again after adjusting brightness. We are working on a better long term solution though!

**Comment by tmjd** [comment]
I have tried with another device I have and setup a simple LED strip with 3 segments, each with 2 LEDs in each segement and I see the behavior I expected (where setting an Individual LED does not depend on the state of the previous segment). So I see correct behavior on a different device.

So I thought maybe there is some configuration/state that was tripping up my original configuration so I did a Factory reset from the "Security & Updates" page and reset my configuration. But unfortunately after configuring the device again I am still seeing the same unexpected behavior. Here is the `json/state` for the new device/configuration:
```
{"on":true,"bri":255,"transition":7,"ps":1,"pl":-1,"nl":{"on":false,"dur":60,"mode":1,"tbri":0,"rem":-1},"udpn":{"send":false,"recv":true},"lor":0,"mainseg":0,"seg":
[{"id":0,"start":0,"stop":18,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":1,"start":18,"stop":36,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[102,153,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":2,"start":36,"stop":54,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[0,204,51],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":3,"start":54,"stop":60,"len":6,"grp":1,"spc":0,"of":0,"on":true,"bri":255,"cct":127,"n":"Notifications","col":[[0,51,204],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false}]}
```

I'm a bit confused at this point to what is happening with the setup that has this unexpected behavior. If I compile with WLED_DEBUG defined would that possibly help? What do I need to do to get that debug output? Is it just have a serial connection to the USB tty device?

Assuming the segment with `id` 3 exists (the 4th segment), is there any configuration that the payload `{'bri':255, 'on':true, 'seg':[{'id': 3, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` would not turn on the 1st LED on the 4th segment? As I understand the command it should be setting master brightness to max, the master to on, turn on the 4th segment (though I expect since I'm setting an Individual LED, all LEDs except the ones specified will be blanked), and set the 1st LED to blue.

**Comment by Aircoookie** [comment]
Thank you for the extra info! I can confirm your segments are set up correctly.
Does the issue only occur if the master brightness or segment with `id` 3 was off before?
If you turn on the brightness and set the individual LEDs in the same command, it will not apply correctly (only display black). The reason is that the individual colors are applied before the brightness change, so the brightness will still be set to 0.

I think I'll change the brightness handling to apply any changes immediately if there is an `i` array within the same request, that way transitions will not work, but at least the colors should be set as expected when sending e.g. `{'bri':255, 'on':true, 'seg':[{'id': 3, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` while the light was off or on low brightness.

**Comment by tmjd** [comment]
I had the master on and brightness max and the segment off but brightness max before sending the command. But even so, I  sent the command multiple times and the only time the individual LED turned on was when the previous segment was already on.

Another interesting data point on this. The reason I've been trying to use these individual LED capability it has been because I was trying to have a few single LEDs that I could turn on/off from Home Assistant. Since my setup seems to have issues with the individual LED functionality, I took my 4th segment (which was 6 LEDs) and created 3 segments with 1 LED each (and left the other 3 LEDs not in a segment). When I used the command `{'bri':255, 'on':true, 'seg':[{'id': 3, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` it did not work to turn on the LED in the 4th segment and turning on/off the previous (3rd) segment had no impact, but when I turned on segment id 5 (the 6th segment) the individual LED turned on when sending the command. Here is the json/state if you want to see this new config.
```
{"on":true,"bri":255,"transition":7,"ps":1,"pl":-1,"nl":{"on":false,"dur":60,"mode":1,"tbri":0,"rem":-1},"udpn":{"send":false,"recv":true},"lor":0,"mainseg":0,"seg":
[{"id":0,"start":0,"stop":18,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":true,"rev":false,"mi":false},
{"id":1,"start":18,"stop":36,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[102,153,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":2,"start":36,"stop":54,"len":18,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"col":[[0,204,51],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":true,"mi":false},
{"id":3,"start":54,"stop":55,"len":1,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"n":"garage","col":[[0,51,204],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":4,"start":55,"stop":56,"len":1,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"n":"doors open","col":[[102,0,153],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false},
{"id":5,"start":56,"stop":57,"len":1,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"n":"lock","col":[[255,0,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":false,"rev":false,"mi":false}]}
```

:shrug: If you want to close this bug and write this off as something messed up on this one device I'm fine with that, I've got a workaround for what I want to do. But if you think there is something to investigate I'm happy to try things.

**Comment by tmjd** [comment]
So maybe it isn't an isolated device. I set up another device and see the same kind of behavior where an individually controlled LED in one segment is controlled by the `on` status and brightness of a different segment.
Here the the `json/state` of the device:
```
{"on":true,"bri":255,"transition":7,"ps":1,"pl":-1,"nl":{"on":false,"dur":60,"mode":1,"tbri":0,"rem":-1},"udpn":{"send":false,"recv":true},"lor":0,"mainseg":0,"seg":
[{"id":0,"start":0,"stop":35,"len":35,"grp":1,"spc":0,"of":0,"on":true,"bri":255,"cct":127,"n":"Counter top","col":[[203,219,255],[255,0,0],[255,200,0]],"fx":0,"sx":134,"ix":133,"pal":2,"sel":true,"rev":false,"mi":false},
{"id":1,"start":35,"stop":70,"len":35,"grp":1,"spc":0,"of":0,"on":false,"bri":255,"cct":127,"n":"Shelf 1","col":[[203,219,255],[255,0,0],[255,200,0]],"fx":0,"sx":134,"ix":133,"pal":2,"sel":true,"rev":true,"mi":false},
{"id":2,"start":70,"stop":105,"len":35,"grp":1,"spc":0,"of":0,"on":true,"bri":255,"cct":127,"n":"Shelf 2","col":[[203,219,255],[255,0,0],[0,0,0]],"fx":0,"sx":134,"ix":133,"pal":2,"sel":true,"rev":false,"mi":false},
{"id":3,"start":105,"stop":140,"len":35,"grp":1,"spc":0,"of":0,"on":true,"bri":255,"cct":127,"n":"Shelf 3","col":[[203,219,255],[255,0,0],[0,0,0]],"fx":0,"sx":134,"ix":133,"pal":2,"sel":true,"rev":false,"mi":false}]}
```
For `{'on':true, 'seg':[{'id':0, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` to turn on the 1st LED in the 1st segment, the 2nd or 4th segment must be on and brightness set.
For `{'on':true, 'seg':[{'id':1, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` to turn on the 1st LED in the 2nd segment, the 1st or the 4th segment must be on and brightness set.
For `{'on':true, 'seg':[{'id':2, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` to turn on the 1st LED in the 3rd segment, the 4th segment must be on and brightness set.
For `{'on':true, 'seg':[{'id':3, 'on':true, 'bri':255, 'i':[[0,0,255]]}]}` to turn on the 1st LED in the 4th segment, the 3rd segment must be on and brightness set.

I'll try to take a look at the code this weekend if I have time to see if I can figure out any possible way this is happening.

**Comment by blazoncek** [comment]
Internal segment workings have been rewritten from scratch for 0.14
If the problem still appears in 0.14 please reopen the issue.
