### ISSUE TITLE
Spotify extension for WLED SR

### ISSUE THREAD

**Issue by Stoppersocke00** [Aircoookie/WLED#2550]
I have used WLED SR for a long time and there is one thing that is frustrating me. For WLED to be sound reactive, you need an external microphone or analog port. The external microphone solution is practical, but does not look as good as the solution with the analog port. Also all of the sound in the room is visualized by WLED. So am I not  using the analog port solution? Because I'm listening to my music with many different devices and I can't connect an analog jack to the devices every time. Also it's very frustrating for me that I always have to use an analog cable. 

I would like to have a solution that is full wireless, compatible with all my Spotify devices (like ps4, echo dot, Smartphone, PC, iPad) and that has the effect quality like the analog port solution.
To realize this, WLED needs to have access to what you're listening to. This feature is already given in Spotify, you can see when you're logged in on two devices with the same account and what the other device is playing. 
My idea was, to create a Spotify extension, that can read what you're listening to on Spotify. This extension only reads what is played on the given account. This would work with all Spotify devices connected to the internet. 

Another solution would working the other way round. To create a module, that is working as a player. The module streams music from Spotify, visualizes the sound of it and sends the sound wireless to other devices like bluetooth speakers. This solution is much more uncomfortable to use, but is easier to realize. 

![Screenshot_20220219-124641.jpg](https://user-images.githubusercontent.com/56961941/154799462-2dae27c8-3fef-42f5-8334-41495ad1791f.jpg)

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Even though this would be great addition to WLED you are referencing WLED SR which is a separate fork.
Please post this into their issue tracker.

You may also check [LedFx](https://github.com/LedFx/LedFx) or what @YeonV have [done](https://github.com/YeonV/wled-manager) using live data stream (not device independent currently, though).
Closing.
