### ISSUE TITLE
https://www.youtube.com/watch?v=Y1DvyiWENC4&feature=emb_logo

### ISSUE THREAD

**Issue by yousaf465** [Aircoookie/WLED#2560]
https://www.youtube.com/watch?v=Y1DvyiWENC4&feature=emb_logo this guy did it with ESPhome, I want to do it with WLED. 
How do I drive and wire-up non-addressable LED like this one? what hardware I would need and how to wire it up? 
![image](https://user-images.githubusercontent.com/83491212/155675814-1632b76d-e10b-4b5a-9ec2-8c4476971654.png)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
