### ISSUE TITLE
HD107s upgrade of APA107

### ISSUE THREAD

**Issue by Suspect-byte** [Aircoookie/WLED#2562]
Hi all,

Im a kindda new to all of this. So i got the HD107s thats the upgrade of the APA107 here is a datasheet

https://www.hd107s-led.com/wp-content/uploads/sites/48/2020/04/HD107S-RGB-LED-5050.pdf

I got a esp32 devkit v1 30GPIO board. How can I let the lets work with wled? Which pins should i use. I already used GPIO14 GPIO13 for CLK and DATA.

I used GPIO 18 for CLK and GPIO23 for data. I only get the full bright lights from my led strip with a flickering of some colours. The ledstrip response to effects but remains white with some sort of flickering of different colours.

What can i do to let them work. Thanks in advance!

**Comment by blazoncek** [comment]
Check with [NeoPixelBus](https://github.com/Makuna/NeoPixelBus) if it (APA107) is supported. If it is, it may be supported in WLED in a future release. If it is protocol compatible with APA102 use that in LED settings.

For all other help and support questions use WLED [forum](https://wled.discourse.group) or Discord.
Closing.
