### ISSUE TITLE
json.cpp: suspicious condition that is always true

### ISSUE THREAD

**Issue by softhack007** [Aircoookie/WLED#2566]
Hi,
below some code that does not look right to me - either the "if" is not needed, or maybe the condition is not correct.

https://github.com/Aircoookie/WLED/blob/25427ee60d75af5708314f2c7641cdd8e387d12b/wled00/json.cpp#L203

The "if" condition will always be true, because any number is _either  > 0  **or**  < 5_.

I found this one with the code analysis tool "cppCheck"
```C++
incorrectLogicOperator
CWE: 571
Logical dis-junction always evaluates to true: sz > 0 || sz < 5. 
Are these conditions necessary? Did you intend to use && instead? Are the numbers correct? 
Are you comparing the correct variables?
```

**Comment by Aircoookie** [comment]
Thank you!
In this case this was intended to be `&&` indeed. Will fix!
