### ISSUE TITLE
Analog button (potentiometer) causes glitches and flickering

### ISSUE THREAD

**Issue by dylan-conlin** [Aircoookie/WLED#2587]
### What happened?

I've noticed that attaching at least 1 potentiometer causes my light strip (300 LEDS) to flicker. The flickering seems to get worse if I increase the number of LEDS.

Does this have something to do with frame rate? Is there a workaround or fix?

### To Reproduce Bug

To reproduce, add a potentiometer to control the effect speed.

### Expected Behavior

I expect the lights to not flicker when I add a potentiometer.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED v0.13.0-b7 "Toki" 2202222

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huggy-d1** [comment]
Which pin is the POT connected to?
Which pin is connected to the LED strip data input?
If those questions have the same answer, there's the problem.

**Comment by tke233** [comment]
I'm experiencing this as well, and also if you tuned in to the DrZzs livestream, you see he also had issues with his potentiometer https://youtu.be/M4M7qox2zFk?t=3035 I am using a 20K Ohm potentiometer he was using a 10K Ohm potentiometer.  I am going to try some other valued potentiometers that I have to see if the results differ any.  The board I'm using is a QuinQuad v2. I have 2 potentiometers hooked up (Pin 36 & 32) flicker occurs when using 1 or both.

**Comment by blazoncek** [comment]
Try adding yield() right after analogRead() and report back.

**Comment by tke233** [comment]
> Try adding yield() right after analogRead() and report back.

I'm on familiar with the point-n-click UI, sorry but if you can give me idiot proof instruction of how to do what you're asking, I will test it out immediately.

**Comment by blazoncek** [comment]
Sorry, needs modifying source and recompiling.

**Comment by shd7899** [comment]
I noticed the same behavior. In my case there were 4 pots 20K each. Connected to ESP32 GPIO36, 39, 34, and 35. LED's flicker whether you use 1 pot or 4. I tried to use a 0.1uf capacitor with each pin and GND, but it did not help.

**Comment by blazoncek** [comment]
Flickering is not related to a capacitor (or the lack of) on the input GPIO.
Try changing the code to wait if `strip.isUpdating()` before processing ADC.

**Comment by softhack007** [comment]
Could this be "simply" the noise from ADC? ESP32 has somewhat noisy analogue sampling hardware, see https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc.html#minimizing-noise

To fight ADC noise, some software filtering might help, like this (just an example to illustrate the idea)
```` C++
static float aRead = 0;
float newReading = analogRead(...);

aRead = aRead + 0.05 * (newReading - aRead);. // exponential filter to smooth noisy input - 0.05 is the filter parameter; adjust to your needs

return(aRead);
````

**Comment by blazoncek** [comment]
Noise is somewhat taken care of (by truncating lower bits).

**Comment by softhack007** [comment]
POTs are sometimes noisy , causing scratching / glitches when you turn them. Noise from the ADC ( up to 1%) is different, and occurs at any time, also when _not_ turning the POT. 

Both kinds of noise could be reduced by low- pass filtering the value from analogread - see my example above. However truncating lower bit would only help sometimes. Imagine when your value is noisy and dancing araround the value of 15. Now if you truncate the lowest two bits, you still have noise whenever the signal crosses the borderline between truncation "bins". For example: going from 15 to 17 then back to 14.  A simple exponential filter would perform better in this case.

I could try to make a PR, however currently I'm too busy with activities related to WLED-SR. 

Would be great (appreciated, la Ola, winner winner chicken dinner, hero of the minute, etc 😉 ) if someone jumps in to make a PR that includes recommendations from above disussions:
1. wait if strip.isUpdating() before reading a new value from ADC
2. Try adding yield() right after analogRead() - might help or not help
3. Filter the value from analogread- filter parameter tuning needed, so the POT remains responsive but the value changes smoothly

**Comment by softhack007** [comment]
I think this would be the code function to look into (@blazoncek please correct me)

https://github.com/Aircoookie/WLED/blob/19c8b4fe2d0d86887d49abd5c965fd1d46502679/wled00/button.cpp#L134

**Comment by blazoncek** [comment]
> I think this would be the code function to look into (@blazoncek please correct me)
> 
> https://github.com/Aircoookie/WLED/blob/19c8b4fe2d0d86887d49abd5c965fd1d46502679/wled00/button.cpp#L134

Correct!
It would be great if you could spare a minute or two to make this better. I have never had serious issues while testing potentiometer but I do admit that I do not use it in any production unit.
One thing I did notice is that analogRead() can be quite slow on ESP8266.

**Comment by softhack007** [comment]
done - see PR #2693.

**Comment by softhack007** [comment]
Just for explanation: the PR should solve problems (flickering) related to analog input. It filters out noise, and ensures that effect parameters are not changed while a "strip update" is in progress.

There are other possible sources of "flickering", which are not specific to analog input; when using web UI you might see "flicker-like" interruptions in some effect:
* when changing effect speed or intensity 
* when the brightness is very low
