### ISSUE TITLE
Binaries WLED_0.8.5_ESP8266_APA102.bin with BGR support :-)

### ISSUE THREAD

**Issue by DuschdrBabbe** [Aircoookie/WLED#259]
Hello,

need bin file for ESP8266 with the LED (APA102) setttings for BGR ...

THX

Pascal

**Comment by lostdave** [comment]
not really an issue, but here you go.
Maybe discord would be a better place to request builds...or you could learn to do it yourself.
There are plenty of tutorials around for atom/arduinoide.

https://drive.google.com/open?id=1LUZZov9XfHM0LC9F6WNKOtfRAyUIu3Ve

**Comment by DuschdrBabbe** [comment]
Hello Dave,

thank you so much ... yes discort is a option ... ;-) 

Pascal

**Comment by DuschdrBabbe** [comment]
Hey Dave,
there ist no BGR in the list :-)

Greetings

**Comment by Aircoookie** [comment]
Hi, i believe the binary Dave sent you has BGR coded in, so if you select GRB you'll have the correct colors. Regardless, i'll add BGR to the options list :)

**Comment by DuschdrBabbe** [comment]
no sir .. ;-) have try it but red and blue are still reversed...
But THANKS for implementing!!!!

**Comment by DuschdrBabbe** [comment]
sorry guys,
it,s my fault... wrong hyperion config...
it works...
