### ISSUE TITLE
Control Single LEDs or Groups of LEDS

### ISSUE THREAD

**Issue by swaxx-ha** [Aircoookie/WLED#260]
Hi there

is there a way to control single LEDs? I think about to switch to WLED (looks very promising, nice work!), but i would like to control individual LEDs, for example the first and last 20 LEDs of the Strip. Is this possible with WLED? If yes, how?

Cheers

Mike

**Comment by raoulteeuwen** [comment]
Do the threads https://github.com/Aircoookie/WLED/issues/226 and https://github.com/Aircoookie/WLED/issues/190 answer you question?

**Comment by swaxx-ha** [comment]
Hi Raoul, i obviously searched with the wrong keywords, i'm sorry. Looking forward to this. Thanks a lot! Cheers, Mike
