### ISSUE TITLE
I hope there will also be a V13 ESP8266 version

### ISSUE THREAD

**Issue by Hardwarekiller** [Aircoookie/WLED#2604]
Will there also be a V13 version for the ESP 8266, I really hope so! and if not why not?

**Comment by k7bbr** [comment]
There's an ESP8266 version in the 0.13.1 release already. https://github.com/Aircoookie/WLED/releases/download/v0.13.1/WLED_0.13.1_ESP8266.bin

**Comment by Aircoookie** [comment]
There is of course! install on install.wled.me, or look in releases for the. bin file.

If you are taking the sound reactive fork, to my knowledge ESP8266 support is abandoned as maintaining it would result in too many tradeoffs, so it's unlikely there will be a 0.13 SR release for the 8266.
