### ISSUE TITLE
AZ-Delivery ESP32 WROOM-32 not showing up WI-FI WLED-AP?!

### ISSUE THREAD

**Issue by Radium2k7** [Aircoookie/WLED#2611]
Hey there,

i flashed the ESP32 with different versions, but it`s not showing up for first Setup in wi-fi :(
Before i tried going with ESP32 i have successfully installed and used a 8266 without any problems.

Any tips??

thnx :)

**Comment by Aircoookie** [comment]
Hi, have you tried https://install.wled.me ?

**Comment by Radium2k7** [comment]
Oh yeah, that does the trick!! thnx so much!!!!! :)
