### ISSUE TITLE
Safari on iPhone interprets presets 9-16 as phone numbers

### ISSUE THREAD

**Issue by qubie2012** [Aircoookie/WLED#262]
Hi I know this is not an issue with WLED code but i wasnt sure where to go with this one
The issue i have is the 16 preset buttons 1 - 8 work fine but 9 - 16 are underlined and if i try to use 9 - 12 my phone wants to call 910 1112 if i try 13 - 16 it wants to call 131 415 16.

I have tried a ANDROID phone and the presets are all fine just IOS 

by the way thankyou for this project I am have more fun playing around with this than i have in a long time.

**Comment by tube0013** [comment]
I can confirm this happens for me as well. (Just upgraded to 13.1.3).

Hitting the WLED ip via safari does not have the same issue.

App:
![IMG_B1AB9D867A8E-1](https://user-images.githubusercontent.com/11084412/66868546-872e2c00-ef6b-11e9-841e-f602788f51a9.jpeg)


Safari:
![IMG_995392E7B06D-1](https://user-images.githubusercontent.com/11084412/66868492-649c1300-ef6b-11e9-9b76-d0b54addebbc.jpeg)

**Comment by lostdave** [comment]
Same Same - 
I don't use the presets, so not so much an issue for me.

**Comment by Aircoookie** [comment]
Interesting issue! That safari even considers this a phone number even though the digits are separated by HTML tags... Will be fixed by upcoming UI update!

**Comment by qubie2012** [comment]
Thanks Aircoookie this is an awesome piece of work
love it.

**Comment by doug1376** [comment]
Also have this issue on iPad and iPhone.  To add to it.  I also have no scroll bar on the right had side of FX and Palettes in iOS.  However Love this app.

Thanks aircookie
![Image-1](https://user-images.githubusercontent.com/57166067/67829565-918c2080-fb3c-11e9-9291-5b1bc7230aa8.jpg)

**Comment by fijit586** [comment]
I have seen this too. iPhone8.

**Comment by Ve6hgw** [comment]
I have this issue too but it’s just a very minor inconvenience.
