### ISSUE TITLE
Latitude: max 66.6 ?

### ISSUE THREAD

**Issue by Quato38** [Aircoookie/WLED#2623]
### What happened?

I live here: Latitude: 69.64, Longitude: 18.99  so i can't get exsact location on my wleds

When i enter 69.64 in Location settings i get an error:  Latitude: must be less og equal to  66.6

### To Reproduce Bug

enter Latidue: over 66.6 

### Expected Behavior

i expected to enter 69.64 witch is my latidude

### Install Method

Binary from WLED.me

### What version of WLED?

wled 13.01

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Unfortunately you live above polar circle where sunrise and sunset calculations will not work.

**Comment by Aircoookie** [comment]
Added this info to KB at https://kno.wled.ge/features/presets/#applying-presets-at-sunrise-and-sunset
