### ISSUE TITLE
WLED version 0.13.1

### ISSUE THREAD

**Issue by kambiumdt** [Aircoookie/WLED#2626]
Hello.

I have two wled fw.
one on ESP32 - work fine
second on esp8266.

On esp32 work perfect.
On 8266, when i turn off power of him, and turn on (5V), the ESP32 its visible on HA, but on esp8266 its all time offline - i must go to web, turn on him, and them i can see him on HA.

There is same config. The only one diffrent - on 8266 i have configuraed input as switch. 

Any solutions?

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
