### ISSUE TITLE
Feature request: Tapping on the sensor button

### ISSUE THREAD

**Issue by valki2** [Aircoookie/WLED#2629]
Hi!
I wonder if it aint sexy to add some more "tapping" options to the (sensor) buttons by distinguishing the way the button was pressed. Then one yould integrate some real cool 1-button-controls like:

- single press for toggle on/off
- long press and holding for incrementing the brightness
- short press followed by a long press/hold for lowering the brightness
- double tap for preset 2
- tripple tap for preset 3
- etc :D

**Comment by blazoncek** [comment]
Some of this is already available using button >0.

**Comment by blazoncek** [comment]
Except for tripple-tap other variants are implemented.
