### ISSUE TITLE
Slow and sever delay with WLED+Jinx+E1.31ORArtnetORtmp2.net+NodeMCU(ESP8266+chipCP2102)+WS2812Bmatrix

### ISSUE THREAD

**Issue by wyhpolyu2020** [Aircoookie/WLED#2631]
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

Dear ALL,

I am trying to set scrolling text to my LEDmatrix using WLED. My method is using Jinx to set it in realtime. However, I tried many times and servre delay problems always meet me. Does anyone know why?  Please also see my video. Thank you all! WLED forever
!!!!

https://user-images.githubusercontent.com/65244536/163119376-59302069-ea81-4e6d-9772-c3d860f35384.mp4

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help or support questions.
Closing.
