### ISSUE TITLE
Presets & playlist

### ISSUE THREAD

**Issue by moshiko2312** [Aircoookie/WLED#2635]
Hi what i can do all the time im lost my presets and playlist
Somebody can help?

![Uploading 1585C252-447F-4C4C-8733-74E6C012D9EA.jpeg…]()

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help or support questions.
Closing.

**Comment by moshiko2312** [comment]
Ok thanks
