### ISSUE TITLE
Feature request: Toggle Switch GPIO mode

### ISSUE THREAD

**Issue by bob-tm** [Aircoookie/WLED#2636]
**Is your feature request related to a problem? Please describe.**
Sync Turning Light On/Off from physical switch and Web switch. 

**Describe the solution you'd like**
I have physical switch connected to GPIO.
physical switch = On => Lights On
web switch = off => Lights Off
Click physical switch => Nothing happens, because physical switch goes from On => Off state.

My solution is to Toggle Lights power every time, when  physical switch change state. Just do "button click", when physical switch change state. 

**Describe alternatives you've considered**
I have UserMode, but new HomeAssistant update feature kill my custom firmware :)
I think few lines of code will help a lot of people. 

```

class BobSwitchUsermod : public Usermod {
  private:
    unsigned long lastTime = 0;
    bool lastState = 0;
  public:
    void setup() {
      pinMode(SWITCHPIN, INPUT_PULLUP);
      lastState = digitalRead(SWITCHPIN);
    }

    void loop() {
      if (millis() - lastTime > 100) {

        if (digitalRead(SWITCHPIN) != lastState) {
          lastState = digitalRead(SWITCHPIN);
          shortPressAction();
        }
        lastTime = millis();
      }
    }
}
```

**Comment by blazoncek** [comment]
Not needed. Just create a preset that toggles power when switch state is changed.

Use: `{"on":"t"}`or T=2 in API call.
