### ISSUE TITLE
push button-change color

### ISSUE THREAD

**Issue by 6000850** [Aircoookie/WLED#2637]
Hello
In the source code, I added a push button that, if pressed, would change the color of the LEDs to white, for example.
How can I change the color of the LEDs?
I have defined this code in the loop and setup methods

setup
```
Serial.begin(115200);
  Serial.setTimeout(50);
  pinMode(buttonPin, INPUT_PULLUP);
```

end of loop method :
 ```
 int button1;
  button1 = digitalRead(buttonPin);
  if(button1 == LOW){
    // change led's color
  }

```

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
