### ISSUE TITLE
USERMOD_AUTO_SAVE feature not working

### ISSUE THREAD

**Issue by asking23** [Aircoookie/WLED#2639]
### What happened?

To Enable Last State Save option, recompiled using PlateformIO.

Got below option in Web UI. But even after settings its not saving last state.

Added to PlateformIO.ini File
` -D USERMOD_AUTO_SAVE feature`

![image](https://user-images.githubusercontent.com/6546108/163991346-f836e83c-0063-417c-a4e4-30a45cd1ba96.png)

### To Reproduce Bug

Just turn off ESP32 after 15 Seconds and rebooted but no effect. Same Default light setting is picked up. 

### Expected Behavior

Expecting to store the last state when power fails.

### Install Method

Self-Compiled

### What version of WLED?

WLED-0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Unfortunately I cannot confirm your findings.
Auto Save usermod is working as expected.

**Comment by asking23** [comment]
You're right. Its working as expected. 

Just those who are looking for Saving last state Please remember to uncheck Powerup/reset and Make Presets : 0.

![image](https://user-images.githubusercontent.com/6546108/164144957-94d53456-5238-4910-9b98-9d262eea687f.png)

**Comment by blazoncek** [comment]
Will add this check to Auto Save usermod...
