### ISSUE TITLE
2 Line LCD display

### ISSUE THREAD

**Issue by sjude68** [Aircoookie/WLED#264]

**Comment by Aircoookie** [comment]
Pin 4 is used for IR receiver by default. Try changing the IR pin to something else in `NpbWrapper.h` (or the second lcd pin) and your LCD should work again :)

**Comment by sjude68** [comment]
I had disabled IR in NpbWrapper.h (-1). LCD wasn't  working.

**Comment by Aircoookie** [comment]
Just found out that the line:
```cpp
pinMode(4, OUTPUT); digitalWrite(4, HIGH);
```
was added to `setup()` in the bottom of wled00.ino in a recent commit.

I don't exactly know my reasoning to init that particular pin (maybe it was only for testing?), but deleting that line could make the LCD work again.

**Comment by sjude68** [comment]
I seen that line but didn't realize it was from you. I have added 4 more
relays to work with Alexa and I thought that I had put that line for
testing. Anyway I am using D5, D6, D7 & D8 for the relays. D3 for DHT11
which I am displaying on the LCD.

I will comment line for pin4 which is D2 on D1 Mini and check out LCD.
Thanks.

**Comment by sjude68** [comment]
LCD working after deletion of line in setup{}

**Comment by sjude68** [comment]
How do I control power on the D1 Mini. 

I connected Dht11 on pin D3 without any resistor. 

When I power up the D1 Mini with power connected to the relay the ESP8266 doesn't boot even after manual reset. But if I disconnect the 5v from the relay at boot and connect it later everything works fine. Is it that the DHT11 is taking all the power.

Everything worked fine (relays and Led strip) without DHT11. I am powering the D1 Mini from external 5v power supply. Led strip uses the same power line. 

Or should I change code (and power connection to DHT11 from an available GPIO pin) to read temperature. This way the power to DHT11 is only used when talking the reading.

**Comment by Aircoookie** [comment]
@sjude68 the pin D3 must be high on boot, otherwise the ESP can't boot. The DHT11 is probably pulling it low. The easiest option is probably to connect the DHT11 to some other pin with an external pullup resistor. You could also hook up DHT11 VCC to some other pin and set it high after boot, but that is generally not good practice, so I recommend the first solution.
