### ISSUE TITLE
Feature request: Playlist End Preset "Last Used"

### ISSUE THREAD

**Issue by thomshouse** [Aircoookie/WLED#2640]
**Is your feature request related to a problem? Please describe.**
I have a few use cases where it would be nice to play a short playlist, then revert to whatever the previous settings were. Examples are creating a visual "chirp" effect for notifications in interior home lighting, or cueing a random "lightning flash" or similar effect for a game room.

**Describe the solution you'd like**
When configuring a playlist, I would love to be able to specify in the End Preset select box "Previous Settings" or "Last Preset".

**Describe alternatives you've considered**
I think being able to revert to the previous settings, whether or not they were a preset, would be most directly useful.  However, if simply tracking the last used preset is an easier implementation, I believe it would be sufficient for my needs.

An additional/extra functionality I considered was also making this "Previous Settings" / "Last Preset" option available for individual states of the playlist as well, not just the end state.  That would enable us to create playlists that look like:

- Preset: "Solid Red" (0.25 seconds)
- Previous Settings (0.25 seconds)
- Preset: "Solid Red" (0.25 seconds)
- Previous Settings (0.25 seconds)
- Preset: "Solid Red" (0.25 seconds)
- End State: Previous Settings

**Additional context**
Thanks to blazoncek on Discord for feedback on this.  After the idea was met warmly there, I realized the Github had feature requests there as well and figured this might be an easier way to track it.

**Comment by blazoncek** [comment]
Implemented in https://github.com/Aircoookie/WLED/commit/80152f522126029a7ab9801c8fd47acc70a57da6

If no preset was selected prior to starting playlist with this option (or was overridden by changing parameters) the behavior will be as no end preset was selected.
