### ISSUE TITLE
Usermode -> currentMode question

### ISSUE THREAD

**Issue by KrX3D** [Aircoookie/WLED#2647]
Hello,

i want to create  usermode but i got a questions .

i want to get the current set mode and after that set a random effect. After x seconds i want to set the old effect back.

For now i only got the random effect part and i didnt find any info on how to get the current effect.

`
			int randomFX = random(0, MODE_COUNT-1);
			 //  Set strip to random FX
			 strip.setMode(strip.getMainSegmentId(), randomFX);`

also is there a way to change the effect my given name and not "id" like "Running", "Pride 2015" etc?

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
