### ISSUE TITLE
Aplication hangs after 24hours on NodeMcu V3

### ISSUE THREAD

**Issue by Hubert97** [Aircoookie/WLED#2660]
### What happened?

Module runs normally. After aproximately 24 hours it becomes unresponsive - it is not present on network. Restarting board fixes the problem.

### To Reproduce Bug

Node mcu V3. after approx 24 hours module goes offline.

### Expected Behavior

For it to stay functional like in prevous version.

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

Prevous version i used on this module (10 something) worked fine for a long long time without probblems. After upgrading it behaves like this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hubert97** [comment]
Update on bug. It seems that the module loses wifi connection. I turned animation on after about 15 hrs from initial power up, and it worked fine. However after ~24 hrs it is no longer present on my network tho animation is still present. I checked and it also doesn't create its own ap.

**Comment by poelzi** [comment]
Does the button work to toggle master on/off. It could be a hard hang which I experience a lot with current FW. I added added a watchdog so the node does not hard lockup anymore #2657

**Comment by Hubert97** [comment]
I do not have an easy access to button and also i don't use it. Ill checkout your commit and reply if this solved the issue.

**Comment by Phara0h** [comment]
I have the same issue and the toggle button still works even though it's not reachable via wifi

**Comment by Hubert97** [comment]
Problem is still persistent on recent build.

**Comment by Hubert97** [comment]
I've noticed that when aplication hangs it is still discoverable by other machines - responds to ping.

**Comment by blazoncek** [comment]
FYI similar behaviour can be observed on ESP32-S2, effects still play, buttons still work but device is unreachable over WiFi.
This is not a WLED bug *per se* but rather underlying WiFi/AsyncWebServer implementation bug.
I am closing this issue as WLED can do little to mitigate the problem. Newer versions of libraries may improve the behaviour in the future.
