### ISSUE TITLE
WLED doesn't turn on correctly.

### ISSUE THREAD

**Issue by AndreePT** [Aircoookie/WLED#2661]
### What happened?

Hello, i have a WS2812B led strip, it's 10 meters of led strip connected to a ESP8266 and a 5V 12A power supply.
The positive and negative are connected to the power supply
The ESP8266 power is connected to the power supply
The data cable is connected correctly to the ESP data pin.

When i power up the power supply to turn on everything, if the data cable is connected, it only shows 2 lights and the ESP doesn't start the AP (Acess Point), but if i power down the power supply, disconnect the data cable, power up and then connect the data cable, it turns on normally.

What should be causing that? Thanks!

### To Reproduce Bug

Just powering up everything, it looks like the ESP can't initialize with data cable connected.

### Expected Behavior

Turn on normally.

### Install Method

Binary from WLED.me

### What version of WLED?

Version 0.13.0-b6

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Incorrect wiring or electrical set-up.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
