### ISSUE TITLE
Transition not working from Home Assistant

### ISSUE THREAD

**Issue by Philje123** [Aircoookie/WLED#267]
Hi folks,

I've searched through all the documentation and closed issues but can't find the answer.

If I use an automation or script from HA with "transition: 60" for example it doesn't work and WLED turns straight off.

I've got it added via MQTT auto discovery.

**Comment by Aircoookie** [comment]
Hi,
just wanted to let you know I haven't forgotten this issue :)
Will take a look tomorrow!
You did try to set the transition duration via the JSON API, correct?
Over MQTT directly that wouldn't work currently.
Cheers!

**Comment by Aircoookie** [comment]
Ah ok, makes sense! It will be possible soon via MQTT using a `device/api/set` topic :)
