### ISSUE TITLE
Battery Status

### ISSUE THREAD

**Issue by rtjeras89** [Aircoookie/WLED#2674]
I try to use the battery status and followd the instruction.. 1 line.... added #define USERMOD_BATTERY_STATUS_BASIC in the my_config.h in the wled00 folder than it should work or am i wrong... i tryed several thing but noting work... what happens when i put in the line and build and flash , after flashing the board resets as expect but never start up or turn on.. only thing i see is 1 led on my strip is bleu..

can sombody piont me the right direction.

**Comment by blazoncek** [comment]
Please contact original usermod author or use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
