### ISSUE TITLE
Non addressable LEDs with Alexa

### ISSUE THREAD

**Issue by dasch3a** [Aircoookie/WLED#2677]
Hi,

I'm trying to control an analog 12V LED Strip via Alexa. Everything works perfectly fine but there is an assue after rebooting. In the LED Preferences I used PWM White to control the Mosfet. Unfortunately I have to set the White Channel slider to max after every system reboot. Is there a solution so that I don't have to do this after every reboot?

Kind regards,
David

**Comment by blazoncek** [comment]
Save a preset.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
