### ISSUE TITLE
Ändern von LEDs Status im Usemode

### ISSUE THREAD

**Issue by trebur** [Aircoookie/WLED#2678]
Hallo zusammen,
Ich benutze WLED als portable Anzeige für Überwachung der Aktivitäten meiner QNAP NAS Server derzeit 5 Stück. Jedem Server wird eine LED zugewiesen und jedem Status eine bestimmte Farbe und einer bestimmte Aktion ( Unbekannt weis, Aktiv grün,gestoppt blau , Fehler rot, Backup von einem NAS auf ein anderes NAS : beide LEDs blinken)
Soweit so gut , da ich das ganze mobil machen wollte betreibeich  das ganze über Accus betreiben.  Da ich nur den Status brauche wenn ich in der Nähe bin habe ich mir ein Usermode geschrieben der WLED in Deep Sleep versetzt und über einen Bewegungsmelder für bestimmte Zeit (einstellbar) wieder aufweckt.  Funktioniert gut. Nun  muss ich aber die Status der NAS Server extern ablegen und beim Starten vom WLED einlesen.
Meine Idee wäre eine SQL DB oder SMB Share, aber wie kann man ‚schmerzlos‘ (analog der JSON API) die LED’s Status innerhalb eines Usermodes ändern. Oder gibt es andere Ideen ?

**Comment by blazoncek** [comment]
handleOverlayDraw()
This method is called after all LEDs have been written to, but not yet displayed. Implement this function in usermod and overwrite any pixel you want with setPixelColor(index,color).
WARNING: ledmaps are not supported in callback routine.

**Comment by trebur** [comment]
Hi softhack and blazonzeck,
thanks for the quick answer  I know the handleOverlayDraw()  I use it to set the brightness to 0 before i go in the Deep Sleep.
But what I need is not only to set color of a led but also  effects like blinking  and bouncing beetween leds. Therefore i ask something like JSON API ( with segments)...

**Comment by blazoncek** [comment]
Even though it may work, JSON API is not (yet) intended for such case.
I would recommend against such practice as it may interfere with WLED behaviour.
