### ISSUE TITLE
Color after power lost

### ISSUE THREAD

**Issue by pepsonEL** [Aircoookie/WLED#2679]
Hi
I have connected to NodeMCU on ESP32 my led strip. After power lost and again power led no turn on. but when turn on led by app or button it turn ON in always color ORANGE. Is any chance to change this start color? 
When i change and power no unplug , when turn on and turn of and again turn on color is my setup. Only when power was lost color is no remember.,

**Comment by blazoncek** [comment]
Use presets and consult [knowledge base](https://kno.wled.ge).
Please use WLED [forum](https://wled.discourse.group) or Discord for help or support questions.
Closing.
