### ISSUE TITLE
EEPROM.put

### ISSUE THREAD

**Issue by anarchking** [Aircoookie/WLED#268]
Was looking over the code and was wondering if it would be a good idea to change EEPROM.write to EEPROM.put? It's only supposed to write if it's being updated. If it's the same value it stays the same, less stress on EEPROM

**Comment by Aircoookie** [comment]
Don't worry, there is only a single write cycle per settings saved. On ESPs, EEPROM.write() doesn't actually write to flash but to a RAM buffer, so there should be no difference!
Only the one EEPROM.commit() call will actually save everything in one go.
