### ISSUE TITLE
Preview effect in UI

### ISSUE THREAD

**Issue by Dschogo** [Aircoookie/WLED#2688]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Preview the effect in the UI like in the Main page with the colors under the buttons.
So something like this, but then correctly animated to the correlating effect.
![image](https://user-images.githubusercontent.com/36862419/173183076-0812f3ab-27dc-43e2-ac59-32959c7dbc56.png)

**Additional context**
Not sure if that's achieveable without rewriting all the effects in js for the UI. 

Anyways, extremely cool project :D

**Comment by blazoncek** [comment]
Not possible since effects are written in C language.
There is a rendering of effects on https://kno.wled.ge
