### ISSUE TITLE
HUE Sync Ambilight+HUE

### ISSUE THREAD

**Issue by andre-bu** [Aircoookie/WLED#2689]
### What happened?

Hello, I have a problem with the HUE synchronization. I also paired my Philips Ambilight TV with the bridge. I have the following structure. My Ambilight TV syncs 2 PlayBars. My WLED lamps sync with these playbars. For a few days now I've had the problem that WLED is no longer synchronized with the PlayBars as soon as the TV is switched on. It has worked flawlessly for almost a year now.
Have tried different WLED versions. Version used is 0.13.1

### To Reproduce Bug

-

### Expected Behavior

-

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
