### ISSUE TITLE
nonPWM White (or RGB(CCW))

### ISSUE THREAD

**Issue by roboraptor** [Aircoookie/WLED#2691]
**Is your feature request related to a problem? Please describe.**
Sometimes i want to control a relay with just ordinary lightbulb socket or something and using "PWM White" on relay input is not really a nice/working solution.

**Describe the solution you'd like**
In LED Preferences ->Add Segment -> Led Type: 1/0 White
On "Controls" page when segment is choosen -> Some kind of ON/OFF switch (instead of dimming slider)

**Describe alternatives you've considered**
I tried to use presets on the segment but it didnt really satisfied me with the ease of use.

**Additional context**
This switches can be added even to RGB or CCW. 
I know it will lack the transition and fading but sometimes it is not really the thing you actually need.

**Comment by blazoncek** [comment]
You can use Multi Relay usermod.
Then create presets to control individual relay.
https://kno.wled.ge/features/relay-control/

**Comment by roboraptor** [comment]
And when I don't want to use presets?
Because I can already use presets with pwm0% and pwm100%...

**Comment by blazoncek** [comment]
I am a bit intrigued how you use WLED without presets to be honest. But to each its own, as they say...
If you can code, you can enhance `bus_manager.h` to implement BusOnOff since WLED already knows about such output.
If not, you can try to find someone who can and have them make a PR. There is no immediate plan to do that from our side.

**Comment by roboraptor** [comment]
Ok, I need to say I'm sorry.
There is actually an easy accessible button for relay in multirelay usernod. Just inside the info section.
That's pretty neat. I just had to spend tedious hours of fighting with patformIO and try it for myself.
I actually use presets. But sometimes it is easier to just have some buttons on front page to just do one thing.

**Comment by blazoncek** [comment]
BTW I have implemented BusOnOff since it was rather trivial.
It is available in source from my fork (currently in audioreactive branch) where most of development is done. @srg74 also has recent binaries in his Weomos shield repository (experimental folder).

Controlling relay from preset is describe in KB on link I provided above.

**Comment by roboraptor** [comment]
Sound Reactive... That is also the place where I am trying to get.

I will try your branch, thank you :)

**Comment by blazoncek** [comment]
Not SoundReactive. That is another fork, completely separate not maintained by me.

**Comment by roboraptor** [comment]
And is SR like "friendly" fork at least? You know like discussing and sharing ideas? Or totally different like "not going to touch that"

Ad your implemented busonoff, is it only in the bus_manager.h?

**Comment by TysTies** [comment]
could one of you send a link to that audioreactive branch? a can't find it.

**Comment by blazoncek** [comment]
just grab 0_14

**Comment by TysTies** [comment]
I don't know what you mean I'm new to github. can you just send me a link?

**Comment by blazoncek** [comment]
Join Discord lot's of people there. Very helpful.
And you'll get binaries there.

**Comment by TysTies** [comment]
I can't I don't have a phone and I'm on a school computer.

**Comment by blazoncek** [comment]
https://github.com/srg74/WLED-wemos-shield/tree/master/resources

**Comment by TysTies** [comment]
Thank You!!!
