### ISSUE TITLE
Basic colors palette for spotlight effect

### ISSUE THREAD

**Issue by roboraptor** [Aircoookie/WLED#2696]
**Is your feature request related to a problem? Please describe.**
I'm missing a palette with basic colors.

**Describe the solution you'd like**
I would like you to add this to palettes.h

> // Gradient palette "cz_spotlight_basiccolor".
> // Custom palette by Roboraptor
> // Size: 42 bytes of program space.
> const byte cz_spotlight_basiccolor[] PROGMEM = {
>     0, 255,  0,  0, //red
>    36, 255,  0,  0,
>    37,   0,255,  0, //green
>    72,   0,255,  0,
>    73,   0,  0,255, //blue
>   108,   0,  0,255,
>   109, 255,255,  0, //yellow
>   144, 255,255,  0,
>   145,   0,255,255, //cyan
>   180,   0,255,255,
>   181, 255,  0,255, //magenta
>   216, 255,  0,255,
>   217, 255,255,255, //white
>   255, 255,255,255};
> 
>   cz_spotlight_basiccolor,      //??-?? Basic Colors

 
**Describe alternatives you've considered**
I wanted to make a PR but still new to this... I am sorry.

**Additional context**
Thank you!

**Comment by blazoncek** [comment]
Custom color palettes are going to be part of the upcoming 0.14 release.
You will be able to create and use up to 10 custom palettes by uploading JSON files.
