### ISSUE TITLE
Fade on/off

### ISSUE THREAD

**Issue by thespirit101** [Aircoookie/WLED#270]
WOW! - great job with the project and interface, love it and already planning my xmas lights, i have one question, all was going smoothly until yesterday, my strip no fades on and off, there is a delay of around 10 secs after cycling when it just used to switch on and off with the button press, have I inadvertently changed a setting? cant see anything obvious 

Cracking job Aircoookie - you rock!

Stay well 
C

**Comment by brentbrooks70** [comment]
@thespirit101  What is the value listed in **Settings -> LED Preferences -> Transitions** _Transition Time_ and is _Crossfade_ checked?

**Comment by thespirit101** [comment]
Thanks so much, you are of  course correct, no idea why it was suddenly checked, but thanks for the prompt, much appreciated
