### ISSUE TITLE
H801 with release 0.13.1

### ISSUE THREAD

**Issue by dirk99** [Aircoookie/WLED#2701]
### What happened?

The H801 was flased with webtool and NodeMCU Py flasher. in both cased thep was ereased. After Reboot the WLAN AP was active an i can configure my WLAN. After configure trhe WLAN the H801 connect to my WLAN and runs. After the next boot the configuration was lost. 
The H801 ist powered  by an ESP8266 with 1MB.

### To Reproduce Bug

configure WLAN an reboot the device with power down and up

### Expected Behavior

reboot

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use correct binary for units with 1MB of flash memory.
