### ISSUE TITLE
Segements are not perfectly synced

### ISSUE THREAD

**Issue by derpeter** [Aircoookie/WLED#2702]
### What happened?

I have a strip physically cut into 4 equal parts (each 11 LEDs) and with the data lane going connected. 
The for strips are mounted on each side of  square shaped peace of wood inside a round lamp.

When i configure them as 4 segments effects e.g. rainbow are not perfect aligned. 
I can achieve a perfect alignment by just connected D to all 4 strips in parallel an tell wled there are only 11 LEDs. But of course this limits the possibilities and also e.g. messes up the power consumption calculation. 

Is there a way to achieve perfect alignment with this with segments? If not it maybe useful to allow to tell WLED of parallel connected strips

### To Reproduce Bug

Put at least 2 strips connected in serial next to each other, configure them as 2 segement, revers the order of the second strip. Run e.g. rainbow effect

### Expected Behavior

Both strip are in sync 

### Install Method

Self-Compiled

### What version of WLED?

WLED version 0.13.2-a0

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
No, this is not possible except by rewriting all effects (which is impractical).

**Comment by derpeter** [comment]
Thanks for the quick response. Is there any where more information on this ? Tip on this page https://github.com/Aircoookie/WLED/wiki/Segments sounds to me as this very feature. Sorry i probably miss something here.

**Comment by blazoncek** [comment]
Not all effects behave in a way to be completely symetrical following this procedure. Some will some won't.

Each segment is treated independently and effects are drawn on them one segment at a time. As time passes drawing one effect a starting point may have changed for the second (and so on).

**Comment by blazoncek** [comment]
You can do that using ledmaps and grouping in segments.

**Comment by derpeter** [comment]
great, seems i missed that will look into it!
