### ISSUE TITLE
Major kudos.

### ISSUE THREAD

**Issue by epiller** [Aircoookie/WLED#2706]
I've put off implementing this project on my ESP8266's with addressable RGBs for way too long (thinking what I had before was alright) and today I installed it and I'm in absolute **awe** how advanced this piece of software is.  
Speaking as an embedded developer (and after looking at the source code) it's absolutely amazing how much features you managed to pack into this thing **and** make it as bug-free as is (so far 😁) with such a beautiful interface.  

**Seriously, hats off to all developers involved and especially @Aircoookie**  

P.S. Sorry for writing this in issues, didn't know where else to put it and I had to say something.

**Comment by blazoncek** [comment]
You can use WLED [forum](https://wled.discourse.group) or Discord where community is gathered.
And thank you for kind words.
