### ISSUE TITLE
PIR - Sensor ONLY without control of WLED

### ISSUE THREAD

**Issue by poldim** [Aircoookie/WLED#2707]
I'm trying to pull in two PIR sensors that are connected to an ESP32 into home assistant as sensors only.  I don't want them to do anything to the state of the lights of the WLED ESP32 itself.  Basically, just provide the data to HA.  I looked in the docs, wiki, and general google without any luck.

Sensor config:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/16869713/176975010-6dd1b796-ec5d-419b-a307-1d88b26fcd23.png">

I tried adding the WLED device in HA but no motion sensors are present.

On Discord I was told this has to be setup through MQTT.  I configured MQTT but still no motion sensors are present.
<img width="145" alt="image" src="https://user-images.githubusercontent.com/16869713/176975142-8c0f2130-a069-48e1-aa9f-fbdf464ddc21.png">

This was done on version:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/16869713/176975204-87892456-5c22-41c3-aa1f-d18295a675c4.png">

**Comment by blazoncek** [comment]
Discord or [forum](https://wled.discourse.group) is a proper place for questions.
You need to set presets that do nothing and enable button MQTT broadcasts in Sync settings.
Closing.
