### ISSUE TITLE
Animated Staircase

### ISSUE THREAD

**Issue by 1damo1** [Aircoookie/WLED#2712]
Hi Everyone,

im tinkering with Animated staircase currently doing some renovations to the house and would love to implement this to the stairs!

I'm having some issues with getting it to work currently, it doesnt seem to remember the in the config usermods sections the options, im using an ESP32.

I've been able to send requests with the json lines to turn the LEDS ON & OFF, enable and disable the usermod, ive also made the 12 steps that i plan on putting it on.

![Info Screen](https://user-images.githubusercontent.com/107168701/178140508-00463696-0fa9-4a66-bdf4-c2a3785c4f24.png)

![usermod settings](https://user-images.githubusercontent.com/107168701/178140525-f69b3be7-d7e5-4faf-a600-951453843dcb.png)

I have tested the PIR Sensors and they appear to be working, ive currently have them sitting on Pins 4 & 5, ive uninstalled and reinstalled WLED a couple times to see if that would fix it.

Thanks!

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Check for pin conflicts when saving configuration.
Closing.
