### ISSUE TITLE
Add WRGB color order for SK6812 and similar.

### ISSUE THREAD

**Issue by cmgreenman** [Aircoookie/WLED#2713]
Hello,
    I recently purhcased some WRGB floodlights from Wally's Lights for use with WLED/FPP/Xlights, however, I found that WLED will not let me define the correct color order (WRGB).  As such the effects do not display correctly nor does the white channel.  Would it be possible to add WRGB (and other white first variants) to the list of color orders?

Thanks,
Chris

**Comment by blazoncek** [comment]
This has been already requested in #2646 and will be fixed in #2610

**Comment by cmgreenman** [comment]
Awesome.  Sorry for the dup.  I didn't find any reference to wrgb in my searches

**Comment by blazoncek** [comment]
Fixed in #2737
