### ISSUE TITLE
Unable to save LED settings

### ISSUE THREAD

**Issue by mcpacific** [Aircoookie/WLED#2727]
### What happened?

I'm running WLED on QuinLED's Dig-Quad with ESP32. Under LED preferences, I selected WS281x, 589 pixels, 12V (30mA), RGB, then click Save. It responds with "LED settings saved". However, if I go back in it reverts to 30 pixels, GBR.

### To Reproduce Bug

Do exactly what I did, as explained above.

### Expected Behavior

It should save the settings.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This has been resolved in a8908238d5e8c0aafb2f603168a193b86338e169.
Download source and compile yourself or use Discord bot to compile from latest source.
Closing.
