### ISSUE TITLE
4 line display user-mod - not cycling 

### ISSUE THREAD

**Issue by kgreene1983** [Aircoookie/WLED#2731]
### What happened?

Not sure if you allow user mods bug in here but. 

The 4th line displayed on OLED displays cycles through various bits of information every 5 secs. However, if sleep mode is deactivated the information is stuck on brightness. 

### To Reproduce Bug

Untick sleep mode in user mode, information stops cycling straight away. 

### Expected Behavior

Expect the information to cycle through if sleep mode is on of off. 

### Install Method

Self-Compiled

### What version of WLED?

0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Pleas use ALT usermod. Non-ALT is not maintained.
