### ISSUE TITLE
Make the Tetrix effect fade out at the end

### ISSUE THREAD

**Issue by ToXIc-Dev** [Aircoookie/WLED#2741]
Is your feature request related to a problem? Please describe.
When the Tetrix effect gets to the end, it just flashes the whole strip back to the second color.

Describe the solution you'd like
Fade into secondary color when end reached, I'm using mine as a slow sand timer and it will be more calming if it fades rather than flashes

Describe alternatives you've considered
N/A

Additional context
N/A

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Added in https://github.com/blazoncek/WLED/commit/22bc3dac2d758734f8247e762499c8eff58e9d3a
The fade out time is fixed to 2.5s
Will be available in 0.14.
