### ISSUE TITLE
Update required: Differences between platformio.ini and usermod docs

### ISSUE THREAD

**Issue by microraptor** [Aircoookie/WLED#2742]
**Is your feature request related to a problem? Please describe.**
In `platformio.ini` there is this commented section for additional libraries:

```ini
  #For use SSD1306 OLED display uncomment following
    #U8g2@~2.27.2
  #For Dallas sensor uncomment following 2 lines
    #OneWire@~2.3.5
    #milesburton/DallasTemperature@^3.9.0
```

However, `/usermods/Temperature/readme.md` states this:

```ini
...
lib_deps =
  ...
  #For Dallas sensor uncomment following line
  OneWire@~2.3.5
...
```

Depending on if` milesburton/DallasTemperature` is actually required for the usermod, it should be added or deleted from the other file. In `platformio.ini` it was added as a dependency with this commit:
https://github.com/Aircoookie/WLED/commit/d975f6e23aac825f89415e12283ce7d0be7d717b

I have read there were some issues with the temperature usermod making leds flicker. If this is still the case, this should probably be mentioned in the usermod readme.

Similarly, the documentation for the four-line-display usermod states the `Wire` library is required and lists `Wire` as a dependency in the example, which is not present in `platformio.ini`. So one of the two probably should also be updated.

The example for the four-line-display usermod configuration at `/usermods/usermod_v2_rotary_encoder_ui/platformio_override.ini.sample` pins a lot of core libraries to versions from over a year ago. Is this still the recommended way of configuration?

See here:
https://github.com/Aircoookie/WLED/blob/main/usermods/usermod_v2_rotary_encoder_ui/platformio_override.ini.sample

Edit:
In the readme of the rotary encoder usermod, it should also be mentioned that the Alt-UI flag should be used since the original one is unmaintained (see #2731 ). According to the discord stickied build environments the milesburton/DallasTemperature is not needed for the dallas temperature mod anymore. It seems defining the Wire library as an additional requirement is not necessary, because U8g2 already lists it as a dependency.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I don't actually have my ESP yet, so I don't know if the usermods actually work at all with current WLED versions. In a few weeks I probably do my WLED build and test the libraries requirements.

**Additional context**
Thanks a lot for your work on this great firmware!

**Comment by softhack007** [comment]
Usermods are not maintained by the core WLED team, but they are under responsibility of the usermod authors. If you have a fix/improvement for a usermod, please make a PR.


> documentation for the four-line-display usermod states the Wire library is required and lists Wire as a dependency.

Since 0.14.0-b1 it is not necessary any more to add `Wire` to lib_deps, as wled.h now also pulls in the necessary dependency. This is also true for other usermods that use I2C.
