### ISSUE TITLE
Webinterface unreachable

### ISSUE THREAD

**Issue by TiRaNy4u** [Aircoookie/WLED#2754]
Dear people, 

I have Wled on and ESP32 and it worked fine for at least 6 month's. It's also addressed via Home Assistant. Now I have the problem that I can't access my Wled config using the webinterface. I have set a fixed IP and when doing an IP scan it tells me it's not responding. On Home assistant I can see the Wled and I can control it from there. I can change colors and I see it's updated to 0.13.2. Manually pinging the IP also resultst in 100% loss. When doing the IP scanner I can not find it on any other IP. (already tried power off and power on but no help). Is there a way that I can reset this and start over without flashing it again? Or what would be a solution for this? I didn't need to access the web interface for a long time, so I don't know since when this problem is there. Since the led strip alway's did what I asked via Home assistant and that it updated to the recent 0.13.2.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
