### ISSUE TITLE
Name iconsitancy when integrating with Homeassistant

### ISSUE THREAD

**Issue by SomeAssembly** [Aircoookie/WLED#2758]
### What happened?

When the entries are made in Homeassistant by autodescovery; the friendly name for both segment-0 and segment-1 both show "friendly_name: WLED Segment 1 Intensity". Segment 0 should show as "intensity 0". Not a big thing but did confuse me.

### To Reproduce Bug

Autodiscover a new WLED instance in homeassistant.

### Expected Behavior

Segment-0 intensity should show as friendly_name: WLED Segment 0 Intensity

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.2 (build 2208140)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This may be an issue of HA integration, not WLED, as WLED does nothing to inform HA of its presence (except for the usermods).
