### ISSUE TITLE
Firefox missing slider hints in web app

### ISSUE THREAD

**Issue by tomlut** [Aircoookie/WLED#276]
The colour strips under the sliders that identify their purpose are not visible in firefox . Works fine in chrome and safari. But looks like this in firefox 69.0.3:

![WLED](https://user-images.githubusercontent.com/10679300/67492790-b149c180-f6c2-11e9-8b15-9c554d00f22f.png)

**Comment by Aircoookie** [comment]
Hi, thank you for the report :)
Seems like Firefox updated their rendering recently, the way these sliders were displayed always seemed a bit off.
I likely won't be fixing this issue as the classic UI will be replaced by a new unified UI in the next major version.

**Comment by tomlut** [comment]
It's not a major issue as I mostly use the iOS app. As you have plans to fix this in the next release I'll close the issue.

Thanks for this excellent software and support.

**Comment by HimbeersaftLP** [comment]
Would you still accept a PR that fixed the issue?
