### ISSUE TITLE
possible to split 1 strip into multiple light entities from 1 controller?

### ISSUE THREAD

**Issue by rchiileea** [Aircoookie/WLED#2762]
**Take a look at the wiki and FAQ, perhaps your question is already answered!**
[FAQ](https://github.com/Aircoookie/WLED/wiki/FAQ)

**Please consider asking your question on the WLED forum or Discord**
[Forum](https://wled.discourse.group/)
[Discord](https://discord.gg/KuqP7NE)
[What to post where?](https://github.com/Aircoookie/WLED/issues/658)

**If you do not like to use these platforms, delete this template and ask away!**
Please keep in mind though that the issue section is generally not the preferred place for general questions.

So I am not sure if this is the right place to post this, I want to make my son a moon lamp (real representation of the moon) combined with home assistant, is there a way via the software to say split one strip and only have lights 1-5 as one light , 9-14, as a second 18 - 23 as a 3rd ect ect... basically seperate the strip into 6 individual lights in home assistant?

or is this not possible 
![moon phaze plan](https://user-images.githubusercontent.com/87599807/186086274-846869dd-9c9b-4b97-aa92-9314ef225786.jpg)

rough idea of what i am talking about, my reasoning behind this is it would enable me to make a custom automation to make the lamp or light sync with moon phases.

**Comment by blazoncek** [comment]
You can use segments for such purpose in WLED. How they map to HA is a question for HA team.
Consult [KB](https://kno.wled.ge) for details about segments.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
