### ISSUE TITLE
Everything syncing except white balance

### ISSUE THREAD

**Issue by conkydong** [Aircoookie/WLED#2770]
### What happened?

I'm using 5 bare ESP32-WROOM-32 (47uF capacitor between GND and 3v3, 10k resistor between EN and 3v3), each soldered to an LED driver (desoldered the original WB2S chip) of a ceiling light and set all GPIOs to the right pins (B to 14, R to 12, G to 13, Cold White to 5, Warm White to 4). 
Now when I want to sync the lights everything is syncing except the white balance. If I the lights are set to cold light and I change them to warm and vice versa only the light I'm controlling is changing.

### To Reproduce Bug

See Problem.

### Expected Behavior

See Problem.

### Install Method

Self-Compiled

### What version of WLED?

every version

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
Hi!
Sync should fully support white balance syncing.
Please check that the settings in the "White management" section in LED settings are the same on both units.
I don't believe it would make a difference, but you can try if enabling "Segment options" in the "Receive" section of sync settings helps.

**Comment by conkydong** [comment]
I don't know what I'm doing wrong but nothing works even though the settings are the same on every light.

**Comment by imtoanle** [comment]
I got this issue too. My board is ESP32 Mini (ESP32-WROOM-32).
I using PWM+CCT strip. RBG and White channel sliders worked but White balance is not.
I tried all things from sync config menu.

<img width="341" alt="Screen Shot 2022-11-01 at 21 16 16" src="https://user-images.githubusercontent.com/4002252/199254718-d751b735-078f-4535-8fd9-26e79616809b.png">

**Comment by blazoncek** [comment]
Please post your white balance/white correction settings and sync settings.

**Comment by blazoncek** [comment]
No response received, closing.
