### ISSUE TITLE
WLED android app crashes when discovering lights

### ISSUE THREAD

**Issue by chrismeg** [Aircoookie/WLED#2772]
I'm running a Pixel 6 with android 13, and everytime I open the WLED app and hit Discover Lights the app crashes. 

Is this a known bug?

**Comment by blazoncek** [comment]
Please open an issue with WLED phone app, not WLED as these are two different products.

**Comment by chrismeg** [comment]
My apologies!

**Comment by Aircoookie** [comment]
Tracking in https://github.com/Aircoookie/WLED-App/issues/23
