### ISSUE TITLE
Extracting led mapping file

### ISSUE THREAD

**Issue by darksworm** [Aircoookie/WLED#2780]
I've set up a custom led mapping a long time ago on my wled device as per instructions https://github.com/Aircoookie/WLED/wiki/Mapping

And am about to migrate it to a different microcontroller, but have forgotten the password to enable wireless OTA.

Is there any way to extract the led mapping file without enabling wireless OTA?

**Comment by Aircoookie** [comment]
Access to the /edit page is disabled when OTA is locked, however you should be able to retrieve your mapping by going to `[WLED-IP]/ledmap.json`.
