### ISSUE TITLE
Cannot adjust number of LEDs on version 13

### ISSUE THREAD

**Issue by jjcustomz** [Aircoookie/WLED#2783]
Starting with version 13, I can no longer adjust the total number of LEDs. It shows the total number of LEDs that were previously set, but there is no text box to adjust, only the text. This has been present in all 3 v13 firmware, either with a manual OTA update or through home assistant. I have not tried to flash the module directly with the computer. Rolling back to v12 again allows the total number of LEDs to be adjusted.

**Comment by Aircoookie** [comment]
Instead of setting the total number of LEDs, in v13 you now set the number per output bus (slightly below the total LED count). This is so that if you change the count you won't have to update it twice :)
