### ISSUE TITLE
Is it possible to adapt WLED for the shape of a snowflake from a ribbon?

### ISSUE THREAD

**Issue by timof123** [Aircoookie/WLED#2786]
I want to use this firmware for homemade snowflakes from WS2812B LED strip. The fact is that many effects (for example, "Chase") do not look quite correct due to the peculiarities of connecting the tape. Is it possible to change the default LED sequence in the firmware? That is, I need, for example, LED #1 in the firmware to be equal to the physical LED #12; #2 equaled #13, and so on. Is it really possible to do this?

**Comment by blazoncek** [comment]
Please use [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing

**Comment by Aircoookie** [comment]
https://kno.wled.ge/advanced/mapping/

**Comment by sansillusion** [comment]
Look into ledmap
I never used it but saw it was implemented a while ago.
