### ISSUE TITLE
DDP output hostname instead of IP

### ISSUE THREAD

**Issue by roboraptor** [Aircoookie/WLED#2798]
**Is your feature request related to a problem? Please describe.**
Having Wleds on network with changing IPs.

**Describe the solution you'd like**
Possibility to set hostname instead of IP address, when setting up DDP output for different WLED nodes.

**Describe alternatives you've considered**
Setting up static IPs but that would not work when carrying the lights around.

**Comment by Aircoookie** [comment]
Resolving a dynamic IP from the hostname is probably not feasible, but doing so from the mDNS address should work. 
However, this requires storing the mDNS name string in the network bus.

**Comment by roboraptor** [comment]
So, it would be possible?
It would be very helpful when moving lights around every second week.

**Comment by blazoncek** [comment]
Possible, yes, feasible, no.

**Comment by roboraptor** [comment]
Not even the mDNS?
