### ISSUE TITLE
Multi Relay usermod not working on GPIO 1 and 13 not

### ISSUE THREAD

**Issue by neoceraea** [Aircoookie/WLED#2799]
### What happened?

- Olimex ESP32-PoE board
- Custom Build with USERMOD_MULTI_RELAY
- Configured relay pin to 1 or 13
- Control Relay via MQTT

Pin 1 (or 13) is always High (3.3V), regardless of the control "On"/"Off"
(when using other pins, these react according to the control)

### To Reproduce Bug

- Custom Build with USERMOD_MULTI_RELAY
- Configured relay pin to 1 or 13
- Control Relay via MQTT

### Expected Behavior

Pins should show high/low polarity depending on control "On"/"Off"

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.3 2208222

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
GPIO1 may be used by serial interface.
GPIO13 was never tested though there are no reasons not to work.

**Comment by blazoncek** [comment]
Tested this last night. On bare ESP32 both GPIO1 and GPIO13 *are* working so the above may be Olimex board shortcoming.
