### ISSUE TITLE
Compatibility with FastLed patterns

### ISSUE THREAD

**Issue by nbietz** [Aircoookie/WLED#28]
I would love to see your project work with Mark Kriegsman's (kriegsman) FastLed patterns, especially Pride (https://gist.github.com/kriegsman/964de772d64c502760e5). Do you know of a way to easily port FastLed patterns to NeoPixel, or vice/versa? Thanks!

**Comment by StormPie** [comment]
FastLED sure has some nifty effects, some people have achieved a hybrid of FastLED and WS2182FX here https://github.com/kitesurfer1404/WS2812FX/issues/78
Note there's an issue with RGBW, which means for me this isn't a viable option but @Aircoookie knows of FastLED and is definitely keen to get some of the effects into WLED 😄
