### ISSUE TITLE
E1.31 connection laggy with more than 1 device

### ISSUE THREAD

**Issue by Keyes** [Aircoookie/WLED#2801]
Hey there! 

When I try to control one device with a small number of LEDs (up to 32 in my case) everything works fine. As soon as I add more devices to the network, the effects/changes start to get choppy/laggy. Looks like they don't receive stable ~30 fps anymore, but go often down to <10. 

Tested with both ESP32 and ESP8266, same results.

Is this a known issue, and is there a way to fix this?

I tried disabling/enabling Wifi sleep and multicast, but no change. Also having both at the same or completely different DMX start addresses doesn't change anything. 

I also tested also multiple different wifi setups:
- both at my home network with lots of other devices and a newer fritzbox router
- both in the same network with a small dlink router, only together with my control laptop to send the E1.31 signal
- one ESP32/8266 opening the network, and everyone else connecting to that
- different distances between the devices and the router

As a controller I'm using right now a M1 MacBook Pro 10core with "Lightkey".

I also tried using LedFX, but it's exactly the same result: as soon as I'm controlling two or more devices at the same time, the effects become laggy.

**Comment by blazoncek** [comment]
Yes, the solution is called Ethernet.

**Comment by Keyes** [comment]
Could you please elaborate a bit more on the reasons and problems here, before closing it?

- Why does it work properly with just one connected WLED device?
- Why does it get laggy after adding a second one?
- What is the source of problem, when the main WiFI network has more than enough capacity to deliver to theoretically 100 devices, and other E1.31/ArtNet devices work properly (but are turned off during the tests)?
- If both ESP32 and ESP8266 do have the exact same problems, it's not caused by their lack of power, since the ESP32 has way more, correct?

I'm just trying to understand what exactly is the problem in this setup, and if WLED is one of them :)

**Comment by blazoncek** [comment]
Have you tried Ethernet? You did not provide any feedback.

WiFi and UDP packets are an area you can waste life diagnosing issues.

My own testing while developing code were successful without any "lagginess" with 3 to 4 devices. What may cause "lagginess" is WiFi congestion or poor reception as well as poor TCP/IP stack implementation. ESP devices are known not to have the best WiFi stack implementation. Another area may be your host computer, etc, etc.

As I cannot reproduce what you are seeing and you not providing any feedback, I decided to close the issue.
You are free to reopen if you have valuable diagnosing data to help resolve the issue in the future.
