### ISSUE TITLE
Add simple GPIO Control

### ISSUE THREAD

**Issue by wuast94** [Aircoookie/WLED#2810]
**Is your feature request related to a problem? Please describe.**
I have build my own ceiling lamps, they have an led stripe inside and 4 spot lights controlled by 4 Relays.
LED works fine but i cant controll the Relays

**Describe the solution you'd like**
Add a simple GPIO option to the LED output type. Then set my Pin and if its reversed. 
As controll a simple toggle switch.

**Describe alternatives you've considered**
I tryed the MULTI_RELAY usermod but there the lights are handled as 1 light so every time i turn on the led´s the 4 spot lights turn on too.

I Also tryed setting the gpio high or low with PWM Led but thats nothing near a solution for me, just a very very dirty workaround

**Additional context**
its important for me to controll it through home assistant 

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Mark each relay as EXTERNAL in usermod settings and then you can control each one individually (JSON API, MQTT or HTTP).
Please use WLED [forum](https://wled.discourse.group) or Discor for help and support questions.
Closing.
