### ISSUE TITLE
Effects not working with JSON API

### ISSUE THREAD

**Issue by cylon147** [Aircoookie/WLED#2815]
### What happened?

I am trying to set the effects using JSON API but somehow the Effects are not changing I am getting the success Replay from Server but it's not executing the Effects.

### To Reproduce Bug

Send JSON API Command
`{"effects":["Flow"]}`

### Expected Behavior

The Effects should change.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 (2208222)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use official JSON API available at https://kno.wled.ge/interfaces/json-api/
Closing.

**Comment by cylon147** [comment]
What is the API syntax for setting Effects via JSON API? The Documentation is not clear about this. Please Help.

**Comment by blazoncek** [comment]
Serialized JSON. No special tricks there.

**Comment by cylon147** [comment]
I have tried sending `{"effects":["Blink"]}` both as JSON and Text but none is working.
I do get `{"success":true}` response from the server but the effect is not getting Executed.

![image](https://user-images.githubusercontent.com/5562285/194694593-3eef688b-acf4-4882-8aaf-2f54711f1188.png)


![image](https://user-images.githubusercontent.com/5562285/194694622-f94ef341-f61b-427a-b484-e43371e93a19.png)

**Comment by blazoncek** [comment]
As said above: Use official API as described in KB.
Also, use your browser's developer tools to observe WLED UI submitted commands.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.

**Comment by sn1ce** [comment]
Hi there,

i am also struggling, since its not working for me neither.
A simple " you need to do it like this" would help, since not all of us are familiar with json and stuff.

In my case, i wanted to use toggle next effect, i am able to do it with HTTP API (easy one##   /win&A=160&FX=~   ), but not able to make it with the json API.

Helping out here, much appreciated. 

sn1ce

**Comment by sn1ce** [comment]
@cylon147 
Hi again,

I was able to set it up to "Flow" with  the following, {"seg":[{"fx":"110"}]}
Make sure, you check on "your.ip.of.wled/json/eff ; there is a newline after the 10th entry, so you can count to your effect you want to have :-) 

Cheers
