### ISSUE TITLE
WLED CODE FLOW

### ISSUE THREAD

**Issue by Gpadhiyar** [Aircoookie/WLED#2817]
I am a beginner at this project structure. So, I do not understand the project structure or project workflow. I do not understand how to communicate applications to ESP32, how to send and receive data from an application to ESP32, and ESP32 to an application. I tried my best to understand the working process of WLED, but I didn't.

Please provide me with some workflow or guidance for understanding the working process of the project.

**Comment by Aircoookie** [comment]
Hey, I'm not sure what you mean with project structure or workflow. If you are looking to make an application that communicates with the WLED ESP32, check the JSON API documentation: https://kno.wled.ge/interfaces/json-api/

**Comment by blazoncek** [comment]
Other than what @Aircoookie said, join the Discord or [forum](https://wled.discourse.group) where friendly people will help you get started.

**Comment by Gpadhiyar** [comment]
If i am mack coustom application then which perameter send to esp32

**Comment by blazoncek** [comment]
Please use forum or Discord.
