### ISSUE TITLE
http or json api hedder file function

### ISSUE THREAD

**Issue by govind183** [Aircoookie/WLED#2823]
thank you for your reply ,
can you share some more details about which header file or function is use for this http or json api.
for better understanding for me.

_Originally posted by @govind183 in https://github.com/Aircoookie/WLED/issues/2822#issuecomment-1272873130_

**Comment by blazoncek** [comment]
Please stop abusing Github issues for support questions.
As instructed please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Please get familiar with [KB](https://kno.wled.ge) as well.
