### ISSUE TITLE
Flicker with too many segments defined

### ISSUE THREAD

**Issue by Fast-T** [Aircoookie/WLED#2826]
Hi there,

I have a 2D pixel matrix with 200 pixels built and use it for Xlights animations. I'd also like to use it with "traditional" WLED effects.
The pixels are wired in a stair pattern with 20 columns each having 10 pixels. 
While normal operation with 1 segment covering all pixels, the effects run smooth. Xlights does run 2D effects without issues. So I can rule out electrical issues here. Once I define a segment for each column (total of 20) running effects makes the display flicker from times to times

https://user-images.githubusercontent.com/77162005/194944524-079f6cef-ae35-4759-bb94-3c68765166f8.mov

. When I reduce the segments to < 10, the issue disappears.

Can someone please look into this?
Thanks

**Comment by blazoncek** [comment]
You may have overlapping segments.
Please update to 0.14 beta as it supports matrices and 2D.

**Comment by Fast-T** [comment]
Thanks! I have had the segments generated automatically and son't see an overlap, but will check again.
Where do I find the 0.14-B? Would love to test it.

**Comment by blazoncek** [comment]
Compile from source or use binary provided by @srg74 from his Wemos shield repo.
