### ISSUE TITLE
SN74HTC125N booster dati

### ISSUE THREAD

**Issue by cocolino83** [Aircoookie/WLED#2829]
hello could I ask you for help !?  😊 I tried to integrate a SN74HTC125N but I can't get it to work.  I am attaching a photo of my link.  where am i wrong?  a thousand thanks
![IMG_20221014_105701](https://user-images.githubusercontent.com/88486650/195818280-b763add6-e60b-43c2-8370-2441a0496cb1.jpg)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
