### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by ludeatude** [Aircoookie/WLED#283]
My lights are not in sync between the 2 wemos d1 mini controllers when I turn it on in the app. Any thoughts?

**Comment by Aircoookie** [comment]
Thanks for the report!
Did this happen after you updated to 0.8.6?

**Comment by ludeatude** [comment]
Did not know there was an update. Can I do this OTA with a wemos d1 mini?

**Comment by ludeatude** [comment]
Still the same issue. Each controller is connected 65 mbps too.

**Comment by Aircoookie** [comment]
Ok, thanks! I believe that the default configuration might somehow be wrong for you. Can you take a look at WLED sync section under sync settings? Most of the checkboxes should be ticked.

**Comment by ludeatude** [comment]
I haven't deselected anything in that section that was already selected. Anything I should make sure IS selected?

**Comment by ludeatude** [comment]
Receive, brightness, color, effects, send Phillip's Hue change notification, udp realtime. This is what is checked.

**Comment by Aircoookie** [comment]
Thank you! That doesn't sound like it's the source of the issue, but to make sure you could enable Sync on direct change (this is what is normally toggled by the slider in the UI). Also please check that both UDP ports are the same (default is 21324). Lastly, UDP multicast might be disabled in your router. You can look whether it has a setting for that. Some models also call it UPnP.
I hope we can get sync to work for you!

**Comment by frenck** [comment]
@Aircoookie I've noticed the same now. It seems to be limited to the JSON API. If an effect change is made through the JSON API, the change event is not broadcasted.

However, if an additional change is made after that (e.g, change of primary color), it gets broadcasted as part of that extra change.

So judging by that, I would say there is a event missing...

**Comment by Aircoookie** [comment]
@frenck Good observation! I would have never cracked down this missing event without your detailed description! Should be fixed in master now!

**Comment by frenck** [comment]
Your welcome m8, glad you've got it resolved.

**Comment by frenck** [comment]
@ludeatude Wait for the next release? 😉 
Or build it from source yourself.

**Comment by Aircoookie** [comment]
@ludeatude is your sync limited to the JSON API FX issue @frenck detailed, or does it not work at all even when only doing something simple, like setting brightness in the app/web UI?

**Comment by ludeatude** [comment]
It works but the 2 controllers get out of sync very easy.
