### ISSUE TITLE
Set device-specific filename when downloading .cfg

### ISSUE THREAD

**Issue by sowbug** [Aircoookie/WLED#2835]
If I have several WLED instances and want to back them up, I will click on the `Backup presets` and `Backup configuration` buttons in Settings -> Misc, but then I'll end up with many files named, e.g., `cfg (1).json`, `cfg (2).json`, etc., which aren't very easy to manage or tell apart from one another.

I would like it if the embedded web server set a `Content-Disposition` header to specify the filename, so that the browser automatically used the right filename when downloading. I think this would go around https://github.com/Aircookie/WLED/blob/main/wled00/json.cpp#L891:

```
  DEBUG_PRINT("JSON buffer size: ");
  DEBUG_PRINTLN(lDoc.memoryUsage());

  // new line
  response->addHeader("Content-Disposition","attachment; filename=\"wled-front-yard-cfg.json\"");

  response->setLength();
  request->send(response);
  releaseJSONBufferLock();
```

Of course, the filename would be dynamic; it could be derived from the `Server description` field in the web setup, and in most cases the code could just tack the server description as a prefix onto the filename.

Problem/challenges:

- The server description string needs to be safe for a filename. No slashes, for example.
- I'm not sure the function `serveJson` actually knows the filename it's downloading. There are lots of code snippets like `url.indexOf(F("eff"))`, which are heuristics for distinguishing the various kinds of files to be downloaded. This means that to manipulate the filename, we'd have to parse the URL to extract the basename. This might take up binary size we don't have. But on the other hand, it could allow cleaning up the `url.indexOf(F("xxxx"))` heuristics and replacing them with something more deterministic and maybe even more reliable.
- Allowing the user to specify part of the filename might actually break the `indexOf` heuristics depending on how it was implemented. If I named my lights "wled-ineffable," for example, and the indexOf tests looked at the filename rather than the original URL, then it might always download the effects.cfg for any .cfg, because it would have "eff" in it.

**Comment by blazoncek** [comment]
The functionality you describe (albeit a bit different implementation) is available in 0_14 branch.
