### ISSUE TITLE
new AI Thinker Module - Ai-WB2-12F 

### ISSUE THREAD

**Issue by Anollya** [Aircoookie/WLED#2838]
Will WLED support the new Module? Seems to be ESP-12F 2.0

http://www.ai-thinker.com/pro_view-110.html
http://www.ai-thinker.com/Uploads/file/20220930/20220930120258_19724.pdf
https://www.cnx-software.com/2022/10/04/ai-thinker-ai-wb2-modules-feature-bl602-risc-v-mcu-with-wifi-and-ble-connectivity/

- BL602 
- Bluetooth
- WPA3
....

Ai-WB2-12F is a Wi-Fi&BT module developed by Shenzhen Ai-Thinker Technology Co., LTD.
The module is equipped with BL602 chip as the core processor and supports Wi-Fi 802.11b/
g/n protocol and BLE 5.0 protocol. The BL602 chip has a low-power 32-bit RISC CPU,
276KB RAM, and a wealth of peripheral interfaces, including SDIO, SPI, UART, I2C, IR
Remote, PWM, ADC, DAC, PIR and GPIO etc. It can be widely used in Internet of Things
(IoT), mobile devices, wearable electronic devices, smart home and other fields.

**Comment by blazoncek** [comment]
If it is based one Espressif chip (ESP8266 or ESP32) then it is already supported. If not...

Not unless all necessary libraries are updated for it.
IMO very unlikely event.
BT will *not* be supported unless someone with knowledge and incentive tries at it.
