### ISSUE TITLE
Support for Raspberry Pi Pico

### ISSUE THREAD

**Issue by vespassassina** [Aircoookie/WLED#2839]
It would be great to be able to install wled on a raspberry pi pico w. 
i know there was a previous issue, but it was opened way before the pico w was launched.

**Comment by blazoncek** [comment]
Unless someone ports all libraries used for WLED it is not going to happen.
And even then it may require complete rewrite as WLED is based on Arduino framework.
Not in any immediate plans.

**Comment by vespassassina** [comment]
Understood. thank you !
