### ISSUE TITLE
sound sensor

### ISSUE THREAD

**Issue by gudworx** [Aircoookie/WLED#2842]
I have 20 esp32 wifi as e1.31 controllers working just fine with Wled but i need to put a sound sensor in one of them. will it sync to all other devices?

**Comment by blazoncek** [comment]
WLED does not yet support sound input.
0.14 will add audio features as a usermod and how that syncs is up to usermod developers.
So far "audio" sync is possible but not compatible with SoundReactive fork of WLED.

Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
