### ISSUE TITLE
Can't connect to my wled 

### ISSUE THREAD

**Issue by Leith-Omrani** [Aircoookie/WLED#2846]
Hello everyone,

Can u please help me with this:
Just got a Wled lamp , no buttons 
everything worked fine first time i got it , was able to connect and make it work through the app then i accidentally deleted the lamp from the app.
So now , i can't discover it : it must be connected to my wifi but i can't add it in the app
How do i reset everything and connect it again (no buttons whatsoever to reset as i said) , i tried turning it on and off for 7 times , it didn't work , its network never showed.

Thank u so much in advance

**Comment by Aircoookie** [comment]
Hey!
Please use Discord or the forum for support questions next time. Closing.

That said, there are 3 things you could try:
- Run the discovery on another phone
- Look in the device list of your router, it should contain the IP address of your lamp so you can add it back manually
- If your lamp has a reachable USB port, re-install WLED (e.g. via [install.wled.me](https://install.wled.me))
