### ISSUE TITLE
AZ-Delivery Mini D1 ESP32

### ISSUE THREAD

**Issue by pwcutajar** [Aircoookie/WLED#2849]
Hi

Please dont close to quickly

I am trying to install WLED to a MINI D1 ESP32. I would like it to be sound reactive
Whatever way I flash it I get the following. web browser install hangs.

also unable to to use sr .bin or browser install.

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
invalid header: 0x08030403
ets Jul 29 2019 12:21:46

Any Help will be great

Thanks

Paul

**Comment by softhack007** [comment]
hey, please don't duplicate too quickly! You could ask to re-open the ticket, or even re-open it yourself 💡

**Comment by pwcutajar** [comment]
I would if I knew how?

**Comment by softhack007** [comment]
@blazoncek please help him, by closing this ticket.
