### ISSUE TITLE
Backup & restore of configuration does not work correctly, no automatic reboot after cfg.json is loaded

### ISSUE THREAD

**Issue by cswaas** [Aircoookie/WLED#2852]
### What happened?

I try to use the Backup/Restore feature for the configuration (cfg.json).
<img width="410" alt="image" src="https://user-images.githubusercontent.com/46220990/197587692-1258fce8-3053-4e1f-b645-10790949747e.png">

I reported my issue in Discord with a conversation with softhack007 and blazoncek. blazoncek suggested to open this GH issue: https://discord.com/channels/473448917040758787/473449548279185408/1034004060904370226

### Issue Nr. 1
The saved cfg.json file does not correspond in all values to the value in the web ui.
Example: Maximum Current.
In ui: 7000 mA
<img width="365" alt="image" src="https://user-images.githubusercontent.com/46220990/197588618-faf20628-dfd0-4cb5-a9e8-2bd4a5fae8a6.png">
In cfg.json: 850 mA (default value)
<img width="283" alt="image" src="https://user-images.githubusercontent.com/46220990/197588796-87632268-2404-4369-91cf-d68aa2b5d678.png">

### Issue Nr. 2
The Restore has no effect on the actual values of the controller (actually reported issue in Discord,  I found Issue Nr 1 above later).  I can upload a previously saved cfg.json in the browser, but no reboot occurs, as was suggested by blazoncek, also showing the corresponding code snipplet.
![image](https://user-images.githubusercontent.com/46220990/197590686-441e557b-f651-431f-8765-434c00de1c51.png)

__

### To Reproduce Bug

Steps

1. Take a running WLED configuration.
2. Save configuration as a backup to cfg.json
3. Control content of cfg.json against web ui (Issue Nr. 1: e.g. Maximum Current was not identical)
4. Change a value in your configuration, e.g. length of an existing segment, and save new configuration to memory of the board
5. Restore previously stored cfg.json (Issue Nr. 2: no automatic reboot happens and configuration)

### Issue Nr. 1
All visible values in the web ui should be found correspondingly in cfg.json

### Issue Nr. 2
A restored configuration file should be applied either by pushing a clearly marked button or automatically, as suggested by blazoncek.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3, Build 2208222

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
See screenshots above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Thank you, but we've already opened #2847 and discussed solution in #2850

**Comment by cswaas** [comment]
@blazoncek 
Will it fix Issue Nr. 1 above as well?

**Comment by blazoncek** [comment]
I am not seeing issue no. 1.

**Comment by cswaas** [comment]
Within the initial text above of this issue #2852 I describe two problems as "Issue Nr. 1" and "Issue Nr. 2".
"Issue Nr.2" you will resolve with your real issue #2847.
However, my "Issue Nr.1" above might still exist.
Sorry, for the confusion with the issue numbers.

**Comment by blazoncek** [comment]
Again, I am not seeing issue nr. 1 (incorrect values in saved cfg.json).
I cannot replicate.

**Comment by cswaas** [comment]
I cannot reproduce Issue Nr. 1 anymore. I guess, that's good!

How does the fix for the restore bug gets released?
So far, I downloaded the file (binary) from here:
https://github.com/Aircoookie/WLED/releases/tag/v0.13.3#:~:text=should%20I%20use%3F-,Assets,-8

**Comment by blazoncek** [comment]
It is merged into main already. Pull & compile or wait for someone else. @srg74 does it daily, usually.
