### ISSUE TITLE
Animated Staircase usermod broken

### ISSUE THREAD

**Issue by SentiQ** [Aircoookie/WLED#2858]
### What happened?

Only segments 0 + 1 light up - doesn't matter which sensor was triggered.
Log is spammed with log put below.

@realrolfje maybe you can help?

### To Reproduce Bug

Flash WLED 0.14.0 beta with Animated Staircase usermod or official main branch and trigger bottom or top sensor.

https://github.com/srg74/WLED-wemos-shield/blob/master/resources/Firmware/WLED_wemos_shield/v0.14.0-b0/WLED_0.14.0-b0_esp32_staircase_mod.bin

### Expected Behavior

segment after segment light up

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
Destroying segment:
-- Copy segment constructor --
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
17d1ca82a6128b5a5c6515d22462deafaaf6fee4 and d30e219d7bcdeae4ffe8f1ea110f0570ab49cdaa should fix this.
