### ISSUE TITLE
iOS App not available in AppStore

### ISSUE THREAD

**Issue by bonderaustria** [Aircoookie/WLED#2866]
### What happened?

Hello!

I wanted to install the WLED app from the appstore, but i couldnt finde it. After 10 minutes i found a direct link to the app, if i clicked on the link it said: The app is not available in your country/region

### To Reproduce Bug

Publish the app again for austria:)

### Expected Behavior

The app should be available again:)

### Install Method

Binary from WLED.me

### What version of WLED?

the latest 

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
The iOS app is temporarily unavailable globally due to an administrative situation between me and Apple. I hope it will be available again within the next few hours. Sorry for the inconvenience :)

**Comment by Aircoookie** [comment]
Will close once the app is available again :)

**Comment by bonderaustria** [comment]
Now the app is back online:)
