### ISSUE TITLE
Wiki quick start guide TYPO

### ISSUE THREAD

**Issue by 400killer** [Aircoookie/WLED#287]
line 3 in the quick start reads:
You will need to install the NeoPixelBus library by Makuna (2.5.1), FastLED, ESPAsyncWebServer, AsyncTCP, and IRRemoteESP8266 (not for ESP32). All other dependencies are included with WLED for convenience. Now compile and flash the software!

The library AsyncTCP is incorrect. This should be ESPAsyncTCP

Took me a minute to realize I had the wrong library installed due to the "ESP" missing, as a library exists called "AsyncTCP". Figured I would save others the time future.

**Comment by Aircoookie** [comment]
You are correct, this was slightly unclear since AsyncTCP is the library you need for ESP32.
Clarified the page, thank you!
