### ISSUE TITLE
Won't boot when "Disable realtime gamma correction" is un-checked

### ISSUE THREAD

**Issue by shayded-exe** [Aircoookie/WLED#2878]
### What happened?

When I un-check "Disable realtime gamma correction" under the Artnet settings, WLED will no longer boot and I have to wipe my esp8266 to get it to work again.

It doesn't matter if I'm actually sending any artnet data. Un-checking that setting completely bricks it.

### To Reproduce Bug

Uncheck "Disable realtime gamma correction" under the Artnet settings.

### Expected Behavior

WLED doesn't freeze on startup.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.13.3_ESP01

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Sorry, can't reproduce. Tried on ESP8266 (D1 mini), ESP32, ESP32-C3 & ESP32-S2

**Comment by shayded-exe** [comment]
Is there any way I can capture log output being that I can't access the UI after disabling the setting?

**Comment by blazoncek** [comment]
Yes. Get or self compile debug version and monitor serial output.
@srg74 provides debug binaries in his Wemos shield repository.

**Comment by blazoncek** [comment]
If there are no updates I assume the issue is solved and will close in a few days.

**Comment by shayded-exe** [comment]
I haven't had an opportunity to test with the debug binaries yet. Please keep open for now.

**Comment by blazoncek** [comment]
4 months have passed without updates.
It looks like the issue is no longer relevant.
I am also unable to reproduce.
