### ISSUE TITLE
[Feature Request] Add WiFi signal to (JSON) API

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#288]
I would like to propose the addition of a property that passes in information about the connected WiFi in the JSON API.

Most importantly would be the WiFi signal. Having a weak signal can make devices behave weirdly, but currently, there is no way to find out about it.

Some other WiFi/Network information is welcome as well. E.g., the connected WiFi access point (SSID & BSSID). I would like to know which of the access points in my home the thing has been connecting with (multiple AP's sending out the same SSID, but with different BSSID's).

Having a simple WiFi signal indicator, might be beneficial for the web interface as well.

**Comment by Aircoookie** [comment]
I like this suggestion, will implement bssid and signal strength to info section of the JSON api :)

**Comment by Aircoookie** [comment]
Done! JSON info section now includes a Wifi object like this:
`"wifi":{"bssid":"CC:CE:1E:B9:3A:AB","signal":96,"channel":1}`
Signal is a relative quality level between 0 and 100, this should be easier to parse and intuitively understand than the negative RSSI scale.

**Comment by frenck** [comment]
That looks great @Aircoookie! 🎉 
Let's close up this issue, since well, it is done and you have enough open already 😉
