### ISSUE TITLE
Testing WLED v0.14.0-b0: Web UI not updating automatically after using JSON API to change state

### ISSUE THREAD

**Issue by cswaas** [Aircoookie/WLED#2880]
### What happened?

I was previously using the official release v.0.13.3, where the web ui was automatically updating the visual state, when it was changed via the JSON API (i.e. turning on/off segment from Loxone controller with {"seg":[{"id":0, "on":"t"}]} ). The segment button was properly grayed out when turning off and highlighted white when turning on.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/46220990/201511279-6d9e1b9d-f7cc-453f-b671-ac07ee40003f.png">

With v.0.14.0-b0, compiled on 13.11.2022, this automatic updating of the ui does not work anymore. When I reload the page, the state is updated correctly.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/46220990/201511392-ff607239-e053-4210-8b49-df9870dd7085.png">

### To Reproduce Bug

Load v.0.14.0-b0 and follow the description above.

### Expected Behavior

The web ui should update automatically, when changing the state via the JSON API.

### Install Method

Self-Compiled

### What version of WLED?

WLED v0.14.0-b0 (2211111)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Using a QuinLED-Dig-Quad v3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This change was intentional.
![Screenshot 2022-11-13 at 09 58 20](https://user-images.githubusercontent.com/7722392/201513919-0ffeca4a-61d8-4f7a-9f13-9eddf97d2b57.png)

**Comment by cswaas** [comment]
May I ask what the logic behind this new behavior is?
Shouldn‘t the ui always represent the actual state of the system?

Alternatively, can I use the JSON API in a way to have state changes represented in the WLED web ui?

**Comment by blazoncek** [comment]
See commit comment.
https://github.com/Aircoookie/WLED/commit/0f6b1e4ae19ec58cdb2acd562e585b1fb7e2e1f4

If changing segment *on* state would cause `stateChange` that would also unload/deselect *current* preset which is not desired. We may need to find another way to broadcast such change over WS.

**Comment by cswaas** [comment]
To be honest, I do not understand the new logic yet. 

When a preset is set "on" (i.e. also as visually activated button) and this preset has a certain segment also in the "on" state, then manually in the ui or via API turning "off" the certain segment should in my opinion turn "off" (deactivate) the preset as the system does not correspond to this preset. When activating the preset, the certain segment should turn "on" again. All this was the behavior in v.0.13.3, which made sense to me.

In v.0.14.0-b0 pushing the preset button does reload the preset state and turns "on" a previously turned "off" segment, but the preset button is not activated anymore. Yet another change in behavior that I do not understand.

I do not understand what you mean by "We may need to find another way to broadcast such change over WS." What is "WS"?

**Comment by blazoncek** [comment]
WS == websockets, a method to inform clients of changes in WLED state. UI uses WS.
If you only need a response of the state after you call `{"seg":[{"id":0, "on":"t"}]}` add a `"v":true` property to the API call.
UI will be informed on next WS broadcast.

**Comment by cswaas** [comment]
Here the ui in v.0.13.3:
-  1. Screenshot: Preset "Default" = "On" -Segment 0 = "On"
-  2. Screenshot: Preset "New Default" = "On" -> Segment 0 = "Off"


1. Screenshot
<img width="765" alt="image" src="https://user-images.githubusercontent.com/46220990/201515979-1bfdefbe-b6d0-40ac-ae7f-c4d703e1f9df.png">

2. Screenshot
<img width="755" alt="image" src="https://user-images.githubusercontent.com/46220990/201516020-950248e9-0dbf-4229-9449-5fa0dd28f153.png">


Here the ui in v.0.14.0-b0:

1. Screenshot
<img width="767" alt="image" src="https://user-images.githubusercontent.com/46220990/201516144-1eca9afe-e700-4bf3-86cd-e69f70e15397.png">


2. Screenshot
<img width="763" alt="image" src="https://user-images.githubusercontent.com/46220990/201516167-dce1a38b-69f3-4c35-9ffb-8a6029670cee.png">

**Comment by blazoncek** [comment]
I have noted your request/issue.
For now just change the mentioned line in json.cpp

**Comment by cswaas** [comment]
Ok, thanks. I will try that.

**Comment by cswaas** [comment]
I was able to apply your suggested change and it works as expected. Thanks again.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/46220990/201517037-f31fe3ff-4de0-4b11-8dec-518c59d46a5d.png">

**Comment by Aircoookie** [comment]
IMO it wouldn't be a problem if toggling segments changed state (aka. unloads preset and causes broadcast).
Changing power option should probably change state, only selection shouldn't.
Or was there a good reason for it that I forgot?

**Comment by blazoncek** [comment]
@Aircoookie I am updating code ATM to reflect above discussion (along with other fixes).
