### ISSUE TITLE
I can't find WLED_AP

### ISSUE THREAD

**Issue by ShiinaMono** [Aircoookie/WLED#2882]
### What happened?

ESP32 S3 cannot display AP

### To Reproduce Bug

I use ESP32 S3, use espdownload to write the firmware, try to erase and then write, uart and usb interface, can not display AP.(of course, Bootloader also wrote, I am wondering if the firmware or BL is not compatible?)

### Expected Behavior

Work light TX always on means normal work

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
S3 is not supported in 0.13 or below.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
