### ISSUE TITLE
Reboot after adding 4th Segment on Wemos D1 Mini

### ISSUE THREAD

**Issue by cbcalhoun** [Aircoookie/WLED#2884]
### What happened?

After adding the 4th segment on Genuine D1 Mini, Wemos begins crashing and rebooting. I am adding Segments groups in 2 and a spacing of 4. Unit will reboot several times then eventually failback to preset saved.

### To Reproduce Bug

Build 4 presets with groups of 2 and a spacing of 4. 
![image](https://user-images.githubusercontent.com/42541741/201914261-9a9e802f-e902-4811-b6fb-cf2ba19ca6fd.png)

### Expected Behavior

Build a 4 color strand with groups of 2 leds of the same color and effect.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 (build 2208222)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please try 0.14 beta since 0.13 is no longer maintained and will be replaced soon.

**Comment by cbcalhoun** [comment]
Ok I will do that this evening. Thank you.

**Comment by cbcalhoun** [comment]
Can you point me to the direction for the .14 beta code? I can't seem to locate it.

**Comment by blazoncek** [comment]
Main branch.

**Comment by blazoncek** [comment]
If the original problem is resolved by 0.14 please close this issue.

**Comment by cbcalhoun** [comment]
I have not had a moment to do the OTA upgrade. I will work on this hopefully this weekend.

**Comment by cbcalhoun** [comment]
I had a moment to do some testing now I am getting a crash and reload after two segments are assembled. 
![image](https://user-images.githubusercontent.com/42541741/206047886-72f3c047-56d1-47ef-9fd7-6cd4169368d5.png)

**Comment by blazoncek** [comment]
Use a debug build and monitor serial. When reboot happens copy crash dump and use exception decoder.
Then post your findings.

BTW out of 10 ESP8266 devices I have installed with multiple segments (not just two) I do not have any reboots. Use esptool to erase flash and upload WLED via serial.

**Comment by blazoncek** [comment]
You can also verify the amount of free heap. Use info page.

**Comment by cbcalhoun** [comment]
On the debug 0.14 bin. I cant use GPIO 1 for my second channel but I was able to create up to 5 seg without disconnection. Also on the .13 bin I have about 19+kB heap.

![image](https://user-images.githubusercontent.com/42541741/206299113-f3dd43f4-e134-4d58-84e0-b18056d36da0.png)

![image](https://user-images.githubusercontent.com/42541741/206299770-01786c41-d298-48bc-92b0-5a73a5da0510.png)

--DEBUG INFO---
Runtime: 690302
Unix time: 1670448487,302
                         Free heap: 17728
Wifi state: 3
State time: 450193
NTP last sync: 999000000
Client IP: 10.0.254.24
Loops/sec: 3977
UM time[ms]: 0/1
Strip time[ms]: 0/5
Segments: 5 -> 360B
                   Modes: 4*187=748B
                                    Data: 4*187=748B
                                                    Map: 2*0=0B

**Comment by blazoncek** [comment]
GPIO1 is reserved for debug output.
You will need to dig deeper for the cause you are experiencing as WELD normally exhibits no such problem on my ESP8266.

**Comment by cbcalhoun** [comment]
Here is the model I am using to compare. 

![image](https://user-images.githubusercontent.com/42541741/206304824-4eac9fc5-499f-4f8e-82f6-b26e70c5ba37.png)

![image](https://user-images.githubusercontent.com/42541741/206304879-076150db-5b54-4871-8d63-50baa82ced6d.png)

**Comment by blazoncek** [comment]
I am using the same make and model.

**Comment by cbcalhoun** [comment]
I will do some more digging here is my settings for the LED strings. I tried a knockoff make of the D1 with the same results. 

![image](https://user-images.githubusercontent.com/42541741/206308410-a5ec568d-808a-4b90-a43b-da132a69e59d.png)

![image](https://user-images.githubusercontent.com/42541741/206308610-aee15180-c47d-458a-bb76-2a4153f24020.png)
![image](https://user-images.githubusercontent.com/42541741/206308647-8d5056f9-7810-42a3-be91-664eaf39417e.png)

**Comment by blazoncek** [comment]
Try lowering led count

**Comment by cbcalhoun** [comment]
I appreciate your time working with me on this. I have just tried 30 leds on 1 segment only. I am able to get to the 5th segment: 0 - 5, 5-10, 10-15, 15-20, crash on adding 20-25

![image](https://user-images.githubusercontent.com/42541741/206311111-c8b619a6-c541-4d75-89ba-2fca8f49d747.png)

![image](https://user-images.githubusercontent.com/42541741/206311600-2db6e52f-d99f-40d7-9b14-04e3a1fc1e6a.png)

**Comment by cbcalhoun** [comment]
Ok after starting from the default config after installing the original bin files I have discovered once the device is tied to my wireless network the issue starts occurring. 

If I go straight in after flashing I can setup many segments. I did up to 9 without issue as shown in the photo below. Once I join the wireless with my PSK and set the static IP, I go in and setup the segments and the hang occurs on the 4th segment on 13.3 and the 3rd segment on .14 beta.

Could there be something in joining the network stack or the complexity of the PSK that is causing this?

Pre Wireless Join:

![image](https://user-images.githubusercontent.com/42541741/206357769-51176270-1a98-4c6a-9339-b165060f18fe.png)

Post Wireless Join:

![image](https://user-images.githubusercontent.com/42541741/206357799-dd5ef1f0-2fca-434b-ac0e-57fb5c358ba3.png)

**Comment by cbcalhoun** [comment]
Seems that using my wireless network with a complex key has something to do with it. I created a hotspot on my phone and joined my laptop and my test WLED D1 Mini to it. I used a simple PSK of 0u8120u812 to join the controller to. I was able to build up to 8 segments without issue shown below. 

My internal home network PSK comprises of special characters such as ! @ and #, I feel this might have something to do with it but not positive. Hope this might help pinpoint the issue.

![image](https://user-images.githubusercontent.com/42541741/206359599-cd3dc630-bb40-42d6-95d9-cb6ea08591a8.png)

**Comment by blazoncek** [comment]
Without crash dumps you are chasing ghosts.

**Comment by cbcalhoun** [comment]
Got the debug output to serial but I am not sure this is what is needed. 

![image](https://user-images.githubusercontent.com/42541741/206449501-a950986f-a3f1-43b7-b977-e0654e171490.png)

**Comment by blazoncek** [comment]
Now look for the crash. You may need to scroll back in the output window.
Crash dump is followed by WLED start sequence which is pretty obvious.

**Comment by cbcalhoun** [comment]
I am not getting a crashdump in the output that I can see, maybe it isn't crashing. I have the log from start-up to issue below after assembling the segments.


---WLED 0.14.0-b0 2212050 INIT---
esp8266 2_7_4_7
heap 27792
PIN ALLOC: Pin 1 successfully allocated by 0x89 (137)
Registering usermods ...
Reading config
Reading settings from /wsec.json...
JSON buffer locked. (3)
JSON buffer released. (3)
JSON buffer locked. (1)
Reading settings from /cfg.json...
Removing all.
PIN ALLOC: Pin 2 successfully allocated by 0x82 (130)
Successfully inited strip 0 (len 30) with type 22 and pins 2,255 (itype 2)
                                                                          PIN ALLOC: Pin 0 successfully allocated by 0x85 (133)
Starting usermod config.
JSON buffer released. (1)
Initializing strip
Usermods setup
lastReconnectAttempt == 0
Access point disabled (init).
Connecting to CBCalhoun...

Connected! IP address: 10.0.254.26
Init STA interfaces
mDNS started
FileRead: /index.htm
Not-Found HTTP call:
URI: /skin.css
FileRead: /skin.css
JSON buffer locked. (17)
JSON buffer size: 7249 for request: 6
                                     JSON buffer released. (17)
JSON buffer locked. (19)
JSON buffer released. (19)
JSON buffer locked. (17)
JSON buffer size: 1596 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 5500 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 4929 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 2129 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 4449 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 3009 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 2289 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 4529 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 2369 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 4129 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 3969 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 1649 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 2929 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 3089 for request: 5
                                     JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 853 for request: 5
                                    JSON buffer released. (17)
JSON buffer locked. (17)
JSON buffer size: 1987 for request: 3
                                     JSON buffer released. (17)
Not-Found HTTP call:
URI: /presets.json
FileRead: /presets.json
WS client connected.
JSON buffer locked. (12)
JSON buffer size: 1988 for WS request (1066).
                                             Sending WS data to a single client.
JSON buffer released. (12)
---DEBUG INFO---
Runtime: 30000
Unix time: 30,000
                 Free heap: 19504
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 10.0.254.26
Loops/sec: 3290
UM time[ms]: 0/1
Strip time[ms]: 0/10
Segments: 1 -> 72B
                  Modes: 4*187=748B
                                   Data: 4*187=748B
                                                   Map: 2*0=0B
                                                              JSON buffer locked. (11)
JSON buffer released. (11)
JSON buffer locked. (12)
JSON buffer size: 1988 for WS request (1073).
                                             Sending WS data to a single client.
JSON buffer released. (12)
Local time: 13:26
                 JSON buffer locked. (12)
JSON buffer size: 1988 for WS request (1074).
                                             Sending WS data to multiple clients.
JSON buffer released. (12)
JSON buffer locked. (11)
JSON buffer released. (11)
JSON buffer locked. (12)
JSON buffer size: 2482 for WS request (1353).
                                             Sending WS data to a single client.
JSON buffer released. (12)
JSON buffer locked. (12)
JSON buffer size: 2482 for WS request (1354).
                                             Sending WS data to multiple clients.
JSON buffer released. (12)
JSON buffer locked. (11)
JSON buffer released. (11)
JSON buffer locked. (12)
JSON buffer size: 2946 for WS request (1633).
                                             Sending WS data to a single client.
JSON buffer released. (12)
JSON buffer locked. (12)
JSON buffer size: 2946 for WS request (1634).
                                             Sending WS data to multiple clients.
JSON buffer released. (12)
WS client disconnected.
---DEBUG INFO---
Runtime: 60012
Unix time: 1670505993,012
                         Free heap: 14400
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 10.0.254.26
Loops/sec: 3139
UM time[ms]: 0/1
Strip time[ms]: 0/2
Segments: 3 -> 216B
                   Modes: 4*187=748B
                                    Data: 4*187=748B
                                                    Map: 2*0=0B

**Comment by blazoncek** [comment]
Then you have some other issues. 8266 can only handle 2 WS clients. If your browser makes more WS connections then this is the reason for your issues.
Unless you see crash there is little I can help.

**Comment by hcker2000** [comment]
This seems to have something to do with special chars in the wifi password. If I use a password with no special chars the wemos d1 behaves as expected. As soon as I add in the special chars it starts acting up.

Not a full crash as there is nothing being thrown when debug is enabled.

The same effect also seems to happen on esp32's (lolin32 for me) if you use special chars in the segment names (left 1/2 for example). In this case it dosn't lose connection right away but takes a second and the connection comes back but the presets.json is messed up when it comes back up.

**Comment by blazoncek** [comment]
It must be a WiFi driver then. Open an issue with Espressif.

As for segment names: Officially only ASCII characters are supported (up to 30), though you can use UTF8 if names are very short.

**Comment by cbcalhoun** [comment]
I doubt I am going to get anywhere with Epressif because of my limited knowledge so I will likely have to just build another SSID for these devices with a simpler PSK for now.

**Comment by blazoncek** [comment]
That would be prudent for any IoT device.

**Comment by cbcalhoun** [comment]
Different project same issue with the special character limitation for others interested. https://github.com/sidoh/esp8266_milight_hub/issues/410

**Comment by hcker2000** [comment]
So after more testing you can still ping the device and go to /edit but the main interface via web or app no longer works after saving more than 3 segments.

It also does not have this behavior when wled is acting as the access point. I'm also not seeing anything in the browser console or network tabs that look out of place.

**Comment by cbcalhoun** [comment]
Also after testing with ESP32 board there is no issue like that found with the Wemos D1 connecting to my specific wireless network with the same PSK. Created 12 segments without issue. 
![image](https://user-images.githubusercontent.com/42541741/208279244-8b23c760-8189-4b56-bda5-9ac3ebb0e015.png)

**Comment by FlyingEagle** [comment]
I do have the same issue, reboot after segmenting.
I have 459 LED.

I can do everything if I do not segment at all.

After beginning of segmentioning, the 8266 reboots suddenly and random.

I have / need 6 segments.

My Wifi PSK is alphanummeric with no special chars.

The segmentation names are free of special chars I use "seg01" e.g.

**Comment by blazoncek** [comment]
Please use debug build and monitor serial output.
Catch crash dump and post it here.
https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/%40Aircoookie/v0.14.0-b2/Debug_builds

**Comment by FlyingEagle** [comment]
The Output is [here](https://gist.github.com/FlyingEagle/6a72dd8272159ac77e316c6794382804)

After some hours of working, the Home Assistant Entry says disabled. I can only put the device of with a long press on it. after this I can not get the device again to live instead of bootin it by cable off.

After this I can not log in via install.wled.me again, the com port is there, but nothing happens.

By pressing some times on "reset device" on the console windows and pressing enter, I got a fast disappearing message: Terminal disconnected: AbortError: signal is aborted without reason.

I try this:

```
Install WLED
Do you want to install WLED 0.14.0-b1/2212222? All existing data will be erased from your device.

```
This works again:
```
Installing WLED
 
14%

This will take a minute.
Keep this page visible to prevent slow down
```
But I can not connect to device.

I tried:
```
Install WLED
Do you want to install WLED 0.13.3/2208222? All existing data will be erased from your device.
```

After some tries I got access, I took the ESP out of the PCB and re-program it.

Now, I have access again.

On the ESP is nothing else connected as the WS2812 1st-Pixel wiith 3.3V out of the ESP. One Button. Both connected to the default GPIO named in the GUI of the ESP.

I have one of the ESP connected to only one led, and it works the hole day. From time to time I went to the web-gui and play around with the colors, everything works fine.

As long til I do segmentation on the hole strip, do some animations or what ever to it, control color and presets on/off via home assistant, went to the gui, adjust some settings and back. The ESP some times suddendly went to walhalla or where ever. It seemed that the config is gone.

I tried to enable/disable wlan sleep, I tried with and without segmention, with and without animation, I tried different ESP (Wemos-Style, Uno-Style) - ok, all were 8266. Every ESP shows the same behaviour.
The WLAN Key is free of special chars only digits and letters.

As long as it works, I love this stuff ...

I hope I could help you to help me :-)

**Comment by blazoncek** [comment]
I can see one crash, 5 resets, and 2 times low memory condition.
Something is accessing your memory starved ESP too often. Try disabling/disconnecting HA.
Upgrade to ESP32 if possible.

**Comment by FlyingEagle** [comment]
I want to use HA, thats the main reason for using WLED.

**Comment by FlyingEagle** [comment]
![image](https://user-images.githubusercontent.com/1306751/219513947-85f40be6-8192-4d81-8366-2ad309f30bb9.png)

This is my setup.

Where can I find some more informations about mapping? I want to have the yellow parts act as one.
