### ISSUE TITLE
WS2814 Officially Supported ?

### ISSUE THREAD

**Issue by Sturm2002** [Aircoookie/WLED#2887]
**Is your feature request related to a problem? Please describe.**
Closest i found was #2646, but looks like it got fixed. But on kno.wled.ge it's not listed as Supported Hardware

**Describe the solution you'd like**
If Supported, maybe Update https://kno.wled.ge/basics/compatible-hardware/

**Describe alternatives you've considered**
If not Supported, add the functionality

**Additional context**
i didn't buy them yet, but would be nice to know wether they work with WLED or not

#2646

https://www.btf-lighting.com/collections/ws2814-12v-24v/products/ws2814-12v-24v-4-in-1-similar-sk6812-rgbw-pixels-addressable-ws2811-rgbww-rgbcw-5050-3pin-led-lights?variant=43463310115042

Thank you so much for maintaining this wonderful project <3

**Comment by blazoncek** [comment]
They are cheap, get a 1m strip, test it, update docs and make a PR there.
As WS281x is a generic protocol, they should be supported. Just select SK6812 as it is RGBW.
