### ISSUE TITLE
[Feature request] Make brightness property part of the segment

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#289]
Brightness is now considered a generic setting for the whole strip, IMHO it would be more useful if it became a property of a segment.

Right now, there is no way to set the brightness of segments individually.

**Comment by Aircoookie** [comment]
Thank you!
While I will not be getting rid of the global brightness property (which would make it way too hard to turn the entire installation on or off), I believe adding another per-segment brightness property is an awesome idea!
