### ISSUE TITLE
Setting a segment in UI disregards LED limit in LED preferences

### ISSUE THREAD

**Issue by Lycia-Renfort** [Aircoookie/WLED#2890]
### What happened?

I have a 60LED strip. I had 1 segment 0-13 and created a new one 14-20. Once the second segment was created, it was the same 0-13 as the first one. I realized later I had set the number of LEDs to 13 in LED preferences, which explains what triggered the behaviour.

https://i.gyazo.com/9d690dce08dd740be831fcef2ae66760.png

https://i.gyazo.com/fa36f28bd563146bad35985ef8944c7b.png

### To Reproduce Bug

Try to create a segment with LED IDs larger than Length set in LED preferences.

### Expected Behavior

UI should throw an error stating the values entered are beyond the range of existing LEDs. Might as well check for overlap between segments while we're at it.

### Install Method

Binary from WLED.me

### What version of WLED?

v0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

The LED numbring is confusing. It starts at 0 and excludes the upper limit LED. So a setting of 0-13 is 13 LEDs, not 14. Perhaps it would be easier for users if either numbering starts at 1, or ends with the LED ID shown, e.g. 0-13 would be 14 LEDs, and next segment can start at 14.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
When you *add* a new segment, start and stop values are pre-filled to encompass all remaining LEDs on a strip.
If these values are the same as first segment (existing one) then you will be creating an overlapping segment (which is possible but not supported ATM).

I added a bounds check here: 43582b6319a83d4af561cfe01276937e1ca090e7
