### ISSUE TITLE
Better handling and documentation of internal pullups on input pins

### ISSUE THREAD

**Issue by DerSpatz** [Aircoookie/WLED#2896]
I have designed a PCB for WLED that has two different 5V rails with two different power supplies (power bank and regular power supply). Depending on which power source is used, WLED should use different presets. I planned to use one GPIO pin as switch input in WLED. 

One of the 5V rails is connected to a GPIO pin of the MCU with a resistor divider (56k and 100k).

Without the MCU, the voltages on the pin connector are correct (3.3V and 0V), but when the MCU is mounted, and the GPIO pin is set as input, the low level voltage is 2.6V, so it does not trigger the switch input. 

This is very likely caused by the internal pullup resistor on the input.

Unfortunately, the use of the internal pullup resistor is not mentioned in the documentation of WLED, and the documentation even says you'd need an external pullup resistor, so IMHO the documentation is misleading in this case. 

Because of this, it would be great if you could disable the internal pullup resistor in software, for example with a checkbox in the settings, and/or if the documentation could be clearer on the use of internal pullups.

Otherwise I would need to order new PCBs with adjusted circuitry, but I would prefer a software solution.

**Comment by blazoncek** [comment]
Please update [WLED-docs](https://github.com/aircoookie/WLED-docs) accordingly and make PR.

**Comment by DerSpatz** [comment]
Done!

https://github.com/Aircoookie/WLED-Docs/pull/93

I could fix the issue on my prototype board by lowering the resistor divider values to 500 Ohms and 1kOhms.
As I already wanted some "cosmetic" changes on my design, I decided to order new PCBs with a proper fix (MOSFET).

**Comment by blazoncek** [comment]
![Screenshot 2022-11-26 at 23 32 41](https://user-images.githubusercontent.com/7722392/204111454-0cc66a9f-06b6-4053-a5a3-a9d30ec8834d.png)

**Comment by DerSpatz** [comment]
Looks great! Thank you!
