### ISSUE TITLE
WLED on new PIXEL7PRO phone crashes when Discover lights is pushed. 

### ISSUE THREAD

**Issue by sdansie** [Aircoookie/WLED#2902]
### What happened?

I purchased a new phone a Google Pixel 7pro. I loaded WLED on it and tried to run it. It brings up the first screen that allows you to discover lights. When Discover Lights is selected, the WLED software immediately crashes. I ran WLED successfully with my Pixel 3 but it seems to have a hang up with the new phone. 

### To Reproduce Bug

Load WLED on a Pixel 7 Pro and try to run it.

### Expected Behavior

The software totally crashes and kicks you back to the ap tiles.

### Install Method

Binary from WLED.me

### What version of WLED?

Most recent version on Google Play for Android

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Known issue.
Please update issue in relevant [repo](https://github.com/aircoookie/WLED-app).
Closing.
