### ISSUE TITLE
[Feature request] Allow for single time override transition time

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#291]
If would be useful if the transition time in the API could be overridden for just a single state change, ignoring the global transition property.

This would allow for turning light on instantly, e.g., alarm triggers, turn lights on NOW, full brightness and red (but there are more use-cases for this).

**Comment by Aircoookie** [comment]
Added support for the `tt` key! Works same as `transition`, but doesn't change the default, so the value is only used for the one change.

**Comment by frenck** [comment]
🎉 Really nice! 🚀 

Let's close up this issue, since well, it is done and you have enough open already 😉

**Comment by tonyn0** [comment]
Not sure if this post will be seen, but &tt **is** changing the default.

**Comment by Aircoookie** [comment]
@tonyn0 agreed, confusing api design on my part.
&TT in HTTP API changes the default, while the `tt` property in the JSON API does not, but `transition` does instead. Will not change though due to compatibility.

**Comment by tonyn0** [comment]
Ohhhh. Okay.

**Comment by Suxsem** [comment]
@Aircoookie sorry does it still work?

I just built 0_15 and created a preset with tt instead of transition but when preset is called default transition time is changed. Thank you
