### ISSUE TITLE
Android app crashes after Samsung update

### ISSUE THREAD

**Issue by DocDelete** [Aircoookie/WLED#2913]
### What happened?

App crashes when doing light discovery after Samsung 13 update

### To Reproduce Bug

Do a light discovery in samsung Android version 13. 

### Expected Behavior

I expected app to discover new lights

### Install Method

Binary from WLED.me

### What version of WLED?

1.0.3

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please report the issue in appropriate repository.
https://github.com/aircoookie/WLED-app
