### ISSUE TITLE
[Feature request] Sort effects & pallets in web UI

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#292]
The effects & pallets list/selects in the UI are currently sorted by their ID, this makes it hard to find the preset you like.

The suggestion is to sort them by alphabet.

**Comment by Aircoookie** [comment]
I've been thinking about this one as well. Alphabetically is a good starting point, but allowing users to set their own order (or sort by category) might make even more sense. I'll keep this one in mind!
