### ISSUE TITLE
Would it be possible to give DDP an across the board brightness adjuster?

### ISSUE THREAD

**Issue by mkaatman** [Aircoookie/WLED#2929]
**Is your feature request related to a problem? Please describe.**
My DDP bulbs aren't bright enough

**Describe the solution you'd like**
I don't know if it would be feasible, but having either a global DDP adjustment or a per device DDP adjustment for brightness might be handy. Something where you could add X% of additional brightness in an attempt to make bulbs match LED strip output more closely.

**Describe alternatives you've considered**
Running a separate WLED instance for each.

**Comment by blazoncek** [comment]
Use "force maximum brightness" in Sync settings and brightness multiplier in LED settings.

**Comment by mkaatman** [comment]
That's an improvement! Thanks.
