### ISSUE TITLE
lolin_c3_mini board support

### ISSUE THREAD

**Issue by wooboo** [Aircoookie/WLED#2934]
I was wondering if lolin_c3_mini is supported.

**Is your feature request related to a problem? Please describe.**
I'm able to buildfor lolin_c3_mini board. It builds with several warnings. 
[build.log](https://github.com/Aircoookie/WLED/files/10188831/build.log)

My env is:
```
[env:lolin_c3_mini]
platform = espressif32@5.1.1
board = lolin_c3_mini
board_build.partitions = tools/WLED_ESP32_4MB_1MB_FS.csv
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32c3.build_flags} 
  -D WLED_RELEASE_NAME=LolinC3_WLED
  -D LEDPIN=6
  -D STATUSLED=7
lib_deps = ${esp32c3.lib_deps}
```
I'm trying to flash this board: [LolinC3Pico](https://www.wemos.cc/en/latest/c3/c3_pico.html)
The problem is when it boots I get error
```
SHA-256 comparison failed:
Calculated: 536dfe3b000041806b8028e5cb5125cd46736c37326abcaa489747c6c6fe4906
Expected: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
Attempting to boot anyway...
entry 0x403ce000
./components/esp_littlefs/src/littlefs/lfs.c:1071:error: Corrupted dir pair at {0x0, 0x1}
E (410) esp_littlefs: mount failed,  (-84)
E (410) esp_littlefs: Failed to initialize LittleFS
./components/esp_littlefs/src/littlefs/lfs.c:1790:debug: Bad block at 0x0
./components/esp_littlefs/src/littlefs/lfs.c:1796:warn: Superblock 0x0 has become unwritable      
E (2081) esp_littlefs: Failed to format filesystem
./components/esp_littlefs/src/littlefs/lfs.c:1071:error: Corrupted dir pair at {0x0, 0x1}
```
What can I do to make it work?
Will a noob be able to do it?  :)

Thank you for your help and let's make WLED better!

**Comment by softhack007** [comment]
Hmmm 🤔 the warnings in you build log could be related to this recent change
https://github.com/Aircoookie/WLED/blob/b24c8b3410c968de96846e080ad0340bab805997/platformio.ini#L114

If comment out the above line, does it work better?

**Comment by wooboo** [comment]
Ok, it gave me less warnings, but the boot issue persists.

**Comment by blazoncek** [comment]
Seems like your partition map is wrong. Erase flash, upload bootloader, upload partitions ant then WLED binary.

**Comment by wjbuys** [comment]
I'm running into the same error. I've tried the following Platformio targets in order:

- Platform -> Erase Flash
- Platform -> Build Filesystem Image
- Platform -> Upload Filesystem Image
- General -> Upload

But, the error still persists. How does uploading the bootloader work? I don't see a PIO target for it...
