### ISSUE TITLE
Presets Backup apparently saves the # leds from Led configuration

### ISSUE THREAD

**Issue by kenmcdaniel** [Aircoookie/WLED#2936]
### What happened?

Backed up presets on a controller with 149 leds, then restored this presets.json file on a controller with 371 leds. When running any preset from the restored controller only 149 leds were lighting up, on this controller and another controller that was synced to it which has 200 leds. I thought only the preset settings would be backed up, but it appears that # leds is also backed up. I do not have any segments defined. Thanks

### To Reproduce Bug

Back up a preset from a controller with small amount of leds defined in the LED Configuration, then restore this preset to a controller with more leds.

### Expected Behavior

Only the number of leds from the first controller will display on the restored presets controller.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 13.3 Build 2208222

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This is not a bug but is by design.
You can save presets without segment length info by unchecking "Segment bounds" when creating a preset.
