### ISSUE TITLE
Unable to set segment name in 2D mode since 0.14.0

### ISSUE THREAD

**Issue by simonemarin** [Aircoookie/WLED#2945]
### What happened?

I am not able to set a segment name anymore after moving to 0.14.0

### To Reproduce Bug

- Set 2D mode in configuration

- In the web GUI click in the pencil icon and set the text field

- Use the check mark (I guess that is like the APPLY button in 0.13.3 ?)

- Name is not applied

### Expected Behavior

I expect the name to be saved after clicking the check mark icon

### Install Method

Binary from WLED.me

### What version of WLED?

v0.14.0-b0 "Hoshi"

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

I can properly change the name of the segment with the JSON API both in a preset and with external API http POST request.
Issue initially posted in https://github.com/MoonModules/WLED/issues/8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonemarin** [comment]
![image](https://user-images.githubusercontent.com/5068735/207016196-0d255ec8-6962-4a60-80ad-3be8be7cf4dc.png)

I had a look at the html and JS console to see if I can spot something weird but it seems ok to me, no errors

**Comment by blazoncek** [comment]
Tested on ESP32 and ESP8266 and cannot reproduce.
You may need to specify test conditions in more detail and/or provide cfg.json and presets.json.

**Comment by gamer1966** [comment]
Tested on different ESP32 (Dev-Kit-C, S3, ESP32 NodeMCU D1). I can reproduce the error. Furthermore no changes are saved.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/43117741/207284742-ea0e81a9-fffe-42c5-9707-7eafc8f981c7.png">

Simple setup
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/43117741/207284946-fa8f1da1-a680-4032-82f8-dcc9e029a7b4.png">

Before
<img width="289" alt="image" src="https://user-images.githubusercontent.com/43117741/207285130-ee6fa2ab-35d5-4333-a3b0-60d635e3ae40.png">


Edit
<img width="272" alt="image" src="https://user-images.githubusercontent.com/43117741/207285547-882725de-196a-4805-b982-645e5585543e.png">


After pressing the checkmark
<img width="277" alt="image" src="https://user-images.githubusercontent.com/43117741/207285734-aa4715e4-ad26-4066-aa40-3dfecc7c1677.png">

**Comment by softhack007** [comment]
Looks like you also modified the "StopY" and "StopX" fields, am I correct?

Maybe the exact sequence of that you did is needed to make the problem reproducible.
Did you first change X/Y values, or first changed the name then modified X/Y?

**Comment by gamer1966** [comment]
Error must be in 43582b6. Before this everything works fine.

![image](https://user-images.githubusercontent.com/43117741/207300006-3e87f69c-10f9-4ddd-93af-0541f014e0eb.png)

**Comment by softhack007** [comment]
> If I leave "html_ui.h" unchanged and only use the changes in "index.js" and [..] everything works fine.
> I don't know what "html_ui.h" is used for.

The way you tried, the change does not have _any_ effect. html_ui.h (and other html files) are generated from the files in data/, like index.js. After changing index.js, you need to run "npm run build" for the changes to take effect.
My suggestion is actually to wait for one of the UI developers (@blazoncek or @ewoudwijma ?) to analyze the problem, and they might come up with a proper solution.

Please also answer the other question: Did you also manually edit  "StopY" and "StopX" fields? If yes, did you edit the preset name before or after?

**Comment by gamer1966** [comment]
> > If I leave "html_ui.h" unchanged and only use the changes in "index.js" and [..] everything works fine.
> > I don't know what "html_ui.h" is used for.
> 
> The way you tried, the change does not have _any_ effect. html_ui.h (and other html files) are generated from the files in data/, like index.js. After changing index.js, you need to run "npm run build" for the changes to take effect. My suggestion is actually to wait for one of the UI developers (@blazoncek or @ewoudwijma ?) to analyze the problem, and they might come up with a proper solution.
> 
> Please also answer the other question: Did you also manually edit "StopY" and "StopX" fields? If yes, did you edit the preset name before or after?

Well, i use Visual Studio Code to build. So I don't run "npm run build". 
First I change the segment name then I change Stop X and Stop Y. After this I press the checkmark.

**Comment by softhack007** [comment]
Thanks, this detail may be important.


> Well, i use Visual Studio Code to build. So I don't run "npm run build".

See https://kno.wled.ge/advanced/custom-features/#changing-web-ui

**Comment by blazoncek** [comment]
BTW your panel setup seems out of place as it is 1D

**Comment by gamer1966** [comment]
> Thanks, this detail may be important.
> 
> If you do it in two steps - edit, change Stop X and Stop Y, press checkmark, edit, change name - does it work better?
> 
> > Well, i use Visual Studio Code to build. So I don't run "npm run build".
> 
> See https://kno.wled.ge/advanced/custom-features/#changing-web-ui

I'm a little bit confused. First I instaled node.js and after a reboot i run "npm run build".
After this it works correct. Then I change `stopY>eY.max` back to `stop>eY.max` and the old error is back.
Now I change `stop>eY.max` to `stopY>eY.max` back and the error is not corrected.
I run "npm run build" multible time but I can not save the changes anymore.

**Comment by gamer1966** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/43117741/207357588-02054cc1-cca8-41fa-b217-07f5c1375e47.png">

Thank You, this works.
