### ISSUE TITLE
[Feature Request] Make current calculator work for 12V pixels

### ISSUE THREAD

**Issue by Sander71** [Aircoookie/WLED#295]
First of all.. thanx for all the hard work.

I am using WLED with 12v pixels. It would be nice to use the  "current calculator" ( in LED setup) with these lights. Now they only use the 5v pixels. Maybe a volt selector ?

Than you again for thsi, i love it !

**Comment by Aircoookie** [comment]
I'm very glad you like it!

Yes will add that! 12V pixels have gotten a lot more popular recently!

**Comment by bagobones** [comment]
+1 for 12V as that is what I am running outdoors right now.. I noted that 24V strips exist as well so maybe this should be an expandable variable although I don't see anything out side of 5V/12V/24V being popular. 5V-24V is also the typical range for an off the shelf controller it seems.

**Comment by blazoncek** [comment]
Automatic brightness limiter operates on current and supports any voltage.
For non-standard LEDs there is an option to enter custom current consumption (per single LED).
