### ISSUE TITLE
Sunset time is not calculating correctly

### ISSUE THREAD

**Issue by TeslaBenny** [Aircoookie/WLED#2950]
### What happened?

The Sunset time is not calculating and showing as 00:00.
![image](https://user-images.githubusercontent.com/42008752/207735782-cd8bf05d-bbe8-47e1-8d2f-b4157717b318.png)

### To Reproduce Bug

Open Config > Time & Macros.
Set local NTP server, timezone, latitude, and longitude settings.
Save the settings.

### Expected Behavior

Sunset should show a valid time based on configured timezone, latitude, and longitude values.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This may occasionally happen (known issue) due to rounding errors. It will go away next day.

**Comment by TeslaBenny** [comment]
Thank you @blazoncek! Where is the known issue documented? I wasn't able to find it.

If the rounding errors aren't fixed yet, may I take a stab at the logic and attempt to provide a resolution to the issue? I just need to know which files and lines of code are involved with the sunset (and sunrise too?) calculation.

**Comment by blazoncek** [comment]
Just check closed issues.
No need to check the code as it is intentional that way (using custom math functions which favor code size over accuracy).
You can compile using -D WLED_USE_REAL_MATH to use double precision functios.

**Comment by jmerc77** [comment]
this just happened to me on 4/21/23. should have been 20:01 for me

**Comment by blazoncek** [comment]
> this just happened to me on 4/21/23. should have been 20:01 for me. using esp32 s3.

And it went away on the next day. Are you using 0.14?

**Comment by jmerc77** [comment]
0.14-b1 to be exact. day not over yet but assume it is temporary as this is the first time i noticed. may find out in about 2.5h.
