### ISSUE TITLE
Backing up presets via presets.json

### ISSUE THREAD

**Issue by githubsteveb** [Aircoookie/WLED#2952]
### What happened?

Hi there, reading [Backing-up and Restoring Presets](https://kno.wled.ge/features/presets/#backing-uprestoring-presets) it say to do the following:

> To backup all presets, go to [WLED-IP]/edit (OTA lock must be off), right click the presets.json file and download!
To restore, use the Choose file and Upload buttons.

However, the presets.json file is empty:
![image](https://user-images.githubusercontent.com/38283300/207832955-a9e95e93-9b25-43bd-8b17-f3b8b9a512a0.png)

Is this a bug ?

Thanks for a wicked piece of software!

### To Reproduce Bug

> To backup all presets, go to [WLED-IP]/edit (OTA lock must be off), right click the presets.json file and download!

### Expected Behavior

presets.json is populated with the existing saved preset.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 (build 2208222)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
The info in KB is a bit outdated (still valid though).
Use backup & restore buttons in Security settings.

**Comment by githubsteveb** [comment]
> The info in KB is a bit outdated (still valid though). Use backup & restore buttons in Security settings.

Thanks - I didn't know about that!

And I've released my original error - there is a massive amount of white space (which I didn't realise ) so I need to right scroll and all the preset config is there! 😆
![image](https://user-images.githubusercontent.com/38283300/207846190-4cf5ef08-15a4-482e-bdaa-84c1acb750b5.png)
