### ISSUE TITLE
Too Many Segments Causes Crash (Request from ALDIY)

### ISSUE THREAD

**Issue by mermelmadness** [Aircoookie/WLED#2954]
### What happened?

I'm using a Wemos D1 Mini ESP8266.  According to the ESP Flasher, it has 4MB memory.  I had 9 presets, each with 9 segments.  The strip is 9 pixels long and I needed each one individually addressable.  In version 0.13.3, switching too quickly between presets, or changing settings too quickly to more than a few segments at once would cause a crash and reset the board.  In version 0.14.0b-0 this is improved, but can still happen if you go way too fast.  In the WLED Home Assistant integration, having too many segments in too many presets would cause a palette error which would prevent the ESP board from being integrated into HA.  This would also show "Unknown Error" if trying to add for the first time.  This occurred on both 0.13.3 and 0.14.0b-0.

![image](https://user-images.githubusercontent.com/38080873/207888158-83379026-41fc-466b-a138-1de26282a354.png)
![image](https://user-images.githubusercontent.com/38080873/207888538-29187aa5-cd0d-4058-bdad-baa24c336fbc.png)

I was able to fix this by reducing the amount of segments per preset and being creative with the LED grouping and spacing.  Reminder, this is on an ESP8266 board.  I have ESP32s in my closet, but have not tried to reproduce on those as they are earmarked for a different project in the coming weeks.

### To Reproduce Bug

To recreate, make 10 presets with 10 segments and attempt to switch quickly between them.  Then try and integrate into Home Assistant.

### Expected Behavior

I expect some issues fast switching on an older ESP8266, but nothing like what I witnessed.

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3 and 0.14.0b-0

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

This was brought up in the Discord and ALDIY assisted me in troubleshooting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
ESP8266 is a MCU not CPU. It is not capable of processing too many requests in a short period of time.
This is due to lack of computing and RAM resources.
We are doing our best to squeeze as much functionality into 32kB of RAM as possible, we cannot do much more.

If you want more power please switch to ESP32.
