### ISSUE TITLE
Minor Issue: Browser tab still says WLED 0.8.4

### ISSUE THREAD

**Issue by Sander71** [Aircoookie/WLED#296]
After updating to 0.8.6 the browser tab still list it as WLED 0.8.4

**Comment by Aircoookie** [comment]
It happened again! I need to remind myself that search and replace doesn't include gzipped pages.

**Comment by frenck** [comment]
Just remove the version number from the title. There is no direct use to have it in there for a normal user.

**Comment by Aircoookie** [comment]
That's exactly what i'd planned to do!

**Comment by Sander71** [comment]
sounds like a smart plan :-)
