### ISSUE TITLE
WLED 0.14.0-b1 marked as stable and mistagged?

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#2968]
### What happened?

It seems like the WLED 0.14.0-b1 was mistagged in git and accidentally marked as stable in the GitHub release as well.

First up, the tag placed in `git`:

![CleanShot 2022-12-23 at 12 55 46](https://user-images.githubusercontent.com/195327/209332694-b6ec779c-d8eb-4e6d-8f38-e718734b87a5.png)

Secondly, the release marked in GitHub for this git tag:

![CleanShot 2022-12-23 at 12 55 56](https://user-images.githubusercontent.com/195327/209332836-5fd783e9-1c56-4889-a2d7-79fee1e65534.png)

Lastly, the assets attached to the release are marked correctly, causing a mismatch between the actual release and the attached firmware versioning.

![CleanShot 2022-12-23 at 13 00 21](https://user-images.githubusercontent.com/195327/209333091-e360b0de-4d3b-4b2c-b9c5-f554fc93a3ae.png)

The latter makes it indeterministic, causing issues with, e.g., determining automatic updates (such as Home Assistant provides).

This issue a result of an issue raised @ the Home Assistant issue tracker in: <https://github.com/home-assistant/core/issues/84490>

This manifest in a couple of issues for those people:

- The firmware update doesn't work (version/filenames mismatch).
- Users are getting a beta version upgrade offered as a stable upgrade. Which should not happen.

../Frenck

### To Reproduce Bug

- Install WLED 13.x
- Add to Home Assistant
- wait...
- Upgrade notification
  - Notice incorrect version offered.
  - Notice how a stable version is offered.
  - Try upgrading: Actual upgrade will fail.

### Expected Behavior

Cheesy answer, but the opposite 😬 

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

Other

### Anything else?

Happy Holidays! 🎄 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesmyatt** [comment]
Previous beta releases haven't been marked as pre-release either, but the tag is definitely different.

**Comment by frenck** [comment]
> Previous beta releases haven't been marked as pre-release either, but the tag is definitely different.

Yeah, HA is able to handle the pre-release vs. stable flags on releases (although I still think it should be correctly flagged in GitHub too, so we don't have to fallback to string parsing).

The tagging mismatching is the real issue in this case.

**Comment by Aircoookie** [comment]
That's why you don't release after a long night at 5am (unless you really want to make a release before christmas).
I apologize for the inconvenience, the tag should be fixed now.

Stable marking is intentional, I apply it when I believe an average user should prefer that version over the latest full release (while still not necessarily fulfilling stability requirements)

**Comment by lensherm** [comment]
@Aircoookie, thanks for your reply, but now I'm even more confused as to whether this release should be used by the general public, or if it is still not considered stable enough for the wider audience.

**Comment by frenck** [comment]
> That's why you don't release after a long night at 5am 

Hehehe, I'm familiar with the concept 🙄 🤣 

> I apologize for the inconvenience, the tag should be fixed now.

Don't worry about it. Thanks for the quick fix and lightning-fast response 🚀 

🎄 Merry Christmas 🎅 

../Frenck

**Comment by Aircoookie** [comment]
@lensherm it is definitely ready to be used, otherwise I'd mark it as pre-release. The main reason it is not yet the final 0.14 release is that some of the changes are not properly documented yet. Some areas (e.g. preset handling) are more stable in 0.14, while others (behavior with a large amount of segments and performance with thousands of LEDs) may still fall short of 0.13.3.

@frenck Merry Christmas to you too! 🕯️🎄

**Comment by lensherm** [comment]
@Aircoookie thank you much for the clarification and more importantly for the joy you bring to all of us LED tinkerers!
