### ISSUE TITLE
Type - Grups in Sync Interface

### ISSUE THREAD

**Issue by harrisonbc** [Aircoookie/WLED#2969]
### What happened?

Typo in the Sync Interface Section
Sync grups

should be 
Sync groups

### To Reproduce Bug

Access Sync Interfaces section ion UI

### Expected Behavior

Should read Sync Groups

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 14.0.1-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Thanks, will be fixed in next commit.
