### ISSUE TITLE
WiFi login issue/re-flash did not work

### ISSUE THREAD

**Issue by wvpt** [Aircoookie/WLED#297]
I am been having trouble logging into my wled. When I originally started the d1mini it came up as wled-ap. I changed wireless info. Now I am unable to log into the ap directly or through the home network. On the wled app it says offline. I tried to re-flash the d1mini but did not take it back to the wled-ap state. 

Any help would be appreciated!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by raoulteeuwen** [comment]
Hi @wvpt . Did you check on your router whether you could see the device getting an IP-address, and if so, could you connect to it? When re-flashing, please choose the erase option mentioned in https://github.com/Aircoookie/WLED/issues/286#issuecomment-546628206 .
