### ISSUE TITLE
Effect speed

### ISSUE THREAD

**Issue by WarlockSVG** [Aircoookie/WLED#2973]
The speed a animation moves along a "strip / string" is "linked" to the total number of the "strip / string" ( ...for some effects ).

More LED's will make the animation go faster, to the point that it moves to fast ( at least for my taste ;-) )

Try the following preset(s)

( Chunchun 50 LEDs speed 0 )

{"on":true,"bri":67,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":50,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[0,0,255],[22,22,22],[255,0,0]],"fx":111,"sx":0,"ix":12,"pal":52,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":1},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]}

( Chunchun 600 LEDs speed 0 )

{"on":true,"bri":67,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":50,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[0,0,255],[22,22,22],[255,0,0]],"fx":111,"sx":0,"ix":12,"pal":52,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":1},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]}

As you can see the animation speed with 600 LEDs moves faster than with 50 LEDs. I would like the animation with 600 LEDs move slower kinda like it does with 50 LEDs

Now It's like "animation delay" = effect speed / total LEDs

And it would make more sens to me if it would be something like "animation delay" = 500ms / effect speed

Chunchun is not the only one that moves to fast ( for my taste ) on "strips / strings" with a high LED count. If this is something you want to look into than I can list other effects that respond the same way with a higher LED count.

**Comment by blazoncek** [comment]
This is your personal preference and there are tens of thousands of users of WLED with their own personal preferences.
It is not possible to accommodate each an every personal preference in a single package.

I recommend you fork WLED, make changes to your taste and compile such version.
