### ISSUE TITLE
Feature Request: Support saving multiple WiFi passwords

### ISSUE THREAD

**Issue by mickmister** [Aircoookie/WLED#2974]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to enter the WiFi password of every place I set up my LEDs, especially when I use them at the same place twice.

**Describe the solution you'd like**

Just like phones and PCs, I would like to store multiple WiFi credentials to allow the device to automatically connect to a router I connected to in the past.

**Describe alternatives you've considered**

I'm not sure of any alternatives. Certainly open to them :+1:

**Comment by softhack007** [comment]
Similar to https://github.com/Aircoookie/WLED/issues/2845

**Comment by blazoncek** [comment]
closed in favor of #2845
