### ISSUE TITLE
Inputs controlling presets

### ISSUE THREAD

**Issue by szymanski1975** [Aircoookie/WLED#2977]
Great project.
Could activation of the selected input trigger the selected preset ?

For example
active GPIO3 working Preset 3
or active GPIO4 working Preset 4

Greatings Tom.

**Comment by blazoncek** [comment]
Yes, use buttons.
More info [KB](https://kno.wled.ge)
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
