### ISSUE TITLE
ESP32 White channel missing

### ISSUE THREAD

**Issue by martin072** [Aircoookie/WLED#2989]
### What happened?

When compiled for a ESP32 (Lolin s2 mini) there is no "white channel slider" on the UI, whilst compiled on the eps8266 (d1_mini), it shows correctly. 

Furthermore, the HEX input (when enabled) shows only RGB value and not RGBW (when selected strip is an RGBW)

### To Reproduce Bug

See above.

### Expected Behavior

White channel should be visible when configured as RGBW strip on ESP32

### Install Method

Self-Compiled

### What version of WLED?

0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP32-S2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by martin072** [comment]
**ESP32**

<img width="346" alt="Screenshot 2022-12-29 at 18 35 32" src="https://user-images.githubusercontent.com/24524506/209989127-2ed0db5c-ffe2-4ea5-9c2c-80029eb3796e.png">



**ESP8266**

<img width="343" alt="Screenshot 2022-12-29 at 18 35 43" src="https://user-images.githubusercontent.com/24524506/209989175-9bc35c80-2f12-411e-9308-d550ba4b4e27.png">

**Comment by softhack007** [comment]
I think you need to set "auto-calculate white" in LED preferences
![image](https://user-images.githubusercontent.com/91616163/209992226-fb3142ee-d4dd-486f-9c45-0a4f57930ac5.png)

After adjusting the settings, I have performed a reboot (info panel), and the "white balance" slider appeared.

Please check your LED preferences.

**Comment by blazoncek** [comment]
FYI: S2 is not *regular* ESP32.

**Comment by martin072** [comment]
Hmm. Seems to be intermitted. When doing a reboot, the slider is back..

**Comment by blazoncek** [comment]
Then please close.
The appearance of white slider depends on how white handling is selected and has been tested numerous times.

**Comment by blazoncek** [comment]
Read the docs and you'll notice **a lot** of differences between those chips.
For start, it is a single core MCU.

**Comment by softhack007** [comment]
> > FYI: S2 is not regular ESP32.

> Can you elaborate on this? 

ESP32-S2 is not a regular "classic ESP32".
* It has a different Processor, so you need a firmware that was build for -S2
* It only has one core (instead of two)
* It is slower (240Mhz vs. 160Mhz)
* It Only supports 4 LED outputs, instead of two
* It is too slow for audioreactive usermod (ok, on the edge actually)

and above all that: WLED support for -S2 (and for -S3 and -C3) is *experimental* and still *bleeding edge*. It may work or not work. So better if you re-think your idea of exchanging all your D1 Mini's to Lolin's ESP-S2...

**Comment by blazoncek** [comment]
A side note: C3 works much better as a substitute for ESP8266.

**Comment by martin072** [comment]
Thanks for all the info! 🙏
