### ISSUE TITLE
Disable internal pull-up/down after reboot

### ISSUE THREAD

**Issue by espuno** [Aircoookie/WLED#2996]
### What happened?

After a reboot the hook is removed (Disable internal pull-up/down).
The setting is not saved

### To Reproduce Bug

LED Preferecene -> Button Settings -> Disable internal pull-up/down

### Expected Behavior

The setting should be saved

### Install Method

Self-Compiled

### What version of WLED?

v0.14.0-b1 "Hoshi" 

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
Thank you for the report, confirmed and fixed in latest source!
