### ISSUE TITLE
[Feature request] Editable NTP-Server

### ISSUE THREAD

**Issue by riwich** [Aircoookie/WLED#300]
Since I run WLED (and most of  my other Smarthome devices) in a isolated network without internet access, the NTP Option as currently implemented (yes/no) is useless in my setup. 

Would be nice and helpful to have the possibility to edit the NTP-Server from the settings interface.

**Comment by Aircoookie** [comment]
Sure, that makes sense! Will implement this when I rework the settings!

**Comment by riwich** [comment]
Incredibly great software, amazingly productive author! Don't you need sleep, or are you even a robot? ;-)

Thanks for this fantastic piece of software.

**Comment by Aircoookie** [comment]
Thank you so much for the encouragement!
I do in fact need sleep, otherwise we'd have segment support already! :)

**Comment by riwich** [comment]
Ach was Aircoookie, Schlaf wird doch völlig überbewertet! ;-)

**Comment by GrumpyMeow** [comment]
This feature is already implemented.
