### ISSUE TITLE
ABC! WLED Controller / ESP32 Hardware

### ISSUE THREAD

**Issue by filzek** [Aircoookie/WLED#3000]
### What happened?

GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!

### To Reproduce Bug

GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!

### Expected Behavior

GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!

### Install Method

Binary from WLED.me

### What version of WLED?

GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!
```

### Anything else?

GErber / Altium / ECAD project to custom build or Schematics for the best creationm usage and parts with manufacture numbers such as boms!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
What's this?

**Comment by softhack007** [comment]
spam. I'll delete it.

**Comment by softhack007** [comment]
can't delete, but I've removed all the junk.
