### ISSUE TITLE
Installer should work in chromium based browsers - not just chrome and edge

### ISSUE THREAD

**Issue by billyjacoby** [Aircoookie/WLED#3001]
### What happened?

Unable to install to a connected device using Brave browser.

### To Reproduce Bug

Try to use the install tool using Brave browser.

### Expected Behavior

Can successfully install binary via Brave Browser.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b1/2212222

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment]
The installer uses the Web Serial API, which in principle works in all Chromium based browsers. However, the Brave team decided to disable it, see https://github.com/brave/brave-browser/issues/13902
