### ISSUE TITLE
ESP32 - Touch pin - Ghost touch and activates by itself

### ISSUE THREAD

**Issue by greiseknoue** [Aircoookie/WLED#3009]
### What happened?

Activates the touch pin and whatever threshold value, the pin sensing touch when it's not being touched - Which cause false touch. Mounted a wire 10cm from the device.

### To Reproduce Bug

Using ESP32 with wled - Activate touch on a pin (Config - Led Preference - Button 0 - Touch), choose an "Touch threshold" between 20-50 - Wait. 

### Expected Behavior

If the pin is not touched, it should not record an touch input. 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED version 0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Esp i'm using: ESP32 Dev Kit C V4 NodeMCU

Noticed this last night as the led keeps turning on and off for no reason. I'm using the touch pin (Gpio 15), with a small RJ45 cable mounted on a screw. When i deactivate the touch pin, this does not occur. 

I kept searching for a solution to see if there was someone else with the similar issue and i found this [forum](https://electronics.stackexchange.com/questions/524544/esp32-touch-sensor-outputs-unstable-values) , where they noticed that the ESP32 could have unstable values (causing false touch). 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
_Touch threshold_ is the only option available to utilise touch functionality without external hardware.
If you are getting phantom touches regardless of _touch threshold_ you will need to make hardware adjustments.
