### ISSUE TITLE
Wrong firmware installation on ESP01-1M from install.wled.me

### ISSUE THREAD

**Issue by hphde** [Aircoookie/WLED#3013]
### What happened?

I tried ESP Fastled first on my EPS01-1M with ESPhome fastled which worked fine except for the limitations then decided to switch to WLED.
Flash was done using https://install.wled.me/ and setting Wi-Fi was a success. Unfortunately after reboot/poweroff the settings are lost. Pressing the backup preset or configuration button gives a 404 Not Found on the requests, visible using debug tools but with not representation on the UI.

### To Reproduce Bug

Flashed 0.13.1, 0.13.3, 0.14.0-b1 on a ESP01-1M (black board) - always the same effect

### Expected Behavior

settings saved

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Hi,
A few questions to better understand what is the root casuse of your problem:

* Please add a screenshot of the WLED "info" page. What size do you see for "Filesystem"? 

> visible using debug tools
* What debug tools are you using?
* please add your "debug tools output" to the problem report

**Comment by hphde** [comment]
This is from the failing instance:
<img width="507" alt="grafik" src="https://user-images.githubusercontent.com/13313834/211741361-0b06b998-ab60-46ff-b239-1c3b957fe501.png">

As soon as I saw the filesystem at 100% I downloaded the ESP01.bin and flashed this to another device:
<img width="515" alt="grafik" src="https://user-images.githubusercontent.com/13313834/211741526-3ca85d28-8714-4736-8f0e-4d1a76ea5ef9.png">
This one has no issues and everything works as expected.

So I am assuming the device detection is not working as expected on the install website and flashes something else?

**Comment by blazoncek** [comment]
You need to flash 1M firmware version for ESP01, except if you know you have 4M flash chip on ESP01 (a rarity).

**Comment by hphde** [comment]
I have changed the topic to reflect the issue found. So it's not an issue with the firmware itself but with https://install.wled.me/

**Comment by blazoncek** [comment]
Than please close the issue here.

**Comment by Aircoookie** [comment]
install.wled.me always installs the 4M binary, ESP Web Tools does not yet distinguish between flash sizes, so we can't serve the appropriate binary. If we can get ESP Web tools to add support for flash size detection, it would be great for all non-4M-flash boards: https://github.com/esphome/esp-web-tools/issues/111

**Comment by Aircoookie** [comment]
Closing in favor of #2367 , which is the same core issue, just a different symptom.

**Comment by hphde** [comment]
I suggest to point this 4m out on the web installer because it is not obvious
