### ISSUE TITLE
[Feature Request] Kerning slider added to Scrolling Text

### ISSUE THREAD

**Issue by mermelmadness** [Aircoookie/WLED#3020]
As the title says, would love a Kerning slider added to the Scrolling Text effect to increase or decrease letter spacing.

**Comment by blazoncek** [comment]
The fonts used are fixed (monospaced) and it is not possible to adjust kerning on them (as it would be inconsistent).
If you have an algorithm to allow kerning on monospaced fonts I would be happy to take a look.

**Comment by mermelmadness** [comment]
Sadly I do not.  thanks for clarifying the font characteristics.  That makes sense.
