### ISSUE TITLE
JSON import of colors ignores first color value in specific instances

### ISSUE THREAD

**Issue by werkstrom** [Aircoookie/WLED#3024]
### What happened?

According to the docs: {"seg": {"i":[0, 'CC0000', '00CC00', '0000CC', 'CC0000]}} should render like this.
![image](https://user-images.githubusercontent.com/13434693/212470691-4cf08eec-d914-409a-b291-4f89bb940d40.png)

But it does render like this:
![image](https://user-images.githubusercontent.com/13434693/212470720-28ba4651-3e29-4788-8176-0d9bc7eb1bd7.png)

Adding a "dummy" value before the first color value makes the render correct:
 {"seg": {"i":[0, 'dummy', 'CC0000', '00CC00', '0000CC', 'CC0000']}}

### To Reproduce Bug

Use the above examples

### Expected Behavior

Should render like this:
![image](https://user-images.githubusercontent.com/13434693/212470824-cca1ba6b-5763-4b16-b84c-9f873d3db8b8.png)

### Install Method

Binary from WLED.me

### What version of WLED?

v0.14.0-b1 "Hoshi"

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Actually a bug: `if (!set) start++;`

Should read `if (set<2) start++;`
