### ISSUE TITLE
Group Circuit

### ISSUE THREAD

**Issue by Datenkrake156** [Aircoookie/WLED#3026]
Athom now has offered 
[ATHOM Pre Blitzte WLED Smart Birne RGBCW 7W Arbeitet E27 B22 Heimautomatisierungsmodule - AliExpress.pdf](https://github.com/Aircoookie/WLED/files/10418281/ATHOM.Pre.Blitzte.WLED.Smart.Birne.RGBCW.7W.Arbeitet.E27.B22.Heimautomatisierungsmodule.-.AliExpress.pdf)
WLED lamps with an E27 socket. From the description, each lamp should have a unique IP address. I will probably make a Blockly script in IO-Broker to switch several lamps in a group with one command.
I haven't found a way to implement such a group circuit in WLED. Would it be possible to implement something like this in an upate?

I already have several strips in use, thank you very much for this great tool.

**Comment by blazoncek** [comment]
Use sync feature of WLED and send command to master unit.
