### ISSUE TITLE
[Documentation] possible approach to document the effects

### ISSUE THREAD

**Issue by lubeda** [Aircoookie/WLED#303]
There is a ASCII like file format for Images.
https://de.wikipedia.org/wiki/Portable_Anymap#ASCII

If WLED could "export" each step/frame of an effect as ascii value it might be possible to convert the ascii values to an images and then to a GIF for the documentation.

Is it possible to export e.g the animations step by step?

**Comment by Aircoookie** [comment]
Good idea! It should indeed be easily possible to print each frame to serial monitor.
