### ISSUE TITLE
Allow control of White LED separately in RGBW mode.

### ISSUE THREAD

**Issue by Armadillo1** [Aircoookie/WLED#3036]
Apologies - posted the same feature request and closed it thinking that it does work in RGBW mode, however setting it to RGBW and entering random GPIO pins doesn't change the GUI to allow for separate White control, therefore I'm resurrecting this feature request:)

Is your feature request related to a problem? Please describe.
I want to use a high power/high CRI RGBW led strip for a planted fish tank, hence it is important for me to be able to control different colours of the RGBW LED chip separately to achieve maximum effect of a specific spectrum.

Describe the solution you'd like
Currently it is possible to use sliders for R/G/B. I would like an additional W slider for white led within the chip.

Describe alternatives you've considered
Just using RGB, however that doesn't let me intensivy certain parts of the light spectrum (not visible to human eye, visible to plants)

Additional context
![image](https://user-images.githubusercontent.com/1597809/212756246-9629804b-1daf-44bf-8b56-304b11752519.png)

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
You can also familiarize yourself with the [KB](https://kno.wled.ge).
Closing.
