### ISSUE TITLE
Manually setting segments via JSON API causes UI errors and unexpected behavior

### ISSUE THREAD

**Issue by hawkeye217** [Aircoookie/WLED#3041]
### What happened?

Since 0.9.x, I've used the JSON API for a specific use case. I have some leds mounted above a door, and I used the API to change them when when motion is detected near the door. 

Whether a preset was loaded/running or the strip was off, I could create a new segment ("id": 9) that I knew was not used by any of my presets and would in essence act as an "overlay" on top of the first few pixels of whatever was running on the strip at the time. When motion stopped, I would simply turn off that segment (again via the API) and the strip would return to what it was doing beforehand.

In 0.14.0-b1, creating a new segment via the API with an ``id`` out of order or not sequential no longer works correctly and produces strange results in the UI.

### To Reproduce Bug

Start with a clean installation of 0.14.0-b1 from wled.me

Run:
$ curl -k -s -f  --header "Content-Type: application/json" --data '{"on":true,"v":true,"seg":[{"id":9, "start":0,"stop":2,"on":true,"col":[[255,240,160]]}]}' http://192.168.1.100/json

UI shows "Segment 1" created, even though I specified ``id`` as ``9``.

Now run:
$ curl -k -s -f  --header "Content-Type: application/json" --data '{"on":true,"v":true,"seg":[{"id":9,"start":0,"stop":0,"on":false}]}' http://192.168.1.100/json

The segment is not turned off.

### Expected Behavior

In 0.13, the created segment showed "Segment 9" in the UI, and the second curl command turned it off as expected.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b1 (build 2212222)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

I'm sure this is just a result of the segment code rewrite in 0.14. 

I hard-coded an ``id`` of 9 because I knew that none of my presets use that many segments. 

If there's a newer or preferred method to achieve the same behavior I had in 0.13, I'm more than happy to change up how I use the API. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
If you use 0.14 and PIR sensor usermod it can save previous state when motion is detected and can return to play previous effect after motion is gone.
Segment logic was completely rewritten (for 2D support) and you will need to update your animation logic. Unfortunately.

BTW technically none of the segments have ID and never did have. Previous version relied on fixed memory structures while 0.14 uses dynamic memory for that.

**Comment by hawkeye217** [comment]
> If you use 0.14 and PIR sensor usermod it can save previous state when motion is detected and can return to play previous effect after motion is gone. Segment logic was completely rewritten (for 2D support) and you will need to update your animation logic. Unfortunately.
> 

Alright, no problem. I don't use the usermod, I'm using a Home Assistant automation to call the API. I'll try to think of another way to get the same behavior.

> BTW technically none of the segments have ID and never did have. Previous version relied on fixed memory structures while 0.14 uses dynamic memory for that.

Makes sense. 

Do you think that the API should report some kind of error if an invalid ``id`` is specified as in my case?

Thanks for the quick response!
