### ISSUE TITLE
Led strip

### ISSUE THREAD

**Issue by tunavis** [Aircoookie/WLED#3044]
### What happened?

Hi guys, i would like to know how to go about my my issue.

My LED strip only has RGB and volts input how should i wite this to my wled strip and should my wled be configured.?

### To Reproduce Bug

Not working

### Expected Behavior

Strip to work with esp32

### Install Method

Binary from WLED.me

### What version of WLED?

Not sure

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
