### ISSUE TITLE
Command on multi segment 2D not rendered correctly

### ISSUE THREAD

**Issue by werkstrom** [Aircoookie/WLED#3046]
### What happened?

When sending commands to render an image on a segment of a multi segment setup the command (image) does not get rendered correctly. Several strange behaviors. Images gets rendered on the wrong segment, images gets rotated and mirrored. 

### To Reproduce Bug

Setup is a three 16x16 panel setup, meaning it takes up 3/4 of a 32x32 matrix. (Why would I have such a strange setup? Because it is the setup you'd need for a cube where you want to be able to address each panel individually)

Led setup:
![image](https://user-images.githubusercontent.com/13434693/213912080-d9e3ec6e-1197-451c-9628-aa4c784d3c3b.png)
![image](https://user-images.githubusercontent.com/13434693/213911971-5028c42b-f405-438c-8751-ecceeed2807a.png)

Panel setup:
![image](https://user-images.githubusercontent.com/13434693/213907236-20d2494d-8b42-4329-ab62-1904580e7fee.png)

Segment setup:
![image](https://user-images.githubusercontent.com/13434693/213907337-b9791598-5d9f-4aea-847b-5f8186e618e1.png) 
![image](https://user-images.githubusercontent.com/13434693/213907352-89820af9-2be1-461d-a2f0-b93352b4f9b5.png) 
![image](https://user-images.githubusercontent.com/13434693/213907370-d39e1733-3504-43d4-9d19-fb10fd5f6742.png)

From what I can tell, all segments are reported correctly in JSON req, 
`[{"id":0,"start":0,"stop":16,"startY":0,"stopY":16,"len":16,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"rY":false,"mY":false,"tp":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"id":1,"start":16,"stop":32,"startY":0,"stopY":16,"len":16,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"n":"Top Right","col":[[255,170,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"rY":false,"mY":false,"tp":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"id":2,"start":0,"stop":16,"startY":16,"stopY":32,"len":16,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"n":"Bottom Left","col":[[255,170,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"rY":false,"mY":false,"tp":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0}`

As is matrix (32x32)
`"matrix":{"w":32,"h":32}`

First off, this is what is rendered when opening peek and turning the lights on.
![image](https://user-images.githubusercontent.com/13434693/213907460-7dccf678-eddf-46f1-a0ed-a71793bde030.png)
(should be a full 16x16 in the bottom left corner)

Then I send this image to the different segments:
![image](https://user-images.githubusercontent.com/13434693/213907521-a3cfa914-1dc6-4ec0-befe-c584aebeffe2.png)

First sending it to seg 0 it gets rendered as expected:
![image](https://user-images.githubusercontent.com/13434693/213907926-75a82e73-0392-41cf-a1d6-254af025608a.png)

Sending it to segment 1 (should be top right quadrant) It gets rendered in segment 0's space.
![image](https://user-images.githubusercontent.com/13434693/213907987-1188de1f-014f-429b-be11-18dc661b9bc9.png)

It should be noted that if I sent the image to seg 1 before rebooting the image was rendered in the wrong plac but rotated and mirrored. After reboot it no longer does that. Also the segments were gone and had to be set up again.
![image](https://user-images.githubusercontent.com/13434693/213907620-7f2e60f5-5491-4a87-9d06-8d29aac53820.png)

And after a while of testing the device (d1mini) stops responding and I have to reboot. Would be great to get some help in doing more testing.

### Expected Behavior

Should render in correct segment

### Install Method

Binary from WLED.me

### What version of WLED?

2301140

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
It renders for me correctly and segments behave as expected.
Please verify your LED count and 2D set up.

**Comment by werkstrom** [comment]
Added to the initial description (so it is complete). I might be missing something, but it looks OK to me...

**Comment by werkstrom** [comment]
![image](https://user-images.githubusercontent.com/13434693/213912382-e4784083-a6e6-4230-a3b3-c81f3fc92cef.png)
Issue is consistant when using effects. This is after a fresh reboot, so it is not the "sending command through JSON" that triggers the behavior.

**Comment by werkstrom** [comment]
Also consistent independent of led count/panel size
![image](https://user-images.githubusercontent.com/13434693/213912692-f6034617-d852-4237-8e07-08900606e8c9.png)

**Comment by werkstrom** [comment]
Setting up 
A. LEDs for an entire square area (8x8x4 in this case)
B. Setting up panels to cover the entire area (4 panels 8x8)
C: Setting up segments for each panel

Renders correctly (and effects and uploads work as expected)

![image](https://user-images.githubusercontent.com/13434693/213913256-988e7e29-b29f-4661-94f2-421664106b84.png)

![image](https://user-images.githubusercontent.com/13434693/213913297-3c499af8-ab62-4d53-8755-8102094c4a54.png)

**Comment by blazoncek** [comment]
Just a side note: ESP8266 may have memory issues if you want to have matrix larger than 16x16.

**Comment by werkstrom** [comment]
Removing the lower right segment, works as expected.
![image](https://user-images.githubusercontent.com/13434693/213913350-42428265-4c35-45f3-94be-151e18df57f7.png)

Removing the "ghost" fourth panel also works (leds still defined as (8x8x4) JSON command and effects work.
![image](https://user-images.githubusercontent.com/13434693/213913414-3efb08c0-d9a0-4247-a87c-b38631484be1.png)

Removing the 64 "ghost" LEDs from LED setup, reintroduces the issue

![image](https://user-images.githubusercontent.com/13434693/213913570-1fcf08f2-c7b1-4ed1-8839-76c9587558f6.png)
