### ISSUE TITLE
Segments lost after reboot (2D setup)

### ISSUE THREAD

**Issue by werkstrom** [Aircoookie/WLED#3047]
### What happened?

Ref. issue #3046 segments are not saved so after a reboot they are gone. Also tried to leave seg 0 as the full matrix (since seg 0 appears be a bit special) and set up seg 1, 2, 3 for the 16x16 panels. Same result.

### To Reproduce Bug

Setup like in issue #3046. Reboot device

### Expected Behavior

Segments should be persistent

### Install Method

Binary from WLED.me

### What version of WLED?

2301140

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not a bug.
You need to save segments into a preset.
