### ISSUE TITLE
Scrolling Text flickers a lot if color intensity is not 100%

### ISSUE THREAD

**Issue by mermelmadness** [Aircoookie/WLED#3050]
### What happened?

When using Scrolling Text effect on a matrix, the text flickers a lot at the same speed as the scroll effect.  This occurs when the top bar is anything other than 100%.  Brightness does not affect behavior.

![image](https://user-images.githubusercontent.com/38080873/214208354-cc37dd76-747a-4d70-a507-5f81f493568a.png)

This can be seen with scrolling or static text.
In addition, even if the text color is at 100%, adding any background color, even a very slight one, causes the same flicker.

https://user-images.githubusercontent.com/38080873/214208542-92cb9337-b4cb-4985-b146-c54b8ea147a8.mov

https://user-images.githubusercontent.com/38080873/214208978-f6781baa-8888-411b-80e1-1cbea59dfafa.mov

https://user-images.githubusercontent.com/38080873/214208985-60654842-e7d3-481e-a99d-2d6dc30418b7.mov

NOTE: This can be clearly seen using Peek.

### To Reproduce Bug

Make a Scrolling Text segment, set a color using the Default palette, then adjust the color intensity slider to witness the effect.

### Expected Behavior

With full color intensity the effect behaves as expected, with smooth scrolling or solid colors if static.  This should occur for all brightness and intensity levels.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b1 2301170

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

This was mentioned in the `Issues` channel and also `beta-testing`
ALDIY confirms he sees the same issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
The same was noticed on multiple units  with  even the text is stationary , Just use random palette and you would see the same on leds and peek  . Default palette  works fine with us so might be a clue .
![1_24_2023_flick_text](https://user-images.githubusercontent.com/87589371/214209640-a4adcfc0-d6b6-4394-ab10-913c18d7f8f3.gif)
![RND_PAL_S TXT_11_Jan_2023_14b1 15](https://user-images.githubusercontent.com/87589371/214209650-7bedef63-78d9-47cb-a77d-430fadac72ed.gif)

**Comment by mermelmadness** [comment]
Default palette gives me flicker, although, setting the whole device brightness to very low and setting each segment brightness to half eliminates the flicker.
![image](https://user-images.githubusercontent.com/38080873/214210034-14e182ec-9c72-4d71-b874-c64b6f0a3bb9.png)
It's pretty dim for most applications, though.

**Comment by dosipod** [comment]
Seems adjusting sliders speed or brightness could reduce it with random palette   , as said we did not notice flicker at all with default  palette . If you face issue wit default  palette   , please try to take video and show all the setting used  .  
![image](https://user-images.githubusercontent.com/87589371/214211079-49e7fa8b-3a56-467d-a19f-d80da5ac1812.png)
This setting produced a solid blue colors text without any issue

**Comment by mermelmadness** [comment]
All videos posted in initial issue are with Default palette.  Here's an additional comparison.
Overall brightness = 10
Each segment brightness = MAX

https://user-images.githubusercontent.com/38080873/214211443-a4564510-bd16-4edd-83ec-257f6f9c2899.mp4

Overall brightness = 10
Each segment brightness = Approx 30%

https://user-images.githubusercontent.com/38080873/214211630-df39f2b3-220f-4ba5-b22b-c08a07d1959b.mp4

WLED just crashed as I was taking the video...

**Comment by blazoncek** [comment]
That is inherently caused by "trail" functionality.

**Comment by mermelmadness** [comment]
In all examples, Trail is set to 0.

**Comment by blazoncek** [comment]
Exactly!

**Comment by blazoncek** [comment]
In case of static text (as in above examples) either use maximum trail length or use overlay mode (which may have other undesirable effects).

**Comment by mermelmadness** [comment]
Setting Trail to 255 does not alleviate the issue.

I'm not sure how overlays work.  Can't seem to find any explanation on the KB.

**Comment by blazoncek** [comment]
It does in my test cases.

**Comment by mermelmadness** [comment]
https://user-images.githubusercontent.com/38080873/214330943-9392662e-b2b8-4c88-8b9b-33c60220c76e.mp4

![image](https://user-images.githubusercontent.com/38080873/214331019-9f90176b-f9aa-4c24-85a0-51f9791c9855.png)

**Comment by blazoncek** [comment]
Use faster speed.

**Comment by mermelmadness** [comment]
https://user-images.githubusercontent.com/38080873/214333095-25451a30-4985-4221-b40f-50a2e55dba55.mp4

![image](https://user-images.githubusercontent.com/38080873/214333134-06e87f45-75b9-466c-b47a-765af03f3eba.png)

Not sure if it comes through on video, but these settings it is less, but still very much there.  Overall brightness is 128, segment brightness is 100%.

**Comment by mermelmadness** [comment]
It should be noted that if the Bg color is black, the flicker is not present.  Can Scrolling Text be paired with Solid using Overlays?
