### ISSUE TITLE
Palette effect not smooth at low speed since 0.14

### ISSUE THREAD

**Issue by PolestarWx** [Aircoookie/WLED#3055]
### What happened?

I have tried 0.14-b1 on both my ESP32 (website) and ESP32-c3 (self-compiled) and it works quite well exept Palette effect that does not run as smooth as before when the speed is low, the led color change abruptly, on 0.13 it was quite smooth event at low speed. It's like the smooth time does not change according to the effecf speed.

### To Reproduce Bug

Install weld 0.14, select Rainbow (or any multiple palette with opposite color) with Palette effect at speed under 30 to notice the bug.

### Expected Behavior

Led color change smooth as in 0.13 for Palette effect.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14-b1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please post comparison video.

**Comment by Aircoookie** [comment]
How many LEDs do you have, and what is the FPS as reported in the info tab on the main UI? You can hit the Refresh button after running the Palette effect for at least 5 seconds to get an accurate frames per seconds value. If it is below 30, that would explain the lagging.

**Comment by blazoncek** [comment]
Tested, but cannot reproduce.

**Comment by dosipod** [comment]
![image](https://user-images.githubusercontent.com/87589371/215302416-4315c1d4-780d-4934-a0e0-edd2b8ee7548.png)

https://user-images.githubusercontent.com/87589371/215302459-f6263ed6-a068-4955-b602-533ebdbaff0a.mov

**Comment by blazoncek** [comment]
As I can see from the image and video above the palette changes and runs smoothly.

**Comment by PolestarWx** [comment]
Thank you very for your time about testing this issue, I see you made a new commit to fix this issue, thanks ! 

If you still need video thatshow the problem, I will try to do it soon

**Comment by blazoncek** [comment]
@PolestarWx @dosipod please verify if the commit https://github.com/Aircoookie/WLED/commit/c6fd11157a8c68c44e69b4a0157796534e619497 fixes this issue and if so, close it.

**Comment by PolestarWx** [comment]
## 0.13
![0.13](https://user-images.githubusercontent.com/16896194/215616921-0ab439e5-2e1f-4c25-a787-f32686548108.PNG)

https://user-images.githubusercontent.com/16896194/215617016-74f40aea-a04f-409d-88fa-5753c4912238.mp4

## 0.14 without commit 
![0 14 before commit](https://user-images.githubusercontent.com/16896194/215617100-29f238bd-46e2-4dab-ab33-d186c6c4ac6b.PNG)

https://user-images.githubusercontent.com/16896194/215617074-c8f62522-20ff-4d42-afde-bd3c09be6d34.mp4

## 0.14 with your commit 

https://user-images.githubusercontent.com/16896194/215617156-a6bde617-b9d1-476e-9e66-20ab9bce2da5.mp4

## Conclusion
Even better than before !

**Comment by blazoncek** [comment]
Unfortunately none of the videos play for me.

**Comment by PolestarWx** [comment]
Strange, it's ok on brave and my android browser via

**Comment by dosipod** [comment]
I had to convert the videos and if you are okay with the result then better detail that

**Comment by PolestarWx** [comment]
it's classic mp4 container with h264 codec :P Don't what going wrong but no problem on my device :p

**Comment by phoenixtechnam** [comment]
I have had that issue for a long time on both v0.13 and 0.14. I thought it was an issue with resources on my ESP8266, but my new ESP32 from QuinLED actually does the same thing. As can be seen in the video, the the leading LEDs are not faded but the trailing LEDs have nice and smooth fade-out. This behaviour can be seen in almost all moving effects at very low speeds.

Effect shown: Sinelon Dual, 42 FPS according to live info

https://user-images.githubusercontent.com/29205326/235636566-519ef2f1-6efd-4142-8c4b-2bf22546860c.mov

Kindly assist. I tried all versions including nightlies (0.14-b2) and also MoonModules v0.14.0.b15
