### ISSUE TITLE
After Time no Conect to Wifi

### ISSUE THREAD

**Issue by NormBot1008** [Aircoookie/WLED#3066]
### What happened?

After about 5 to 10 minutes, the WiFi connection separates and it is no longer possible to operate the WLED controller via its interface, but it doesn't seem to hang up completely, since the last function continues to run, has anyone else observed this phenomenon?
I have a D1 Mini ESP8266 on it

### To Reproduce Bug

Error can be reproduced, after a certain time during operation, or when trying to call up the edit, it disconnects the WiFi connection

### Expected Behavior

-

### Install Method

Binary from WLED.me

### What version of WLED?

0,14.0 b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This may be an issue with your particular device and/or WiFi network.
