### ISSUE TITLE
Settings page not working on reverse proxy

### ISSUE THREAD

**Issue by rulkens** [Aircoookie/WLED#3069]
### What happened?

I'm building a standalone server with Raspberry Pi that exposes the WLED interface over wifi, with a QuinLED board connected to the Pi over ethernet (to stream LED data realtime). 

When setting up a reverse proxy with nginx on the Pi I can forward all traffic to WLED and it shows the interface in the browser. But when navigating to the `/settings` page, it never succeeds in getting back a request from WLED and the connection times out after a minute or two. 

I've inspected the HTTP headers and it seems the `/settings` page is returning some different HTTP headers than the main `/` page. Specifically, it's also using gzip encoding, but it never returns the `content-encoding: gzip` and `content-length: xx` headers. It does return a `Transfer-Encoding: chunked` header.

### To Reproduce Bug

Create an nginx proxy to forward all traffic to the WLED server:

`
server {
    listen 3007;
    location / {
        proxy_pass http://{{WLED IP}};
    }
}
`

And then do a request to the proxy server `/settings` page. It never resolves.

### Expected Behavior

I expect the settings page to also work through a proxy server.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

I'm running WLED pre-installed on a QuinLED Dig Uno with an Ethernet hat.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Known issue.
There is a PR waiting extensive testing. #2788 
Please test it and report.
