### ISSUE TITLE
Interupt PIR usermod countdown

### ISSUE THREAD

**Issue by Shaps-77** [Aircoookie/WLED#3080]
Is there a way to temporaily interupt the countdown timer function of the PIR usermod?

My situation is this.. I'm currently using the PIR and Rotary encoder usermods to control my ensuite lights. I have the PIR setup to turn on some ambient lights and the rotary encoder takes care of brightness and using its built in momentary button where 'short press' triggers preset macros and 'long press' powers off..

Here's my situation... as I enter the room the PIR triggers the lights on and the timer starts the countdown to turn off..(This is great for most situations) buttttt.. Is there a way that any input from the rotary encoder or button can suspend/cancel the PIR countdown function until WLED is powered down? Thus keeping the LEDs on in their current state.. Otherwise it seams I need to wait until the PIR counts all the way down before I can turn on the lights manually using the button or Rot Encoder... at the moment even if I use the button or encoder whilst the PIR usermod is counting down, the inputs are registered and the lights change etc.. but the countdown continues until WLED powers off.

**Comment by Shaps-77** [comment]
Tested and PIR interrupt working inline with expectations above although I appear to be getting temperature sensor errors now..?   Getting constant "0 Sensor Error!" message on INFO page..
Is it just an issue with the USERMOD_DALLASTEMPERATURE and the usermod-enhance branch??

**Comment by blazoncek** [comment]
@Shaps-77 for Dallas take a look at https://github.com/PaulStoffregen/OneWire/pull/93
