### ISSUE TITLE
Home Assistant - missing segments

### ISSUE THREAD

**Issue by FlyingEagle** [Aircoookie/WLED#3092]
### What happened?

I have 6 segments (0-5) created in WLED, in HA only shown 5 of them (1-5).

Do I missed something?

### To Reproduce Bug

create segments and count them in HA

### Expected Behavior

Have 6 segments in this case

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not a WLED issue.
Please open an issue on HA Github.
