### ISSUE TITLE
Random resets when connected to home network

### ISSUE THREAD

**Issue by Deadeye5589** [Aircoookie/WLED#3100]
### What happened?

Hello,

I'm experencing random resets with one of my WLED projects. The strange fact is, that I have multiple WLED projects in the same network and those are wokring well. Only my "Matrix" is randomly resetting. The Matrix is a custom board design with a total of 160 LEDs. The matrix is arranged in 8x20 pattern. As controller I'm using a ESP8266-F12 chiplet. 

Before the question arises, that it could be a hardware problem. I do not bevlieve so. The resets only occour when the matrix is connected to my home network. If I connect it to a different AP, the matrix works fine and does not experience random resets at all. 

I have already seen this behaviour with the 0.13.x versions of WLED and even with the recent update to the latest beta release, this problem persists. So I would like to try to figure out what is causing this random resets. 

### To Reproduce Bug

Random resets occour ever 20 minutes to 3 hours when the matrix is connectet to my home network.
I have tried to disable most interfaces in WLED that I don't need.
I would like to control the matrix via the regular web interface or by DMX. The error can also be observed when the DMX master is not present in the network. 

### Expected Behavior

No random resets

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

```shell
ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v3969889e
```

### Anything else?

Here are my configuration and preset files, which might be helpful for debugging. 
[wled_presets_WLED_Matrix.zip](https://github.com/Aircoookie/WLED/files/10766611/wled_presets_WLED_Matrix.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
WDT is the watchdog. Something stalls.
Use debug build.

**Comment by Deadeye5589** [comment]
Ok, where can I find the debug build bin file?

**Comment by Deadeye5589** [comment]
Ok I got a debug build running. But I'm wondering what build env matches the file inclueded in the release WLED_0.14.0-b1_ESP8266.bin?

**Comment by Deadeye5589** [comment]
Ok here are debug traces from 2 random resets

**1st reboot**

JSON buffer released. (11)
JSON buffer locked. (12)
JSON buffer size: 5449 for WS request (3045).
                                             Sending WS data to a single client.
JSON buffer released. (12)
---DEBUG INFO---
Runtime: 7624312
Unix time: 1676731389,312
                         Free heap: 13888
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.2.14
Loops/sec: 1528
UM time[ms]: 0/1
Strip time[ms]: 0/17
Segments: 8 -> 2624B
                    Modes: 4*187=748B
                                     Data: 4*187=748B
                                                     Map: 2*0=0B

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3584, room 16
tail 0
chksum 0xb0
csum 0xb0
v3969889e
~ld

---WLED 0.14.0-b2 2302120 INIT---
esp8266 2_7_4_7
heap 27656
PIN ALLOC: Pin 1 successfully allocated by 0x89 (137)
Registering usermods ...
Reading config
Reading settings from /wsec.json...
JSON buffer locked. (3)
JSON buffer released. (3)
JSON buffer locked. (1)
Reading settings from /cfg.json...
Removing all.
PIN ALLOC: Pin 4 successfully allocated by 0x82 (130)
Successfully inited strip 0 (len 160) with type 22 and pins 4,255 (itype 4)
                                                                           Starting usermod config.
JSON buffer released. (1)
Initializing strip
Request to apply preset: 1
Usermods setup
lastReconnectAttempt == 0
Access point disabled (init).
Connecting to Changeme...
JSON buffer locked. (9)
Applying preset: 1
JSON buffer released. (9)
Slow strip.

Connected! IP address: 192.168.2.14
Init STA interfaces
mDNS started




__________________________________________________________
**2nd reboot**



State time: 0
NTP last sync: 999000000
Client IP: 192.168.2.14
Loops/sec: 1536
UM time[ms]: 0/1
Strip time[ms]: 0/18
Segments: 8 -> 2624B
                    Modes: 4*187=748B
                                     Data: 4*187=748B
                                                     Map: 2*0=0B
                                                                Local time: 15:36
                                                                                 ---DEBUG INFO---
Runtime: 3181847
Unix time: 1676734589,847
                         Free heap: 14056
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.2.14
Loops/sec: 1528
UM time[ms]: 0/1
Strip time[ms]: 0/18
Segments: 8 -> 2624B
                    Modes: 4*187=748B
                                     Data: 4*187=748B
                                                     Map: 2*0=0B

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3584, room 16
tail 0
chksum 0xb0
csum 0xb0
v3969889e
~ld

---WLED 0.14.0-b2 2302120 INIT---
esp8266 2_7_4_7
heap 27656
PIN ALLOC: Pin 1 successfully allocated by 0x89 (137)
Registering usermods ...
Reading config
Reading settings from /wsec.json...
JSON buffer locked. (3)
JSON buffer released. (3)
JSON buffer locked. (1)
Reading settings from /cfg.json...
Removing all.
PIN ALLOC: Pin 4 successfully allocated by 0x82 (130)
Successfully inited strip 0 (len 160) with type 22 and pins 4,255 (itype 4)
                                                                           Starting usermod config.
JSON buffer released. (1)
Initializing strip
Request to apply preset: 1
Usermods setup
lastReconnectAttempt == 0
Access point disabled (init).
Connecting to Changeme...
JSON buffer locked. (9)
Applying preset: 1
JSON buffer released. (9)

Connected! IP address: 192.168.2.14
Init STA interfaces
mDNS started

**Comment by blazoncek** [comment]
If you are using GPIO4 for LEDs, reconsider using GPIO2 or GPIO1 (not available with debug build).
Those are hardware assisted.

WDT means MCU did not get enough time to process other tasks. There is nothing that can be done in such case.
If you keep getting resets, even with GPIO2, try ESP32.

**Comment by ghwaldo** [comment]
> Ok here are debug traces from 2 random resets
> 
> **1st reboot**
> 
> JSON buffer released. (11) JSON buffer locked. (12) JSON buffer size: 5449 for WS request (3045). Sending WS data to a single client. JSON buffer released. (12) ---DEBUG INFO--- Runtime: 7624312 Unix time: 1676731389,312 Free heap: 13888 Wifi state: 3 State time: 0 NTP last sync: 999000000 Client IP: 192.168.2.14 Loops/sec: 1528 UM time[ms]: 0/1 Strip time[ms]: 0/17 Segments: 8 -> 2624B Modes: 4_187=748B Data: 4_187=748B Map: 2*0=0B
> 
> ets Jan 8 2013,rst cause:4, boot mode:(3,7)
> 
> wdt reset load 0x4010f000, len 3584, room 16 tail 0 chksum 0xb0 csum 0xb0 v3969889e ~ld
> 
> ---WLED 0.14.0-b2 2302120 INIT--- esp8266 2_7_4_7 heap 27656 PIN ALLOC: Pin 1 successfully allocated by 0x89 (137) Registering usermods ... Reading config Reading settings from /wsec.json... JSON buffer locked. (3) JSON buffer released. (3) JSON buffer locked. (1) Reading settings from /cfg.json... Removing all. PIN ALLOC: Pin 4 successfully allocated by 0x82 (130) Successfully inited strip 0 (len 160) with type 22 and pins 4,255 (itype 4) Starting usermod config. JSON buffer released. (1) Initializing strip Request to apply preset: 1 Usermods setup lastReconnectAttempt == 0 Access point disabled (init). Connecting to Changeme... JSON buffer locked. (9) Applying preset: 1 JSON buffer released. (9) Slow strip.
> 
> Connected! IP address: 192.168.2.14 Init STA interfaces mDNS started
> 
> **2nd reboot**
> 
> State time: 0 NTP last sync: 999000000 Client IP: 192.168.2.14 Loops/sec: 1536 UM time[ms]: 0/1 Strip time[ms]: 0/18 Segments: 8 -> 2624B Modes: 4_187=748B Data: 4_187=748B Map: 2_0=0B Local time: 15:36 ---DEBUG INFO--- Runtime: 3181847 Unix time: 1676734589,847 Free heap: 14056 Wifi state: 3 State time: 0 NTP last sync: 999000000 Client IP: 192.168.2.14 Loops/sec: 1528 UM time[ms]: 0/1 Strip time[ms]: 0/18 Segments: 8 -> 2624B Modes: 4_187=748B Data: 4_187=748B Map: 2_0=0B
> 
> ets Jan 8 2013,rst cause:4, boot mode:(3,7)
> 
> wdt reset load 0x4010f000, len 3584, room 16 tail 0 chksum 0xb0 csum 0xb0 v3969889e ~ld
> 
> ---WLED 0.14.0-b2 2302120 INIT--- esp8266 2_7_4_7 heap 27656 PIN ALLOC: Pin 1 successfully allocated by 0x89 (137) Registering usermods ... Reading config Reading settings from /wsec.json... JSON buffer locked. (3) JSON buffer released. (3) JSON buffer locked. (1) Reading settings from /cfg.json... Removing all. PIN ALLOC: Pin 4 successfully allocated by 0x82 (130) Successfully inited strip 0 (len 160) with type 22 and pins 4,255 (itype 4) Starting usermod config. JSON buffer released. (1) Initializing strip Request to apply preset: 1 Usermods setup lastReconnectAttempt == 0 Access point disabled (init). Connecting to Changeme... JSON buffer locked. (9) Applying preset: 1 JSON buffer released. (9)
> 
> Connected! IP address: 192.168.2.14 Init STA interfaces mDNS started

Did you manage to get it work with no resets ?
Got the same here. Sometimes 5hrs working, sometimes only few minutes.
