### ISSUE TITLE
MQTT does not receive double button press if no preset is selected in WLED interface

### ISSUE THREAD

**Issue by cssinate** [Aircoookie/WLED#3109]
### What happened?

In the WLED UI, if I have the "double" action set to `0` (for no preset), MQTT never publishes `double` for the button. It just publishes two quick `short` events in succession. If I change the "double" action to any other preset, then MQTT does publish the `double` event.

### To Reproduce Bug

I have an ESP8266, with a momentary switch attached. WLED is synced with MQTT. In the WLED UI, I set the "double" action to 0. MQTT only publishes `long` and `short` button presses. Any attempts at a double click of the button only result in two successive `short` publications.

I created a new Preset with the API command `{}` and assigned this preset to the double field in the WLED UI. Now MQTT publishes `double` without fail.

### Expected Behavior

MQTT should publish `double` no matter what the preset is set to in the WLED UI.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
This is expected behaviour for button 0.
If you want double press MQTT message without actual preset assigned, use button 1.
