### ISSUE TITLE
Add HEX Codes rather than just RGB values for JSON API or lengthen string allowance

### ISSUE THREAD

**Issue by makeitworktech** [Aircoookie/WLED#3110]
**Is your feature request related to a problem? Please describe.**
When using the JSON API to individually address LEDs, there is maximum limit on the length of the API string. This means that for more complex pixel art using a 32x32 matrix for example, I can't send the entire image in 1 command, and have to create two instead.

**Describe the solution you'd like**
Two possible solutions I see, and forgive me if it sounds naïve, but I don't have a programming background.

First solution, change the API to allow HEX codes as well as RGB values. Currently RGB values are allowed in the format ``` ID1,ID2,[rrr,ggg,bbb] ```. Would be nice to see HEX codes allow in a format like  ``` ID1,ID2,[HEXCODE] ```. 

Second solution, change the allowed length for API commands to 2x or more the length currently allowed.

**Describe alternatives you've considered**
I guess I described one above.

**Additional context**
Here I can give two examples of JSON API info, saved as presets in WLED. If you have a 32x32 matrix, you can paste them into a preset and you'll see the pixel art I'm creating.

First preset: 
`{"on":true,"bri":100,"seg":{"i":[0,1024,[0,0,0],0,17,[255,255,255],17,20,[204,0,0],20,24,[255,0,0],24,47,[255,255,255],47,50,[204,0,0],50,[165,0,33],51,56,[255,0,0],56,[204,0,0],57,[255,0,0],58,77,[255,255,255],77,80,[204,0,0],80,[255,0,0],81,[165,0,33],82,[255,0,0],83,85,[165,0,33],85,87,[255,0,0],87,[165,0,33],88,90,[255,0,0],90,[255,80,80],91,108,[255,255,255],108,111,[204,0,0],111,113,[255,0,0],113,[165,0,33],114,117,[255,0,0],117,119,[165,0,33],119,123,[255,0,0],123,[255,80,80],124,140,[255,255,255],140,142,[204,0,0],142,144,[255,0,0],144,[204,0,0],145,150,[255,0,0],150,152,[165,0,33],152,155,[255,0,0],155,[204,0,0],156,[255,80,80],157,171,[255,255,255],171,173,[204,0,0],173,176,[255,0,0],176,[204,0,0],177,181,[255,0,0],181,[165,0,33],182,184,[255,0,0],184,[165,0,33],185,[255,0,0],186,[165,0,33],187,189,[255,0,0],189,[255,80,80],190,192,[255,255,255],192,[255,0,0],193,203,[255,255,255],203,205,[204,0,0],205,207,[255,0,0],207,[204,0,0],208,[255,0,0],209,212,[165,0,33],212,[255,0,0],213,[165,0,33],214,217,[255,0,0],217,[165,0,33],218,220,[255,0,0],220,222,[204,0,0],222,[255,80,80],223,[255,255,255],224,226,[255,0,0],226,234,[255,255,255],234,237,[204,0,0],237,[255,0,0],238,[204,0,0],239,244,[255,0,0],244,[165,0,33],245,249,[255,0,0],249,[165,0,33],250,[255,0,0],251,[204,0,0],252,255,[255,0,0],255,[255,255,255],256,[204,0,0],257,259,[255,0,0],259,266,[255,255,255],266,268,[204,0,0],268,270,[255,0,0],270,[204,0,0],271,276,[255,0,0],276,278,[165,0,33],278,282,[255,0,0],282,[204,0,0],283,[255,0,0],284,[204,0,0],285,287,[255,0,0],287,[255,80,80],288,293,[255,0,0],293,298,[255,255,255],298,300,[204,0,0],300,[255,0,0],301,[204,0,0],302,307,[255,0,0],307,[165,0,33],308,310,[255,0,0],310,[165,0,33],311,314,[255,0,0],314,[128,0,0],315,317,[255,0,0],317,[204,0,0],318,[255,0,0],319,[255,80,80],320,[204,0,0],321,[255,0,0],322,324,[204,0,0],324,327,[255,0,0],327,329,[255,255,255],329,332,[204,0,0],332,[255,0,0],333,[204,0,0],334,339,[255,0,0],339,[165,0,33],340,343,[255,0,0],343,[165,0,33],344,[255,0,0],345,[128,0,0],347,[128,0,0],348,[204,0,0],349,351,[255,0,0],351,[255,80,80],352,359,[204,0,0],359,362,[165,0,33],362,364,[204,0,0],364,[165,0,33],365,[204,0,0],366,370,[255,0,0],370,[165,0,33],371,375,[255,0,0],375,[165,0,33],376,[255,0,0],379,[165,0,33],380,[204,0,0],381,[255,0,0],382,[204,0,0],383,[255,0,0],384,389,[204,0,0],389,[165,0,33],390,393,[204,0,0],393,[165,0,33],394,396,[204,0,0],396,[165,0,33],397,402,[255,0,0],402,[165,0,33],403,408,[255,0,0],408,[128,0,0],410,[128,128,128],412,414,[204,0,0],414,416,[255,0,0],416,420,[204,0,0],420,[165,0,33],421,424,[204,0,0],424,[165,0,33],425,428,[204,0,0],428,[165,0,33],429,434,[255,0,0],434,[165,0,33],435,440,[255,0,0],441,[128,128,128],442,[191,191,191],443,[128,128,128],445,448,[255,0,0],448,451,[204,0,0],451,[165,0,33],452,456,[204,0,0],456,[165,0,33],457,459,[204,0,0],459,467,[165,0,33],467,472,[255,0,0],473,[191,191,191],474,[255,255,255],475,[191,191,191],477,479,[204,0,0],479,[255,0,0],480,483,[204,0,0],483,[165,0,33],484,488,[204,0,0],488,[165,0,33],489,491,[204,0,0],491,493,[165,0,33],493,[204,0,0],494,498,[255,0,0],498,500,[165,0,33]]}}`

Second preset:
`{"on":true,"bri":100,"seg":{"i":[500,503,[255,0,0],503,[128,0,0],505,[191,191,191],506,[255,255,255],507,[191,191,191],509,[128,0,0],510,512,[255,0,0],512,514,[204,0,0],514,[165,0,33],515,520,[204,0,0],520,[165,0,33],521,523,[204,0,0],523,[165,0,33],524,[128,0,0],525,[204,0,0],526,530,[255,0,0],530,[165,0,33],531,[255,0,0],532,534,[165,0,33],534,[255,0,0],535,[128,0,0],537,[191,191,191],538,[255,255,255],539,[191,191,191],541,[128,0,0],542,[255,0,0],543,[255,255,255],544,546,[204,0,0],546,[165,0,33],547,551,[204,0,0],551,[165,0,33],552,554,[204,0,0],554,556,[165,0,33],556,[128,0,0],557,559,[204,0,0],559,562,[255,0,0],562,[165,0,33],563,566,[255,0,0],566,[165,0,33],567,[128,0,0],569,572,[191,191,191],573,[165,0,33],574,[255,0,0],575,[255,255,255],576,588,[165,0,33],588,[128,0,0],589,[204,0,0],590,595,[255,0,0],595,[165,0,33],596,600,[255,0,0],601,[128,128,128],602,[191,191,191],603,[128,128,128],604,[128,0,0],605,[255,0,0],606,608,[255,255,255],608,610,[204,0,0],610,[165,0,33],611,615,[204,0,0],615,[165,0,33],616,618,[204,0,0],618,[165,0,33],619,621,[128,0,0],621,624,[204,0,0],624,627,[255,0,0],627,[165,0,33],628,632,[255,0,0],632,[128,0,0],636,[165,0,33],637,640,[255,255,255],640,642,[204,0,0],642,[165,0,33],643,648,[204,0,0],648,651,[165,0,33],651,653,[128,0,0],653,655,[204,0,0],655,660,[255,0,0],660,[165,0,33],661,665,[255,0,0],665,668,[128,0,0],668,672,[255,255,255],672,674,[204,0,0],674,[165,0,33],675,680,[204,0,0],680,682,[165,0,33],682,685,[128,0,0],685,[204,0,0],686,[255,0,0],687,[204,0,0],688,692,[255,0,0],692,[165,0,33],693,696,[255,0,0],696,[165,0,33],697,700,[255,0,0],700,704,[255,255,255],704,706,[204,0,0],706,[165,0,33],707,710,[204,0,0],710,713,[165,0,33],713,717,[128,0,0],717,[165,0,33],718,[204,0,0],719,723,[255,0,0],723,725,[165,0,33],725,[255,0,0],726,728,[165,0,33],728,732,[255,0,0],732,736,[255,255,255],736,738,[204,0,0],738,[165,0,33],739,741,[204,0,0],741,743,[165,0,33],743,750,[128,0,0],750,752,[204,0,0],752,755,[165,0,33],755,757,[255,0,0],757,[165,0,33],758,763,[255,0,0],763,768,[255,255,255],768,771,[204,0,0],771,774,[165,0,33],774,777,[128,0,0],777,781,[255,255,255],781,[128,0,0],782,784,[165,0,33],784,[204,0,0],785,790,[255,0,0],790,[165,0,33],791,794,[255,0,0],794,800,[255,255,255],800,804,[204,0,0],804,806,[165,0,33],806,[128,0,0],807,814,[255,255,255],814,[128,0,0],815,817,[165,0,33],817,[204,0,0],818,824,[255,0,0],824,832,[255,255,255],832,836,[204,0,0],836,[165,0,33],837,[128,0,0],838,847,[255,255,255],847,[128,0,0],848,850,[165,0,33],850,[204,0,0],851,855,[255,0,0],855,864,[255,255,255],864,867,[204,0,0],867,869,[165,0,33],869,[255,0,0],870,880,[255,255,255],880,882,[128,0,0],882,[165,0,33],883,[204,0,0],884,886,[255,0,0],886,896,[255,255,255],896,898,[204,0,0],898,900,[165,0,33],900,[204,0,0],901,[255,0,0],902,914,[255,255,255],914,[128,0,0],915,[165,0,33],916,[255,0,0],917,928,[255,255,255],928,[204,0,0],929,931,[165,0,33],931,[204,0,0],932,935,[255,0,0],935,960,[255,255,255],960,962,[165,0,33],962,964,[204,0,0],964,968,[255,0,0],968,992,[255,255,255],992,[165,0,33],993,[204,0,0],994,[255,0,0],995,997,[204,0,0],997,1001,[255,0,0],1001,1024,[255,255,255]]}}`

Both together (won't work because of length of API command):
`{"on":true,"bri":100,"seg":{"i":[0,1024,[0,0,0],0,17,[255,255,255],17,20,[204,0,0],20,24,[255,0,0],24,47,[255,255,255],47,50,[204,0,0],50,[165,0,33],51,56,[255,0,0],56,[204,0,0],57,[255,0,0],58,77,[255,255,255],77,80,[204,0,0],80,[255,0,0],81,[165,0,33],82,[255,0,0],83,85,[165,0,33],85,87,[255,0,0],87,[165,0,33],88,90,[255,0,0],90,[255,80,80],91,108,[255,255,255],108,111,[204,0,0],111,113,[255,0,0],113,[165,0,33],114,117,[255,0,0],117,119,[165,0,33],119,123,[255,0,0],123,[255,80,80],124,140,[255,255,255],140,142,[204,0,0],142,144,[255,0,0],144,[204,0,0],145,150,[255,0,0],150,152,[165,0,33],152,155,[255,0,0],155,[204,0,0],156,[255,80,80],157,171,[255,255,255],171,173,[204,0,0],173,176,[255,0,0],176,[204,0,0],177,181,[255,0,0],181,[165,0,33],182,184,[255,0,0],184,[165,0,33],185,[255,0,0],186,[165,0,33],187,189,[255,0,0],189,[255,80,80],190,192,[255,255,255],192,[255,0,0],193,203,[255,255,255],203,205,[204,0,0],205,207,[255,0,0],207,[204,0,0],208,[255,0,0],209,212,[165,0,33],212,[255,0,0],213,[165,0,33],214,217,[255,0,0],217,[165,0,33],218,220,[255,0,0],220,222,[204,0,0],222,[255,80,80],223,[255,255,255],224,226,[255,0,0],226,234,[255,255,255],234,237,[204,0,0],237,[255,0,0],238,[204,0,0],239,244,[255,0,0],244,[165,0,33],245,249,[255,0,0],249,[165,0,33],250,[255,0,0],251,[204,0,0],252,255,[255,0,0],255,[255,255,255],256,[204,0,0],257,259,[255,0,0],259,266,[255,255,255],266,268,[204,0,0],268,270,[255,0,0],270,[204,0,0],271,276,[255,0,0],276,278,[165,0,33],278,282,[255,0,0],282,[204,0,0],283,[255,0,0],284,[204,0,0],285,287,[255,0,0],287,[255,80,80],288,293,[255,0,0],293,298,[255,255,255],298,300,[204,0,0],300,[255,0,0],301,[204,0,0],302,307,[255,0,0],307,[165,0,33],308,310,[255,0,0],310,[165,0,33],311,314,[255,0,0],314,[128,0,0],315,317,[255,0,0],317,[204,0,0],318,[255,0,0],319,[255,80,80],320,[204,0,0],321,[255,0,0],322,324,[204,0,0],324,327,[255,0,0],327,329,[255,255,255],329,332,[204,0,0],332,[255,0,0],333,[204,0,0],334,339,[255,0,0],339,[165,0,33],340,343,[255,0,0],343,[165,0,33],344,[255,0,0],345,[128,0,0],347,[128,0,0],348,[204,0,0],349,351,[255,0,0],351,[255,80,80],352,359,[204,0,0],359,362,[165,0,33],362,364,[204,0,0],364,[165,0,33],365,[204,0,0],366,370,[255,0,0],370,[165,0,33],371,375,[255,0,0],375,[165,0,33],376,[255,0,0],379,[165,0,33],380,[204,0,0],381,[255,0,0],382,[204,0,0],383,[255,0,0],384,389,[204,0,0],389,[165,0,33],390,393,[204,0,0],393,[165,0,33],394,396,[204,0,0],396,[165,0,33],397,402,[255,0,0],402,[165,0,33],403,408,[255,0,0],408,[128,0,0],410,[128,128,128],412,414,[204,0,0],414,416,[255,0,0],416,420,[204,0,0],420,[165,0,33],421,424,[204,0,0],424,[165,0,33],425,428,[204,0,0],428,[165,0,33],429,434,[255,0,0],434,[165,0,33],435,440,[255,0,0],441,[128,128,128],442,[191,191,191],443,[128,128,128],445,448,[255,0,0],448,451,[204,0,0],451,[165,0,33],452,456,[204,0,0],456,[165,0,33],457,459,[204,0,0],459,467,[165,0,33],467,472,[255,0,0],473,[191,191,191],474,[255,255,255],475,[191,191,191],477,479,[204,0,0],479,[255,0,0],480,483,[204,0,0],483,[165,0,33],484,488,[204,0,0],488,[165,0,33],489,491,[204,0,0],491,493,[165,0,33],493,[204,0,0],494,498,[255,0,0],498,500,[165,0,33],500,503,[255,0,0],503,[128,0,0],505,[191,191,191],506,[255,255,255],507,[191,191,191],509,[128,0,0],510,512,[255,0,0],512,514,[204,0,0],514,[165,0,33],515,520,[204,0,0],520,[165,0,33],521,523,[204,0,0],523,[165,0,33],524,[128,0,0],525,[204,0,0],526,530,[255,0,0],530,[165,0,33],531,[255,0,0],532,534,[165,0,33],534,[255,0,0],535,[128,0,0],537,[191,191,191],538,[255,255,255],539,[191,191,191],541,[128,0,0],542,[255,0,0],543,[255,255,255],544,546,[204,0,0],546,[165,0,33],547,551,[204,0,0],551,[165,0,33],552,554,[204,0,0],554,556,[165,0,33],556,[128,0,0],557,559,[204,0,0],559,562,[255,0,0],562,[165,0,33],563,566,[255,0,0],566,[165,0,33],567,[128,0,0],569,572,[191,191,191],573,[165,0,33],574,[255,0,0],575,[255,255,255],576,588,[165,0,33],588,[128,0,0],589,[204,0,0],590,595,[255,0,0],595,[165,0,33],596,600,[255,0,0],601,[128,128,128],602,[191,191,191],603,[128,128,128],604,[128,0,0],605,[255,0,0],606,608,[255,255,255],608,610,[204,0,0],610,[165,0,33],611,615,[204,0,0],615,[165,0,33],616,618,[204,0,0],618,[165,0,33],619,621,[128,0,0],621,624,[204,0,0],624,627,[255,0,0],627,[165,0,33],628,632,[255,0,0],632,[128,0,0],636,[165,0,33],637,640,[255,255,255],640,642,[204,0,0],642,[165,0,33],643,648,[204,0,0],648,651,[165,0,33],651,653,[128,0,0],653,655,[204,0,0],655,660,[255,0,0],660,[165,0,33],661,665,[255,0,0],665,668,[128,0,0],668,672,[255,255,255],672,674,[204,0,0],674,[165,0,33],675,680,[204,0,0],680,682,[165,0,33],682,685,[128,0,0],685,[204,0,0],686,[255,0,0],687,[204,0,0],688,692,[255,0,0],692,[165,0,33],693,696,[255,0,0],696,[165,0,33],697,700,[255,0,0],700,704,[255,255,255],704,706,[204,0,0],706,[165,0,33],707,710,[204,0,0],710,713,[165,0,33],713,717,[128,0,0],717,[165,0,33],718,[204,0,0],719,723,[255,0,0],723,725,[165,0,33],725,[255,0,0],726,728,[165,0,33],728,732,[255,0,0],732,736,[255,255,255],736,738,[204,0,0],738,[165,0,33],739,741,[204,0,0],741,743,[165,0,33],743,750,[128,0,0],750,752,[204,0,0],752,755,[165,0,33],755,757,[255,0,0],757,[165,0,33],758,763,[255,0,0],763,768,[255,255,255],768,771,[204,0,0],771,774,[165,0,33],774,777,[128,0,0],777,781,[255,255,255],781,[128,0,0],782,784,[165,0,33],784,[204,0,0],785,790,[255,0,0],790,[165,0,33],791,794,[255,0,0],794,800,[255,255,255],800,804,[204,0,0],804,806,[165,0,33],806,[128,0,0],807,814,[255,255,255],814,[128,0,0],815,817,[165,0,33],817,[204,0,0],818,824,[255,0,0],824,832,[255,255,255],832,836,[204,0,0],836,[165,0,33],837,[128,0,0],838,847,[255,255,255],847,[128,0,0],848,850,[165,0,33],850,[204,0,0],851,855,[255,0,0],855,864,[255,255,255],864,867,[204,0,0],867,869,[165,0,33],869,[255,0,0],870,880,[255,255,255],880,882,[128,0,0],882,[165,0,33],883,[204,0,0],884,886,[255,0,0],886,896,[255,255,255],896,898,[204,0,0],898,900,[165,0,33],900,[204,0,0],901,[255,0,0],902,914,[255,255,255],914,[128,0,0],915,[165,0,33],916,[255,0,0],917,928,[255,255,255],928,[204,0,0],929,931,[165,0,33],931,[204,0,0],932,935,[255,0,0],935,960,[255,255,255],960,962,[165,0,33],962,964,[204,0,0],964,968,[255,0,0],968,992,[255,255,255],992,[165,0,33],993,[204,0,0],994,[255,0,0],995,997,[204,0,0],997,1001,[255,0,0],1001,1024,[255,255,255]]}}`

I've attached the PEEK view of the two presets I showed.

Thank you for your ideas for making WLED better!

![spiderman1](https://user-images.githubusercontent.com/90069122/222125578-b3cd1009-6b64-44c2-8f28-5f5400b7f02d.jpg)
![spiderman2](https://user-images.githubusercontent.com/90069122/222125594-700c0001-491f-44ce-a736-0d44b3c77174.jpg)

**Comment by blazoncek** [comment]
Please check API in [KB](https://kno.wled.ge/interfaces/json-api/#per-segment-individual-led-control)

Feature has been implemented a while ago.
You can also compile with `-D WLED_ENABLE_PIXART` to enable embedded pixel art converter (available on http://device_IP/pixart.htm) or use external from @werkstrom which optimizes JSON.
