### ISSUE TITLE
Gamma correction does not apply to UDP realtime

### ISSUE THREAD

**Issue by CarbonNeuron** [Aircoookie/WLED#3112]
### What happened?

When using DRGB, or WARLS (It may be on all of the UDP realtime packet types, I haven't tried all of them), Gamma color correction is not applied to the output even when the respected options are turned on (Use Gamma correction for color).

### To Reproduce Bug

Sending #FFA500 to the LEDs over UDP realtime using DRGB or WARLS produces a non color corrected yellow color.
Shown Here:
![image](https://user-images.githubusercontent.com/16768821/222463909-da37e158-0e81-4236-9a85-e477979985b2.png)

### Expected Behavior

I expect that gamma correction is applied to UDP realtime LEDs when the option is enabled. Here is a picture of what it looks like when applying gamma correction on the sender side.
![image](https://user-images.githubusercontent.com/16768821/222464326-43fa7693-2ca8-4e4d-b364-4dc0bc0ab6ca.png)
 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED v0.13.3 (Build 2208222)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CarbonNeuron** [comment]
I've found the option that disables realtime gamma correction under Settings -> Sync Interfaces -> E1.31 Info. This is handled correctly on WLED v0.13.3 (Build 2208222), but not on the latest development build. In the GetV() function an exception is thrown that says d.Sf.PY.value = 0 cannot set value on undefined. PY does not exist, so it can't load any settings past that.

**Comment by blazoncek** [comment]
Clear cache ans local storage.
Settings save works as expected.
