### ISSUE TITLE
More security for public use.

### ISSUE THREAD

**Issue by TysTies** [Aircoookie/WLED#3115]
**I have WLED devices in the county fair. Last year someone deleted all my presets from their device. Luckily, I had them exported :) With the new feature that gives the option that makes it so people can't make changes to the settings without a pin/password, I am wondering if there could be a way that people could view the presets but need a pin/password to change/delete them.

**Comment by blazoncek** [comment]
This (or similar) was requested several times.
Unfortunately it would require re-engineering of entire WLED work-flow and is infeasible ATM.
