### ISSUE TITLE
Create and edit custom palettes via API

### ISSUE THREAD

**Issue by Wegi** [Aircoookie/WLED#3117]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an enhanced experience.

**Describe the solution you'd like**
I would like to use the JSON or HTTP API to upload or edit a custom palette. Currently, the /edit interface needs to be used, which does not work as nicely, because the user has to do some actions.

**Additional context**
The goal is to create and edit the palettes via API, so an enduser does not have to do anything manually, like uploading files.

Thanks for the very good work on WLED.

**Comment by blazoncek** [comment]
Please see #246 and contribute if you can.
Closed as a duplicate.
