### ISSUE TITLE
Async E1.31

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#312]
Switching to async library will likely increase performance and stability.
On hold until 0.8.6 connectivity issues are resolved.

**Comment by yusufsulaiman** [comment]
hi. I have tried connecting Jinx software with E131, for 300 LEDs it is stable, but for 400/500/600 LEDs there is a delay

**Comment by debsahu** [comment]
Hope this helps: https://github.com/debsahu/E131_PixelPusher
