### ISSUE TITLE
Relay or Mosfet with WLED

### ISSUE THREAD

**Issue by Gagghe89** [Aircoookie/WLED#3129]
HI. First of all congratulations for the project which I find very creative and always improving with the addition of features. Compliments.
But I wanted to ask you something. I'm making PCBs for a personal project and I don't want to use relays both for the noise when they close and for the consumption of the coil, etc. I was aiming at using a mosfet instead of a relay.
1) How do you see it? It's possible?
2) I'm not very familiar with addressable leds (ws2812, ws2811 etc) but watching videos I noticed that with WLED many who use the relay position the relay on the + of the power supply. For example in the case of the WS2812 they put the +5v on the common of the relay and then on the closure of the relay the power supply of the ws2812 leds. However, in doing so, does the DATA track always remain powered? Or does this not happen because the DATA track and the PIN to which I connect the Relay are activated together by the ESP8266 and therefore until the ESP8266 has a command the pins remain in HIGH IMPEDANCE and therefore have no consumption? 

Thank you

**Comment by blazoncek** [comment]
Hi. Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Please also see [KB](https://kno.wled.ge) for some common scenarios and wiring instructions.
Not a software related issue. Closing.
