### ISSUE TITLE
2D Matrix over 1024px not working correctly

### ISSUE THREAD

**Issue by gwwiktor** [Aircoookie/WLED#3131]
### What happened?

Bottom half of the display does the same thing that the last correctly working LED and animations are doubled on the left and right side when 2D matrix contains more than 1024 pixels. My example contains 1800 pixels configured in 60x30 2D Matrix.

### To Reproduce Bug

1. Install WLED v0.14.0-b2 (build 2303050) or v0.14.0-b1
2. Configure outputs for 1800LEDs
    <img src="https://user-images.githubusercontent.com/94049168/225424729-07807948-c64e-40be-8d01-300b2c717b66.PNG" width=7% height=7%>
3. Configure 2D Matrix to 60x30 pixels, Vertical, Serpentine checked
    <img src="https://user-images.githubusercontent.com/94049168/225425330-8d926a66-8bef-419f-8c6e-b2df9c04f234.PNG" width=7% height=7%>
4. Try to use Effects and observe

### Expected Behavior

2D Matrix is expected to display chosen animation on the whole surface and each pixel is expected to be driven independently

### Install Method

Binary from WLED.me

### What version of WLED?

WLED v0.14.0-b2 (build 2303050)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Similar issue was mentioned before, but in fact it is not fixed in the newest build
[https://github.com/Aircoookie/WLED/issues/3120](url)

Bottom half working incorrectly and the arrow pointed to the last working LED:
<img src="https://user-images.githubusercontent.com/94049168/225421567-ea4ee0c8-5bb7-4365-be26-9c24f1b01afc.jpg" width=12% height=12%>

<img src="https://user-images.githubusercontent.com/94049168/225422202-dbd96121-01fa-4fb1-ab4d-350f1eb580fb.jpg" width=12% height=12%>

Doubled animation on the upper half of the matrix and bottom not working:
<img src="https://user-images.githubusercontent.com/94049168/225422642-b2c250a7-4e30-4dd1-aad9-c5dde2001fa6.jpg" width=12% height=12%>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please send pictures of actual LED output, not peek preview.

**Comment by gwwiktor** [comment]
Thank you for such fast response and also forgive me my lack of consideration. I did not think of possibility of broken peek preview and I didn’t try connecting LEDs as I thought preview reflects actual output data. I’ll try to do better next time

**Comment by blazoncek** [comment]
@ewoudwijma could you look into this?

**Comment by MoonModules** [comment]
Change the following in ws.cpp / sendLiveLedsWs :

  const uint16_t MAX_LIVE_LEDS_WS = strip.isMatrix ? 4096 : 256; //WLEDMM use 4096 as max matrix size

instead of 1024

**Comment by blazoncek** [comment]
> Change the following in ws.cpp / sendLiveLedsWs :
> const uint16_t MAX_LIVE_LEDS_WS = strip.isMatrix ? 4096 : 256; //WLEDMM use 4096 as max matrix size

Unfortunately this may have adverse consequences as the size of 4096 may still not be adequate. It will also needlessly send *all* matrix LEDs to a peek client possibly overwhelming MCU.
I'd much rather see a scaled approach in the same way current 1D LEDs are handled.

**Comment by MoonModules** [comment]
Maybe ... but as long as that functionality is not in place, 4096 is better then 1024, note that only total leds are sent so if you have a matrix of 16x16 only 256 pixels are sent, so it's in your own hands ;-)
4096 working fine in WLED MM until now.

**Comment by blazoncek** [comment]
I've now written matrix scaling if matrix is bigger than 256 pixels.
It works for any size of matrix up to 8192 pixels.

It does not look best when matrix is above 256 pixels, but reduces strain on ESP so ESP8266 can also provide peek on matrices of 512 pixels or more.

It will be available after a while.

**Comment by MoonModules** [comment]
Nice!

Less nice is it does not look best ...

Can't you make it conditional on esp8266? And make it higher then 256 bytes, 1024 sounds better

**Comment by kmatokov** [comment]
HI, i use 4x1052 out in matrix, it look correct on led matrix but visualization is wrong, not showing configured led but some reduced and shifted. when use low amount of pixel it work correct. not so important but when work remote it would be more handy to see what is currently playing.
