### ISSUE TITLE
Wifi login with username + password

### ISSUE THREAD

**Issue by Kurzhalsgiraffe** [Aircoookie/WLED#3133]
Some Wireless LANs require a login via WLAN-SSID + Username + Password. Im unable to use those Networks, because WLED doesnt provide a login with a username.

Im not 100% sure, but i think this authentication is called "WLAN Enterprise Mode".

Consider adding a username field to the WLAN settings in order to log into.

**Comment by blazoncek** [comment]
Enterprise WLAN mode is not supported. Yet.
