### ISSUE TITLE
E1.31 in 0.14  - 1d vs 2d

### ISSUE THREAD

**Issue by flloyd-aa7bq** [Aircoookie/WLED#3136]
**Is your feature request related to a problem? Please describe.**
Using e1.31 in 1D, the LED string presents as a linear array.   With e1.31 in 2D mode, the array goes nonlinear, and the folding provided by the serpentine transformation scrambles the LED positions.

I have a 20x20 matrix made of 400 WS2811s in one long string.  The layout of the matrix is serpentine.  The WLED 2D effects configure and work flawlessly, as do the 1D effects.   Rendering under xLights using e1.31, however, is only normal in 1D mode.  Using e1.31 in 2D mode results in a scrambled presentation.   BTW, my displays use WLED effects part-time and xLights effects at others.

**Describe the solution you'd like**
It would be very helpful if a setting existed whereby e1.31 could be directed to use either the 1D or the 2D configuration exclusively.

**Describe alternatives you've considered**
The alternative is to change my xLights model to account for the WLED scrambling.  In a mixed environment using controllers from multiple vendors, the same xLights model should work on any controller.   This alternative creates a WLED-specific model and effectively doubles the work of setting it up.

**Additional context**
The mapping and gap spacing provided by the 2D should not take effect under e1.31.  The actual physical layout of the LEDs must be preserved at the interface to the outside world.  

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
WLED always respected ledmaps, even when dealing with E1.31 input.

2D functionality builds internal ledmap which serves to simplify any and all 2D functions and allows uniform approach to draw on 2D surface. As such it allows you to build matrix from unequal panels oriented in any orientation possible (serpentine or not).

As E1.31 functionality respects ledmaps it is not possible to disregard internally built up ledmap as that would be a breaking change.

As a workaround you can create a custom ledmap containing only one pixel and use that when switching to E1.31 input. When switching back to WLED effects change to default ledmap. Custom ledmap will remove (or override) internally built one exposing raw LED arrangement (if you only use 1 pixel in ledmap).
To switch ledmaps using JSON API use: `{"ledmap":X}` to switch to `ledmapX.json` file (where X is a digit from 1 to 9) and `{"ledmap":0}` to switch to default ledmap.

For ledmap functionality check [KB](https://kno.wled.ge/advanced/mapping/).
