### ISSUE TITLE
New light control interface - Home Assistant API

### ISSUE THREAD

**Issue by Nornode** [Aircoookie/WLED#314]
I'm thinking of testing this out as I'd like better support for LED strips specifically. I know it would be very much easier to integrate into Homeassistant with its own HomeAssistant API  much like ESPhome has and adoption rate with HA users would rise!

It is currently possible but the configuration with MQTT isn't for everyone and adoption is much slower with a lot of troubleshooting involved if it's not working correctly.

Please consider supporting native HomeAssistant API.

**Comment by TheZoker** [comment]
I think this issue can be closed :wink: 
https://github.com/home-assistant/home-assistant/pull/28542

**Comment by Nornode** [comment]
Woohaa! Awesomeness!! 😍👍
