### ISSUE TITLE
Make segments individually on/off when controlled with diyHUE

### ISSUE THREAD

**Issue by Aaroneisele55** [Aircoookie/WLED#3143]
**Is your feature request related to a problem? Please describe.**
I am annoyed by the fact that you can't turn off individual segments from external systems such as diyHUE and that it turns off the whole strip/light instead

**Describe the solution you'd like**
The segments should have extra on/off state as they have in the "segments" page in the UI

**Describe alternatives you've considered**
If this doesn't work, I can't really use this with diyHUE and I'd have to delete my segments to make it usable.

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Segments have API that allows them to act independently.
But one has to have HUE (or compatible) hardware to develop WLED integration.

**Comment by Aaroneisele55** [comment]
> Segments have API that allows them to act independently.
> But one has to have HUE (or compatible) hardware to develop WLED integration.

They (currently) have all features except turning on/off individual segments.
If this would be implemented, external apps could handle multiple segments much better

**Comment by blazoncek** [comment]
You are welcome to add implementation if you own HUE.

**Comment by Aaroneisele55** [comment]
> You are welcome to add implementation if you own HUE.
Unfortunately, I'm not that good at progrmming and imto do this
>But one has to have HUE (or compatible) hardware to develop WLED integration.

**Comment by Aaroneisele55** [comment]
>But one has to have HUE (or compatible) hardware to develop WLED integration.
No, it also works if you only have WLED and a computer on which diyHUE runs (can also be a Pi Zero W on which I run it)

**Comment by blazoncek** [comment]
I have no intention of using HUE or diyHUE. 😄
