### ISSUE TITLE
Adjustable Random Cycle Color Time

### ISSUE THREAD

**Issue by DarthWeber** [Aircoookie/WLED#3147]
Random Cycle Color Time seems to be fixed to 5s  - which results in restless color changes in my opinion. It would be great to have this time adjustable e.g. simple in the web control like transisition times.

**Comment by blazoncek** [comment]
Where would you expect to set this?

**Comment by DarthWeber** [comment]
Hi, maybe under LED Settings where you set the transisiotn time ?

**Comment by blazoncek** [comment]
![Screenshot 2023-03-24 at 20 30 10](https://user-images.githubusercontent.com/7722392/227622080-223e4c8e-369e-4e49-9244-2c7423d72b1c.png)
Seems to work well. Will be available shortly.

**Comment by DarthWeber** [comment]
Great ! Thanks a lot !

**Comment by DarthWeber** [comment]
Thank you very much - but is it possible to extend the setting to uint16 ? Now only times until 255s are possible. I would like to enter times for a couple of hours.

**Comment by blazoncek** [comment]
You did not specify that in your original request. 🤷‍♂️ 
Fork and adjust until I get another go at it.

**Comment by DarthWeber** [comment]
ah okay, sorry. I didnt expect this to be limited to a byte.
