### ISSUE TITLE
White Channel slider missing from >v14.

### ISSUE THREAD

**Issue by Shaps-77** [Aircoookie/WLED#3150]
### What happened?

When using the 'PWM White' option in LED preferences, the 'White Channel' slider is not present in the UI from version 14.0 onward.
Without this slider, you are unable to drive the channel.

The following pictures show the bug.

![LED setup and GPIO](https://user-images.githubusercontent.com/105588996/227806843-56b6915a-f490-4358-a4fb-88e834f5dcdb.png)
![Main UI_ No white channel slider](https://user-images.githubusercontent.com/105588996/227806907-f3cabff3-c957-43ce-932c-f9a0cdfd22c0.png)
![INFO page](https://user-images.githubusercontent.com/105588996/227806942-54bfe577-d524-4a1e-b428-9cbd384016d0.png)

The following picture show the correct functionality when compiling from v13.3

![Showing White Channel](https://user-images.githubusercontent.com/105588996/227807436-e7a5add0-232e-4a40-9403-c5b6e8fad50f.png)

Thanks as always Dev team 💯 

### To Reproduce Bug

Check UI for missing 'White Channel' slider  when using 'PWM White' in LED preferences.
I think the bug is only present from version 14.0 onward..

### Expected Behavior

'White Channel' slider should be present in UI.

### Install Method

Self-Compiled

### What version of WLED?

v14 onward

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use latest source 2303240 and clear browser cache and local storage.

**Comment by Shaps-77** [comment]
You're the man Blaž 🍻
All working fine with build 2303240 👍
