### ISSUE TITLE
Animated Staircase: Fading time between steps when switching states

### ISSUE THREAD

**Issue by niiccooo1** [Aircoookie/WLED#3156]
**Describe the solution you'd like**
At the moment every step is turning from on to off or from off to on instantly. 
It would be nice if you can setup a fade-out and fade-on time for every step to switch states.

@blazoncek 

Thank you in advance!

**Comment by blazoncek** [comment]
Just increase the transition time.

**Comment by niiccooo1** [comment]
I´ll try that. Thanks!
