### ISSUE TITLE
Issues with the effects page

### ISSUE THREAD

**Issue by Kentro1989** [Aircoookie/WLED#3165]
### What happened?

When I try to scroll through the effects page the intensity bar and timer bar pull down the effects options and they all disappears

### To Reproduce Bug

I enter the app and go to the effects tab and scroll

### Expected Behavior

To scroll through the effects options without a problem

### Install Method

Binary from WLED.me

### What version of WLED?

V0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use web browser. It may be a limitation of webview mobile app uses.
You may also want to try some unofficial apps if you do not want to use browser.

**Comment by blazoncek** [comment]
Please use web browser (Safari) and compare it also with Firefox, Opera or any other phone browser.

**Comment by roninniagara** [comment]
Yep. Same here. Seems to be a formatting issue. :(

**Comment by Uofuforever** [comment]
Is there a fix out there for this without using browser?

**Comment by blazoncek** [comment]
No, until app is updated.
Meanwhile you can use alternate "WLED Native" app by @Moustachauve
