### ISSUE TITLE
Show gradient of custom palette in UI

### ISSUE THREAD

**Issue by werkstrom** [Aircoookie/WLED#3167]
It would be nice if the gradient of the custom palettes would be visable like the gradients on the standard palettes, Would be much easier to select desired palette that way IMHO.

**Comment by blazoncek** [comment]
It is, unfortunately you need to clear local storage (or at least remove `wledPalx` entry) for the palette previews to be rebuilt. It is a known issue.
You can clear local storage from UI settings page.

**Comment by werkstrom** [comment]
Worked fine... Any way to do that via API?

**Comment by blazoncek** [comment]
I am looking at https://www.sohamkamani.com/javascript/localstorage-with-ttl-expiry/ to implement TTL for some local storage elements to expire after a while.

**Comment by werkstrom** [comment]
Aha... Would perhaps some sort of indicator that can be controlled from the "server" (WLED software) be an alternative? Like if you have a property in local storage that is "lastUpdate" so you know how old the data is, and then you can send a parameter with the page that suggests a reload and have a script compare and if the local data is older, then clear and reload. Example: If you set the "lastServerDataChange" to now() every time you reboot. And then check that time, compared to the local data you have. Could even be something in the UI like "The server suggests clearing you local storage, klick here to do it". I would imagine there are times (like when setting up) that you would like to reload this quite often and then long periods where nothing really changes... Which is why a TTL solution might not give the best experionce, IMHO

**Comment by werkstrom** [comment]
Lets close, not enought upside to justify effort

**Comment by blazoncek** [comment]
Once uploading custom palette via #3164 is possible I will update palette preview logic so that new palettes are reloaded.
