### ISSUE TITLE
WLED on raspberry Pi Pico W

### ISSUE THREAD

**Issue by luca-alexander-thomas** [Aircoookie/WLED#3174]
Is ist possible to run WLED on the new Rpi Pico W?

**Comment by softhack007** [comment]
No. WLED runs on espressif hardware exclusively (esp32 or esp8266)


Please don't abuse issue reports (aka bug reports) for support questions. Community support for WLED is in discord.

<br/>

<a href="https://discord.gg/KuqP7NE"><img src="https://discordapp.com/api/guilds/473448917040758787/widget.png?style=banner2" width="30%" align="middle"></a>
Join Discord to discuss [AirCookie's WLED](https://discord.gg/KuqP7NE).
