### ISSUE TITLE
Circular matrix

### ISSUE THREAD

**Issue by GrandNewbien** [Aircoookie/WLED#3178]
**Is your feature request related to a problem? Please describe.**

I'd love to be able to control a circular pattern matrix.

**Describe the solution you'd like**
I've built a >4600 LED circular display and would love to have effect work on it

The matrix limit is 128, but I've use standard 30LED/M strips, using the full 5 meters to build 31 radial spokes. 

**Describe alternatives you've considered**
Writing a custom effect

**Comment by blazoncek** [comment]
4600 is a lot of LEDs even for ESP32 in a matrix layout.
Theoretical matrix size limit is 255x255 but that will deplete RAM and may have adverse affect on WLED performance.

Regarding circular layout I'm afraid I will let you down. It will not happen any time soon as WLED 2D implementation is based on Catresian coordinates.

**Comment by dosipod** [comment]
Yeah not really possible unless you will do a custom mapping , for 4600 this would be really tricky from mapping and performance or even stability , I would think with this number of pixels you could go with something like xlight but might be you like to do things cause they are hard . Small example  with less leds but concept is the same 

https://user-images.githubusercontent.com/87589371/233555547-793e413c-eb16-480d-b117-8c89c85d9623.mov
https://discord.com/channels/473448917040758787/801531333067014164/1078979082345271327

**Comment by dosipod** [comment]
We also done 241 
![image](https://github.com/Aircoookie/WLED/assets/87589371/dc384f4a-5b92-4806-9c32-bb64f26074c4)
![June9__rings2](https://github.com/Aircoookie/WLED/assets/87589371/40b10e58-4726-4eff-a204-6aad63877f78)
![June9_text_rings](https://github.com/Aircoookie/WLED/assets/87589371/8a7844de-5915-4ed3-925a-4e6fb0f6000f)
