### ISSUE TITLE
Ability to disable Seconds from Analog Clock Overlay

### ISSUE THREAD

**Issue by Abulrock** [Aircoookie/WLED#3179]
**Is your feature request related to a problem? Please describe.**
No, just an option to disable seconds on the Analog Clock Overlay

**Describe the solution you'd like**
A simple check box

**Describe alternatives you've considered**
If possible to change colors of Hour, Minute, and Seconds

Purely an amazing project thank you for making the process incredibly simple
Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
There is an advanced version of analog clock overlay via usermod, It allows for more customizations.
Please use that (may require you to self compile WLED).

Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
