### ISSUE TITLE
2 sliders for the ‘ Spots ‘ effect 

### ISSUE THREAD

**Issue by Illumidel** [Aircoookie/WLED#3188]
In version 13 , there was 2 sliders for the Spots effect . Is it possible to bring this back ?
Is was giving us more options and flexibility to create regular pot lights effects

Thank you

❤️wled

**Comment by blazoncek** [comment]
Will do.

**Comment by blazoncek** [comment]
Fixed in 5e2fa1347109999712ffd05ef03924b33e74e3ce
