### ISSUE TITLE
Instance list, more info. 

### ISSUE THREAD

**Issue by theantnest** [Aircoookie/WLED#3200]
It would be amazing if there was an icon to show that an instance is a sync Master. 

![Screenshot_20230512-135201.png](https://github.com/Aircoookie/WLED/assets/12680421/37b6971d-4c3f-4e4d-8973-b875f103a9ef)

When you have a few controllers it would be super useful to know which is the group master and maybe even the sync group number it is controlling. Maybe a green number for master and a yellow number for slave, or similar?

**Comment by blazoncek** [comment]
Please re-post this issue on WLED app repository.
