### ISSUE TITLE
Titlebar Version 

### ISSUE THREAD

**Issue by hidra000** [Aircoookie/WLED#321]
Not realy an big issue but i have 0.8.6 running and the titlebar in chrome / firefox and Vivaldi is showing WLED 0.8.4 
Just a heads up to improve WLED

**Comment by raoulteeuwen** [comment]
Tx. Already noted, see https://github.com/Aircoookie/WLED/issues/296 ...

**Comment by Aircoookie** [comment]
I know :) closing as duplicate of #296.
