### ISSUE TITLE
Transition not applied in playlist to API preset

### ISSUE THREAD

**Issue by marcobrianza** [Aircoookie/WLED#3210]
### What happened?

I am creating a playlist based on presets created with WLED Pixel Art Converter.
The presets are applied immediately without the specified transition time in the playlist editor.
If I create e mixed playlist the transition is applied correctly to the presets created with "use current state" 

Should I add the transition in some way in the json api call?

### To Reproduce Bug

create a playlist with json commmands

### Expected Behavior

the transition time should be applied as cross fade

### Install Method

Binary from WLED.me

### What version of WLED?

standard release 0.14 and 0.13 (but also compiled from source today)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Pixel Art Converter generates pixels override (`"seg":[{...,"i":[...]}]`) which is incompatible with transitions as it is not *effect*.
Unfortunately nothing can be done.
