### ISSUE TITLE
Flag retain

### ISSUE THREAD

**Issue by InnateEvil** [Aircoookie/WLED#3217]
Good time! I ask you to add the option to enable the retain flag.

I have a lot of lamps on esp with WLED firmware.

And I use a smart home device that requires the retain flag to connect and configure MQTT for the first time.

I really like using WLED and I really want to add them to my smart home.

Maybe this feature has already been added, but I couldn't find it, help!!!! Thank you in advance!

**Comment by blazoncek** [comment]
Some messages are retained. Some are not.
LWT is also set.

**Comment by InnateEvil** [comment]
LWT?

**Comment by blazoncek** [comment]
Closing as a duplicate of #2263
