### ISSUE TITLE
"Turn LEDs on after power up/reset" conflicts with preset

### ISSUE THREAD

**Issue by MegoVaTx** [Aircoookie/WLED#3219]
### What happened?

When I uncheck "Turn LEDs on after power up/reset" and reboot leds won't turn of after reboot, which is perfect.
How ever when I select default preset controller ignores that setting and after reboot led DO turn On. 
I need Dafult preset to be what I want it to be and not to turn on after reboot, (powerloss)

### To Reproduce Bug

uncheck "Turn LEDs on after power up/reset" and type something into preset. Done "Turn LEDs on after power up/reset" will be ignored

### Expected Behavior

if "Turn LEDs on after power up/reset" unchecked then DO NOT Turn LEDs on after power up/reset

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use a preset a) with power off or b) without saved brightness.
