### ISSUE TITLE
Expose buttons in Home Assistant

### ISSUE THREAD

**Issue by Rodrigoah** [Aircoookie/WLED#3221]
**Is your feature request related to a problem? Please describe.**
Phisical buttons are not exposed in home assitant making impossible to trigger other home automations

**Describe the solution you'd like**
Buttons should show up as entities under the device in home assistant. Different behaviours could be set up depending if it is a button or a switch.

**Describe alternatives you've considered**
Switching to ESPHome

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Buttons are exposed to MQTT and you can add them as MQTT entities in HA.

BTW, HA is already stressing WLED too much and adding buttons (with the complexity they offer) might be too much for WLED to handle.
