### ISSUE TITLE
INMP441 interference from power source

### ISSUE THREAD

**Issue by Sle77en** [Aircoookie/WLED#3223]
### What happened?

Hello,

i did a 32x32 LED matrix of four 16x16 led panels. I used the led panels and power source from BFT-Lightning.
The power source is a 5V 60A power supply.
WLED itself works without any problems. Unfortunately is not working properly with the microphone. It seems that the power supply is interfering with the INMP441. Because if I use a different power source, for example, I don't have this problem. Is there a way to fix this problem?

### To Reproduce Bug

BFT Lightning LED Pannels and Powersuply 5v60a interference with the INMP441

### Expected Behavior

No interference. Maybe with a interference suppression filter

### Install Method

Binary from WLED.me

### What version of WLED?

WLED SR 

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
What you describe looks like a hardware problem. Unfortunately there is no solution possible in Software.

If your power source is not stabilized (i.e. it has voltage ripples) then adding a big capacitor between Vcc an GND.
https://kno.wled.ge/basics/getting-started/

Closing, as this problem cannot be solved in software/firmware.
