### ISSUE TITLE
Random flickering when connect to homeassistant

### ISSUE THREAD

**Issue by benas1989** [Aircoookie/WLED#3227]
### What happened?

I have few quinled  quad controllers. I use 4 channels of 520 LEDs. Everything works fine. But when I connect to homeassistant there is random flickering.

### To Reproduce Bug

Configure 4 channels on the Quinled quad with 520 LEDs each.
Connect the controller to the Homeassistant server.
Use the Colorloop effect. It is easy to notice the flickering.

### Expected Behavior

No flickering.

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Duplicate of #2480
Closing
