### ISSUE TITLE
Getting `{"error":9}` in websocket

### ISSUE THREAD

**Issue by theapache64** [Aircoookie/WLED#3234]
### What happened?

Getting `{"error":9}` when trying to send state to the websocket

### To Reproduce Bug

- Open the websocket
- Pass below state

```json
{
  "seg": [
    {
      "col": [
        [
          45,
          56,
          58
        ]
      ],
      "len": 3,
      "start": 0,
      "stop": 3,
      "sx": 1
    },
    {
      "col": [
        [
          45,
          56,
          58
        ]
      ],
      "len": 3,
      "start": 3,
      "stop": 6,
      "sx": 1
    },
    {
      "col": [
        [
          41,
          41,
          55
        ]
      ],
      "len": 3,
      "start": 6,
      "stop": 9,
      "sx": 1
    },
    {
      "col": [
        [
          41,
          41,
          55
        ]
      ],
      "len": 3,
      "start": 9,
      "stop": 12,
      "sx": 1
    },
    {
      "col": [
        [
          41,
          41,
          55
        ]
      ],
      "len": 3,
      "start": 12,
      "stop": 15,
      "sx": 1
    },
    {
      "col": [
        [
          41,
          41,
          55
        ]
      ],
      "len": 3,
      "start": 15,
      "stop": 18,
      "sx": 1
    },
    {
      "col": [
        [
          41,
          41,
          55
        ]
      ],
      "len": 4,
      "start": 18,
      "stop": 22,
      "sx": 1
    },
    {
      "col": [
        [
          44,
          33,
          51
        ]
      ],
      "len": 3,
      "start": 22,
      "stop": 25,
      "sx": 1
    },
    {
      "col": [
        [
          44,
          33,
          51
        ]
      ],
      "len": 3,
      "start": 25,
      "stop": 28,
      "sx": 1
    }
  ]
}
```

### Expected Behavior

Reply should be success

### Install Method

Binary from WLED.me

### What version of WLED?

Installed version: WLED 0.14.0-b1 (ESP32-D0WDQ5 build 2212222)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theapache64** [comment]
**Here's a video of the issue**

https://github.com/Aircoookie/WLED/assets/9678279/b34943be-c6df-4e8a-8376-6f3b87bbf5b5

**Comment by blazoncek** [comment]
`error: 9` is indication of JSON formatting error or that size of the JSON was too big to fit into RAM. It is not a WLED bug.
Please use correctly formatted and minimised JSON.

**Comment by theapache64** [comment]
@blazoncek What's the max lenght a web socket send can handle ?

**Comment by blazoncek** [comment]
BTW fragmented websocket packets are not supported ATM.

**Comment by e3e6** [comment]
There has to be more descriptive error, rather than error:9

**Comment by softhack007** [comment]
> There has to be more descriptive error, rather than error:9

Error 9 = JSON parsing failed (input too large?).

Unfortunately the screen space for error codes is very limited, so lots of prose to describe possible causes and solutions seems unfeasible.

Actually `0_15` already has an error text for code 9
https://github.com/Aircoookie/WLED/blob/6f3d7e76c93c039bd2dad518bf923310b66ecac3/wled00/data/index.js#L1488-L1490

**Comment by noelie88** [comment]
This is probably me, but even when I try to put in the curl command below in command prompt, I keep getting the response {"error":9}. Running 0.14.2, tried the command on 0.14.4 and 0.15b4 with the same results.
Any idea's?

curl -X POST "http://192.168.30.26/json/state" -d '{"on":true,"bri":128}' -H "Content-Type: application/json"
