### ISSUE TITLE
Stuck at loading WLED UI

### ISSUE THREAD

**Issue by Dutchlikeme** [Aircoookie/WLED#3241]
### What happened?

After trying to set the time presets in time and macro's it gets stuck at loading WLED UI (I had no presets made)
Removing the macro's did not remove the bug

### To Reproduce Bug

Time & Macros
![image](https://github.com/Aircoookie/WLED/assets/100804523/ab96a7bc-03cb-4bda-a6bf-1c78492dc26e)
Time-controlled presets
![image](https://github.com/Aircoookie/WLED/assets/100804523/bf873699-f1fb-416a-929c-f40b9e3152cc)
Save and exit (I have no presets made yet)
It's stuck at loading WLED UI
![image](https://github.com/Aircoookie/WLED/assets/100804523/f9e3b046-53d2-4852-9fe1-ae8f2a27842b)
I can still press the buttons on top to access the settings

I didn't have the presets made yet so I restored the settings to the original
but it's still stuck at loading WLED UI
After restoring these settings it's still stuck, I was able to change the color etc. before
![image](https://github.com/Aircoookie/WLED/assets/100804523/8ad7c88f-0938-4e9b-b14e-330a06625c31)

### Expected Behavior

Use the default preset/active color and warn me that preset 2 has not been configured yet / load the WLED UI

### Install Method

Binary from WLED.me

### What version of WLED?

WLED version 0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dutchlikeme** [comment]
Was able to reset through the controller and redo my config
![image](https://github.com/Aircoookie/WLED/assets/100804523/5d2d3429-ae3d-45f8-8800-f70a6481f2b4)

**Comment by blazoncek** [comment]
Please use latest nightly build.

**Comment by blazoncek** [comment]
@Dutchlikeme pleas close the issue if you resolved it.
