### ISSUE TITLE
 An irritating flash of random colors when turned on

### ISSUE THREAD

**Issue by MayysterUFTD** [Aircoookie/WLED#3247]
### What happened?

Good morning!
I'm adapting the ESP to the car's backlight (underglow and interior). I use my PCB with ESP8266 for this purpose together with SN74AHCT125N on board. Unfortunately, while the ESP is starting, there is a short but strong flash on all strips (mainly white).
GPIOs 2, 12, 13, 14 were tested.
ESP and the LEDs themselves are activated by a relay, controlled from the car (+12v after ignition).

P.S. WLED is great, the ability to integrate with signals from the car makes people's jaws drop :)

### To Reproduce Bug

Not possible

### Expected Behavior

Smooth power on leds

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.14.0-b1_ESP8266

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not a software issue. WLED prior to #3220 had an issue with brief orange flash in some circumstances.
Try updating to latest binary from @srg74 Wemos Shield repository.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
