### ISSUE TITLE
Adding Setting to Ignore Effect Palettes or Use Recommended Color Palette

### ISSUE THREAD

**Issue by BeastCrawler** [Aircoookie/WLED#3251]
I hope this message finds you well. I'm writing to propose a new feature that I believe would greatly enhance the user experience in the latest beta version of WLED.

	Firstly, I want to express my appreciation for the hard work you put into developing WLED and making it an exceptional lighting control software. However, I've encountered a slight inconvenience with the color palette in the new beta version, particularly when switching between effects.

	Currently, when I select an effect such as "Aurora," the color palette automatically changes to green and purple. While this might be suitable for some users, it becomes frustrating for those of us who prefer different color combinations for different effects. Another problem arises when I click on a new effect; the color palette remains unchanged, retaining the previous green and purple colors. This makes it difficult and time-consuming to adjust the colors to my desired preferences.

	Therefore, I would like to propose the addition of a new setting within the WLED interface. This setting could be called "Ignore Effect Palettes" or "Use Recommended Color Palette." By enabling this setting, users would have the option to disregard the effect-specific color palettes and either maintain their previously chosen colors or switch to a recommended color palette that complements the selected effect.

	I believe this feature would significantly improve the usability and flexibility of WLED, allowing users to seamlessly switch between effects without the hassle of manually readjusting the color palette each time.
Thank you for considering my suggestion. I understand that the WLED project relies on the dedication of volunteers like yourselves, and I appreciate your time and effort in reviewing this feature request. I look forward to hearing your thoughts on the matter and whether it aligns with the project's vision.

**Comment by blazoncek** [comment]
This only happens when you use GUI and is intended that way as certain effects look best with their appropriate palettes chosen by effect writer.
If you use API calls (MQTT, HA, etc) no such behaviour is implemented. Also, when you save a preset and later select it the colors and palettes will be correctly set.

However adding on/off setting for this behaviour is on our TODO list.
