### ISSUE TITLE
WLED apple app display error on latest version 

### ISSUE THREAD

**Issue by aplees** [Aircoookie/WLED#3254]
### What happened?

After updating to the latest release 0.14.0-b1 the effects tab in the apple WLED app does not work correctly. 

### To Reproduce Bug

Use the WLED Apple application and the latest release. 

### Expected Behavior

No change to occur as the error is from the update to 0.14.0-b1

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

```shell
.
```

### Anything else?

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please submit the issue in WLED App [repository](https://github.com/Aircoookie/WLED-App) as it is an issue of rendering HTML within app.
Not a WLED issue.
