### ISSUE TITLE
Playlist cycling via presets is broken in 0.14.3

### ISSUE THREAD

**Issue by alackmann** [Aircoookie/WLED#3260]
### What happened?

In my 0.13.x installation of WLED, you can create a preset with the API command similar to `P1=20&P2=22&PL=~` that when triggered will cycle through playlists 20,21,22 and then back to 20. These can be triggered either from the WebUI by pressing the preset OR from an external button macro (among others).

In all the 0.14.x versions I've tried, this is no longer working. Instead it repeatedly triggers the first playlist in the list. So in the example above, the playlist in preset 20.

### To Reproduce Bug

* Create 3 new playlists via the UI. In this example using IDs 20, 21 & 22 for the presets. Put different presets within each playlist.
* Create a preset (can be any ID, but let's call it 3 in this example) that has the API command `P1=20&P2=22&PL=~` as the preset content
* Using the web interface, click on the new preset 3
* Playlist 20 will play
* Click playlist 3 again
* Playlist 20 will restart again

### Expected Behavior

* On the second click, playlist 21 should play. 
* On the third click, playlist 22 should play
* On the fourth, the cycle should restart and playlist 20 should play

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0-b3 (build 2306210)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please try JSON API instead of HTTP API.
I.e. `{"ps":"20~22~"}`

**Comment by alackmann** [comment]
Neither were working @blazoncek. My PR fixes both.

**Comment by blazoncek** [comment]
It breaks other (legacy) things.
