### ISSUE TITLE
The ability to control a single-color LED strip using WS2811 is possible.

### ISSUE THREAD

**Issue by ZajerTMF** [Aircoookie/WLED#3266]
Hello, can we expect the ability to control a single-color LED strip using WS2811? For example, here's a link: https://marioled.pl/tasma-led-cob-cyfrowa-6000k-13w-24v-ws2811-420-led-m-highlight If such an option exists but I can't find it in the settings, I would appreciate some assistance. Thank you in advance! I'm using ESP32.

**Comment by blazoncek** [comment]
#3073
