### ISSUE TITLE
Add support for FW1906 (introduced in NeoPixelBus 2.7.6)

### ISSUE THREAD

**Issue by Robert-github-com** [Aircoookie/WLED#3277]
There is a new programmable PWM led driver FW1906 that support six LEDs per pixel. It is used in RGB+CCT LED strips. It would be great to add support for it to WLED.

Support for that chip was added recently to NeoPixelBus. So it requires to bump version to [2.7.6](https://github.com/Makuna/NeoPixelBus/releases/tag/2.7.6) and use new features RgbwwColor & GrbcwxFeature.

There are some more information [here](https://wled.discourse.group/t/add-support-for-fw1906-not-the-same-as-tm1906-enhancement/8531).

**Comment by blazoncek** [comment]
See #3256 about NPB 2.7.6

**Comment by homeusepb** [comment]
Any updates on this?

**Comment by blazoncek** [comment]
Please follow PR #3298 for updates.

**Comment by Robert-github-com** [comment]
Hi,
No progress so far. I have a "reverseBalanceFromKelvin" function, but for
precise calculations 16bit white RGB color is needed. I tested some values
using 8bit RGB and the error is up to 3 per channel. But still better than
without.

śr., 26 lip 2023 o 13:52 homeusepb ***@***.***> napisał(a):

**Comment by blazoncek** [comment]
available since 0.15.0-b2
