### ISSUE TITLE
Preset API transfer incorrect in 0.14.xx

### ISSUE THREAD

**Issue by jsv93** [Aircoookie/WLED#3278]
### What happened?

When copying the API settings from the presets of a device running version 0.13.xx of WLED to a device using the current release causes abnormalities in the presets once recalled. For example some of my presets had an underlying rainbow effect that wasnt visable when active but could be seen when transitioning between presets. The effect setting was also assigned to rainbow when it should have been a solid colour. I am unsure if this same behaviour would affect existing presets just from updating the firmware.

### To Reproduce Bug

Copy the preset API settings from a 0.13.xx device to a current release device.

### Expected Behavior

Exact replica of presets from one device to another.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.xx

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
The change was intentional as the original transition was flawed.
Also it was needed for the upcoming effect transitions when they are fully implemented.
Unfortunately that means, if you relied on a flawed transition as an "effect", you will no longer be able to use the same.
Sorry about that.

**Comment by jsv93** [comment]
Good to know! I was chasing my tail a little bit as I was rolling out a new hardware implementation and wasnt sure if it was a problem being generated on my end. Re-building the effects/presets fully rectified the issue. Was there any documentation anywhere to indicate this change/requirement to rebuild presets/effects? Just so I know where to look next time.

**Comment by blazoncek** [comment]
Some info is given in the changelog.

Please post example preset from 0.13 and updated preset from 0.14.

**Comment by softhack007** [comment]
seems to be similar to this report
* https://github.com/Aircoookie/WLED/issues/2967

**Comment by blazoncek** [comment]
No response received, closing.
