### ISSUE TITLE
Add device name to "Software Update" section

### ISSUE THREAD

**Issue by rodhammond** [Aircoookie/WLED#3286]
Often, I manually update json preset and config files to ensure equal presets and time macros settings across all devices. Is it possible to add the device name just above the "Software Update" section on the "Security & Updates" page? This would provide just a final check for a user to visually inspect the correct device and file is being selected.

**Comment by blazoncek** [comment]
Please use `multi-update.sh` or `multi-update.cmd` from tools folder for multiple device updates.
You can also upload presets and configuration in a similar fashion using `/upload` endpoint.
