### ISSUE TITLE
Need clarification on the installation process on ESP32-C3

### ISSUE THREAD

**Issue by berkut0** [Aircoookie/WLED#3288]
### What happened?

I have several ESP32-C3 based boards and am completely confused. On one board I installed the firmware easily and didn't even notice how. On the other two same boards I was unable to install the firmware. Clearly I am doing something wrong, but what?

Any constructive comments would be greatly appreciated. Please share your experiences and thoughts on "how to do it right".

### To Reproduce Bug

Install the firmware from scratch

### Expected Behavior

Can we clarify the installation process on C3 chips a little?

1. Do I need a bootloader?

2. If a bootloader is needed, what kind of bootloader is needed for C3?

3. Where can I get the bootloader I need for C3?

4. What is the memory address for flashing the bootloader for C3?

5. Do I need to enter bootloader mode to flash C3?

6. What is the firmware address for the C3?

7. Do I have to flash the bootloader first and then the firmware, or can they be flashed together?

8. I am using EDT 3.9.5 but are there any known issues with this tool and should I use a different one?

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.14.0-b3_ESP32-C3.bin

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berkut0** [comment]
For example, this combination finally works.
But I got the bootloader from https://docs.espressif.com/projects/esp-at/en/latest/esp32c3/AT_Binary_Lists/ESP32-C3_AT_binaries.html

![image](https://github.com/Aircoookie/WLED/assets/8849896/abb261f8-8f0b-4bf4-8114-054e2e8b346e)

**Comment by berkut0** [comment]
Most successful way is writing from Platformio tasks
I boot the ESP32-C3 and press the upload button.

![image](https://github.com/Aircoookie/WLED/assets/8849896/c38c1209-b88c-4c06-a366-fcf518d2994b)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
