### ISSUE TITLE
PWM signal 1.65V max

### ISSUE THREAD

**Issue by Bros11** [Aircoookie/WLED#3299]
### What happened?

Hello, I use PWM White with mosfets, but my maximum PWM signal reaches only 1.65V, and the brightness of the LED strip is not at its maximum. I tried all settings. Don't know where the problem might be? Thank you. I am using an ESP 32 board.

### To Reproduce Bug

Unfortunately, the maximum PWM signal only reaches half the value.

### Expected Behavior

That the PWM signal reaches its maximum at 3.3v

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
PWM stands for Pulse Width Modulation. It's peak value is less important than correct width of the pulse as it is assumed you *are* using power amplifiers (MOSFET).

Other than that, WLED uses stock LEDC PWM driver from ESP32 hardware and is not responsible for the peak value of PWM signal as there is no option to set such value.

For further information please consult Espressif technical [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/ledc.html).
