### ISSUE TITLE
Scrolling text font size

### ISSUE THREAD

**Issue by jrtraynor** [Aircoookie/WLED#3304]
### What happened?

Am running the latest 14b3 nightly on a 2d panel of 20x20. and also one on 60x20.And am using the scrolling text function and while it works the font size slider even at it's maximum doesn't use the whole height of the panel. 255 on the font size slider is about half the height of the panel.
Looking at the code ( I assume the right part 
`  switch (map(SEGMENT.custom2, 0, 255, 1, 5)) {
    default:
    case 1: letterWidth = 4; letterHeight =  6; break;
    case 2: letterWidth = 5; letterHeight =  8; break;
    case 3: letterWidth = 6; letterHeight =  8; break;
    case 4: letterWidth = 7; letterHeight =  9; break;
    case 5: letterWidth = 5; letterHeight = 12; break;`

Is this a limit of the fonts. or could the height/width be based on the he panel size rather than these few preset options. So the slider in the ui being at 255 means the text is 100% of the height of the panel.

Also is the last item a typo, ie letterwidth=8 not 5?  Which would explain the the largest text is hard to read.

Thanks

James

### To Reproduce Bug

A 20x20 2d panel, scrolling text effect, max font size and only get half height

### Expected Behavior

Font scales to panel height at 255 on the slider.

### Install Method

Binary from WLED.me

### What version of WLED?

14b3 nightly 20230728

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Fonts are fixed size and cannot be enlarged.
