### ISSUE TITLE
WiFi Status to GPIO pin (for an LED)

### ISSUE THREAD

**Issue by DoctorWiz** [Aircoookie/WLED#3305]
I would like to be able to tell at a glance if WLED has (or at least thinks it has) a valid WiFi connection.  I'm assuming there is likely already a flag or boolean type variable that reflects this, so I would like to see that [optionally] tied to an unused GPIO pin which could then have a LED attached.  This would be very valuable for troubleshooting especially for a non-technical end user.  (Like my Grandma, whos WiFi tends to be a little flakey)

**Comment by blazoncek** [comment]
Use `-D STATUSLED=x` when compiling.
Check source for more detailed answer.
