### ISSUE TITLE
Turning on fan/ changing fan speeds makes some lights glitch

### ISSUE THREAD

**Issue by Sulaiman09** [Aircoookie/WLED#3316]
### What happened?

While trying to change my ceiling fan speed I see that at the beginning and end of my led strip glitches (random colors/ some  leds turn off). sometimes it’s in other places but mainly front and back of the strip. Is this some sort of power issue? I attached a video, the color of the lights doesn’t matter
sk6812 1040 leds minus the first one. I have power injection and an 80a psu 

### To Reproduce Bug

Changing or turning on fan 

### Expected Behavior

Nothing 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 (build 2208222)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

https://github.com/Aircoookie/WLED/assets/98357314/f20d0b24-e523-4d95-b39f-3f148370824e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
That is EMI. Use shielded data cable.

**Comment by Sulaiman09** [comment]
Thank you, but could you show me what the cable is. All I'm finding are Ethernet cables and cables with multiple wires. Sorry I'm new to this stuff😅.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for hep and support questions.
Closing.
