### ISSUE TITLE
Effects tab is not viewing properly on iPhone WLED App

### ISSUE THREAD

**Issue by shane-peiris** [Aircoookie/WLED#3321]
### What happened?

When you navigate to the effects tab in the iPhone (Checked on iPhone 12 Pro Max and iPhone 14 Pro), it is all over and unable to click on any of the effects.

![EEC58D65-53FF-4D27-BCF6-0CF302A3A617](https://github.com/Aircoookie/WLED/assets/5033283/65228083-358d-41e0-81e4-2cae92e64177)
![4A8047A7-F6E0-44BF-839A-6A2AE66FC036](https://github.com/Aircoookie/WLED/assets/5033283/d7757590-1118-4be5-ae6a-1aa432e5e80f)

### To Reproduce Bug

Click on the Effects Tab. This issue is available on both the sound reactive and normal version.

### Expected Behavior

To show the effects properly just like in the web browser and without them suddenly disappearing.

![2AE84B76-D6D2-4A32-9B0A-BF94CC76C25E](https://github.com/Aircoookie/WLED/assets/5033283/5e222061-6ece-4d32-a1f6-3fffe8ff5960)

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.3 (build 2210301)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please open an issue in WLED app repository?
Closing.

**Comment by softhack007** [comment]
The mobile app has it's own repository on github https://github.com/Aircoookie/WLED-App

This iOS problem is already reported multiple times:
https://github.com/Aircoookie/WLED-App/issues/36 and 
https://github.com/Aircoookie/WLED-App/issues/35 and 
https://github.com/Aircoookie/WLED-App/issues/34 and 
https://github.com/Aircoookie/WLED-App/issues/39

Please, study existing report before reporting the same thing again.
