### ISSUE TITLE
Scrolling text direction enhancment 

### ISSUE THREAD

**Issue by dosipod** [Aircoookie/WLED#3322]
At the moment Scrolling text direction is from right to left , this feature request is to add correct movement from left to right and also vertical movement .
As you see in the video if  reverse is selected in segment then movement will change from  left to right but the fonts is  reversed

![text_direction](https://github.com/Aircoookie/WLED/assets/87589371/d6a8ad0d-626c-4853-9491-23af7b10bf59)

Also vertical movement at the moment is as listed in the video ( I assume the request for vertical  is for small text that does not scroll )

![text_direction-up-down](https://github.com/Aircoookie/WLED/assets/87589371/a100ea47-1299-48d3-b133-3ba1ab03330c)

I have kept Feature request similar  to the original post in discord found here  ( i am only posting on their behave )  
https://discord.com/channels/473448917040758787/473448917543944193/1140772522867052596

**Comment by Havenview** [comment]
For clarification I envisaged the vertical movement up and down to be on horizontal text .
eg with text such as
vvv Way Out vvv
or
^^^ Way Out ^^^

Appreciate this relies on the text length to be smaller than the display length

**Comment by blazoncek** [comment]
How do you propose this to be available from UI?
I already replaced leading 0 checkmark with scrolling direction checkmark and used 3rd custom slider for letter rotation.

**Comment by Havenview** [comment]
You could have the speed slider have a midpoint eg would range -128 to +127 with +ve being to the left and -ve to the right
is it possible  to use a second slider for up down and altering one axis resets the other to zero?

**Comment by Havenview** [comment]
I should have used the term "another slider" instead of "second slider"

Currently:
![Screenshot_20230816-084901.png](https://github.com/Aircoookie/WLED/assets/67010605/8e95a071-38ec-4e7e-9ad7-e33a154b0b9d)

As a suggestion add a 5th slider for the y speed?

**Comment by blazoncek** [comment]
5th slider is used for character rotation so you can create vertically scrolling text.

**Comment by Havenview** [comment]
Assume that's in a beta version?
I was using segment transpose for vertical scroll

**Comment by dosipod** [comment]
![text_fx_bleding](https://github.com/Aircoookie/WLED/assets/87589371/ff5a59b5-2199-4e28-9176-dd86832593b1)
