### ISSUE TITLE
Scroll-Probleme in WLED-App mit Iphone14 bei Anzeigezoom 

### ISSUE THREAD

**Issue by hardl1** [Aircoookie/WLED#3326]
### What happened?

Wenn ich mit dem Iphone14/Einstellungen/Anzeige&Helligkeit/Display-Anzeigezoom "Größerer Text" in der WLED-App bei Effects oder Presets scrolle, werden falsche Datenpunkte angezeigt.
![DFC811E4-AB0E-4759-AD92-5F6985662DBD](https://github.com/Aircoookie/WLED/assets/38688960/ca8f5c73-6c16-415a-93f3-ff30984b0f80)

### To Reproduce Bug

WLED-App mit Iphone14/Einstellungen/Anzeige&Helligkeit/Display-Anzeigezoom "Größerer Text

### Expected Behavior

Wie bei Anzeigezoom "Standard"

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b4

### Which microcontroller/board are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
WLED app has its own repository and this problem has been reported many times.
Please update issue with WLED app.
Closing

**Comment by hardl1** [comment]
Sorry
