### ISSUE TITLE
Build-task issue with VS Code and PlatformIO

### ISSUE THREAD

**Issue by arittner** [Aircoookie/WLED#3327]
### What happened?

The `PlatformIO: Build` in VS Code is out of order. 

When I click on the `Checkmark/Build` button, the command palette opens and no build is started. When I remove `PlatformIO:` I get this list:

![grafik](https://github.com/Aircoookie/WLED/assets/5605065/d760bf4c-2881-467c-b623-66c38e6a250f)

`Build: binary only` is working. 

First, I thought it's a documentation issue (see https://github.com/Aircoookie/WLED-Docs/issues/150)

VS Code: 1.81.1
OS: Windows 11 x64
PlatformIO: v3.3.1

### To Reproduce Bug

When I click on the `Checkmark/Build` button, the command palette opens and no build is started.

### Expected Behavior

The build should start (at least `Build: binary only`)

### Install Method

Self-Compiled

### What version of WLED?

0.13.3 (build 2208222)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

^- installed method, version and board are irrelevant.

Wiki issue: https://github.com/Aircoookie/WLED-Docs/issues/150

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
Yeah it was working before but a while back it not longer works , still works if we select run build task from menu ( on mac )  
![image](https://github.com/Aircoookie/WLED/assets/87589371/bbd2fbab-1eb2-44de-83c2-a67bec6af6f9)

**Comment by blazoncek** [comment]
When a drop-down list opens after clicking "Build" button (checkmark) just delete pre-filled content of the field. Then select "Build: binary only" from the drop-down list.

**Comment by dosipod** [comment]
Delete works 
![PIO_BUILD](https://github.com/Aircoookie/WLED/assets/87589371/13b26c9a-1c52-4090-bae3-1b7093f74ddd)

**Comment by softhack007** [comment]
> 0.13.3 (build 2208222)

If you want to compile old versions of the source code, you need this patch 
https://github.com/Aircoookie/WLED/commit/bc90309dd69533ff9f4b879fb82ecfd1b1db35d7

It fixes compatibility problem with newer versions of platformIO.

**Comment by blazoncek** [comment]
Closing as this may not be WLED related issue but MS VSC + PIO issue.
