### ISSUE TITLE
Scrolling Text Not Readable

### ISSUE THREAD

**Issue by TwisterMc** [Aircoookie/WLED#3329]
### What happened?

I have a led matrix setup and it’s not working right. I don’t know if it’s a bug or if my setup is wrong but hopefully someone can help. 

![IMG_6593](https://github.com/Aircoookie/WLED/assets/46997/382b0cdd-f009-4cb6-a135-9d0c7ff2c9d9)
![IMG_6592](https://github.com/Aircoookie/WLED/assets/46997/b41671c8-6797-43f5-ae5e-bbac558d2d65)

### To Reproduce Bug

Screenshots attached with my settings. 

### Expected Behavior

I should be able to read the text. 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED version 0.14.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TwisterMc** [comment]
Video 
https://github.com/Aircoookie/WLED/assets/46997/de48b89c-eae2-4d32-8422-2d7d152784cd

**Comment by TwisterMc** [comment]
I figured it out. These are the new settings. I had to set my orientation to vertical. The strip is horizontal so not sure what’s going on. 
![IMG_6594](https://github.com/Aircoookie/WLED/assets/46997/48d9e9fe-70c8-42bb-8d4a-3e6f0c3e4177)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
