### ISSUE TITLE
No WebUI after flashing/updating to b4

### ISSUE THREAD

**Issue by micarius** [Aircoookie/WLED#3330]
### What happened?

Hi there,

i had some issues updating from b1 to b4 .. here is was happend :

first i tried the update via WLED-Webinterface .. after the reset .. nothing happend. I couldnt get the WEB-UI on my screen.
Then i downloaded the bin file (8266) and used esphome-flasher to manualy flash the ESP new :
- got the AP mode running and could enter my wifi - but after the reboot - no WEB UI 

to see if the new version is the issue - i downloaded the b1 bin and flashed it the same way i did before with b4.
I used esphome-flasher  and after SP mode and wifi entering it took one minute and i could access the WEB UI.

### To Reproduce Bug

Installing b4 - setup wifi in AP mode - reboot - there was no way i could access wled over wifi 

### Expected Behavior

I was expecting to access the wled UI over wifi 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.14.0-b4_ESP8266.bin

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Use web installer at https://install.wled.me or https://wled-install.github.io (unofficial)
Please use WLED [forum](https://wled.discourse.group) for help and support questions.
Closing.
