### ISSUE TITLE
Combine LEDS

### ISSUE THREAD

**Issue by armss001** [Aircoookie/WLED#3333]
Hello, 

I am asking (and this maybe possible another way) to be able to combine white LEDs with RGB. A few stipes I have repaired from Govee include seperate White channels. So LED 1 is RGB and LED 2 is white LED 3 is RGB and so on. Is there away to add (or explain how) to make these behave as a single RGBW LED?

My other though process it to Map RGB (1,3,5,7...) all together and then map all the white LEDs together (2,4,6,8...) so that segments can be used more easily for effects. 

Please let me know any thoughts you might have.

**Comment by blazoncek** [comment]
Yes, you can use ledmap and yes you can use segments to group LEDs.
Please use WLED [forum](https://wled.discourse.group) or Discord foe help and support questions.
Closing.
