### ISSUE TITLE
V0.14.0-b4 Skip first LEDs is ignored when pixels are reversed

### ISSUE THREAD

**Issue by fcmower** [Aircoookie/WLED#3346]
### What happened?

If “Reversed (rotated 180°)” IS checked, the “Skip first LEDs” option is completely ignored, i.e., no LEDs are skipped. If Reversed IS NOT checked, the specified number of LEDs (closest to the controller) are skipped.

This is different than in v0.13 where the specified number of LEDs closest to the controller are skipped whether the output is Reversed or not.

### To Reproduce Bug

LED outputs:
1: WS281x
Color Order: RGB
Start: 0
Length: 100
GPIO: 2
Reversed (rotated 180°): CHECKED
Skip first LEDs: 1
Off Refresh: unchecked

Segment 0:
Start LED: 0
Stop LED: 100
Offset: 0
Grouping: 1
Spacing: 0
Reverse direction: unchecked
Mirror effect: unchecked
Ledmap: none

Effects: Solid or Any
Colors: Fx: Blue or Any

The sacrificial pixel next to the controller is lit and the last pixel at the end of the string is not lit.  Any value entered into "Skip first LEDs:" makes no difference to any lit or unlit pixel.

### Expected Behavior

When
Reversed (rotated 180°): is CHECKED
and
Skip first LEDs: is 1,
I expect the first pixel next to the controller to be always off and all pixels from "Start:" to "Length:" to be functional.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b4 (build 2308110)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Fixed in source. Will be available in next release.
