### ISSUE TITLE
Unable to unlock OTA

### ISSUE THREAD

**Issue by juerujin** [Aircoookie/WLED#335]
I originally had changed my OTA password a while back but couldn't remember what I had set it to so I reflashed the ESP8266 via USB. Once I got it up and running I attempted to unluck OTA using the default password "wledota" but it doesn't seem to work. The device reboots and when I go back to the security settings it is still locked. Does the Nodemcu ep8266 retain those settings over a reflash? Is there something else I'm doing wrong? I am running the master branch with the latest commit of f3cc616.

Thanks!

**Comment by Aircoookie** [comment]
If you are uploading via Arduino IDE, try setting "Erase flash: All flash contents" in the Tools menu :)
If you use something else, `esptool.py erase_flash` also works!

Hope it will help!
