### ISSUE TITLE
add fx library to another project

### ISSUE THREAD

**Issue by mehranviva** [Aircoookie/WLED#3350]
thanks for your good project
how can i port the 'fx' library in other project?

**Comment by blazoncek** [comment]
WLED is not a library and porting effects will be a manual task.

**Comment by softhack007** [comment]
If you want something portable, maybe look into the 'WS2812FX' library from kitesurfer1404 : https://github.com/kitesurfer1404/WS2812FX .

**Comment by mehranviva** [comment]
exactly i want to manualy add it to another project if there is a way plz help me

**Comment by blazoncek** [comment]
Please use WLED [forum ](https://wled.discourse.group) or Discord for help and support questions.
Closing.
