### ISSUE TITLE
Buttons do not toggle the preset when a playlist is placed on a button

### ISSUE THREAD

**Issue by gamer1966** [Aircoookie/WLED#3352]
### What happened?

When I put a playlist with an animation on a button, I can no longer switch to a preset via a button after pressing the button with the playlist. The playlist always remains active. With the app you can switch between the playlist and the presets without any problems.

### To Reproduce Bug

Create some presets with some segments and any effects.
Create one or more playlist with Pixel Magic Tool.
Assign the presets and the playlists to the buttons.
Use a button to switch to a playlist and the use a button to switch to a preset.

![HardwareSetup](https://github.com/Aircoookie/WLED/assets/43117741/986b2971-19a0-4487-a1d3-d9d3e211c49d)
![Button2](https://github.com/Aircoookie/WLED/assets/43117741/edebfaf2-772d-4fc2-a573-c627f57dd9b5)
![Presets](https://github.com/Aircoookie/WLED/assets/43117741/976de3f3-0b12-457d-afc9-25af9bb968dc)

### Expected Behavior

I assume that switching presets works the same as it does in the app.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0-b4 "Hoshi" build 2308110

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Playlist is just another preset with specific JSON.
It runs until end or until stopped by switching WLED off or changing any setting or another preset is selected.

**Comment by gamer1966** [comment]
> Playlist is just another preset with specific JSON. It runs until end or until stopped by switching WLED off or changing any setting or another preset is selected.

Thank You for the quick reply.
If you select another preset or playlist by pressing a button the playlist doesn't stop.
If you select another preset or playlist in the app, the playlist stops and the new preset or playlist is active.

**Comment by gamer1966** [comment]
Thank You.
This fix works better, but if you change from a preset with multiple segments to an animated playlist, the playlist run only in the first segment.

**Comment by blazoncek** [comment]
The playlist does not care about segments. It is presets that store segment data.
If a preset is made for one segment it will only update one segment.

**Comment by gamer1966** [comment]
> The playlist does not care about segments. It is presets that store segment data. If a preset is made for one segment it will only update one segment.

Let me explain.
I have a matrix with 16x137 pixels and I use 8 GPIO's.
This matrix has:
1x 16x137 pixel preset
1x 16x137 pixel animation in a playlist
1x a preset with 6 segments, the first segment has 15x16 pixels

When I switch between the presets everything is O.K.
When I choose the playlist and switch to the preset with only one segment, everything is O.K.
When I choose the playlist and switch to the preset with the 6 segments, only the first segment is changing.

**Comment by gamer1966** [comment]
> > The playlist does not care about segments. It is presets that store segment data. If a preset is made for one segment it will only update one segment.
> 
> Let me explain. I have a matrix with 16x137 pixels and I use 8 GPIO's. This matrix has: 1x 16x137 pixel preset in one segment 1x 16x137 pixel animation in a playlist 1x a preset with 6 segments, the first segment has 15x16 pixels
> 
> When I switch between the presets everything is O.K. When I choose the playlist and switch to the preset with only one segment, everything is O.K. When I choose the playlist and switch to the preset with the 6 segments, only the first segment is changing.

I think it's a bug within Pix Magic Tool. If I generate a playlist with no animation everything is O.K.

**Comment by blazoncek** [comment]
Please close as original issue was resolved.
