### ISSUE TITLE
Assign different default LED data pin at compile-time for usermods?

### ISSUE THREAD

**Issue by spiff72** [Aircoookie/WLED#3358]
**Is your feature request related to a problem? Please describe.**
I have a usermod using the TTGO T-Display board with a built-in TFT screen that I use to show various details of WLED.  The screen utilizes pin 2 as the LED pin instead of the default pin 16 for ESP32.  This seems to cause a conflict and it won't run with the latest library TFT_eSPI.  If I force version 2.1.4, it works fine.

**Describe the solution you'd like**
I would like to have a way to change the default LED pin at compile-time for my usermod (in a way that I don't have to modify the underlying code -- so it installs like an "original" usermod.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Please also consult [KB](https://kno.wled.ge) if helpful.
