### ISSUE TITLE
Show segments as different controller

### ISSUE THREAD

**Issue by 12nick12** [Aircoookie/WLED#3365]
**Describe the solution you'd like**
To be able to have the segments show up as separate controllers in the app. This would make it less confusing to use segments. 

**Describe alternatives you've considered**
You can control segments, but I feel it'd be great to just have it show as a different controller that way you don't have to think about which strip is in which controller when using with different rooms off a single strip.

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
WLED App has its own repository so please move this request there.
https://github.com/Aircoookie/WLED-App

There is also WLED native app, with more development going on so you may also try there.
https://github.com/Moustachauve/WLED-Native-iOS
https://github.com/Moustachauve/WLED-Native-Android
