### ISSUE TITLE
Leds data no responding

### ISSUE THREAD

**Issue by Daaaacu** [Aircoookie/WLED#3366]
### What happened?

Hello, im new on WLED and on Github jajajajaja. I have a problem with the testing of my WLED. I've already installed the flash on my NodeMCU with esp32s and the wifi is responding well, when i change the color in my phone i see the changes in the PC at the same time, but the LED are not changing colors. I tested with a strip of 60 LEDs and another one with only 6 (they come 3 per chip and both strips works with 12V). i testesd with a circuit of 5V and 12V but they keep no responding. Sometimes if i send a request and reset the power they change, but only some of them and other ones shut down. I tried all the versions of WLED avilable.
<img width="944" alt="Screenshot-2019-01-30-at-19 34 29" src="https://github.com/Aircoookie/WLED/assets/144588267/e9f6a4b2-ebe4-4552-a1ac-0ee581321957">
The Wiring is like this one but with an esp 32s.
i checked the output pin and is te same that i used, in the following image i requested 6 green LEDs
![9e2d0155-7bbd-4327-8b17-6776a3b063c0](https://github.com/Aircoookie/WLED/assets/144588267/bc0ef812-c7f0-49db-94cf-2d7365a57a1e)
![ad8bfbef-f9fb-4609-b220-46fbb6f4fcac](https://github.com/Aircoookie/WLED/assets/144588267/97ebaa9f-2755-480e-abbc-d022253e12d2)
![WhatsApp Image 2023-09-10 at 5 38 16 AM](https://github.com/Aircoookie/WLED/assets/144588267/27e10d98-d36f-44c8-837f-7eec4bdddfbc)
Thanks you very much for reading and for the help

### To Reproduce Bug

Its replicable with the nodeMCU nad the Wled program

### Expected Behavior

It should change colors

### Install Method

Self-Compiled

### What version of WLED?

0.13.3 and 0.14.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
