### ISSUE TITLE
Seconds are not longer shown when using #TIME

### ISSUE THREAD

**Issue by ccie7009** [Aircoookie/WLED#3369]
### What happened?

Updated to v0.14.0-b5 from v0.14.0-b4 and the seconds no longer show when using #TIME in the segment name.

### To Reproduce Bug

Updated to v0.14.0-b5 from v0.14.0-b4.

### Expected Behavior

The seconds showed on the previous version v0.14.0-b4 and before.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED version 0.14.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

I am running two 8x32 matrices side by side which shows up as an 8x64 matrix.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Fix available in b6.
