### ISSUE TITLE
Remap addressable led chips like ws2811 as separate LED channels 

### ISSUE THREAD

**Issue by ThisAccount7777** [Aircoookie/WLED#3378]
**Is your feature request related to a problem? Please describe.**
Problem: Each led has to be controlled by a separate WS2811 Chip so 24 LEDS == 24 Chips used and PCB space.

**Describe the solution you'd like**
The ability to remap all the channels on an led controller like the WS2811 as 3 separate channels that can only be controlled from 0-255. 

> Suppose you would have 3 LEDS connected to a WS2811 and you want to control each RGB channel as if it was a separate led with its own index the same way you would with WS2811 white.

**Comment by blazoncek** [comment]
That is implemented a white addressable.

**Comment by ThisAccount7777** [comment]
Ok

**Comment by ThisAccount7777** [comment]
> That is implemented as white addressable.

I couldn't find it

**Comment by blazoncek** [comment]
![image](https://github.com/Aircoookie/WLED/assets/7722392/78da58e5-7010-4ec3-b035-7cd20ffbc2c6)
![image](https://github.com/Aircoookie/WLED/assets/7722392/89afd680-151c-4119-8304-85e2477a7b7d)
![image](https://github.com/Aircoookie/WLED/assets/7722392/7e45de71-9af0-4ba1-b3c1-0d3a25201399)

**Comment by ThisAccount7777** [comment]
![image](https://github.com/Aircoookie/WLED/assets/145419488/cc7e0474-d572-4985-ae12-ec5b0df9150e)

What I'm saying is the ability to split the 3 led channels of the WS2811 ic into 3 separate addressable channels.

**Comment by blazoncek** [comment]
That's how it is implemented. Each LED channel acts as a single white led with brightness values 0-255.
It cannot be done otherwise.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.

**Comment by snenyl** [comment]
This is not implemented correctly. 

Current implementation of "WS2811 White" is:

LED 1 is controller 1 color R and controller 2 color R and controller 3 color R
LED 2 is controller 1 color G and controller 2 color G and controller 3 color G
LED 3 is controller 1 color B and controller 2 color B and controller 3 color B
LED 4 is controller 4 color R and controller 5 color R and controller 6 color R
LED 5 is controller 4 color G and controller 5 color G and controller 6 color G
LED 6 is controller 4 color B and controller 5 color B and controller 6 color B


But is should be:

LED 1 is controller 1 color R
LED 2 is controller 1 color G
LED 3 is controller 1 color B
LED 4 is controller 2 color R
LED 5 is controller 2 color G
LED 6 is controller 2 color B


Here is what happens to my LED strip when starting each LED from 1 to 6:

![Image](https://github.com/user-attachments/assets/b91c485d-260e-408f-8279-577f940610e0)
![Image](https://github.com/user-attachments/assets/2d5c6910-5626-4ebb-b733-4b8e9901e8e2)
![Image](https://github.com/user-attachments/assets/cffa2e8a-1120-491a-a83d-ac14a545282e)
![Image](https://github.com/user-attachments/assets/5e3596bc-f8f7-404c-9082-901ed6da1126)
![Image](https://github.com/user-attachments/assets/2a371be2-19f4-4684-892c-a37742b53c79)
![Image](https://github.com/user-attachments/assets/66880683-ec90-4802-8251-af57fdf5847a)

**Comment by blazoncek** [comment]
There are plenty of different implementations of "single addressable white" LED strips. WLED currently supports one that was 1st available (and may be most common).
Unfortunately I do not own any of these and the current implementation is from @Aircoookie if he can lend help.
