### ISSUE TITLE
Can i use HTTPClient in usermod, or other way to request external web server?

### ISSUE THREAD

**Issue by laxtiz** [Aircoookie/WLED#3386]
### What happened?

i'm new to this project.
i want create a usermod to communication with other service, so i use `HTTPClient` in `Usermod::connected()`, but after compiled and upload, serial output have nothing, both of AP, led, all not working.

### To Reproduce Bug

platformio_override.ini

```ini
[platformio]
default_envs = airm2m_core_esp32c3

[env:airm2m_core_esp32c3]
board = airm2m_core_esp32c3
board_build.partitions = tools/WLED_ESP32_4MB_1MB_FS.csv
extends = esp32c3
platform = ${esp32c3.platform}
platform_packages = ${esp32c3.platform_packages}
upload_speed = 921600
lib_deps =
  ${esp32c3.lib_deps}
  WiFiClientSecure
  HTTPClient
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32c3.build_flags} ${common.debug_flags}
  -DWLED_RELEASE_NAME=AirM2M_CORE_ESP32C3
  -DWLED_WATCHDOG_TIMEOUT=0
  -DLOLIN_WIFI_FIX
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DUSERMOD_BLINKER
```

wled00/usermod_list.cpp

```cpp
#ifdef USERMOD_BLINKER
  #include "../usermods/blinker/usermode_v2_blinker.h"
#endif

void registerUsermods()
{
  #ifdef USERMOD_BLINKER
  usermods.add(new BlinkerUsermod());
  #endif
}
  
```

usermods/blinker/usermod_v2_blinker.h

```cpp
#pragma once

#include "wled.h"
#include <HTTPClient.h>

class BlinkerUsermod : public Usermod
{
public:
    void setup()
    {
        DEBUG_PRINTLN("BlinkerUsermod setup.");
    }

    void connected()
    {
        DEBUG_PRINTLN("BlinkerUsermod connected.");
        HTTPClient http;
        // from here ------------------
        http.begin("https://github.com");
        http.GET();
        http.end();
        // to here --------------------
    }

    void loop()
    {
    }
};
```

### Expected Behavior

when i haven't used `HTTPClient` in my usermod, everything is normal.
but i need request a external web server to get some data.
how can i do?

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0-b6 2309241

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Relevant log/trace output

```shell
serial output nothing.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Yes, but the exact method is for you to discover, unfortunately.

You should use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
