### ISSUE TITLE
Pwm Output Value Is Not Zero (0-255). For Rgbw

### ISSUE THREAD

**Issue by seyfettinkazanir** [Aircoookie/WLED#3388]
### What happened?

When I select PWM RGBW from the LED features, it does not reach zero when I want to turn off the LEDs completely using the invert option.

### To Reproduce Bug

WLED 13.3 and 14.6 installation process was done. PWM RGBW option was selected from LED features. Pin numbers were chosen as 12, 4, 14, 15. Since transistors were used, the invert option was activated. Observation was made with an oscilloscope. When we wanted to turn off the LEDs completely, the brightness value was set to zero, but PWM did not reach zero.

### Expected Behavior

The LEDs were expected to turn off completely.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 13.3 ve WLED 14.6

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

![WhatsApp Image 2023-09-26 at 21 14 06](https://github.com/Aircoookie/WLED/assets/27890571/14ae2a13-544a-4ace-b8b0-6ee5948b1f89)

The oscilloscope image was taken when PWM was set to zero. (invert option is active.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
WLED uses hardware LEDC driver for PWM. Check for bugs in Espressif code.

**Comment by seyfettinkazanir** [comment]
![Ekran görüntüsü 2023-09-26 220732](https://github.com/Aircoookie/WLED/assets/27890571/e8414312-d456-4c1a-95a8-8cec2fd008c4)


The last value for brightness settings appears to be 1. Could it be related to this error?

**Comment by blazoncek** [comment]
That is normal behaviour. If you turn WLED off (using UI button) the brightness will be 0.
