### ISSUE TITLE
Add WaterTorture as effect

### ISSUE THREAD

**Issue by ArJay60** [Aircoookie/WLED#339]
Hi. Is it possible to add WaterTorture as effect? Code can be found at the bottom of: https://gist.github.com/headphones81/d3474359f1b3744ce203b16905f93d5f

**Comment by HimbeersaftLP** [comment]
And maybe give it a more friendly name lol

**Comment by Aircoookie** [comment]
Haha yes i believe i will call it "Drip"

**Comment by n1iic** [comment]
I can't believe he  called us drips!! LOL
