### ISSUE TITLE
winamp &wledsr fusion before the inner eye

### ISSUE THREAD

**Issue by sk2eu** [Aircoookie/WLED#3393]
do not want to spoil your fantasy
but do you now also see the fusion like me before the inner eye?

![image](https://github.com/Aircoookie/WLED/assets/48036204/276fd474-c6bc-4c44-9d77-36f9c2bbb469)
![image](https://github.com/Aircoookie/WLED/assets/48036204/f4b2d4be-4015-4fbe-8aec-66da4b008441)
![image](https://github.com/Aircoookie/WLED/assets/48036204/5add1a79-0f09-42b5-909e-404a063f7091)
![image](https://github.com/Aircoookie/WLED/assets/48036204/52046f2a-23ce-4df1-b070-6e73a43ce775)
and so much more

**Comment by blazoncek** [comment]
what are you trying to convey?
