### ISSUE TITLE
Add legend or hover tooltip for filters

### ISSUE THREAD

**Issue by tablatronix** [Aircoookie/WLED#3404]
These are a bit ambiguous, it would help new users to know what these meean. A simple alt tag might do the trick, or a legend somewhere in UI

![Screenshot 2023-09-30 at 9 25 26 AM](https://github.com/Aircoookie/WLED/assets/807787/c5e010b3-9334-4743-9d39-d736d5b63170)

Either with tooltip class

or just a title

```html
<label id="filterFreq" class="check fchkl" title="TITLE">♫ <input type="checkbox" data-flt="♫" onchange="filterFx(this)"> <span class="checkmark"></span> 
</label>
```

![Screenshot 2023-09-30 at 9 45 53 AM](https://github.com/Aircoookie/WLED/assets/807787/bd5c47fc-7395-4429-b16a-2969674a46d1)

**Comment by tablatronix** [comment]
I am not even sure what these flags mean. Not sure its even documented fyi.

https://kno.wled.ge/features/effects/

**Comment by blazoncek** [comment]
If you figure out correct CSS I will gladly add it.

**Comment by tablatronix** [comment]
Looks like there is a tooltip class

```html
<span id="sliderLabel0" class="tooltiptext">Effect speed</span>
```

**Comment by tablatronix** [comment]
This will require a lot of adjustments because of the sticky and overflow visibility and z index etc.

![Screenshot 2023-09-30 at 2 15 04 PM](https://github.com/Aircoookie/WLED/assets/807787/c8a4d0c3-2b6b-4586-aeb8-a763a2aa19ea)

**Comment by blazoncek** [comment]
Fill the search field and test on iOs/Android as well, please.

**Comment by blazoncek** [comment]
When you have it ready you can make a PR.
https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR

If you do not want to bother just submit what changed.
Thank you.

**Comment by blazoncek** [comment]
Any updates?

**Comment by tablatronix** [comment]
Doing it now

**Comment by tablatronix** [comment]
Need to figure out how to compile first, having an issue with 
(project configuration file): 'No option 'ldscript_1m0m' in section: 'common''

**Comment by tablatronix** [comment]
How tf do I upload the index.htm, I have been uploading spiffs and nothing changes..

**Comment by blazoncek** [comment]
https://kno.wled.ge/advanced/custom-features/#changing-web-ui
