### ISSUE TITLE
Segments name on HomeAssistant

### ISSUE THREAD

**Issue by gschanuel** [Aircoookie/WLED#3419]
When integrating WLED in HomeAssistant, the Segments are imported as Segment 1, Segment 2...
It would be nice if it shared the same name that was set on WLED

**Comment by blazoncek** [comment]
That is a feature request for HomeAssistant, not WLED.
WLED export all data.

**Comment by blazoncek** [comment]
@gschanuel please visit WLED [forum](http://wled.discourse.group) or Discord for further help and support questions instead of opening new issues.
