### ISSUE TITLE
ESP32-POE ETH01 no connection with APA102 configurated 

### ISSUE THREAD

**Issue by Baalthorun** [Aircoookie/WLED#3446]
### What happened?

The Ethernet connection fails when the LED Configration is set to APA102.

### To Reproduce Bug

Set the LED configuration to APA102

### Expected Behavior

working Ethernet connection with activated APA102 configuration. Other LED strips such as SK6812 work perfectly

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

Other

### Anything else?

I have seen issue #2542
https://github.com/Aircoookie/WLED/issues/2542
According to this, the error should be fixed. With Release 14.0 it does not seem to work.

Sometimes it works until reboot but then the interface is dead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
My own Ethernet set-up works correctly.
Please provide your configuration (cfg.json) so we can diagnose better.

**Comment by Baalthorun** [comment]
[wled_cfg.json](https://github.com/Aircoookie/WLED/files/12913797/wled_cfg.json)

Board: https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware

**Comment by blazoncek** [comment]
What happens if you de-configure WiFi?
If possible please get a debug build from @srg74 and post complete boot sequence.

**Comment by Baalthorun** [comment]
Disabling WLAN does not change anything. Except that the AP is activated. I left it on to make it easier to test different GPIO configurations.

Sorry my programming experience and Github experience is not very extensive. How do I get the dbug build? I have not found a way to contact @srg74 directly.

**Comment by blazoncek** [comment]
Apparently he does not have Ethernet debug builds.

**Comment by blazoncek** [comment]
Here it is: https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/%40Aircoookie/Latest/Debug_builds

**Comment by Baalthorun** [comment]
hope I have done everything right

[putty.log](https://github.com/Aircoookie/WLED/files/12922144/putty.log)

**Comment by blazoncek** [comment]
Everything seems to be in order. And the code has not been changed in quite some time.
Unfortunately I have no ideas left.
