### ISSUE TITLE
Effects & Presets Tab incorrectly formatted - iOS

### ISSUE THREAD

**Issue by coryking** [Aircoookie/WLED#3451]
### What happened?

The effects & presets tab in the WLED-App is busted. Since I'm pretty sure the HTML is actually contained in this codebase, the bug should probably live here too.

![image](https://github.com/Aircoookie/WLED/assets/526250/c66a7c5b-923a-46ad-a5e3-7edef2acdbbe)
![image](https://github.com/Aircoookie/WLED/assets/526250/fc840ee0-25d8-4834-8c14-1b73aaf57aa6)

### To Reproduce Bug

Get the iOS app, connect to a WLED controller, view the effects or presets tab.

### Expected Behavior

The presets & effects tab should look "correct"

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b5 (build 2309100)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

This bug has also been reported in the WLED-App repo: Aircoookie/WLED-App#34

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Closing as this is WLED app related.
Please use WLED Native app by @Moustachauve
