### ISSUE TITLE
uncontrollable illuminated LEDs

### ISSUE THREAD

**Issue by Ruxery** [Aircoookie/WLED#3453]
### What happened?

I created uncontrollable but still illuminated LEDs until I undo the LED Preferences setting or unplug power.

If your light strip is on while changing the strips length in config to a lower number, you can create uncontrollable illuminated LEDs

### To Reproduce Bug

1. Turn on your light strip
2. Go to Config > LED Preferences > Hardware setup > LED outputs
3. Change the length setting to a lower number than it is right now.
    Example: My strip has 127 LEDs, change the length to a number lower than 127 (I am changing it to 125)
    before: ![grafik](https://github.com/Aircoookie/WLED/assets/102697188/f47d113d-b42c-4b46-b4bd-9a4a85317751) after: ![grafik](https://github.com/Aircoookie/WLED/assets/102697188/a83dc172-e5bd-47ce-bab5-693591e9d0da)
4. Save
5. Go Back
6. Control your lights
You will see that you can control the 125 LEDs, but not the last 2 LEDs that are still on. 

### Expected Behavior

The last (in my case 2) LEDs, that you dont want to control anymore, turn off when you save the config.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Light Strip: **WS2812B**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
When you reduce the length of a strip (number of LEDs) WLED no longer knows that there are LEDs at the end of a strip so it can no longer control them.
If you want trailing LEDs to be unilluminated turn WLED off before adjusting strip length.
