### ISSUE TITLE
Adding Segments Actually Sets to Delete and Check Mark Deletes your Segment Setting (v0.14.0)

### ISSUE THREAD

**Issue by comet424** [Aircoookie/WLED#3459]
### What happened?

when you try to create a segments with a matrix ...  and you got 64 LEDS  when when you trying to save  it changes the word  64 LEDS to   (delete)   and the check mark  will erase your segment  and if you manage to re create segments like a few of them  it will delete each one seperating  

### To Reproduce Bug

make segments and try to make each row seperate ..  and then you cant   and then changes the LEDS  to (delete) and then  check mark  doesnt save  your settings it (deletes)    the segment    whats the point of the garbage can  if the check mark can delete  the your segments

### Expected Behavior

the expected behavaior is to be able to created  like 8 segments for a 8x8 matrix  so i can have 1 row of 8 per segment 

### Install Method

Binary from WLED.me

### What version of WLED?

14

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
When you see (delete) word in UI the intended segment *will* delete a segment with the same start parameter. That is intended behaviour.
When creating segments make sure they do not have the same start fields.
