### ISSUE TITLE
Preset saving - changing already existing with "save ID to x"

### ISSUE THREAD

**Issue by ToTXR4Y** [Aircoookie/WLED#3465]
### What happened?

Presets 1, 2 ,3 are already existing

Loaded an effect for example "Ripple Rainbow", choose Preset 1 with Option "save to ID 4" and overwrite from State.

Now i have the presets in the Top Line 1, 2, 3, 1. The New preset is set to the lowest one, instead of the highest.

### To Reproduce Bug

See what happened.

### Expected Behavior

A new ID (in my case ID 4) should´ve been created instead of another ID 1. The new preset should be in the upper part, not the main one.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 Hoshi

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please share prests.json
