### ISSUE TITLE
any way to change 7 segment led order in 7 segment display clock usermod

### ISSUE THREAD

**Issue by loverboyritesh** [Aircoookie/WLED#3469]
any way to change the segment order in the 7 segment display usermod [not the reloaded one], there are 6 configurations provided but mine doesn't match any, help me with this order..  Dont laugh at my unusual segment order , but its that way .
............c.........    
|.................... |     
b....................d    
| .........e.........|
| ....................|
a....................g
|...........f.........|              
SSDR doesnt have this problem as each segment can be mapped  from WLED itself.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
