### ISSUE TITLE
LittleVGL to C Array

### ISSUE THREAD

**Issue by jamesbahr** [Aircoookie/WLED#347]
Did little vgl remove support for converting gzip to carray? i remember doing it through that site but now it says it cant accept gzip files?

**Comment by Aircoookie** [comment]
Yes, they added an annoying check to see if the input is actually an image file.
They are only checking the extension though, so you can still use the site by adding a .png or .bmp to the filename.
It's another step to take, I should really read up on Python to create a tool for simple CLI gzip + C array creation (+length) to make the process more convenient. Or I will ask if someone in the community would do it :)

**Comment by jamesbahr** [comment]
its kinda crazy one doesn't exist yet in this IoT age. Thanks for the
advice on changing extension :)

**Comment by jamesbahr** [comment]
https://littlevgl.com/image-converter/  and the site always goes down :/

**Comment by jamesbahr** [comment]
i tried to install little vgl converter on a linux box as the site is down to see if i could get it working but its giving me same error?

~/lv_utils# php img_conv_core.php "name=mobile.c&img=mobile.png"
PHP Warning:  imagecreatefrompng(): 'mobile.png' is not a valid PNG file in /root/lv_utils/img_conv_core.php on line 66

**Comment by Aircoookie** [comment]
Opened #357 for this :)
