### ISSUE TITLE
API Request (Philips Hue Polling Light) is not Working for me.

### ISSUE THREAD

**Issue by itwegner72** [Aircoookie/WLED#3482]
### What happened?

The API Request

&HP=  0 to 99 (Sets Hue polling light ID (0 is off) | 0.5.1)

Is not working for me. Nothing was changed ?

MFG
Ingo

### To Reproduce Bug

curl "http://192.168.178.181/win&HP=0"   for off (no Sync)
curl "http://192.168.178.181/win&HP=26" polling the Light 26 (Sync)

### Expected Behavior

I want to switch off and on the Hue Sync between my Hue Light and the Wled Instance.

### Install Method

Binary from WLED.me

### What version of WLED?

latest

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Nothing was changed in HUE API. Make sure you have HUE enabled WLED binary as it is optional compile.

**Comment by itwegner72** [comment]
Test it by yourself, is not working.

**Comment by blazoncek** [comment]
> Test it by yourself, is not working.

I will when you send me Hue lights. 😄 Unfortunately I do not own Hue or compatible lights.
Still, Hue code in WLED was not changed in last 2 years (there was a whitespace cleanup 9 months ago, but only whitespace). I would assume something wrong with your set-up or environment.

**Comment by itwegner72** [comment]
Have you testest it, No , Or ?

**Comment by itwegner72** [comment]
![image](https://github.com/Aircoookie/WLED/assets/22859892/4cf89f3a-1c13-43c2-93ac-365069ed0158)
![image](https://github.com/Aircoookie/WLED/assets/22859892/9c60689f-9b3c-4eaa-9cec-02e9229dfe20)

**Comment by itwegner72** [comment]
![image](https://github.com/Aircoookie/WLED/assets/22859892/5cb28bf0-b1ea-437e-867f-d7efee3374c6)


Nothing was changed
