### ISSUE TITLE
Audio Reactive profiles wont show up

### ISSUE THREAD

**Issue by pranjalchanda08** [Aircoookie/WLED#3494]
### What happened?

Audio reactive profiles does not show up when LED setting is set to PWM-RGB.
The same is not seen even after falling back to WLED mode.
Default the profiles are visible.

Had to factory restore/reload firmware to get back the profiles.

### To Reproduce Bug

1. Set the LED to PWM-RGB
2. Reset the LED to WLED

### Expected Behavior

The profiles shall be visible.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pranjalchanda08** [comment]
After doing some tweeks I understand that this happens when total number of LED set is only 1.

**Comment by blazoncek** [comment]
If by "profiles" you mean effects (or sometimes called modes). That's by design.

**Comment by pranjalchanda08** [comment]
True. This can be documented somewhere or shown as a warning in the UI for people to understand their fault. You may use this issue to implement that caution waring or document and close this issue.

**Comment by blazoncek** [comment]
You are welcome to update the documentation: [WLED-docs](https://github.com/Aircoookie/WLED-docs)
