### ISSUE TITLE
WLED doesn't DDP-sync after DDP has been off, until WLED is rebooted

### ISSUE THREAD

**Issue by kristofferR** [Aircoookie/WLED#3535]
### What happened?

I've got a WLED&Hyperion setup on my TV. When I turn off the TV and Hyperion stops sending data, the color synchronization stops as expected. However, when I turn on the TV again and Hyperion starts sending new data, WLED doesn't DDP-synchronize with Hyperian. However, as soon as I reboot WLED it works properly again, every time.

Before updating to v0.14, everything worked fine.

I have filmed a video here that shows the bug in action:

https://github.com/Aircoookie/WLED/assets/481270/d84e1c0f-b0fc-43be-96fd-75ce73d7f0ec

### To Reproduce Bug

Have DDP-synchronization enabled. Sync something, then turn off the sync at source, then start DDP-syncing again.

### Expected Behavior

WLED shouldn't have to be rebooted to get DDP-sync working again.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Sync has nothing to do with DDP. Leave it off.

**Comment by kristofferR** [comment]
> Sync has nothing to do with DDP. Leave it off.

I've updated the language to be more clear.

**Comment by Yuke-hd** [comment]
I'm experiencing the same issue.

After stopping DDP streaming source (shut down Hyperion) the WLED webui is still responsive but even the built in effects won't work

![image](https://github.com/Aircoookie/WLED/assets/38873367/d8043157-5430-40d9-b4e6-7f671e26e46f)

See above screenshot: I was trying to show a solid red but the leds were off and PEAK is showing nothing

**Comment by Yuke-hd** [comment]
https://github.com/Aircoookie/WLED/issues/3700#issuecomment-1914889050

might be related

**Comment by kristofferR** [comment]
> [#3700 (comment)](https://github.com/Aircoookie/WLED/issues/3700#issuecomment-1914889050)
> 
> might be related

Awesome, yeah, upgrading to 0.15 nightly fixed it for me.
