### ISSUE TITLE
Implémentation of standard strip rgb

### ISSUE THREAD

**Issue by BugsBunny1403** [Aircoookie/WLED#354]
Hello, i'm very interested by the project. But i would command standard strip rgb with pin 12 13 14. It's possible to implement setting for switch to this mode and contrôle single value for rgb but always take effect.

**Comment by Aircoookie** [comment]
Hi, please see #58 :)

**Comment by Aircoookie** [comment]
You can find the latest code that supports this in #269 !

**Comment by BugsBunny1403** [comment]
Yes, i have read. But can you pull fork by def3nder to the master.
