### ISSUE TITLE
ws2813 1st led issue

### ISSUE THREAD

**Issue by jurajs5** [Aircoookie/WLED#3544]
### What happened?

on every led strip 2813 1st led is flickering - no matter how I change config. Tried multiple strips - this is not HW issue. 
test: 
- connect strip to uncofigured channel - multiple led start to light
- create configuration with WS281x setup and every time 1st LED will flickering - even in OFF status. Config change to skip 1st led don't help 

### To Reproduce Bug

reproducable on quinLED quad - multiple strips, multiple setups - it will appear every time

### Expected Behavior

fix 1st led on WS2813

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
You should ground BI wire.

**Comment by jurajs5** [comment]
ground done - no change

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.

BTW WLED uses NeoPixelBus as a driver for LEDs. You may want to check there if there are any incompatibilities.
