### ISSUE TITLE
Time completely incorrect

### ISSUE THREAD

**Issue by cambirch** [Aircoookie/WLED#3553]
### What happened?

The time/ntp functionality loaded the time wrong.
![image](https://github.com/Aircoookie/WLED/assets/2991289/9b9158a8-179f-42f3-b86c-a5c0bf930af9)

### To Reproduce Bug

Not entirely sure.  I did accidentally try to load my location via the wled-native IOS app before switching to the local browser on Windows.  Tried changing timezone and alternative NTP servers, same result.

### Expected Behavior

Correct (or close enough) time.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

Is this fixable via configuration changes? Do I need to wipe and re-install?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nmbgeek** [comment]
I had the same issue this morning after a power outage with the year being 2106 and ended up here.  Power cycling and then turning "On" wled, navigating back to the Time & Macros page and re-saving it while "On" has got my time back to being correct.
