### ISSUE TITLE
ESP32-S3-DevKit Flashes, but it wants to flash again?

### ISSUE THREAD

**Issue by ssurovich** [Aircoookie/WLED#3557]
### What happened?

Using the Web installer, WLED installs fine - it looks good, but once it's done, it goes back to the screen that asked to flash WLED or to look at logs.  So, it seems like it flashes but it doesnt work?

### To Reproduce Bug

Use a ESP32-S3-DevKit and flash WLED 0.14

### Expected Behavior

Hoping WLED will deploy fully and I can configure it.  It doesnt ask for WiFi in the web flasher and if I look for the WLED AP it doesnt show. 

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
