### ISSUE TITLE
Effects screen on mobile is breaking

### ISSUE THREAD

**Issue by nicdford** [Aircoookie/WLED#3566]
### What happened?

Whenever I visit the "Effects" screen on mobile, I get a very broken list view of the effects. 

### To Reproduce Bug

Visit the effects screen and start scrolling down the page and it should start breaking. 

### Expected Behavior

Shows a list of effects like it does on the desktop client. 

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Screenshots:

![3](https://github.com/Aircoookie/WLED/assets/7292444/910047b2-2835-4728-86c4-73cdb52487b3)
![2](https://github.com/Aircoookie/WLED/assets/7292444/24f02157-8cf9-43e0-b0f0-216a12383d0f)
![1](https://github.com/Aircoookie/WLED/assets/7292444/e18c50ea-ea02-425e-aa1f-b926819c4326)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
WLED app has its own repository, please open issue there.
Other than that, you may be better off using WLED Native by @Moustachauve
