### ISSUE TITLE
Gzip minifier and C array encoder

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#357]
For developing WLED (and other ESP projects) it would be very helpful to have a simple (CLI or GUI) tool that does two things:

- Take any specified input file and apply gzip compression to it, output file.gz
- Take any specified input file and convert it to a C char/byte array, output file.c
Also needs to include the lenght of the array in bytes.

It would be best if both operations could be combined in a single command!

Right now this process requires two webpages:
https://online-converting.com/archives/convert-to-gzip/
and
https://littlevgl.com/image-to-c-array/
LittleVGL also requires you to rename the input file format to .png for example to function.
This process is quite tedious and it would be nice to have a locally running open-source tool for this.

It would probably make sense for you to start a new repo for the tool, as it will be general purpose and not only specifically built for WLED!

I am very grateful if you decide to help me out on this one! 
Let me know if you need any more information :)

**Comment by debsahu** [comment]
Greetings, I use VSCode to do all these things:

1. minify using https://github.com/HookyQR/VSCodeMinify extension (F1 -> Minify)
2. gzip using 7zip
3. c-array from the zip file using https://github.com/stef-levesque/vscode-hexdump extension (Right click -> Copy to C-array)
