### ISSUE TITLE
Lytmi light strip

### ISSUE THREAD

**Issue by medapayne** [Aircoookie/WLED#3571]
**Is your feature request related to a problem? Please describe.**
Hello all
I would like to know if the Lytmi light strip is ok with WLED or Maybe it is in the future 

https://www.lytmi.co/products/lytmi-led-light-strip?variant=43613858038010

Thx for your help

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
