### ISSUE TITLE
mqtt (wled/device/status) status info takes a long time to update

### ISSUE THREAD

**Issue by viktor6** [Aircoookie/WLED#3576]
### What happened?

mqtt status takes a long time to update
esp8266   wled/wled/status   30 seconds
esp32      wled/wled/status   2 minutes  which is very long

### To Reproduce Bug

on/off esp32 wemos D1 

### Expected Behavior

30 c

### Install Method

Binary from WLED.me

### What version of WLED?

Installed version: WLED 0.14.0 (ESP32-D0WDQ6 build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

On esp8266 it makes a status update from offline to online in 30 seconds
On esp32  it makes a status update from offline to online in 2 minutes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by viktor6** [comment]
but on my esp32 it updates consistently in 2 minutes. I tried 3 different esp32s and more than once

**Comment by viktor6** [comment]
I need to track when wled appears on the network and for further automation

**Comment by dosipod** [comment]
Okay i so what you mean  when you listed on/off  you actually mean remove power or make it offline from the network  
![image](https://github.com/Aircoookie/WLED/assets/87589371/ff9e895a-770b-4d1f-985d-90453cd41b35)
I can see use case for car garage

**Comment by viktor6** [comment]
And on esp8266 it is about 30 seconds

**Comment by blazoncek** [comment]
You don't seem to understand MQTT. `/status` topic is **retained** with LWT set.
When WLED device is without power you will receive LWT (which is "offline"), when it is powered on you will receive "online". WLED will not re-broadcast it on its own but only together with any other state change (see example below).

![Screenshot 2023-12-08 at 20 33 16](https://github.com/Aircoookie/WLED/assets/7722392/d14fc3c4-4a9e-4a89-be7f-b6dbf33bd72d)

**Comment by dosipod** [comment]
> And on esp8266 it is about 30 seconds

I also got the same strange result you pointed out when I tested with esp8266 , it will be reconnected after i remove power  in very much less time  then esp32 . Must be something with mqtt re-connection on esp32  could be heavy after power down  , I did not even trap for offline /online but only for wled/WLED/g as you see in the example which is the same test I did on esp32  


![image](https://github.com/Aircoookie/WLED/assets/87589371/eb3cf615-10aa-48e3-aebf-773abdd0f849)

**Comment by dosipod** [comment]
@viktor6  
I found something you may want to try , once I changed the   MQTT_KEEP_ALIVE_TIME value in  wled00/mqtt.cpp the status change on esp32 is much faster now  , Bin and change is here 
https://github.com/dosipod/wled-dos-mod/actions/runs/7151014493
![image](https://github.com/Aircoookie/WLED/assets/87589371/ec7d2e53-814a-40b4-bdee-4e3dbb33eb4b)
