### ISSUE TITLE
Lock in specific ledmap upon receiving DDP

### ISSUE THREAD

**Issue by spblat** [Aircoookie/WLED#3579]
**Is your feature request related to a problem? Please describe.**

When DDP is received by a WLED from another WLED, the ledmap that is active on the target WLED *at that time* is the ledmap that applies. If the target has more than one ledmap, we have no way from the sending side to be sure that the LEDs will be mapped correctly during DDP.

**Describe the solution you'd like**

Establish a specific ledmap that we will adopt when receiving DDP as a client. It should be probably simply be the default ledmap on the target WLED unless you really want another preference in the UI.

**Describe alternatives you've considered**

If I’m sending DDP to a WLED that usually has a particular ledmap, I could rewrite the ledmap on the sending wled, but relying on nested ledmaps doesn’t make much sense, and the problem remains—depending on the active preset at the time DDP begins we can’t be sure what map will apply. 

Or I could switch the target WLED to a preset with the right ledmap before sending DDP. But there’s no way to automate this from the sending side unless we add an API for telling the target WLED to switch to a specific preset (which I would also like).

**Additional context**

I’m using wled to decorate derelict wall-mounted pinball playfields. The physical ledmap is the best use of finite string. The second ledmap is a logical arrangement of lamps according to their original purpose on the playfield, so that “chase” on a particular segment looks like it did when the game was intact. A third ledmap relates to an effort to make a 2D matrix out of the arrangement of lamps on a playfield. DDP is used to make a matrix out of up to 5 playfields. I’ll post a demo to #showcase in Discord when I’m ready to share. https://github.com/spblat/wled-ncp/tree/main/Playfields

Thank you for working on WLED :-D

**Comment by blazoncek** [comment]
Will be solved by #3554

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.

**Comment by spblat** [comment]
Initial test indicates #3554 fix was successful in my setup. Thank you!!

**Comment by spblat** [comment]
Thanks for the reply. The fix in the main branch would meet the use case.
But now I’m curious. How would I use this HTTP API from one WLED to tell
another WLED to change to a specific preset? This would be really useful to
me but I didn’t think it was possible. Today I use iOS shortcuts to do it.

**Comment by softhack007** [comment]
> But now I’m curious. How would I use this HTTP API from one WLED to tell another WLED to change to a specific preset?

@spblat maybe I misunderstood your question - when you asked for an API for the sending side" I was assuming that your "sending side" is something like XLights or falcon, so an external system that can issue commands to WLED APIs.

I have no idea if this is possible also "from wled to wled".

**Comment by blazoncek** [comment]
It is not. At least, not yet.
