### ISSUE TITLE
XML API Response from MQTT does not include Tertiary color

### ISSUE THREAD

**Issue by Grampt** [Aircoookie/WLED#3585]
### What happened?

When MQTT is enabled, the device sends an update with each change in status to the broker with an XML API response. This includes the Primary color and the Secondary color but is missing the Tertiary color from the response.

### To Reproduce Bug

Create an mqtt instance and subscribe to the [mqttDeviceTopic]/v feed and receive the xml response. Only <CL> and <CS> are provided.
![image](https://github.com/Aircoookie/WLED/assets/23340586/f0bf8fbf-be9f-4718-b17c-0f50653fa8e5)

### Expected Behavior

A third category, <CT> or equivalent with the Tertiary color provided.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

[Relavent Link](https://kno.wled.ge/interfaces/http-api/#xml-response)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not a bug. Tertiary color is not specified ti XML output.
