### ISSUE TITLE
Feature request. Bouncing balls effect

### ISSUE THREAD

**Issue by ArJay60** [Aircoookie/WLED#359]
Would be nice to have boucing balls effect available as in https://codebender.cc/sketch:302569#Bouncing%20Ball%20Neopixel%20Pattern.ino

**Comment by fishbone-git** [comment]
I use this one in my home build of wled, so cleaned it up a bit and made a pull request if that helps

**Comment by Aircoookie** [comment]
Added in 0.9.1!
