### ISSUE TITLE
Changing .htm file does nothing

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#3600]
### What happened?

Wanted to change welcome screen message and move wifi button below to the controls button

### To Reproduce Bug

Edit the htm file

### Expected Behavior

New button and message layout

### Install Method

Self-Compiled

### What version of WLED?

0.14.1.b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

If its not htm to edit, which should I be editing?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please consult [KB](https://kno.wled.ge/advanced/custom-features/#changing-web-ui)
Closing.

**Comment by Doyle4** [comment]
Thank you.
