### ISSUE TITLE
adding new usermode WLED

### ISSUE THREAD

**Issue by mustafatopcu87** [Aircoookie/WLED#3614]
Hello, first of all, I apologize for my bad English.

I started to create a new usermode on wled, but I've been drowning in codes for a few days :).

I see myself at the beginning of the road in these matters.

By compiling different sources, I made a digital clock for myself with the fastled library and ntp, but I got bored of constantly using the pride animation in this clock and tried to create a user mode using the wled base, but I failed many times.

My request from you is, can you add my codes, which I currently compile with Arduino (which I cannot manage), to the main files as user mode?

I apologize if I opened the pull request incorrectly. I am new here.

I tried to compile my codes with the usermode I found, but I kept failing.
https://www.hwtronics.com/2021/04/08/7-segment-digital-clock-firmware-wled-powered/

**My current example is like this.**
https://www.instagram.com/reel/CoAQ-e5tp96/?utm_source=ig_web_copy_link
(the explosions in the video do not actually exist)

The codes I use are attached with a compressed file.
[Clock_24.zip](https://github.com/Aircoookie/WLED/files/13761774/Clock_24.zip)

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
