### ISSUE TITLE
Segment stop LED number incorrect

### ISSUE THREAD

**Issue by casesolved-co-uk** [Aircoookie/WLED#3629]
### What happened?

The stop LED number is always 1 more than it should be.
If start LED = 0, and length = 3, stop LED should equal 2 but instead equals 3.

![Screen Shot 2024-01-01 at 01 07 35](https://github.com/Aircoookie/WLED/assets/110036763/bba79936-29cc-4d1d-b301-55afa1e29711)

### To Reproduce Bug

Look at the segment numbers

### Expected Behavior

LED numbers are indexes

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.1-b2 (build 2312230)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Hi, this is expected behaviour.
The "stop" is always the first LED that is not included.

Btw, you can change the UI behaviour in "UI settings"
![Screenshot_20240101-024941](https://github.com/Aircoookie/WLED/assets/91616163/25ae9d80-4096-4baa-b133-7a08e4a15356)
