### ISSUE TITLE
Effects look different on different ESP boards

### ISSUE THREAD

**Issue by andreas-bulling** [Aircoookie/WLED#3635]
### What happened?

I've installed two different Athom LED controllers both running WLED 0.14.0 in our kitchen: One based on an ESP32 that runs two LED strips and another based on an ESP8266 that runs one strip. This dual-controller setup was necessary because we have to separate kitchen counters and one strip was not long enough to go all around the kitchen island.

I've configured both the same way as far as LEDs etc are concerned. The ESP8266-based controller works as the master and syncs with the other one (brigthness, colour, effects, segment options). I confirmed that the sync works, i.e. if I change any of these settings on the ESP8266-based controller they instantly sync to the other.

However, I noticed differences in how the selected effect mode (colortwinkles with "Aurora" color scheme) is shown: The animation on the ESP8266 seem more "dynamic", i.e. LEDs seem to turn on and off more quickly and, in contrast to the ESP32, LEDs turn off completely as part of the animation. The ESP32 animation overall is "calmer"/less hectic. Also, the ESP32 doesn't show the dark blue colors at all that pop up in the ESP8266 animation. I also noticed that this difference is only visible/only occurs for fast fade/spawn speeds. If I leave the speeds at their default (128) the animation looks the same.

The LED strips are exactly the same of course...

Is this "normal"? Any idea whether the different ESPs could cause this (different timings etc)?
Could this be fixed in software?

### To Reproduce Bug

see abve

### Expected Behavior

animations are visually the same/highly similar

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
There are fundamental differences between ESP8266 and ESP32 especially with the way newer transition engine works.
ESP8266 does not have enough resources to fulfill every capability built into WLED 0.14 (or later).

I will remove bug label as the code for both is the same except for the features that ESP8266 cannot handle.

If you want all effects to display equally on all devices try using virtual LEDs on ESP32 (DDP) which will stream data to linked ESP8266 devices.
