### ISSUE TITLE
Read Binary Websockets

### ISSUE THREAD

**Issue by cuban8IO** [Aircoookie/WLED#3636]
### What happened?

Hi, i need to read the binary data do RGBA values for interacting with zigbee2mqtt.
I need from led X the current color state.  How can i decode the stream? 
The Json Live output is not an option because i must pull every time.

I've following tested:

### To Reproduce Bug

var arr = new Uint8Array(msg.payload);
var text = new vutil.TextDecoder("utf-8").decode(arr);

console.log(text);
return {payload: text}

Sorry for my bad english.
Thanks!

### Expected Behavior

-

### Install Method

Binary from WLED.me

### What version of WLED?

WLED v0.14.1-b2 (Build 2312290)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use source code where live data is generated (`ws.cpp`) as there is no documentation for this.
For other help and support questions please use WLED [forum](https://wled.discourse.group) or Discord.
Closing.
