### ISSUE TITLE
bk7231 support

### ISSUE THREAD

**Issue by VASAPOL** [Aircoookie/WLED#3645]
I just found https://github.com/libretiny-eu/libretiny that make platformio support bk7231.

**Comment by softhack007** [comment]
It looks like bk7231 is a SoC with wifi, but not compatible with espressif chips?
Actually the library you found seems to provide "aeduino core" features. However this is not sufficient for WLED, as we rely on several other ESP specific libraries (NeoPixelBus, esp-idf, espAsyncWebserver, any many more). Most of them will be available on your bk7231 chip, and its not possible to replace them with "something similar" unfortunately.

The WLED core team has more than enough work with the currently supported espressif chips. We don't intend to port WLED to other chips. 

You are welcome to try your luck with porting WLED to bk7231, however it could be a long journey.
