### ISSUE TITLE
Add time zone

### ISSUE THREAD

**Issue by pepeEL** [Aircoookie/WLED#365]
Please add time zone to config to setup example Europe/Warsaw... Now when i set time utc it is wrong by one hour.
Also please add summer time / winter time

**Comment by Aircoookie** [comment]
Select CET/CEST from the time zone dropdown. It is Warsaw's timezone (Central European). Summer/Winter time is also automatically adjusted then.

**Comment by pepeEL** [comment]
ok thanks
