### ISSUE TITLE
WLED / ESP32 orange light light flash

### ISSUE THREAD

**Issue by Orao-1** [Aircoookie/WLED#3650]
Light flash orange before the playlist is loaded

Does anyone have an idea why this is and can help?

Licht Blitz orange bevor die Playlist geladen wird
Hat jemand eine Idee woran das liegt und kann helfen ?
https://github.com/Aircoookie/WLED/assets/155824935/7b3e8e46-9a9d-4ad8-858a-1eac71c808ce

**Comment by blazoncek** [comment]
Disable "turn LEDs at boot" and use 0 transition for your boot preset.

Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing

**Comment by Orao-1** [comment]
Hello,

I have already deactivated Turn LEDs at Boot!

But the problem still exists.

What do you mean by setting the transition to 0.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Blaž Kristan ***@***.***>
Gesendet: Sunday, January 7, 2024 10:13:13 AM
An: Aircoookie/WLED ***@***.***>
Cc: Orao-1 ***@***.***>; Author ***@***.***>
Betreff: Re: [Aircoookie/WLED] WLED / ESP32 orange light light flash (Issue #3650)


Closed #3650<https://github.com/Aircoookie/WLED/issues/3650> as completed.
