### ISSUE TITLE
beta versions of 14.0 cause power off strangeness on matrix display

### ISSUE THREAD

**Issue by Dramus8** [Aircoookie/WLED#3651]
### What happened?

Pressing the power off button in the web page causes the matrix to switch to an all yellow/orange color rather than switching the LED's off.

### To Reproduce Bug

Switch matrix on to a preset display, then press the power off button in the web page.

### Expected Behavior

Expect LED panel to turn off

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 14.0.b1 and 14.0.b2

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Unfortunately that is not the case on 30+ of my devices.
Please post your configuration and presets.

**Comment by Dramus8** [comment]
[wled_cfg (1).json](https://github.com/Aircoookie/WLED/files/13854482/wled_cfg.1.json)
[wled_presets (1).json](https://github.com/Aircoookie/WLED/files/13854483/wled_presets.1.json)

I know it happens with the Jayhawk preset.

Thanks for taking a look into this for me.

**Comment by blazoncek** [comment]
Please update to latest version.

**Comment by Dramus8** [comment]
![image](https://github.com/Aircoookie/WLED/assets/97399411/e6f721ad-6c8e-4684-a891-b88fe9560ac0)
 Still seeing the same behavior.

**Comment by blazoncek** [comment]
The issue comes from PixelArt being stored in preset.
Please use debug build with exception decoder and submit crash log.

**Comment by softhack007** [comment]
> The issue comes from PixelArt being stored in preset.

Hi @blazoncek i've just tried his presets file with my own debug build - did not see any crash, but noticed something much simpler: The PixelArt preset is based on "solid". When activating the "jayhawkx" presets, pixelart is loaded from JSON. Now click on global "switch off" icon -> black. click on global "switch" again -> orange. 

I think it's simply that the pixelart JSON is not re-loaded at global switch-on, so the selected effect takes over and re-paints the matrix in orange.

**Comment by blazoncek** [comment]
Thank you @softhack007 for explanation. I was dealing with two issues at the same time while being interrupted in-between. 😁 

Pixelart is a temporary display data which is lost after any change in WLED state. This is not a bug but a design choice.
There is nothing that can be done except to re-select preset.
This will not be fixed.

**Comment by softhack007** [comment]
@Dramus8 a workaround is to put your PixelArt Preset into a regularly repeating playlist.

![image](https://github.com/Aircoookie/WLED/assets/91616163/6b28596a-7de0-4d21-a392-b28b257d80b2)

This way the image is re-loaded every 10 seconds, so your favourite bird will re-appear after some seconds when the matrix was switched off.
