### ISSUE TITLE
WS2814 support

### ISSUE THREAD

**Issue by Spire9** [Aircoookie/WLED#3655]
**Is your feature request related to a problem? Please describe.**
I bought two types of WS2814 RGBW light strips from BTF, and the WLED option for "WS281x" is wrong and does not work.  I spent a lot of time fiddling and Googling to find a workaround.  A "WS2814" option is needed.

**Describe the solution you'd like**
Add an option for setup as "WS2814" that functionally works like the settings "SK6812 RGBW"; Color Order: "BRG"; Swap: "W&G".  Additionally, the current option for "WS281x" needs to be renamed to whatever it was really designed for, "WS2811" for example.

**Describe alternatives you've considered**
I've considered not submitting this feature request to inflict my experience upon all new users.

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
WS281x and SK6812 protocols are exactly the same the difference is the interpretation of channels.
Use SK6812 and swap White channel and you are done.
Won't fix.

**Comment by Spire9** [comment]
Then let's change the option's wording to say "SK6812 & WS2814 RGBW" instead of "SK6812 RGBW".

**Comment by softhack007** [comment]
> Then let's change the option's wording to say "SK6812 & WS2814 RGBW" instead of "SK6812 RGBW".

Makes sense - changed in latest source code. Thanks for pointing out. 
I'll just use "/" instead of "&", because & is a trouble maker in html files.

**Comment by blazoncek** [comment]
The use for WS2814 is well documented in [KB](https://kno.wled.ge/basics/compatible-led-strips/).

**Comment by Spire9** [comment]
@softhack007 Awesome, you're the man!  That is a nice improvement to the new user experience.
@blazoncek I believe you that it's documented for people that have heard of WLED.  But like many others in this world I was shopping for my first addressable LEDs last month.  Search results seemed to imply there was no open-source software and controller combination that was known to support 24v WS2814.

**Comment by omayhemo** [comment]
> WS281x and SK6812 protocols are exactly the same the difference is the interpretation of channels. Use SK6812 and swap White channel and you are done. Won't fix.

Swap the white for what exactly?  And in what order is RGB.  I've tried every combination, none work properly.

**Comment by VORX-CORP** [comment]
> > WS281x and SK6812 protocols are exactly the same the difference is the interpretation of channels. Use SK6812 and swap White channel and you are done. Won't fix.
> 
> Swap the white for what exactly? And in what order is RGB. I've tried every combination, none work properly.

I had the exact same problem with color selections not being accurate for the WS2814 (WRGB). Found the answer on https://kno.wled.ge/basics/compatible-led-strips/ which was to use "**color order: BRG, swap W and G** (this option is available since WLED 0.14.0-b1)"

**Comment by krzychunh** [comment]
color order: BRG, swap W and G Thank you, I was looking for this solution
