### ISSUE TITLE
Enabled setting "Force 802.11g mode (ESP8266 only)" lost after reboot

### ISSUE THREAD

**Issue by trfrde** [Aircoookie/WLED#3665]
### What happened?

I have several D1 mini 8266 devices, which had connection problems (using an UniFi access point). The newly introduced setting "Force 802.11g mode (ESP8266 only)" does seem to solve the issue, thank you! Unfortunately, the setting is not saved during reboot. After a soft or hard reboot, the devices connect using the WiFi 4 standard (and not the WiFi 3 when activating the option).

### To Reproduce Bug

Activate the setting "Force 802.11g mode (ESP8266 only)"
Reboot
Setting "Force 802.11g mode (ESP8266 only)" not activated any more

### Expected Behavior

Settings "Force 802.11g mode (ESP8266 only)" keeps activated.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1-b3 build 2401060

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
You may want to disable fast roaming and BSS transition in UniFi.

**Comment by blazoncek** [comment]
And please post your configuration (cfg.json)

**Comment by softhack007** [comment]
I was able to reproduce the problem, with MS EDGE on windows.

* go into Wifi settings, check "Force 802.11g mode". Just for comparison, i've also checked "disable wifi sleep".
* save & connect
* go back into Wifi settings -> Ok -> checkmarks are there
* look at cfg.json -> ok -> contains `"wifi":{"sleep":false,"phy":1}`
* open info panel, press "reboot"
* after reboot, look into wifi settings --> NOK -> checkmark missing for "Force 802.11g mode"  (checkmark "disable sleep" is still there)
* cfg.json still correct: `"wifi":{"sleep":false,"phy":1}` 
 
@blazoncek very mysterious behaviour - "disable sleep" is still there after reboot, but "force g mode" is lost. The only suspicious part is that "sleep" is stored with true/false value, while "phy" is stored as 0/1. Any idea?

**Comment by blazoncek** [comment]
On first look everything seems in order.
```c++
force802_3g = doc[F("wifi")][F("phy")] | force802_3g; //force phy mode g?
```
and
```c++
wifi[F("phy")] = (int)force802_3g;
```

But now I wonder if `|` operator handles it properly.

Try changing the line 698 to read:
```c++
  wifi[F("phy")] = (bool)force802_3g;
```
and re-save configurations.

**Comment by softhack007** [comment]
> Try changing the line 698 to read:
> 
> ```c++
>   wifi[F("phy")] = (bool)force802_3g;
> ```
> 
> and re-save configurations.

Confirmed - works for my case, too 👍 cfg.json now has `"wifi":{"sleep":false,"phy":true}` as it should be.
