### ISSUE TITLE
Missing Color Swap in Color Overrride function. Support more RGBW

### ISSUE THREAD

**Issue by Daniel091988** [Aircoookie/WLED#3671]
**Is your feature request related to a problem? Please describe.**
Yes it is. I am Using TM1814 RGBW Led Stripes. Every stripe has a diffrent color order.
But WLED is unable to correct the color order because the Color override functions supports only RGB not W. in my Case I need to Swap W and R. But its impossable.

**Describe the solution you'd like**
Add Swap to Color Order Overrride. Like in the Initial LED Settings

**Describe alternatives you've considered**
Not Using The LED Stripes and Wait for an WLED solution or an other Controlsoftware 

**Additional context**
I Think it should be an Easy fix. Make RGBW settings and support Standart!

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.

**Comment by umerm64** [comment]
@blazoncek @Daniel091988 can one of you guys point out the commits/branches/tags associated with this issue please.
Thank you.
