### ISSUE TITLE
Esp32-S3 WROOM-1 cannot access Access Point after installation

### ISSUE THREAD

**Issue by nrawert** [Aircoookie/WLED#3677]
### What happened?

I bought an ESP32 module for running WLED, because i had no luck fixing RGBW lights on SK6812 to run on arduino with fastled.
I tried different methods of istallation (https://install.wled.me/,  https://wled-install.github.io/ and through esp32 flash download tool,  esptool.exe  using   esp32_bootloader.bin (also tried   esp32_bootloader_v4.bin)  and WLED_0.14.0_ESP32-S3_8MB and  WLED_0.15.0-a0_ESP32S3_8MB (which i got at https://wled-install.github.io).
In all cases I cannot access the access point wifi. No error on upload as far as I understand.
Before 1st install (new module) an RGB led was pulsing, now only an other red led is constantly lit, if that makes any difference.
Is this a known issue with the selected module, is ther a hardware problem, or is something else missing? 

### To Reproduce Bug

Here's the log of esptool installation:

C:\Users\#\Downloads\esptool-v4.2.1-win64\esptool-v4.2.1-win64> esptool.exe -p COM6 erase_flash
esptool.py v4.2.1
Serial port COM6
Connecting...
Detecting chip type... ESP32-S3
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 48:27:e2:e9:0c:dc
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.1s
Hard resetting via RTS pin...

C:\Users\#\Downloads\esptool-v4.2.1-win64\esptool-v4.2.1-win64>esptool.exe -p COM6 write_flash 0x010000 WLED_0.14.0_ESP32-S3_8MB
usage: esptool write_flash [-h] [--erase-all] [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                           [--flash_mode {keep,qio,qout,dio,dout}]
                           [--flash_size {detect,keep,256KB,512KB,1MB,2MB,2MB-c1,4MB,4MB-c1,8MB,16MB,32MB,64MB,128MB}]
                           [--spi-connection SPI_CONNECTION] [--no-progress] [--verify] [--encrypt]
                           [--encrypt-files <address> <filename> [<address> <filename> ...]]
                           [--ignore-flash-encryption-efuse-setting] [--force] [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'WLED_0.14.0_ESP32-S3_8MB'

C:\Users\#\Downloads\esptool-v4.2.1-win64\esptool-v4.2.1-win64>esptool.exe -p COM6 write_flash 0x010000 WLED_0.14.0_ESP32-S3_8MB.bin
esptool.py v4.2.1
Serial port COM6
Connecting...
Detecting chip type... ESP32-S3
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 48:27:e2:e9:0c:dc
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00010000 to 0x0015cfff...
Compressed 1362656 bytes to 918037...
Wrote 1362656 bytes (918037 compressed) at 0x00010000 in 10.4 seconds (effective 1045.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

C:\Users\#\Downloads\esptool-v4.2.1-win64\esptool-v4.2.1-win64> esptool.exe -p COM6 write_flash 0x0 esp32_bootloader.bin
esptool.py v4.2.1
Serial port COM6
Connecting...
Detecting chip type... ESP32-S3
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 48:27:e2:e9:0c:dc
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x0000ffff...
Compressed 65536 bytes to 12827...
Wrote 65536 bytes (12827 compressed) at 0x00000000 in 0.4 seconds (effective 1371.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

C:\Users\#\Downloads\esptool-v4.2.1-win64\esptool-v4.2.1-win64>

### Expected Behavior

After reset of module, I would expect to see the wled access point in the list of wifis 

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.14.0_ESP32-S3_8MB

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Anything else?

I followed workarround from
https://github.com/Aircoookie/WLED/issues/1212
https://github.com/Aircoookie/WLED/issues/1061
https://github.com/Aircoookie/WLED/issues/517#issuecomment-571333712

 Thank you in advance for your help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing
