### ISSUE TITLE
Usermod staircase wipe is not working

### ISSUE THREAD

**Issue by mnigten** [Aircoookie/WLED#3678]
### What happened?

When i compile the soucre code with the nessecary adjustments as descriped it is nog working

### To Reproduce Bug

when i build the project in VS code

### Expected Behavior

Usermod working properly

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.1b3 (build 2401060)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
wled00/usermods_list.cpp: In function 'void registerUsermods()':
wled00/usermods_list.cpp:215:40: error: invalid new-expression of abstract class type 'StairwayWipeUsermod'      
   usermods.add(new StairwayWipeUsermod());
                                        ^
In file included from wled00/usermods_list.cpp:14:0:
wled00/stairway-wipe-usermod-v2.h:14:7: note:   because the following virtual functions are pure within 'StairwayWipeUsermod':
 class StairwayWipeUsermod : public Usermod {
       ^
In file included from wled00/wled.h:177:0,
                 from wled00/usermods_list.cpp:1:
wled00/fcn_declare.h:283:18: note:      virtual void Usermod::setup()
     virtual void setup() = 0; // pure virtual, has to be overriden
                  ^
*** [.pio\build\esp32dev\src\usermods_list.cpp.o] Error 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please contact usermod author or maintainer.
