### ISSUE TITLE
Having less ports configured than the board supports causes configured ports to not function.

### ISSUE THREAD

**Issue by chrkov** [Aircoookie/WLED#3679]
### What happened?

I have a 4 port WLED board made by Wasatch Pixels.   I am only using 2 of the 4 ports and I am using xlights to upload the configuration.   Because I am only using 2 ports, xlights only creates the two ports in WLED.   When the card is only configured for 2 ports, nothing works on those two ports.  I cant control any lights.   If I manually add the 2 additional ports as just a single led each, then everything will work correctly.   I can also manually configure the system for 2 ports and get the same behavior, so its not an xlights thing,  It doesnt make a difference what I add the ports 3 and 4 as, can be ws2811 or even DDP or ArtNet.  Seems because its 4 ports, it has to have 4 ports configured to work.

### To Reproduce Bug

Create 1, 2 or 3 strings on a 4 port system.

### Expected Behavior

I would expect if only 2 ports of 4 were configured, that the 2 ports would work normally.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.1-b3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please consult xLights if the correctly configure your board.

**Comment by chrkov** [comment]
Its not xlights.   If I manually configure the WLED board, it does that same thing.   Xlights is configuring it correctly, its just not working with by xlights upload or by manually configuring it for only using 2 ports.

**Comment by blazoncek** [comment]
Then your configuration is wrong. WLED is functioning properly with multiple outputs configured.
Please consult your hardware manufacturer for correct configuration.

**Comment by chrkov** [comment]
Can you explain to me how in this configuration Ports 1 and 2 work perfect:
![image](https://github.com/Aircoookie/WLED/assets/57808614/b63bcf19-5117-48bb-b0a7-09f5440a94f8)

But in this configuration, they do not function at all?
![image](https://github.com/Aircoookie/WLED/assets/57808614/63874a57-c2d8-4b5a-a998-4a62e45cc39c)

Ports 1 and 2 are configured exactly the same.  Only difference is there is no output 3 and 4 configured.
This makes no sense of how its a configuration issue when the configuration for outputs 3 and 4 have nothing to do with 1 and 2.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions or contact manufacturer of the controller.
