### ISSUE TITLE
2 LEDs missing with ledmap.json

### ISSUE THREAD

**Issue by DarthWeber** [Aircoookie/WLED#3687]
### What happened?

Without ledmap.json all LEDs (1536 with 384 LEDs on 4 different GPIOs) are working. With ledmap there are 2 LEDs missing

### To Reproduce Bug

I use 24 ws2812 8x8 Panels. On 4 GPIOs i connected 6 Panels in dequence. So alltogether there are 24 Panels with 1536 LEDs. Like that:

GPIO16: Panel1-2-3-4-5-6
GPIO17: Panel7-8-9-10-11-12
GPIO18: Panel13-14-15-16-17-18
GPIO19: Panel19-20-21-22-23-24

and each Panel consists of 8x8 LEDs in non-serpentine arrangement.

Since i can't define 24 Panels with the Panel-Setup i tried my luck with ledmap.json:

`{"map":[383,382,381,380,379,378,377,376,319,318,317,316,315,314,313,312,255,254,253,252,251,250,249,248,191,190,189,188,187,186,185,184,127,126,125,124,123,122,121,120,63,62,61,60,59,58,57,56,767,766,765,764,763,762,761,760,703,702,701,700,699,698,697,696,639,638,637,636,635,634,633,632,575,574,573,572,571,570,569,568,511,510,509,508,507,506,505,504,447,446,445,444,443,442,441,440,375,374,373,372,371,370,369,368,311,310,309,308,307,306,305,304,247,246,245,244,243,242,241,240,183,182,181,180,179,178,177,176,119,118,117,116,115,114,113,112,55,54,53,52,51,50,49,48,759,758,757,756,755,754,753,752,695,694,693,692,691,690,689,688,631,630,629,628,627,626,625,624,567,566,565,564,563,562,561,560,503,502,501,500,499,498,497,496,439,438,437,436,435,434,433,432,367,366,365,364,363,362,361,360,303,302,301,300,299,298,297,296,239,238,237,236,235,234,233,232,175,174,173,172,171,170,169,168,111,110,109,108,107,106,105,104,47,46,45,44,43,42,41,40,751,750,749,748,747,746,745,744,687,686,685,684,683,682,681,680,623,622,621,620,619,618,617,616,559,558,557,556,555,554,553,552,495,494,493,492,491,490,489,488,431,430,429,428,427,426,425,424,359,358,357,356,355,354,353,352,295,294,293,292,291,290,289,288,231,230,229,228,227,226,225,224,167,166,165,164,163,162,161,160,103,102,101,100,99,98,97,96,39,38,37,36,35,34,33,32,743,742,741,740,739,738,737,736,679,678,677,676,675,674,673,672,615,614,613,612,611,610,609,608,551,550,549,548,547,546,545,544,487,486,485,484,483,482,481,480,423,422,421,420,419,418,417,416,351,350,349,348,347,346,345,344,287,286,285,284,283,282,281,280,223,222,221,220,219,218,217,216,159,158,157,156,155,154,153,152,95,94,93,92,91,90,89,88,31,30,29,28,27,26,25,24,735,734,733,732,731,730,729,728,671,670,669,668,667,666,665,664,607,606,605,604,603,602,601,600,543,542,541,540,539,538,537,536,479,478,477,476,475,474,473,472,415,414,413,412,411,410,409,408,343,342,341,340,339,338,337,336,279,278,277,276,275,274,273,272,215,214,213,212,211,210,209,208,151,150,149,148,147,146,145,144,87,86,85,84,83,82,81,80,23,22,21,20,19,18,17,16,727,726,725,724,723,722,721,720,663,662,661,660,659,658,657,656,599,598,597,596,595,594,593,592,535,534,533,532,531,530,529,528,471,470,469,468,467,466,465,464,407,406,405,404,403,402,401,400,335,334,333,332,331,330,329,328,271,270,269,268,267,266,265,264,207,206,205,204,203,202,201,200,143,142,141,140,139,138,137,136,79,78,77,76,75,74,73,72,15,14,13,12,11,10,9,8,719,718,717,716,715,714,713,712,655,654,653,652,651,650,649,648,591,590,589,588,587,586,585,584,527,526,525,524,523,522,521,520,463,462,461,460,459,458,457,456,399,398,397,396,395,394,393,392,327,326,325,324,323,322,321,320,263,262,261,260,259,258,257,256,199,198,197,196,195,194,193,192,135,134,133,132,131,130,129,128,71,70,69,68,67,66,65,64,7,6,5,4,3,2,1,0,711,710,709,708,707,706,705,704,647,646,645,644,643,642,641,640,583,582,581,580,579,578,577,576,519,518,517,516,515,514,513,512,455,454,453,452,451,450,449,448,391,390,389,388,387,386,385,384,1535,1534,1533,1532,1531,1530,1529,1528,1471,1470,1469,1468,1467,1466,1465,1464,1407,1406,1405,1404,1403,1402,1401,1400,1343,1342,1341,1340,1339,1338,1337,1336,1279,1278,1277,1276,1275,1274,1273,1272,1215,1214,1213,1212,1211,1210,1209,1208,1151,1150,1149,1148,1147,1146,1145,1144,1087,1086,1085,1084,1083,1082,1081,1080,1023,1022,1021,1020,1019,1018,1017,1016,959,958,957,956,955,954,953,952,895,894,893,892,891,890,889,888,831,830,829,828,827,826,825,824,1527,1526,1525,1524,1523,1522,1521,1520,1463,1462,1461,1460,1459,1458,1457,1456,1399,1398,1397,1396,1395,1394,1393,1392,1335,1334,1333,1332,1331,1330,1329,1328,1271,1270,1269,1268,1267,1266,1265,1264,1207,1206,1205,1204,1203,1202,1201,1200,1143,1142,1141,1140,1139,1138,1137,1136,1079,1078,1077,1076,1075,1074,1073,1072,1015,1014,1013,1012,1011,1010,1009,1008,951,950,949,948,947,946,945,944,887,886,885,884,883,882,881,880,823,822,821,820,819,818,817,816,1519,1518,1517,1516,1515,1514,1513,1512,1455,1454,1453,1452,1451,1450,1449,1448,1391,1390,1389,1388,1387,1386,1385,1384,1327,1326,1325,1324,1323,1322,1321,1320,1263,1262,1261,1260,1259,1258,1257,1256,1199,1198,1197,1196,1195,1194,1193,1192,1135,1134,1133,1132,1131,1130,1129,1128,1071,1070,1069,1068,1067,1066,1065,1064,1007,1006,1005,1004,1003,1002,1001,1000,943,942,941,940,939,938,937,936,879,878,877,876,875,874,873,872,815,814,813,812,811,810,809,808,1511,1510,1509,1508,1507,1506,1505,1504,1447,1446,1445,1444,1443,1442,1441,1440,1383,1382,1381,1380,1379,1378,1377,1376,1319,1318,1317,1316,1315,1314,1313,1312,1255,1254,1253,1252,1251,1250,1249,1248,1191,1190,1189,1188,1187,1186,1185,1184,1127,1126,1125,1124,1123,1122,1121,1120,1063,1062,1061,1060,1059,1058,1057,1056,999,998,997,996,995,994,993,992,935,934,933,932,931,930,929,928,871,870,869,868,867,866,865,864,807,806,805,804,803,802,801,800,1503,1502,1501,1500,1499,1498,1497,1496,1439,1438,1437,1436,1435,1434,1433,1432,1375,1374,1373,1372,1371,1370,1369,1368,1311,1310,1309,1308,1307,1306,1305,1304,1247,1246,1245,1244,1243,1242,1241,1240,1183,1182,1181,1180,1179,1178,1177,1176,1119,1118,1117,1116,1115,1114,1113,1112,1055,1054,1053,1052,1051,1050,1049,1048,991,990,989,988,987,986,985,984,927,926,925,924,923,922,921,920,863,862,861,860,859,858,857,856,799,798,797,796,795,794,793,792,1495,1494,1493,1492,1491,1490,1489,1488,1431,1430,1429,1428,1427,1426,1425,1424,1367,1366,1365,1364,1363,1362,1361,1360,1303,1302,1301,1300,1299,1298,1297,1296,1239,1238,1237,1236,1235,1234,1233,1232,1175,1174,1173,1172,1171,1170,1169,1168,1111,1110,1109,1108,1107,1106,1105,1104,1047,1046,1045,1044,1043,1042,1041,1040,983,982,981,980,979,978,977,976,919,918,917,916,915,914,913,912,855,854,853,852,851,850,849,848,791,790,789,788,787,786,785,784,1487,1486,1485,1484,1483,1482,1481,1480,1423,1422,1421,1420,1419,1418,1417,1416,1359,1358,1357,1356,1355,1354,1353,1352,1295,1294,1293,1292,1291,1290,1289,1288,1231,1230,1229,1228,1227,1226,1225,1224,1167,1166,1165,1164,1163,1162,1161,1160,1103,1102,1101,1100,1099,1098,1097,1096,1039,1038,1037,1036,1035,1034,1033,1032,975,974,973,972,971,970,969,968,911,910,909,908,907,906,905,904,847,846,845,844,843,842,841,840,783,782,781,780,779,778,777,776,1479,1478,1477,1476,1475,1474,1473,1472,1415,1414,1413,1412,1411,1410,1409,1408,1351,1350,1349,1348,1347,1346,1345,1344,1287,1286,1285,1284,1283,1282,1281,1280,1223,1222,1221,1220,1219,1218,1217,1216,1159,1158,1157,1156,1155,1154,1153,1152,1095,1094,1093,1092,1091,1090,1089,1088,1031,1030,1029,1028,1027,1026,1025,1024,967,966,965,964,963,962,961,960,903,902,901,900,899,898,897,896,839,838,837,836,835,834,833,832,775,774,773,772,771,770,769,768]}`

better to read:

[Bad Spiegel.csv](https://github.com/Aircoookie/WLED/files/13936314/Bad.Spiegel.csv)

I did it several times and i am pretty sure i did everything right, since "scrolling text" is working well, BUT: The first 2 LEDs of Panel 13/14 are dark an it mostly looks like they are mixed in LEDs 1534 and 1535.

Of course i have no defined skipped LEDs and i also douple-checked the GPIO Definitions - i am quite sure that everything is right, since it works (of course with unreadable scrolling text) when i delet the ledmapping.json . And if i swap GPIO 18 and 19, the problem change to Panel 19-20.

Is that maybe a problem with the ledmapping function?

### Expected Behavior

correct mapping

### Install Method

Self-Compiled

### What version of WLED?

0.14.0-b3 and 0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
@DarthWeber 
I have seen that reported before with large ledmaps , what worked for others and you might want to try 
is change  JSON_BUFFER_SIZE in const.h to 50000 and test again 
https://github.com/Aircoookie/WLED/blob/main/wled00/const.h

**Comment by DarthWeber** [comment]
Great, that solves that problem. Thank you!

Just to avoid keeping different versions: Can i use this buffer size for all instances or is there any way to define this in the platformio_override.ini?

**Comment by dosipod** [comment]
I do not think a platformio flag is there at the moment and as far as my  limited testing that did not impact the units in a bad way so you could just OTA the same bin to all your other units . If you are having concerns then test with one unit for a day or two

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.
There is still a limit on the size of ledmap. It has been increased to support larger LED count though.
