### ISSUE TITLE
Since 0.14.1: Turning a segment off no longer fades to off, but turns off instantly

### ISSUE THREAD

**Issue by fedus** [Aircoookie/WLED#3693]
### What happened?

On 0.14.0, turning a segment off would let the LEDs fade out. Since updating to 0.14.1, turning a segment off instantly turns the LEDs off.

### To Reproduce Bug

On default settings:
 - turn a segment on: LEDs fade to ON
 - turn the segment off: LEDs turn off instantly

### Expected Behavior

That the LEDs fade to off

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.1 build 2401141

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

Tested with 2-3 active segments. Haven't tested behaviour when only a single segment is defined.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Found & fixed.
Thanks for reporting.

**Comment by fedus** [comment]
Wow, that was fast. Many thanks for your amazing work and the wonderful project!

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.
