### ISSUE TITLE
WS2812D Question, not really a bug

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#3694]
### What happened?

Colors incorrect

### To Reproduce Bug

Select white etc

### Expected Behavior

Colors to work correct (Not WLEDs problem)

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32-S2

### Anything else?

More of a question on compatible LED's.
I got some [these](https://www.aliexpress.com/item/4000720415203.html) I was wondering if anyone has used them and what LED settings they used please? If I select the WS281X and change color mode to RGB its the closest I can get to correct colors, but colors such as White/Orange/Yellow isn't working, the LED doesn't emit a mix of colors to create the color I have selected, they look as if they have turned off.

I have tried other LED profiles to no luck.
Had a google and I can't seem to find anything on them with WLED, any help would be great thanks.

EDIT: Updated link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Doyle4** [comment]
Ok, I just found this quote online without any other details if anyone understands it.

Someone had asked something similar on a reddit post 2years ago which is now not able to reply too, someone was creating a matrix from standard WS281X strips and some one replied with "Why not just use WS2812D-F5's?"

 Reply was "WS2812D requires an additional resistor and capacitor to function, whereas this board contains the capacitor on the back."

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord which have broader user base than Github.
Perhaps someone has successfully used them and will reply there.

**Comment by dosipod** [comment]
@Doyle4 Alie specs are not the best and i would advise you to contact the seller prior to ordering . Still on the product page your linked and reviews they are listed as not needing resistor and capacitor 
![image](https://github.com/Aircoookie/WLED/assets/87589371/62ba754d-ab2c-4434-a0bb-fbe2e0d70c82)

I have also ordered something like those ( not labeled as ws2812d  on alie ) but they are addressable and worked without
resistor and capacitor  https://www.aliexpress.us/item/3256802451320866.html?gatewayAdapt=glo2usa

Might be better to close this and use the forum or discord
