### ISSUE TITLE
Enhancement, allow nodes buttons to be opened in new target, or copy ip address

### ISSUE THREAD

**Issue by tablatronix** [Aircoookie/WLED#3708]
Enhancement, Nodes buttons to behave like proper href links, So i can open in new, or copy link etc.

I see no reason why these links are coded like this.
I cannot open in new target, copy link or anything logical for an external link.

![Screenshot 2024-01-20 at 1 26 46 PM](https://github.com/Aircoookie/WLED/assets/807787/aad10ac5-ddf2-4bbd-9d5d-d354f89733a3)

Please adopt some basic styleguide and accessibility guidlines in this library for all UI

**Comment by WoodyLetsCode** [comment]
You're right! I'll fix this.

**Comment by blazoncek** [comment]
Do not forget that some mobile apps (which utilise web view) may not support everything regular browser can.

**Comment by tablatronix** [comment]
Yeah thats why I said styleguide, not sure if there was a reasoning but not to break the wled native app, surely js href is a thing tho?

**Comment by blazoncek** [comment]
> Yeah thats why I said styleguide, not sure if there was a reasoning but not to break the wled native app, surely js href is a thing tho?

Nobody is prohibiting you from submitting a PR. 😉 There are just too many users and cases and too few developers.

**Comment by tablatronix** [comment]
I dont know if this was done on purpose or what the coding standards are for this, its cleary not just a simple webapp. 

https://github.com/Aircoookie/WLED/blob/main/CONTRIBUTING.md is just just coding style not UI standards.

Is wled native just wrapping the webapp or using js api and its own ux?

**Comment by WoodyLetsCode** [comment]
WLED Native is basically just a browser (WebView) that opens the web UI of WLED.
WLED Native also exists for iOS.
I don't know what UI standards you would expect, but you can basically just modify the code and then make a PR.
If you are unsure about how to implement something, you could also ask on the WLED Discord server. 😄 
I will later fix this issue here, so you know, and we don't do double work.
If you want to contribute to WLED anyway, you are very welcome to do so. 🤗

**Comment by tablatronix** [comment]
I notice NO ui elements are aria safe, so I guess this is not really a small problem , SO I am going to change this request to just make it eeasier to OPEN NODES in a new window or copy ip address only.

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.

**Comment by tablatronix** [comment]
Will check it out tonight!
