### ISSUE TITLE
Mirroring not saved in Segment 0

### ISSUE THREAD

**Issue by Mangomc** [Aircoookie/WLED#3713]
### What happened?

I want that the mirroring effect is saved in Segment 0m but when you reboot wled the setting is gone

### To Reproduce Bug

Change Segment 0 to mirror effect and reboot wled

### Expected Behavior

Option is saved

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.1 (build 2401141)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Segment and its options are only saved in preset.
Please consult [KB](https://kno.wled.ge) and use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
