### ISSUE TITLE
local ntp server

### ISSUE THREAD

**Issue by r100gs** [Aircoookie/WLED#372]
Hello Aircoookie,

its a real great project! Would it be possible to set a local ntp server in the webinterface?

Best regards,
Stefan

**Comment by Aircoookie** [comment]
Hi Stefan,

yes, this is an option I should add!

**Comment by vijayvikma** [comment]
Hello there @Aircoookie . Wonderful work on effects.I have 5 LED strip running without any issue but is it possible to add clock ⏰ as an effect list which will show current time? Thanks much in advance

**Comment by Aircoookie** [comment]
@vijayvikma Hi! This is already supported, you can select an Analog clock from the dropdown in Time settings!
