### ISSUE TITLE
ESP32 With WLED (Any version) not picking wifi

### ISSUE THREAD

**Issue by Junicavi** [Aircoookie/WLED#3727]
### What happened?

I wa setting up a new ESP32 board with WLED, and after the install was completed, when I was going to set up my WIFI info, nothing is coming up in the dropdown, I already tried to manually enter the credentials, and nothing.

![image](https://github.com/Aircoookie/WLED/assets/30063203/c62538a1-bbc3-4dec-8aea-d8ffabeee67b)

### To Reproduce Bug

Install WLED on an ESP32 Board

### Expected Behavior

Be able to configure Wifi

### Install Method

Binary from WLED.me

### What version of WLED?

Any

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roninniagara** [comment]
try 13.3 instead of 14.1?

**Comment by blazoncek** [comment]
Or use AP mode and configure from that.
