### ISSUE TITLE
General design question regarding MQTT implementation

### ISSUE THREAD

**Issue by gsieben** [Aircoookie/WLED#3746]
### What happened?

Hi guys,

I am currently testing my user module for the BME68X sensor. This is taking a while because this sensor has to be calibrated. And that has to be implemented properly.

This sensor can be integrated into HomeAssistance using MQTT and HADiscovery. Now I've noticed that MQTT is behaving strangely for me. 

When I start the device, an MQTT message is issued after a short time. The first message says "[MQTTDeviceName]/status=offline". Then my HomeAssistant discovery tree is posted via onMqttConnect(). Everything is as it should be. 

But then there is a pause that I don't understand. No further MQTT messages are sent for about 4 minutes. Only then does everything work as it should. 

Now I ask myself whether the behavior of the MQTT was deliberately programmed this way. 

### To Reproduce Bug

I don't know if this is a bug

### Expected Behavior

An uninterrupted functionality of MQTT

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.1 build 2401141

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Offline is a LWT.
There are no delays introduced AFAIK.
