### ISSUE TITLE
Presets are not deleted after LED output reconfigure

### ISSUE THREAD

**Issue by casesolved-co-uk** [Aircoookie/WLED#3754]
### What happened?

Various issues happen when using outdated presets after an LED output reconfigure.
Issues like effect shadows and outputs disappearing.

Cause: Presets are not deleted after LED output reconfigure, thus they have spurious settings saved

### To Reproduce Bug

1. Configure LED outputs
2. Save a preset
3. Reconfigure with different LED lengths
4. Presets still exist and cause issues

### Expected Behavior

Presets are removed

### Install Method

Binary from WLED.me

### What version of WLED?

14.1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
That is the intended behaviour. Unfortunately for some.

You can, however, modify presets to not include start and stop indices so they can be transferable across multiple devices.
