### ISSUE TITLE
crash in device

### ISSUE THREAD

**Issue by mehrdadpilevar** [Aircoookie/WLED#3757]
### What happened?

when click in analog clock and set led address from start > end application has crashd

### To Reproduce Bug

 ip not available

### Expected Behavior

nothing

### Install Method

Binary from WLED.me

### What version of WLED?

 1.4 ?

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
> set led address from start > end

You mean when "start" is bigger than "end", like start=40 end =15 ?? Please confirm if my guess is correct.

> 1.4 ?

you tell us ;-) In fact the bug report for explains how to find the version and build number:

_What version of WLED?
 You can find this in by going to Config -> Security & Updates -> Scroll to Bottom. Copy and paste the entire line after "Server message"_
