### ISSUE TITLE
Undefined error when backing up configuration

### ISSUE THREAD

**Issue by lolimpol** [Aircoookie/WLED#3769]
### What happened?

My ESP32 for some reason seemingly wiped its EMMC and all my WLED settings are gone, when I try to back them up from a JSON file I downloaded from the same controller just an hour ago, I get an error "undefined".
I've tried downloading a config from a different controller that uses the same development board and pinout, a different browser and reflashing WLED. Nothing seems to help. Any help would be appreciated!

### To Reproduce Bug

Upload any backup to any of my WLED controllers

### Expected Behavior

The backup to be accepted, written to memory and the controller to work accordingly.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP32-S2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Its possible that your .json files were already corrupted when downloading. Please provide them so we can have a look.

**Comment by lolimpol** [comment]
Thanks for the reply, I'm closing this issue as it seems to be an issue with android and not WLED. Just tried it ilon Windows and worked instantly first try. Likely some kind of security measure? Tested on Samsung Galaxy S21 5G.
