### ISSUE TITLE
Loop LED Segment

### ISSUE THREAD

**Issue by B1BU** [Aircoookie/WLED#3774]
**Is your feature request related to a problem? Please describe.**
WLED doesn't allow segments that start at the end of a LED strip and end at the start.

**Describe the solution you'd like**
Add an option so that when a segment goes over the end of the LED strip it loops back around to the start to finish it.
Optionally let Start LED, End LED/LED Count and Offset segment parameters accept negative values (Equivalent to LED strip length - value).

**Additional context**
One of my presets has a segment for each corner of my room, but the corner where the two ends meet requires two, and because of that effects don't work with it.

**Comment by blazoncek** [comment]
Use ledmaps for such behaviour.
