### ISSUE TITLE
WS2805 Support

### ISSUE THREAD

**Issue by SimonG2024** [Aircoookie/WLED#3776]
WS2805 doesn't exist yet and that would be great if it can be added. You can do RGBCCT with them and I think it would be great for others to have support

**Comment by blazoncek** [comment]
Perhaps in 0.16, so not soon.

**Comment by davidmehren** [comment]
Duplicate of https://github.com/Aircoookie/WLED/issues/3608 ?

**Comment by blazoncek** [comment]
Indeed.

**Comment by blazoncek** [comment]
Implemented for 0.15.0-b2
