### ISSUE TITLE
Backup and restore section of settings is not clear enough

### ISSUE THREAD

**Issue by B1BU** [Aircoookie/WLED#3778]
### What happened?

I accidentally uploaded a presets file as a configuration file in the Security & Updates section of the settings menu and that reset my configuration. The two options look very similar and are very close together so this is a very easy mistake to make.

### To Reproduce Bug

Upload a _presets.json_ or any .json file in the "Restore configuration" option of the Security & Updates section of the settings menu.

### Expected Behavior

One or more of the following:
1. For the device to not accept the file.
2. For the control panel to show a warning that the file is invalid.
3. For the device to save a temporary backup of the settings before replacing the file and restore it if the uploaded file doesn't work, otherwise deleting the backup to free up storage.
4. For the two options in the settings menu to look visually distinct.
5. For the warning text to be at the top of the Backup & Restore section maybe?

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.2-b1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
That is the expected behaviour. Unfortunately.
There is a warning saying so.
![Screenshot 2024-02-26 at 23 02 18](https://github.com/Aircoookie/WLED/assets/7722392/6d69e569-c40d-4e79-8738-6b5dcfdc0a3f)

**Comment by B1BU** [comment]
Yeah, but my issue is that it's still too easy to make the mistake. The options could at least be further apart or look more visually distinct.

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.
