### ISSUE TITLE
Transition mode: Wipe

### ISSUE THREAD

**Issue by tinimark** [Aircoookie/WLED#378]
Any chance of adding an option for the LEDs to do a wipe when the device is powered on instead of fading on as they do now?

**Comment by Aircoookie** [comment]
Good idea! I will try and find an easy way to implement this.

**Comment by nibblerrick** [comment]
Wanted to ask the same question, useful for applications like in this issue [https://github.com/Aircoookie/WLED/issues/310](url).
Maybe the question can be worded a bit more general: Possibility to run (some) effects once and not in a loop?
If used as transitions it would be cool to define these things also for turning the stripe off, too.

**Comment by blazoncek** [comment]
You can achieve the effect by applying boot preset.
Closing.
