### ISSUE TITLE
Line In pass-through for ESP32 Audio Kit

### ISSUE THREAD

**Issue by T-vK** [Aircoookie/WLED#3782]
It is great to see that the ESP32 Audio Kit V2.2 is supported. I managed to get it to work by following the pin configuration from the docs of the Moon Modules branch: https://mm.kno.wled.ge/soundreactive/Line-Input/#es8388

It would be nice to get audio pass-trough to work:
![image](https://github.com/MoonModules/WLED/assets/11368523/19539e33-bb64-4535-a89a-9db4a333eb12)

I read that it can be achieved with this board with basically zero latency, but it doesn't appear to be enabled by default. 

It would be a very valuable feature because this way you wouldn't need a mixer (or Y-adapter and deal with all the impedance issues).

Looks like all it would take is something this:

``` C
i2s_read(I2S_NUM, i2s_buffer_read, I2S_READLEN, &i2s_bytes_read, 100);

/* left channel */
for (uint32_t i = 0; i < i2s_bytes_read / 2; i += 2)
 i2s_buffer_write[i] = i2s_buffer_read[i];

/* right channel */
for (uint32_t i = 1; i < i2s_bytes_read / 2; i += 2)
 i2s_buffer_write[i] = i2s_buffer_read[i];

i2s_write(I2S_NUM, i2s_buffer_write, i2s_bytes_read, &i2s_bytes_written, 100);
```

Looking at this full example: [ESP32-LyraT Audio Passthrough](https://github.com/Jeija/esp32-lyrat-passthrough/blob/master/main/main.c)

The i2s_read in WLED appears to happen here atm: 
https://github.com/Aircoookie/WLED/blob/c8c394b4e923d98d37b95e6007509b40b624a8a3/usermods/audioreactive/audio_source.h#L323

**Edit:**
Actually, looking at this:
https://github.com/Aircoookie/WLED/blob/c8c394b4e923d98d37b95e6007509b40b624a8a3/usermods/audioreactive/audio_source.h#L458

Shouldn't this already work right now?

**Comment by blazoncek** [comment]
Why don't you modify the code and test?
I'm afraid we do not have this HW.

**Comment by T-vK** [comment]
Well, my suggestion would have been software-based and if I understand the quoted comment correctly, the current code sets the ES8288 registers in a way that there is actually a hardware passthrough completely outside of the ESP.
But I tested that and it did not work..

**Comment by blazoncek** [comment]
@softhack007 can you help?

**Comment by softhack007** [comment]
Hi, I think you should indeed go for the low-level "hardware" pass-through.

The ES8388 driver was developed by @netmindz and @troyhacks, who had a hard time to read and understand the ES8388 datasheet. Maybe one of them has a clue on how to get pass-tru working on the A1S board.


Modifying the code in getSamples() - as you proposed for a software based solution -  will _not_ work in your case:

1) we only read samples for the left channel, so it's not possible to "write out" the right channel in software.

2) as i2s_write needs time, this will have negative side-effects  on audio processing - fft and other need time, and you're creating a bottleneck by "stealing" time (and buffer ressources) for writing back audio. So I expect that WLED sound processing will start to lag behind audio. Also the "software pass-through" output  might stutter and lag behind as a lot of post processing needs to happen in between sampling from I2S.

3) we sample audio at 22khz, which is great for performance but not exactly hi-fi quality.

**Comment by softhack007** [comment]
Btw, just for sake of completeness, you also make the same proposal in them MoonModules repository.

https://github.com/MoonModules/WLED/issues/121

 In fact I generally prefer to keep discussions together in one place, I stead of spreading parts throughout several repos....

**Comment by troyhacks** [comment]
The Audiokit A1S board absolutely can do on-chip analog passthru, no need to actually code anything drastic besides maybe a minor I2C init sequence change.

The LyraT uses the same ES8388 codec chip, and analog passthru is enabled for it by default. It's also a much better board as far as audio design. (The AudioKit A1S is a bit of a mess and if you don't already have one, get the LyraT instead. 😁)

This issue highlights the "problem" with these I2C controlled codecs - just because one chipset (like the ES8388) is supported doesn't mean the startup code initializes them for the physical implementation - the A1S is slightly different from the LyraT. Maybe you want to use the mics instead of line-in, or maybe the line-in is on a different input pin, etc.

**Comment by troyhacks** [comment]
So I have... no idea. I just dusted off an AudioKit A1S board and flashed it up with current MoonModules mdev (not that it matters, the ES8388 code hasn't changed in some time) and analog passthru is working just fine, even with a hard reset.

![PXL_20240227_224533274.jpg](https://github.com/Aircoookie/WLED/assets/5659019/381c8395-56dc-4e07-a471-06bc76f27182)

**Comment by troyhacks** [comment]
{You may also notice my AudioKit A1S board is missing a microphone - this is intentional as the line-in and mic share the same signal path. Like I said, it's not a great board.)

**Comment by T-vK** [comment]
Thanks for all the feedback. It turns out that my board has a hardware defect :( 
Line In in working fine, but the Earphone jack or some component along the way is broken.
I managed to get my hands on another Audio Kit board for testing, also flashed it with the current moon modules and that board just worked out of the box. I ended up with a slightly different config though:
![image](https://github.com/Aircoookie/WLED/assets/11368523/ed03c317-e555-4cac-b933-fb20bbdf50e9)

Are the dip switches in any way relevant btw?
Mine are set to:
| 1   | 2   | 3   | 4    | 5    |
| --- | --- | --- | ---- | ---- |
| ON  | ON  | ON  | OFF  | OFF  |

**Comment by troyhacks** [comment]
> Are the dip switches in any way relevant btw? Mine are set to:
> 
> 1	 2	3	4	5
> ON ON	 ON	OFF	OFF

The DIP switches are kinda poorly detailed on the silkscreen beside the DIPs - basically they set the functionality of GPIO 13 and 15, and they're in use for the SD card or something else (like key2).

For WLED, whatever works for you is fine - but only one of each switch for GPIO 13 (there's 3) and GPIO 15 (there's 2) should be set at a time.

If you want to use the physical buttons/keys, here's the GPIOs:

![image](https://github.com/Aircoookie/WLED/assets/5659019/d547a3a7-3eb2-4942-832a-1b4aae9234be)

You can see KEY2 is marked slightly differently as "IO13_KEY" - which means that key is only enabled if DIP 1 is set to "on".

**Comment by troyhacks** [comment]
Just for extra info, I have also added support for the WM8978 chipset - which is generally similar to the ES8388 used on the AudioKit A1S and the Espressif LyraT - both the WM8978 and the ES8388 are initialized via I2C commands,

The reference board for the WM8978 is the Puca DSP: https://www.ohmic.net/puca-dsp

![image](https://github.com/Aircoookie/WLED/assets/5659019/6b160a28-d51e-4c7a-9158-a7c9957de7a6)

The board is similar in function to the AudioKit A1S or the LyraT, but much smaller and without buttons or an SD card slot.  

I also enabled analog passthru on the WM8978 as well, and the Puca DSP is currently my go-to for WLED audio sync. The init sequence may be specific the WM8978 hookup on the Puca DSP, but that could be adjusted.

**Comment by softhack007** [comment]
Problem solved. 
Looks like faulty AudioKit A1S board.

Analog passthru is working as expected with the user's replacement board.

**Comment by HasanNoMore** [comment]
This conversation is very useful for me before buying the correct module 😍. Thank you for the information. This conversation occurred before the two-year mark. However, I believe the same issue exists with the ESP32 A1 Audio Kit. So I try to use LyraT V4.3. However, the delivery costs are prohibitively expensive, and this module is difficult to find. Anyway, thanks to everyone.

(I must emphasize that I have no knowledge of WLED or sound engineering. MY MAIN GOAL IS TO CREATE A LED PANEL, "THE PANEL IS ALREADY DONE." Now looking for a quality module with Line-in and Output that works with the WLED. I NEED REAL SOUND WAWES FOR MY LED PANEL FROM MY STUDIO MONITORS, BUT ONLY WITH WLED.

Thank you again, everyone. Best wishes for your upcoming projects! 🥰

**Comment by troyhacks** [comment]
@HasanNoMore You can also just get one of these and add to any ESP32 (except the Ethernet ones)

![Img_2025_10_10_17_57_32.jpeg](https://github.com/user-attachments/assets/853b4f48-c8fb-4b2e-9382-efcd94be6235)

They're very compliant and have nice ports onboard for both RCA and 3.5mm stereo. 

No pass-thru tho (just get a splitter), but that is more a fun add-on hack than something I rely on.

**Comment by Aogu181** [comment]
I recently acquired a development board, model ESP32-A1S K536, which the customer said uses the ES8388 chip. I selected ES8388 as the type, and tried all the other configurations according to your instructions.  Even with the music effect selected, the LED strip remains off regardless of the external sound level.
Can I directly obtain audio data through mic1 and mic2? Could someone tell me how to do this?

**Comment by troyhacks** [comment]
@Aogu181 the ES8388 startup code is currently set up for line-in. It would need to be modified for mic. 

I think there may be a commented out section somewhere that shows the mic config - but honestly, if you can use line-in, use line-in. There's MUCH better ways to do mics rather than the A1S, which is garbage. 

I usually physically snap the mics off my A1S boards because they interfere with the line-in path in loud environments.

**Comment by Aogu181** [comment]
> [@Aogu181](https://github.com/Aogu181) the ES8388 startup code is currently set up for line-in. It would need to be modified for mic.
> 
> I think there may be a commented out section somewhere that shows the mic config - but honestly, if you can use line-in, use line-in. There's MUCH better ways to do mics rather than the A1S, which is garbage.
> 
> I usually physically snap the mics off my A1S boards because they interfere with the line-in path in loud environments.

Thank you for your suggestion, but I still want to try inputting the audio signal directly through the analog microphone. I've tried the following modifications:
I enabled `use_es8388_mic` in `usermods\audioreactive\audio_source.h` and used `_es8388I2cWrite(10,0b01010000); // Use Lin2/Rin2 for ADC input`
I'm not sure if this approach is feasible, and I don't know how to configure the I2C GPIO pins to allow the ESP32 and ES8388 to communicate.

**Comment by Aogu181** [comment]
> [@Aogu181](https://github.com/Aogu181) the ES8388 startup code is currently set up for line-in. It would need to be modified for mic.
> 
> I think there may be a commented out section somewhere that shows the mic config - but honestly, if you can use line-in, use line-in. There's MUCH better ways to do mics rather than the A1S, which is garbage.
> 
> I usually physically snap the mics off my A1S boards because they interfere with the line-in path in loud environments.

Hi @troyhacks , I've recently been trying out wired input, and the configuration is shown in the image below. I don't know why the music mode is still not working.

![Image](https://github.com/user-attachments/assets/6abea4d7-6e3c-4c81-9046-aeddc400a13f)

![Image](https://github.com/user-attachments/assets/346fa7cd-3b9b-4bb9-b824-f4bf4d544cfd)

**Comment by troyhacks** [comment]
@Aogu181 the "audio kit" is at four to 6 board revisions m with the same name but two different codecs, and at least 5 different pinouts.

RT (our) FM and work thru the different configurations. I should work. 😁

**Comment by troyhacks** [comment]
Adding the AmyBoard to this list. I haven't added their codec but I soon will be as there's three on on my desk.

They also have MIDI in/out and digital audio in/out - separately.

**Comment by Aogu181** [comment]
> [@Aogu181](https://github.com/Aogu181) the "audio kit" is at four to 6 board revisions m with the same name but two different codecs, and at least 5 different pinouts.
> 
> RT (our) FM and work thru the different configurations. I should work. 😁

Here's the English translation:

---

Thank you for your reminder. However, I contacted the seller and they told me that the codec chip in my unit is the ES8388. I wrote my own detection code for the ES8388 based on their example code, and the pins are indeed as shown in my picture. However, it still doesn't work after flashing the WLED program. What should I do?

**Comment by softhack007** [comment]
@Aogu181 you need custom build with ``-D use_es8388_mic`, if you want to use the microphone _instead of_ line-in.
 
- either add ``-D use_es8388_mic`` to your ``build_flags`` (WLED release 0.14.x or 0.15.x)
- or (WLED 16.0.0) add this line at the top of ``usermods/audioreactive/audio_reactive.cpp``:
  ```#define use_es8388_mic```

https://github.com/wled/WLED/blob/12f6fbc00534cc18805e8f1eb5c4d071fca36300/usermods/audioreactive/audio_source.h#L493-L499

If it still does not work - sorry but the truth is, no WLED developer has this board any more.

**Comment by netmindz** [comment]
As Troy mentioned, there are almost endless variants, I do have a similar looking board however that I use with esphome, so try i2c and i2s values here

[beoplay.yaml.txt](https://github.com/user-attachments/files/26590426/beoplay.yaml.txt)
