### ISSUE TITLE
Some effects on the wiki are outdated

### ISSUE THREAD

**Issue by LightAndy1** [Aircoookie/WLED#3785]
### What happened?

I searched for the 49th effect (Fairy) on the wiki and it doesn't match. The 49th effect on the wiki is the Police effect.

### To Reproduce Bug

Self explanatory

### Expected Behavior

The wiki should be updated as it's a bit out of date.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
@scottrbailey can you take a look when time permits?

@LightAndy1 next time please open the issue in correct repository. In this case WLED-Docs.

**Comment by scottrbailey** [comment]
The wiki that is deprecated and read only?

Actually, why is it still around?

**Comment by blazoncek** [comment]
Oops! My bad.
Yes, wiki is obsolete..

**Comment by LightAndy1** [comment]
Oh, well sorry guys :(
