### ISSUE TITLE
Cycle through Presets via Poti / Button

### ISSUE THREAD

**Issue by robertvb83** [Aircoookie/WLED#3787]
Hi,

title says it... It would be cool to have a nice Dial aka Poti to cycle through your list of presets.

Divide Voltage range by number of presets and use each slot for one preset.

In addition I would like a Button not to be assigned to one specific preset but go to the next preset on every press.

Regards
Robert

**Comment by blazoncek** [comment]
Please see [KB](https://kno.wled.ge).
And/or use WLED [forum](https://wled.discourse.group) for help and support questions.

**Comment by robertvb83** [comment]
The same question was asked here https://github.com/Aircoookie/WLED/issues/3932

Only for reference:

I found what i was looking for:

That exact functionality is actually already available and is described here in the presets section
https://kno.wled.ge/features/presets/

Scroll down to the last entry of the table. You only need to define some presets and then create a special cycling preset. This preset is then assigned to your button.

![Screenshot_20240504-193559](https://github.com/Aircoookie/WLED/assets/36081149/429f35d0-261c-47ed-850f-6042f2727ffa)
