### ISSUE TITLE
http polling

### ISSUE THREAD

**Issue by bwente** [Aircoookie/WLED#379]
I see that there are option from controlling WLED from outside your local network. I was wondering if it would be possible to add a simple polling method? Rather than exposing the ip externally, have the ESP check a config/settings file every 15 minutes or so. It could be a static JSON or XML file or dynamically generated. You could use dropbox to sync and update all of them at once.

**Comment by Aircoookie** [comment]
Hi! While that would certainly be possible, I don't believe it would be very useful to many users. The perfect protocol for cross network control is [MQTT](https://github.com/Aircoookie/WLED/wiki/MQTT) though! You can use a public broker like _broker.hivemq.com_ and when you push a message to the device topic it will instantly get set to the ESP, no polling required.

**Comment by bwente** [comment]
I didn't know there was public broker. I haven't used MQTT, so that's something new for me. I was trying to do a simple cheerlight, for family members.

**Comment by nothans** [comment]
> 

CheerLights now spports MQTT natively and with Adafruit IO and ThingSpeak. (mqtt.cheerlights.com:1883 / https://cheerlights.com/cheerlights-now-supports-mqtt/)
