### ISSUE TITLE
Same LED always off in arc 1d expansion mode

### ISSUE THREAD

**Issue by jabertwo** [Aircoookie/WLED#3791]
### What happened?

In 0.14.2-b1 using arc 1d expand mode on a 48x48 matrix one particular led always stays unlit (see image)
![PXL_20240303_211916090](https://github.com/Aircoookie/WLED/assets/24753429/7f79223e-05ad-4f5a-bb01-0083e9db96bb)

### To Reproduce Bug

1. Install 0.14.2-b1
2. Put any 1d effect on arc expansion

### Expected Behavior

All leds should be lit

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.2-b1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Even though we try hard (using suboptimal arc drawing) there will always be a pixel that does not fall to an arc curve, hence it will not be drawn/painted.
If we used much faster Bresenham's algorithm (allowing for much larger matrices) there would be even more missing pixels.
