### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by basings** [Aircoookie/WLED#3795]
![Screenshot from 2024-03-05 23-26-13](https://github.com/Aircoookie/WLED/assets/92867705/bb1730a1-9b59-4968-b7a4-0e066a87181a)

Firefox shows this error message. What is missing? What is it looking for that it is not finding?

**Comment by blazoncek** [comment]
Please consult web installer repo and open an issue there if you do not find the answer.
FYI Firefox is missing serial component driver.

**Comment by basings** [comment]
thx, good to know.

Brave reports the same as firefox. Ungoogled Chromium and Chromium report `Failed to execute 'open' on 'SerialPort': Failed to open serial port.`
