### ISSUE TITLE
remote visit throw an error

### ISSUE THREAD

**Issue by mengluo04** [Aircoookie/WLED#3797]
### What happened?

I use remote Ip:port visit the device,web page show an error
![image](https://github.com/Aircoookie/WLED/assets/32565940/f20cd9c1-0902-47d5-9f41-ef543093411c)

### To Reproduce Bug

1、Set up port forwarding on the router
2、Access through ddns domain name and port
3、get an error

### Expected Behavior

Able to control equipment normally

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.1 (build 2401141)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
resolved in 0.15
