### ISSUE TITLE
Json-API accepts "t*" as on-toogle argument

### ISSUE THREAD

**Issue by tj0vtj0v** [Aircoookie/WLED#3804]
### What happened?

json api takes a string starting with t as toggle.
Eg. setting "on": "true" instead of "on": true, is handled as toggle

### To Reproduce Bug

requests.post("http://192.168.178.42/json", '{"on": "true"}')

### Expected Behavior

toggles on/off 

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
That is the intended behaviour.
[KB](https://kno.wled.ge/interfaces/json-api/)
