### ISSUE TITLE
sound reactive stop working after 2 days

### ISSUE THREAD

**Issue by parham3423** [Aircoookie/WLED#3807]
### What happened?

Sound reactive function stop working after 2 days 
And nothing make it work , changing mic pin , reset , disconnect from power source, ota manual update to flash firmware (also flashed binary from wled using ota)
all other function worked except sound reactive . 
The only fix was to erase flash , and upload it again with platformio
Version : Wled 0.14.1
Device : esp32 Dev

### To Reproduce Bug

Don't know what happened . It was working fine and  suddenly stop working , I take down all of thing and did what I told you 

### Expected Behavior

Do not stop working after some time

### Install Method

Self-Compiled

### What version of WLED?

0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Hi, a few questions to help me reproduce your issue:
* What kind of microphone are you using?
* Which PlatformIO environment did you use for compiling?
* Did you upload directly from PlatformIO, or did you install WLED by OTA?

**Comment by blazoncek** [comment]
Closing as no response received.
