### ISSUE TITLE
Wled on WEMOS D1 R1

### ISSUE THREAD

**Issue by dhpete** [Aircoookie/WLED#381]
Any Idea if this will work on the old D1 R1? Got a few around, and have tried the ESP flash and IDE programming. I get the AP and can connect but get no output to the LEDs. Using pin4, is the GPiO on these different? Tried 4 boards with same results. Ideas? Thanks, guys.

**Comment by Aircoookie** [comment]
Hi! Turns out the D1 R1 has a completely different pinout. Try connecting the LEDs to the pin `TX1/D9`, that should do the trick!

**Comment by dhpete** [comment]
Thanks, I'll give that a go.

**Comment by dhpete** [comment]
Worked like a charm!!! You are THE MAN!!!!!
