### ISSUE TITLE
Widgets for Android ?

### ISSUE THREAD

**Issue by sci666-2023** [Aircoookie/WLED#3815]
can you add Widget Support for Android with on/off buttons and maybe macro/preset buttons ? that would be great to make a simple Tablet or Smartphone  "Control Screen"

**Comment by blazoncek** [comment]
Please open an issue in the WLED app repository. WLED doesn't do Android or iOS.

BTW WLED app has been discontinued. A new app has been developed ba @Moustachauve .

**Comment by Aircoookie** [comment]
The app [HTTP Request Shortcuts](https://http-shortcuts.rmy.ch/) is also amazing for this use case. I use shortcuts on my home screen for 90% of WLED controlling I do from my phone. Of course you need to look at the WLED API for the relevant commands (e.g. `ip/win&T=2` for toggle on/off)

**Comment by sci666-2023** [comment]
> Please open an issue in the WLED app repository. WLED doesn't do Android or iOS.
> 
> BTW WLED app has been discontinued. A new app has been developed ba @Moustachauve .

Which App is it and where can I find it?

**Comment by blazoncek** [comment]
WLED Native
