### ISSUE TITLE
Playlist doesn't stop on switch button

### ISSUE THREAD

**Issue by dmelching** [Aircoookie/WLED#3827]
### What happened?

I am having a preset ID 1 and a playlist ID 6.
A Switch is connected to Button 1 on GPIO5
![Screenshot 2024-03-16 at 16 18 48](https://github.com/Aircoookie/WLED/assets/3215751/1b06ad88-676f-4617-b146-8b1f9ed3c96d)

![Screenshot 2024-03-16 at 16 18 14](https://github.com/Aircoookie/WLED/assets/3215751/30457b30-e9f9-41b0-b02c-69d7aa6d55d0)

when I switch the Button on the Playlist ID 6  starts.
When I turn the switch off, I see preset ID for about half a second, then Playlist ID 6 is visible again.

Hint: having the switch toggle two presets (instead a preset and a playlist), everything works as expected. 

### To Reproduce Bug

create at least 1 preset and one playlist.
Connect a switch as pullup according to https://kno.wled.ge/features/macros/.
Make the switch off->on: start playlist, on->off start preset.

Toggle the switch.

### Expected Behavior

Switch toggle should toggle between preset and playlist.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.2-b2, 0.14.2, 0.15.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Available in 0.15.0 beta 1.
