### ISSUE TITLE
Please provide binaries for the 4MB version of the ESP32-S3

### ISSUE THREAD

**Issue by mase76** [Aircoookie/WLED#3829]
Hi,
could you please provide binaries for the 4MB version of the EPS32-S3? Me and a friend were able to built them, and we can confirm, that is works.

**Comment by blazoncek** [comment]
I do not own one to test. Perhaps @softhack007 has it?

**Comment by mase76** [comment]
I have designed a PCB with this device. Maybe I can send you one.

**Comment by blazoncek** [comment]
Thanks. PM me on Discord.
BTW you can use `board_build.partitions = tools/WLED_ESP32_4MB_1MB_FS.csv` in the build environment.

**Comment by softhack007** [comment]
> I do not own one to test. Perhaps @softhack007 has it?

Yes, I have one -S3 with 4MB flash and 4M  PSRAM for testing. I'm currently on holidays and "away from wled", so I'd need to look into it in beginning of April.

**Comment by softhack007** [comment]
Edit: I think the inofficial installer installer from @wled-install  (Wladi) already has a build for -S3 4MB. You might find your firmware there until we add it to out official builds.

https://wled-install.github.io/

@blazoncek we also need to add "official release" build for -S3 with 4MB PSRAM (qspi) and >= 8MB PSRAM (opi) - as these variants both need a separate firmware build and will not work with other -S3 builds.

**Comment by mase76** [comment]
I use a ESP32-S3FH4R2 with 2MB PSRAM. I think, there is also a different bootloader needed.

**Comment by blazoncek** [comment]
ba9ce4adf2adc0261bd2572e220f413860313a69

**Comment by SunboX** [comment]
@mase76 I also have a ESP32-S3FH4R2 with 2MB PSRAM. Can you please share more details how you did build WLED for it?

**Comment by softhack007** [comment]
@mase76 the 4MB S3 board should work with this standard firmware image from the release page:
* https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b7/WLED_0.15.0-b7_ESP32-S3_4M_qspi.bin
