### ISSUE TITLE
Please provide the ESP02 gz file, as previously in WLED_0.14.2-b2_ESP02_160.bin.gz

### ISSUE THREAD

**Issue by vingerha** [Aircoookie/WLED#3830]
0.14.2-b2 contained the version, 0.14.2 not. I am not sure if it is as simple to gzip the bin WLED_0.14.2_ESP02_160.bin

**Comment by gustjoha** [comment]
> 0.14.2-b2 contained the version, 0.14.2 not. I am not sure if it is as simple to gzip the bin WLED_0.14.2_ESP02_160.bin

It is. I am using 7zip  to make it a gzip.

**Comment by vingerha** [comment]
Then I do it myself...thx

**Comment by blazoncek** [comment]
![Screenshot 2024-03-17 at 21 04 40](https://github.com/Aircoookie/WLED/assets/7722392/74e8373b-326b-4b21-a5fc-86b003d3aaf3)
