### ISSUE TITLE
strip doesn't turn ON after update

### ISSUE THREAD

**Issue by R3Cardoso** [Aircoookie/WLED#3832]
### What happened?

If I update my ESP32 Gledopto controller from anything after 1.4.0, the strip doesn't work after power is off.
If I use 1.4.0 there is not problem, if I do a factory reset on anything after 1.4.0 it work, but as soon I power off the power it doesn't turn on the strip any more.

### To Reproduce Bug

Strip doesn't light up after losing power on any update after 1.4.0.

### Expected Behavior

turn on strip, as it does on version 1.4.0

### Install Method

Binary from WLED.me

### What version of WLED?

1.4.2

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please provide serial output of boot sequence.
You may also want to upload debug binary.
You may also want to erase flash entirely using esptool or similar.

**Comment by R3Cardoso** [comment]
I don't know how to get that.
But if I put it on version 1.4.0, everything works fine.
If I do a factory reset it works fine until I power it off(remote power source)

**Comment by blazoncek** [comment]
Do a flash erase and then upload newer binary.

**Comment by R3Cardoso** [comment]
the board doesn't have a usb power, and I don't have tools to connect direclty to board.
it's possible to do it wireless?

**Comment by blazoncek** [comment]
no. unfortunately that means I'm unable to help further.

**Comment by R3Cardoso** [comment]
I undestand it.
It's strange how it works fine on 1.4.0, it works fine after a factory reset on any other upgrade, but only as soon it lost power it doesn't work any more.

**Comment by blazoncek** [comment]
yes, that is fixed in 0.15
