### ISSUE TITLE
5050 Rgb led using wled?

### ISSUE THREAD

**Issue by Dogu105** [Aircoookie/WLED#3840]
### What happened?

I am using a non-addressable 5050 RGB LED strip, I set up the MOSFET circuit and tried using PWM RGB and the pins, but I couldn't get any results. I don't know what I'm doing wrong, I've looked at old topics but couldn't find anything useful that would work with the current version of WLED. Can you help me?

### To Reproduce Bug

help me

### Expected Behavior

help me 

### Install Method

Binary from WLED.me

### What version of WLED?

15.01

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
