### ISSUE TITLE
Playlist stuck on first Preset

### ISSUE THREAD

**Issue by garnbleiche** [Aircoookie/WLED#3843]
### What happened?

Playlist loads only first Preset and gets stucked.

### To Reproduce Bug

Create a playlist with with some entrys and start the playlist.

### Expected Behavior

Play the entire playlist without being stuck on the first entry.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0-b1 (build 2403190)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Output from debug build

Playlist works in version WLED 0.14.2-b2 !

#### Serial Output from Debug Build WLED 0.15.0-b1 (playlist stuck on first entry):

Applying preset: 5
Playlist unloaded.
Playlist loaded.
JSON buffer released. (9)
Loop took 31ms.
Usermods took 0ms.
Strip took 29ms.
Playlist unloaded.
Request to apply preset: 2
JSON buffer locked. (9)
Applying preset: 2
JSON buffer released. (9)
JSON buffer locked. (12)
JSON buffer size: 2302 for WS request (1270).
heap 190596
Sending WS data to multiple clients.
JSON buffer released. (12)
Loop took 47ms.
Usermods took 0ms.
Strip took 44ms.

#### Serial Output from Debug Build WLED 0.14.2-b2 (playlist works):

Applying preset: 5
Playlist unloaded.
Playlist loaded.
JSON buffer released. (9)
Request to apply preset: 2
JSON buffer locked. (9)
Applying preset: 2
JSON buffer released. (9)
JSON buffer locked. (12)
JSON buffer size: 2168 for WS request (1195).
heap 202664
Sending WS data to multiple clients.
JSON buffer released. (12)
Loop took 45ms.
Usermods took 0ms.
Strip took 43ms.
Request to apply preset: 4
JSON buffer locked. (9)
Applying preset: 4
JSON buffer released. (9)
JSON buffer locked. (12)
JSON buffer size: 2166 for WS request (1194).
heap 202668
Sending WS data to multiple clients.
JSON buffer released. (12)
Loop took 47ms.
Usermods took 0ms.
Strip took 46ms.
Request to apply preset: 3
JSON buffer locked. (9)
Applying preset: 3
JSON buffer released. (9)
JSON buffer locked. (12)
JSON buffer size: 2170 for WS request (1199).
heap 202668
Sending WS data to multiple clients.
JSON buffer released. (12)
Loop took 46ms.
Usermods took 0ms.
Strip took 45ms.
Playlist unloaded.
Request to apply preset: 4
JSON buffer locked. (9)
Applying preset: 4
JSON buffer released. (9)
JSON buffer locked. (12)
JSON buffer size: 2166 for WS request (1195).
heap 202708
Sending WS data to multiple clients.
JSON buffer released. (12)
Loop took 46ms.
Usermods took 0ms.
Strip took 45ms.

It seems that the bug is in the presets.cpp (unloadPlaylist):

```
bool applyPreset(byte index, byte callMode)
{
  unloadPlaylist(); // applying a preset unloads the playlist (#3827)
  DEBUG_PRINT(F("Request to apply preset: "));
  DEBUG_PRINTLN(index);
  presetToApply = index;
  callModeToApply = callMode;
  return true;
}
```

**Comment by blazoncek** [comment]
Will be available in next release.
