### ISSUE TITLE
Can't save Playlist End preset: "Restore preset"

### ISSUE THREAD

**Issue by garnbleiche** [Aircoookie/WLED#3844]
### What happened?

The End preset: "Restore preset" does not work. It saves the presets that is active while editing the playlist

### To Reproduce Bug

Create a playlist an set the End preset to "Restore preset"

### Expected Behavior

Restore the preset that is loaded before starting the playlist.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.2 (build 2403170)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

If i edit the preset.json and change the end preset of the playlist to 255 the playlist works as expected. But after editing the playlist from the webui it is broken again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Will be available in next release.
