### ISSUE TITLE
Unable to delete preset.

### ISSUE THREAD

**Issue by SomeWarez** [Aircoookie/WLED#3849]
### What happened?

I accidentally saved a preset with the same name as another.

### To Reproduce Bug

Try to delete either of the presets with the same name and the Delete button just goes red and shows 'Delete!'.

### Expected Behavior

Expected to be warned of another preset with the same name before saving, or at the very least allow the user to delete either of the presets.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.2

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
It is ok to have multiple presets with same name. The presets are identified by their ID and are also deleted by ID, not name.
ID is unique, if not, old preset is overwritten.

**Comment by blazoncek** [comment]
Just update the name and save.
