### ISSUE TITLE
digital clock Matrix 16x16

### ISSUE THREAD

**Issue by slavikfoxy** [Aircoookie/WLED#3864]
Hi, I have a 16x16 ws2812b matrix, can I output a digital clock as it is implemented on GyverMatrix, sorry to have such a big project and the distance is so simple and important function.

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
You can also consult [KB](https://kno.wled.ge).
