### ISSUE TITLE
webui power button unresponsive after regaining control from hyperion

### ISSUE THREAD

**Issue by quixotic120** [Aircoookie/WLED#3865]
### What happened?

in instances where hyperion fails to release control of WLED after powering off and a manual override is required I am unable to power off WLED with the webui. I can click the webui button and see the animation that indicates it was clicked but nothing occurs on the device. rebooting the device allows the button to work. All other features such as changing color, brightness, patterns, etc work after manual override. Power button does not work regardless of whether webui is accessed from browser (tested chrome, safari, firefox), iOS app, android app

issue occurred with both 14.1 and 14.2 but did not occur with 14.0 and prior

### To Reproduce Bug

start hyperion
stop hyperion with failure to release control - if you manually override while hyperion is still running it tends to just regain control again
manually override
try to power off

### Expected Behavior

WLED powers off

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.2 2403170

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by willmmiles** [comment]
Hyperion sets the transition time to 0, which is bugged in v0.14.1 and v0.14.2.   Ref #3854 and #3720.   v0.14.3 or newer should have the fix.
