### ISSUE TITLE
Erase user data no back or escape

### ISSUE THREAD

**Issue by ldijkman** [Aircoookie/WLED#3869]
### What happened?

Erase user data no back or escape
ok escape button works 
but maybe not elegant escape

on my newer espwebtools escape does not work https://ldijkman.github.io/async-esp-fs-webserver/

![Screenshot from 2024-03-31 06-48-52](https://github.com/Aircoookie/WLED/assets/45427770/5a7dc1e7-e770-4f52-b22c-c9453f233f22)

![Screenshot from 2024-03-31 06-48-33](https://github.com/Aircoookie/WLED/assets/45427770/6e9240b6-977e-427d-8c36-37553f117da3)

### To Reproduce Bug

just install and open install again

problem is esp web tools

### Expected Behavior

an escape back button

### Install Method

Binary from WLED.me

### What version of WLED?

WLED version 0.15.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Web installer is a separate software.
Please open an issue in it's repository.
