### ISSUE TITLE
v0.15.0-b1 do not sync as source  to other nodes

### ISSUE THREAD

**Issue by oltas123** [Aircoookie/WLED#3871]
### What happened?

i updated all my nodes to version 0.15.0-b1, after that no sync from any node to the others. After downgrade one node to v14.2 the sync from this node works to all nodes with version 0.15.0-b1 as usual.

### To Reproduce Bug

install version 0.15.0-b1 of the  sync  node

### Expected Behavior

the active sync node should sync the other nodes of the network

### Install Method

Binary from WLED.me

### What version of WLED?

version 0.15.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP32, ESP32-S2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xrtze** [comment]
Confirming the same behaviour

**Comment by blazoncek** [comment]
It does. You just need to enable sync.
It works a bit different though.

You need to tick notifications.
![Screenshot 2024-04-01 at 21 56 50](https://github.com/Aircoookie/WLED/assets/7722392/0162caea-820b-49fd-b06f-954549965577)

**Comment by xrtze** [comment]
If I understand correctly, this not enabled on default? Wouldn't it be less missleading, if it was? Bcs rn if you click on the sync button in the top bar of the UI, nothing happens and the feature seems to not work.

**Comment by blazoncek** [comment]
This is a **beta** release, not all features are complete and are subject to change at any time.
You are welcome to document changes and submit PR to WLED documentation.
