### ISSUE TITLE
Invalid Header after loading from website

### ISSUE THREAD

**Issue by ebabcock72** [Aircoookie/WLED#3874]
### What happened?

After installing WLED from the website https://install.wled.me/, I am unable to find the WiFi Hotspot. To debug it, I connect to the serial monitor in Arduino IDE and the output spams `invalid header: 0x000081b3`. I tried multiple versions of WLED.

### To Reproduce Bug

Install WLED onto ESP32-S2 devkit. 

### Expected Behavior

Install successfully and run normally.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0 through 0.15.0-b1 (all 0.14 versions)

### Which microcontroller/board are you seeing the problem on?

ESP32-S2

### Relevant log/trace output

```shell
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
invalid header: 0x000081b3
invalid header: 0x000081b3
invalid header: 0x000081b3
invalid header: 0x000081b3
```

### Anything else?

I was able to get everything working several months ago using the same model of hardware (but a different physical unit). I wanted to add an additional unit to my house, and ran into this issue. I am able to install the Arduino Blink example and everything runs just fine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Not an issue with WLED firmware.
You need correct bootloader and partition map for your ESP32-S2 chip. Unfortunately there are too many variants to have them all covered so you'll need to diagnose which firmware and what partition map to upload yourself. You can try by compiling from PlatformIO which works in most cases if correct board is chosen.

You can, however, open an issue on web installer Github repository.
