### ISSUE TITLE
Multi-threaded connection

### ISSUE THREAD

**Issue by crmie** [Aircoookie/WLED#3890]
Hi I wanted to put some LED plugs together so that it would be parallel, but it was not possible to do whenever the branch was more than 2 circuits did not work. I want to know if you can change the opacity so that LEDs are a branch but from 1 to 36 and 37 to 72 and so on. Anything that happens to 1 to 36 happens to 37 to 72 at the same time

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
Closing.
