### ISSUE TITLE
Password/PIN error when trying to update OTA

### ISSUE THREAD

**Issue by c0nt4x** [Aircoookie/WLED#3894]
### What happened?

I've tried to update OTA both my new devices in the native WLED app and I just keep getting the below error. I have already unchecked the 'Lock Wireless' box but still get the error. Also updating the devices in HomeAssistant is not working as it tries to update but the older version remains.
![IMG_1308](https://github.com/Aircoookie/WLED/assets/70321584/6738d58a-2939-4e6a-919c-4f717be03b56)
![IMG_1307](https://github.com/Aircoookie/WLED/assets/70321584/d7ba26f8-d188-470b-a091-05b082297afe)

### To Reproduce Bug

When trying to update

### Expected Behavior

Firmware should be updated successfully

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0-b1 (build 2212222)

### Which microcontroller/board are you seeing the problem on?

Other

### Anything else?

The devices are Athom controllers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
The only official way to update a WLED device is using "Manual OTA Update" button (and subsequent page, http://wled.local/update) in Security & Updates settings page.
When updating via any other method please contact the application developer.
