### ISSUE TITLE
LED Custom mA/LED is not saved

### ISSUE THREAD

**Issue by robertvb83** [Aircoookie/WLED#3896]
### What happened?

When setting mA/LED to Custom, the value of mA is set to 55 and other values are not saved

### To Reproduce Bug

Set mA/LED to Custom, change mA to 30 and hit save...

### Expected Behavior

Should save custom valies

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.15-b2

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

![Screenshot_20240412-205654](https://github.com/Aircoookie/WLED/assets/36081149/34ec1f23-149b-4d1e-8cb9-0a18b084cf3e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Thanks for reporting. Value is saved correctly and is used correctly by ABL, the error is in display. You can verify by looking at cfg.json
Will fix it in next release.

**Comment by robertvb83** [comment]
Works as it should, thanks for fixing
