### ISSUE TITLE
Not an issue, just a big big thank you :)

### ISSUE THREAD

**Issue by swaxx-ha** [Aircoookie/WLED#390]
Just tried out the newest build and the Theater and Solid Pattern Effects are fabulous. Thank you so much for your hard work and dedication for this project! Will donate a coffee or two :)

Cheers

Mike

**Comment by Aircoookie** [comment]
Hi Mike, awesome that you like WLED so much :) I am so grateful for your kind words (and coffee!) and I hope you'll be able to look forward to even more awesomeness with future updates!
Let me know if you have ideas for new features or run into any issues!

Cheers
Christian
