### ISSUE TITLE
Question: Possibility to control "dumb" 2-pin LED strips with WLED controller (maybe with relay?)

### ISSUE THREAD

**Issue by TimoUrban** [Aircoookie/WLED#3907]
Hi everyone, 

in my last project i used some rgbww strips to get a nice warm light atmosphere. But in reality the warm white chips had bit different color temperatures and it looks not as i expected. 

Is there a way to power on and power off a "normal" LED strip next to the adressable leds? This would be a very smart solution to toggle anything else (fan, motor, etc. ) on and off - independent from the addressable strip. Like an extra output on GPIO, a relay and a button in the mobile app. 

With this solution i could use an addressable rgbw strip and a cheap warm white non addressable led strip in the same project with just one controller.

**Comment by blazoncek** [comment]
That's all already included with WLED.
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
You can also consult [KB](https://kno.wled.ge).
