### ISSUE TITLE
Issue with Effects cycling

### ISSUE THREAD

**Issue by galapogos01** [Aircoookie/WLED#3910]
### What happened?

When following the documentation to set up a macro to cycle between Effects using `FX=~` , WLED gets stuck where effects have been deleted in the code.

This makes effects cycling impossible as the device just gets stuck on one effect.

More info at https://wled.discourse.group/t/wled-sr-cycling-effects-issue/7559/5

It does not appear anyone created a bug for this as it's still currently unfixed.

### To Reproduce Bug

Setup a macro using `FX=~`. 
Assign button to execute macro.
Press button. 
Receive a few effects, then get stuck on one. 

### Expected Behavior

WLED would skip the missing effect and pick the next one. 

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
That's already resolved in 0.15.

**Comment by galapogos01** [comment]
That's a coincidence! The forum thread I referred to is over 12 months old.

When will 0.15 be released? Current release at https://github.com/Aircoookie/WLED/releases/ is still 0.14.3.

Thanks for the quick reply.

**Comment by blazoncek** [comment]
Only God knows.
Beta is out.

**Comment by galapogos01** [comment]
Do you have the commit/issue tracking the fix handy? Wouldn't mind reading more.

**Comment by blazoncek** [comment]
There is a releases page, pay it a visit.
