### ISSUE TITLE
Sound Reactive update

### ISSUE THREAD

**Issue by Ehnja** [Aircoookie/WLED#3914]
I downloaded the soundreactive version 13.4, and i know that its not a priority, and i get its not up to date with the standard.

The "problem" im facing with SR, is that im not able to use the canvases on some effects, a specific example is with the "Candle multi" effect. Which is possible in the standard version.

I guess ideally the sound reactive version would be the same as standard but with the added ability of SR, so you dont miss out on anything.

Idk if your still working on the SR version, if not fair enough. but id think it would be cool if it was kept up to date.

If i have misunderstood anything please let me know.

Thx for WLED its great.

**Comment by blazoncek** [comment]
WLED SR 0.13.4 was developed by different team of people in [WLED SR fork](https://github.com/atuline/WLED).
It is no longer updated AFAIK.

If you want to use regular WLED with Audioreactive usermod, you'll need to update to 0.14.3 which is the most recent version. Your other option is WLED MM by @MoonModules.
