### ISSUE TITLE
Can not perform manual update v0.14.0->v0.14.3 failed

### ISSUE THREAD

**Issue by vitalii-dmytruk** [Aircoookie/WLED#3915]
### What happened?

Manual update of v0.14.0 (build 2310130) can not be updated to v0.14.3 (ESP8266)

### To Reproduce Bug

1. download binary from [https://github.com/Aircoookie/WLED/releases/download/v0.14.3/WLED_0.14.3_ESP8266.bin](https://github.com/Aircoookie/WLED/releases/download/v0.14.3/WLED_0.14.3_ESP8266.bin)

2. disable OTA update lock in security settings

3. Update manually using downloaded binary

### Expected Behavior

Successful update

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

```shell
Don't have any
```

### Anything else?

![Screen1](https://github.com/Aircoookie/WLED/assets/699995/91f7f4ae-06c9-4a88-960f-b438f0864dec)
![Screen2](https://github.com/Aircoookie/WLED/assets/699995/8481875d-3713-498d-b515-10fc20488b71)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
This could be a known issue, as the firmware for 8266 with 2MB flash is over the limit of what's possible for OTA. Unfortunately that's a limitation affecting 8266 boards with less than 4MB flash.

As a workaround, you could try OTA with the `.bin.gz` file from the release page.

* https://github.com/Aircoookie/WLED/issues/3257

**Comment by vitalii-dmytruk** [comment]
Got it. Thanks for response

пт, 19 квіт. 2024 р., 14:03 користувач Blaž Kristan <
***@***.***> пише:

**Comment by vitalii-dmytruk** [comment]
I found the following setting in the LED Preferences. It's possible I have
4KB memory. Is it possible there is another reason why update doesn't work?

пт, 19 квіт. 2024 р., 21:35 користувач Christian Schwinne <
***@***.***> пише:
