### ISSUE TITLE
New Segment input resolution messed up

### ISSUE THREAD

**Issue by robertvb83** [Aircoookie/WLED#3919]
### What happened?

Press new segment will open the respective input dialogue, however the resolution is messed up and "save" is out of visible area

### To Reproduce Bug

Create new segment

### Expected Behavior

The full dialogue screen Should be visible

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.15-b3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

![Screenshot_20240419-174028](https://github.com/Aircoookie/WLED/assets/36081149/eb01692a-53aa-496c-99f3-82ae467e3515)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
Yeah the size on phone is hard to work with , it will work correctly if you collapse the other segment 

https://github.com/Aircoookie/WLED/assets/87589371/001e7c6f-415f-401e-8f8e-c8a804653bf7

**Comment by robertvb83** [comment]
I compiled again today...
![Screenshot_20240420-123216](https://github.com/Aircoookie/WLED/assets/36081149/4c199738-e97d-404e-886c-b35d0fb1f1e9)

**Comment by robertvb83** [comment]
Please wait i am investigating more. It seems that a factory reset solves my issue.

**Comment by robertvb83** [comment]
It works as it should again, thanks for fixing
