### ISSUE TITLE
Output 9 does not work on 0.15.0-b2

### ISSUE THREAD

**Issue by bandi13** [Aircoookie/WLED#3922]
### What happened?

Simply updating to 0.15.0-b2 makes one of my panels no longer light up. I use GPIO 5 for panel 9 in a 2D matrix. Reverting back to 0.14.3 (or even 0.15-0-b1) fixes the issue. I use nine WS2812B panels in a 3x3 matrix. The connections are soldered on to a circuit board, so rewiring won't be the easiest. I use the WLED_N_ESP32.bin type for the firmware.

### To Reproduce Bug

Ugrade the firmware to 0.15.0-b2. Completely reproducible by doing a "Manual OTA". The 9th panel stays lit with whatever was drawn on it last.

### Expected Behavior

I expect the same configuration to work regardless of the version the firmware is running.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0-b2 (build 2404100)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

My suspicion is that some new feature is mapped onto GPIO5, but the release notes don't mention anything.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
There are no restrictions or default assignments for GPIO5. Please do a factory reset and configure the device from scratch, it may be a configuration issue.
You can backup configuration and presets from "Security & Updates" settings page.

If resetting the device has no effect on behaviour then please get a debug build (from @srg74 repository) and post boot sequence serial output. You will need to attach the device to computer using USB cable and use tool for dumping serial output (like Putty or other terminal tool).

**Comment by blazoncek** [comment]
You need a debug build.

**Comment by blazoncek** [comment]
https://github.com/srg74/WLED-wemos-shield/tree/master/resources/Firmware/%40Aircoookie/Dev/0.15.0-b2/Debug_builds

**Comment by bandi13** [comment]
Whoops, sorry, it was really late for me. Here's the output with the debug
image:
>>>
WLED RESET
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8

---WLED 0.15.0-b2 2403280 INIT---
esp32 v3.3.6-16-gcc5440f6a2
arduino-esp32 v1.0.x

CPU:   ESP32-D0WDQ5 rev.3, 2 core(s), 240MHz.
FLASH: 4MB, Mode 3 (DOUT), speed 40MHz.
heap 302524
JSON buffer allocated: 32767
PIN ALLOC: Pin 1 successfully allocated by 0x89 (137)
Registering usermods ...
heap 269512
Reading config
Reading settings from /wsec.json...
JSON buffer locked. (3)
JSON buffer released. (3)
JSON buffer locked. (1)
Reading settings from /cfg.json...
Removing all.
PIN ALLOC: Pin 27 successfully allocated by 0x82 (130)
Successfully inited strip 0 (len 256) with type 22 and pins 27,255 (itype
23). mA=55/555

            PIN ALLOC: Pin 23 successfully allocated by 0x82 (130)
Successfully inited strip 1 (len 256) with type 22 and pins 23,255 (itype
21). mA=55/555

            PIN ALLOC: Pin 2 successfully allocated by 0x82 (130)
Successfully inited strip 2 (len 256) with type 22 and pins 2,255 (itype
21). mA=55/555

           PIN ALLOC: Pin 26 successfully allocated by 0x82 (130)
Successfully inited strip 3 (len 256) with type 22 and pins 26,255 (itype
21). mA=55/555

            PIN ALLOC: Pin 22 successfully allocated by 0x82 (130)
Successfully inited strip 4 (len 256) with type 22 and pins 22,255 (itype
21). mA=55/555

            PIN ALLOC: Pin 4 successfully allocated by 0x82 (130)
Successfully inited strip 5 (len 256) with type 22 and pins 4,255 (itype
21). mA=55/555

           PIN ALLOC: Pin 25 successfully allocated by 0x82 (130)
Successfully inited strip 6 (len 256) with type 22 and pins 25,255 (itype
21). mA=55/555

            PIN ALLOC: Pin 21 successfully allocated by 0x82 (130)
Successfully inited strip 7 (len 256) with type 22 and pins 21,255 (itype
21). mA=55/555

            PIN ALLOC: Pin 5 successfully allocated by 0x82 (130)
Successfully inited strip 8 (len 256) with type 22 and pins 5,255 (itype
21). mA=55/555

           PIN ALLOC: Pin 0 successfully allocated by 0x85 (133)
Starting usermod config.
JSON buffer released. (1)
heap 239252
Initializing strip
Loading custom palettes
Loading custom ledmaps
Matrix ledmap:
   0,  31,  32,  63,  64,  95,  96, 127, 128, 159, 160, 191, 192, 223, 224,
255, 256, 287, 288, 319, 320, 351, 352, 383, 384, 415, 416, 447, 448, 479,
480, 511, 512, 543, 544, 575, 576, 607, 608, 639, 640, 671, 672, 703, 704,
735, 736, 767,
   1,  30,  33,  62,  65,  94,  97, 126, 129, 158, 161, 190, 193, 222, 225,
254, 257, 286, 289, 318, 321, 350, 353, 382, 385, 414, 417, 446, 449, 478,
481, 510, 513, 542, 545, 574, 577, 606, 609, 638, 641, 670, 673, 702, 705,
734, 737, 766,
   2,  29,  34,  61,  66,  93,  98, 125, 130, 157, 162, 189, 194, 221, 226,
253, 258, 285, 290, 317, 322, 349, 354, 381, 386, 413, 418, 445, 450, 477,
482, 509, 514, 541, 546, 573, 578, 605, 610, 637, 642, 669, 674, 701, 706,
733, 738, 765,
   3,  28,  35,  60,  67,  92,  99, 124, 131, 156, 163, 188, 195, 220, 227,
252, 259, 284, 291, 316, 323, 348, 355, 380, 387, 412, 419, 444, 451, 476,
483, 508, 515, 540, 547, 572, 579, 604, 611, 636, 643, 668, 675, 700, 707,
732, 739, 764,
   4,  27,  36,  59,  68,  91, 100, 123, 132, 155, 164, 187, 196, 219, 228,
251, 260, 283, 292, 315, 324, 347, 356, 379, 388, 411, 420, 443, 452, 475,
484, 507, 516, 539, 548, 571, 580, 603, 612, 635, 644, 667, 676, 699, 708,
731, 740, 763,
   5,  26,  37,  58,  69,  90, 101, 122, 133, 154, 165, 186, 197, 218, 229,
250, 261, 282, 293, 314, 325, 346, 357, 378, 389, 410, 421, 442, 453, 474,
485, 506, 517, 538, 549, 570, 581, 602, 613, 634, 645, 666, 677, 698, 709,
730, 741, 762,
   6,  25,  38,  57,  70,  89, 102, 121, 134, 153, 166, 185, 198, 217, 230,
249, 262, 281, 294, 313, 326, 345, 358, 377, 390, 409, 422, 441, 454, 473,
486, 505, 518, 537, 550, 569, 582, 601, 614, 633, 646, 665, 678, 697, 710,
729, 742, 761,
   7,  24,  39,  56,  71,  88, 103, 120, 135, 152, 167, 184, 199, 216, 231,
248, 263, 280, 295, 312, 327, 344, 359, 376, 391, 408, 423, 440, 455, 472,
487, 504, 519, 536, 551, 568, 583, 600, 615, 632, 647, 664, 679, 696, 711,
728, 743, 760,
   8,  23,  40,  55,  72,  87, 104, 119, 136, 151, 168, 183, 200, 215, 232,
247, 264, 279, 296, 311, 328, 343, 360, 375, 392, 407, 424, 439, 456, 471,
488, 503, 520, 535, 552, 567, 584, 599, 616, 631, 648, 663, 680, 695, 712,
727, 744, 759,
   9,  22,  41,  54,  73,  86, 105, 118, 137, 150, 169, 182, 201, 214, 233,
246, 265, 278, 297, 310, 329, 342, 361, 374, 393, 406, 425, 438, 457, 470,
489, 502, 521, 534, 553, 566, 585, 598, 617, 630, 649, 662, 681, 694, 713,
726, 745, 758,
  10,  21,  42,  53,  74,  85, 106, 117, 138, 149, 170, 181, 202, 213, 234,
245, 266, 277, 298, 309, 330, 341, 362, 373, 394, 405, 426, 437, 458, 469,
490, 501, 522, 533, 554, 565, 586, 597, 618, 629, 650, 661, 682, 693, 714,
725, 746, 757,
  11,  20,  43,  52,  75,  84, 107, 116, 139, 148, 171, 180, 203, 212, 235,
244, 267, 276, 299, 308, 331, 340, 363, 372, 395, 404, 427, 436, 459, 468,
491, 500, 523, 532, 555, 564, 587, 596, 619, 628, 651, 660, 683, 692, 715,
724, 747, 756,
  12,  19,  44,  51,  76,  83, 108, 115, 140, 147, 172, 179, 204, 211, 236,
243, 268, 275, 300, 307, 332, 339, 364, 371, 396, 403, 428, 435, 460, 467,
492, 499, 524, 531, 556, 563, 588, 595, 620, 627, 652, 659, 684, 691, 716,
723, 748, 755,
  13,  18,  45,  50,  77,  82, 109, 114, 141, 146, 173, 178, 205, 210, 237,
242, 269, 274, 301, 306, 333, 338, 365, 370, 397, 402, 429, 434, 461, 466,
493, 498, 525, 530, 557, 562, 589, 594, 621, 626, 653, 658, 685, 690, 717,
722, 749, 754,
  14,  17,  46,  49,  78,  81, 110, 113, 142, 145, 174, 177, 206, 209, 238,
241, 270, 273, 302, 305, 334, 337, 366, 369, 398, 401, 430, 433, 462, 465,
494, 497, 526, 529, 558, 561, 590, 593, 622, 625, 654, 657, 686, 689, 718,
721, 750, 753,
  15,  16,  47,  48,  79,  80, 111, 112, 143, 144, 175, 176, 207, 208, 239,
240, 271, 272, 303, 304, 335, 336, 367, 368, 399, 400, 431, 432, 463, 464,
495, 496, 527, 528, 559, 560, 591, 592, 623, 624, 655, 656, 687, 688, 719,
720, 751, 752,
 768, 799, 800, 831, 832, 863, 864, 895, 896, 927, 928, 959, 960, 991,
992,1023,1024,1055,1056,1087,1088,1119,1120,1151,1152,1183,1184,1215,1216,1247,1248,1279,1280,1311,1312,1343,1344,1375,1376,1407,1408,1439,1440,1471,1472,1503,1504,1535,
 769, 798, 801, 830, 833, 862, 865, 894, 897, 926, 929, 958, 961, 990,
993,1022,1025,1054,1057,1086,1089,1118,1121,1150,1153,1182,1185,1214,1217,1246,1249,1278,1281,1310,1313,1342,1345,1374,1377,1406,1409,1438,1441,1470,1473,1502,1505,1534,
 770, 797, 802, 829, 834, 861, 866, 893, 898, 925, 930, 957, 962, 989,
994,1021,1026,1053,1058,1085,1090,1117,1122,1149,1154,1181,1186,1213,1218,1245,1250,1277,1282,1309,1314,1341,1346,1373,1378,1405,1410,1437,1442,1469,1474,1501,1506,1533,
 771, 796, 803, 828, 835, 860, 867, 892, 899, 924, 931, 956, 963, 988,
995,1020,1027,1052,1059,1084,1091,1116,1123,1148,1155,1180,1187,1212,1219,1244,1251,1276,1283,1308,1315,1340,1347,1372,1379,1404,1411,1436,1443,1468,1475,1500,1507,1532,
 772, 795, 804, 827, 836, 859, 868, 891, 900, 923, 932, 955, 964, 987,
996,1019,1028,1051,1060,1083,1092,1115,1124,1147,1156,1179,1188,1211,1220,1243,1252,1275,1284,1307,1316,1339,1348,1371,1380,1403,1412,1435,1444,1467,1476,1499,1508,1531,
 773, 794, 805, 826, 837, 858, 869, 890, 901, 922, 933, 954, 965, 986,
997,1018,1029,1050,1061,1082,1093,1114,1125,1146,1157,1178,1189,1210,1221,1242,1253,1274,1285,1306,1317,1338,1349,1370,1381,1402,1413,1434,1445,1466,1477,1498,1509,1530,
 774, 793, 806, 825, 838, 857, 870, 889, 902, 921, 934, 953, 966, 985,
998,1017,1030,1049,1062,1081,1094,1113,1126,1145,1158,1177,1190,1209,1222,1241,1254,1273,1286,1305,1318,1337,1350,1369,1382,1401,1414,1433,1446,1465,1478,1497,1510,1529,
 775, 792, 807, 824, 839, 856, 871, 888, 903, 920, 935, 952, 967, 984,
999,1016,1031,1048,1063,1080,1095,1112,1127,1144,1159,1176,1191,1208,1223,1240,1255,1272,1287,1304,1319,1336,1351,1368,1383,1400,1415,1432,1447,1464,1479,1496,1511,1528,
 776, 791, 808, 823, 840, 855, 872, 887, 904, 919, 936, 951, 968,
983,1000,1015,1032,1047,1064,1079,1096,1111,1128,1143,1160,1175,1192,1207,1224,1239,1256,1271,1288,1303,1320,1335,1352,1367,1384,1399,1416,1431,1448,1463,1480,1495,1512,1527,
 777, 790, 809, 822, 841, 854, 873, 886, 905, 918, 937, 950, 969,
982,1001,1014,1033,1046,1065,1078,1097,1110,1129,1142,1161,1174,1193,1206,1225,1238,1257,1270,1289,1302,1321,1334,1353,1366,1385,1398,1417,1430,1449,1462,1481,1494,1513,1526,
 778, 789, 810, 821, 842, 853, 874, 885, 906, 917, 938, 949, 970,
981,1002,1013,1034,1045,1066,1077,1098,1109,1130,1141,1162,1173,1194,1205,1226,1237,1258,1269,1290,1301,1322,1333,1354,1365,1386,1397,1418,1429,1450,1461,1482,1493,1514,1525,
 779, 788, 811, 820, 843, 852, 875, 884, 907, 916, 939, 948, 971,
980,1003,1012,1035,1044,1067,1076,1099,1108,1131,1140,1163,1172,1195,1204,1227,1236,1259,1268,1291,1300,1323,1332,1355,1364,1387,1396,1419,1428,1451,1460,1483,1492,1515,1524,
 780, 787, 812, 819, 844, 851, 876, 883, 908, 915, 940, 947, 972,
979,1004,1011,1036,1043,1068,1075,1100,1107,1132,1139,1164,1171,1196,1203,1228,1235,1260,1267,1292,1299,1324,1331,1356,1363,1388,1395,1420,1427,1452,1459,1484,1491,1516,1523,
 781, 786, 813, 818, 845, 850, 877, 882, 909, 914, 941, 946, 973,
978,1005,1010,1037,1042,1069,1074,1101,1106,1133,1138,1165,1170,1197,1202,1229,1234,1261,1266,1293,1298,1325,1330,1357,1362,1389,1394,1421,1426,1453,1458,1485,1490,1517,1522,
 782, 785, 814, 817, 846, 849, 878, 881, 910, 913, 942, 945, 974,
977,1006,1009,1038,1041,1070,1073,1102,1105,1134,1137,1166,1169,1198,1201,1230,1233,1262,1265,1294,1297,1326,1329,1358,1361,1390,1393,1422,1425,1454,1457,1486,1489,1518,1521,
 783, 784, 815, 816, 847, 848, 879, 880, 911, 912, 943, 944, 975,
976,1007,1008,1039,1040,1071,1072,1103,1104,1135,1136,1167,1168,1199,1200,1231,1232,1263,1264,1295,1296,1327,1328,1359,1360,1391,1392,1423,1424,1455,1456,1487,1488,1519,1520,
1536,1567,1568,1599,1600,1631,1632,1663,1664,1695,1696,1727,1728,1759,1760,1791,1792,1823,1824,1855,1856,1887,1888,1919,1920,1951,1952,1983,1984,2015,2016,2047,2048,2079,2080,2111,2112,2143,2144,2175,2176,2207,2208,2239,2240,2271,2272,2303,
1537,1566,1569,1598,1601,1630,1633,1662,1665,1694,1697,1726,1729,1758,1761,1790,1793,1822,1825,1854,1857,1886,1889,1918,1921,1950,1953,1982,1985,2014,2017,2046,2049,2078,2081,2110,2113,2142,2145,2174,2177,2206,2209,2238,2241,2270,2273,2302,
1538,1565,1570,1597,1602,1629,1634,1661,1666,1693,1698,1725,1730,1757,1762,1789,1794,1821,1826,1853,1858,1885,1890,1917,1922,1949,1954,1981,1986,2013,2018,2045,2050,2077,2082,2109,2114,2141,2146,2173,2178,2205,2210,2237,2242,2269,2274,2301,
1539,1564,1571,1596,1603,1628,1635,1660,1667,1692,1699,1724,1731,1756,1763,1788,1795,1820,1827,1852,1859,1884,1891,1916,1923,1948,1955,1980,1987,2012,2019,2044,2051,2076,2083,2108,2115,2140,2147,2172,2179,2204,2211,2236,2243,2268,2275,2300,
1540,1563,1572,1595,1604,1627,1636,1659,1668,1691,1700,1723,1732,1755,1764,1787,1796,1819,1828,1851,1860,1883,1892,1915,1924,1947,1956,1979,1988,2011,2020,2043,2052,2075,2084,2107,2116,2139,2148,2171,2180,2203,2212,2235,2244,2267,2276,2299,
1541,1562,1573,1594,1605,1626,1637,1658,1669,1690,1701,1722,1733,1754,1765,1786,1797,1818,1829,1850,1861,1882,1893,1914,1925,1946,1957,1978,1989,2010,2021,2042,2053,2074,2085,2106,2117,2138,2149,2170,2181,2202,2213,2234,2245,2266,2277,2298,
1542,1561,1574,1593,1606,1625,1638,1657,1670,1689,1702,1721,1734,1753,1766,1785,1798,1817,1830,1849,1862,1881,1894,1913,1926,1945,1958,1977,1990,2009,2022,2041,2054,2073,2086,2105,2118,2137,2150,2169,2182,2201,2214,2233,2246,2265,2278,2297,
1543,1560,1575,1592,1607,1624,1639,1656,1671,1688,1703,1720,1735,1752,1767,1784,1799,1816,1831,1848,1863,1880,1895,1912,1927,1944,1959,1976,1991,2008,2023,2040,2055,2072,2087,2104,2119,2136,2151,2168,2183,2200,2215,2232,2247,2264,2279,2296,
1544,1559,1576,1591,1608,1623,1640,1655,1672,1687,1704,1719,1736,1751,1768,1783,1800,1815,1832,1847,1864,1879,1896,1911,1928,1943,1960,1975,1992,2007,2024,2039,2056,2071,2088,2103,2120,2135,2152,2167,2184,2199,2216,2231,2248,2263,2280,2295,
1545,1558,1577,1590,1609,1622,1641,1654,1673,1686,1705,1718,1737,1750,1769,1782,1801,1814,1833,1846,1865,1878,1897,1910,1929,1942,1961,1974,1993,2006,2025,2038,2057,2070,2089,2102,2121,2134,2153,2166,2185,2198,2217,2230,2249,2262,2281,2294,
1546,1557,1578,1589,1610,1621,1642,1653,1674,1685,1706,1717,1738,1749,1770,1781,1802,1813,1834,1845,1866,1877,1898,1909,1930,1941,1962,1973,1994,2005,2026,2037,2058,2069,2090,2101,2122,2133,2154,2165,2186,2197,2218,2229,2250,2261,2282,2293,
1547,1556,1579,1588,1611,1620,1643,1652,1675,1684,1707,1716,1739,1748,1771,1780,1803,1812,1835,1844,1867,1876,1899,1908,1931,1940,1963,1972,1995,2004,2027,2036,2059,2068,2091,2100,2123,2132,2155,2164,2187,2196,2219,2228,2251,2260,2283,2292,
1548,1555,1580,1587,1612,1619,1644,1651,1676,1683,1708,1715,1740,1747,1772,1779,1804,1811,1836,1843,1868,1875,1900,1907,1932,1939,1964,1971,1996,2003,2028,2035,2060,2067,2092,2099,2124,2131,2156,2163,2188,2195,2220,2227,2252,2259,2284,2291,
1549,1554,1581,1586,1613,1618,1645,1650,1677,1682,1709,1714,1741,1746,1773,1778,1805,1810,1837,1842,1869,1874,1901,1906,1933,1938,1965,1970,1997,2002,2029,2034,2061,2066,2093,2098,2125,2130,2157,2162,2189,2194,2221,2226,2253,2258,2285,2290,
1550,1553,1582,1585,1614,1617,1646,1649,1678,1681,1710,1713,1742,1745,1774,1777,1806,1809,1838,1841,1870,1873,1902,1905,1934,1937,1966,1969,1998,2001,2030,2033,2062,2065,2094,2097,2126,2129,2158,2161,2190,2193,2222,2225,2254,2257,2286,2289,
1551,1552,1583,1584,1615,1616,1647,1648,1679,1680,1711,1712,1743,1744,1775,1776,1807,1808,1839,1840,1871,1872,1903,1904,1935,1936,1967,1968,1999,2000,2031,2032,2063,2064,2095,2096,2127,2128,2159,2160,2191,2192,2223,2224,2255,2256,2287,2288,
Playlist unloaded.
Request to apply preset: 1
heap 234424
Usermods setup
PIN ALLOC: Pin 25 already allocated by 0x82 (130)
AR: Failed to initialize sound input driver. Please check input PIN
settings.
heap 234204
Defaulf WiFi used.
initServer
heap 179720
Local time: 01:28
                 Initial connect or forced reconnect.
Defaulf WiFi used.
initConnection() called.
Access point disabled (init).
Connecting to Fekete csalad...
JSON buffer locked. (9)
Applying preset: 1
JSON buffer released. (9)
Slow effects 34/23.
                   Slow strip 54/23.
                                    Loop took 107ms.
                                                    Usermods took 1ms.
                                                                      Strip
took 79ms.

          Slow strip 41/23.

                           Loop took 43ms.

                                          Usermods took 0ms.

                                                            Strip took 42ms.


Slow strip 40/23.


                 Loop took 42ms.


                                Usermods took 0ms.


                                                  Strip took 41ms.


                                                                  Slow
strip 40/23.
<<<

Looks like there's a different "successful" code (0x85 vs 0x82) on the
faulty GPIO. Also, I'm not sure about those "Slow strip" errors.

-András

**Comment by blazoncek** [comment]
You are using Audioreactive usermod which prohibits more than 8 buses/outputs on versions prior to 0.15.0-b3.
Please use (unreleased ATM) 0.15.0-b3.

**Comment by bandi13** [comment]
I just used the version you linked for the Debug version. Previously I was
loading
https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b2/WLED_0.15.0-b2_ESP32.bin
which exhibits the issue. I don't think that's the Audioreactive version.

-András

**Comment by softhack007** [comment]
> I just used the version you linked for the Debug version. Previously I was loading https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b2/WLED_0.15.0-b2_ESP32.bin which exhibits the issue. I don't think that's the Audioreactive version.

I agree with the conclusion from @blazoncek - this line in the log
> AR: Failed to initialize sound input driver. Please check input PIN

means you're running a firmware that includes the audioreactive usermod. In version WLED_0.15.0-b2 (or older 0.15 pre-releases), WLED with audioreactive will not drive any LEDs on output 9 or 10. Technically its a resource conflict on the I2S driver - outputs 9 & 10 need the I2S unit, however the unit is already "claimed" by audioreactive even when the usermod is disabled.

**Comment by bandi13** [comment]
Note, there's a
https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b2/WLED_0.15.0-b2_ESP32_audioreactive.bin
version in addition to the one I used. I'm using a release version which
exhibits the issue. Either there's an issue with the releases having
Audioreactive in the versions that aren't supposed to have it, or it's not
an Audioreactive issue at all.

**Comment by bandi13** [comment]
I tried on the latest 0.15 build from source as well, and the 9th panel does not work. I will try to put an oscilloscope on to the line. My thinking is maybe the timing isn't correct on it? This week I'm pretty busy, but I'll try to get to it one evening.

**Comment by blazoncek** [comment]
You can compile custom binary by switching to parallel I2S. Almost all necessary code exists in bus_wrapper.h. You will need to select I2S for the first 8 buses in such case.

**Comment by Konos3** [comment]
I have the same issue with another data pin GPIO27, downloaded from https://install.wled.me/, not audioreactive and 9 led strips

**Comment by blazoncek** [comment]
@Konos3 please provide cfg.json and debug dump.

**Comment by bandi13** [comment]
I ended up hooking up an oscilloscope, and on my 9th panel (GPIO5) I don't get any output with the official https://github.com/Aircoookie/WLED/releases/download/v0.15.0-b2/WLED_0.15.0-b2_ESP32.bin release.
My cfg.json is here: [wled_cfg.json](https://github.com/Aircoookie/WLED/files/15124512/wled_cfg.json). Though I don't think it's relevant since other versions work fine with the same configuration. I'll try to get you a debug dump when I can.

**Comment by blazoncek** [comment]
FYI found the bug. It was well hidden.
