### ISSUE TITLE
Do the presets in the playlist start at the same time?

### ISSUE THREAD

**Issue by sous-park** [Aircoookie/WLED#3923]
### What happened?

Hello, I came across a strange feature of how presets and playlists work. 
my equipment:
WLED 15.0-b2 gledopto controller based on esp 32 + ss relay + rgb 24v strip on WS2811

I'm trying to make a playlist to replicate this functionality: https://www.youtube.com/shorts/IwoQO7lnJRE 

Before using the first effect, I need to make a delay of about 0.7 seconds so that the relay and the 24 volt power supply have time to turn on. I used solid mode with intensity 0 and created a preset of it. After that I used the tri wipe effect, And then I use solid effect.

Afterwards I made a playlist with the following settings: Delay (2sec) -> tri wipe 2 sec -> solid 
and everything works correctly, but you need to reduce the delay from 2 to 0.7 seconds and here I ran into a problem, and probably an error in the logic of the work WLED.

It seems that all the presets start working at the same time, and after a given duration they replace each other, this leads to the fact that subsequent effects when displayed do not start working from the beginning? 

If I change the duration of 1 preset to 1 second, upon completion I see the second preset, the effect is displayed at the end of the LED strip. It looks like it started working (although it wasn't displayed) along with the first preset in the playlist.

I recorded a video of the interface where this problem is clearly visible, it seems to me that there is an error here.
I tried changing many settings, but nothing fixed the issue.

https://www.youtube.com/watch?v=b7LY0Ioeix8

### To Reproduce Bug

Playlist with presets:

`{"0":{},"1":{"on":true,"bri":128,"transition":0,"mainseg":0,"seg":[{"id":0,"start":0,"stop":100,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"set":0,"col":[[0,0,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}],"n":"Delay"},"2":{"on":true,"bri":128,"transition":0,"mainseg":0,"seg":[{"id":0,"start":0,"stop":100,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"set":0,"col":[[255,0,17],[0,0,0],[0,0,0]],"fx":55,"sx":239,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}],"n":"Power on"},"3":{"on":true,"bri":128,"transition":0,"mainseg":0,"seg":[{"id":0,"start":0,"stop":100,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"set":0,"col":[[255,0,17],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}],"n":"Solid"},"4":{"playlist":{"ps":[1,2],"dur":[7,20],"transition":[0,0],"repeat":1,"end":3,"r":0},"on":true,"n":"Playlist"}}`

### Expected Behavior

When running a playlist, each preset should start from the logical beginning of the effect, just like it works when changing effects in the effects menu.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 15.0-b2

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
use API `"tb":0` in each preset

**Comment by sous-park** [comment]
> use API `"tb":0` in each preset
wow, that really helped set up the effects.
I looked at the API several times, but the function description is not very detailed, and I'm stupid

Thanks a lot
