### ISSUE TITLE
HTML Sources to GitHub

### ISSUE THREAD

**Issue by stockklauser** [Aircoookie/WLED#393]
Hay Aircookie, 

can you add the Sources of the HTML code to the Project? 
I think it would be an good Idea, to add it and make a Python script or something else to re-integrated it in the headers (shrinked and zipped).

Regards

**Comment by Aircoookie** [comment]
Hi,
they are part of the repo, here: https://github.com/Aircoookie/WLED/tree/master/wled00/data
Admittedly, they may be a bit hard to find :)

Greetings

**Comment by stockklauser** [comment]
Haha sorry for that!
