### ISSUE TITLE
WLED automatically turns on

### ISSUE THREAD

**Issue by sanjitsaluja** [Aircoookie/WLED#394]
My WLED version 0.8.5 automatically turns on randomly. I have Alexa integration turned on. Anyone else having same problems?

**Comment by brentbrooks70** [comment]
@sanjitsaluja Can you check to see if you have **Turn LEDs on after power up/reset** checked under _Settings -> LED Preferences_ If you do it is possible it is rebooting. You can always check the uptime at http://DeviceIP/json/info and see if it has recently rebooted.

**Comment by sanjitsaluja** [comment]
Thanks @brentbrooks70 thats probably it.
