### ISSUE TITLE
WS2805 support (RGBCCT). Or maybe FW1906 can be selected ?

### ISSUE THREAD

**Issue by mathojojo** [Aircoookie/WLED#3969]
**Is your feature request related to a problem? Please describe.**
Support for FW1906 was recently added for 0.15 version of wled. I now have some WS2805 strip RGBCCT, and don't see it in the available options to configure my LED preferences.
WS2805 seems to be very similar to FW1906

**Describe the solution you'd like**
I would like this WS2805 chip to be supported.
If WS2805 can be used using the FW1906 option, then, please make it clear in the list adding FW1906 / WS2805.
If WS2805 can't be used using FW1906 option, then can you please add it ?

**Describe alternatives you've considered**
_

**Additional context**
_

Thank you very much.

**Comment by mathojojo** [comment]
Sorry, There is already an existing issue for WS2805. i close  it

**Comment by mathojojo** [comment]
Closed

**Comment by blazoncek** [comment]
It is implemented.

**Comment by mathojojo** [comment]
Thank you @blazoncek. Can you please tell me which version I should get to test it (probably not the official realease) ?
