### ISSUE TITLE
More Segments i want way more segments for my WLED project.

### ISSUE THREAD

**Issue by JL-Productions** [Aircoookie/WLED#3974]
**Is your feature request related to a problem? Please describe.**
Yes i cannot use WLED for my home project because i need way more segments then currently possible.

**Describe the solution you'd like**
Maybe 100 Segments because i need at least 68 segments for my current project

**Describe alternatives you've considered**
Or a sample code how to use 68 segments of 16 leds where i can send animations to.

**Additional context**
Im making a smart LED table with 68 segments and have touch sensors and want to play an animation on the segment where the motion sensor is triggered

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
You can override by defining `MAX_NUM_SEGMENTS`.
But be warned, anything beyond 32 (ESP32) or 12 (ESP8266) may cause WLED to become unstable and crash unpredictably. Any issue opened because of that will be closed without investigation.
