### ISSUE TITLE
FW1906 single white flash when turned on

### ISSUE THREAD

**Issue by Suxsem** [Aircoookie/WLED#3981]
### What happened?

I have a long strip of FW1906 leds (RGBCCT) and a relay to turn off the power supply when not in use (using the built-in relay feature of WLED). WLED controller is always powered.
Every time I turn on the strip I get a brief (like 0.1s or so) white flash at full brightness before getting the desired color/brightness.
Any help?
Thank you!

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0-b3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Suxsem** [comment]
No one experienced this?

**Comment by softhack007** [comment]
In case you use an SSR relay to control AC power - it might be  a hardware problem.
* https://github.com/Aircoookie/WLED/issues/3581

Another possibility is is you're using TX or one of the esp32 "strapping pins". These are driven by the bootloader, when WLED is not running yet. In this case, try a different pin for LEDs driving.

**Comment by asonnema** [comment]
Hi, I had the same issue. with ESP8266 controller. In Led preferences there is a setting Relay GPIO. This was set to 12, i've removed (unused) it, then the first time flash went away.

**Comment by ggajoch** [comment]
For anyone having this issue, I've found a "good enough" solution which works for me.

You need to power the LEDs additionally from 5 V via Diode, such as:

<img width="4710" height="1510" alt="Image" src="https://github.com/user-attachments/assets/3255e441-55f7-4915-9314-3205ea376f33" />

This way, when there is no 24 V into the LEDs, the 5 V will be enough to power the electronics inside and be able to receive light commands, but not not enough to turn on the LEDs. 5 V draw is minimal.

**Comment by Suxsem** [comment]
@ggajoch thank you for your suggestion, how many leds have your strip? mine has 189 segments (for a total of 189x6=1134 leds) and I'm worried that the small 5v power supply for the controller is not enough

**Comment by ggajoch** [comment]
@Suxsem At one side I have around 17 meters of that strip (so, 170 segmets/controllers). 5V draw was negligible, and USB was more then plenty.
