### ISSUE TITLE
Setting in the config to tell it what binary to grab

### ISSUE THREAD

**Issue by monsieurlatte** [Aircoookie/WLED#3989]
**Is your feature request related to a problem? Please describe.**
Not really, if you could tell the device what binary to grab I could do the updates from within HA directly.  

**Describe the solution you'd like**
I have some athom devices that work perfectly fine but I have to manually grab the .zip for them and update manually.  

**Describe alternatives you've considered**
Nothing as it's not a huge problem just a "would be nice" feature :) 

**Additional context**
Appreciate the project itself and if you dont have time or interest in this I totally understand.

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
That's already available in 0.15

**Comment by monsieurlatte** [comment]
hah, that's awesome and I hadn't gotten around to look at .15 release notes!
