### ISSUE TITLE
Unable to connect WLED v0.15 to Openhab

### ISSUE THREAD

**Issue by danielvoigt01** [Aircoookie/WLED#3991]
### What happened?

openhab can no longer be used with WLED devices with beta version 0.15.
An error message appears due to an incorrect value in the json/state $.rem
(It is presented in the nightlight part nl event with NightlightActive false):

![json_rem_error](https://github.com/Aircoookie/WLED/assets/46729881/5ffe1b63-5b03-4949-8faa-ce7501f6cc79)

It is therefore no longer possible to control the device.

However, the error is apparently due to a change in json.cpp:

![image](https://github.com/Aircoookie/WLED/assets/46729881/9108eb18-30a2-49b4-b6a5-72ae3890e2a9)

If I write out the line again in the original block, it works... Unfortunately I don't know why....

![image](https://github.com/Aircoookie/WLED/assets/46729881/cca6c696-10ac-4048-8672-606ae884caea)

### To Reproduce Bug

Is visible in esp32dev and esp32dev_audioreactive in WLED/json/state in the nl --> rem part. I have also tested the precompiled versions, with the same result.

### Expected Behavior

The expected behavior is the rem value '-1' if the nightlightActive is false ("nl":{"on":false})

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.15.0-b3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moesfeld** [comment]
I can confirm this
