### ISSUE TITLE
cant upgarde WLED 0.13.3 to higher

### ISSUE THREAD

**Issue by pressurejets** [Aircoookie/WLED#4022]
### What happened?

flasing esp d1 mini, can flash 0.13.3 and working 
when come to upgarde to 14.0 14.1 or higher, its not working on ip ?? 
any ideas

### To Reproduce Bug

flashing any higher than 13.3 

### Expected Behavior

after flashing and setting network, ip does not load wled,

### Install Method

Binary from WLED.me

### What version of WLED?

wled 0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
might be a problem with partition sizes - its a well-known fact that OTA updating from older versions is sometimes not possible, and you need to perform a fresh install via USB.

* https://github.com/Aircoookie/WLED/issues/3988
