### ISSUE TITLE
save multiple WiFi networks 

### ISSUE THREAD

**Issue by SpeeterYT** [Aircoookie/WLED#4024]
**Is your feature request related to a problem? Please describe.**
I often move a device with WLED from one room to another and have to change the WiFi every time.

**Describe the solution you'd like**
Add the ability to save multiple WiFi networks, and connect to the best one.

**Describe alternatives you've considered**
I can't change both networks to the same SSID and password

**Comment by blazoncek** [comment]
Available in 0.15
