### ISSUE TITLE
Support Wifi Status LED on free GPIO

### ISSUE THREAD

**Issue by TPPTim** [Aircoookie/WLED#4029]
Hey together,

i would like to use a small blue external led to display the wifi status on WLED WROOM-32. Is there a feature available?
I was not able to find something in the source, or the documentation.

It would be great if you can help me :)

Best regards
Tim

**Comment by blazoncek** [comment]
You will need a custom build with an option (build flag) @softhack007 provided.

If you prefer `my_config.h` you can `#define STATUSLED <GPIO>` there.

**Comment by TPPTim** [comment]
Thank you very much for the fast response and help! This is exact what I need!

Have a nice day!
