### ISSUE TITLE
Sync feature not working 

### ISSUE THREAD

**Issue by roee21** [Aircoookie/WLED#4037]
### What happened?

I am having trouble syncing 3 WLED instances. 
- They are all running latest version (one of them with AudioReactive)
- They are all connected and recognized, showing in the nodes tab
- In Sync Interfaces, all set to same ports, same sync group (receive/send) all rest is default

No matter what I try, when clicking Sync on one of them, nothing happens.

### To Reproduce Bug

Not sure how to reproduce on other systems, but I am running 2 instances on ESP32 and one on ESP8266.

### Expected Behavior

When clicking on the Sync button, this instance should now control all other instances set to receive in the same sync group.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0-b3 

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Enable sync events in Sync Settings. I.e. Direct change.
