### ISSUE TITLE
WLED_0.8.6_ESP8266_ledpin4.bin causes boot loop

### ISSUE THREAD

**Issue by hippieua** [Aircoookie/WLED#404]
After flasing WLED_0.8.6_ESP8266_ledpin4.bin any ESP8266 boards start boot loop after WiFi setup.

I tried Wemos, NodeMCU and my custom boards. All behave the same. After flasing firmware and setting up WiFi credits. Default firmware (WLED_0.8.6_ESP8266.bin)  works perfect.

Exception (2):
epc1=0x3fff470c epc2=0x00000000 epc3=0x00000000 excvaddr=0x3fff470c depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffb70 end: 3fffffc0 offset: 01a0
3ffffd10:  3fff4982 0000002e 3fff2b6c 3fff4ef4  
3ffffd20:  3fff296c 00000000 00000010 00000000  
3ffffd30:  3fff24b8 3fff2480 3fff493c 4023bc53  
3ffffd40:  3fff29b2 3fff2480 3fff493c 4023c044  
3ffffd50:  3ffffd80 000000d8 3fff2548 00000000  
3ffffd60:  3fff2470 3fff2438 3fff296c 3fff493c  
3ffffd70:  3fff493c 3fff4928 3fff2480 40243a11  
3ffffd80:  005e0001 0000fb00 00000020 40101392  
3ffffd90:  3fff4990 3fff4928 3fff2480 402444fc  
3ffffda0:  0000005a 40244fc8 00000074 4022f80c  
3ffffdb0:  00000018 3fff2484 00000001 00000000  
3ffffdc0:  00000002 3fff23f4 00000004 3fff1f20  
3ffffdd0:  3fff2a5c 00000020 00000000 3fff4924  
3ffffde0:  00000000 3fff493c 3fff49a8 40244544  
3ffffdf0:  3fff2480 3ffffe20 00000004 3fff4924  
3ffffe00:  00000016 3fff2480 3fff4924 40243c69  
3ffffe10:  3fff2480 3ffffe20 00000004 4023c098  
3ffffe20:  00000494 00000000 3fff2644 4023c0d4  
3ffffe30:  3fff4928 3fff2480 00000472 40243d3a  
3ffffe40:  3fff48bc 00000001 3fff48dc 00000020  
3ffffe50:  3ffffeb8 3fff2480 3fff4924 40243f13  
3ffffe60:  3ffffeb8 3ffeb428 3fff2480 40243f9f  
3ffffe70:  3fff48bc 00000001 3fffff00 3ffeb428  
3ffffe80:  3fff1bec 00000000 3fff1bec 40221e00  
3ffffe90:  3fff1f20 000000d8 000000d8 4022f5c8  
3ffffea0:  3fff1bd0 00000000 3ffffef0 4022f9f0  
3ffffeb0:  3fff1f20 00000001 fb0000e0 4022072d  
3ffffec0:  3fff1bd0 4023b892 3fff1c00 3fff1c88  
3ffffed0:  3fff1bd0 00000000 3fff1bec 40220786  
3ffffee0:  3fff1bd0 00000000 3fff1bec 402204f5  
3ffffef0:  3fff2c0c 3fff47a4 40220014 402200fc  
3fffff00:  00000000 00000000 3fff1c78 40230244  
3fffff10:  00000000 3fff1bec 3fff1c78 4022a3d3  
3fffff20:  3fff2a74 00000000 40229cfc 402310dc  
3fffff30:  00000000 00000000 ff53f7ce 00000000  
3fffff40:  3fff1bd0 00000000 3ffe8654 40216b75  
3fffff50:  4025febf 00000000 00000000 00000001  
3fffff60:  3fff4b2c 4021eaac 3ffe883c 00000000  
3fffff70:  3fff1bd0 00000000 3fff19cb 40216d8a  
3fffff80:  3fff4b2c 4021eaac 3fff1e48 3fff1e78  
3fffff90:  3fffdad0 00000000 3fff1e48 4021d294  
3fffffa0:  3fffdad0 00000000 3fff1e48 4022ddcc  
3fffffb0:  feefeffe feefeffe 3ffe883c 401007e5  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
Ada

**Comment by sepffuzzball** [comment]
I seem to be experiencing this issue as well!
