### ISSUE TITLE
Incorrect ADC Readings due to 13Bit capture width as default on ESP32-S2

### ISSUE THREAD

**Issue by Orel-A** [Aircoookie/WLED#4040]
### What happened?

handleAnalog() function incorrectly assumes the analogRead() arduino API on ESP32-S2 will give a value between 0-4095 but in fact it's 0-8191 (13bit)

### To Reproduce Bug

-

### Expected Behavior

-

### Install Method

Binary from WLED.me

### What version of WLED?

0.15.0-b4

### Which microcontroller/board are you seeing the problem on?

ESP32-S2

### Anything else?

Can be fixed with a call of analogReadResolution(12); on init code or change the divide by 16 in handleAnalog() function.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
> Can be fixed with a call of analogReadResolution(12); on init code or change the divide by 16 in handleAnalog() function.

You are welcome to provide a PR.

**Comment by blazoncek** [comment]
You can try latest 0_15.

**Comment by Orel-A** [comment]
The fix is working, thanks.
