### ISSUE TITLE
Enable a pixel mapping feature

### ISSUE THREAD

**Issue by damiencorpataux** [Aircoookie/WLED#4046]
**Is your feature request related to a problem? Please describe.**
I would like to be able to map pixels directly in WLED software.

**Describe the solution you'd like**
A way to tell WLED how each physical pixel is mapped in 2D space and have WLED map these pixels.

**Describe alternatives you've considered**
For now I have patched [wledcast](https://github.com/damiencorpataux/wledcast/tree/dev-pixelmapper) to handle pixels mapping and I am streaming to WLED using via DDP.

**Additional context**
- It works pretty well using this alternative: https://www.youtube.com/watch?v=YndGKItbZoQ
- But it requires a computer for a rather simple task:
  - https://github.com/damiencorpataux/wledcast/blob/dev-pixelmapper/wledcast/mapper/__init__.py
  - https://github.com/damiencorpataux/wledcast/blob/dev-pixelmapper/wledcast/mapper/shape.py

Here are examples from my prototype on wledcast:
  - https://github.com/damiencorpataux/wledcast/blob/dev-pixelmapper/dev-mapping.yaml
  - Tester code: https://github.com/damiencorpataux/wledcast/blob/dev-pixelmapper/dev-test-mapping.py

I would like to give it a try but I would need a few pointers on where to begin.

Thank you for making WLED ❤️

**Comment by blazoncek** [comment]
There is: #4018 and #3903 and some other resources on net.
It will most likely not be included in WLED firmware as it will eat away precious memory.
