### ISSUE TITLE
LED settings Buggy in 15b4 on Lolin D1 Mini v4.

### ISSUE THREAD

**Issue by YerBabiE** [Aircoookie/WLED#4049]
### What happened?

Latest v14 works fine on Lolin D1 Mini v4, when I move to 15b4 I can't get the LED settings to work. I run 2 strips of 512 leds, using GPIO 2 and GPIO 1. I can configure and use one strip, but can not use both. The moment I go to add an addtional strip and save the settings the first one running on GPIO 2 gets currupted, and no longer works.

### To Reproduce Bug

Add additioanl strip of LED's, the normally breaks the first strip group.

### Expected Behavior

In v14 this does not happen, and it just works.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 15b4

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Known issue. Use latest sources and compile yourself or wait for b5.
