### ISSUE TITLE
Can you update the color changing circle to be smoother like McLighting

### ISSUE THREAD

**Issue by DONSAREBAK** [Aircoookie/WLED#4064]
1. **Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I'm always frustrated when [This makes me less comfortable using WLED because changing colors in the color circle is not smooth like McLighting, please upgrade that feature also to the latest WLED version ]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment]
Please provide a meaningful description or the issue will be closed.
