### ISSUE TITLE
Which binary for Wemos D1 Mini?

### ISSUE THREAD

**Issue by SteveRMann** [Aircoookie/WLED#407]
Which binary should I download for the Wemos D1 Mini?

**Comment by Aircoookie** [comment]
I'd recommend the `wled_0.8.6_ESP8266_lwip1.bin`! Should be the most stable.

**Comment by r100gs** [comment]
Hello,

I tried it this morning (very short) but after disconnecting it from computer and reconnecting to an usb-charger works great.

**Comment by robyevolution** [comment]
hello, where can i find the : wled_0.9.1_ESP8266_lwip1.bin  ??

**Comment by Aircoookie** [comment]
@robyevolution this file doesn't exist, all 0.9.1 binaries are compiled with lwip1 :)
You can just use the regular `wled_0.9.1_ESP8266.bin`!

**Comment by robyevolution** [comment]
I had the version  wled_0.8.6_ESP8266_lwip1.bin, I tried to install via OTA the WLED_0.9.1_ESP8266_1M_ota.bin but not work, why?

**Comment by austwhite** [comment]
@robyevolution what device are you installing on?
Have you tried one of the other binaries?

Might be best to ask this as a new question as this one is closed and it is a different question to the topic of this issue.

**Comment by robyevolution** [comment]
i have a wemos d1 mini

**Comment by fishbone-git** [comment]
What aspect didn't work?  Did the OTA fail, and did you get any error messages? 
If the OTA succeeded (I'll assume it also then worked well enough to go back to the previous binary).  What wasn't working?

As above, probably best to take this elsewhere as there are now better options for handling questions like this: https://github.com/Aircoookie/WLED/issues/658

**Comment by Aircoookie** [comment]
@robyevolution use the normal `WLED_0.9.1_ESP8266.bin` please, the 1M is only for devices with 1mb of flash like ESP-01 or Sonoff.
You are not the first one to choose the incorrect binary, I really have to make a page that explains which binary to use for what board :)

**Comment by austwhite** [comment]
@Aircoookie 
Maybe need less binaries 🙂

**Comment by Aircoookie** [comment]
Of course, there will be less once LED pin and type are configurable in the web UI 😄
