### ISSUE TITLE
Add the "100-line" demo reel effects?

### ISSUE THREAD

**Issue by BlodKolle** [Aircoookie/WLED#408]
I really like rainbow with glitter from kriegmans fastled demo reel. Is it possible to add the effects from his demo?

[https://gist.github.com/kriegsman/062e10f7f07ba8518af6](https://gist.github.com/kriegsman/062e10f7f07ba8518af6)

Thanks for making WLED! Its a great program for my LEDs.

**Comment by Aircoookie** [comment]
Ok, I'll add that effect soon!

**Comment by Aircoookie** [comment]
Part of v0.9.0!
