### ISSUE TITLE
MQTT Device topic >32

### ISSUE THREAD

**Issue by kriznik** [Aircoookie/WLED#4083]
Hello,
is there any reasoning for having MQTT topics limited to 32 chars only?

I'd like to have bit more room, as I do have MQTT more semantic like house/floor/room/lights/ etc. and 32 is for this not very usable.

Thank you

**Comment by blazoncek** [comment]
Please use custom compile and use MQTT_MAX_TOPIC_LEN and/or MQTT_MAX_SERVER_LEN override.
