### ISSUE TITLE
WS2805 RGBCCT

### ISSUE THREAD

**Issue by evazzoler** [Aircoookie/WLED#4133]
Hi,
I'm not expert but I suppose _WS2805 RGBCCT_ is not _WS2805 RGBCW_.
Well, unfortunately I bought 20mt of _WS2805 RGBCCT_ and I configured them as _WS2805 RGBCW_, the only one available in the 0.15.0-b4 nightly build, but I have a lot of problems.
Some 6-group-led (first, 11, 21) are flickering with alternate colours and don't turn off when I switch off.
If I disconnect the controller, they stop changing color.
I've changed both the controller and the strip, with same result...
I suppose it is a wled-side issue, so I ask if it is a bug or _WS2805 RGBCCT_ must be supported for fixing the issue.
If the support miss and is needed, I kindly ask to add it.
Thanks!

**Comment by blazoncek** [comment]
Please use WLED [forum](https://wled.discourse.group) or Discord for help and support questions.
