### ISSUE TITLE
Feature Request: Dawn to Dusk timer

### ISSUE THREAD

**Issue by fijit586** [Aircoookie/WLED#414]
As many uses of the wled app involve use at night. I would like to see a dawn to dusk feature built in. Nodemcu is already connected to internet so couldn't it pull local dawn and dusk times and allow for auto on and off features. Enhanced by dusk + X hours (2,4,6,8) for customization.
I'm sort of newbie to this stuff so maybe this feature isn't executable in wled. If so, please forgive my ignorance on how this all works.

**Comment by woody2010** [comment]
I use an amazon smart plug for this functionality since I don't want my 60amp power supply to run when not in use.

**Comment by fijit586** [comment]
Thats exactly what i did. Alexa controlled and has schedule function. No power to psu or leds when not in use.

Regards,
Fred Tangelder
248-953-5122
