### ISSUE TITLE
Switch naming scheme for "main" and "segment0"

### ISSUE THREAD

**Issue by Boerny41** [Aircoookie/WLED#4159]
**Is your feature request related to a problem? Please describe.**
Currently, when adding a WLED device to Home Assistant, segment0 gets the name of the WLED instance while main is just called that. Every other segment will get a number:
![image](https://github.com/user-attachments/assets/287c9755-89f3-4b42-bf8d-7461f3ea9f2f)

**Describe the solution you'd like**
I think it would make more sense to name all segments "segmentXY" and "main" the actual device name.

**Additional context**
Not sure if you guys have any influence on the naming scheme. Maybe it is a HA problem, if so, sorry.

Thank you for your ideas for making WLED better! No, thank you for WLED.

**Comment by blazoncek** [comment]
That is something you need to talk to Homeassistant team.
You can name segments in WLED up to 32 characters in length.
