### ISSUE TITLE
Not able to compile WLED with Visual Studio Code

### ISSUE THREAD

**Issue by TPPTim** [Aircoookie/WLED#4171]
### What happened?

Hello,
I am not able to compile the WLED project using Visual Studio Code. I followed this guide: https://kno.wled.ge/advanced/compiling-wled/

When I hit the **build** check button on the bottom PIO bar, only this line popps up in the search fild.
![image](https://github.com/user-attachments/assets/9a06025d-4579-4208-889f-502767bc6b07)

Nothing else happened. The Problems shows:
![image](https://github.com/user-attachments/assets/c03b6d62-1b84-46ba-a92a-62ae0ee1b1eb)

I did not change any thing else in the WLED project folder. Can you please help me what is wrong?

### To Reproduce Bug

Install Git
Install Node JS
Install Visual Studio Code
Install Platform IO Plugin
Open WLED project folder

### Expected Behavior

compiling the project

### Install Method

Self-Compiled

### What version of WLED?

0.14.4

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by netmindz** [comment]
You should really be selecting which build env to use. Please also include a screenshot of what is shown when you select platformio on the right

**Comment by TPPTim** [comment]
When I hit the build check button still nothing happened.
![image](https://github.com/user-attachments/assets/6301e380-9a59-40f1-81a4-8b504095bfe8)

When I click on build at the left side in the menue, then it starts to compile:
![image](https://github.com/user-attachments/assets/cd3e1af9-fb19-4079-8a19-5f32bd370ef0)

Is this behavior ok?

**Comment by blazoncek** [comment]
That is a known issue with PIO since update sometime in late 2022.

**Comment by TPPTim** [comment]
OK thank you very much! What is the common solution for this problem.
Is there an work around or should I use the Build option from the left sided Menue bar instead in future?

**Comment by TPPTim** [comment]
Thank you very much! I have tried this, but I get an error that I cannot explain.
![image](https://github.com/user-attachments/assets/2d856941-e078-43a5-a936-a8b2a9a776bc)

For this I created the **platformio_override.ini** in the main Folder and added some **-D Pindefines**:
![image](https://github.com/user-attachments/assets/2f89a459-08a2-4044-9d47-e6084a8dcd1c)

**Comment by blazoncek** [comment]
Github issues are not intended to educate users.
Please use WLED [forum](https://wled.discourse.group) or [Discord](https://discord.gg/FMvz8nzmat) for help and support questions.

**Comment by TPPTim** [comment]
OK - thank you!
I created a topic here: [](https://wled.discourse.group/t/compile-wled-with-visual-studio-code-platformio-issue/12860)
