### ISSUE TITLE
Improv broken in 0.15.0-b5

### ISSUE THREAD

**Issue by Xevel** [Aircoookie/WLED#4173]
### What happened?

Improv rejects all incoming packets.
Bug happened in commit efa32ed4f6b350512f306cae7e4ee47528416dab.

Cause is that the checksum (l.48) that used to be an "uint8_t" has been changed to a "unsigned" without adding code to keep the value in the same range as before. It thus is not equal to the checksum at the end of the packet.

### To Reproduce Bug

Try to use Improv, it rejects all communication, answering INVALID_RPC_PACKET.

### Expected Behavior

Improv correctly parses incoming packets.

### Install Method

Self-Compiled

### What version of WLED?

0.15.0-b5

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Anything else?

Either restore type to uint8_t, or for example add l.126:
    checksum &= 0xFF;

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
Please provide a PR.
