### ISSUE TITLE
0.90.0 dev - new UI can't scroll effects page in safari on ios

### ISSUE THREAD

**Issue by tube0013** [Aircoookie/WLED#419]
With the new dev build of 0.9.0 on mobile on iOS 13.2.3 I'm not able to scroll the list of effects. I checked via the WLED ios app, Safari and the Chrome app.

![4EBA2551-3DDE-4E9E-9A59-AB8FD2108C88](https://user-images.githubusercontent.com/11084412/70199370-7aae9000-16df-11ea-8e98-4aca7f63af1a.GIF)

**Comment by Aircoookie** [comment]
Thank you, good that you found this issue! Seems like the function for the horizontal swipe cancels the scroll event (which doesn't happen on android). I hope I can find a solution quickly!

**Comment by HaasNL2** [comment]
I noticed this is also in on Andriod.

**Comment by Patrick-Plueard** [comment]
I just downloaded the latest release .9 1 hr ago and I am 
having vertical scrolling issues with Android.

**Comment by SputnikSeven** [comment]
I'm not sure if it's the same bug, but this has been happening for me as well.  I can scroll the effects list down, but if I try to scroll it up it a circular type of wait symbol appears momentarily then it returns me to the main Colors screen. I'm on Android 10 on a Oneplus 6T and I have included a photo of the symbol that appears as scrolling. 
![image](https://user-images.githubusercontent.com/48901896/111243648-d1d82b80-85d7-11eb-84af-eda2689a001c.png)
