### ISSUE TITLE
Using Alexa without actual hardware device

### ISSUE THREAD

**Issue by pete111** [Aircoookie/WLED#42]
Hi there, 
please does somebody know how to emulate Alexa without real alexa device (e.g. without Echo Dot2)? I would really like to try Wled control via alexa but I don't have Alexa device at home. Many thanks

**Comment by Aircoookie** [comment]
I believe the device discovery only works with the real device sadly. However, you could try both the official Alexa app or the Reverb.ai app, both may work if your phone is on the same wifi as the ESP.

**Comment by Aircoookie** [comment]
Closing since not an issue with WLED. Feel free to reopen if you'd like to further discuss this topic.
