### ISSUE TITLE
5th PWM White output does not persist

### ISSUE THREAD

**Issue by jmsblah** [Aircoookie/WLED#4215]
### What happened?

Trying to add 5 "PWM White" LED outputs, only 4 get saved.

### To Reproduce Bug

adding a 5th PWN output in "LED Preferences"

### Expected Behavior

5 outputs to persist

### Install Method

Binary from WLED.me

### What version of WLED?

LED 0.15.0-b6 (build 2410140)

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Anything else?

![image](https://github.com/user-attachments/assets/4ab1a8e0-7a8d-4739-b2d4-3528ee7acc4e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
C3 only allows 4 outputs in the current code. Perhaps an oversight as it *can* do 6 individual PWM outputs, but only 2 digital ones.
