### ISSUE TITLE
Wled Battery Percentage Showing Indicator 

### ISSUE THREAD

**Issue by raunak1334** [Aircoookie/WLED#4218]
Hi , I Want A Bin File Of Wled Battery Percentage Indicator . 

My Battery Config In 3000MAH Lithium-ion 18650 Cell 

Max Voltage - 4.2 
Lowest -2.6 

Can anyone Help Me ?

**Comment by softhack007** [comment]
@raunak1334 please ask support and help requests to the WLED community on discord <a href="https://discord.gg/QAh7wJHrRM"><img src="https://img.shields.io/discord/473448917040758787.svg?colorB=blue&label=discord&style=flat-square"></a>

This issue tracker is strictly for bugs and for proposing new features.
