### ISSUE TITLE
--IDEA-- Integration of a RF Remote with 2 Modes 

### ISSUE THREAD

**Issue by stockklauser** [Aircoookie/WLED#423]
Hay Aircookie, 

i had a nice idea, so i try to integrate a RF Remote (2.4GHz) like the Mi-Led Remote Controllers and want to add 2 Modes.

**1 Mode -- Direct Command Mode** 
You can Control your WLED device directly (set Color, On/Off,...)
**2 Mode -- RF Remote Gateway** 
I want forward the commands from the remote as Raw information (RC Code) to a MQTT Server and work with it on Home Assistant or Node RED (or booth together). 
I had many times the Problems that i cant Control the Devices proberly without my Phone 
So the Distance could be really Far if you have no fun to grab your Phone... :D 

My plan is to Contribute this Integration to the Mainstream of your Project! 
But i must wait for the Remote now, it comes from China ;) 

Regards
Thomas

**Comment by ammmze** [comment]
I'm also looking for something like this. Not sure if this would be helpful, but I did find another project that emulates some of the remotes from MiLight. So essentially the opposite of what we are looking for here, but perhaps may be helpful? 

https://github.com/sidoh/esp8266_milight_hub
