### ISSUE TITLE
How does Alice support WLED?

### ISSUE THREAD

**Issue by Aogu181** [Aircoookie/WLED#4233]
How does Alice support WLED? Not use Home Assistant.
who can tell me?

**Comment by softhack007** [comment]
Looks like it doesn't. 

Please join our discord to get help and support from the WLED community. This github issue tracker is not a good place for such questions.

 <a href="https://discord.gg/QAh7wJHrRM"><img src="https://img.shields.io/discord/473448917040758787.svg?colorB=blue&label=discord&style=flat-square"></a>

**Comment by blazoncek** [comment]
AFAIK Alice is in Wonderland. 😉 
🤣
