### ISSUE TITLE
Dropping Wifi Connection

### ISSUE THREAD

**Issue by ozzi91** [Aircoookie/WLED#424]
Hello!
I have problem with drop wifi connection. After 20-30mins my wled on wemos d1 mini is not reachable till wemos reset. After reset wled is working again for next 20-30mins and goes off. I tried 2 wemos, and it is not working at all.

I tried wled_0.8.6_ESP8266_lwip1 and WLED_0.8.5_ESP8266 flashed by esphome flasher but it doesnt help-the same result. Distance between router and esp its like 10cm. I can provide you any information you want to check it out. If it is matter i integrate it with HA.

**Comment by thedannymullen** [comment]
Have you tried without any leds on it?  I actually had this problem and found my led was causing the wemos to lock up.  I can’t explain it without a scope but assume it was pulling the pin down and causing a reset.  
I found another led and put one in series with my string as a null pixel.  Everything works fine.  
It was confirmed to be hardware as other software had the same issue with the suspect led tied in first.

**Comment by ozzi91** [comment]
Hello! Ty for answer. I tried wit h2 differents leds set and even without any led. Still wifi droping. Blue led on wemos is on so wemos is working :/

**Comment by ksuclipse** [comment]
i'm actually running into the exact same thing.  it failed right at 20 minutes though the effects are still running.  it just dropped off wifi.  here is json/info:

```{"ver":"0.8.6","vid":1910255,"leds":{"count":519,"rgbw":false,"pin":[2],"pwr":0,"maxpwr":65000,"maxseg":10},"name":"WLED Light","udpport":21324,"live":false,"fxcount":83,"palcount":50,"arch":"esp8266","core":"2_5_2","freeheap":18296,"uptime":1200,"opt":119,"brand":"WLED","product":"DIY light","btype":"bin"

**Comment by markusn1** [comment]
I have the same issue with 0.8.6 and 0.9.0-b1. 
0.8.5 does not seem to be affected by this.
Could it be the "non-Wemos" D1 minis from aliexpress?

**Comment by ksuclipse** [comment]
i was seeing it in 8.5 as well.  so additional testing, i had the esp8266 running standalone with no led's attached and it still dropped its wifi eventually.  Strangely when i ran it with AP mode set to always it ran all night with no issue however when i plugged it back into the LEDs it failed after about an hour.  Even the AP is no longer broadcasting.

**Comment by markusn1** [comment]
I just tried using binaries which i compiled myself with different core versions (i tried 2.4.1 and 2.6.2), but it did not change anything.

ksuclipse, what board are you using?

**Comment by ksuclipse** [comment]
Its a knock off nodemcu.  so i was wrong it is still working if i have the AP always on.  give it a try and see if i'm crazy

**Comment by markusn1** [comment]
I tested all WiFi modes (on, on when not connected, off) to no avail. Still the same behavior for me. After about 10-20 mins the Wemos loses WiFi. But like i said, it is still connected to my accesspoint. If i kick it, it will come back reachable, but eventually loses connection again.

**Comment by raoulteeuwen** [comment]
@Aircoookie Could the people at https://github.com/esp8266/Arduino/issues/5083 be on to something re ESP8266 and wifi / sleep? Or this one: https://github.com/esp8266/Arduino/issues/5912#issuecomment-478389370 ? This: https://community.home-assistant.io/t/esp8266-weird-wifi-issues/50484/26 ? This: https://forum.micropython.org/viewtopic.php?t=6860 ?

**Comment by Aircoookie** [comment]
@raoulteeuwen Thank you for the links! I believe I will add a setting to enable `WiFi.setSleepMode(WIFI_NONE_SLEEP);`, but not enable it by default.

The only thing I do not like about it is that it triples the average power consumption of the ESP from 20mA to 60mA (which will also make it run hotter), but if it helps fix disconnects, that tradeoff would be worth it in those cases. I have a very flaky WLED installation myself (because it is outside, signal strength very low, around -80), I will test tomorrow if disabling sleep could help in that case.
All my indoor devices with good signal strength never seem to have any connectivity issues.

It could also be router-dependent, ESPs tend to run better with FritzBoxes or Netgear than TP-link or Asus units as far as i've heard.

**Comment by Aircoookie** [comment]
An update on this. Setting sleep mode unfortunately doesn't seem to help with connectivity on my outside unit. I seems like the signal quality is just really poor on that unit (maybe hardware defect). I also opened the WLED-AP and I can only access it from outside, phone doesn't discover it inside. I will try and flash 0.8.5 (since many of you report issues since 0.8.6) just in case, but I do believe it is just because of the signal. It's a shame too since my phone has good Wifi reception at the place the outside unit is set up...

**Comment by ozzi91** [comment]
Just for info, i really have no idea why this is working or not. I tried:
Use 3 different NODEMCU bought on Aliexpress.
Use 3 different Wemos D1 mini bought on alie
Turn it on without ir with led strip or led lights and it doesnt help.

Devices are like 10cm away from router (Netgear with openwrt). I used different power source aswell like usb form pc or extended power source.
I dont know what i can try more.

**Comment by raoulteeuwen** [comment]
Could you try to assign one or more controllers (NodeMCU/Wemos) a fixed IP and see whether that has any influence? Just wondering whether any other router config option could be in play...

**Comment by ksuclipse** [comment]
Mine is set as static ip, ap always on and connected to WiFi. Been
connected for about a week and it’s still online.

**Comment by ozzi91** [comment]
Even with static ip problem still exist :/

**Comment by markusn1** [comment]
> @raoulteeuwen Thank you for the links! I believe I will add a setting to enable `WiFi.setSleepMode(WIFI_NONE_SLEEP);`, but not enable it by default.
> 
> The only thing I do not like about it is that it triples the average power consumption of the ESP from 20mA to 60mA (which will also make it run hotter), but if it helps fix disconnects, that tradeoff would be worth it in those cases. I have a very flaky WLED installation myself (because it is outside, signal strength very low, around -80), I will test tomorrow if disabling sleep could help in that case.
> All my indoor devices with good signal strength never seem to have any connectivity issues.
> 
> It could also be router-dependent, ESPs tend to run better with FritzBoxes or Netgear than TP-link or Asus units as far as i've heard.

I am running a lot of ESP-based devices (Sonoff, Shelly, WemosD1 etc) on my WiFi (Ubiquiti Unifi UAP-AC-LR), and all are very stable, with the exception of D1s running WLED 0.8.6 and later. I had similar issues with Tasmota when it was compiled with the wrong ESP Core. Trying different core versions on newer versions of WLED did not help though.

**Comment by kabelux** [comment]
My NodeMCU ESP32 is really wifi unstable. Keeps disconnecting every 2 or 5 minutes. I'm using latest beta version (glitter effect is so cool!)

**Comment by Pocke01** [comment]
I have the same problem with a WemosD1 on a QuinLED-dig-uno and running wled 0.8.6. 

After a few minutes I'm unable to ping the ip and connect to the web interface.  
The strange thing is I'm still able to turn leds on/off with home assistant. 

I have tried with both dhcp and static ip.   If I use dhcp my server show the wled as offline at the same time as I'm unable to connect to the ip.  Im using Unifi AP-AC Pro for my wifi.

**Comment by AnshumanFauzdar** [comment]
Ohh well, I think problem is not solved yet
I am also using Wemos D1 mini and same wifi connection drops after 15-20 minutes and I have to manually power off/on wemos!
Please do update if anyone finds a solution!
Thanks :)

**Comment by paularmstrong** [comment]
I have the same issue with an ESP32s: #517. It's even more noticeable with that, as it often fails to stay on for even a few seconds. When it does come on, it'll stay up for ~15 minutes before it drops and needs power-cycling

**Comment by AnshumanFauzdar** [comment]
> I have the same issue with an ESP32s: #517. It's even more noticeable with that, as it often fails to stay on for even a few seconds. When it does come on, it'll stay up for ~15 minutes before it drops and needs power-cycling

Lets see, if anybody comes up to a solution, WLED UI is very dope, I want to use this only!

**Comment by markusn1** [comment]
I just compiled wled from the latest master branch, and so far it seems to be stable (around 2 hours so far). Will keep you updated!

**Comment by AnshumanFauzdar** [comment]
> I just compiled wled from the latest master branch, and so far it seems to be stable (around 2 hours so far). Will keep you updated!

Ohh thank you brother, You did not used the binary?

**Comment by markusn1** [comment]
So, around 20 hours later it is still running fine.
@AnshumanFauzdar yes i did not use one of the precompiled binaries, but compiles it from the most recent source.
@Aircoookie whatever you did, it seems to work for me!

**Comment by AnshumanFauzdar** [comment]
Thanks brother, will compile it ASAP

**Comment by sirs2k** [comment]
> I just compiled wled from the latest master branch

I'm sorry, still a noob here but having wifi issues like everyone else. 
Could you link me to the specific release for the esp8266?

Thank you

**Comment by AnshumanFauzdar** [comment]
> > I just compiled wled from the latest master branch
> 
> I'm sorry, still a noob here but having wifi issues like everyone else.
> Could you link me to the specific release for the esp8266?
> 
> Thank you

Hey,
Have you complied from [here?](https://github.com/Aircoookie/WLED/tree/master/wled00)

**Comment by Apapra** [comment]
My problem is that my four esp8266 nodemcu works perfectly with WLED 0.9.0-b2 (and static IP) till router reboot. I found that after reboot esp8266 don't reconnect to wifi till power off-on. Any way to fix this? Thanks!

**Comment by AnshumanFauzdar** [comment]
> WLED 0.9.0-b2 

Where is b2 released?

**Comment by Apapra** [comment]
> Where is b2 released?

It's not released, it's compiled from source code.

**Comment by AnshumanFauzdar** [comment]
> It's not released, it's compiled from source code.
Okay, Thanks!

**Comment by Apapra** [comment]
> My problem is that my four esp8266 nodemcu works perfectly with WLED 0.9.0-b2 (and static IP) till router reboot. I found that after reboot esp8266 don't reconnect to wifi till power off-on. Any way to fix this? Thanks!

Well, after reading various threads I think I should try to play with "Try connecting before opening AP for x s" setting.

**Comment by AnshumanFauzdar** [comment]
> > My problem is that my four esp8266 nodemcu works perfectly with WLED 0.9.0-b2 (and static IP) till router reboot. I found that after reboot esp8266 don't reconnect to wifi till power off-on. Any way to fix this? Thanks!
> 
> Well, after reading various threads I think I should try to play with "Try connecting before opening AP for x s" setting.

Please do update here if you are able to solve the problem
Thanks :)

**Comment by Apapra** [comment]
I didn't find this setting in current firmware. :) But after I filled all fields in static IP section (IP, gateway, subnet) it seems that problem is solved. Now after router reboot nodemcu is available (online) again.

**Comment by AnshumanFauzdar** [comment]
> I didn't find this setting in current firmware. :) But after I filled all fields in static IP section (IP, gateway, subnet) it seems that problem is solved. Now after router reboot nodemcu is available (online) again.

Okay thanks!

**Comment by deepak-varade** [comment]
> An update on this. Setting sleep mode unfortunately doesn't seem to help with connectivity on my outside unit. I seems like the signal quality is just really poor on that unit (maybe hardware defect). I also opened the WLED-AP and I can only access it from outside, phone doesn't discover it inside. I will try and flash 0.8.5 (since many of you report issues since 0.8.6) just in case, but I do believe it is just because of the signal. It's a shame too since my phone has good Wifi reception at the place the outside unit is set up...

Hi
i think finally found exact solution for continuous rebooting of esp.
if i set time Time and Macros setting using any ntp server with my time zone.is working fine.No connection issue with esp server.Correct me if i am wrong.

**Comment by AnshumanFauzdar** [comment]
> > An update on this. Setting sleep mode unfortunately doesn't seem to help with connectivity on my outside unit. I seems like the signal quality is just really poor on that unit (maybe hardware defect). I also opened the WLED-AP and I can only access it from outside, phone doesn't discover it inside. I will try and flash 0.8.5 (since many of you report issues since 0.8.6) just in case, but I do believe it is just because of the signal. It's a shame too since my phone has good Wifi reception at the place the outside unit is set up...
> 
> Hi
> i think finally found exact solution for continuous rebooting of esp.
> if i set time in Time and Macros setting using any ntp server with my time zone.is working fine.No connection issue with esp server.Correct me if i am wrong.

Thank you for your effort and solution
I just upgraded to latest firmware and now connection is not dropping at all
Thank you!

**Comment by deepak-varade** [comment]
> > > An update on this. Setting sleep mode unfortunately doesn't seem to help with connectivity on my outside unit. I seems like the signal quality is just really poor on that unit (maybe hardware defect). I also opened the WLED-AP and I can only access it from outside, phone doesn't discover it inside. I will try and flash 0.8.5 (since many of you report issues since 0.8.6) just in case, but I do believe it is just because of the signal. It's a shame too since my phone has good Wifi reception at the place the outside unit is set up...
> > 
> > 
> > Hi
> > i think finally found exact solution for continuous rebooting of esp.
> > if i set time in Time and Macros setting using any ntp server with my time zone.is working fine.No connection issue with esp server.Correct me if i am wrong.
> 
> Thank you for your effort and solution
> I just upgraded to latest firmware and now connection is not dropping at all
> Thank you!

Hi 
wled android app showing offline esp ,also when try to connect from Google chrome browser its getting frequently disconnected any idea what may be the problem?

**Comment by AnshumanFauzdar** [comment]
> > > > An update on this. Setting sleep mode unfortunately doesn't seem to help with connectivity on my outside unit. I seems like the signal quality is just really poor on that unit (maybe hardware defect). I also opened the WLED-AP and I can only access it from outside, phone doesn't discover it inside. I will try and flash 0.8.5 (since many of you report issues since 0.8.6) just in case, but I do believe it is just because of the signal. It's a shame too since my phone has good Wifi reception at the place the outside unit is set up...
> > > 
> > > 
> > > Hi
> > > i think finally found exact solution for continuous rebooting of esp.
> > > if i set time in Time and Macros setting using any ntp server with my time zone.is working fine.No connection issue with esp server.Correct me if i am wrong.
> > 
> > 
> > Thank you for your effort and solution
> > I just upgraded to latest firmware and now connection is not dropping at all
> > Thank you!
> 
> Hi
> wled android app showing offline esp ,also when try to connect from Google chrome browser its getting frequently disconnected any idea what may be the problem?

Try to reflash your hardware, it will solve your problem

**Comment by gegu** [comment]
First, thanks for the great project.

For years I have had problems with all projects where a web server is started by ESP8266/ESP32.
Sooner or later I stopped the projects, because none of them worked stable for a long time. No matter if own projects, Tasmota, or whatever.

All settings, tips and recommendations unfortunately did not bring any improvement.
Now I have tested WLED - the same game again.

But now I could find a way to make the webserver stable at least in my environment, which I don't want to withhold from you.

- WLED configuration with static IP
- Every 60 seconds a ping to the local IP address of ESP.

**Implementation**:

Install library [ESP8266Ping](https://github.com/dancol90/ESP8266Ping)

_usermod.cpp_:
```cpp
#include "wled.h"
/*
 * This file allows you to add own functionality to WLED more easily
 * See: https://github.com/Aircoookie/WLED/wiki/Add-own-functionality
 * EEPROM bytes 2750+ are reserved for your custom use case. (if you extend #define EEPSIZE in const.h)
 * bytes 2400+ are currently ununsed, but might be used for future wled features
 */

// climits to define MAX_INT which is used by ESP8266Ping
#include <climits>
// ping lib
#include <ESP8266Ping.h>

// delay between pings
const int CheckWiFiDelayMs = 60000;
// WiFi connection status
bool connectedWiFi = false;
// last ping
long lastPingTime = 0;


//Use userVar0 and userVar1 (API calls &U0=,&U1=, uint16_t)

//gets called once at boot. Do all initialization that doesn't depend on network here
void userSetup()
{

}

//gets called every time WiFi is (re-)connected. Initialize own network interfaces here
void userConnected()
{
	connectedWiFi = true;
}

//loop. You can use "if (WLED_CONNECTED)" to check for successful connection
void userLoop()
{
	// Send ping request to keep the web server alive
	if (connectedWiFi && millis()-lastPingTime > CheckWiFiDelayMs)
	{
		Ping.ping(WiFi.localIP(), 1);
		lastPingTime = millis();
	}
}
```

Compile using lastest core and WLED version from master branch.

**Comment by triggerx** [comment]
I have all but confirmed that this is issue is presented in a Unifi AP based network.  I'm 0 for 5 on NodeMCUs and 0 for 2 D1 Minis on my home Unifi based network when trying to run WLED 0.9.x.  Just keeps resetting.  They work fine on my RAVPower travel router AP.  However EVERY one of those devices work fine on my network when running WLED 0.8.x.  So, I'm almost ready to conclude that *something* in 0.9.x is just not compatible with *something* in my Unifi network.  Also, as an fyi, I have my APs set to 2.4GHz.

**Comment by AnshumanFauzdar** [comment]
Hey @gegu Thank you so much for this wonderful idea I will bookmark this one for future updates

@triggerx This maybe the issue you are mentioning, but after flashing my wemos d1 mini with latest firmware and powering both WS2812 an wemos with same power source solved all my problems!
Thanks

**Comment by Operation760** [comment]
> 
> 
> I have all but confirmed that this is issue is presented in a Unifi AP based network. I'm 0 for 5 on NodeMCUs and 0 for 2 D1 Minis on my home Unifi based network when trying to run WLED 0.9.x. Just keeps resetting. They work fine on my RAVPower travel router AP. However EVERY one of those devices work fine on my network when running WLED 0.8.x. So, I'm almost ready to conclude that _something_ in 0.9.x is just not compatible with _something_ in my Unifi network. Also, as an fyi, I have my APs set to 2.4GHz.

I tend to agree with this. I have an all-Unifi network. However, my NodeMCUs are not the issue and do not exhibit the problem. It's Arilux ESP8285-based RGB/RGBW Controllers which have WLED firmware which do, When I flash them to Tasmota, the problem goes away.

**Comment by dpalecek** [comment]
I can confirm that I have the same exact problems with 2/3 WLEDs appear offline. I am also running a Unifi network

**Comment by acorn1sh** [comment]
I am having the sames issues on a LUXUL network. I am using a static IP address but the IP doesn't even show on the router when I search for connected clients. I have tried 4 NODEMCU and all are having the same issue. I think the last version i had that worked was 8.6. I really like the segments so would like to upgrade.

**Comment by thedannymullen** [comment]
If you set the static ip on the wled controller it may not show in the router.   Typically the router won’t know about something unless it issued the dhcp address for it.

**Comment by triggerx** [comment]
> I am having the sames issues on a LUXUL network. I am using a static IP address but the IP doesn't even show on the router when I search for connected clients. I have tried 4 NODEMCU and all are having the same issue. I think the last version i had that worked was 8.6. I really like the segments so would like to upgrade.

Turn off Alexa Emulation in the Sync Interfaces screen.... that'll fix your problem.

**Comment by acorn1sh** [comment]
Tried turning off sync services and got one to run for an hour. I started to wonder if it isn’t my APs so I took an old router I had laying around and set it up. I didn’t connect it to the network but set up a SSID to to connect my phone and the modem I nodemcu. I have been stable all day so far. On my main network I have my SSIDs hidden could this cause an issue with the connection dropping? Is it possible that a recent firmware update on the AP is making WLED drop?  I can use the old router but it is a pain as it is not on my network.

**Comment by gegu** [comment]
If anyone is interested:

I modified the **unreachable network services ping fix** to keep the code as minimal as possible (external dependency removed) and to make it work with DHCP. [See here](https://github.com/gegu/WLED/tree/master/usermods/Fix_unreachable_webserver)

**Comment by Aircoookie** [comment]
@gegu awesome! Would you be interested in submitting the usermod as a pull request? I would then ask people with WiFi issues to give it a try and if it helps a lot of users I would add it to the base code as an option :)

**Comment by gegu** [comment]
> 
> 
> @gegu awesome! Would you be interested in submitting the usermod as a pull request? I would then ask people with WiFi issues to give it a try and if it helps a lot of users I would add it to the base code as an option :)

Gladly, it's done.
Since it is not really an extension of the functionality, I have not yet created a PR 😄 
But it's true, the connection problems are unfortunately quite common and affect many users.

It would be great if there was a setting option for it. Of course, only if it helps others as well..

**Comment by acorn1sh** [comment]
Would love to give it a try but still new to this. How would I compile for a nodemcu?

**Comment by gegu** [comment]
See the wiki section **[Compile settings - ESP8266](https://github.com/Aircoookie/WLED/wiki#compile-settings)**

**Comment by Aircoookie** [comment]
What might also be of interest for a few of you is https://github.com/Aircoookie/WLED/issues/946#issuecomment-634100863
That surprisingly helped a lot of users.

**Comment by acorn1sh** [comment]
> What might also be of interest for a few of you is [#946 (comment)](https://github.com/Aircoookie/WLED/issues/946#issuecomment-634100863)
> That surprisingly helped a lot of users.

This has fixed my issues so far!

**Comment by gegu** [comment]
After some testing time I can tell you that with a WLED version compiled using the latest core version ESP8266 `2.7.1` there are no more WiFi problems in my environment. 
I have disabled the fix and used the default WiFi settings.

**Comment by gegu** [comment]
**What I wrote was unfortunately not true.**

It worked because MQTT was active. If I decativate MQTT I need the ping fix again.
So it is clear that outgoing requests help to keep the network services active.

> 
> 
> After some testing time I can tell you that with a WLED version compiled using the latest core version ESP8266 `2.7.1` there are no more WiFi problems in my environment.
> I have disabled the fix and used the default WiFi settings.

**Comment by Zoltant7** [comment]
Tried  the latest 10.x Wled,: I got :
wemos d1 mini, with or without leds same,it's looses connection after 5 sec, finally I flashed Tasmota just to see is it a defective unit but seems to work with it just perfectly,

**Comment by RandomPotato893** [comment]
I need some help. I've been troubleshooting this for 3 days and I think I've tried everything imaginable. Different boards, different firmware releases, I did the ping thing, I built all the firmware by myself and it seems to not work. Any help appreciated.

**Comment by AnshumanFauzdar** [comment]
> I need some help. I've been troubleshooting this for 3 days and I think I've tried everything imaginable. Different boards, different firmware releases, I did the ping thing, I built all the firmware by myself and it seems to not work. Any help appreciated.

Hi @RandomPotato893 
I solved this reboot problem by using same power supply for WS2812 and board (In my case wemos d1 mini)

**Comment by psinide** [comment]
@gegu I followed your instructions on the usermods and compiled a bin file with it. I can't see the ping stats on the INFO page.
I've used the d1_mini for my D1 Mini Board.
Is there any configuration change required? or just copy pasting the usermod to wled00 and updating the usermods_list.cpp file as per your instructions enough?

**Comment by gegu** [comment]
The usermod is active, but with the current WLED version the user interface does not work.
You can check this by querying `http://<WLED-host>/json`. PingDelay: 60 should exist here.

If you want to have the UI, you can use v0.11.1 of WLED. `git checkout v0.11.1` before you make the change in `usermods_list.cpp` and the build.

@Aircookie has something changed since v0.11.1 to place custom elements on the info page from a usermod?

**Comment by gegu** [comment]
@psinide UI should work again. You can use now the current master branch.

**Comment by psinide** [comment]
> @psinide UI should work again. You can use now the current master branch.

Thanks, can see it in the GUI. The add on was running as you said, could see PingDelay on the JSON page, but the D1 mini still dropped off the network, albeit, it takes five six hours now, but still dropping off. 

Just flashed it with a new git check out and can the UI is working again. Going to test it again

**Comment by gegu** [comment]
>
> it takes five six hours now, but still dropping off.

It might help if you reduce the delay between pings in the GUI to 10 to 30 seconds. I also recommend rebooting the AP/router once.

**Comment by spinkohass** [comment]
I just setup 2 wled using esp8266 boards and both are having this issue. I tried disabling sleep mode and dont have alexa sync enabled. They lose connection intermittently. I can see they have IP addresses on the router. What's interesting is that if one drops offline, it can still be controlled via the sync feature which suggests that it's the web-server dieing? Anyways, this is super frustrating to a noobie like me. I have not tried going to 11.0 yet. I have 2 new esp boards coming today, will see how that goes.

**Comment by spinkohass** [comment]
> I just setup 2 wled using esp8266/nodemcu boards and both are having this issue. I tried disabling sleep mode and dont have alexa sync enabled. They lose connection intermittently. I can see they have IP addresses on the router. What's interesting is that if one drops offline, it can still be controlled via the sync feature which suggests that it's the web-server dieing? Anyways, this is super frustrating to a noobie like me. I have not tried going to 11.0 yet. I have 2 new esp boards coming today, will see how that goes.

Make that 4/4 boards that have this issue. I tried 11.0 (from 11.1) and it seems to have fixed one board.

**Comment by spinkohass** [comment]
> > I just setup 2 wled using esp8266/nodemcu boards and both are having this issue. I tried disabling sleep mode and dont have alexa sync enabled. They lose connection intermittently. I can see they have IP addresses on the router. What's interesting is that if one drops offline, it can still be controlled via the sync feature which suggests that it's the web-server dieing? Anyways, this is super frustrating to a noobie like me. I have not tried going to 11.0 yet. I have 2 new esp boards coming today, will see how that goes.
> 
> Make that 4/4 boards that have this issue. I tried 11.0 (from 11.1) and it seems to have fixed one board.

11.0 ma

> > I just setup 2 wled using esp8266/nodemcu boards and both are having this issue. I tried disabling sleep mode and dont have alexa sync enabled. They lose connection intermittently. I can see they have IP addresses on the router. What's interesting is that if one drops offline, it can still be controlled via the sync feature which suggests that it's the web-server dieing? Anyways, this is super frustrating to a noobie like me. I have not tried going to 11.0 yet. I have 2 new esp boards coming today, will see how that goes.
> 
> Make that 4/4 boards that have this issue. I tried 11.0 (from 11.1) and it seems to have fixed one board.

11.0 made it 24 hours then dropped it offline. 10.2 didn't work either (2 drops in 2 hours)

**Comment by sockmonkey0223** [comment]
I know it's not a great answer, but after suffering with this on multiple ESP8266 boards forever, I finally switched to an ESP32 board and it has been rock solid.

**Comment by spinkohass** [comment]
> I know it's not a great answer, but after suffering with this on multiple ESP8266 boards forever, I finally switched to an ESP32 board and it has been rock solid.

I appreciate the info - I wish I would have known about this before ordering these other boards. I have ordered 3 digUno in Jan, but am getting impatient as they are taking forever to become available/deliver. I ordered 3 esp8266 to kill the time with the thought of repurposing these boards later. 1 showed up dead. Then I ordered 2 more. At this point, I have 4 boards and all of them are intermittent, but some more than others. Sigh. I guess I will put up with these until the DigUno's show up (esp32 based) and hope for the best.

**Comment by the4jaggz2** [comment]
I just received a DigQuad with the esp32 and for the last couple of days it has been an exercise in frustration. Same issue as all posters have been reporting.  Not only does it take a looong time to pull up WLED (which includes multiple page refreshes) but once in, I get the "connection to light failed".  While the connection does comes back again, it goes out just when you thought that maybe everything was ok.  For some reason, though, all 4 of my esp8266 (non Dig) boards have been rock solid.  Like others I have tried everything and now I am beginning to wonder whether it is a software issue or a HW one.

**Comment by BroManDudeGuyPhD** [comment]
I'm actually running into this as well. One board is a DigUno and one is ESP32. I've flashed both again and turned off WiFi sleep

**Comment by BroManDudeGuyPhD** [comment]
So making each IP reserved on my router and using the reserved IP setting in WLED got me the longest uptime I've seen so far

I also have run into the weird issue where they're both offline in the app, I manually unplug one, it comes online so I turn on sync, and my other light works with sync even though it's offline in the app. This only works about half the time

**Comment by rshea0** [comment]
It would be nice if we could configure a GPIO pin as a reset button to either restart WLED or reset the WIFI connection in the event of a dropout.

**Comment by AnshumanFauzdar** [comment]
> It would be nice if we could configure a GPIO pin as a reset button to either restart WLED or reset the WIFI connection in the event of a dropout.

Wi-Fi connection is working fine on latest versions and there is experimental Wi-Fi sleep option on setting -> Wi-Fi page:
![image](https://user-images.githubusercontent.com/40523329/147849639-fa11a86a-d891-4d00-94fc-32de6ec720bb.png)

**Comment by BroManDudeGuyPhD** [comment]
Actually, I haven't had an issue after separating my 2.4 and 5GHz bands. Try this. Had it on auto before, but now all my smarthome WLED stuff has been online for weeks straight with no issues. Most these boards need 2.4 and for some reason auto on the router just messes them up

**Comment by rshea0** [comment]
> Wi-Fi connection is working fine on latest versions and there is experimental Wi-Fi sleep option on setting -> Wi-Fi page: ![image](https://user-images.githubusercontent.com/40523329/147849639-fa11a86a-d891-4d00-94fc-32de6ec720bb.png)

By latest versions do you mean 0.12.x or beta 0.13.x (I'm on 0.12.x)?

I've been having dropouts that require a reset after five or so minutes of use. I'll give the WiFi sleep option a try!

> Actually, I haven't had an issue after separating my 2.4 and 5GHz bands. Try this. Had it on auto before, but now all my smarthome WLED stuff has been online for weeks straight with no issues. Most these boards need 2.4 and for some reason auto on the router just messes them up

I'm already using separate bands. Do you have WiFi sleep disabled?

**Comment by blazoncek** [comment]
> 3 day ago I updated to 0.13.0-b7. Since that update WIFI seams to be absolute stable... Is somthing changed in 0.13.0 which improves the wifi stability?

you bet! 😁

**Comment by olialb** [comment]
@blazoncek Cool!! I really like this great project with all the features. Thanks to all conributors!
If the new ESP core make the difference its super good news!
At the end its all about stability of the WiFi connection to be happy with it in any day use and  I was really annoyed about this connection losts.

**Comment by rshea0** [comment]
> Newer ESP core. Not WLED related, but still beneficial.

Does this also benefit ESP-8266?

**Comment by blazoncek** [comment]
I think yes. Check platformio.ini.

You can always choose to compile yourself with the latest ESP core.

**Comment by olialb** [comment]
> Does this also benefit ESP-8266?

@rshea0. Actually I am using ESP-8266 and WIFI seams to be stable now!

**Comment by rshea0** [comment]
> @rshea0. Actually I am using ESP-8266 and WIFI seams to be stable now!

Excited to hear! I took a break from my project but I'll have to test it out when I start on it again.

**Comment by Losses** [comment]
Using ESP8266, the issue still exists, is there any way to provide some logs for the developers?

**Comment by blazoncek** [comment]
Use debug build and monitor serial output.
You will need to compile your own binary or check @srg74 repository for pre-compiled debug binaries.

**Comment by Losses** [comment]
> Use debug build and monitor serial output. You will need to compile your own binary or check @srg74 repository for pre-compiled debug binaries.

One more detail, if I turn on the light, it will always work, but if it's turned down, the Wifi connection will be unavailable eventually.

So, there's a question, I have to turn on the "debug mode" and keep watching the terminal until the device is down? That looks really exhausting...

**Comment by blazoncek** [comment]
Unfortunately, yes.

**Comment by Losses** [comment]
Okay, I'll do that

**Comment by Suxsem** [comment]
Same issue for me. Esp8266, after some hours the IP stack dies (wifi connected but no ping, no http response) despite the led effects still running. Will try the no wifi sleep without much hope...

**Comment by Suxsem** [comment]
If I disconnect the device from the access point control panel, it will reconnect and start to repond again, without any reboot required. (runtime is weeks so no power supply related issue here)

**Comment by exhibitO** [comment]
I too have having this issue and it seems agnostic of WLED version, I have tried several and toggled settings above such as Disable Wifi sleep, static IP and it still happens. 

Trying to update firmware for ESP-WROOM-32 as indicated here https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Downloading_guide.html#id4, after that I reflashed WLED and 🤞🏽

**Comment by Gittegatt** [comment]
Had the same issue and I first thought that me D1 Mini has a defect with the wifi interface module.

**Please keep in mind!,**
that every single wire causes interferences. I had a scenario with lots of wires in a small acryl case and most of the pings dropped and those who answered, had a response time latency delay of >1 second.
So, if you are using a lot of wires in a small case with just little distance to the wires, you will facing bad signal strength and even connection drops.

Solution options to avoid this:
1. use a bigger or no case
2. keep distance to the wires
3. drill the wires to cancel / flatten out interferences
4. avoid placing the device nearest area to USB 3.x devices/cable --> [background reason](https://www.elektronik-kompendium.de/sites/com/1310061.htm)  last topic (maybe you have to translate)

Regards and stay tuned. =)
