### ISSUE TITLE
Support for GW6205 RGB LED strips

### ISSUE THREAD

**Issue by jerano** [Aircoookie/WLED#4246]
It is supported by the FastLED project here on GitHub. 

The strip is originally for commercial large scale displays, on ie. house facades.
Practically the same serial protocol and timing as WS281x strip, but with a 12bit color data instead of 8bit.

Thanks!

**Comment by DedeHai** [comment]
WLED does not use fastled but [NeoPixelBus](https://github.com/Makuna/NeoPixelBus). If NeoPixelBus supports it, it can be added, otherwise not.

**Comment by jerano** [comment]
Ok, I will check with them (and their source) to see wether it's possible... Thanks!
