### ISSUE TITLE
fix -Wwrite-string warnings in gcc/arduino

### ISSUE THREAD

**Issue by daavery** [Aircoookie/WLED#426]
in wled00.ino:

@ -482,7 +482,7 @@ void reset()

//append new c string to temp buffer efficiently
-bool oappend(char* txt)
+bool oappend(const char* txt)
{
  uint16_t len = strlen(txt);
  if (olen + len >= OMAX) return false; //buffer full

====================================

in wlen02_xml.ino:
@ -82,7 +82,7 @@ char* XML_response(AsyncWebServerRequest *request, char* dest = nullptr)
}

//append a numeric setting to string buffer
-void sappend(char stype, char* key, int val)
+void sappend(char stype, const char* key, int val)
{
  char ds[] = "d.Sf.";

@ -113,7 +113,7 @@ void sappend(char stype, char* key, int val)
}

//append a string setting to buffer
-void sappends(char stype, char* key, char* val)
+void sappends(char stype, const char* key, const char* val)
{
  switch(stype)
  {
==========================================================

**Comment by Aircoookie** [comment]
Thank you, I have added the suggested changes to the latest master source :)
