### ISSUE TITLE
please explain on the home page a bit more how to find the binary files to download.

### ISSUE THREAD

**Issue by macron0** [Aircoookie/WLED#4276]
Sorry to bother 

But  I googled a lot and every thing points to the git hub page but I just cant find a link to any binary It must be me of ofcourse I just dont understand github.  

Its just that on you tube it looked so simpole have a d1 mini download a bin file flash it. 

well been searching the git hub page for 45 minutes now but I just cant seem to find binaries for wled. Maybe there are more people like me. going to install chrome now which I really wanted to avoid.

**Comment by netmindz** [comment]
They are listed under releases.

If you are new to WLED then you should be using the web installer rather than downloading bin files
