### ISSUE TITLE
Countdown 

### ISSUE THREAD

**Issue by Natal-CWB** [Aircoookie/WLED#4278]
### What happened?

in countdown mode putting date 12/25/2024 (Christmas) appears as "feb 11, 1970 6:00:00".

### To Reproduce Bug

2d Matrix 16x16, effect "Scroling Text"
![image](https://github.com/user-attachments/assets/0e12702e-1c81-44dc-a230-fd004e57ffdf)
I tested removing the 24 hour setting but same result

### Expected Behavior

I expect it show 1M, 11D, 12h, 0m, 10s, or 41 Days, 12h, 0m, 10s

### Install Method

Binary from WLED.me

### What version of WLED?

V0.15.0-b05

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
this is known and being worked on: https://github.com/Aircoookie/WLED/issues/4197

**Comment by Natal-CWB** [comment]
sorry for not seeing it
