### ISSUE TITLE
NODE MCU .09 - settings don't save, multiple releases

### ISSUE THREAD

**Issue by highground88** [Aircoookie/WLED#431]
Firstly great work - I'm obviously having quite a big issue but I hope to be able to use this for our Christmas tree lights soon, as it works great! (temporarily)

I have a Wemos D1 Mini with 4mB flash - and have tried multiple upload methods (esptool, esphome-flasher, Arduino IDE), however none of these methods provide me with a device that the settings persist after a reboot.

I have tried `esptool.py erase_flash` as per #271 , various SPIFFS settings, upload speeds, and also compiled my own 0.8.6 binaries in addition to  WLED_0.8.6_ESP8266.bin, WLED_0.8.6_ESP8266_ledpin4.bin, & wled_0.8.6_ESP8266_lwip1.bin (and also bins from 0.8.5).

I've also tried using in IDE using '1.4 Higher bandwidth' , with no change.

I'm pretty much out of ideas .... is there anything else I can try? 

```
 esptool.py v2.8
Serial port COM9
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 5c:cf:7f:1xxxxxxxxx
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Flash params set to 0x0220
Compressed 535136 bytes to 368264...
Wrote 535136 bytes (368264 compressed) at 0x00000000 in 32.6 seconds (effective 131.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

```

**Comment by highground88** [comment]
Just additionally if it helps .... I've migrated through a bunch of different versions, and now the OTA update constantly results in 'Failed updating firmware!'. Tried with fresh 0.8.5 and .6 bins on both versions (upgrade/downgrade). 

Something somewhere on this board has been messed up?

**Comment by Mariu86** [comment]
You can compile the last dev version 0.9 to see how it's working must be a more stable version. I tried to compile but I have some library errors .

**Comment by highground88** [comment]
Just compiled dev version 0.9, only changes made were to Wifi. Still not holding new setting changes.

Arduino IDE upload options:
[](https://imgur.com/a/8dzrqHl)

**Comment by Aircoookie** [comment]
@highground88 Hi and welcome! You are probably using ESP01 or another board with only 1MB flash. "WLED error 2" means the settings could not be written to flash. Try selecting "Generic ESP8266" in the boards menu and select Flash (1MB, FS none) and saving should work!

**Comment by highground88** [comment]
Wow.... @Aircoookie .... I'm very sorry..... I thought I'd check the chip so I just opened up the enclosure and I've actually put a random NodeMCU board into this. You are spot on. I should sleep more.

That said - I take it this board won't be any good past 0.9.0 anyway based on your notation re SPIFFS?

Sorry again for everyone that used some brain power trying to work out my problem!!!

**Comment by highground88** [comment]
That all said and done - I still cant get this to work even at 1M no SPIFFS.

The 0.9 version goes on, but as soon as any changes are made, I get boot loops.  Using a binary for various ESP8266 etc results in again not retaining data (as I cant control uploads settings perhaps?)

**Comment by Skyking721** [comment]
NodeMcu Error 2 again w/ latest Wled release. hmmm

**Comment by Aircoookie** [comment]
@Skyking721 what binary/compile settings did you use. Make sure to use the one without `1M` in the name
