### ISSUE TITLE
How to change the starting color of "Primary color hue" to blue?

### ISSUE THREAD

**Issue by czweb** [Aircoookie/WLED#4314]
How to change the starting color of "Primary color hue" to blue, the faster the speed, the higher the energy, and use the analog value to transition to red
![3601732454394_ pic](https://github.com/user-attachments/assets/c50dea77-0486-4279-8e59-691861c600f2)
![WechatIMG358](https://github.com/user-attachments/assets/c50365c7-a8b6-491b-b8b0-cb0e136fe52f)
![WechatIMG359](https://github.com/user-attachments/assets/623754c9-b579-4438-9e73-36c82413f298)
![WechatIMG361](https://github.com/user-attachments/assets/3da77f0c-76df-4116-a8aa-caf872ae81fc)

**Comment by DedeHai** [comment]
use presets. also please use the forum or discord for support questions.
