### ISSUE TITLE
unclear use of comma operator in settings_leds.htm

### ISSUE THREAD

**Issue by softhack007** [Aircoookie/WLED#4321]
I'm not sure if this line does the right thing; 
actually my IDE (CLion) warned me of a "comma expression that may lead to subtle bugs".

https://github.com/Aircoookie/WLED/blob/5b989adebc666f5d6314e0ece81c1141a0ae454f/wled00/data/settings_leds.htm#L53

Either the comma is not needed here --> replace with ";"
Or it has a very special intention ?? --> maybe add a comment to explain?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_operator#using_the_comma_operator_to_join_assignments

**Comment by blazoncek** [comment]
```js
function bLimits(b,v,p,m,l,o=5,d=2,a=6) {
	oMaxB = maxB = b; // maxB - max buses (can be changed if using ESP32 parallel I2S)
	maxD = d; // maxD - max digital channels (can be changed if using ESP32 parallel I2S)
	maxA = a; // maxA - max analog channels
	maxV = v; // maxV - min virtual buses
	maxPB = p; // maxPB - max LEDs per bus
	maxM = m; // maxM - max LED memory
	maxL = l; // maxL - max LEDs (will serve to determine ESP >1664 == ESP32)
	maxCO = o; // maxCO - max Color Order mappings
}
```
