### ISSUE TITLE
0.9.0-dev effects don't match previous builds

### ISSUE THREAD

**Issue by marc-gist** [Aircoookie/WLED#435]
Hopefully you can make this backward compatible so that Effect #N is the same from 0.8.6 to 0.9.0.
My testing shows effects have change quite a bit in the latest version and numbering has changed, or effects completely removed :(

**Comment by Aircoookie** [comment]
Hi,
what effects are broken for you using 0.9.0? The sync is designed to be backwards compatible and not many effects have changed (only the In Outs have been replaced with police, as those can be easily done using wipe and two segments). If there are any other effects not syncing up correctly, please let  me know the effect names/IDs so I can take a look at what's wrong :)

Ah, it could be that you mean that the effect list has changed. That is true, it is now in alphabetical order which was in fact user requested. The effects themselves stayed the same though. I know it's a bit weird at first, but you'll get used to it quite quickly and it makes it easier to find a particular effect in the list :)
