### ISSUE TITLE
[0.15] Do not define default audioreactive pins by default

### ISSUE THREAD

**Issue by kilrah** [Aircoookie/WLED#4352]
On controllers running 0.14 without AR with led outputs set to some of the AR default pins (14/15/32), flashing 0.15 and going to change the led settings shows the pin as red and won't allow saving since with the inclusion of AR by default those pins are grabbed by the AR usermod. It is not clear to the user why those pins that were perfectly usable suddenly wouldn't be.

The AR code should probably be modified to set all pins to "unused" by default. If I understand correctly that wouldn't affect existing AR setups since the json settings would already specify the pins, but systems that previously had no AR should not run into the issue. Of course if the user wanted to add a mic they could then assign the pins accordingly.

**Comment by netmindz** [comment]
I believe that it's a specific design decision to preset the pins for audio reactive.

We can however take your comments onboard and look to make it clearer why those pins are unavailable. Elsewhere we do use a drop-down for the pin and that shows the current usage for pins already in use or unsuitable
