### ISSUE TITLE
WLED with FCOB RGBIC LED STRIP WS2812b

### ISSUE THREAD

**Issue by Doriginal** [Aircoookie/WLED#4357]
### What happened?

Hi,
I replaced a 5 meter WS2812b LED strip with 30 leds/meter with a FCOB RGBIC LED STRIP ws2812b with 720 leds/meter (this one: https://fr.aliexpress.com/item/1005005047242165.html?spm=a2g0o.order_list.order_list_main.29.526c5e5bjEETtQ&gatewayAdapt=glo2fra#nav-specification ) and it doesn't work.

my equipment is:

- FCOB RGBIC LED STRIP ws2812b ( https://fr.aliexpress.com/item/1005005047242165.html?spm=a2g0o.order_list.order_list_main.29.526c5e5bjEETtQ&gatewayAdapt=glo2fra#nav-specification )
- FCOB LED Light Power Supply 24v ( https://fr.aliexpress.com/item/1005002190218584.html?spm=a2g0o.order_list.order_list_main.39.11815e5bkaFAqi&gatewayAdapt=glo2fra )
- ESP32-WROOM-32S 32D ( https://fr.aliexpress.com/item/1005006456519790.html?spm=a2g0o.order_list.order_list_main.46.6ccb5e5bP431Mo&gatewayAdapt=glo2fra )

With the WS2812b 5-meter LED strip with 30 led/meter everything works.
Did I forget to do something?

Thanks

### To Reproduce Bug

replaced a 5 meter WS2812b LED strip with 30 leds/meter with a FCOB RGBIC LED STRIP ws2812b with 720 leds/meter

### Expected Behavior

Please help

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0 RC1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
please use the forum or discord for support questions.
