### ISSUE TITLE
[ESP32] Unable to upgrade from 0.14.4 to any 0.15.x releases

### ISSUE THREAD

**Issue by jsloyer** [Aircoookie/WLED#4369]
### What happened?

I am unable to update to any 15.x releases for one of my ESP32’s. I tried rc1, b3, and b7. All fail.

![IMG_2982](https://github.com/user-attachments/assets/6033a04c-3f94-4416-81b6-97b77b6e14e7)
![IMG_2985](https://github.com/user-attachments/assets/58dcdd3d-0371-42ab-aade-5cbd7389f94f)
![IMG_2986](https://github.com/user-attachments/assets/26f01b55-8d46-456a-8cb0-af8603bdd0f1)
![IMG_2981](https://github.com/user-attachments/assets/143e60e8-3439-45d9-9b09-928f18ec8404)

### To Reproduce Bug

I’ve only had this on a single ESP32. All of my other ESP’s upgraded fine.

### Expected Behavior

To be able to upgrade to 15.x.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.4 (build 2405180)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
maybe related to tasmota bootloader: https://github.com/Aircoookie/WLED/issues/4241

**Comment by netmindz** [comment]
Please confirm @jsloyer exactly how and where you did your **_initial_** install of WLED onto this device from (not how you installed any previous updates)

**Comment by jsloyer** [comment]
I'm actually not sure. The ESP32 came from quindoor, https://quinled.info/quinled-esp32/.

**Comment by blazoncek** [comment]
This is related to inadequate application partitions. Your file system should read 983kB when correct partitions are in place.
You will need to flash using USB connection but doing so will erase all file system content (configuration and presets) so back up before flashing.

**Comment by misosec** [comment]
I have the same problem with Quinled ESP32 updated via Homeassistant. My file system size is the same: 20/1707 kB.
HA doesn't update is either - updating just stops.

**Comment by chrisella** [comment]
I'm experiencing the same problem +1
I've tried updating directly with the various downloaded binaries AND through HA, neither works.

**Comment by DedeHai** [comment]
@misosec @chrisella  the answer was already given by blazoncek. your file system MUST BE 983kB (see info tab in WLED) or you will not be able to do over the air update.

**Comment by chrisella** [comment]
Ah that's awkward then, particularly for several of my units that are "deployed" in positions that make that not easily possible.
Guess this is the end of the road for me with WLED then until I possibly get a chance to physically pull them out 😢

**Comment by softhack007** [comment]
> I have the same problem with Quinled ESP32 updated via Homeassistant. My file system size is the same: 20/1707 kB.
> HA doesn't update is either - updating just stops.

@intermittech (Quindor) Can you check quinled boards still ship with the (very old) 1.5MB LittleFS partition scheme? Or is this user having a possibly very old install?

FYI, we have changed to a new partition scheme - 1MB LitleFS - already 3 years ago (WLED 0.13.0).

**Comment by erikvaliquette** [comment]
Same issue, can't update to version 15 on all my quin led devices. Unable to communicate with wled api

![image](https://github.com/user-attachments/assets/9b77597e-bab5-4bd8-99b6-7878c63013d0)

**Comment by blazoncek** [comment]
@erikvaliquette please use USB method as described above.

**Comment by gzxto1** [comment]
Same issues here, all my ESP8266 worked fine, all ESP32 don't work via HA or binary upload

**Comment by erikvaliquette** [comment]
> @erikvaliquette please use USB method as described above.

Which is not really possible for the moment as they are part of the holiday decorations 🎅

**Comment by jsloyer** [comment]
Just for others that find this using the installer at install.wled.me fixed this for me.

**Comment by chiefymuc** [comment]
Quinled also has binaries here: https://github.com/intermittech/QuinLED-Firmware/releases

**Comment by intermittech** [comment]
> > I have the same problem with Quinled ESP32 updated via Homeassistant. My file system size is the same: 20/1707 kB.
> > HA doesn't update is either - updating just stops.
> 
> @intermittech (Quindor) Can you check if quinled boards still ship with the (very old) 1.5MB LittleFS partition scheme? Or is this user having a possibly very old install?
> 
> FYI, we have changed to a new partition scheme - 1MB LitleFS - already 3 years ago (WLED 0.13.0).

We've been flashing WLED v0.14.x for quite a while now so that should be fine in regards to partition size. We also offer https://install.quinled.info which has also had that version for quite a while.

It is however possible people have had these boards since the v0.13.x days and never updated other then doing OTA. My boards all come with USB-C partly because of this reason, although I get it's sometimes inconvenient when it's part of a show right now!

I will doublecheck though to make sure boards aren't going out with a too old firmware, maybe update the pre-installed version to v0.15 now that it's been released.

**Comment by softplus** [comment]
Is there a way to change the partition without a USB connection? I set up 2 ESP32 modules a few years ago, updates until 14.4 worked fine, they're installed in pretty inaccessible places. The generic "update failed" was a bit annoying to figure out, but I realize "back-updating" 14.4 to check for an incompatible setup required for the next release is ~impossible :).

**Comment by blazoncek** [comment]
Short answer: No.

Long one: Technically possible but will require specially crafted software that would copy itself out of regular application partitions. Then update partition table, format partitions and start OTA download process.

**Comment by chiefymuc** [comment]
Someone apparently figured it out here: 
https://www.reddit.com/r/esp32/comments/18dtwip/changing_the_partitiontable_over_the_air/

But I am not smart enough to understand without a step-by-step guide... But would be highly interested as my DigUno is also hidden.

**Comment by blazoncek** [comment]
@chiefymuc I wrote it is technically possible. But it is not for the faint-hearted.

**Comment by softhack007** [comment]
@chiefymuc I just found the same reddit post.

If you cannot access the esp32 to update via USB, I would not recommend trying the hack described by the linked articles. It anything goes wrong, your device will be in a bootloop (not able to start wled) and you must take it down from the roof to your desk, in order to attach it to a computer by USB.

https://gist.github.com/floitsch/ed2530caa613581057d8998dee0a911f

The author of the hack says "it's like replacing the jet engine while you are flying it". I think that's a serious warning.

**Comment by softplus** [comment]
I created a firmware to fix this for me. You basically OTA to this, have the partition table updated (and hope, I guess), then you can OTA to WLED 0.15.0. https://github.com/softplus/Esp32Repartition

I've tried this with a test device, and my two WLED devices that were stuck because of the partition table sizes, but I can't promise that it'll work everywhere, obviously. Also, if something goes weird with your device at the wrong time (there's a really short window), it can leave the partition table broken.

**Comment by rhinodavid** [comment]
> I created a firmware to fix this for me. You basically OTA to this, have the partition table updated (and hope, I guess), then you can OTA to WLED 0.15.0. https://github.com/softplus/Esp32Repartition

Works for me on a DigUno that initially had v13 installed. Legend.

**Comment by chrisella** [comment]
> I created a firmware to fix this for me. You basically OTA to this, have the partition table updated (and hope, I guess), then you can OTA to WLED 0.15.0. [softplus/Esp32Repartition](https://github.com/softplus/Esp32Repartition)

As a warning, this unfortunately didn't work for me, luckily I tried it first on one of my "easier" to access (still PITA) units", so now that it's unresponsive I'll have to go about the harder route. This could in all likelihood be due to my board or config or something else, but just be warned that path is still full of possible nastiness.

**Comment by blazoncek** [comment]
One (possibly crucial) note when updating partitions from previous version using OTA:
When an ESP device was 1st flashed (or last time it was flashed using serial connection) it was flashed with bootloader and app0 binary. Bootloaders change! What was originally flashed may no longer work (well) with recent WLED firmware as some features may require newer bootloader features.
I just want you to be aware of the possibilities.

**Comment by nmbgeek** [comment]
> I created a firmware to fix this for me. You basically OTA to this, have the partition table updated (and hope, I guess), then you can OTA to WLED 0.15.0. https://github.com/softplus/Esp32Repartition
> 
> I've tried this with a test device, and my two WLED devices that were stuck because of the partition table sizes, but I can't promise that it'll work everywhere, obviously. Also, if something goes weird with your device at the wrong time (there's a really short window), it can leave the partition table broken.

This worked for me!  Thank you @softplus

**Comment by netmindz** [comment]
Thanks for sharing that @softplus 

Both the WLED (AC) and WLED-MM teams have both been struggling with image size Vs the current partition table out in the wild that allocates quite a large amount of space for the file system that only has the config and presets files in most cases. 

We have wanted to reduce the size of the filesystem to give more space to the app, perhaps your approach of using an intermediate specialist bin might be something we can use for that

**Comment by chatziko** [comment]
@softplus : just wanted to say a big thanks for your Esp32Repartition tool, it worked like a charm.

Fun story: after running the tool and flashing WLED 0.15 I was waiting for WLED-AP to appear to restore my config. But it didn't, so I got dissapointed and started preparing ladders for USB flashing. Only to realize that my WLED configuration was actually __preserved__ by the partition upgrade for some reason, so the upgraded WLED just happily connected to my wifi and I was ready to go 😄

**Comment by vaderag** [comment]
Okay - so landed here as (now it's winter) my WLED is starting to be used again... 
I am on 14.4 and similarly to those here I cannot update to 0.15

My questions are
1. If the WLED is not accessible is the repartition tool above safe?
2. Failing that, it seems reflashing and re-setting up via USB... which is definitely not going to be easy for me so...
3. Is there any reason not to stay on 14.4?

~I guess the other question is why all this faff - what's the advantage of changing the file system?!~ (saw this above)

**Comment by JHarding86** [comment]
@softplus You're a hero. Worked like a charm on my Quinled board. Configuration preserved throughout the update process. Wonderful! Thank you.
