### ISSUE TITLE
Random preset json not work

### ISSUE THREAD

**Issue by Niorix** [Aircoookie/WLED#4381]
### What happened?

I have a few presets. I want to change these effects randomly. I created a preset with the json `{"ps":"1~5~r"}`, but it switches presets sequentially.

### To Reproduce Bug

Upload presets.json and select "rnd" preset a few times.
[presets.json](https://github.com/user-attachments/files/18105621/presets.json)

### Expected Behavior

Presets switched randomly.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0 (build 2412100)

### Which microcontroller/board are you seeing the problem on?

ESP8266, ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
`{"ps":"1~5r"}`
