### ISSUE TITLE
Estimated Current Isn't Reported When Off Since 0.15.0

### ISSUE THREAD

**Issue by AlexKusnezov** [Aircoookie/WLED#4383]
### What happened?

Estimated Current Isn't Reported When off Since 0.15.0:
<img width="547" alt="Screenshot 2024-12-12 at 16 26 40" src="https://github.com/user-attachments/assets/7edd268b-67df-4c8c-b84a-eed40f05e6a1" />

0.14.0:
<img width="567" alt="Screenshot 2024-12-12 at 16 28 17" src="https://github.com/user-attachments/assets/9db1f0c5-3819-4baf-a960-b816340521b7" />

Brighness limiter was on in both cases
After reverting back to 0.14.0 brightness limiter got disbaled so I had to re-enable it manually

Also on Athom bulbs 0.15.0 doesn't report estimated current at all!

### To Reproduce Bug

 - update to 0.15.0
 - look at "estimated current"

### Expected Behavior

Estimated Current should be prperly reported

### Install Method

Binary from WLED.me

### What version of WLED?

0.15.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment]
0.15.0 uses new ABL, please update settings and verify again.

**Comment by AlexKusnezov** [comment]
> 0.15.0 uses new ABL, please update settings and verify again.

Same
unchecked ABL, reboort, check ABL set ma, reboot, result:
"Not Caclulated" when off

**Comment by blazoncek** [comment]
That is expected. ABL calculation has been moved into LED output driver to support per output limitations.

**Comment by AlexKusnezov** [comment]
@blazoncek got it, sadly that way the consuption of the esp itself is lost.

**Comment by blazoncek** [comment]
ESP current is 120mA constant and irrelevant  when LEDs are off as far as calculation goes.

**Comment by Riscue** [comment]
it's not reported to Home Assistant Integration also, lost my power consumption values after 0.15.0

**Comment by AlexKusnezov** [comment]
> it's not reported to Home Assistant Integration also, lost my power consumption values after 0.15.0

that's right, same here.

**Comment by DedeHai** [comment]
@blazoncek  would it be possible to just report the 0.12A fixed instead of 'not calculated'? Or is there any good reason to break backward compatibility with HA? If this is something that is not possible with the new ABL, then this needs to be reported to HA to implement a fix for the new behaviour IMHO.

**Comment by AlexKusnezov** [comment]
> @AlexKusnezov can you check if its ok now? latest bin with a fix is here: https://github.com/Aircoookie/WLED/actions/runs/12378696924

thanks, looks good.
