### ISSUE TITLE
Internal temperature causes 'error 12: preset not found' even without any presets

### ISSUE THREAD

**Issue by orbitinstasis** [Aircoookie/WLED#4390]
### What happened?

every time i open one of my two wled instances, I get 'error 12: preset not found'

### To Reproduce Bug

I have updated to version 15 recently and don't remember the error showing there, but I can isolate it to this mod because I emptied all my presets and the error still showed, and only stops showing when i disable the mod, and starts showing again when i re-enable the mod

### Expected Behavior

stop showing the error 

### Install Method

Self-Compiled. Completely vanilla to the 'main' branch except for the config in platformio.ini changes to default_envs, uncommented line to the onewire lib, 

and added: 

```
-D USERMOD_DALLASTEMPERATURE
-D USERMOD_INTERNAL_TEMPERATURE
-D USERMOD_PWM_FAN
```
under [env:esp32c3dev]
### What version of WLED?

0.15.0

### Which microcontroller/board are you seeing the problem on?

ESP32-C3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lost-hope** [comment]
What preset is set in the dialog field in the setting of the internal temp preset?

**Comment by orbitinstasis** [comment]
> What preset is set in the dialog field in the setting of the internal temp preset?

0

**Comment by lost-hope** [comment]
Try setting that to -1

**Comment by blazoncek** [comment]
0 should be a valid value and should mean "no preset" as no presets can have id 0.

**Comment by orbitinstasis** [comment]
Just did a small but reasonable boundary test. 

If i set the 'preset to set' value to -1 and click save, it changes automatically back to 0. Same behaviour on the polling setting if you go anything below 10000.

I always get th error if the setting is 0 for the preset, and also occurs if the number is a positive integer higher than any preset I have saved.

However, the error never shows if the preset to set is an integer above 0 which I also have a saved preset for

**Comment by lost-hope** [comment]
OK i will look into it later. Maybe tomorrow. i havent added the preset functionality to the usermod, but normally it should not try to change the preset when set to 0. (atleast that is what a quick look showed)

**Comment by lost-hope** [comment]
Found the issue and made a PR.

**Comment by orbitinstasis** [comment]
> Found the issue and made a PR.

Thanks - when might this move to the main branch ? I'm assuming that's the branch the devs want most users who are compiling usermods to use?

**Comment by fredkampf** [comment]
Hi.  I am using an esp 8266 and am experiencing this issue.  I loaded the most recent verson 16 but still are experiencing the issue.  When I try to save a default, I get the error and it does not boot to the saved effect.  thanks!

**Comment by DedeHai** [comment]
this happens if a non existing preset is being applied at bootup. a config reset usually fixes it.
