### ISSUE TITLE
Weird flicker when toggling on/off Athom bulbs with 0.15.0-b6

### ISSUE THREAD

**Issue by Andro-Marian** [Aircoookie/WLED#4396]
### What happened?

When the fade-in starts and when fade-out is finishing. A weird flicked happens.
https://drive.google.com/file/d/1YgvZzD1sl7MFx1y-zQKS_JEvJhUdDfPS/view?usp=sharing

When turning on is starting to increase brightness, then turning instant off than on again. And vice versa.

### To Reproduce Bug

Flash the  0.15.0-b6 or the release 0.15 to any Athom 7w or 15w.
Turn it on/off by the web interface.

I think was introduces in **0.15.0-b6**. Works fine on **0.15.0-b5**

Noticed a flicker when going on or off.

### Expected Behavior

To be smooth as before.

### Install Method

Binary from WLED.me

### What version of WLED?

0.15-(b6/release)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
I noticed this too when working on the new PWM outputs. It is related to fading value being offset from the starting and target value but I could not pin-point where this actually happens.

**Comment by Andro-Marian** [comment]
Not sure what was changed on Beta 6. Thinking if the https://github.com/Aircoookie/WLED/issues/3196 was introduced first on b6

**Comment by JorinL** [comment]
Hey there,
before opening a complete new - according to the video - it could be also my issue.

I think i might have the same thing - it "looks" pretty the same.

I have this problem on my 3 PWM strips.
When I cut the transitiontime it is gone - with transition it flashes when turning on before dimming up and when turning off while dimming down a flash and dimming further down.

I added a small video of the current situation.
https://github.com/user-attachments/assets/f6009672-1853-451c-b2fd-f404a0fe5acc

**Comment by marcolino7** [comment]
Hi,
same behavoiur here, WLED 0.15 on PWM RGBW strip. I reverted back to 0.14 and issue gone

**Comment by DedeHai** [comment]
I found one issue in the code related to CIE brightness curve calculation. Is the issue gone if you enable dithering in the PWM LED settings?

**Comment by JorinL** [comment]
Thanks for fixing :-)
Tried the Alpha 16. Works :-)

**Comment by SuulsaK** [comment]
I don't know if I'm doing something wrong, but I've flashed several of my Athom bulbs with supposedly fixed alpha firmware and now the flickef is gone, but is replaced with nice slow transition at start, then sudden jump to full brightness. I've checked if i have correct pins set, the issue still persist.
