### ISSUE TITLE
FX range with analog clock overlay. 

### ISSUE THREAD

**Issue by kayrozen** [Aircoookie/WLED#44]
First of all, this is a great work you've done here :) 

I'm using 0.7.1 rev and using it for an analog clock. I'm currently aving 144 leds, 0 to 119 being the clock and 120 to 144 being for fx animations (i would like to tie them to a wheater api in the future) 

But as i understand it, the clock is an overlay so any animations that runs underneat it, are partly hidden (as a fact). 

Is there a way to define range of FX animations (like the range in the clock sections) ? 

Thx a lot for your work again. (and i'm looking forward the API macro timed calls :) )

**Comment by Aircoookie** [comment]
This is possible using the new Segments feature! It is already available via JSON and soon also via the UI :)
