### ISSUE TITLE
broken dissolve Effect

### ISSUE THREAD

**Issue by IronGuy-tech** [Aircoookie/WLED#4432]
### What happened?

so when ever i put the effect "dissolve" and turn off the ligths via the app the ligths won´t fully turn off and leave a lot of pixels still lit but with any other effect they  turn of normaly.

### To Reproduce Bug

you just need to select the dissolve effect and then try to turn your ligths off, if it does not work the first try turning the on off 5 times and then the bug will take effect.

### Expected Behavior

the ligths won´t fully turn off and will leave a lot of pixels lit up but some are going to turn off.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0 (build 2412100)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
duplicate: https://github.com/Aircoookie/WLED/issues/4401
