### ISSUE TITLE
Segment names resetting after reboot

### ISSUE THREAD

**Issue by r1b4z01d** [Aircoookie/WLED#4434]
### What happened?

After rebooting all segment names get reset to segment 1,2,3, etc. 

### To Reproduce Bug

1. Name a segment
2. Save
3. reboot
4. reload ui
5. observe segment renamed back to default

### Expected Behavior

custom name should be saved after reboot

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.15.0 (build 2412100)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
only what you save in a preset persists. rename, save as preset, load preset at bootup and segment names persist.
