### ISSUE TITLE
Auto power off circuit control

### ISSUE THREAD

**Issue by mryndzionek** [Aircoookie/WLED#4436]
I want to use an auto power off circuit with WLED controller. In order to do that I need to control the "latching" GPIO as soon as possible after boot. What would be the best way to achieve that? Hardcode the GPIO control directly in source, or some other way (dedicated usermod, etc.)?
Oh yeah, I almost forgot, I also need to toggle the GPIO after nightlight timer expires. Would it be possible to do that via macros?

**Comment by DedeHai** [comment]
please use discord or discourse forum for support questions. The relay pin does pretty much what you want. If you need it faster, edit the code.
