### ISSUE TITLE
ESP32 update from 14.4 to 15 not possible

### ISSUE THREAD

**Issue by PLCHome** [Aircoookie/WLED#4438]
### What happened?

When installing the WLED_0.15.0_ESP32.bin via the web interface, the message "Update failed!
Please check your file and retry!" appears.

### To Reproduce Bug

Install WLED_0.14.4_ESP32.bin on an ESP32 then upgrade to WLED_0.15.0_ESP32.bin via the web interface.

### Expected Behavior

Install WLED_0.14.4_ESP32.bin downgrade via web interface on an ESP32 then upgrade to WLED_0.14.3_ESP32.bin and WLED_0.14.2_ESP32.bin is no problem from WLED_0.14.2_ESP32.bin to WLED_0.14.4_ESP32.bin is no problem. Update WLED_0.15.0_ESP32.bin via the web interface does not work.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.15.0_ESP32.bin

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DedeHai** [comment]
most likely an incompatible file system. how did you install WLED originall? official web installer or using tasmota or home-assistant?

**Comment by PLCHome** [comment]
I downloaded all the files here  https://github.com/Aircoookie/WLED/releases/tag/v0.15.0. Everything works up to 14.4, everything up to 15.0 doesn't work, including beta and rc.

**Comment by softhack007** [comment]
@PLCHome how did you install your first WLED (initially = before OTA update? 

Did you use https://install.wled.me, https://wled-install.github.io/, or a different installation method?
