### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by bitterdog** [Aircoookie/WLED#448]
Is there a guide to set up a timer? Id like the leds to come on at XXX and stay on till XXX or Stay on XX number of minutes.

Thanks. Love the project.

**Comment by raoulteeuwen** [comment]
Please have a look at https://github.com/Aircoookie/WLED/issues/278#issuecomment-546183748 and https://github.com/Aircoookie/WLED/issues/52#issuecomment-430703080 .

**Comment by bitterdog** [comment]
Thanks thats perfect
