### ISSUE TITLE
 Can't sync LED strips in same network together

### ISSUE THREAD

**Issue by tihoangyeudau** [Aircoookie/WLED#463]
When I press the sync button of the led strip has ip: 192.168.0.100, then select an effect, the remaining led strip has ip: 192.168.0.102 just blinks and turns off without changing the effect according to main led.

i try to change numled of all led strips to same 300 pixels but not work

(d1 mini, 921600, 80mhz, 1M, v2 HB, Easer flash all content, 300 pixels)

**Comment by Aircoookie** [comment]
Hi and thanks for reporting!
That's a very strange issue! Please first check if all these checkboxes are enabled in Sync settings :)
![sync](https://user-images.githubusercontent.com/21045690/70869184-8bd18980-1f88-11ea-8580-3082b3ea0b97.JPG)

You can also try compilinh with lwip 1.4 HB, that's what I use, maybe it helps!

**Comment by tihoangyeudau** [comment]
It works. Thank you!
