### ISSUE TITLE
Change nightlight length

### ISSUE THREAD

**Issue by r3m0dul8** [Aircoookie/WLED#467]
Have I missed it somewhere? Looking for the timer that you can set how long the night light goes on for?

Thanks (Also, love this update - nice look you've done to the UI)

**Comment by Aircoookie** [comment]
Hi!
Thank you, I am glad you like the new update!
You can set the length in LED settings -> Timed Light -> Default Duration :)

**Comment by r3m0dul8** [comment]
Love it! This makes it so much easier when setting a night light now - again keep up the great work you seamlessly pump out!

Looking forward to the next update!

Dave
