### ISSUE TITLE
0.8.6 User code

### ISSUE THREAD

**Issue by mehranviva** [Aircoookie/WLED#473]
Hi thanks for your efforts
How can I add an effect to the program and that there is a function that by changing its parameters I can turn off the current effect and execute my own effect and then restore it again.
Thanks a lot

**Comment by Aircoookie** [comment]
Hi!
Take a look at `FX.h` and `FX.cpp`, that may give you an idea how you can add effects :)
What kind of effect do you have in mind?
You can save/restore effects with the preset function.

Happy holidays :)
