### ISSUE TITLE
0.9.0B1 after some days working stop

### ISSUE THREAD

**Issue by pepeEL** [Aircoookie/WLED#476]
Hi
I have flashed my nodeMCU v3 by this firmware WLED 0.9.0b1 
For some days all works ok. But today i see that WLED no working. Led on ESP8266 no light. Restart nothing change. After reflash still working ok but i must configure all from begining.

**Comment by pepeEL** [comment]
Any solution.... Maybe new version? :)

**Comment by sr1sws** [comment]
I've had 0.9.0 running on a NodeMCU for days without issues. I suspect you have a hardware issue. Do you have an alternate device to try it on?

**Comment by pepeEL** [comment]
Nów i reflashed the same and again test. When get problem i test on other device.

**Comment by Aircoookie** [comment]
@pepeEL is it still working?
