### ISSUE TITLE
changing color and blinking leds..

### ISSUE THREAD

**Issue by wchpikus** [Aircoookie/WLED#477]
Hi
First, great work!
I have some question and propose to add.

First, some effect courses blinging leds (it look like to less steps, what changing colors..
I have 300 leds and it is visable on all strip.

Second..on web and apk, 16 slots is a litle to low..
Better will be checkbox on all effects and you can add effect what you want to display ( one function similar like now slots,with time display).
Could you add come gradiends?

Great work!

**Comment by Aircoookie** [comment]
Hi!
Thank you and sorry for the late response!
What version are you using? If you have segments, make sure they don't overlap!
If there is still flickering, you might have to use a levelshifter.

Also thanks for the suggestions! That is all already planned :)
