### ISSUE TITLE
Add DPP protocol (lightweight E1.31 alternative)

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#478]
http://www.3waylabs.com/ddp/

**Comment by Aircoookie** [comment]
xLights ZCCP also seems great

**Comment by MrPaulAR** [comment]
Based on what I see daily in the zoom room zcpp doesn't seem to be getting much use but DDP use is growing.  The main driver for this is the only controller that supports zcpp is Falcon stuff and Kulp has already stated that he won't be adding it to FPP (or his controllers).  Sure someone else may contribute the code.

Hopefully you'll find some time to work on DDP.

**Comment by tihoangyeudau** [comment]
Nice
