### ISSUE TITLE
Software Flashing Guide (german)

### ISSUE THREAD

**Issue by Mazdaracer121** [Aircoookie/WLED#48]
Hallo. gibt es hier jemanden der mir das flashen auf den ESP8266 erklären könnte?

**Comment by Aircoookie** [comment]
Gerne, das ist eigentlich ganz einfach.

Hier ist eine Step-by-step-Anleitung :)
- [Arduino IDE](https://www.arduino.cc/en/Main/Software) (neueste Version) runterladen
- Im Menü "File -> Preferences" unter "Additional Board Manager URLs" folgendes einfügen: 
  `http://arduino.esp8266.com/stable/package_esp8266com_index.json`
Dies installiert die Software und Arduino-Libraries für den ESP8266.
- Dann WLED runterladen (in Github grünen Button mit "Clone or download" -> download ZIP)
- In der extrahierten ZIP "wled00.ino" mit Arduino öffnen
- Im Menü "Tools -> Boards" den "NodeMCU 1.0 (ESP-12E Module)" auswählen. Dieser funktioniert für die meisten Entwicklerboards. Wenn nicht, einfach dein Board in der Liste auswählen.
- Links oben den Pfeil (Upload) zum Flashen klicken

Wenn du auf irgendwelche Probleme beim Flashen oder dem Gebrauch der Software stößt, melde dich gerne nochmal :)

Viel Spaß!

**Comment by Mazdaracer121** [comment]
Wunderbar, hat 1a geklappt. Super Arbeit die du da geleistet hast 👌 Vielen Dank dafür
