### ISSUE TITLE
ASUS RT-AC3100 router WLED connection problems

### ISSUE THREAD

**Issue by rfordhamjr** [Aircoookie/WLED#480]
I just started working with wled last week. In this time, I have had a lot to problems. Mainly being able to connect thought the UI and syncing. I flashed a number of .bins, tried 2 other nodemcus, reset, router changes, password, etc. I was about to give up when grabbed a 10 year old netgear router and set it up all by it self with nothing more then the router, an old S6 phone, and two NodeMcus. Since doing this. I have had Zero problems. My main router is an ASUS RT-AC3100. Has anyone come across anything similar?

**Comment by sansillusion** [comment]
I have an SR905ac OpenWRT router and when I connect any esp32 or esp8266 I
get disconnections and after a short while the whole 2.4Ghz band crashes on
my router until I reboot the router. What makes it bad is that it's one of
the internet service providers supplied router of my region, so if I build
something as a gift, it could haunt me for a while ! I would love to find a
solution. But my problem is not only with WLED but any sketch that uses
wifi.

Le mar. 17 déc. 2019 9 h 59 p.m., rfordhamjr <notifications@github.com> a
écrit :
