### ISSUE TITLE
Got an WS2812 RGB Strip from Ebay but Green and Blue are Reversed...

### ISSUE THREAD

**Issue by Mazdaracer121** [Aircoookie/WLED#49]
The colours Green and Blue are reversed on this strip. How can i fix that?

**Comment by Aircoookie** [comment]
Hi! That is an easy fix luckily! See https://github.com/Aircoookie/WLED/issues/14#issuecomment-383368208

Hope you enjoy the software and feel free to respond if you run into any other issue :)

**Comment by Aircoookie** [comment]
Assuming you got it to work. If there is any issue or you have a question, absolutely feel free to re-open the issue!
