### ISSUE TITLE
0.8.6 FX 2nd Color issue

### ISSUE THREAD

**Issue by jonesjordan19** [Aircoookie/WLED#490]
Anytime I toggle to change the fx 2nd color my device goes unresponsive. I only have control over primary color. Once in a while I can adjust 2nd color. Seems that the device isn’t saving my request on 2nd color. As soon as I try to make an adjustment in 2nd color mode device doesn’t work.

**Comment by Aircoookie** [comment]
Hi, that is very strange indeed... Never heard of issues with the secondary color before. Did you already try 0.9.0? Maybe it fixes it for you!

Anyways, happy holidays :)

**Comment by jonesjordan19** [comment]
Update fixed the issue! Thanks for everything!
