### ISSUE TITLE
Holiday reduced communication notice 🎄🕯️

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#497]
Hi everyone!

Just wanted to let you know that I'll be taking a few week's break over the holidays!

Knowing that I can't help myself, additions to WLED will probably still be made, but please be aware that I might miss your messages or take a long time to reply to them until about January 6th.

Have a merry Christmas and a great start into the new decade! 🎄🕯️🎆

Christian

**Comment by bline79** [comment]
Thanks for all your hard work! Enjoy your time with family and friends :)

**Comment by sansillusion** [comment]
Merry Christmas and Happy New year !

Le ven. 20 déc. 2019 11 h 39 p.m., bline79 <notifications@github.com> a
écrit :

**Comment by timdonovanuk** [comment]
My Christmas tree will look amazing this year and its all down to your hard work! Thank you so much :) <3

**Comment by sr1sws** [comment]
Merry Christmas!

**Comment by Mariu86** [comment]
Merry Christmas and Happy New Year Aircoookie! Happy holidays everyone!

**Comment by dorinik** [comment]
Thanks for your work Aircoookie!
Thank you for making our winter holidays much more beautiful and colorful!
A much richer Christmas and New Year with your loved ones!
Happy holidays everyone!

**Comment by StefanRu1** [comment]
Thank you so much!
Enjoy your holidays and have a Merry Christmas and a Happy New year !

**Comment by sujitrp** [comment]
Merry Christmas and a Happy New year ! Enjoy
