### ISSUE TITLE
UserMod and publishMqtt()

### ISSUE THREAD

**Issue by Datulipan** [Aircoookie/WLED#503]
Can anyone give me some guidance on how to use the publishMqtt() function?

I am using "wled06_usermod.ino" to include PIR motion detection to my dev board. I would like to send "motion_detected" or "motion_standby" via MQTT when either state is true.

Please see my code below.

`//Use userVar0 and userVar1 (API calls &U0=,&U1=, uint16_t)

/**************************** PIR SENSOR DEFINITIONS *******************************************/

#define PIR_MOTION_PIN1 D1  // pin the 1st PIR Sensor is connected to.  If not using the sensor, leave it as it is
#define PIR_MOTION_PIN2 D2  // pin the 2nd PIR Sensor is connected to.  If not using the sensor, leave it as it is

int pirValue1;
int pirValue2;
int pirValue;
int pirStatus;
String motionStatus;

//gets called once at boot. Do all initialization that doesn't depend on network here
void userSetup()
{
  Serial.begin(115200);
  pinMode(PIR_MOTION_PIN1, INPUT);
  pinMode(PIR_MOTION_PIN2, INPUT);
}

//gets called every time WiFi is (re-)connected. Initialize own network interfaces here
void userConnected()
{
  
}

//loop. You can use "if (WLED_CONNECTED)" to check for successful connection
void userLoop()
{
//PIR CODE
  pirValue1 = digitalRead(PIR_MOTION_PIN1); //read state of the
  pirValue2 = digitalRead(PIR_MOTION_PIN2); //read state of the
//  delay(100);
  if (pirValue1 == HIGH) {
    pirValue = HIGH;
  }
  else if (pirValue2 == HIGH) {
    pirValue = HIGH;
  }
  else {
    pirValue = LOW;
  }
  if (pirValue == HIGH && pirStatus != 1){
    motionStatus = "motion_detected";
    pirStatus = 1;
    Serial.println("PIR Value is HIGH");
//    publishMqtt();
  }
  else if (pirValue == LOW && pirStatus != 2){
    motionStatus = "standby";
    pirStatus = 2;
    Serial.println("PIR Value is LOW");
//    publishMqtt();
  }
}`

**Comment by Def3nder** [comment]
Hi @Datulipan ,
have a look at the usermod “ QuinLED_Dig_Uno_Temp_MQTT “.

The topic must be created and used in the publish function:

> char subuf[38];
>       strcpy(subuf, mqttDeviceTopic);
>       strcat(subuf, "/Motion");
>       mqtt->publish(subuf, 0, true, String(motionStatus).c_str());
