### ISSUE TITLE
(Circular) LED matrix effects support

### ISSUE THREAD

**Issue by martijnvdwoude** [Aircoookie/WLED#505]
What would it take to develop support for circular LED rings effects? Is this something that WLED allows for?

This is the kind I'm talking about:
https://www.pcboard.ca/neopixel-ring

I'm specifically interested in doing effects like in this video:
https://youtu.be/nubyADJ7BFQ

**Comment by sr1sws** [comment]
Disclaimer: WLED noob here.

I would think that you might do something like this with segments in 0.9.0_b1. 

Others may weigh in with different opinions. :) 

Steve

**Comment by martijnvdwoude** [comment]
Just after opening this I installed 0.9.0-b1 and noticed the segments functionality! It seems like at least a big step in the direction to do something like this. I'll try to play around with it!

**Comment by sr1sws** [comment]
If you set something up using segments, be aware that the full segment config can only be saved in preset #16. Just a heads up so hopefully you can avoid some confusion and frustration. ;)

Steve

**Comment by Aircoookie** [comment]
I agree, segments are a good way to make this work. In the video they appear to have just connected the rings in parallel since they always run the same effect. The same could be done with WLED, just set the LED count to that of the largest ring.

**Comment by yusufsulaiman** [comment]
hi. this is my led matrix ws2812b with pride 2015 effect. it is coool. thanks Aircoookie
https://www.youtube.com/watch?v=nGESMWByWhQ&t=39s
