### ISSUE TITLE
0.9.0b1 JSON errors

### ISSUE THREAD

**Issue by pepeEL** [Aircoookie/WLED#512]
Hi
First i write WLED on my nodeMCU and after some days stop working but can not connect by IP.
Again flash nodeMCU by other new device. This also works some days and not GUI by IP open but function like POWE ON and other not working. Configuration by GUI works ok. Bu i can not power on and control my leds. Looks what error show... IT is two of more errors,
![1](https://user-images.githubusercontent.com/16692223/71401663-d4dda980-262a-11ea-890b-96b24396320e.jpg)

![2](https://user-images.githubusercontent.com/16692223/71401669-d7d89a00-262a-11ea-8567-84cd57d3f3be.jpg)

**Comment by pepeEL** [comment]
![3](https://user-images.githubusercontent.com/16692223/71401791-2f770580-262b-11ea-9f26-1232b3539107.jpg)

**Comment by Aircoookie** [comment]
Hi, sorry for the issues!
They should already be fixed in source, also see https://github.com/Aircoookie/WLED/issues/453
Releasing a new binary in a few days :)
