### ISSUE TITLE
Connection on apk

### ISSUE THREAD

**Issue by wchpikus** [Aircoookie/WLED#515]
It works all, but i have connection problem.
Afrer refresh all submit settings are correct.

On off works, brightness also, only save to socket no.
![Screenshot_20191224-220834](https://user-images.githubusercontent.com/3776183/71425422-d6e05080-269c-11ea-8927-747260bd2829.jpg)

**Comment by Aircoookie** [comment]
Hi,
thank you for reporting!
I already fixed this issue in source and will release a new binary soon :)
See: https://github.com/Aircoookie/WLED/issues/453
