### ISSUE TITLE
Support for TM1814 RGBW leds

### ISSUE THREAD

**Issue by ryanjjennings** [Aircoookie/WLED#518]
I have some TM1814 leds I am looking for a way to control.  Any chance it will be added to WLED?

This was about the only info I could find on it.
https://forum.arduino.cc/index.php?topic=631680.0

Thanks for the help,
Ryan

**Comment by Aircoookie** [comment]
Hi Ryan!
The easiest way to get them supported would be to ask the Neopixelbus creator Makuna if he can support them. He made the excellent library WLED uses for driving the LEDs!
I'd do it, but I just opened an issue with him to support WS2801 already.

Have a good start into the new decade!

**Comment by Aircoookie** [comment]
Seems like this could be happening soon!
https://github.com/Makuna/NeoPixelBus/issues/325

**Comment by ryanjjennings** [comment]
Just checking in to see if the Neopixel changes made it into WLED?

**Comment by Aircoookie** [comment]
They hadn't yet, I just added the define to be able to easily select TM1814 in WLED!
