### ISSUE TITLE
Add option to show pass WiFi

### ISSUE THREAD

**Issue by ghost** [Aircoookie/WLED#519]
Hi
Good option will be add to setup WiFi checkbox to show password wifi. This is good option and sometimes need.

**Comment by pepeEL** [comment]
Is any chance to add this feature request ?

**Comment by Aircoookie** [comment]
Hi,
while I agree that it would be convenient sometimes, it is quite the security risk to transmit the WiFi password in plain text every time the settings are opened.

I will think about it, but I don't think that it is justifiable unless HTTPS and a user login (similar to what you suggested in #520) are added.

**Comment by blazoncek** [comment]
Closing due to insecure nature of exposing passwords over HTTP.
No excuse should be good enough for exposing passwords IMO, even over HTTPS connections.
