### ISSUE TITLE
Add secure by password

### ISSUE THREAD

**Issue by pepeEL** [Aircoookie/WLED#520]
Good option will be add option to secure access to configuration by password. This will be very need.

**Comment by pepeEL** [comment]
Is any chance to add this Feature Request ?

**Comment by Aircoookie** [comment]
Hi!
For wifi and security settings, this is already supported using the "OTA lock" password in security settings. This will block updates and optionally access to the wifi settings. I might consider adding password support to the entire UI or the entire settings.
This has already been suggested here, so I'm closing this issue: https://github.com/Aircoookie/WLED/issues/308

**Comment by pepsonEL** [comment]
Hi
Is any news about add option to security panel UI ?

**Comment by GeneArnold** [comment]
I just wanted to add my support for password protection. I have two daughters that will be playing around with each others night lights if I can't password protect each one. I really would be very helpful. Thank you very much!
