### ISSUE TITLE
Set color brightness through http request?

### ISSUE THREAD

**Issue by avraham** [Aircoookie/WLED#525]
Thanks for this software. I love it

I followed the wiki steps and tried sending the request myipaddress/win&A=255, which seems to work for the 'master brightness' but not for the color brightness.

I include a picture to explain myself better

<img width="876" alt="Screen Shot 2019-12-27 at 10 23 18 PM" src="https://user-images.githubusercontent.com/2100103/71539878-ead3be80-28f7-11ea-9191-3cceb2a69b1e.png">
Thanks

**Comment by Mariu86** [comment]
For the color you need to send her colors like A=255&R=60&G=127&B=80.

**Comment by avraham** [comment]
Thanks for the help.
I'm actually sending an hex value and it picks the right color from the wheel color picker, but the bar i pointed out with the arrow it always reset to half.

Is there a parameter for that?

These are my parameters: CL=H00538C&A=255

**Comment by Aircoookie** [comment]
Hi!
The bar sends the brightness of the RGB color! That means you modify it by sending different RGB values as @Mariu86 pointed out. `CL=H00538C` is about half brightness, so that is correct. You can try `CL=H0097FF` for example, that is the same color, but using full RGB brightness.

**Comment by avraham** [comment]
Got it. :)
Thank you so much
