### ISSUE TITLE
Presets don't save correctly with new Tertiary color option

### ISSUE THREAD

**Issue by jstephenson69** [Aircoookie/WLED#528]
With new third color if I create a setup with TwinkleFox and three colors and then save it to a preset. When I recall the preset it does not reload with the original settings. It appears to only recall 2 colors and not all three.

**Comment by Aircoookie** [comment]
You are correct, I had missed that! It is already supported in source and there should be a new binary coming this decade (so in about 3 days)
See https://github.com/Aircoookie/WLED/issues/509 :)
