### ISSUE TITLE
Using a Sound Sensor?

### ISSUE THREAD

**Issue by bendobos** [Aircoookie/WLED#53]
Since this project uses W2812FX, which has support for sound sensors, I was thinking of using one. How would I go about doing that? 

I don’t know if this is at all possible but the ability to turn it on and off would also be amazing.

**Comment by bendobos** [comment]
“Clap on/off” is a really cool idea! The sensor I ordered is called KY-037.

Thanks for the tip for the sound visualization but it is a bit overkill for me.
Am 5. Okt. 2018, 12:22 +0200 schrieb Aircoookie <notifications@github.com>:

**Comment by Lazerjules** [comment]
Hi Aircoookie

As many have said, awesome work! This really is a great project. 
I wanted to +1 on bendobos suggestion of some audio interfacing, I would really like to be able to use a microphone connected to one of the analogue inputs and to be able to select some patterns which would produce a VU meter effect, I agree that many of the effects currently wouldn't fit with amplitude based progression. 
I have used [this](https://www.hackster.io/wannaduino/vu-meter-on-steroids-arduino-nano-and-neopixel-ws2812b-7f78e1) project on hackster which is great, perhaps if you feel it's within the scope of your project some sound triggered VU effects would be a nice inclusion? 
To be able to run your project as it stands but with these added would I think be very useful.
