### ISSUE TITLE
wifi_set_phy_mode(WIFI_PHY_MODE_N);

### ISSUE THREAD

**Issue by dzikus** [Aircoookie/WLED#531]
Please add “wifi_set_phy_mode(WIFI_PHY_MODE_N);”. This will give possibility to use WLED with new routers/ap.

**Comment by Aircoookie** [comment]
Could consider this! Have you tried this or is there other evidence that it might solve issues?
Phy mode B could also be interesting as an option as it may increase range (G is in-between and the default)

**Comment by dzikus** [comment]
I’m using openwrt with mwlwifi drivers. After connecting WLED without wifi_set_phy_mode(WIFI_PHY_MODE_N); my 2.4 is completely broken. There is many issues on github related to this https://forum.openwrt.org/t/mwlwifi-and-esp-devices-update-wrt32x/34156/5 for example. I’m using many esp devices in my home (esphome, espeasy, shelly), only WLED is not using N.

**Comment by pety3bi** [comment]
Possibly it would be great to see this configurable from webUI
