### ISSUE TITLE
Bin file link

### ISSUE THREAD

**Issue by wchpikus** [Aircoookie/WLED#532]
Is is possible to add last compiled bin (default d4 pin) to apk or www?
It will be easier to flash new version.
Now i have to searching it..

**Comment by Def3nder** [comment]
Hi @wchpikus ,
you can find the .bin files in the releases section.
This is the default distribution channel.

https://github.com/Aircoookie/WLED/releases

**Comment by wchpikus** [comment]
Is it include all changes?
I watching this project about 3 weaks..or i have to compile it myself?

**Comment by Def3nder** [comment]
The master is very close to the 0.9b2, so which changes are you waiting to be included in the .bin ?

**Comment by Aircoookie** [comment]
@Def3nder is correct, you can always download the latest binaries on that page. Yes the version is from 3 weeks ago and there are a few minor changes, so I will release a new version shortly!
