### ISSUE TITLE
E1.31 does not support White channel

### ISSUE THREAD

**Issue by AndrewApi** [Aircoookie/WLED#534]
Hi
Just tested new code for "Fix analog write range" release "WLED 0.9.0-b2 (build 1912291)", works great now full brightness on LED Strip.

I am using RGBWW analogue strip, WLED controls all 4 channels when RGBW is selected, but in E1.31 mode I can only control the 3 RGB channels, I can not get the white channel (CH4) to light at all. Is this a possibility to correct please.

Thank you for all your hard work on this great project.

**Comment by Def3nder** [comment]
Hi @AndrewApi ,

did you try to set the option „ Auto-calculate white channel from RGB: “ in the LED Settings ?
Does this change anything ?

**Comment by AndrewApi** [comment]
Hi Def3nder

Thanks for the reply.
This takes away the White channel fader in GUI, it does not change anything when trying to control the White channel via E1.31.

**Comment by Aircoookie** [comment]
Hi!
Unfortunately, any channels but RGB are not supported in E1.31 mode currently.
The reason for that is that most E1.31 sending software assumes 3 channels (RGB) per LED.
I might consider adding an "E1.31 layout" or similar option, that would allow you to control the white channel via E1.31.

**Comment by pille** [comment]
i'd like to implement E1.31 RGBW modes analog to those introduced with #665.
does it make sense to wait until you figured out emulation in #573?

**Comment by Def3nder** [comment]
Hi @pille, is there any software that can send RGBW via E1.31 ?

**Comment by pille** [comment]
it should be possible to just add another channel for the white value.
i'm using QLC+ with my own fixture definition.

**Comment by Aircoookie** [comment]
DDP now supports white channel, but there is basically no software that supports it (yet)
