### ISSUE TITLE
Issue with same color in 2 tones. 

### ISSUE THREAD

**Issue by rubenzori86** [Aircoookie/WLED#545]
Issue with same color in 2 tones. I have setup on White but i get this. 

![15779987159853684312976966538054](https://user-images.githubusercontent.com/34756089/71692748-1862b100-2dab-11ea-9ed9-324a9b059204.jpg)
![Screenshot_2020-01-02-21-58-55-401_com aircoookie WLED](https://user-images.githubusercontent.com/34756089/71692764-1f89bf00-2dab-11ea-8222-3f7ea4081bea.jpg)

**Comment by Biothefirst** [comment]
I recommend that you don't use white dead center. I have had odd issues with it. 

Also is it a gradual change or drastic like the pic. Ie is the pic doing justice. 
If so you might be having voltage loss along your string. Should not though for how short it is. Or your signal line is got an issue where it changes color. 

Do you have a multi meter or a scope?

Also don't forget to toss a coin to your Witcher.

**Comment by raoulteeuwen** [comment]
what is shown in the Segments-tab?

**Comment by rubenzori86** [comment]
I configured wled on settings according with my power supply and now i think os working better

**Comment by Aircoookie** [comment]
Seems like there were either (unintentionally) two segments as @raoulteeuwen suggested or there is a significant voltage drop at that point in your strip, which could happen with bad connections or solder joints. Glad it is working better now :) Feel free to reopen if the issue happens again.

By the way, I will finally publish a new binary in a few days that will get rid of the pesky success typeError :)
