### ISSUE TITLE
Homenassistant integration disconnects

### ISSUE THREAD

**Issue by rubenzori86** [Aircoookie/WLED#546]
I have beta release and used default ha integration. But light disconnects recurrently every  x time
![Screenshot_2020-01-02-22-02-31-116_io homeassistant companion android](https://user-images.githubusercontent.com/34756089/71693008-ab9be680-2dab-11ea-9981-e85bf1d1dd80.jpg)

**Comment by kabelux** [comment]
Same here. Esp32 is really near my router

**Comment by rubenzori86** [comment]
Finally i decided setup with mqtt... Native integration doesnt work fine

**Comment by Aircoookie** [comment]
Hi!
I believe this is rather a general connectivity issue than specific to the HA integration, since that just interfaces to the JSON API. @rubenzori86 are you using ESP32 as well? And did you compile yourself (if yes, which arduino core and LwiP) or did you use a binary (if yes, which)?

Thank you!

**Comment by rubenzori86** [comment]
Hi, I'm usign Wemos mini D1 and I flashed directly compiled binary.

**Comment by Dreamoffice** [comment]
same here. Wemos D1 mini with the compiled file. it disconnects oftem from home assistant and in the UI i got this message.....
<img width="639" alt="Bildschirmfoto 2020-01-05 um 20 57 40" src="https://user-images.githubusercontent.com/35889916/71785357-ec3f6e00-2ffe-11ea-98d6-5a7e599e1417.png">

**Comment by raoulteeuwen** [comment]
1. @Dreamoffice how do you establish WLED/the Wemos is disconnecting often from HA?
2. And how did you integrate WLED into HA? Via HA > Configuration > Integrations > Add(+) > WLED > enter ip-of-WLED ?

**Comment by Dreamoffice** [comment]
1. i can see it in the state history that it is not available. 
2. yes i did it exactly this way. 
few minutes ago i was playing around with the segments. it was not possible to set up segments. i got this errors in the UI:
<img width="416" alt="Bildschirmfoto 2020-01-05 um 21 34 00" src="https://user-images.githubusercontent.com/35889916/71785862-ffedd300-3004-11ea-8874-447443adf0c9.png">
<img width="225" alt="Bildschirmfoto 2020-01-05 um 21 39 33" src="https://user-images.githubusercontent.com/35889916/71785863-00866980-3005-11ea-9e2a-99532cbc4276.png">

**Comment by Aircoookie** [comment]
@Dreamoffice ah yes, this issue happens when you run out of memory. Unfortunately, requests allocate double the required memory in 0.9.0, which means it happens quite often. Already fixed in source, new release this weekend!

**Comment by Dreamoffice** [comment]
i swaped the system from D1 Mini to nodemcu, it is much more stable, but the police all effect is not working with 816 LEDs it looks more like a sparkle effect.

**Comment by Aircoookie** [comment]
@Dreamoffice could it be that you have more than the default segment? ("Segment 0")
Then on segment would draw over another and interfere with most effects. If you'd like to have multiple Segments, make sure they don't overlap :)

**Comment by mdietinger** [comment]
Had as well huge connectivity issues with WLED and Home Assistant. UI of native WLED app was very slowly loading. Resolved it by changing Wifi channel to 11.
This improved reponsiness dramatically.
You need to check with a WLAN analyser App what works best for you, as well ensure you are not interfering with Zigbee frequencies.

**Comment by rubenzori86** [comment]
Same is working with last updates

**Comment by c-soft** [comment]
I'm seeing the same issue with latest Hassio 0.115 and Wled 0.10.0  (I'm using  D1 mini) :-(
