### ISSUE TITLE
Wled sync with rgb fusion (GigaByte)

### ISSUE THREAD

**Issue by lscosta90br** [Aircoookie/WLED#558]
Hello,

I have a Gigabye card using rgbfusion for pc color control.
I would like to extend the control to the room environment using wled software where they would be synchronized the tapes of every room.
What do you think of this terial any tips or support?

**Comment by Aircoookie** [comment]
Hi,
I do not know about RGBfusion, but they will likely have some sort of API you can use to add lights or at least query the state of existing ones. Then you could write some adapter (for example, using NodeRED running on your PC) to update the WLED lights via one of my APIs!
