### ISSUE TITLE
Home assistant not setting effects to synced devices

### ISSUE THREAD

**Issue by geyles** [Aircoookie/WLED#576]
I can go to the devices IP GUI and set the effect which inturn sets the effect of the others but from home assistant if I set the effect it will only change the one device. If I then select a colour (while the effect is on it will then change all of them). If I change solid colour it does work fine though.

**Comment by Def3nder** [comment]
Hi @geyles , what did you slect in the Sync settings in section **WLED Broadcast** ?
Send notifications on direct change: ☑️ 
Send notifications on button press: ☑️ 
Send Alexa notifications: ☑️ 
Send Philips Hue change notifications: ☑️ 
Send Macro notifications: ☑️ 
Send notifications twice: ☑️

**Comment by geyles** [comment]
I already have all them ticked
![Screenshot_20200109-203623](https://user-images.githubusercontent.com/55559734/72102821-c7f5d100-331f-11ea-8fc2-e6eb754e6bce.png)

**Comment by geyles** [comment]
Also the built in GUI when choosing solid colours it smoothly transitions to the new colour. When using home assistant to change solid colour it instantly changes.

**Comment by geyles** [comment]
Now seems to work in the latest release
