### ISSUE TITLE
Turn Off Status Led of wemos D1 Mini?

### ISSUE THREAD

**Issue by tuffelh** [Aircoookie/WLED#580]
Is there any way to disable the Status Led of the wemos D1 Mini?
When all LEDs are turned Off, this is very bright.

**Comment by raoulteeuwen** [comment]
You mean like https://github.com/Aircoookie/WLED/issues/18 ?

**Comment by Aircoookie** [comment]
Sorry, still no good solution available other than using a different pin or disabling the LED by desoldering/levering off/covering.
