### ISSUE TITLE
Unable to create segments 

### ISSUE THREAD

**Issue by exeljb** [Aircoookie/WLED#590]
Hi, so I feel like I’m not doing something right when trying to make new segments. I set a color and effect with segment 0 checked and change my stop LED. When I tap on Add New Segment, Segment 1 (new) shows up but no checkbox is there nor another Add New Segment button. What am I missing?  This seems like something that should be pretty straightforward. I’ve tried 3 different browsers on my Mac and both safari and wled app on my iPad and iPhones.

**Comment by raoulteeuwen** [comment]
Do you see a check mark in the segment box? What happens when you press that? (for me, that adds another segment ... i agree maybe a + would be clearer compared to a check mark)

**Comment by Def3nder** [comment]
Hi @exeljb , after pressing "add segment" you have to check/update the start/stop LEDs and then press the ✔️ 

After that you get the "add segment" button again and can add more segments.

**Comment by exeljb** [comment]
Ahh the checkmark!  I was clicking the checkbox til i was blue in the face, thanks for your help folks!  I don't know why i didn't think to click the actual checkmark, i feel a bit foolish for not thinking of clicking that little guy.  A plus sign or a next arrow would've been a bit easier, or maybe the checkmark being located at the bottom right of the open segment window would've made it more obvious for blind folks like myself.  Thanks for the help!

**Comment by Def3nder** [comment]
...if all is okay you can close the issue 😄
