### ISSUE TITLE
Can't connect to WiFi with versions 0.9.0-b1 (regression from 0.8.6)

### ISSUE THREAD

**Issue by Uriziel01** [Aircoookie/WLED#592]
My WiFi is quite ordinary **802.11n** - **WPA2-PSK [AES]** protected network with **Netgear r6220** router with the SSID of `Name&Surname_v2` (I'm not sure if the ampersand or underscore could make any difference?).

With version **0.8.6** everything is working perfectly but beta of new 0.9.0 version just fails to connect and fallbacks to AP mode.

Is there any debugging/logging I can do to help you resolve the issue?

For now I just downgraded to the older version which still works just fine but I can just update yet again to make any further tests if required :)

Already tried clearing entire EEPROM, no success.

**Comment by Def3nder** [comment]
Hi @Uriziel01 ,

to "debug" this you would need to compile from source and set the build_flag -D WLED_DEBUG (or search for the "#define WLED_DEBUG" line in wled00.ino and uncomment this line.)
Then you need to have the ESP connected to the serial port e.g. via USB and start the serial monitor. You will see more messages printed to the serial monitor this way.

**Comment by turbouk2312** [comment]
Same issue with me. I see it authenticating on the router, it gets offered an ip address but there's no dhcpack in return. I have the router and another AP to help the signal at the opposite end of the apartment, if I turn this AP off the WiFi of wled works properly. It's like it's half connecting to one and half connecting to the other. Work fine on the previous release

**Comment by harueg** [comment]
Had the same problem. Tried 0.8.6  and connection to home wifi was established, Then  I updated to 0.9.0-b1  with OTA, and now working.

**Comment by mleegwt** [comment]
Same issue here. Applied @harueg's solution successfully.
