### ISSUE TITLE
Feature Request - Roll the Dice | Random Color, Effects, Etc.

### ISSUE THREAD

**Issue by josephdyland** [Aircoookie/WLED#593]
I have a Feature Request I think would be useful, some randomization like a Roll the Dice button and have different and selectable things be randomized.  I Drew and attached a Mock-up ![Mock up](https://user-images.githubusercontent.com/2946074/72381851-ba549880-36dd-11ea-9e0a-64eeaea0bac6.png)
 of what it could look like.

Since it is so difficult to make up ones mind on which effect / colors to use. It would be great to be able to enable randomness on;

Primary Color
Secondary Color
Tertiary Color
Effect
Palette
Speed
Intensity

**Comment by huggy-d1** [comment]
To expand on this excellent concept, I wonder if a subset of all effects / colors could be selected, like checkbox for "All" (original suggestion).   Suppose either a visitor or resident has epilepsy and we want to exclude all strobe effects, and limit speed to sub-seizure rates.

If "All" is unchecked, display effects with a checkbox (or other selector).

If "Favorite" is unchecked for color palette, then all colors.  If it's checked, only allow color randomizing from "Favorites" colors.

As an interim solution, maybe create a new effect with additional properties, named "Random effect", and new color, named "Random color".  When those are selected, we get the effect as if we rolled the dice, but just one time.  Once the dice is rolled (random function called) for each option, that option is now _selected_ as if we manually selected it.

The OP has an intriguing UI perspective where dice are rolled.  WLED presents new effect (and/or new color).  We look at our significant other's expression.  Depending, perhaps we keep rolling the dice, hoping to stumble upon an effect that suits our (or their) mood.  

I think this suggestion can increase WAF!  Probably fun to play with during parties too.

If I were to implement it, I would have Di shown in the UI, and when "roll the dice" button is selected, I would use JS to animate the Di and alter the # of visible pips on the face.  Either that, or find a free Di animation and activate it when the Di are rolled !!

**Comment by sansillusion** [comment]
I support that idea ! That's what I am missing from wled.

Le mer. 15 janv. 2020 1 h 05 p.m., huggy-d1 <notifications@github.com> a
écrit :

**Comment by Aircoookie** [comment]
I like this suggestion! A simple random color selector will in fact be part of the upcoming 0.9.1 version.

Randomizing effects and their parameters really sounds like a fun concept! Excluding some effects from the list or constraining the range of possible values for speed and intensity should also be done, I agree!

**Comment by pniewiadowski** [comment]
Do we have an volunteer to take care of this? I really appreciate the idea!

**Comment by blazoncek** [comment]
It is possible to use "r" as a parameter for "sx", "ix", "pal", "fx" (and others) keys in JSON API allowing for random values to be applied.
https://kno.wled.ge/interfaces/json-api/#contents-of-the-segment-object
