### ISSUE TITLE
PIO ini should contain  "-D DECODE_NEC=true"

### ISSUE THREAD

**Issue by Def3nder** [Aircoookie/WLED#608]
Hi @Aircoookie , 
I see you noticed that the compile_flags branch was merged into the master of the IRremoteESP8266 library :-) 

However, I would suggest to leave at least the NEC support in the PIO ini file since the far most of the "cheap small remotes" are working with the NEC protocol.

Could you pls. re-include the line 
`  -D DECODE_NEC=true  `

?

**Comment by Aircoookie** [comment]
Hi, sure :) Sorry, I was totally expecting this to just be used for NEC brand remotes, and not a requirement for - let's call them - China remotes. Added it back!
