### ISSUE TITLE
Use of interrupts inside wled06_usermod.ino

### ISSUE THREAD

**Issue by huggy-d1** [Aircoookie/WLED#612]
Are we allowed to use interrupts to manage data pins inside usermods?

It sure would be easier to get called on leading and trailing edge of motion inputs rather than detecting leading and trailing edge while polling.  It would also be more efficient and leave more time for the rest of WLED to do its thing.

**Comment by Aircoookie** [comment]
Yes, of course you are! There are just a few ESP8266 specific things to look out for when using interrupts. Firstly, you mustn't use them in async callbacks (that is, any method that was not called from the main loop, but for example the JSON response parsers). `userLoop()` should always be fine. Secondly, they have to be short enough and mustn't use delay() or yield().
But don't worry, you cannot break anything! If you accidentally use interrupts inappropiately, the ESP will just let you know with an exception :)
