### ISSUE TITLE
Multi Button and IR support

### ISSUE THREAD

**Issue by DaveDischord** [Aircoookie/WLED#62]
I don't know if it'd be of any use, but a button library I've come across [TTBOUNCE](https://github.com/TOLDOTECHNIK/TTBOUNCE), allows for some defined button actions/callbacks.

**Comment by Mariu86** [comment]
For me will be a good addition , my wife it's not a smartphone fan and a button whith multi function and ir sensor for a remote control will be the best code for all my ledstrips in my house! Thanks in advance Aircoookie for everything you do whith this !!!

**Comment by Aircoookie** [comment]
Thank you! I'll work on this soon. With macros, you already have the possibility to set different actions for button short/long press, but I want to add double/triple click detection as well as support for more buttons (you will need to add a pullup resistor to the other buttons though since on most ESPs, only gpio0, the current button pin, has a built-in pullup)

I can't work on IR right now since I don't have the required hardware for testing, but I have some IR receivers and remote lying around somewhere. Just need to find them...

**Comment by Mariu86** [comment]
The ir sensor it's a very good addition , I will use it with Alexa + Logitech harmony/ brodlink and I will change not only the brightness and on/off , we can change the color and effects almost anything.

**Comment by raymiec** [comment]
not sure much space you have left, i used a library not long ago to make an ir blaster for the tv, if that can be included it would be pretty straight forward one would think.  

Another solution would be is to have a single ir receiver hooked up to an esp with an api. Means we could control various lights and also other devices across the network.

I might post an example here soon actually i kinda want to make it.

**Comment by raymiec** [comment]
Here's some very basic code that will receive an IR command and call an api, i.e Wled. 
Load the sketch onto an esp, hook up led receiver to D5. You will need to map your remote, just open serial monitor and you can watch incoming commands when you push any button.

I'll finish this off as soon as i soon as i have time but it's a starting point for anyone else who wants to give it a go.

I've mapped a couple of buttons to control brightness and another couple to randomly choose effects.

`#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <IRremoteESP8266.h>
#include <IRrecv.h>
#include <IRutils.h>
#include <WiFiClient.h>
#include <ESP8266HTTPClient.h>
 
const char* ssid = "Theinternet";
const char* password = "password";
const uint16_t rPin = 14;
String cmd;

const uint64_t  btn_1 = 16580863;
const uint64_t  btn_2 = 16613503;
const uint64_t  btn_3 = 16597183;
const uint64_t  btn_4 = 16589023;
const uint64_t  btn_5 = 16621663;
const uint64_t  btn_6 = 16605343;
const uint64_t  btn_7 = 16584943;
const uint64_t  btn_8 = 16617583;
const uint64_t  btn_9 = 16601263;
const uint64_t  btn_0 = 16625743;
const uint64_t  btn_ok = 16623703;
const uint64_t  btn_up = 16615543;
const uint64_t  btn_down = 16619623;
const uint64_t  btn_left = 16591063;
const uint64_t  btn_right = 16607383;
const uint64_t  btn_star = 16593103;
const uint64_t  btn_hash = 16609423;

IRrecv ir_recv(rPin);
decode_results res;
int status = WL_IDLE_STATUS;
WiFiClient client;

void getApi(String cmd) {
  HTTPClient http; 
  String endpoint = "http://192.168.1.155/";
  String command;  
 
  if(cmd == "s"){
    int randNumber = random(0, 75);
       command = "win&FX="+String(randNumber);
    } else if(cmd == "h"){
    int randNumber = random(0, 46);
       command = "win&FP="+String(randNumber);
    } else {  
       command = "win";
    }

  http.begin(endpoint+command);
  int httpCode = http.GET();        
  String payload = http.getString();   
  http.end();

     // change here as we already have the current value at this point.
    if(cmd == "u"){
      String current = midString( payload, "<ac>", "</ac>" );
      int newval = current.toInt()+10;
      http.begin(endpoint+"win&A="+String(newval));
      httpCode = http.GET();         
      http.end();   
    }else if(cmd == "d"){
      String current = midString( payload, "<ac>", "</ac>" );
      int newval = current.toInt()-10;
      http.begin(endpoint+"win&A="+String(newval));
      httpCode = http.GET();          
      http.end();   
  }
  
}

String midString(String str, String start, String finish){
  int locStart = str.indexOf(start);
  if (locStart==-1) return "";
  locStart += start.length();
  int locFinish = str.indexOf(finish, locStart);
  if (locFinish==-1) return "";
  return str.substring(locStart, locFinish);
}

void setup() {
  Serial.begin(115200);
  ir_recv.enableIRIn();
  while (!Serial) 
    delay(50);
   WiFi.begin(ssid, password);
   Serial.println("");
   Serial.print("Connecting");
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
    }
  Serial.println("");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP().toString());
}

void loop() {
  if (ir_recv.decode(&res)) {
      if (res.value == btn_ok) {
        cmd="k";
      } else if(res.value == btn_1){
        cmd="1";
       }else if(res.value == btn_2){
        cmd="2";
       }else if(res.value == btn_3){
        cmd="3";
       }else if(res.value == btn_4){
        cmd="4";
       }else if(res.value == btn_5){
        cmd="5";
       }else if(res.value == btn_6){
        cmd="6";
       }else if(res.value == btn_7){
        cmd="7";
       }else if(res.value == btn_8){
        cmd="8";
       }else if(res.value == btn_9){
        cmd="9";
       }else if(res.value == btn_0){
        cmd="0";
       }else if(res.value == btn_up){
        cmd="u";
       }else if(res.value == btn_down){
        cmd="d";
       }else if(res.value == btn_left){
        cmd="l";
       }else if(res.value == btn_right){
        cmd="r";
       }else if(res.value == btn_star){
        cmd="s";
       }else if(res.value == btn_hash){
        cmd="h";
       } else {
        //code not mapped
        cmd="";
        serialPrintUint64(res.value);
      }
       if(cmd != "")
          getApi(cmd);
        
    ir_recv.resume();
  }
  delay(100);
}`

**Comment by aenertia** [comment]
I got the IR8266Remote library working fine with an esp32 - but obviously needs json/api and web hooks for it to be more than a usemod toy
