### ISSUE TITLE
Support for Evil Genius Lab shield

### ISSUE THREAD

**Issue by r4ptor121** [Aircoookie/WLED#620]
The EVIL GENIUS LABS ESP2866 shield doesn't have the required GPIO2 (D4) pin on the shield.
Is there any way to have a image for another pin such as GPIO12-15 (D5-8)?
Perhaps the option to change the pinout directly from the app would be nice.

**Comment by Def3nder** [comment]
Hi @r4ptor121, yes, this option is already there:

Look at the file `NpbWrapper.h` in line 6:
`#define LEDPIN 2      //strip pin. Any for ESP32, gpio2 or 3 is recommended for ESP8266` 

Just change this to your desired pin an you're done 😄

**Comment by fishbone-git** [comment]
see also discussion #345.
