### ISSUE TITLE
Button wiring D1 Mini and NodeMCU

### ISSUE THREAD

**Issue by ggrant111** [Aircoookie/WLED#622]
First a big shout out to AirCookie and the other developers of this software. I used it for my christmas shows this past month integrating with xlights as well!!

I am trying to add a button to trigger a few macros and tried hooking it up as the first few paragraphs say in the Wiki adding a normally open button to D4 - GPIO0(i belive it says) and the other end to ground. When i did this and enabled the button in the settings and set the short, long and double press and the macros it didn't respond. I was able to change the macros the the HTTP rest api fine from a web browser. I tried searching in the issues to see if someone else had issues and found one that said it needed to be connected to D4 pin and VIN with a pullup resistor. So i am confused now because the D4 pin is supposed to already have a pull-up resistor. Where I am confused is the Wiki says one to the pin and one to ground and someone else said to the pin and the other end to VIN.

I am using D1 mini boards and also Nodemcu devkit1 boards as well.

Can someone help me figure this out?

thank you

**Comment by srg74** [comment]
Hi! You have to use a pull-up resistor 10K from pin to 3.3V and then NO button from pin to ground. I'm using default button pin in my board and it's working just fine.
Best regards

**Comment by ggrant111** [comment]
What do you mean default button? The on board button?

**Comment by srg74** [comment]
Default button to WLED project e.g. GPIO0
Best regards

**Comment by ggrant111** [comment]
Ok thank you

**Comment by ggrant111** [comment]
Just soldered a resistor and button leads. After testing it works as
expected.

Thank you for the clarification.

**Comment by srg74** [comment]
Hi! Np with button :)
Please close this issue if you satisfied. 
Best regards
