### ISSUE TITLE
WLED Aircoookie mit Odroid N2 möglich? 

### ISSUE THREAD

**Issue by Cosmicbase** [Aircoookie/WLED#632]
Hallo, ich habe einen Odroid N2 mit aktuellen CoreElec, Arduino Uno R3, APA102 am laufen. 
Kann ich durch Tausch des Arduino in einen ESP32 meine LEDs ins Netzwerk einbinden?
Preislich wäre der Austausch mehr als rentabel. 
Wie schaut es mit dem Hyperion.ng aus wo ich momentan nutze?

**Comment by Aircoookie** [comment]
Hi und willkommen!
Wie sieht denn das Setup aus? Wenn der Arduino Uno nur die Daten von Hyperion (ich nehme an dies läuft auf dem Odroid) via USB entgegenimmt, kann der WLED ESP32 dies auch (über das UDP Typ 0 Protokoll, also kabellos).

**Comment by Def3nder** [comment]
Hi @Cosmicbase, hyperion.ng spricht den Arduino als Adalight über USB an, oder ?
Wenn ja, dann kannst Du den Arduino durch einen ESP8266 oder einen ESP32 austauschen 😄

**Comment by Cosmicbase** [comment]
> Hi @Cosmicbase, hyperion.ng spricht den Arduino als Adalight über USB an, oder ?
> Wenn ja, dann kannst Du den Arduino durch einen ESP8266 oder einen ESP32 austauschen

OK danke, Ja mein Arduino ist via USB am Odroid N2 und wir als Adalight angesprochen. 

Gibt es eine klare Empfehlung in Sachen Stabilität und momentanen Standpunkt?
ESP32 oder ESP8266?

**Comment by Cosmicbase** [comment]
> Hi und willkommen!
> Wie sieht denn das Setup aus? Wenn der Arduino Uno nur die Daten von Hyperion (ich nehme an dies läuft auf dem Odroid) via USB entgegenimmt, kann der WLED ESP32 dies auch (über das UDP Typ 0 Protokoll, also kabellos).

Ja soweit hast du recht. Ich gehe davon aus das Ausgabe in dem Scroll Down "Steuerungstyp" ausgewählt wird siehe Bild
![Screenshot_20200127_173150_com android chrome](https://user-images.githubusercontent.com/31271212/73193690-44afea00-412b-11ea-8a9b-eb17fd6e3e39.jpg)
