### ISSUE TITLE
DMX support

### ISSUE THREAD

**Issue by pille** [Aircoookie/WLED#635]
it would be nice to see DMX support (over Art-Net or E1.13).
that way the WLED becomes a fixture and its LEDs could be remotely controlled via standardized controllers and integrated into complex scenes.
it's possible to implement different modes, with a different complexity/amount of channels
the most basic one may treat all LEDs the same, exporting four channels (brightness, R, G, B).
a more complex one would export all LEDs individually (master brightness, R, G, B, R, G, B, ...).
another channel could just trigger effects locally.

**Comment by sansillusion** [comment]
E1.31 is already supported just have to activate it in sync settings.

Le lun. 27 janv. 2020 9 h 28 a.m., pille <notifications@github.com> a
écrit :

**Comment by sansillusion** [comment]
The current e1.31 support gives each led 3 channel (R.G.B.).

Le lun. 27 janv. 2020 9 h 28 a.m., pille <notifications@github.com> a
écrit :

**Comment by Aircoookie** [comment]
Thank you for the suggestion!
E1.31 is already supported on a per-pixel RGB basis as @sansillusion said!
Art-Net support has already been requested: https://github.com/Aircoookie/WLED/issues/417

**Comment by pille** [comment]
thanks @sansillusion for the hint. i successfully played with the current implementation and am planning to extend support for different modes.

**Comment by pille** [comment]
that would require adding a new config parameter, which seems rather complex as parameters seem to be relevant in many places. is there some kind of best practices? e.g. this would effect EEPROM layout.

**Comment by pille** [comment]
@Aircoookie, can you please help me out with the info requested above?

**Comment by pille** [comment]
announced DMX-modes were implemented in #665.
