### ISSUE TITLE
Use black as base color when transitioning from off 

### ISSUE THREAD

**Issue by chaptergy** [Aircoookie/WLED#651]
Currently, when I set my leds to blue, switch them off, and then switch them back on to red with a transition, it starts off with the last blue color while fading on, and then slowly fading to the new color. However I can't see a use case where we'd want to have an old color which when switching on the lights with a transition. Wouldn't it make more sense to transition them from black (all 0) to this color we want?

**Comment by Aircoookie** [comment]
Thank you for your suggestion, I believe it would indeed make sense to omit the color transition if we are turning on :)
