### ISSUE TITLE
Sync Settings > MQTT Port required, although disabled

### ISSUE THREAD

**Issue by pille** [Aircoookie/WLED#654]
minor inconvenience: i have disabled MQTT in sync settings.
the web form forces me to enter a port.

![Selection_080](https://user-images.githubusercontent.com/736655/73653691-12057480-468a-11ea-851e-d489caf00d5e.png)

**Comment by Aircoookie** [comment]
Thank you :) same as the Hue disabled issue recently. Will publish a fix later today :)
