### ISSUE TITLE
JSON API command crashes ESP

### ISSUE THREAD

**Issue by Aircoookie** [Aircoookie/WLED#661]
The (illegal) JSON API call

```
{"seg":{"1":{"fx":2}}}
```

seems to crash the ESP (reported by @DutchmanNL on discord)

**Comment by Def3nder** [comment]
Hi Aircoookie, 
sending the (wrong) above string **does not crash an ESP32 nor does it crash an ESP8266**.
I tried both: sending it to `/json/state` and to `/json`.

And sending 
```
{
    "bri": 50,
    "seg": [
        {
            "id": 0,
            "fx": 2
        }
    ]
}
```
to `/json/state` does **work as expected** on both ESP32 and ESP8266.

**Comment by DutchmanNL** [comment]
Hmm interesting, did you try just ones or multiple times after each other ?

I saw this behavior by building an integration by JSON api and my system crashed the esp definitely  but not instand at the first one.

Using latest version build from git

**Comment by Aircoookie** [comment]
Indeed I cannot reproduce the crash either, even with sending the request multiple times in a row.
@DutchmanNL maybe it was related to the communication rate (although I don't believe you send more than 10 requests a second, which is about the max. an ESP8266 running WLED can handle)
or some headers being sent, not the request itself.

**Comment by DutchmanNL** [comment]
I can't reproduce it either only by indeed spamming the devices.
I keep it o bad coding on my side but can't verify as already improved :/
