### ISSUE TITLE
expose debugging via webUI

### ISSUE THREAD

**Issue by pille** [Aircoookie/WLED#666]
it would be useful to be able to see DEBUG messages via webUI.

**Comment by TravisDean** [comment]
Would it be enough to just print them to the console, enabled with a UI setting?

**Comment by pille** [comment]
no. the goal is debugging a deployed device.

**Comment by flloyd-aa7bq** [comment]
Much easier to use /json/info for this.  It’s always available and doesn’t muck with the UI.

**Comment by blazoncek** [comment]
Network debug printer is implemented in 0.14.
