### ISSUE TITLE
broken layout in Android 7

### ISSUE THREAD

**Issue by pille** [Aircoookie/WLED#668]
the first effect (solid) isn't visible.
the parameter sliders won't work.
![Screenshot_2020-02-08_21-28-46](https://user-images.githubusercontent.com/736655/74091692-69587a00-4aba-11ea-8945-eefb0a3341d9.png)

anyways: the new design is really helpful for understanding/using it.

**Comment by Aircoookie** [comment]
Thank you for the feedback! Which phone model and browser is this?

**Comment by pille** [comment]
chrome-60 on some cheap <6" nobrand

**Comment by pille** [comment]
this is still an issue.

**Comment by Aircoookie** [comment]
Please reopen if still an issue in 0.13+

**Comment by pille** [comment]
the issue still exists. additionally the colorwheel is only grey (circular gradient).
