### ISSUE TITLE
Can I move my WLED's to a seperate VLAN?

### ISSUE THREAD

**Issue by fribse** [Aircoookie/WLED#677]
Hi Aircookie

I've started the motion of my NOT's and IOT's to seperate VLAN's.
It works well for most items, but I'm a bit unsure about WLED, and before I just cut off the branch I'm sitting on, I wanted to check in with you :-)
I have it integrated to HA, but as I understand the integration, the HA connects to WLED's API, and therefore it doesn't need any ports open from the NOT's VLAN to the LAN?
But how about the WLED discovery, both from the app and the HA, is that just done with mDNS, or how is that accomplished? If it's 'just' mDNS, then I can just move them, because that is already working for my esphome devices.

**Comment by fribse** [comment]
Ok, I tried doing this morning, so far everything is good, I removed them from HA, and put them back in with the new IP's. I couldn't autodiscover them though, but the app finds them without problems, so I guess it's working 😄

**Comment by Aircoookie** [comment]
Glad it's working! Yep, mDNS and normal HTTP GET/POST is everything WLED needs to function, so it should work in a VLAN if devices in it are accessible from your personal device VLAN.

**Comment by mcaulifn** [comment]
@fribse I know this is old. Wondering if you can post how you got this working? The wled app will not connect despite having http open.

**Comment by netmindz** [comment]
If you split your network into different networks, you can't auto discover devices on your network any more as you are on a different network. If you want to share dates between your networks you might want to configure your router to pass mDNS between your networks, but then you are really just undermining having network segregation
