### ISSUE TITLE
FR: Broadcast button presses via mqtt

### ISSUE THREAD

**Issue by chibbert** [Aircoookie/WLED#685]
I've had a quick play with the button support in wled which is great.

I'd like to make use of the button press within my openhab system, so broadcasting button presses, long and short via mqtt would make sense to me.

I'm prepared to have a go at this feature if anyone else thinks this is useful.

**Comment by Aircoookie** [comment]
Hi, if you want the button to control the WLED LEDs as well, you can make macros in "Time & Macro settings" for short, long and optionally double press. Then you would just check in openhab for the value (for example a specific color set in the macro) and if it is the same, you use that to trigger other stuff. To have more freedom, probably the easiest way would be to publish the value of userVar0 to MQTT, call publishMqtt() after each applied macro and setting the macros to `U0=1`, `U0=2` and `U0=3` for each button press type respectively.
