### ISSUE TITLE
Every second LED is dark

### ISSUE THREAD

**Issue by palengh** [Aircoookie/WLED#689]
My string has every second LED dark when “Disable repeating N LEDs:” is set to “0”.
![E783F334-C050-4216-AA94-427E54280E42](https://user-images.githubusercontent.com/12332161/74638608-7df8da00-516c-11ea-9daa-84d7275c0fc5.jpeg)

When set to “1” they’re all dark. Switching to “2” dims out 2 consecutive LEDs

What am I missing out?

version 0.9.0-b1
WS2815b
12V 3.5A supply connected to LEDs

**Comment by palengh** [comment]
Rebooting through the app made no progress. 
After cutting the mains, and switching power back on (NodeMCU) has constant power, all LEDs showed up again.

**Comment by Def3nder** [comment]
Hi @palengh, could you please look on the segments tab, if there is something entered in the field "spacing" ? "normal" would be "0" for spacing.

**Comment by palengh** [comment]
![08E347D7-E2F8-4349-8DB7-FB78231A9815](https://user-images.githubusercontent.com/12332161/74833717-50519380-531a-11ea-8acb-2de997e30087.jpeg)

**Comment by palengh** [comment]
As mentioned Above; the “Disable repeating N LEDs:” is set to “0”.

**Comment by Def3nder** [comment]
hmmm - I see - the UI for entering the "spacing" value for a segment was just added I think.
So probably there are values in,  but you cannot see the values.

You could either clone the latest master or reset the EEPROM and start over with default values:
```
http://[WLED-IP]/cleareeprom
```

The first would keep the existing values and would suggest to do that 😄

**Comment by palengh** [comment]
What do you mean by “ clone the latest master”?

**Comment by Def3nder** [comment]
sorry - I thought you would have compiled from source 😢 

Which version did you use (for which ESP device)?
Standard PINs ?

...I will compile a binary for you.

**Comment by palengh** [comment]
WLED version 0.9.0-b1
WS2815b
12V 3.5A supply connected to LEDs
Rynning on a NodeMCU.

**Comment by Def3nder** [comment]
Hi @palengh,

her we go: NodeMCU version from the actual master:
[WLED_pre-0.9.1_ESP8266.zip](https://github.com/Aircoookie/WLED/files/4229595/WLED_pre-0.9.1_ESP8266.zip)

...after flashing you will see the spacing in the segements tab:
![image](https://user-images.githubusercontent.com/33399267/74914964-adedea80-53c3-11ea-9b96-908c683c952b.png)

**Comment by palengh** [comment]
Thanks A lot. 
There seems to be an issue with current (not the one you compiled) version. It gets unreachable after 10-50 hours. Power is on and the light switch is turned off. 
Then the NodeMCU is unavailable.

**Comment by palengh** [comment]
After flashing:

![6AC93616-E65D-4F51-81E0-93FCCEE75D8E](https://user-images.githubusercontent.com/12332161/74929171-4348a900-53db-11ea-93ed-de21ffa8d885.jpeg)

**Comment by Def3nder** [comment]
hmmm - looks "normal". Is the "every second LED" effect present with the new binary, too ?

**Comment by palengh** [comment]
The second led issue seems to be fixed in this latest update. 
Thank you!
