### ISSUE TITLE
Built-in LED, I wan to turn it off!

### ISSUE THREAD

**Issue by micmax1** [Aircoookie/WLED#693]
Hi, I have 2 NodeMCU setups and would like to turn off the built-in LED so that when sleeping I don't have to see the LED shining. Is it me or isn't this an option (yet)?

Thnx in advance

**Comment by fishbone-git** [comment]
not an option yet, as there is an issue that conflicts with existing support.  See #18 for further tracking

**Comment by micmax1** [comment]
Thnx I'll keep track there
