### ISSUE TITLE
Tertiary colour fails to sync until other colour is changed

### ISSUE THREAD

**Issue by fishbone-git** [Aircoookie/WLED#695]
Seems to have been somewhat recent, although I cannot recall specifically testing (just can't recall ever noticing it).  Tertiary colour won't sync over udp when changed via the ui.  However, once either the primary or secondary is changed, then the tertiary catches up.

**Comment by Def3nder** [comment]
Hi @fishbone-git, 

did you refresh the UI after the sync (on the target ESP) ?
...I think the UI will not show other colors without getting a "refresh".

**Comment by Aircoookie** [comment]
It actually makes sense that this bug happens. UDP sync is only sent if a value changed.
The tertiary color is the only value that is not checked for changes in the `colorUpdated()` and will thus never trigger a sync packet. I will try and find a way to make the sync work without introducing `colTer` variables just for checking.

**Comment by pille** [comment]
@Aircoookie: when you would introduce `colTer`, i could use that in E1.31 `DMX_EFFECT` mode and add a channel for that. i already planned supporting tertiary color in #665, but using `strip.setColor` was slow, so i left it out.

**Comment by blazoncek** [comment]
Fixed in recent sync changes (full segment sync).
https://github.com/Aircoookie/WLED/pull/2547 and https://github.com/Aircoookie/WLED/pull/2427
Closing.
