### ISSUE TITLE
New version faills to reconnect to wifi if disconnects

### ISSUE THREAD

**Issue by davidcreager** [Aircoookie/WLED#696]
Apologies if this is duplicative.   It is mentioned in other issues.
I have three wled drive strips, two on the latest version(0.9.0-b1) and one on the previous version (0.8.6).   When I reboot my router (ie restart wifi) both WLEDs running the latest version do not reconnect until I power cycle them.   The one running the previous version reconnects fine

**Comment by huggy-d1** [comment]
If you install the latest build for 0.9.0-b1, does it fix the problem?  The devs found / fixed some wifi related issue(s) fairly recently.

**Comment by davidcreager** [comment]
Yikes   it didn't occur to me to try.....I will try now and report back

**Comment by Def3nder** [comment]
Hi @davidcreager, there is not new release yet - which device do you use ?
I can create a suiting binary for you from the current master.

**Comment by davidcreager** [comment]
> Hi @davidcreager, there is not new release yet - which device do you use ?
> I can create a suiting binary for you from the current master.

Oh that is so kind.   I am using esp8266 devices currently flashed with WLED_0.9.0-b1_ESP8266.bin

**Comment by snook** [comment]
There is a large thread regarding wifi connection issues here #644

**Comment by davidcreager** [comment]
> There is a large thread regarding wifi connection/reconnection issues here #644

Yes, I read that, however, I thought it worth flagging the different behavior between versions in a separate issue.   Apologies if it is not helpful.

**Comment by Def3nder** [comment]
Hi @davidcreager, this is from the the current master branch:
[WLED_pre-0.9.1_ESP8266.zip](https://github.com/Aircoookie/WLED/files/4230368/WLED_pre-0.9.1_ESP8266.zip)

**Comment by davidcreager** [comment]
> Hi @davidcreager, this is from the the current master branch:
> WLED_pre-0.9.1_ESP8266.zip

Thank you so much,   I will test this today and provide feedback.

**Comment by davidcreager** [comment]
Ok, so I have installed the pre 0.9.1 onto the two strips that were exhibiting the failure to reconnect.   They appear to be working fine.

Before this, I attempted to set up a test to demonstrate the problem and I 'think' I managed to do this in that I recreated the issue, deployed the new firmware which seemed to fix things.   I am hedging my comments a little as it was not as controlled as I would have liked and ideally I would have proved repeatability.

Anyway, I am going to continue with the new firmware and if I have any problems I will post here.

Thanks again for your help.   Very much appreciated

**Comment by Def3nder** [comment]
@davidcreager, if resolved could you pls. close the issue ? Thx 😸

**Comment by davidcreager** [comment]
One more test and I will -:)   give me a couple of hours!

**Comment by davidcreager** [comment]
YIPPEEE!   A good test and it worked perfectly   You guys are the best   Thanks
