### ISSUE TITLE
Going to Config and Back destroys color wheel

### ISSUE THREAD

**Issue by HugoBalder** [Aircoookie/WLED#712]
Hi all,
when i click in the browser on Config and simply go Back, the Colors in the wheel on the main page are gone.
This seems due to the fact, that the Url changed to http://<ip address>/?
When i remove the /? and reload then the Wheel shows all colors again.

Tested on Safari with IOS 13 on a iphone and an iPad Pro.

Not very tragic as i don‘t use the wheel, but just to let you know.

**Comment by srg74** [comment]
I experienced same issue but if you using Chrome instead of Safari everything is OK. Maybe its Webkit problem on OS X.

**Comment by Aircoookie** [comment]
Hi,
does this happen using the latest version 0.9.1?

**Comment by HugoBalder** [comment]
Hi, yes it does. I installed yesterday the latest 0.9.1 release. Today i tried the IOS App and there it also happens whenever you click on the big Back-Button.

**Comment by srg74** [comment]
It’s only happening in Safari. My guess it’s Apple WebKit glitch.
