### ISSUE TITLE
Chase Glitch: Same as #380?

### ISSUE THREAD

**Issue by tonyn0** [Aircoookie/WLED#718]
On ESP32...

fx 28, sx 59

Glitches (flashes of secondary in primary) for me.

fx 28, sx 76

Is fine.

**Comment by tonyn0** [comment]
Video goodness. https://photos.app.goo.gl/pAecE417JGwXVGXS8

**Comment by Aircoookie** [comment]
Thank you for reporting! This seems to need a fix. Will look into it :)

**Comment by Aircoookie** [comment]
Hi, I believe I just fixed the chase effects :)
Could you give the latest master a try or should I send a binary?

**Comment by tonyn0** [comment]
Thanks. I'll just compile it.

**Comment by tonyn0** [comment]
No revision bump?

**Comment by Aircoookie** [comment]
Good that it's working!
I'll release 0.9.2 soon, but i still need to iron out a few other things like #742 and #734 .
