### ISSUE TITLE
ws2812 + Analog White + separate global brightness + MQTT control

### ISSUE THREAD

**Issue by marsic-84** [Aircoookie/WLED#723]
I want to use one RGB ws2812 Led Strip and one White Analog Strip, but when i set RGB type in LED setup, the white strip brightness control not available. And when i set RGBW type in LED setup, ws2812 Led Strip becomes uncontrollable and shows strange colors (because it is not sk6812). And i need the ability to control the brightness separately, ideally through MQTT. 
Is it all possible?

**Comment by huggy-d1** [comment]
That sounds like two separate WLED µcontrollers, or creating a custom usermod to handle the analog white strip in addition to the RGB strip.

**Comment by harueg** [comment]
Have a look at issue #628

**Comment by marsic-84** [comment]
> That sounds like two separate WLED µcontrollers, or creating a custom usermod to handle the analog white strip in addition to the RGB strip.

Is there some examples how to use custom usermod??   I need to read mqtt topic with white brightnes data and control one PWM output pin. Can you help me with that?

**Comment by nelzon101** [comment]
Hello @marsic-84 

have you find a solution? I would also take one digital and one analog strip on a ESP8266.
