### ISSUE TITLE
need latest WLED for GPIO0

### ISSUE THREAD

**Issue by ErfanDL** [Aircoookie/WLED#724]
Hi friends. can any one compile the latest version with GPIO0 LED pins ?

**Comment by Def3nder** [comment]
Hi @ErfanDL,

which board do you have ?

The ESP-chip and the flash size are needed to compile the correct version...

e.g. WeMos D1 mini ESP8266 with 4MB flash.
or ESP32 (flash doesn't matter here)
or ESP-01 with 1MB flash
