### ISSUE TITLE
Request: ANAVI controller

### ISSUE THREAD

**Issue by tpmodding** [Aircoookie/WLED#731]
i am using an anavi controller, and flashed it with WLED, works without issues

it uses a different led pin order

https://github.com/AnaviTechnology/anavi-light-controller
pin order:
https://github.com/AnaviTechnology/anavi-light-controller-sw/blob/91f7bc8f10d9733f647710c24cf57907fd86dcbb/anavi-light-controller-sw/anavi-light-controller-sw.ino#L43
should we add it as device option in nbpwrapper?

**Comment by Aircoookie** [comment]
Hi, yes, we could do so :)
Soon I will add a runtime device selector so that it doesn't even need to be changed before compiling!

**Comment by tpmodding** [comment]
also ich kann im betrieb zwischen rgb-led oder ws2812b oder apa102 oder xxx wechseln?? rgb leds gibts keine binarys nämlich

**Comment by Aircoookie** [comment]
@tpmodding genau, das ist was ich machen moechte. Es gibt langsam so viele Optionen dass man 200 binaries braucht um alle Kombinationen abzudecken :D
