### ISSUE TITLE
[documentation] Need an explanation of assets' uses

### ISSUE THREAD

**Issue by jezmck** [Aircoookie/WLED#733]
What are the different files for?

**Comment by huggy-d1** [comment]
What assets?  The WLED files in the Code tab on github.com?  If you have opened them, you can see what they contain.

**Comment by fishbone-git** [comment]
For the release .bin files, there is this (link currently just below the 0.9.1 release notes):
https://github.com/Aircoookie/WLED/wiki/Install-WLED-binary#what-binary-should-i-use

**Comment by jezmck** [comment]
Ah, thanks @fishbone-git, I didn't see that before.

**Comment by jezmck** [comment]
Phew, thought I was going blind!
