### ISSUE TITLE
wled wall mount switch and led strip compatibility 

### ISSUE THREAD

**Issue by lefterismikronis** [Aircoookie/WLED#735]
at first is the sk6812 led strip compatible with wled yes or no ?

Now my main question is that if its posible to add a physical and by phisical i mean a wall munted switch so you can turn on / off the wled from the web and also from the physical switch to make long story short i want the physical switch to interact with wled virtual on/off switch like a 3 way, for exhample when im clossing the switch web virtual switch goes off too and as a result les strip turn off too obviously ??

moreover can you do something like this through home assitant and a philips hue dimmer by programming the dimmer to interact with hassio and the hassio whould send commands to the ledstrip ???

**Comment by raoulteeuwen** [comment]
Hi. As mentioned in https://github.com/Aircoookie/WLED/wiki/FAQ , yes, SK6812 is supported. 

WLED is supported natively by HA, so you can set up any automation you like through HA.
