### ISSUE TITLE
Add support for MY9291 and MY9231 protocols

### ISSUE THREAD

**Issue by goatchurchprime** [Aircoookie/WLED#751]
These two chips MY9291 and MY9231 are in common use in ESP8266-based Wifi lightbulbs.  

A good teardown of one is given [here](https://tinkerman.cat/post/yet-another-wifi-light-bulb/).

The arduino code for it is [here](https://github.com/xoseperez/my92xx), and I've ported (slightly simplified) into a Micropython function [here](https://github.com/micropython/micropython/pull/5702).

It's a [simple protocol](https://github.com/micropython/micropython/pull/5702/commits/df9f2ef88e96b19117d686899eaa3e88bfe6754b#diff-42c6fc70b46e43e4343d60403835b935R65) that involves bitbanging DI and DCK pins (though unfortunately it is not documented anywhere).  You need to pulse the DI pin 8 times after you have sent the 4 words for RGBW, and that's about it.

**Comment by adjivas** [comment]
Did you test that? https://github.com/spectrenoir06/WLED_MY9291
