### ISSUE TITLE
Lightning Effect Issue

### ISSUE THREAD

**Issue by tonyn0** [Aircoookie/WLED#754]
In my analog version with four strips, I'm only seeing the first two ever come on for lightning effect.

**Comment by raoulteeuwen** [comment]
how is you setup? Are the 4 strips in parallel connected to a controller, or in series? How many LEDs? You have them working with other effects just fine and only the lightning is a problem/limited to the 1st 2 strips?

**Comment by tonyn0** [comment]
It's an analog implementation using the first, four pixels to drive four channels.

Most effects are fine. I have not had time yet to check and document each.
