### ISSUE TITLE
VU Meter Option IDEA

### ISSUE THREAD

**Issue by RAMBORG** [Aircoookie/WLED#761]
A vu meter part would be great,
Example VU-Meter from Cinelights (YouTube)

That's the last thing and Wled is perfect :)

**Comment by mike2nl** [comment]
Hehe, not the last thing but a very good idea. Was missing that too.

Think about two groups and the second one works in reverse direction. That would be cool with audio support. But audio support must be come from somewhere else not on the esp8266. But a VU animation is one missisng part.

**Comment by RAMBORG** [comment]
Microphone MAX4466 for example on Pin A0.

**Comment by RAMBORG** [comment]
Cinelights use a Arduino mega, uno...... Without WiFi feature, no Webserver.

**Comment by sjude68** [comment]
Ledfx on a Windows 10 computer within Anaconda or Ledfx on a raspberry pi works well for music lights.  I tried both.

Try this.
https://ahodges9.github.io/LedFx/

**Comment by RAMBORG** [comment]
It's not the same -_- 
I mean a version with a microphone, without windows or a raspberry.

Best example is on YouTube cinelights vu meter.

**Comment by Aircoookie** [comment]
Closing this in favor of #124 , which proposes the same feature. Will comment on that issue soon :)

**Comment by DJprasenjit** [comment]
i managed to do it. wire less VU meter using WLED programme. and its working great . i will share video here. its so simple setup.
its only works on windows laptop or desktop pc. its shows the display color background or the sound effect vu meter. both are looks great.
