### ISSUE TITLE
Change host name of WLED? Multiple devices with WLED on same LAN.

### ISSUE THREAD

**Issue by velkrosmaak** [Aircoookie/WLED#762]
As per the title - I can't find a way to change the hostname in the WLED UI. Is there a way? 

I've set a name for it on my dhcp server, but it still sends the name 'WLED' via MQTT, so I can't see my other WLED device which is on the same network as the names conflict. 

Any advice?
Thanks!

**Comment by fishbone-git** [comment]
Mqtt settings are in sync interfaces (for client name and topic), wifi setup has the mdns name.

**Comment by velkrosmaak** [comment]
The mdns only seems to work for Zeroconf, not the actual DNS name of the device. Thanks for the tip for sync interfaces!

**Comment by TheOnlyMatty** [comment]
In my experience changing "Server description" in the user interface settings changes the actual dns name.

**Comment by BBaoVanC** [comment]
> In my experience changing "Server description" in the user interface settings changes the actual dns name.

Just found this from a Google search. It seems like now, you have to change the mDNS hostname option for it to also change DHCP DNS. With the mDNS hostname set to blank, it was using `esp32c3-9ccba8` as the hostname.

**Comment by BBaoVanC** [comment]
Sorry, nevermind, enabling mDNS hostname was not having an effect. I am getting #4586 instead.
