### ISSUE TITLE
Question - is it possible to add a Microphone Module

### ISSUE THREAD

**Issue by CMaxim77** [Aircoookie/WLED#764]
Please forgive me if this is not the correct place to ask a question. I have searched everywhere I could think of.
I love the WLED software, thank you so much for your time and allowing us to use your software.

I have a digital/analog microphone board

![286DFB0C-3ACD-4CEF-96B3-C14245948B82](https://user-images.githubusercontent.com/34638986/76236686-6eb4fb80-6203-11ea-9b42-daf3e801679a.jpeg)

Would it be possible with the existing software to attach this to a 8266 MCU board ( Either the same one or a “wireless” connection between two boards to make the led pixels react to sound?

I used this project to make a cloud light and with the lightning effect (that looks awesome) it would be really awesome to place the microphone next to a speaker that I usually play thunder storm sounds at night and have the cloud react to the the thunder strikes in real time.

I appreciate any response that is provided.

Thanks again!

Corey

**Comment by RAMBORG** [comment]
https://github.com/Aircoookie/WLED/issues/124
