### ISSUE TITLE
Control segments via MQTT

### ISSUE THREAD

**Issue by velkrosmaak** [Aircoookie/WLED#771]
I would like to turn on and off, as well as set effects for individual segments on my WLED device. Is that possible? Thanks!

**Comment by Def3nder** [comment]
Hi @velkrosmaak, yes, you can controll segments via MQTT.

To do this you need to use the API functions of the HTTP API with sending a message to 
`[mqttDeviceTopic]/api`

The messages you need for this are documented here: [HTTP Request API](https://github.com/Aircoookie/WLED/wiki/HTTP-request-API).

You need to include either `&SS=` (or  `&SV=` in another request before) to select the segment and then add the things you want to control. 

BUT: if you main application (e.g. Home Assistant or NodeRED etc,) does support JSON, it's a lot easier using the [JSON API](https://github.com/Aircoookie/WLED/wiki/JSON-API) for dealing with segments.

**Comment by velkrosmaak** [comment]
Hey @Def3nder thanks for the reply! 

I'm using Home Assistant to achieve this, turning on different parts of the segment depending on which people are at home. I'll look into doing it using the JSON API! If you have any example code to hand, i'd be grateful in the meantime. :) Thanks again!

**Comment by viktor6** [comment]
Give an example

**Comment by mushdawg** [comment]
Hello, I have 9 segments running the same effect 'CHASE'.   I have a plex integration which changes the effect when plex is being accessed.  Is there a way for all the segments to be triggered and changed ?

**Comment by Aircoookie** [comment]
@mushdawg If all segments should run the same effect, you can select them all (tick checkbox next to the segment name) and the effect of all segments should change if you send an FX api call over MQTT.

**Comment by mushdawg** [comment]
Im using home assistant, with plex integration, I dont think MQTT is used.
I have selected all the segments in the wled mobile app, however when the call service is triggered only segment 0 changes effect, the others remain the same.

**Comment by Aircoookie** [comment]
In that case, it is probably interfacing not via MQTT, but with the integration. It should already support segments AFAIK, is your home assistant the latest version?
