### ISSUE TITLE
E131 wastes first packet for RGB modes

### ISSUE THREAD

**Issue by mjdieter** [Aircoookie/WLED#772]
With ver 9.1 the arlsLock() call in handleE131Packet() is after the pixels are set in various modes. arlsLock() then blanks all pixels (after the first packet set them) thereby wasting the first packet data. The previous version called arlsLock() before setting pixels.

**Comment by mjdieter** [comment]
When I move the arlsLock() before the select in handleE131Packet() the whole system is more responsive to E131 packets and responds more like I would expect it to.

**Comment by Aircoookie** [comment]
Thank you for finding this one, that was indeed not intended. Fixed!
