### ISSUE TITLE
MQTT API Sleep Timer still sends <nl>1</nl> when turned off

### ISSUE THREAD

**Issue by Skinah** [Aircoookie/WLED#776]
I'll keep this short in case this is in error, but I can not determine if the sleep timer is on or off as it always sends <nl>1</nl> even when turning the control off and I can not detect any difference in the MQTT messages between on and off states.

Is there a way? or is this a bug and it should be sending <nl>0</nl> when off and <nl>1</nl> when on?

**Comment by Skinah** [comment]
I can confirm the HTTP api changes correctly and the MQTT messages do not follow the same output, so I am leaning towards this is a bug or lacking feature.

**Comment by Aircoookie** [comment]
Closing since likely same issue as #777 :)
