### ISSUE TITLE
Trying to change the LED's to white with Alexa turns the RGB values to 0

### ISSUE THREAD

**Issue by arrows94** [Aircoookie/WLED#780]
If I try to change the LED's to white with the voice command the values are turned to 0. It seems that it does not calculate the RGB values from the RGBW ones. It was working in 0.8.6 I think.

**Comment by Aircoookie** [comment]
Just looked into the code and can confirm that this happens. Alexa white values are only optimized for RGBW strips, always setting RGB to 0,0,0 even if no White channel is present. Will make that conditional so that whites work well again with RGB.

**Comment by aexeler** [comment]
Hi,
i use the Binary WLED_0.9.1_ESP32.bin with the esphome-flasher-tool and it works with the App!
Thanks for this Projet.
But i have the Alexa White Problem, how can i fix it? Modify the Binary? (and how?)
Thanks for help!
Greets
Andreas

**Comment by softhack007** [comment]
Seems that this one is fixed with #3209
