### ISSUE TITLE
Cheap controller that WLED supports

### ISSUE THREAD

**Issue by Algram** [Aircoookie/WLED#783]
Hi, thanks for all the work you put into this!

I would like to ask if there are any cheap controllers available that WLED runs on out of the box?
Something like this for example: https://www.aliexpress.com/item/32890025804.html

Ideally I would like to drive about 2m (288 LEDs) with a controller and WLED.

Thanks!

**Comment by srg74** [comment]
@Algram 
Look at the section https://github.com/Aircoookie/WLED/wiki/Compatible-hardware

**Comment by tonyn0** [comment]
I'm not seeing anything in the wiki but development boards. He's looking for an existing LED controller that can be flashed. 

Should that be a new section or just put in Useful boards and addons?

**Comment by Aircoookie** [comment]
@tonyn0 i would just add it to the `ESP8266/32 boards` section

**Comment by luminxa** [comment]
Yes our new board comes with it preinstalled :) https://luminxa.com/product/luminxa-2-2-2/

<img src="https://luminxa.com/wp-content/uploads/2020/02/DSC01074aa.png">

**Comment by huggy-d1** [comment]
I hope @Aircoookie gets a % of the profits...

**Comment by luminxa** [comment]
He will :)

**Comment by almulder** [comment]
Check out these. I used one to run my Addressable flood lights in my back yard. All inhad tondonwas plug into pc. Flash the wled to it and inwas up and running. They are only like $3 each. 

Amazon.com
KeeYees 3pcs ESP8266 NodeMCU CP2102 ESP-12E WiFi Internet Development Board Wireless Module Compatible with Arduino IDE https://www.amazon.com/dp/B07HF44GBT/ref=cm_sw_r_other_apa_i_4XcFEbZMDFE88

**Comment by luminxa** [comment]
those are cool kind of in between the d1 and nodemcu

**Comment by luminxa** [comment]
> I hope @Aircoookie gets a % of the profits...

Just an update: we haven't sold any yet, going to reach out to adafruit and see if they might be interested in distribution though.

**Comment by thedannymullen** [comment]
> I would like to ask if there are any cheap controllers available that WLED runs on out of the box?
> Something like this for example: https://www.aliexpress.com/item/32890025804.html

If this box has and 8266 in it then it could be reflashed.  I would love to use one of these as it would be and out of the box led driver with no wiring needed.   I have not had the chance to purchase or research which ones have 8266 and can be reflashed though.

**Comment by tonyn0** [comment]
Check the link. 

https://github.com/Aircoookie/WLED/wiki/Compatible-hardware

I added the one I know of.

**Comment by thedannymullen** [comment]
@tonyn0 Thanks I missed that one!!!

**Comment by srg74** [comment]
@thedannymullen In the same section there is another cheap H803 controller which can be flashed out of box too :)
