### ISSUE TITLE
Change start led

### ISSUE THREAD

**Issue by Maurotb** [Aircoookie/WLED#788]
Hi,
i have 894 led ws2815 , my strips are installed as an O.
To keep the length of the signal cable short, I need to connect it to a specific point, but so some effects where you need to have the start / end pixel in a specific position are bad to see.
There is a possibility to shift the first led on another position via code?
Thanks

**Comment by Aircoookie** [comment]
Hi!
You can set a different starting point using segments, but that would keep the LEDs before this point off. What you really want is for the LEDs to wrap around. That is not possible right now, but easy to add! Will be an option in version 0.9.2 :)

**Comment by Maurotb** [comment]
Good!
It would be nice to be able to do it on segment 0 so that we can have transactions :)

**Comment by Geraldidi** [comment]
I was meesing with a rectangular shape and would love to change start led position so visually looks good. I'm using it with LedFX so I think setting it as a segment configuration would work with it

**Comment by Pe-MaKer** [comment]
I found this feature request after posting on discord:
https://wled.discourse.group/t/right-placement-of-led-ends-behind-tv/1239 

I'd like to set the first pixel indepentantly from the physical start/end of the strip I placed my TV in the usual square shape. ;)
Hopefully, this FR will make it in the next release.

**Comment by Aircoookie** [comment]
Implemented!

**Comment by coryking** [comment]
Dude, nice!!!! Thanks!

**Comment by rngDeadeye** [comment]
How do you do it?

**Comment by DedeHai** [comment]
@rngDeadeye please use discord for support questions
