### ISSUE TITLE
Request for Pacifica animation from fastled

### ISSUE THREAD

**Issue by emdeex** [Aircoookie/WLED#790]
First off... loving WLED since I found it this morning!

Second ... can I request we get the new Pacifica animation that fastled has?  Not sure yet if this is non-trivial or not.

https://www.reddit.com/r/FastLED/comments/eordjm/pacifica_new_water_animation_dedicated_to_dan/

**Comment by Aircoookie** [comment]
Rest in Peace Dan.

This effect is absolutely mesmerizing, I will add it to WLED asap!

**Comment by Aircoookie** [comment]
Added! However I still want to expand on it a little bit soon to be able to set different colors (although these nice blues will always stay the default!)

**Comment by emdeex** [comment]
Fantastic!  Can't wait to try it... I'm using the WLED binary currently,
any chance of whipping a new binary version up?

**Comment by NietGiftig** [comment]
@Aircoookie 
Did you have a try for expanding it with different colors, or is this not possible?
This a awesome effect !!

**Comment by Aircoookie** [comment]
@NietGiftig glad you like it! Yes, Pacifica now supports palettes, so you can pick any you like most. Or select the palette  `* Color Gradient` in the name, it will allow you to set 3 custom colors :)

**Comment by NietGiftig** [comment]
@Aircoookie 
Great, thanks, had not discovered the correct way to integraded the palette in the effect.
Using WLED just for a couple of hours
rtfm, as always the best solution
