### ISSUE TITLE
Embedded ESP32 with 12 LEDs onboard + Gyro Sensor

### ISSUE THREAD

**Issue by luminxa** [Aircoookie/WLED#791]
I have launched a ESP32 Board with 12 onboard LEDs (6 on each side) + Gyro Sensor
https://luminxa.com/product/luminxa-2-2-2/
https://youtu.be/eo4T2oC7ZcA
Bulk pricing available.
<img src="https://luminxa.com/wp-content/uploads/2020/02/DSC01074aa.png">

**Comment by Aircoookie** [comment]
Hi,
that is very cool! but not an issue.
Feel free to add it to the forum though :) https://wled.discourse.group/c/projects/6
Greetings
