### ISSUE TITLE
Question about pattern presets

### ISSUE THREAD

**Issue by PJMCL1618033** [Aircoookie/WLED#793]
Is there a method to clone Wled’s sixteen pattern presets from one Wemos D1 to a second one?
Thanks for this awesome software.

**Comment by Aircoookie** [comment]
Yes, there are two ways:

1. If you can connect both D1 to your PC via USB:
Use the command from https://github.com/Aircoookie/WLED/issues/479#issuecomment-567587568 to read all data (installation, settings, presets) from one ESP and use `write_flash` to write it to the second. You may need to immediately change the mdns and ip addresses in Wifi config to not cause conflicts.

2. Manually via WLED sync:
Activate the sync button on the first D1 mini and select the first preset. The second controller should change to that preset, too. Now save it in the same slot on the second unit. Repeat this for all the presets you need.

This will get easier in the future. I aim to have just a single `presets.json` file for this purpose, you'll be able to simply copy it over :)
