### ISSUE TITLE
Possibility to save color/intensiti/effect/speed as effect name

### ISSUE THREAD

**Issue by Maurotb** [Aircoookie/WLED#796]
I use wled with homeassistant and node-red, frome homeassistant/node-red i can set only effect and color.
I need for my home one automation a combo of effect/color/intensity/speed for various situation but i can't make this from HA.
One feature request, possibility to make a custom effect name based on  effect/color/intensity/speed,
with this i can use full feature of wled in my HA simply selecting custom effect
Thanks

**Comment by pille** [comment]
this is a feature request. please reopen.

**Comment by blazoncek** [comment]
Presets are implemented since 0.11. Closing.
