### ISSUE TITLE
Red light chassing string on any effect

### ISSUE THREAD

**Issue by almulder** [Aircoookie/WLED#797]
So I am running  0.9.1 and reguardles of the effect I select the last led becomes red and jumps from the last to the next led working it's way to the first led and then it stops for about 1 min and then it starts again. Moving from the last led to the first led. I only have 11 LEDs on the strip. 

Any idea what is causing this?

**Comment by Aircoookie** [comment]
Hi,
another user had this issue a few months ago, it is presumably caused by flash corruption.
You can try completely erasing the flash memory with esptool (`esptool.py erase_flash`) and then re-flashing WLED, that could fix it :)

**Comment by almulder** [comment]
Aw ok, I will try that tonight when it gets dark again outside. Thanks!

**Comment by almulder** [comment]
Yes this fixed the issue. Thanks.
