### ISSUE TITLE
Question - ESP32 with WS2801

### ISSUE THREAD

**Issue by Stoffl1981** [Aircoookie/WLED#800]
Hey, could you please provide a version for the ESP32 with WS2801 LED? Thanks in advance!

**Comment by Stoffl1981** [comment]
Ok, I compiled it myself, but I had to change the pins to get it work:

CLKPIN 18
DATAPIN 19


[WLED_0.9.1_ESP32_CLKPIN_18_DATAPIN_19.zip](https://github.com/Aircoookie/WLED/files/4386413/WLED_0.9.1_ESP32_CLKPIN_18_DATAPIN_19.zip)

**Comment by pattyland** [comment]
You are awesome! This build worked for me right away.
Did you built current versions for WS2801 too? Would you mind sharing them?
