### ISSUE TITLE
Compiling WLED for default_envs = esp8285_5CH_H801 throws error

### ISSUE THREAD

**Issue by Dreamoffice** [Aircoookie/WLED#802]
Hello
i m trying to compile WLED to use it on the Novostella Floodlights. These are 5 channel pwm LED lights.
therefore i did the following:

![Bild 1](https://user-images.githubusercontent.com/35889916/77621391-ab3f6180-6f3c-11ea-843c-76a6cd3053a7.png)
![Bild 2](https://user-images.githubusercontent.com/35889916/77621508-e0e44a80-6f3c-11ea-9e12-931aaa4e5d25.png)

but during compiling i get this error:
![Bild 3](https://user-images.githubusercontent.com/35889916/77621578-feb1af80-6f3c-11ea-8615-8ab2c5ac5e20.png)

`wled00\FX_fcn.cpp: In member function 'void WS2812FX::setRgbwPwm()':
wled00\FX_fcn.cpp:829:20: error: cannot convert 'RgbwColor' to 'uint32_t {aka unsigned int}' in assignment
   _analogLastColor = color;
                    ^
*** [.pio\build\esp8285_5CH_H801\src\FX_fcn.cpp.o] Error 1`
![Bild 4](https://user-images.githubusercontent.com/35889916/77621668-2c96f400-6f3d-11ea-85f0-8e68f96d6546.png)
 
i didn't get the problem....

br Dave

**Comment by huggy-d1** [comment]
I proposed an edit to FX.h that changes _analogLastColor to datatype RgbwColor.  Hope that works. Otherwise it may need to be defined locally as a class property, which is kinda weird (to me at least) for conditionally used variables and logic.

**Comment by Aircoookie** [comment]
@huggy-d1 i did just that, change the type to RgbwColor yesterday. Just didn't push yet 😅 
Fixed in master!
