### ISSUE TITLE
Feature Request: Show colors in palettes

### ISSUE THREAD

**Issue by jezmck** [Aircoookie/WLED#803]
I've not memorised all the options, and think it would be good to show them in the \<select>, or replace it with a list of selectable bars (radio buttons).

**Comment by jezmck** [comment]
Perhaps like this?

https://codepen.io/jezmck/details/KKpromE

![image](https://user-images.githubusercontent.com/89996/77658770-143fcd00-6f6f-11ea-900f-0d4a9c28fe22.png)

**Comment by Aircoookie** [comment]
Not a bad idea! Once the palettes are stored in a `palettes.json` file instead of hard-coded, the browser could read this file and render previews for the palettes! (would be changed from select dropdown to buttons)

**Comment by tihoangyeudau** [comment]
> 
> 
> Not a bad idea! Once the palettes are stored in a `palettes.json` file instead of hard-coded, the browser could read this file and render previews for the palettes! (would be changed from select dropdown to buttons)

i like it. very easy to choose

**Comment by jezmck** [comment]
Something clever will have to happen for the special palettes I guess.

**Comment by Brausmith** [comment]
I like this, and also for the favourites.

**Comment by jezmck** [comment]
Awesome job in the latest release, thanks!
