### ISSUE TITLE
DMX Single color RGBW support

### ISSUE THREAD

**Issue by AndrewApi** [Aircoookie/WLED#811]
Hi

Thank you for the DMX Mode it works great.

Could we have in the drop down list options for:
Single RGBW
Single DRGBW
For use with analogue LED strips.
The EFFECTS option at present is the only way to control White Channels.

Andrew

**Comment by Aircoookie** [comment]
Hi Andrew,

I am not going to add new DMX modes for now, that is not necessary for RGBW support. Rather I will make the single RGBW and single DRGBW modes support an additional channel for white support :)

**Comment by AndrewApi** [comment]
Great, as all ways, thank you.

**Comment by Aircoookie** [comment]
Done :)
