### ISSUE TITLE
esp01-s flash WLED_0.9.1_ESP8266_512K.bin error

### ISSUE THREAD

**Issue by nmweizi** [Aircoookie/WLED#821]
Need to compile myself?
1. flush WLED_0.9.1_ESP8266_512K
2. 4.3.2.1->configure wifi
3. not connect wifi
4. Serial port info,cycle
 
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)                                  
                                                                               
load 0x4010f000, len 1384, room 16                                             
tail 8                                                                         
chksum 0x2d                                                                    
csum 0x2d                                                                      
vbc204a9b                                                                      
~ld                                                                            
   Ada

**Comment by Aircoookie** [comment]
Hi,
this issue has also been reported for the 1M_full binary. You can try clearing the mDNS field in wifi settings at the same time you enter your home wifi settings (you will need to erase flash beforehand), that may be a workaround. if it connects successfully, send me the output of `[WLED-IP]/json/info` so I can look into it :)

**Comment by nmweizi** [comment]
is fine,thank you.
1. erase flash
2. flash 1M_full binary
3. clearing the mDNS field in wifi settings at the same time you enter your home wifi settings
