### ISSUE TITLE
APA102 RGBW with separated LEDs support

### ISSUE THREAD

**Issue by lwalpurgis** [Aircoookie/WLED#824]
Hello,
At first a very big thank to @Aircoookie , for this really amazing project.
I have a special APA102 RGBWW LED stripe, where an APA102 RGB and a solid WW APA102 led is alternately on the strip. See the picture.
![20170430_153518](https://user-images.githubusercontent.com/10418543/78469297-29132200-7720-11ea-9ba9-77de6cd3860d.jpg)
I used my own Fastled code for this project where I created 2 "virtual" led stripes (RGB and ww) and mapped these at the end before show method in the right order into the real LED stripe, which works good. (I copied the warm white value into all 3 bytes of the warm white led) But now I want to use wled, which is way better. How can I achieve this? Thanks for help!!!

**Comment by thedannymullen** [comment]
@lwalpurgis  did you custom build that ?  Or was it an off the shelf item?

**Comment by lwalpurgis** [comment]
> @lwalpurgis did you custom build that ? Or was it an off the shelf item?

I ordered this led stripe in this configuration in china...

**Comment by thedannymullen** [comment]
Really mice!  I will look for it if you have a link it would be great.
