### ISSUE TITLE
Preview shows wrong color if RGB is changed to RBG

### ISSUE THREAD

**Issue by diabolo86** [Aircoookie/WLED#825]
The preview shows the wrong color if I change the settings from RGB to RBG.
Red shows blue, blue shows green and green shows red.
Only the preview is wrong, the LEDs show the right color.

![grafik](https://user-images.githubusercontent.com/47504455/78602064-1a2e8b80-7856-11ea-9f1f-6ddb99843e00.png)

Setup: WLED 0.9.1, NodeMCU, WS2801 with levelshifter

**Comment by Aircoookie** [comment]
Thank you for reporting! RBG mode was affected too. Fixed in source :)

**Comment by diabolo86** [comment]
Thanks for the support and the great project.
