### ISSUE TITLE
10apr github fails to build - sappends define mismatch between xml.cpp and fcn_defines.h

### ISSUE THREAD

**Issue by daavery** [Aircoookie/WLED#836]
void sappends(char stype, const char* key, const char* val);
vs 
void sappends(char stype, const char* key, char* val);

**Comment by Aircoookie** [comment]
I wonder what that is about... what IDE are you using?

Yesterday's build 2004100 correctly has 
```cpp
void sappends(char stype, const char* key, char* val);
```
in fcn_declare.h and
```cpp
void sappends(char stype, const char* key, char* val)
```
in xml.cpp. Those seem to match.

Can you send the complete error message? Maybe we can find out the reason it doesn't compile for you.
