### ISSUE TITLE
Led Orange when no e131 data also auto power on for e131

### ISSUE THREAD

**Issue by thedannymullen** [Aircoookie/WLED#837]
I am trying to latest version of wled for my xlights setup.  I have two issues that I don't know how to resolve in the preference menu.

1. How can I have it auto power on when e131 data is received?  So coming out of reset the power should be on.

2. When I quit sending data over e131 how do I make it not turn orange? It should just be off or last state, until it receive more data.

**Comment by Aircoookie** [comment]
Hi,
the easiest workaround is setting the WLED UI color to black, but leaving the brightness on. In that case, E1.31 will work as expected and the LEDs turn off if there is no new data.
