### ISSUE TITLE
Feature request: numeric value for speed,intensity,luminosity,rgb, white point

### ISSUE THREAD

**Issue by Maurotb** [Aircoookie/WLED#839]
Hi, i have two strip led, i need to make same colour, speed ,intensity, luminosity for this strip.
Is difficult to make identical value with colour palette and slide bars...
Another feature that serves, in addition to the color palette, it would be useful to have also a palette for white (with various shades from cold white to warm white) such as philips hue

**Comment by Aircoookie** [comment]
Hi! You can automatically sync both strips together using the sync button in the top of the UI.
But I agree that a numerical input could be helpful!
Color temperature/white shade input is also planned :)

**Comment by Maurotb** [comment]
I need to power on/off two strip independently, sync is not an option for me :)
Good! I'm waiting new release, great wled !

**Comment by Aircoookie** [comment]
You can just turn the sync button on, set the correct palette/sliders and then turn it off again.
Then both will be controllable independently again :)
