### ISSUE TITLE
LED Count mismatch

### ISSUE THREAD

**Issue by Beliar-666** [Aircoookie/WLED#842]
Hi, now a real issue i can´t figure out why this happens. I have a strip with 150 LED Its a 2813 (The one with the reserve Signal line). It works fine but one Problem exists.
WLED version 0.9.1

I have to set number of Leds to 151 if i set it to 150, what i really have, the Last Led stays off and wont light up. Any Idea why this happens? Why this is a Problem? If i use e1.31 to control the Leds, the pattern doesnt dit, cause the Count is wrong. Hope u understand what i will say.

Any Idea why this happens? Why i have to Config one more Led than i have?

Edit: I also have ws2812, there it works with the LED Count. 30 per Strip, 30 in Config, 30 lights up.
Here is a link to the explantation of the difference between 2812 and 2813:
[https://www.seeedstudio.com/blog/2019/02/14/ws2812b-vs-ws2813-addressable-rgb-led-strips-how-are-they-different/](url)

**Comment by Aircoookie** [comment]
Hmm I have no idea why this happens... you could try a slow Scan effect to see which LED is skipped/counted twice. As a workaround, try setting 150 in config and checking "Skip first LED", that should fix the E1.31 issue.
Might be related to the backup pin or something...

**Comment by tonyn0** [comment]
Maybe it's just like the wonky numbers in segments?
