### ISSUE TITLE
(Q) Is it possible 6803 IC Chip LED to operate?

### ISSUE THREAD

**Issue by salopette** [Aircoookie/WLED#851]
Hello, maybe there is a possibility to use 6803 IC Led's with the hot WLED?

**Comment by Aircoookie** [comment]
Hi,
it could be that the LPD6803 uses either the WS2801, LPD8806, P9813 or APA102 protocols. You could test this by un-commenting one header at a time in `NpbWrapper.h`. If none of them work, the IC is not supported and I'd recommend opening a ticket with Makuna at https://github.com/Makuna/NeoPixelBus and maybe buying him a coffee for his hard work :)

**Comment by salopette** [comment]
Ok, I'll try! Which pin do I have to use for data and which for clock?

Thank you

**Comment by Aircoookie** [comment]
Clock pin GPIO 0 (D3) and data GPIO 2 (D4) by default :)

**Comment by WerkAG** [comment]
> 
> 
> Hi,
> it could be that the LPD6803 uses either the WS2801, LPD8806, P9813 or APA102 protocols.
>...

The LPD6803 does not work using any of those types, however its possible to make WLED work with those kind of LED strips.
I understand that the low level communication is provided by NeoPixelBus. 
Based on some already supported LED types by NeoPixelBus, I created two new files for the LPD6803 type:
Lpd6803ColorFeatures.h
Lpd6803GenericMethod.h

I have a 10 meters (2 x 5m) LED string working for almost 10 days, with WLED 0.11.0 and a Wemos D1 mini (ESP8266).
Already sent the files to Makuna. In case he decides to integrate them on NeoPixelsBus, will be easy add support for the LPD6803 to WLED, by doing minimal changes on NpbWrapper.h (possibly on the BusWrapper_h file on the dev version too).
