### ISSUE TITLE
Is there any way to change the PIN that is used for the LED?

### ISSUE THREAD

**Issue by simpat1zq** [Aircoookie/WLED#855]
I'm trying to compile with Arduino IDE, and I keep running into issues. The only thing I need to change is the PIN, so it would be nice if I can just load the binary and change it through the settings.

**Comment by simpat1zq** [comment]
Well, it looks like I was able to get it to compile by updating the board in Arduino. I had to downgrade it a while ago to get it to work with some old code I had. Anyways, I still think changing the pin in the webUI would be a useful feature.

**Comment by fishbone-git** [comment]
it's in the works, but please follow #345 for activity.

**Comment by Aircoookie** [comment]
Yep, in the works!
