### ISSUE TITLE
feature request: serialized config format

### ISSUE THREAD

**Issue by pille** [Aircoookie/WLED#860]
i'd like to propose to change the way wled stores its configuration.
currently it is stored in EEPROM using a hardcoded layout. though it already supports versioning, this means the load/save config code needs to be modified for every added feature that comes with new settings in a backward-compatible way. there's no simple way of backing up the config or even selecting one out of a bunch (unless you go the hard way: #479).
this will also help to overcome preset/segment limitations (#737) and ease implementing #852.
#639 is _currently_ a blocker, since this will increase the config size, but @Aircoookie already mentioned in https://github.com/Aircoookie/WLED/issues/639#issuecomment-579316324 to enable SPIFFS by default.

the serialized config format should be a trade off between small size and human readability. compression may be an option. maybe it can be even squeezed into EEPROM, but SPIFFS is the way to go, since it would support multiple configs and backups. even undo/redo ;)

**Comment by Aircoookie** [comment]
Mainline feature of WLED 0.11.0, planned to release on Sunday :)
