### ISSUE TITLE
Cycling through effects automatically

### ISSUE THREAD

**Issue by CollaVinilica** [Aircoookie/WLED#861]
Maybe I'm missing something, but is there the possibility to cycle through ALL the included effects without the presets automatically?

**Comment by raoulteeuwen** [comment]
You're not missing anything; there is no(t yet) such thing/option... Not sure whether https://github.com/Aircoookie/WLED/issues/593 would suit you, or maybe add your question to that thread?

**Comment by Aircoookie** [comment]
Yep, there is no such option. It wouldn't really make sense to cycle through all effects as most look good with different speed/intensity settings. I will add a configurable effect playlist feature at some point, then you can of course create a playlist with all presets :)
