### ISSUE TITLE
notifyMacro

### ISSUE THREAD

**Issue by StevenG929** [Aircoookie/WLED#868]
It seems that even if Notify Macro is set in the GUI it doesn't broadcast which macro is being executed?

Also if the web GUI is used to turn on/off, or turn on night timer mode it doesn't send a broadcast either from what i see, it would be great to be able to keep in sync

Thank you - this software is great

**Comment by Aircoookie** [comment]
Hi! Sounds like the sync is not correctly enabled in your setup.
Make sure all devices you want to sync have the same port (21324 by default) and receiving is ticked for all of them in Sync settings.
Then enable the master sync send via the Sync button in the top of the UI. Only if that is active, syncing from macros or direct change in the web UI will be possible :)
