### ISSUE TITLE
Stop effect when its finished

### ISSUE THREAD

**Issue by EvertJob** [Aircoookie/WLED#877]
Hi,

I've mounted 6 strips underneath the stairs and I used the "Tri-wipe" effect to get a nice effect when I'm walking up the stairs.

But the effects keeps repeating itself and I would like to change it to "Solid" when all the leds are done.

It will give some cool features if it's possible to stop the effect when it's done ;)

Does anyone know if this is possible?

**Comment by huggy-d1** [comment]
Have you looked at the stairway basic usermod?  I think that is what you want to try next.

**Comment by EvertJob** [comment]
If you mean this one: https://github.com/Aircoookie/WLED/blob/master/usermods/stairway_wipe_basic/wled06_usermod.ino

Yeah, just found it. But cannot find out how to install it :(
