### ISSUE TITLE
ESP32 pausing effect

### ISSUE THREAD

**Issue by srg74** [Aircoookie/WLED#878]
ESP32 mini version pausing running effect (hanging) for ~3 sec and then run again for another ~24sec. Process repeating in cycle.

**Comment by Aircoookie** [comment]
Hi, can you send me a link to this ESP32 mini board? Such hanging mostly happens from blocking APIs, check if NTP time and Blynk are disabled, they often cause this :)

**Comment by srg74** [comment]
Thank you so much. Pauses have been due to disabled internet access and enabled NTP. Everything is good now. Board is [here](https://www.amazon.com/gp/product/B01LBOJUI6/ref=ppx_yo_dt_b_asin_title_o08_s01?ie=UTF8&psc=1)
