### ISSUE TITLE
ACST Timezone

### ISSUE THREAD

**Issue by nicr4wks** [Aircoookie/WLED#881]
Hello,

Please add support for Australian Central Standard Time (ACST) GMT +9.30
This timezone is 30 minutes behind AEST (GMT +10).

ACST covers South Australia and Northern Territory.
Northern Territory does not observe daylight savings.
South Australia does observe daylight savings.

Thanks.

**Comment by Aircoookie** [comment]
Done! :) Will be part of the 0.10.0 release tomorrow!
