### ISSUE TITLE
Error 2 NodeMCU

### ISSUE THREAD

**Issue by Skyking721** [Aircoookie/WLED#900]
Flashed latest bin release NodeMcu and a few issues I did not see on the D1 mini.  Red Error 2 box on WLED Ap /UI pops up every enter, auto discovery not fining device,  Google mesh network, Mcu locks up on 5g band. (as expected. Cant turn off 5g nor Vlan w/ Google Mesh.) :(

**Comment by Aircoookie** [comment]
Hi!
5GHz is not the issue, most every router also accepts connections on 2.4GHz.
Error 2 means the flash layout is off, probably you flashed the `ESP8266_1M.bin` where the correct one for NodeMCU is just `ESP8266.bin` :)

**Comment by Skyking721** [comment]
Thanks for reply. I can not disable 5g on Google mesh and therefore when d1 or nodemcu is closer to ap, 5g is assigned by default.   I flashed a D1 with same bin as Node and get same Error on both Node and D1. Strange.

**Comment by Skyking721** [comment]
I'll try the other bin on the node. Tx
