### ISSUE TITLE
How I save default color

### ISSUE THREAD

**Issue by sentinelapr** [Aircoookie/WLED#904]
How can I record the default RGB color, so that when I reboot I don't lose the color settings? I'm new. I put the colors Red Green and Blue and when I turn off the NodeMcu it is placed Orange, No color and no color

**Comment by raoulteeuwen** [comment]
You are using segments? Currently, only memory location 16 can store segments. In one of the next release the dev will provide more storage locations and every location will be able to hold segment info. So for now: store your segment setup in location 16, and make the nodeMCU boot up with memory location 16 and you should be good.

**Comment by sansillusion** [comment]
I think sentinelapr is saying that after a power off when it boots it loads
default color or stored settings but would like it to remember last state
instead. Wich I too would like a lot since I get random reboots due to heap
corruption on esp32.

Le ven. 8 mai 2020 3 h 03 a.m., Raoul Teeuwen <notifications@github.com> a
écrit :

**Comment by sentinelapr** [comment]
Yes Sansillusion. Sorry for my english.  Its the first time power up.  No configuration.  I choose RGB color, reboot and no remember last setup or save.

**Comment by sentinelapr** [comment]
> You are using segments? Currently, only memory location 16 can store segments. In one of the next releases the dev will provide more storage locations and every location will be able to hold segment info. So for now: store your segment setup in location 16, and make the nodeMCU boot up with memory location 16 and you should be good.

No segments, default configuration, firstimer

**Comment by pille** [comment]
save the effect settings you want to come up at boot in a slot and configure it to be loaded on boot in LED settings.
