### ISSUE TITLE
Power Button

### ISSUE THREAD

**Issue by qubie2012** [Aircoookie/WLED#906]
when using preset cycle if i press power button the leds turn off but only for a few seconds, the leds turn back on at the next preset cycle. if i use just 1 preset and power off the leds stay off until i press the power button or one of the presets.

many thanks for the new update, i am running 5 nodemcu with esp8266.bin latest build.

**Comment by Aircoookie** [comment]
Hi! Awesome that you like WLED! Please see #895, I'm going to change the cycle behavior :)
