### ISSUE TITLE
Alexa cannot discover my device

### ISSUE THREAD

**Issue by tihoangyeudau** [Aircoookie/WLED#909]
In 0.10.0 version, alexa cannot detect it anymore. Can you fix it?

**Comment by Aircoookie** [comment]
Hi, do you mean the 0.10.0 release or current master source? What ESP are you using?

**Comment by tihoangyeudau** [comment]
Yes i do. Im using wemos d1 mini

**Comment by copperfield74** [comment]
Hi guys. Same problem with NodeMCU V3
