### ISSUE TITLE
First pixel incorrect

### ISSUE THREAD

**Issue by Jdbrown87** [Aircoookie/WLED#914]
I am using a 5v 50 pixel led string with a 5v/60a Powersupply. Everything is connected and running but the first pixel will not allow me to control it. I have tried multiple strings and I am getting the same result. If i select skip the first led it actually skips the 2nd one(The one after the uncontrollable one)

**Comment by sansillusion** [comment]
Sounds like a dead led that is shorted between Din and Dout. Try putting
the data signal on a random led to see if it skips that one.

**Comment by huggy-d1** [comment]
There is a WLED setting that skips the 1st pixel.  Maybe it is checked for your setup?
