### ISSUE TITLE
Fire preset when network connection lost?

### ISSUE THREAD

**Issue by jaygrovr** [Aircoookie/WLED#918]
I have your amazing software running a pretty big nightlight in my daughters room, and its set to turn off at certain times, specifically their bedtime.  Last night It did not trigger at the time specified and it didnt have a connection to the network, which I wasnt sure why, but I wasnt able to troubleshoot when the issue occurred.  Is it possible to setup a preset to be fired when the connection to the network is lost and another preset when its regained?

**Comment by Aircoookie** [comment]
Hi, I'm glad that you like WLED so much. Sorry for the connection issues! Is the ESP close enough to your router? You can check the signal strength in the new 0.10.0 "Info" screen (top button in web UI).
If you want to fire a preset when the connection status is changed, you could add this to `userLoop()` in usermod.cpp (and compile yourself)

```cpp
static bool connectedBefore = false;
if (WLED_CONNECTED != connectedBefore)
{
  connectedBefore = WLED_CONNECTED;
  if (connectedBefore) {
    applyPreset(2); //reconnected preset
  } else {
    applyPreset(3); //disconnected preset
  }
 colorUpdated(5);
}
```
