### ISSUE TITLE
Alexa problem

### ISSUE THREAD

**Issue by colder1989** [Aircoookie/WLED#930]
i have a problem with alexa...when i try to controll my strip with alexa, the Nodemcu go always offline... i need to reboot manual... if i control the led from my browser and with the app works good...
i have compileted by myself but the only change is uncommented analog led and change UDP port from "Sync Settings"

**Comment by huggy-d1** [comment]
Have you disabled SYNC for all things that can sync up?

**Comment by colder1989** [comment]
![wled](https://user-images.githubusercontent.com/64509346/82502261-0897ff00-9af7-11ea-959c-813d752342e8.jpg)
I've got everything off, except alexa.

**Comment by huggy-d1** [comment]
I am by no means an expert in configuring WLED (meaning I can be 100% wrong), but.. here's what I see enabled that relates to outside devices:

1. Broadcasting brightness, color, effects all enabled
2. Send notifications for direct change & button press enabled
3. Receive UDP realtime enabled

On the main WLED screen, is SYNC configured to ON for either send or receive?

**Comment by colder1989** [comment]
Ty man...now works...if i enable "send alexa notifications", the device stuck..... what is that option for?

**Comment by huggy-d1** [comment]
I don't know, but guess it relates to updating Alexa with current values for dim level, color, and on/off status.

**Comment by d3iu** [comment]
i can't even get alexa to discover the device, all is set, including a name, alexa option is on... nothing works.. disabled everything on sync... literaly nothing works.. wled is running on a nodemcu, did not have this problem with another device running wled version 9

**Comment by huggy-d1** [comment]
@d3iu Did you ever get Alexa to discover your WLED install?

**Comment by drschnalli** [comment]
I'm trying to connect it to alexa, too. But it does not discover the device. Alexa Sync is turned on.
