### ISSUE TITLE
ip connection

### ISSUE THREAD

**Issue by velidhu** [Aircoookie/WLED#934]
I loaded the software. connected to ap. set my ssid and reset. esp8266 does not connect to my wifi. it's not on my network. only if I connect directly to ap. both static ip and dhcp.
from ap I control all functions well

**Comment by dogson3006** [comment]
check this out: https://github.com/Aircoookie/WLED/issues/946.
hope it will help you too

**Comment by velidhu** [comment]
> check this out: #946.
> hope it will help you too

i think the problem was that it didn't change wifi settings if the esp had been used for other projects. with a new esp no problem. with the new core it also works on recycled esp
