### ISSUE TITLE
Possibility to disable the LED on Controller board

### ISSUE THREAD

**Issue by FalkPe** [Aircoookie/WLED#939]
Hey Aircookie,
Is the a possibility to disable the blue power led on my NodeMCU v3 via the Firmware?

Thanks for your wonderful WLED

**Comment by raoulteeuwen** [comment]
Hi @FalkPe . Does the question/answer about the LED in https://github.com/Aircoookie/WLED/wiki/FAQ answer your question?

**Comment by FalkPe** [comment]
Sorry for my question. 👍
