### ISSUE TITLE
Mqtt Port Change

### ISSUE THREAD

**Issue by Beliar-666** [Aircoookie/WLED#94]
Hello,
I think in the Sync Section on Mqtt there should it be possible to change the mqtt Port. I had to search for the Port in the Files to change it to my Port for functioning.

**Comment by Aircoookie** [comment]
Ok, I will add a MQTT port setting in the next update!

**Comment by Beliar-666** [comment]
Wow U R fast with Feedback. Before i Forget, Merry Xmas.

I just found jour WLED. I just tried ither Ways to Control my WS2812 via NodeMcu. I now have one Stripe with your WLEd and one i build before with McLightning. 
Wled has quite more effects and the possibillity to easy switch off is great. Also to change secondary Color is quiet a great feature.

I´m just searching for one special effect i think FastLed Lib has. Its Rainbow with bright white flickering single leds. Is it possible to integrate that also?

**Comment by Aircoookie** [comment]
Merry Christmas to you as well!
I'm happy that you like WLED.

You should be able to achieve an effect really similar to the one you are searching for by selecting the Sparkle effect, white primary color and Rainbow as the palette setting. What palette does depends on the effect, but for Sparkle it sets the background. To quickly save that config for later use, you can use the [presets](https://github.com/Aircoookie/WLED/wiki/Presets) feature!

**Comment by Beliar-666** [comment]
Thank You, yes this works. But i mean a moving Rainbow. I Think in ws2812fx its Rainbow cycle. And in this effect i wanna have real bright white sparkle.

**Comment by DennisH1978** [comment]
Hello! Is there a chance to change the port now? On 1883 my Sonoff devices running.
Or is there a way for me to give WLED an other port?
Thx Dennis
