### ISSUE TITLE
Night Light Behaviour

### ISSUE THREAD

**Issue by Morphy99** [Aircoookie/WLED#940]
I've noticed that if the target brightness is higher than 0 the light will not turn off as stated when clicking the nightlight button in the GUI. I've tested this on the latest 0.10.0 binary using APA102 LED's on a WEMOS D1 mini. I've tried un-ticking Fade Down and it still stays on.

**Comment by Aircoookie** [comment]
Hi! This is intended behavior, the nightlight will fade towards the set Target brightness. However you are correct that I should change the wording in the popup, because it indeed does not turn off (and is not meant to) with a target brightness higher than 0.

**Comment by Morphy99** [comment]
I thought it would turn off if fade down was unticked? What's the function of fade down then?

**Comment by Aircoookie** [comment]
It will turn off if you set the Target Brightness to 0. Fade down will when checked gradually change the brightness over the duration, when unchecked it will stay the same until the duration is over, then instantly apply the set Target brightness :)
