### ISSUE TITLE
Conncecting to Wi-Fi issue

### ISSUE THREAD

**Issue by SimState** [Aircoookie/WLED#944]
I can connect to WLED Wi-Fi, but when in settings i try to conncect the ESP8266 to my home Wi-Fi it connects, the ip showed in my roter config is 192.168.1.5, but seraching it in my browser nothing show.

**Comment by dogson3006** [comment]
same problem here, buddy. try wled 0.8.5. thats the only version works for me

**Comment by pille** [comment]
may be related to #946. check the workaround.
