### ISSUE TITLE
only WLED_0.8.5_ESP8266.bin works on my device

### ISSUE THREAD

**Issue by dogson3006** [Aircoookie/WLED#946]
hi, 
my problem is, that only WLED_0.8.5_ESP8266.bin works on my device.
 if i flash for example WLED_0.10.0_ESP8266.bin, i can find the AP. but if i type in my data to local wlan,  it didnt connect correctly.
 the device will shown in the list of my router,  but when i try to connect to the displayed IP, no gui appears and the error running out of time.
plz give me a hint
thank you

**Comment by SimState** [comment]
Same here! only 0.8.5 works...

**Comment by Legsmaniac** [comment]
> if i flash for example WLED_0.10.0_ESP8266.bin

Instead of flashing WLED_0.10.0_ESP8266.bin, have you tried updating to WLED_0.10.0_ESP8266.bin via OTA from the UI?  Doing that should maintain your settings with no need to use AP

**Comment by aryedevops** [comment]
I have had the same issue with earlier versions - and ONLY 0.8.5 works!! I was getting disconnected all the time and getting RED messages all over. I wonder why?

**Comment by Aircoookie** [comment]
Hi everyone! I suspect that this issue is due to the Arduino core version, not any changes to WLED.
Here is the latest version compiled with core `2.5.2`, same as 0.8.5:
https://drive.google.com/open?id=1g-5s3WtJ_VgGq-oSdHazuABUNJBskd1i
Let me know if that works better!

**Comment by dogson3006** [comment]
> 
> 
> > if i flash for example WLED_0.10.0_ESP8266.bin
> 
> Instead of flashing WLED_0.10.0_ESP8266.bin, have you tried updating to WLED_0.10.0_ESP8266.bin via OTA from the UI? Doing that should maintain your settings with no need to use AP

good idea. but i did this the first time to update to new version. after selecting the file, the update starts and a message said: update successfull, rebooting. after that i ll cant connect again. same error. 
ip is given from router but the gui will not open. allways: running out of time.

**Comment by dogson3006** [comment]
> 
> 
> Hi everyone! I suspect that this issue is due to the Arduino core version, not any changes to WLED.
> Here is the latest version compiled with core `2.5.2`, same as 0.8.5:
> https://drive.google.com/open?id=1g-5s3WtJ_VgGq-oSdHazuABUNJBskd1i
> Let me know if that works better!

thanks man, you are the best. this version works perfectly.

**Comment by velidhu** [comment]
i think the problem was that it didn't change wifi settings if the esp had been used for other projects. with a new esp no problem. with the new core it also works on recycled esp

**Comment by pontos-dev** [comment]
@Aircoookie It work's with that binary you linked to :)
Thx

**Comment by acorn1sh** [comment]
> Hi everyone! I suspect that this issue is due to the Arduino core version, not any changes to WLED.
> Here is the latest version compiled with core `2.5.2`, same as 0.8.5:
> https://drive.google.com/open?id=1g-5s3WtJ_VgGq-oSdHazuABUNJBskd1i
> Let me know if that works better!

So I have noticed that this binary is flashing when I choose an effect. I loaded 10.0 and I have no flashing but when I use this file my lights will flash like issue #230. If I choose a solid color it seems to be fine.

**Comment by jonhawkes** [comment]
I needed this to stop the web front end hanging for me. Works fine.
