### ISSUE TITLE
LOLin Wifi Issue

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#947]
So I setup my Wifi Kit 8, no problems at all.

I do the same for my LOLin, flashes, I do the setup... then nothing, nothing will find the board, seems as soon as setup and hard rest is done, its like the device has been wiped, so i reflash... same thing again, Iv noticed its when i change either .local name or wifi device name.

**Comment by mike2nl** [comment]
@Doyle4 
Try to use a real IP address and NOT the .local DNS part. Dpending on your router the DNS won't work. It is a known issue with many router because wrong DNS implementation.

**Comment by Doyle4** [comment]
I will give this a try.

I did however spot was going wrong. Its not the board erasing, the SSD is hidden even when unticked, not sure if its a bug or is meant to be like this.
