### ISSUE TITLE
433 MHz receiver support?

### ISSUE THREAD

**Issue by vtni** [Aircoookie/WLED#956]
Hi there,
it would be great if we could turn WLED on/off or change effects through a 433 MHz remote. Is something like this planned?

**Comment by Aircoookie** [comment]
Hi,
no that isn't planned right now for the core of WLED. However you can add support using an usermod :)

**Comment by Legsmaniac** [comment]
Just curious but why would you need that when you have the app?  🤔

**Comment by vtni** [comment]
> 
> 
> Just curious but why would you need that when you have the app? 🤔

I wanted to build a wireless button (without any hub) that isn't connected to the wifi.

**Comment by Legsmaniac** [comment]
Fair point.  
Just wondered because you'd still need to be within range for 433Mhz to work and so the same could be said for using AP which wouldn't rely on WiFi connection to your router.  Kinda the same thing in a way but with all the functions.

**Comment by vtni** [comment]
That's right and my first idea was to use an ESP as a button, however if it is not connected all the time, it will take some seconds until connected to the wifi. And i wanted to avoid delay. Deep Sleep would also not help in that case.

**Comment by Legsmaniac** [comment]
> it will take some seconds until connected

Ah yeah, good point.  Fair enough.  Thanks.
