### ISSUE TITLE
SOUND SENSOR

### ISSUE THREAD

**Issue by renanbarbalho** [Aircoookie/WLED#959]
Hello, do we have any function to add a sound sensor to the LED?

**Comment by raoulteeuwen** [comment]
Do you know of https://github.com/scottlawsonbc/audio-reactive-led-strip ? It's a fork of WLED. I did not now adding sound took a bit more than a sound sensor and a few lines of code :-).

**Comment by Aircoookie** [comment]
https://github.com/atuline/WLED is the awesome fork with built in sound effects and microphone support. It will be merged into the WLED master at some point soon :)

**Comment by raoulteeuwen** [comment]
Sorry for linking to the wrong project...

**Comment by Aircoookie** [comment]
No worries, the audio reactive led strip project is also cool!

**Comment by renanbarbalho** [comment]
Thanks a lot, I'll wait for merged into the WLED master.
