### ISSUE TITLE
publish IR codes received to mqtt

### ISSUE THREAD

**Issue by StevenG929** [Aircoookie/WLED#962]
Is there a way to publish the hex values that are sent to the serial port to MQTT so home automation systems can use them?

**Comment by Aircoookie** [comment]
Not built in, but you could add an MQTT publish to the `decodeIR` function in ir.cpp.
Something like (untested!)
```cpp
if (WLED_MQTT_CONNECTED) {
  char s[16];
  char subuf[38];

  sprintf(s,"0x%08x",code);
  strcpy(subuf, mqttDeviceTopic);
  strcat(subuf, "/ircode");
  mqtt->publish(subuf, 0, true, s);
}
```
