### ISSUE TITLE
Arduino nano vu meter

### ISSUE THREAD

**Issue by phantom2438** [Aircoookie/WLED#967]
I am thinking about building the Arduino Nano stereo Vu Meter by Cine-Lights (Youtube) video and I am wondering how this works. If I plug the vu meter into my phone or any other device via AUX cable, would I still hear the music or how does this work?

**Comment by Aircoookie** [comment]
No, you wouldn't by default, but there are simple aux splitters you can buy for less than a dollar (I believe their primary use is airplanes), so you can feed the signal both to the VU meter and a speaker/headphones.
I believe the sound reactive fork of WLED has a VU meter support, but I don't know if it supports the different FFT channels. Best to ask the guys themselves in the `#soundreactive` Discord!
