### ISSUE TITLE
More than 700 lights 

### ISSUE THREAD

**Issue by Brywes03** [Aircoookie/WLED#972]
I am brand new to this and can't figure out what I am doing wrong.       But after I connect a third strand of lights and change the number of lights to 900, the app says redirecting and than all the lights shut off

**Comment by Aircoookie** [comment]
Hi, welcome to WLED!

I believe this might be the automatic brightness limiter limiting the brightness to nothing with its default `850mA` limit. Just enter your LED power supply amp rating in the `Maximum Current` field in LED settings and it should work :)

**Comment by Brywes03** [comment]
Thanks.   That was it
