### ISSUE TITLE
XML Secondary Color Support

### ISSUE THREAD

**Issue by Shaegi** [Aircoookie/WLED#98]
Hello,
first of all awesome project! Loving working with it so far. 

It would be great if the secondary color is also provided as response of the api calls. 

Hopefully you can help me out there.

**Comment by Aircoookie** [comment]
Thank you! Not a problem, I can add this in the next version!

**Comment by Shaegi** [comment]
Sorry for the long response time. Thanks for adding secondary color, works just fine.
CORS still makes problems...Even with the updated version I will the same CORS errors mentioned.
