### ISSUE TITLE
Add LO= to HTTP API

### ISSUE THREAD

**Issue by alborzs** [Aircoookie/WLED#980]
I am trying to control a led strip from two different interfaces, **E1.31 (DMX)** (via xlight) and **MQTT** running on a ESP32.

Ideally there would be a way to disable DMX via a MQTT message and then later enable it, but I have not been able to find such a feature in the current MQTT implementation.

If this feature is considered outside the scope of near releases, please point me in the right direction (where should I start changing the code) regarding implementing this myself.

**Comment by Aircoookie** [comment]
Hi, yes, `lor` is used to toggle on an off the acceptance of E1.31 data.
WLED will always listen to MQTT, just that e.g. color changes will have no effect because the E1.31 data is displayed. With return to stream I mean that once `lor` is set to 0, the E1.31 data will be displayed again :)

**Comment by pille** [comment]
how about introducing a (configurable) priority, so a user can define which protocol wins over others? it may be a top-down-list where higher positions override lower ones.

**Comment by alborzs** [comment]
Sounds like a good idea as long as the priority can be changed on the fly, over mqtt or HTML API

**Comment by drinfernoo** [comment]
This does appear to be implemented and working now, in case anyone couldn't figure it out... It's not in the docs 😅

**Comment by drinfernoo** [comment]
I've added it to the docs apparently... expected it to ask me for a PR 😅 

https://github.com/Aircoookie/WLED/wiki/HTTP-request-API/_compare/41ae7f8fb0457bc357e9a8a9480b834259a7630b...885567599259c05bc9f5f12e9b5bddd8f0b8f2b1
