### ISSUE TITLE
Segment enhancements

### ISSUE THREAD

**Issue by ToXIc-Dev** [Aircoookie/WLED#982]
Would be great to have a button to quickly delete all segments.

It also would be great to have a segment that can override the rest (give it a little checkbox like the reverse direction one), so we can easily set the whole strip without deleting segments.

Both would be very useful.

**Comment by mike240se** [comment]
> @ToXIc-Dev I agree with both of your suggestings! Adding a reset button is a great idea. I believe it would be most intuitive if it deleted all but one segment and set that segment to fill the entire strip.
> For overriding, I'm actually planning that segments with a higher number will be layered above the others, so if I get that to work, that feature will also be possible!
> 
> @mike240se that is currently possible, although not necessarily intuitive. Just added it to the FAQ: https://github.com/Aircoookie/WLED/wiki/FAQ#my-segments-are-gone-after-a-reboot

Excellent!  thank you.  I have one long strip but it covers 2 distinct areas of my yard so I have it broke into segments so i can have a different display in different areas.  Setting up the segments after every reboot was a pita so this is a great tip! thanks!

**Comment by codamo35** [comment]
> For overriding, I'm actually planning that segments with a higher number will be layered above the others, so if I get that to work, that feature will also be possible!

By layering, are you meaning having the ability to stack multiple effects over the same segment of strip? That would be great!! Possibly even done by having a "Stack" or an "Add" checkbox.
"Stack" : segments layer on top of each other, and lower segment numbers only show through areas with black pixels on higher segments.
"Add" : segments layer, and colors add together on pixels with multiple effects addressing simultaneous points.

Just throwing out some ideas ;)

**Comment by ogodich** [comment]
> @ToXIc-Dev I agree with both of your suggestings! Adding a reset button is a great idea. I believe it would be most intuitive if it deleted all but one segment and set that segment to fill the entire strip.
> For overriding, I'm actually planning that segments with a higher number will be layered above the others, so if I get that to work, that feature will also be possible!
> 
> @mike240se that is currently possible, although not necessarily intuitive. Just added it to the FAQ: https://github.com/Aircoookie/WLED/wiki/FAQ#my-segments-are-gone-after-a-reboot

Nice to hear that! I need to swhitch on and off a segments like a layers!

**Comment by blazoncek** [comment]
Numerous enhancements to segments were added in 0.13.
Closing.
