### ISSUE TITLE
Transition lag when using multiple segments

### ISSUE THREAD

**Issue by ToXIc-Dev** [Aircoookie/WLED#985]
Im using an ESP32 and a 60 LED SK6812 strip and the fade transition (power on/off, brightness) lags when using 3 segments.

I could've sworn this didn't happen at first but its happening now and I haven't changed anything.

**Comment by ToXIc-Dev** [comment]
I erased the flash using esptool and reflashed WLED and now it fades smoothly, no idea why it happened though.

**Comment by ToXIc-Dev** [comment]
So I have found out that when the segments are saved to slot 16 is when the transition fade starts to happen.

**Comment by ToXIc-Dev** [comment]
I tried two segments (each 30 LEDs) saved to slot 16 and it fades just fine

**Comment by Aircoookie** [comment]
I'm having a bit of trouble visualizing the lag you are experiencing... Can you send a video of the LEDs when it occurs?

**Comment by ToXIc-Dev** [comment]
So it appears to be only after saving 3 segments to slot 16 and then rebooting, then if I load slot 16 and turn it on/off or change brightness it happens, here is a video.

https://gfycat.com/finefearfulaxolotl

**Comment by Aircoookie** [comment]
Thank you for getting back to me with a video so quickly!
Right after reboot a 2 second lag is normal while the WiFi initializes. But a lag after manually loading slot 16 is not something that should ever happen. It appears so from the video, but just to confirm, the segments are all on Solid, correct?

**Comment by ToXIc-Dev** [comment]
Yes, they are on solid.

**Comment by Aircoookie** [comment]
I believe I was able to reproduce this.
Had a hard time finding this bug, because it only occurs if both Segment 0 has been deleted and the segments are read from the preset slot! Should luckily be an easy fix though!

**Comment by ToXIc-Dev** [comment]
> I believe I was able to reproduce this.
> Had a hard time finding this bug, because it only occurs if both Segment 0 has been deleted and the segments are read from the preset slot! Should luckily be an easy fix though!

Props for finding it so quickly, great work as usual.

Glad it's an easy fix and nothing to do with my esp. :)

**Comment by Legsmaniac** [comment]
Wow!  Such dedication, persistence and patience to your software and your user base.  Something that is so very rare to be seen in Devs.  Many Devs would have just said "Nothing wrong with my code, it's your setup." and that would be the end of it.
Kudos Mr @Aircoookie Boss Man Sir!

![](https://media1.giphy.com/media/iiS84hOJXh1Pq/giphy.gif?cid=5a38a5a26d911a2d6e0b87c52020938e4ec5e6ab9ecfaadd&rid=giphy.gif)

**Comment by Aircoookie** [comment]
@Legsmaniac thank you! I want everyone to have a great experience using WLED - If I'd just develop it for myself, I would not have put it up on GitHub 😂
