### ISSUE TITLE
Relay Module Low Level trigger

### ISSUE THREAD

**Issue by JerryLutor** [Aircoookie/WLED#986]
How to connect an inverted relay?

Changing the mode does not help.

The relay is this:
![Hb63fdca486294c118d33628f93db67a0z](https://user-images.githubusercontent.com/7032814/84566774-780eb080-ad7c-11ea-8061-9995c66391d3.jpeg)

**Comment by raoulteeuwen** [comment]
If i understand you correctly, i had a similar situation, and Aircookie explained how to solve and even supplied a firmware: https://github.com/Aircoookie/WLED/issues/631#issuecomment-605512524 . You can also order relays with a dip switch so you can change behaviour. Also see https://github.com/Aircoookie/WLED/wiki/Control-a-relay-with-WLED .

**Comment by lancer199135** [comment]
I'm not sure if my relay is setup right. It turns on and off, but WLED still shows estimated usage around 250ma when off. Getting same reading on a strip with no relay.

**Comment by raoulteeuwen** [comment]
Maybe share a picture showing the wiring? And what firmware are you running exactly? Do you have a multimeter?

**Comment by lancer199135** [comment]
Not sure how to diagram like the ones I see online. I do have a meter, for some reason it will read volts in DC but amps it stays at AC. I've checked while it's off and it reads nothing. When on I'm getting about .1a. I have a logic level shifter thrown in but basically wiring is relay signal side going to esp8266 pin d6 with 5v power and ground commented. Power going to NO on relay and then out to the led strip. DR on ESP8266 to DIN on LED strip. The relay is turning on and off. I'm just wondering if the WLED app should be reading zero or not. On 0.10.0.
