### ISSUE TITLE
Remember the last state 

### ISSUE THREAD

**Issue by JerryLutor** [Aircoookie/WLED#987]
Can you add memorization of the last state before turning off the power?

**Comment by pille** [comment]
good idea. this should be implemented, once settings are stored in SPIFFS instead of EEPROM to protect the flash, as it would need to write often.

**Comment by Puntoboy** [comment]
Has this been fixed? Mine is forgetting the last state.

**Comment by Moustachauve** [comment]
Any chance this could be done? At least to remember the power state after a power outage would be great (If it was ON, turn on led on startup, otherwise leave them off if they were off when powered down)
