### ISSUE TITLE
Hue ID

### ISSUE THREAD

**Issue by salopette** [Aircoookie/WLED#993]
Hallo, im WIKI steht man muss numerische ID des Farbtonlichts eingeben, 

aber wo muss man das eintragen?
![sshot-1](https://user-images.githubusercontent.com/32480002/84592594-19623900-ae47-11ea-9f7e-d9126bba4e86.jpg)

**Comment by Aircoookie** [comment]
Hi!
Das stimmt, die ID lässt sich in der About/"Über" Kategorie in der Hue-App finden. Die ID des Lichtes, zu dem Du das WLED-Licht synchronisieren möchtest, einfach in dem allerersten Feld (nach `Poll Hue Licht`) eintragen.

P.S. Die Auto-Übersetzung ist echt komisch 🙈

**Comment by salopette** [comment]
Danke! Ich werde es versuchen!
